### ISSUE TITLE
Allow using |tojson in double-quoted HTML attributes again

### ISSUE THREAD

**Issue by joeyespo** [pallets/flask#1002]
I'm in a project where double-quoted HTML attributes is part of the style guide. We're also using data- attributes to pass data to code and consider it a bad practice to render anything directly within scripts.

Being able to remove `|safe` within `<script>` seems convenient at first glance. But after discovering that it changes the behavior of `|tojson` everywhere else when using double-quoted attributes, it doesn't seem as nice. It's just less intuitive overall. Forcing you to use a particular HTML style or requiring `|forceescape` (as opposed to just `|e`) isn't really a great tradeoff for implying `|safe` within `<script>`.

So the underlying question. Can we allow `|tojson` to work within double-quotes attributes again? Or is there some technical reason why we can't. And if not, why not add another filter to use within `<script>` blocks instead so the principal of least surprise isn't violated?

**Comment by dorianpula** [comment]
I'd like to work on this as part of the PyCon sprints.  Do we want to allow double quotes or not for the tojson filter?

**Comment by untitaker** [comment]
I'm not really sure if we want to go back after two releases. It would be nice to figure out a way to make the XSS case @joeyespo posted safe again, but catering to all sorts of styleguides while still being mostly secure is an impossible balancing act.

**Comment by davidism** [comment]
I'm fine with adding some documentation "don't put json in an html attribute, but if you do, use `|forceescape`".

**Comment by untitaker** [comment]
No, the requirement is to always use single quotes.

**Comment by davidism** [comment]
Sure, that works too.  Still seems awkward to try and shove json in an html attribute in the first place.  Are we agreeing that `tojson` shouldn't change?

**Comment by joeyespo** [comment]
It's common when using [data-* attributes](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes) to preload structured data onto the page without requiring additional AJAX calls. Particularly when mixing Flask with a front-end JS framework.

The problem is more about breaking [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Right now `tojson` works differently depending on what style quotation you use. Like Python, it doesn't (or in this case: shouldn't) make a difference if your style guide requires one or the other.

If shoving json in HTML attributes seems wildly awkward to Flask, why not favor consistency and make it break  this feature *both* places? Require `|forceescape` in single quotes too. That way there's no surprises when refactoring `<div data-field='{{ field }}'>` to `<div data-field="{{ field }}">` and vice versa.

**Comment by untitaker** [comment]
>Right now tojson works differently depending on what style quotation you use.

That is not true. The filter outputs the same thing in either case. That is like saying `{{ foo|safe }}` "works differently" based on quotation style.

>If shoving json in HTML attributes seems wildly awkward to the Flask community

No, not really.

**Comment by joeyespo** [comment]
> The filter outputs the same thing in either case.

True.

It's different *behavior* though. One quotation style breaks your front-end, the other doesn't. It's a dangerous side effect from how this is currently implemented.

**Comment by untitaker** [comment]
cc @mitsuhiko since he implemented this behavior

**Comment by mitsuhiko** [comment]
I should probably reply to this but the current filter works this way because it works in two situations: within `<script>` tags as well as within single quoted attributes. There is no way to make it work in double quoted attributes without breaking the usage in `<script>` tags and others.

**Comment by mitsuhiko** [comment]
I should clarify that i close this because changing this behavior would break lots of code in very subtle and potentially dangerous ways.

**Comment by ccbrown** [comment]
I know it's closed, but I just want to add my +1 here in case there's a possibility of this getting fixed in a major update down the road. I'm not gonna comment on proper ways to fix the issue, but I will say this: The name and function of 'tojson' don't imply to me that a different escape mechanism will be used, so it's pretty astonishing to find that `{{ '"quoted"' }}` and `{{ 'quoted'|tojson }}` are not equivalent.

**Comment by untitaker** [comment]
I'm ambivalent wrt this behavior but it takes much better arguments to change it now. Both usecases make sense.

However, I don't understand how reverting to the old behavior would break code in *dangerous* ways as claimed by @mitsuhiko

**Comment by odraencoded** [comment]
I'm way late for this but I must say it also doesn't make sense to me that `tojson_filter` calls a function called `htmlsafe_dumps` and returns an object of a type called `Markup` which has a `__html__` attribute and it's somehow not supposed to be escaped for html, but for javascript, which isn't even markup.

**Comment by ExplodingCabbage** [comment]
@odraencoded It's escaped for use in *inline script elements* - i.e. JavaScript within HTML, which is markup. So there is some logic to it.
