### ISSUE TITLE
Using encodings other than UTF-8 in Response

### ISSUE THREAD

**Issue by barosl** [pallets/flask#1005]
The Flask documentation states that Flask assumes the encoding of the response to be UTF-8.

```
the encoding for text on your website is UTF-8

From http://flask.pocoo.org/docs/unicode/
```

Does that mean we are discouraged to use the encodings other than UTF-8 in the Flask response? I was unable to find a way to change the intended encoding of neither `flask.wrappers.Response` nor `werkzeug.wrappers.Response` correctly.
1. I cannot directly pass the text to the constructor, as it calls set_data() with the UTF-8 encoding. That's because the constructor has no `charset` parameter. There is no way to change its behavior. So I should create the response object with no constructor arguments, and then assign 'utf-8' to `response.charset`, and call `response.set_data()`.
2. But still, as `content_type` is determined in the constructor, it will still be "text/html; charset=UTF-8" because the `charset` attribute is always `'utf-8'` during the object creation process. So I'm forced to pass `content_type` to the constructor, which is kinda confusing because my original intention was just changing the encoding, rather than explicitly setting the Content-Type.

Do I understand the process accurately?

If I'm right, I suggest:
1. Allow passing `charset` to the `Response` class.
2. Or, the `content_type` attribute should be updated again when the user manually sets the `charset` attribute.

**Comment by davidism** [comment]
Going to close this in favor of the options in the previous comment.
