### ISSUE TITLE
Implement jinja's ModuleLoader

### ISSUE THREAD

**Issue by ghost** [pallets/flask#101]
It would be interesting to implement ModuleLoader in flask. It would make a huge difference in GAE response times for flask applications.

**Comment by jeffwidman** [comment]
This is an ancient issue, and I'm not too familiar with Jinja2 internals. Anyone know if it's still relevant?

**Comment by jeffwidman** [comment]
@untitaker looks like you started to mark as `closing candidate` but then thought better of it, I'm curious why? At this point, I'd just close it as an ancient issue with not enough traction...

**Comment by untitaker** [comment]
@dinoboff showed how it is possible, but having ModuleLoader as a default is not very user friendly and usually not fixing the actual bottleneck.

**Comment by pernisunil** [comment]
Jinja2 templates Still Not working - Can someone help me with a fix . I am using Flask 1.0.2 and Python 3.6
