### ISSUE TITLE
incomplete formatted string expression

### ISSUE THREAD

**Issue by jarmstro** [pallets/flask#1072]
in the example code of doc page
http://flask.pocoo.org/docs/patterns/mongokit/

the formatted string expression in the exception has two %s placeholders but only one variable.
see excerpt following:
'''
Here is an example document (put this also into app.py, e.g.):

def max_length(length):
    def validate(value):
        if len(value) <= length:
            return True
        raise Exception('%s must be at most %s characters long' % length)
    return validate
'''

**Comment by jarmstro** [comment]
in the second code example in 'declarative' section of
http://flask.pocoo.org/docs/0.10/patterns/mongokit/

in the   validate(value)     function,
 in the raise  statement,
   the formatted string expression has two %s placeholders but only one variable.

raise Exception('%s must be at most %s characters long' % length)

**Comment by ThiefMaster** [comment]
Good catch. And a great thing for a quick pull request (it's one of the cases where using the web-based github editor comes handy).

**Comment by ryanbackman** [comment]
Looks like this is fixed in the latest version of the docs.

http://flask.pocoo.org/docs/0.11/patterns/mongokit/

**Comment by untitaker** [comment]
Yes, thank you.
