### ISSUE TITLE
Issue with module path/name in imported classes when using from...import on flask.ext.* (Python 3)

### ISSUE THREAD

**Issue by lyschoening** [pallets/flask#1092]
There is an issue when importing something inside an extension using Python 3 where Flask imports the classes in such a way that they are no longer equal to the same classes imported inside the extension. The issue occurs when importing from a submodule of an extension using `from flask.ext.xxx.yyy import zzz`. 

The classes imported using from-import get masked as `<class 'flask.ext.xxx.yyy.zzz'>`, where `<class 'flask_xxx.yyy.zzz'>` would be expected.

The issue is specific to Python 3.

Example:

```
Python 3.4.0 (default, Apr  9 2014, 11:51:10) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask.ext.restful.fields import String
>>> from flask_restful.fields import String as String_internal
>>> String == String_internal
False
>>> String
<class 'flask.ext.restful.fields.String'>
>>> String_internal
<class 'flask_restful.fields.String'>
>>> import flask.ext.restful
>>> import flask_restful
>>> flask.ext.restful.fields.String == flask_restful.fields.String
True
>>> flask.ext.restful.fields.String
<class 'flask_restful.fields.String'>
>>> flask_restful.fields.String
<class 'flask_restful.fields.String'>
```

**Comment by taion** [comment]
I just unexpectedly hit the same issue. Should https://github.com/mitsuhiko/flask/pull/1220 be considered normative now, or not until it actually gets merged?

**Comment by davidism** [comment]
Yes, import directly from the package you installed, do not use the `flaskext` namespace package or the `flask.ext` import helper.

**Comment by taion** [comment]
Great, thanks.

**Comment by jeffwidman** [comment]
Closing this as Flask 0.11 added a runtime warning that the `flask.ext` namespace is deprecated. So it's no longer easy to miss.
