### ISSUE TITLE
Let's kill run

### ISSUE THREAD

**Issue by DasIch** [pallets/flask#1102]
In order to run a Flask application during development we have the `.run()` method or with 1.0 `flask run`. While both are convenient they are a bad idea.

First of all their naming implies that, they are used for running a Flask application, they aren't. They are for running a Flask application during development, a subtle but important difference that causes significant confusion. Apart from that though, running a Flask application is never what you want.

Instead you want to *develop*, *test* or *deploy* an application. While development and testing can imply running a web server, running a web server during development means something different than running a web server during testing. In deployment you don't actually want to run your application at all, you should let a web server do that.

So far we kind of allow people to signal their intent with DEBUG and TESTING, but this needs to be explicitly configured by every user and issues such as #1049, show that this is not without issues.

Therefore what I would like to propose is to create three commands `develop`, `test` and `deploy`. These commands should be extendable through extensions and users. It should be easily possible to use different configurations for these scenarios.  Extensions that are only helpful during development like Flask-Debugtoolbar could activate/deactivate themselves based on intent, Flask-Migrate could perform migrations during development and extensions dealing with assets could start background threads monitoring the file system for changes during development. It would further simply clear up a lot of confusion for newcomers.

Running flask with either of these commands should by default set `DEVELOPMENT` (for backwards compatibilty also DEBUG but let's remove that, the name is awful), `TESTING` or `DEPLOYMENT` respectively and issue a signal. Furthermore `develop` should run the development server as `run` does now. `test` and `deployment` shouldn't actually test or deploy the application as we don't want to enforce a specific test runner or deployment solution. Instead the user should be implement these, if so desired. Nevertheless they would be useful as they establish convention extensions can rely on.

I realize that such a change is probably somewhat controversial (which is why this is not a pull request), it would also distinguish us significantly from Django, which works like Flask does now. Nevertheless I think it would be a great idea and I'm curious what others think of this idea. So, thoughts?

**Comment by sprin** [comment]
Hi, just perusing the list of 1.0 issues and found this. Thought I would take 5 and send in a PR for it.

I prefer the simple approach of always printing a short warning when ``run()`` is used, then making it easy for the app developer to find the docs on using a production WSGI server. Not renaming preserves compatibility, but also gives us the opportunity to point people in the right direction in the form of the warning.

Thanks for Flask!

**Comment by zealsham** [comment]
Thanks for flask

**Comment by RonnyPfannschmidt** [comment]
`run` and `develop` are both bad choices, because all it does is `serve_http` or `serve_http --debug`

for anything that has grown you need caches, redis, queues, maybe celery and lots and lots of services to actually tun it

**Comment by justanr** [comment]
Maybe naming it `runlocal`. To me this communicates it'll run the web app but it's meant for local use only.

**Comment by jirikuncar** [comment]
I like @RonnyPfannschmidt proposal for `serve_http [--debug]`. Alternatively something similar to what @Auha proposed: `app.(web)server.start()`.

**Comment by RonnyPfannschmidt** [comment]
`app` should no longer have the method

**Comment by MartiUK** [comment]
+1

I'm with @DasIch's proposal, there's no half measures with this, even with updating documentation people will still use `.run()` in production; best to nip it in the bud.

**Comment by guyskk** [comment]
app should no longer have the method

I suggest add a comand line tool:

create a project

    flask init

run local server

    flask runserver

and so on

**Comment by miguelgrinberg** [comment]
I'm strongly -1 on removing `app.run()`. True, some people use it on production, but what's going to prevent people from running `flask runserver` on production as well?

I don't oppose having an alternative method of starting the application that eliminates the need to issue the `app.run()` altogether, but removing `app.run()` just like that seems wrong to me. Just add a warning to it, make it as scary as you want, but don't break a workflow that people have been using for ages. If you guys feel strongly about removing it, then do it properly, start by deprecating it (scary message) and wait a 2-3 releases to actually remove it.

Also, having access to method that starts the application is useful for certain kind of tests. An example is when you want to run tests with Selenium, where you need a real server running. See how I do it [here](https://github.com/miguelgrinberg/flasky/blob/579ecd9435b392df114110985f514ad173a315f2/tests/test_selenium.py#L48). Obviously this can be implemented differently if `app.run()` didn't exist, but I think it is convenient and super simple to do it this way.

Regarding renaming `run()` to something else, I think it achieves little.

**Comment by jaapz** [comment]
> First of all their naming implies that, they are used for running a Flask application, they aren't. They are for running a Flask application during development, a subtle but important difference that causes significant confusion. Apart from that though, running a Flask application is never what you want.

What about just adding a big shiny warning message when starting an app using `run`, telling people that it should not be used in production. Just completely removing it would hurt Flask in the long run I think, because it would be a pretty backwards incompatible change, outdating a lot of documentation and articles about Flask.

> app should no longer have the method
I suggest add a comand line tool:

Although off-topic, I personally like that flask is not opinionated about which project structure you should use. So I am not in favor of adding a tool that tells people how to structure their app. Also, we already have something like [cookiecutter](https://github.com/sloria/cookiecutter-flask) for that purpose.

Just my two cents.

**Comment by ThiefMaster** [comment]
> What about just adding a big shiny warning message when starting an app using run, telling people that it should not be used in production.

Should have a kwarg to disable it (or possibly an env var). It's really annoying to see the same message over and over. Just like the "be careful while driving" nonsense GPS devices in cars show at every startup you end up hating it.

**Comment by RonnyPfannschmidt** [comment]
it would be enough to name it `run_insecure_devserver` (which is a propper description) where its suddenly very apparent that such a method shouldnt be on the app
there is nothing wrong with having a api to do it, its wrong to have one thats easyly missused and abused

**Comment by davidism** [comment]
Run is dead, long live `flask run`.  Not that that actually "solves" this problem, but I don't think there's any foolproof way to protect users from themselves at this point.  I think we should close this.

**Comment by mitsuhiko** [comment]
Yeah. Run can hang around in the current form. We ship something better now :)

**Comment by RonnyPfannschmidt** [comment]
Should APP.run perhaps print a big warning
