### ISSUE TITLE
CLI: "flask" command help doesn't list custom commands

### ISSUE THREAD

**Issue by erwagasore** [pallets/flask#1124]
I am playing with the latest release of flask with <code>cli</code> module. I have created a command called <code>initdb</code> and when I call <code>flask initdb</code> it works as expected, but when I just call <code>flask</code> command it supposed to show the list of all available commands including <code>initdb</code>, which is not the case. Any idea why?

**Comment by betterenvi** [comment]
try the following command:
pip install https://github.com/mitsuhiko/flask/tarball/master
ref: https://github.com/mitsuhiko/flask/issues/1048

**Comment by davidism** [comment]
@betterenvi that's not related, this is about the behavior of the command, not how to get the command in the first place

**Comment by mitsuhiko** [comment]
I'm closing this for now as the latest changes implicitly fixed this.
