### ISSUE TITLE
Deprecate flask.ext and create migration tool to flask_*

### ISSUE THREAD

**Issue by DasIch** [pallets/flask#1135]

**Comment by keyanp** [comment]
I'd like to try to tackle this. Just to get some clarification, the proposed migration tool would essentially search old sourcecode and replace instances of `import flask.ext.foo` with `import flask_foo`, am I understanding this correctly?

**Comment by ThiefMaster** [comment]
Yes. It would have to cover these imports (unless I missed anything):

```
from flask.ext import foo
from flask.ext.foo import <anything
import flask.ext.foo
```

**Comment by keyanp** [comment]
And the aforementioned imports would be replaced with what?

**Comment by ThiefMaster** [comment]
flask.ext.foo => flask_foo

**Comment by untitaker** [comment]
Exactly what ThiefMaster said. Thanks for giving this a try!

>And the aforementioned imports would be replaced with what?

* ``from flask.ext import foo`` => ``import flask_foo as foo``
* ``from flask.ext.foo import bam`` => ``from flask_foo import bam``
* ``import flask.ext.foo`` => We'd have to rewrite any reference to ``flask.ext.foo`` in the code further below. If that's too hard, just skip those and show a warning.

**Comment by davidism** [comment]
If you can actually evaluate the import, you could try to figure out the actual package name, rather than guessing that it's `flask_<name>`.

**Comment by untitaker** [comment]
True, but then you'd be dependent on whether the migration script is running in the correct virtualenv, and things like that. Also I don't think anybody actually uses ``flaskext`` extensions anymore.

**Comment by lepture** [comment]
Let's correct every answers on <http://stackoverflow.com/search?q=flask.ext>, and encourage users to use `flask_foo` instead of `flask.ext.foo`.

There are many Flask extentions whose documentation contains `from flask.ext.foo import bar`. We should encourage the developers to change the documentation. For example: https://pythonhosted.org/Flask-Testing/

**Comment by keyanp** [comment]
@lepture that's certainly ambitious, I think it would be nice to resolve #1367 and #1366 before doing something like that. The current documentation still suggests using the `.ext` format. It will be easier to encourage a transition once the docs are fixed and use of the migration tool is fully supported and documented.

**Comment by lepture** [comment]
@keyanp in the meanwhile, we should notify Flask extention developers. Their documentations would also confuse users.

**Comment by keyanp** [comment]
@lepture sure, we can certainly try to let some developers know, alerting **all** extension developers is probably unrealistic.

**Comment by lepture** [comment]
@keyanp that's what I am doing. I will do a search on [these projects](https://github.com/pocoo/metaflask/tree/master/projects), find out who should be notified.

**Comment by keyanp** [comment]
Figured I would at least change pocoo documentation regarding it.

**Comment by untitaker** [comment]
@lepture thanks for notifying extension authors!

**Comment by untitaker** [comment]
cc @DasIch

**Comment by jeffwidman** [comment]
#1484 made the deprecation explicit in the docs and added runtime warnings if you try to import `flask.ext.*`. 

While a migration script might be convenient, I don't think it's necessary for most projects. I've migrated multiple Flask projects to the new format using a simple find-and-replace for `flask.ext.` to `flask_`.

Are we okay to close this issue?
