### ISSUE TITLE
Modify docs for new testsuite

### ISSUE THREAD

**Issue by MikeiLL** [pallets/flask#1180]
I tried viewing some of the bundled docs with https://www.tele3.cz/jbar/rest/render.py and restview. Both returned errors.

Are there docs somewhere that would apply to latest version of test_flaskr which uses pytest?

[This one](http://flask.pocoo.org/docs/0.10/) uses unittest.

**Comment by rhgraysonii** [comment]
@ThiefMaster one the note of `pytest-flask` that seems like something that wouldn't be too huge an undertaking. I'm personally a huge fan of the project myself and looking to get involved. Has anyone made efforts or put research toward this?

**Comment by RonnyPfannschmidt** [comment]
its only on my watch list, but i'd be more than happy to help with the pytest knowledge

i can be found in #pylib on freenode

**Comment by untitaker** [comment]
Exactly because it wouldn't be a huge undertaking, I am unsure what such a pytest helper would provide. If we're going to include pytest in the docs, I'd like to keep it vanilla to be more easily translatable to other testrunners.

**Comment by RonnyPfannschmidt** [comment]
not a chance for that, the real power behind pytest are features that no other testrunner has to begin with ^^

**Comment by untitaker** [comment]
My point is that it'll make it even harder to translate if we're hiding logic in third-party plugins.

**Comment by jeffwidman** [comment]
Big fan of `py.test`, and have no issues if the core Flask docs include vanilla `py.test` examples. 

> My point is that it'll make it even harder to translate if we're hiding logic in third-party plugins.

Agreed.
I looked into using some of the third-party plugins that integrate `py.test`/`flask` when I switched my main Flask/SQLAlchemy-based app over to `py.test` and decided to forgo them. Haven't missed them yet. 

I do think the Flask examples of `py.test` integration should illustrate using `py.test` fixtures... if you illustrate it without using external plugins, then it's still pretty straightforward to translate them back to `UnitTest`.

**Comment by untitaker** [comment]
Probably using fixtures is fine if we explicitly state that pytest isn't the only testing framework out there.

On 8 April 2016 09:09:48 CEST, Jeff Widman <notifications@github.com> wrote:
>Big fan of `py.test`, and have no issues if the core Flask docs include
>vanilla `py.test` examples. 
>
>> My point is that it'll make it even harder to translate if we're
>hiding logic in third-party plugins.
>
>Agreed.
>I looked into using some of the third-party plugins that integrate
>`py.test`/`flask` when I switched my main Flask/SQLAlchemy-based app
>over to `py.test` and decided to forgo them. Haven't missed them yet. 
>
>I do think the Flask examples of `py.test` integration should
>illustrate using `py.test` fixtures... if you illustrate it without
>using external plugins, then it's still pretty straightforward to
>translate them back to `UnitTest`.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/1180#issuecomment-207262987

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davidism** [comment]
#2286 #2307
