### ISSUE TITLE
Need more documentation for usage of instance_path

### ISSUE THREAD

**Issue by jgonggrijp** [pallets/flask#1249]
There is one short section on instance paths in the configuration handling doc, but nothing else. I have questions like the following:

> Suppose I want to separate the application package, the instance directory and the configuration file. In other words, I want all three to be in different locations within the filesystem and I don't want those locations to be hard-coded in the package. The WSGI script should load the application factory from the package and pass the instance path and the configuration file to the factory, after which the factory returns an application object. The application and some of the blueprints registered on it should use the instance directory for uploads but not for configuration. How should I write my code in order to realize that?

Please help me find the answer to the question above, and please consider providing more documentation on the instance path!

**Comment by schjak** [comment]
I think have the same issue or lack of understanding. In the docs there is an example:

Flask(__name__, instance_path='/path/to/instance/folder')

But I guess you would never actually hardcode this value in your code since that would impose a specific directory structure on the server.

I image it should be more dynamic - for instance:

Flask(__name__, instance_path=os.environ['MY_FLASK_APP_INSTANCE_PATH'])

But I am unsure if this is the proper way to go about it (probably because I am a novice to both Flask and web servers).

**Comment by jsonbrazeal** [comment]
working on this at #pycon2016 sprints

**Comment by jsonbrazeal** [comment]
After looking at this issue, it seems that the original poster's case is too specific to be included in the docs as untitaker mentions. For schjak's comment on making the path dynamic...the user is free to implement this and use dynamic paths throughout the flask configuration, but how to change a hardcoded path to an environment variable probably doesn't belong in the instance_path documentation.

**Comment by jeffwidman** [comment]
Agreed

**Comment by untitaker** [comment]
@schjak Flask doesn't impose any best practices on you. You can use a `ini`-like configuration and read your variables from there, environment variables, ... whatever the other tools work best with.

**Comment by jgonggrijp** [comment]
Excuse me for replying late, it appears that this thread escaped my attention back in 2014-2015. I did what @untitaker suggested with the snippet of code: add parameters to the app factory that specify the configuration file and the instance path independently. Thank you for that solution.

In my opinion, making an app factory with the instance path and the configuration as parameters is nearly always a good idea. Maybe it is not a universally best practice, but at least is it a generally good practice. My use case was not "specific"; I was trying to separate concerns and make my application portable. Therefor, I would encourage you to prominently include this in your documentation.
