### ISSUE TITLE
Calling redirect() from Blueprint#before_app_request() 

### ISSUE THREAD

**Issue by fmoo** [pallets/flask#1257]
Calling `flask.redirect()` or returning data from a callback passed to `Blueprint#before_app_request()` are ignored, despite the callback executing.

`Flask#before_request()` and `Blueprint#before_request()` both appear to work as intended, redirecting and/or handling the request as appropriate.

It's not immediately clear from reading the inline documentation that this particular behavior is intended.  The only documentation I can find on the matter is on `Flask#preprocess_request()`, which doesn't really touch on Blueprint behavior:

```
    """Called before the actual request dispatching and will
    call every as :meth:`before_request` decorated function.
    If any of these function returns a value it's handled as
    if it was the return value from the view and further
    request handling is stopped.

    This also triggers the :meth:`url_value_processor` functions before
    the actual :meth:`before_request` functions are called.
    """
```

Is this a bug or just an undocumented / intended behavior?

**Comment by untitaker** [comment]
I think it's undocumented behavior. Better ask @mitsuhiko what he wants.

**Comment by davidism** [comment]
This appears to have been fixed at some point.
