### ISSUE TITLE
Slash in route affects sorting/matching order

### ISSUE THREAD

**Issue by nicolas-garcia** [pallets/flask#1265]
Hi !

I'm in trouble since a moment using Flask with that point.
I'm registring 2 url rules in a blueprint :

``` python
class MyClass(Blueprint):
    def setup(self):
        self.add_url_rule('<service>.<ext>', view_func=service_call)
        self.add_url_rule('networks.<ext>', view_func=networks)
```

I've read somewhere that the rule with the less number of parameters is taken in routing.
But, when I'm typing /networks.json, I'm in the `service_call()` function, not in `networks()`
When I print the `url_map` :

``` python
Map([ <Rule '/v1/<service>.<ext>' (HEAD, OPTIONS, GET) -> v1.service_call>,
 <Rule '/v1/networks.<ext>' (HEAD, OPTIONS, GET) -> v1.networks>,
 <Rule '/static/<filename>' (HEAD, OPTIONS, GET) -> static>])
```

After some tests, it seems that following code is working as expected :

``` python
class MyClass(Blueprint):
    def setup(self):
        self.add_url_rule('<service>/<ext>', view_func=service_call)
        self.add_url_rule('networks/<ext>', view_func=networks)
```

So, the dot isn't considered as a "separator" ?
Is there a way to fix that ?

Thanks in advance for your help !

**Comment by mreinhardt** [comment]
I think this is a Werkzeug issue, specifically with https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/routing.py I think. You should probably submit it to https://github.com/mitsuhiko/werkzeug/issues

**Comment by davidism** [comment]
This is a Werkzeug issue, already reported at pallets/werkzeug#727.
