### ISSUE TITLE
Thoughts about the fabric docs

### ISSUE THREAD

**Issue by dag** [pallets/flask#129]
Maybe use of one of these should be suggested:

    setup.py egg_info ...
    --tag-svn-revision (-r)  Add subversion revision ID to version number
    --tag-date (-d)          Add date stamp (e.g. 20050528) to version number
    --tag-build (-b)         Specify explicit tag to add to version number

A problem with this is that ``setup.py --fullname`` does not include the tag. Not really an issue with ``-b``, a useful value might be ``git log -1 --format=%h`` for example.

Another thought: why go through all that trouble to extract the tarball?

    easy_install myapp.tar.gz

Also: why not call ``pack()`` in deploy?

**Comment by jeffwidman** [comment]
For future reference (since I just looked it up) the Fabric docs are here: http://flask.pocoo.org/docs/dev/patterns/fabric/

**Comment by SkiftCreative** [comment]
The PR I submitted updates the docs and seems to take care of these cases.

**Comment by davidism** [comment]
Addressed the "why unpack it" point here: aa9a994946acf45187cb12506b47433306aa3473.  Uses pip to install the package now.
