### ISSUE TITLE
Make it easier to serve 304 (Not Modified) using a database file.

### ISSUE THREAD

**Issue by flying-sheep** [pallets/flask#1321]
Currently, i have to do this if i want to simply reply 304.

given an object `f` with the fields `mime`, `modified` and `data`:

```python
rv = send_file(BytesIO(f.data), mimetype=f.mime)
rv.last_modified = f.modified.timestamp()
return rv.make_conditional(request)
```

using python 2, this would be worse, as it is most times:

```python
rv.last_modified = (f.modified - datetime(1970, 1, 1)).total_seconds()
```

i’d like to have a way to make use of a `datetime` object or POSIX timestamp in combination with the existing `conditional` argument to `send_file`. a way that one can use without having to discover `last_modified` and `make_conditional` both, e.g. (`last_modified` can be a `datetime` or timestamp):

```python
return send_file(BytesIO(f.data), mimetype=f.mime,
                 conditional=True, last_modified=f.modified)
```

Docs
----
the documentation to the `conditional` parameter would be extended to mention that `last_timestamp` has to be supplied if the first argument is a file handle instead of a name.

Implementation
--------------
we could create a helper function:

```python
def to_timestamp(da_ti):
    if PY2:
        epoch = datetime(1970, 1, 1, tzinfo=da_ti.tzinfo)  # use tzinfo to ensure subtractability
        return (da_ti - epoch).total_seconds()
    else:  # we do require python 3 >= 3.3, right?
        return da_ti.timestamp()
```

**Comment by untitaker** [comment]
Instead of your Python 2 variant, there's also this:

    int(dt.strftime("%s"))

Honestly this seems too trivial for me to warrant the complication of the API.

**Comment by flying-sheep** [comment]
true, but damn,  time → str → int is ugly!

i’d rather have a convoluted hack than a straightforward-looking one that goes via serializing ad unserializing

**Comment by untitaker** [comment]
Maybe the last_modified property could simply accept datetime objects?

**Comment by flying-sheep** [comment]
that was my idea, sorry if this was unclear. the “helper function” i mentioned was for internal use.

**Comment by untitaker** [comment]
That seems totally fine then, and I'd like to see a PR! However, please make sure that retrieving the value of ``last_modified`` always returns the same type.

**Comment by prachikhadke** [comment]
As per https://github.com/pallets/werkzeug/blob/master/werkzeug/wrappers.py#L1740, last_modified is a Datetime. My current tests are failing locally as the int value I set gets typecast to Datetime

**Comment by jeffwidman** [comment]
@untitaker should this issue be closed or should Werkzeug be modified?

**Comment by untitaker** [comment]
As far as I understand this issue was only about *passing* a datetime to last-modified, not *reading*.

**Comment by untitaker** [comment]
In other words, if we can set `last_modified` to a datetime already, then the goal of this issue is already fullfilled!

@flying-sheep ?

**Comment by flying-sheep** [comment]
if this works for an “f” with a `modified: DateTime` field, then yes:

```py
rv = send_file(BytesIO(f.data), mimetype=f.mime)
rv.last_modified=f.modified
return rv.make_conditional(request)
```

**Comment by davidism** [comment]
~~~python
rv = send_file(BytesIO(b'hello'), mimetype='text/plain')
rv.last_modified = datetime.utcnow()
return rv.make_conditional(request)
~~~

This works.  Are we ok with not having a `last_modified` argument for `send_file`?  Seems like it would be useful.

**Comment by flying-sheep** [comment]
it would yes. i’d prefer it to setting an attribute.

**Comment by untitaker** [comment]
Seems sensible, but we should have some sort of idea or a ruleset for what should be an argument and what an attribute.
