### ISSUE TITLE
sessions not saved when streaming

### ISSUE THREAD

**Issue by kneeke** [pallets/flask#1348]
When streaming, changes to the session object at the start of the request 
processing are never saved at all, the moment template rendering starts, a new 
session object is created which is then saved.

The statement on IRC was first that this is due to the fact that sessions (by default) are stored client side, and can not change anymore after the headers are send.
This is only true for sessions that are stored client side, if the sessions are server side it should be possible to change (and save) them during the whole request/response.
The real problem here seems to be that a new session is created when the stream starts.

We used the following example to stream contents: http://flask.pocoo.org/docs/0.10/patterns/streaming/

For now a workaround is to explicitly save the session after modifying, before rendering the template / starting the stream.

Expected output is always the same, one time session open and one time session save.
In the stream example the output is different; 2 sessions are opend, the first one is the one that changes, but the second one (this is opened when the stream starts) is the only one that is saved.

**Comment by kneeke** [comment]
Example again, with correct identation
```
from flask import Flask, Response, stream_with_context, session
from flask.sessions import SessionMixin, SessionInterface
from werkzeug.datastructures import CallbackDict

class Session(CallbackDict, SessionMixin):
    modified = True

class TestSessionInterface(SessionInterface):
    def open_session(self, *args, **kwargs):
        print("OPEN SESSION CALLED")
        return Session()
        
    def save_session(self, *args, **kwargs):
        print("SAVE SESSION CALLED")
    
app = Flask(__name__)
app.session_interface = TestSessionInterface()

@app.route('/return')
def returndata():
    return "SDFSDF"

@app.route('/stream')
def stream():
    def generate():
        yield "resp"
    return Response(stream_with_context(generate()))

if __name__ == '__main__':
    app.run()
```

**Comment by davidism** [comment]
Shorter example:

~~~python
import time
from flask import Flask, Response, stream_with_context, session

app = Flask(__name__)
app.secret_key = 'dev'

@app.route('/')
def index():
    session['test'] = 'a'

    @stream_with_context
    def gen():
        print(session['test'])
        yield 'flask'

    return Response(gen())
~~~

Accessing `session['test']` inside the generator raises a `KeyError` because a new session based on the initial request was opened by `stream_with_context`.

**Comment by davidism** [comment]
[These lines](https://github.com/pallets/flask/blob/0.12.2/flask/ctx.py#L332-L334) should only happen if the request is not already pushed. If `request.session` is set, it should be kept.
