### ISSUE TITLE
Include wheels on the PyPI release

### ISSUE THREAD

**Issue by prophile** [pallets/flask#1350]
It would be a nice speed increase for `pip install flask` if the PyPI release had wheel distributions.

**Comment by keyanp** [comment]
I'm guessing mitsuhiko would be okay with that: http://lucumr.pocoo.org/2014/1/27/python-on-wheels/

**Comment by mitsuhiko** [comment]
There will be wheels for 1.0.

**Comment by prophile** [comment]
:+1:

**Comment by untitaker** [comment]
This is fixed with https://github.com/pallets/flask/pull/1760
