### ISSUE TITLE
flaskr tutorial doesn't match flaskr repo

### ISSUE THREAD

**Issue by kissmygritts** [pallets/flask#1374]
This is making it difficult as I am getting an error, I check the repo and the code is completely different. This makes it difficult for a beginner.

**Comment by keyanp** [comment]
Hi @kissmygritts to help address your concern please cite specific paragraphs and sections in the tutorial, as well as line numbers in the repo files, that you don't think match. Or else whoever tries working on this will have to waste a lot of time finding what the problem even is.

**Comment by keyanp** [comment]
@untitaker Suggesting this be closed as @kissmygritts has not provided any reference point to begin address the claim.

**Comment by kissmygritts** [comment]
If you look at the flask tutorial, it mentions reviewing the code on the 4th step (http://flask.pocoo.org/docs/0.10/tutorial/dbcon/#tutorial-dbcon). However the code doesn't match what the tutorial is using (https://github.com/mitsuhiko/flask/tree/master/examples/flaskr/).

The database setup is different, on github using app.config.update(dict(...)) instead of the global variables above. That is one example, there are many more. 

Essential the Tutorial is very dissimilar to the code here in GitHub. All that needs be done is compare the tutorial to the flaskr example repo.

**Comment by gmschroeder** [comment]
@kissmygritts probably hasn't provided any reference because it's not clear if the site should be modified to resemble the github or vice versa.

**Comment by untitaker** [comment]
No, the error is clear, but I'm not sure how to fix it. The *stable* docs don't map cleanly to the *development* repository, and while that's unfortunate for the user, having development in master lowers the barrier for contribution IMO.

**Comment by omarkhd** [comment]
So how do you plan to fix this? I'd be glad to help.

**Comment by untitaker** [comment]
I don't think there's a solution (not sure why this is tagged as beginner friendly).

@omarkhd I'll try to find some other issues for that label, but you'll have to wait.

**Comment by omarkhd** [comment]
@untitaker of course, I'll be checking the issues list to see if I can help in anything else.

**Comment by davejonesbkk** [comment]
Id like to add too that this is very frustrating as a beginner, the tutorial links to the completed code on git and says to look at that as a reference, however the code there is very different to the steps in the tutorial with many things in that are not mentioned at all in the tutorial. I can't get the code Ive used from the tutorial to run now but I dont just want to copy the finished code from git as that isn't going to help me learn.

**Comment by davidism** [comment]
Each release is tagged in Git and accessible in GitHub.  [Here is the code for flaskr in 0.10.1.][1]  Going forward, perhaps we could have a TODO before release to set more specific links in the docs.

[1]: https://github.com/mitsuhiko/flask/tree/0.10.1/examples/flaskr

**Comment by prachikhadke** [comment]
Clearly, the sample https://github.com/pallets/flask/tree/master/examples/flaskr is very different from the tutorial. One solution is to create a sample using the tutorial steps to ensure consistency for new users.

**Comment by jason-neal** [comment]
I just went though the tutorial this week and had some issues getting flaskr to work. 

In the [http://flask.pocoo.org/docs/0.12/tutorial/packaging/](http://flask.pocoo.org/docs/0.12/tutorial/packaging/) the export commands were not correct/sufficient.
Following suggestions on [stackoverflow](https://stackoverflow.com/questions/12118192/flaskr-tutorial-cant-import-flaskr-initialize-database). I had to change
`export FLASK_APP=flaskr`  -> `export FLASK_APP=flaskr.py`
and add 
`export PATH="$PATH:/the/path/to/flaskr.py" `


In [http://flask.pocoo.org/docs/dev/testing/](http://flask.pocoo.org/docs/dev/testing/) the import line shown `import flaskr` needs to be changed to `from flaskr import flaskr` as given in the github code or else no tests work.  Also the tests in the tutorial use `unittest` while the code does not use `unittest` at all, just `pytest`.

**Comment by changeling** [comment]
Flaskr Tutorial Issue between stable documentation (0.12.x) testing.rst and tutorial/testing.rst:

"For now go ahead a create the :file:`tests/` directory as well as the **:file:`test_flaskr.py`** file."
-- http://flask.pocoo.org/docs/0.12/tutorial/testing/

"In order to test the application, we add a second module (**:file:`flaskr_tests.py`**) and create a unittest skeleton there:"
--- http://flask.pocoo.org/docs/0.12/testing/

(If this is a subtle encouragement to think through "Testing," well-played, sir or madam. Well played indeed.)

**Comment by davidism** [comment]
continued in #2513
