### ISSUE TITLE
request.json and a lot of other attributes don't use autodoc

### ISSUE THREAD

**Issue by untitaker** [pallets/flask#1430]
Some attributes and methods have custom documentation in api.rst, while there doesn't seem to be a reason why that couldn't be generated through autodoc.

**Comment by AnaPana** [comment]
Working on this issue while sprinting on PyCon2016

**Comment by jeffwidman** [comment]
@frankV @AnaPana don't forget to submit a Pull Request with your changes. If there's any parts you're uncertain about, just mention it in a comment on the PR and we can discuss.

**Comment by frankV** [comment]
@jeffwidman haven't forgotten, trouble encountered when beginning to switch over to autodocs. End up losing a lot of custom documentation, so the question arises whether they should go into the docstrings, or break out into their own section.

Also I think this issue should incorporate #190 as there's a lot of overlap with Werkzeug in the api.rst. Waiting for an answer there as well.

**Comment by paulgb** [comment]
I took a look at this as part of the TS Open sprint. It looks like the `request.get_json` call mentioned in the issue name now has its documentation pulled in from `werkzeug.wrappers.json`. At first glance, I could not find any examples of redundancy between sections of api.rst and other parts of the documentation.

**Comment by davidism** [comment]
Yeah, looks like this is good now. Thanks for checking!
