### ISSUE TITLE
Clarify what app.config.from_object accepts

### ISSUE THREAD

**Issue by tony** [pallets/flask#1457]
```
$ python
Python 2.7.9 (default, Apr 29 2015, 18:34:06) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask
>>> conf = {"DEBUG": True}
>>> app = flask.Flask(__name__)                                                
>>> app.config.from_object(conf)
>>> app.debug
False
```

Expected behavior would be to accept to setting in the flask application object.

```
>>> flask.__version__
'0.10.1'
```

```
>>> conf = {"SECRET_KEY": "honey"}                                                                                                                                      
>>> app = flask.Flask(__name__)                                                                                                                                         
>>> app.config.from_object(conf)                                                                                                                                        
>>> app.secret_key
```

**Comment by untitaker** [comment]
from_object doesn't read from dictionary keys, instead it traverses `dir(obj)`. This is useful if you pass a module object with global vars in it.

This is something that should be clarified in the docs though.

**Comment by tony** [comment]
@untitaker :  

Thanks for getting back so quickly

I happen to be working inside of a larger example that should be turning the dict into an object. Let me look closer to verify that functionality is working as expected.

**Comment by untitaker** [comment]
Could you post a link to that example? AFAIK from_object was never supposed to work that way.

**Comment by tony** [comment]
Yeah, it may be a bigger oversight on part. Checking it.

**Comment by tony** [comment]
First I was using is totally wrong then.

https://github.com/tony/cookiecutter-flask-pythonic/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D.py#L32

``app.config.from_object(dict(self.config))``.

If I wanted to go that approach, I think my only option to write my own config parser.

**Comment by untitaker** [comment]
According to the code above, `self.config` already has the wished attributes? So calling `dict` on it is the problem, nothing else.

**Comment by tony** [comment]
``self.config`` is this:

```python

class AttributeDict(dict):

    def __getattr__(self, name):
        if not name in self:
            raise AttributeError("'{}' object has no attribute '{}'".format(
                self.__class__,
                name,
            ))

        return self[name]
```

**Comment by tony** [comment]
Removed the ``dict`` part, still not getting anything because of ``dir``'s results.

Perhaps if I gave the ``AttributeDict`` a ``__dir__`` dunder?

**Comment by untitaker** [comment]
You could also just set your attributes on your AttributeDict instance instead of defining `__getattr__`, provided your config is readonly.

**Comment by jsonbrazeal** [comment]
looking at this for #pycon2016 sprints

**Comment by davidism** [comment]
#1870
