### ISSUE TITLE
try_trigger_before_first_request_functions in test cases

### ISSUE THREAD

**Issue by nitori** [pallets/flask#1466]
Hi,

I'm currently testing a feature (knitori@f2ae742d163300a22b7b03ca2ac60810ed1de59b) that required to move the registration of the static url from `__init__` to a method, and register that method using `before_first_request` (knitori@6bc77363ed9ee1a9ba00d3536f0479ab0967a8bd).

It works pretty well with a normal application, but it fails one test (`tests/test_basic.py::test_static_files FAILED`). And I realized, that the registered `before_first_request` functions are never actually called with the test client `testing.FlaskClient`. I fixed that locally by adding `self.application.try_trigger_before_first_request_functions()` right before the return statement of `testing.FlaskClient.open` (or should it even go to `Client.open`?).

I'm wondering if there is a rationale behind not calling the registered functions? Or has there just never been a case where it's actually required?

**Edit**

I realized this doesn't work. If the first request is to a static URL, it will return 404, because the RequestContext was created before the static route was registered. If anything, I probably need another even like `before_first_request_context` or something like that. Maybe called inside of `Flask.request_context`.

I'm sorry, it seems this turned into a completely different issue.

**Comment by davidism** [comment]
As soon as the application is handling any part of a request, it should no longer be modifying itself.
