### ISSUE TITLE
Add support for default environ in test_client

### ISSUE THREAD

**Issue by haizaar** [pallets/flask#1467]
It would be nice if `test_client()` would accept default environ dictionary. That would stop us doing hacks like [this](http://stackoverflow.com/questions/15278285/setting-mocking-request-headers-for-flask-app-unit-test) over and over.

For example:
```
test_client = app.test_client(defailt_environ = {
    "REMOTE_ADDR": "127.0.0.1"
})
```

`default_environ` should be then passed down all the way to `environment_base` args of `EnvironBuilder` in test.py.

Thank you!

**Comment by mrecachinas** [comment]
@haizaar see #2047 to ensure this met your request, and if so, feel free to close it! :)

**Comment by haizaar** [comment]
Looking at the code seems like it does. Unfortunately I don't have an access to the project where it was originally required. I'll close this issue.

Thank you for implementing it!
