### ISSUE TITLE
Consider adding documentation about script-name-stripping middleware to CGI deployment documentation

### ISSUE THREAD

**Issue by DanielGibbsNZ** [pallets/flask#1485]
The FastCGI deployment documentation mentions that it may be necessary to configure some middleware to strip the `SCRIPT_NAME` environment variable of the actual script file name in order to prevent it appearing in the URL (e.g. `example.com/yourapplication.fcgi/news/`).

The default `mod_rewrite` configuration given in the CGI deployment documentation has the same issues yet no mention of this workaround is given. Please consider mentioning this on this page also.

**Comment by davidism** [comment]
I'm moving away from officially supporting mod_userdir deployments. After testing with mod_proxy_fcgi, SCRIPT_NAME was always set appropriately.
