### ISSUE TITLE
UnicodeEncodeError when script is in a folder with non-ascii characters in the name

### ISSUE THREAD

**Issue by jjunho** [pallets/flask#149]
Very very nice work done in Flask! Really liked it!
However, I was trying to run my Flask script under a subfolder of my Desktop folder in Ubuntu. Since my system is set up for Portuguese (I'm Brazilian), the default name for the folder is "Área de Trabalho". I was getting UnicodeEncodeError every time I tried to run the example in "11.7 Uploading Files". (At least it was really good to teach me how to use the Flask debugger!) I went around, examining where the error was coming from, and, finally, got to "File "/usr/local/lib/python2.6/dist-packages/Flask-0.6-py2.6.egg/flask/helpers.py", line 350, in send_file", when the function adler32 uses the unicode string. Then, I just tried a quick "from zlib import adler32; adler32(u'Á')" to realize that zlib doesn't allow unicode strings, returning a "UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 0: ordinal not in range(128)".
Of course I can move my script to another folder, but it would be nice not having to think about that in the future, especially when it is said that "Flask like Jinja2 and Werkzeug is totally Unicode based when it comes to text".
Sorry if I don't make much sense... it's almost 3:00am around here...

Congrats for the great job on Flask!

jjunho

**Comment by jeffwidman** [comment]
The original bug was reported against Flask 0.6. 

Is this issue still relevant?

**Comment by antsar** [comment]
Tried this on 0.7 thru master and **could not reproduce**. Flask examples run fine even when the path contains non-ascii chars.
