### ISSUE TITLE
Better docs for app context and it's solutions

### ISSUE THREAD

**Issue by rakanalh** [pallets/flask#1521]
I've been using Flask for about a month now and i can say that it's pretty awesome.

The one thing that annoys me is the "application context" and it's lack of proper documentation.

I understand that app context makes you able to instantiate multiple apps in a single python process. But i've been thinking for quite a while about what is a proper use case for this? can the documentation provide an example about why and how to do this?

In addition, if faced with "working outside application context" exception, how do you overcome this? for example in a celery task. Do we use something like, [Flask Celery Helper](https://github.com/Robpol86/Flask-Celery-Helper)? Because even using the Celery object alone would still result in such exception being raised inside whatever we do inside the celery task itself. That has been kind of a debugging nightmare.

Many Thanks

**Comment by cescoferraro** [comment]
app.app_context().push()

No helper needed. See https://github.com/miguelgrinberg/flasky-with-celery

**Comment by davidism** [comment]
The docs already describe how to manually work inside an app context, as well as a method of doing this with Celery.  Flask-Script and the new CLI maintain an app context for commands.  Most tutorials also mention this.  The one thing that's missing is what you point out: a description of the error you get when something needs an app context.  I'll add this in, or welcome a PR if someone would like to contribute.

**Comment by jeffwidman** [comment]
See also #1151

**Comment by ryanbackman** [comment]
Working on this as part of Pycon 2016
