### ISSUE TITLE
Update docs on the website (at least the python 3 ones)

### ISSUE THREAD

**Issue by JelteF** [pallets/flask#1578]
The website gives a very outdated view on the python 3 issue:
http://flask.pocoo.org/docs/0.10/python3/

This seems to be updated to make it a lot more realistic, but is not online:
https://github.com/mitsuhiko/flask/blob/master/docs/python3.rst

This RST file also seems to give a very different view than the dedicated python3 one:
https://github.com/mitsuhiko/flask/blob/master/docs/advanced_foreword.rst

**Comment by ewilson** [comment]
I've been wondering about this also. What is on the website is dated 2013, and seems unlikely to represent the current reality.

**Comment by davidism** [comment]
The dev version docs are online: http://flask.pocoo.org/docs/dev/python3/.
I agree that the message between the two pages needs to be consistent.

**Comment by untitaker** [comment]
Since this is fixed in dev already, is there really anything left to be done except cut a new release?

**Comment by JelteF** [comment]
I think this one should still be updated:
https://github.com/pallets/flask/blob/master/docs/advanced_foreword.rst

But for the rest I think that a release would indeed be the solution. I'm not sure if a release is on the planning though. But it might be useful to update these kinds of docs at least even if an actual new release is not needed. Since Flask is pretty popular I've seen people reference these docs as reasons not to use Python 3, even though the pages are updated in the repo already.

**Comment by untitaker** [comment]
>I think this one should still be updated:

Agreed.

I'd rather not hotfix the docs though. As this is all a volunteer effort I'm really reluctant on giving an ETA (I myself don't know), but a release is definetly in the making.

**Comment by jasonslay** [comment]
Should this be closed and rolled into #1772?

**Comment by untitaker** [comment]
No, as far as I can remember this is not even fixed in master.

**Comment by alatar-** [comment]
I am working on this within PyCon sprint.
