### ISSUE TITLE
OPTIONS requests sometimes match the wrong url_rule if there are multiple route handlers for different methods

### ISSUE THREAD

**Issue by ahuling13** [pallets/flask#1604]
I have multiple route handlers with the same path but with different methods that they handles, e.g.

```
@app.route('/users', methods=['GET'])
@app.route('/users', methods=['POST'])
```

The problem occurs when a CORS pre-flight OPTIONS request is made to `/users`. Since the route and method match both endpoints, the wrong endpoint is sometimes returned which is problematic if you are trying to use the matched `url_rule` for any logic. In my case, I was using `request.url_rule.methods` to add the `Access-Control-Allow-Methods` header to the response.

**Comment by mitsuhiko** [comment]
Can you please provide a testcase?

**Comment by tranqil** [comment]
I had similar issue, I thought `request.url_rule.methods` will return *combined* list of allowed methods for `/users` resource but instead it returns allowed methods for current handler function.
 
I'm not sure why 'the wrong endpoint is *sometimes* returned', for me its always the endpoint that was defined first in the source code, so in your case, OPTIONS always would been handled by:
`@app.route('/users', methods=['GET'])`

There is a snippet that shows CORS implementation as decorator: http://flask.pocoo.org/snippets/56/
If we look at `get_methods()` function:

```
    def get_methods():
        if methods is not None:
            return methods

        options_resp = current_app.make_default_options_response()
        return options_resp.headers['allow']
```
At first, default OPTIONS response is created using `make_default_options_response()` function, this is the response that flask returns by default if OPTIONS is not overwritten (so you don't have to handle OPTIONS each time you create a route).

What happens next is that we take 'allow' header and return its value.
'allow' header (https://github.com/pallets/werkzeug/blob/b5eb6415232df923f157a31558c52385beb72897/werkzeug/wrappers.py#L1799) contains string of all allowed methods for this endpoint, in your case it will be 'GET, POST' which is exactly what you need - list of all allowed methods that the server willing to accept for '/users' endpoint.

**Comment by ahuling13** [comment]
Looks great -- I'll give it a shot. Thank you!

Re: the wrong endpoint sometimes being returned, I just meant that the only time the right endpoint is returned is when you are requesting the endpoint defined first in the source code. Then the "right" endpoint is returned. Otherwise, the wrong endpoint (the first one) is returned.

**Comment by jeffwidman** [comment]
I suspect this is related to #1783 with the root cause being https://github.com/pallets/werkzeug/pull/907

**Comment by davidism** [comment]
Sounds like the specific use case described here is already handled by the default options route, which can be overridden with `Flask.make_default_options_response`. Also, pallets/werkzeug#1137 fixed some issues with path weights including those linked by Jeff, although I'm not sure if those were actually related.
