### ISSUE TITLE
Documentation on setting up configuration file might cause friction to new users

### ISSUE THREAD

**Issue by benjaminweb** [pallets/flask#1615]
_refers to: http://flask.pocoo.org/docs/0.10/config/#development-production_

I did not have `__init__.py` present. I did not know whether `.py` to be part of `server_config` as filename.

Friction for new user can be reduced by giving a more precise example, like:

```
app.config.from_object('module.server_config')
```
files:
```
module/__init__.py (may be empty)
module/server_config.py
```
Let server_config.py contain the following:

```
DEBUG = False
TESTING = False
DATABASE_URI = 'sqlite://:memory:'
user = 'Aladdin' 
```

However, app.config will carry only UPPERCASE keys (KEY=value) in config file.
Hence, app.config['DATABASE_URI'] will be set, app.config['user'] not.

**Comment by ankitdbst** [comment]
Hello,

As per my understanding __init__.py should be present for a directory to be python module. Only then can we refer to the internal modules using module.<internal_module_filename>

It would certainly help if we can provide the directory view of the files during the configuration step.
Other details like Upper case keys are mentioned in the section above: http://flask.pocoo.org/docs/0.10/config/#configuring-from-files

**Comment by jeffwidman** [comment]
We do want to make it easy for folks to get started. The best next action is if either of you can put together a PR with suggested improvements, then we can review/discuss the concrete changes you're thinking.

**Comment by jeffwidman** [comment]
I'm going to close this for now as I think this is more of an optional enhancement than a bug. 

We can definitely re-open if you submit a PR with your suggested improvements.
