### ISSUE TITLE
Documentation / Quickstart / Debugger - how to activate

### ISSUE THREAD

**Issue by ewann** [pallets/flask#1625]
When following the quickstart, specifically:

https://github.com/mitsuhiko/flask/search?utf8=%E2%9C%93&q=++Screenshot+of+the+debugger+in+action

I found myself jumping to google to learn how to activate the debugger. Perhaps if the screen grab showed & highlighted the console icon on the far left of my screen, that wouldn't have happened.

I'm happy to submit a pull request with a replacement screenshot if you agree this would be useful, noting I'm not on mac, so screen grab might look out of place, if that detail is considered important

**Comment by CrimsonRay** [comment]
There are instructions on how to use the debugger below the traceback at the bottom of the page.

> The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
> 
> To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. **For code execution mouse-over the frame you want to debug and click on the console icon on the right side.**
> 
> You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:
> 
> * dump() shows all variables in the frame
> * dump(obj) dumps all that's known about the object

**Comment by davidism** [comment]
The debugger is part of Werkzeug, and some more instruction is located in [those doc][1].  The Flask docs could either link there or mention it as well.

[1]: http://werkzeug.pocoo.org/docs/0.11/debug/#using-the-debugger

**Comment by jeffwidman** [comment]
+1 on linking to Werkzeug, as I don't see the point of repeating that info in Flask beyond what's already in there that @CrimsonRay mentioned. Probably best to link to the dev version of Werkzeug docs rather than pinning to a specific release.
