### ISSUE TITLE
Delete superfluous branches from the repo?

### ISSUE THREAD

**Issue by jeffwidman** [pallets/flask#1670]
There's several branches on this repo that are superfluous and should probably be deleted because they contain no additional commits and haven't been worked on in years. 

For example:
* https://github.com/mitsuhiko/flask/tree/json-sessions
* https://github.com/mitsuhiko/flask/tree/flask_deployment_docs
* https://github.com/mitsuhiko/flask/tree/appdispatch-docs

**Comment by untitaker** [comment]
I've deleted the ones that were already merged into master.

**Comment by ThiefMaster** [comment]
`new-modules` can most likely go away too.. that's from the pre-blueprint era

**Comment by jeffwidman** [comment]
@untitaker Any objection to deleting `new-modules`? It'd be nice to mark this task as completed one way or the other.

**Comment by untitaker** [comment]
No idea what that branch is as I probably wasn't around at that time.

**Comment by jeffwidman** [comment]
I just deleted `new-modules`.
