### ISSUE TITLE
Allow specifying blueprint-local JSON encoder 

### ISSUE THREAD

**Issue by jfinkels** [pallets/flask#1710]
A user can specify a JSONEncoder on a Flask application, but it would be useful to be able to specify a JSONEncoder on a blueprint as well, so that requests made to that blueprint would receive responses interpreted by the specified JSON encoder.

This is important, for example, in [Flask-Restless](https://github.com/jfinkels/flask-restless), where we would like to transform SQLAlchemy objects into JSON objects at the blueprint level, without modifying the JSON Encoder assigned to the specific Flask application.

**Comment by guyskk** [comment]
I think Flask-Restless should provide a JSONEncoder not depend on flask, then you can modify it.

**Comment by RaHus** [comment]
An attempt to provide this functionality. 
Modeled after `Flask.json_encoder`, `Flask.json_decoder`.
One possible issue is that it ties flasks json helpers (dumps, loads, etc) to an active request, which may break tests that only setup an app context.

**Comment by ThiefMaster** [comment]
> that it ties flasks json helpers (dumps, loads, etc) to an active request

IMHO that's a big no-no. You could check whether there's a request context but I'm not sure if this should be in the Flask core at all.

**Comment by RaHus** [comment]
@ThiefMaster Is there a way to get the `current_blueprint` without using an active request? Could you take a look at the commented diff?

**Comment by ThiefMaster** [comment]
There is no active/current blueprint except during a request that was handled by an endpoint within the blueprint.

**Comment by RaHus** [comment]
Comments noted, I'll make the changes shortly

**Comment by RaHus** [comment]
Changes are there, if the diff looks ok and the feature is considered ok for flask core i will add some documentation before making a PR,

**Comment by davidism** [comment]
Would you make this a pull request so we can review this in one place with the full diff?

**Comment by RaHus** [comment]
Done
