### ISSUE TITLE
Documentation needs to explain Circular Dependencies Better

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/flask#173]
Currently the documentation does not explain well enough how to deal with circular imports.

Related feedback issues:

* http://feedback.flask.pocoo.org/message/99
* http://feedback.flask.pocoo.org/message/18

**Comment by shanhind** [comment]
This issue should be closed as the links to the docs in question are no longer active or accessible.

**Comment by jeffwidman** [comment]
There's now some more info on circular imports in http://flask.pocoo.org/docs/0.11/patterns/packages/
