### ISSUE TITLE
Error Handlers versus Werkzeug Exceptions

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/flask#175]
Currently you can only declare error handler for Werkzeug exceptions. That's pretty much the case because what is not raised as a Werkzeug HTTP exception can't be catched. However since Python 2.4 is currently in the process of being phased out we could now finally make exceptions actual response objects if we prefer so it would make sense to keep that in mind and provide catching not only by code but also by any kind of instance check.

This also affects Werkzeug.

Related feedback issues:
- http://feedback.flask.pocoo.org/message/112

**Comment by jeffwidman** [comment]
@untitaker Is this still relevant? 

I don't fully understand the original issue, and unfortunately the linked-to feedback site is now dead.

**Comment by untitaker** [comment]
It's been a while, but I think the main idea here is to make HTTP exceptions fully fledged response objects. This is still valid.

The code for *handling* errors has been refactored to not make that much of a difference between HTTP and other exceptions, see https://github.com/pallets/flask/pull/1291. But that's not the main point of this issue anyway.

**Comment by davidism** [comment]
`HTTPException` is a WSGI callable, so `make_response` handles it fine. Not sure what else needs to be done here. If this is still an issue it needs to be clarified before reopening.
