### ISSUE TITLE
Add Zappa To Flask Deploy Guides

### ISSUE THREAD

**Issue by Miserlou** [pallets/flask#1768]
Since [Zappa](http://github.com/Miserlou/Zappa) now integrates seamlessly with Flask, I was wondering if you'd be open to the notion of having Zappa as one of the documented deployment options. I'm willing to write the docs myself, but I wanted to confirm the feature before submitting a pull request. I've also already written a [small tutorial](https://gun.io/blog/serverless-microservices-with-zappa-and-flask/) if anybody is interested in learning more.

Thanks!

**Comment by untitaker** [comment]
I'd rather have this outside of the Flask project unless there is sufficient demand for having it baked into the Flask docs.

**Comment by davidism** [comment]
This looks really cool, and could definitely be included in the extensions directory.

For the deploy page, I'm ok with including a link to external official documentation (more than a blog post) like we do with other services.  But the stuff that's included first-party is for more general/traditional server setups.

**Comment by davidism** [comment]
On second look, how is this different than CGI.  It sounds like you're starting an entire process for every request, which would be incredibly inefficient.

**Comment by Miserlou** [comment]
You are, but it's across n-many virtual machines, which are spawned instantly when the HTTP request comes through the API Gateway. It would be inefficient on a single machine, but Amazon automatically handles horizontal scaling. Plus, you never have to worry about server maintenance ever again, because the servers only exist for a single HTTP request.

**Comment by jeffwidman** [comment]
It seems the consensus from the maintenance team that while we're genuinely excited that Zappa supports Flask, we don't want to have detailed deployment instructions for proprietary/third-party services in the docs. It's too easy for the Flask docs to get outdated when the third-party updates some random config setting.

**Comment by Miserlou** [comment]
Fair enough, sound reasoning, thanks for considering.
