### ISSUE TITLE
Flask docs need rebuilding

### ISSUE THREAD

**Issue by jeffwidman** [pallets/flask#1772]
d3d8a4694a9c1601e213d6b5f27fab34615609b7 hasn't shown up yet here: http://flask.pocoo.org/docs/dev/extensions/

I'm not sure how to trigger a rebuild... on RTD, anyone can trigger a rebuild from the web, but since it's hosted on Pocoo I'm not sure if there's a webhook that watches the repo for commits, or if @mitsuhiko has to manually do it.

**Comment by jaapz** [comment]
Would be nice if the docs were just hosted on read the docs instead.

**Comment by mitsuhiko** [comment]
I tried to manually trigger a build but something is wrong. I will investigate that in detail later.

**Comment by jeffwidman** [comment]
> Would be nice if the docs were just hosted on read the docs instead.

Indeed, this would be fixed by https://github.com/pallets/meta/issues/15
