### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by vamsi** [pallets/flask#1773]
It would be nice if you could add an issue template to the repository.

**Comment by jeffwidman** [comment]
Why? Not trying to be snarky, just genuinely curious what value it would add, as we (generally) do okay right now and AFAIK don't have problems with most bug reports missing necessary information.

**Comment by untitaker** [comment]
All-caps "use StackOverflow for questions"

On 8 April 2016 08:43:12 CEST, Jeff Widman <notifications@github.com> wrote:
>Why? Not trying to be snarky, just genuinely curious what value it
>would add, as we (generally) do okay right now and AFAIK don't have
>problems with most bug reports missing necessary information.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/1773#issuecomment-207245750

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeffwidman** [comment]
Just went to fix this, but it requires owner permissions on the repo, so @untitaker you'll probably need to do this.

**Comment by untitaker** [comment]
Why? It's just a file in the repo, nothing fancy.

**Comment by jeffwidman** [comment]
Oops, my bad, I thought it was buried in the repo settings somewhere.

**Comment by lepture** [comment]
A CONTRIBUTING.rst is enough.

**Comment by indera** [comment]
@lepture Does this mean that we should add more details on how to submit issues to the existing https://github.com/pallets/flask/blob/master/CONTRIBUTING.rst ?

**Comment by untitaker** [comment]
Note this is the personal opinion of lepture. IMO we do need one, though we also should take care not to duplicate content.

**Comment by lepture** [comment]
Actually, the current contributing guide looks like an issue guide rather than contributing guide.

**Comment by hyunchel** [comment]
I'm working on this at pycon.
