### ISSUE TITLE
Update the list of Approved Extensions

### ISSUE THREAD

**Issue by jeffwidman** [pallets/flask#1775]
http://flask.pocoo.org/docs/dev/extensiondev/#approved-extensions

Does anyone keep this updated? 
Should the concept of "approved" extensions get dropped?

Similarly, with the transition to `pallets`, what's going to happen to the extensions list itself? http://flask.pocoo.org/extensions/ 

Will it get dropped like snippets are?

See also #865 about updating the docs on approved extensions.

**Comment by davidism** [comment]
I'm converting the extensions to Lektor content.  I'll try to get it done this weekend.

**Comment by xqliu** [comment]
Some of the extensions hasn't been updated for a long time and also did not been update to py3 compatible,
Will the core team take sometime to reconsider the approval status of those extensions?
Thanks.

On Fri, Apr 8, 2016 at 4:35 PM, David Lord <notifications@github.com> wrote:
I'm converting the extensions to Lektor content. I'll try to get it done this weekend.

**Comment by untitaker** [comment]
In principle we should keep this list and keep it updated (also remove some approvals)

On 8 April 2016 10:38:34 CEST, Lawrence Liu <notifications@github.com> wrote:
>Some of the extensions hasn't been updated for a long time and also did
>not been update to py3 compatible,
>Will the core team take sometime to reconsider the approval status of
>those extensions?
>Thanks.
>
>On Fri, Apr 8, 2016 at 4:35 PM, David Lord <notifications@github.com>
>wrote:
>I'm converting the extensions to Lektor content. I'll try to get it
>done this weekend.
>
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub
>[https://github.com/pallets/flask/issues/1775#issuecomment-207315902]
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/1775#issuecomment-207319259

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davidism** [comment]
Yeah, I want to keep the idea of approved extensions.  It's definitely a good idea to call attention to the ones that are well organized.  I'll do a short review when I port them over, and it looks like there was an old script that tested the approved extensions, but if we want to change the process I'm up for discussion.

**Comment by zed2015** [comment]
good

**Comment by dchevell** [comment]
Is this still happening? Two years on, Flask-Cache remains recommended despite receiving no updates in 4 years, and users have to do their own research to find the currently maintained fork, Flask-Caching.

**Comment by davidism** [comment]
This is probably not going to happen at this point. I may revisit adding a more extensive registry on the Pallets site at some point, but now that PyPI has a Flask tag the need isn't as great.

**Comment by Morabaraba** [comment]
Is there any way to identify approved extensions on PyPI?

**Comment by davidism** [comment]
No, and there was no practical way to identify them on the old list either, since the last approved extension was added many years ago, ignoring years of further development.

**Comment by Morabaraba** [comment]
Thanks for the feedback. 

Suggestion, maybe update the official documentation that [approved extensions](https://flask.palletsprojects.com/en/1.1.x/extensiondev/#approved-extensions) is not available anymore?
