### ISSUE TITLE
Determine API for integrating custom shells with Flask such as IPython, etc?

### ISSUE THREAD

**Issue by jeffwidman** [pallets/flask#1776]
Continuing discussion from #1729 

1. Should Flask shell natively support iPython?
If so, what should that API look like?

2. Should Flask have a generic hook for extensions to add support for additional third-party shells? 
If so, how would this work? @RonnyPfannschmidt suggested using entry points for this.

My vote is to natively support for iPython since it's so popular (I use it myself all the time via Flask-Script). But draw the line there and require other custom shell integrations to happen through third-party extensions.

**Comment by untitaker** [comment]
I'd much rather draw the line earlier and have everything done via extensions. We can have official extensions nonetheless (different topic).

**Comment by AzureusNation** [comment]
I don't see the point o this, other wise your going to be getting other people wanting their shells. If they want to have it supported then let them have an API to create an extension if that isn't already available.
