### ISSUE TITLE
app.route does not catch // when having <path:> in the directive

### ISSUE THREAD

**Issue by tzickel** [pallets/flask#1778]
```python
@app.route('/test/<path:yey>')

>>> requests.get('http://localhost:5000/test/ye')
<Response [200]>
>>> requests.get('http://localhost:5000/test//')
<Response [404]>
>>> requests.get('http://localhost:5000/test//test')
<Response [404]>
>>> requests.get('http://localhost:5000/test/ye/te')
<Response [200]>
>>> requests.get('http://localhost:5000/test/ye//te')
<Response [200]>
>>> requests.get('http://localhost:5000/test///te')
<Response [404]>
>>> requests.get('http://localhost:5000/test//a/te')
<Response [404]>
>>> requests.get('http://localhost:5000/test/a//te')
<Response [200]>
```

All the 404 stuff should be intercepted but aren't.

**Comment by ThiefMaster** [comment]
URLs with two consecutive slashes are usually garbage/broken. But I remember some issue with the dev server related to this. Can you try if it also breaks when using a real WSGI container instead? gunicorn is probably the quickest way to test this.

**Comment by tzickel** [comment]
Currently I only have gevent WSGI (where it happens as well).

**Comment by davidism** [comment]
The regex for [`PathConverter`](https://github.com/pallets/werkzeug/blob/0.11.5/werkzeug/routing.py#L978-L989) matches anything that doesn't start with a `/`, as absolute paths are typically a bad idea to let users enter.  If you need your own converter that does something different, you can write and register one the same way the others are.
