### ISSUE TITLE
Not possible to set a session cookie without a domain attribute when SERVER_NAME is set

### ISSUE THREAD

**Issue by wrr** [pallets/flask#1784]
If cookie has no domain attribute, it is valid only for the exact domain to which the request that sets the cookie is addressed, this is often a desirable behavior. A domain attribute makes the cookie also valid for all sub-domains of the specified domain.

Looking at https://github.com/pallets/flask/blob/c9b29f4072b66be4c751af060d64ea749c6991c1/flask/sessions.py#L198 if `SERVER_NAME` is set, a cookie will always have a domain attribute (either explicitly set via `SESSION_COOKIE_DOMAIN` or inferred from the `SERVER_NAME`).

Would it be possible to allow setting cookies without a domain  when `SERVER_NAME` is set?

**Comment by Fajkowsky** [comment]
But why? What would be purpose of this?

**Comment by wrr** [comment]
@Fajkowsky say `example.org` site uses `admin.example.org` subdomain for administration purposes and would like to set authentication cookies that are restricted to `admin.example.org` only.

**Comment by untitaker** [comment]
I don't understand how a decent API would look like. Note that you can already subclass Flask (which is generally encouraged).

**Comment by wrr** [comment]
@untitaker ideally `SESSION_COOKIE_DOMAIN` would be the only setting that controls the `domain` attribute (the `domain` would be never set if `SESSION_COOKIE_DOMAIN` is `None`). But such change is not backward compatible. 

A backward compatible approach would be to introduce for example `SESSION_COOKIE_DOMAIN_FROM_SERVER_NAME` setting that defaults to `True`. With the setting set to `True`, the current behavior is preserved. With the setting set to `False`, the `domain` attribute is set based on the `SESSION_COOKIE_DOMAIN` only.

**Comment by davidism** [comment]
You can now set `SESSION_COOKIE_DOMAIN = False` to explicitly prevent any domain being set on the cookie. #2282
