### ISSUE TITLE
Failed get_json

### ISSUE THREAD

**Issue by yi719** [pallets/flask#1786]
hi, we find a strange error, sometime  request.get_json(force=True) will fail.
And,  https://github.com/pallets/flask/blob/c9b29f4072b66be4c751af060d64ea749c6991c1/flask/wrappers.py#L151
data here is http header in string instead of http body!!

**Comment by RonnyPfannschmidt** [comment]
please provide more context, like what wsgi gateway is being used, what versions are involved and get us some proactive information

because what you wrote cannot possibly help in guessing/comprehending what's wrong on your side

**Comment by yi719** [comment]
@RonnyPfannschmidt  Thank you for reminding me.
we use 
gunicorn==19.3.0
Flask==0.10.1
gevent==1.1.0


behind nginx/1.4.6

we see errors from sentry like
flask.wrappers in on_json_loading_failed BadRequest: 400: Bad Request

![085d2019-0284-465d-a154-9f1c09df5474](https://cloud.githubusercontent.com/assets/629937/14667692/0550266e-0713-11e6-94d9-d6100d684d80.png)

**Comment by ThiefMaster** [comment]
Well that looks a lot like you are sending data that's not valid JSON.

**Comment by RonnyPfannschmidt** [comment]
at first glance this looks like a complete http message is being sent as body of a request, this could be a bad client, does this happen from your tests or is the  source a certain customer/user

**Comment by yi719** [comment]
this only occurs Occasionally in one of our API to which client  post analytics in batch mode.
just wondering if it's caused by werkzeug parsing HTTP or request  modified by some ISP's proxy

**Comment by davidism** [comment]
The `data` is not valid JSON.  Whatever is causing that is the problem, but it's not Flask.  If you discover it *is* Flask, you'll need to provide enough information for us to reproduce the issue.

**Comment by jaketeater** [comment]
I also encountered this problem. In case it would help anyone else, I found that with sentry commented out, the get_json() worked.  However, with the exact same request while using sentry it failed every time.  

Seems to be an issue with sentry?
