### ISSUE TITLE
Install flask gives error

### ISSUE THREAD

**Issue by rich7** [pallets/flask#1788]
I was curious and tried to give flask a try. But it goes wrong from the start. 

$ python hello.py
python: can't open file 'hello.py': [Errno 2] No such file or directory

pi@raspberrypi ~/relaxbank $ find . -name 'hello.py'
pi@raspberrypi ~/relaxbank $

**Comment by RonnyPfannschmidt** [comment]
thats not related to flask at all - that is a plain basic "file is not there" problem and entirely your fault

**Comment by rich7** [comment]
Quote from the flask website 
"  And Easy to Setup
$ pip install Flask
$ python hello.py"

following this it gives this error, so where did I go wrong?

**Comment by RonnyPfannschmidt** [comment]
http://flask.pocoo.org/docs/0.10/quickstart/#a-minimal-application tells you to make that file yourself

but you didn't even tell us what you did, only "things don't work" followed by stuff that's completely unrelated to flask

**Comment by zoidbergwill** [comment]
This is a strange tone to open a bug report with:

> I was curious and tried to give flask a try. But it goes wrong from the start.

`python hello.py` is just trying to execute a file called `hello.py` with whichever Python interpreter you have installed as default `python`, so it'd be difficult for that to be using any Flask code, unless you were using some Flask code within the `hello.py` file or any modules which it imports.

Good luck with your adventures and whatever framework you decide to use though.

**Comment by untitaker** [comment]
>p.s. good luck with your framework, the way a question is handled tells how helpful the community is 

You have opened a bug report against Flask, not asked a question. While I definetly see potential for improvement regarding how newcomers are treated, the contribution guide [shown when opening an issue](https://github.com/blog/1184-contributing-guidelines) tells you that support questions don't belong here.

Before "Easy to setup" you find the content of `hello.py`.
