### ISSUE TITLE
'Flash' Silent Error: occurrs when trying to flash a string with too many characters.

### ISSUE THREAD

**Issue by joeflack4** [pallets/flask#1789]
An error is occurring when I try to flash a message with too many characters. In my case, that number is 91,326.

    if authority == True:
        rows = validate_rows(import_data, data_context)
        erroneous_rows = rows['erroneous_rows']

        if len(erroneous_rows) > 0:
            erroneous_row_string = ''
            i = 1

            # - DEBUGGING
            flash(2)

            for erroneous_row in erroneous_rows:
                erroneous_row_string += '<span style="text-decoration: underline">Row ' + str(i) + ': ' + \
                    str(erroneous_row['errors']) + '</span><br/>' + str(erroneous_row['row_data']) + '<br/><br/>'
                i += 1
            erroneous_row_string = erroneous_row_string[:-1]

            # - DEBUGGING
            # flash(erroneous_row_string) <--- If I do this, it appears to 'crash' flash(), and no messages will appear.
            flash(isinstance(erroneous_row_string, str))
            flash(len(erroneous_row_string))
            flash(3)`

When the above is executed, I get the screen below.
![error1](https://cloud.githubusercontent.com/assets/13045020/14771460/300ecdb0-0a51-11e6-8307-0ba35a68a7bf.png)

If I were to do `flash(erroneous_row_string)` instead of `flash(len(erroneous_row_string)`, no flashed messages will appear at all. Assuming that this is because there is an upper limit to # of characters a flash message can have.

This makes sense, but it would be nice to return a non-silent error, I think.

**Comment by joeflack4** [comment]
Also, I would be fine to help fix the issue by returning an error, but I am not sure how to assist. I am still kind of a newbie. But if one can let me know where to look within flask to handle this type of exception, I would be happy to assist.

**Comment by joeflack4** [comment]
Update: In an error to allow exception handling of the silent error, I played around a bit more with various outputs. I was able to flash messages containing up to 68,493 characters somewhere. So the limit appears to be somewhere between 68,493 - 91,326 characters.

**Comment by davidism** [comment]
It's probably the browser or the web server enforcing a limit on the size of cookies, not anything Flask is doing.  It's not a good idea to store this much data in the session cookie anyway, it would use a lot of bandwidth.

**Comment by joeflack4** [comment]
Hello there~ Thanks so much for the feedback. That definitely makes sense. I'll adjust my code so that the Flash message links to a dialogue modal which gives more information.

I think, however, that silent errors are generally bad. Good to be cross-platform compatible, and add a nice layer to deal with such contingencies. Then again, I'm really out of ideas as to where to add such exception handling to flask. I took a look at the Flash related architecture, and couldn't really figure out where I would even add it.

**Comment by untitaker** [comment]
The broader issue is that there is not "one true size limit" we could enforce. I think it's better to deal with this in docs.

**Comment by prachikhadke** [comment]
A good place to mention this is https://github.com/pallets/flask/blob/master/docs/patterns/flashing.rst

**Comment by jeffwidman** [comment]
Fixed in d9a98dd536b4cac42fc9012c6184251a5ae2ad7a

**Comment by joeflack4** [comment]
Thanks!
