### ISSUE TITLE
flaskr example seems to loose data on every launch

### ISSUE THREAD

**Issue by KyleVeritas** [pallets/flask#1790]
Branch: 0.10
Example - flaskr
Description: Every time close and reopen the flaskr.py, the data submitted previously are erased.

I think problem is 

``` 
if __name__ == '__main__':
    init_db() 
    app.run()
```

**Comment by RonnyPfannschmidt** [comment]
this is fixed in master,
its indeed a bug just to call it like that

**Comment by RonnyPfannschmidt** [comment]
its easy to fix but the next major release will contain a fix as well

**Comment by matheuspoleza** [comment]
@RonnyPfannschmidt so, how can I fix that?

**Comment by davidism** [comment]
https://github.com/pallets/flask/blob/0.10.1/examples/flaskr/schema.sql#L1
