### ISSUE TITLE
ImportError when dropping privileges before running Flask

### ISSUE THREAD

**Issue by blechschmidt** [pallets/flask#1800]
When using Flask as privileged user, it may under circumstances not be possible to drop permissions before the app is run, including when using ports that do not require root privileges.

    drop_privileges() # drop privileges to nobody
    app.run()

The above code will throw an `ImportError`, given the scenario that Flask's python files are not accessible to the nobody user due to file permissions, because Flask's `run`-method (and other internal methods) make use of additional inline imports.

As this scenario might be more common, it may be desirable to move all inline imports to the top of their respective module.

There are various other reasons that might support the request to move imports to the top of modules: See [Python import coding style](https://stackoverflow.com/questions/477096).

**Comment by davidism** [comment]
I can't reproduce your error, running Python as root, setting group and user to "nobody", then importing Flask still succeeds.

Create a user for your app, set up a virtualenv with that user, and run as that user.  `/usr/lib/pythonX.Y/site-packages` is typically installed with other+read privileges as well, so should still be readable anyway.

**Comment by RonnyPfannschmidt** [comment]
also note that you should never use `app.run` in production

**Comment by blechschmidt** [comment]
> I can't reproduce your error. Running Python as root, setting group and user to "nobody", then importing Flask still succeeds.
This is probably the case in a standard non-virtualized environment.

In my case, the virtual environment is located within the _/root/_-folder which _nobody_ does not have access to. Additionally, I have no control over the location of the virtual environment and at some point, the scripts within the environment indeed require _root_-access.

**Comment by davidism** [comment]
Don't put your virtual environments in root.  That's not something we can fix.
