### ISSUE TITLE
How to bind() when DEBUG = True

### ISSUE THREAD

**Issue by mekanix** [pallets/flask#1805]
For this example I use ZeroMQ but I suppose any socket library could do. This is the code
```
#!/usr/bin/env python
import zmq
from flask import Flask

app = Flask(__name__)

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind('tcp://*:5500')

app.debug = True  # Commenting this line does the trick
app.run()
```

As when using DEBUG process is fork()ed, the code tries to bind twice. Obviously, Flask knows how to open the port only once, so I'm wondering how to do the same for functions that bind()?

**Comment by wgwz** [comment]
Just as a heads up, this is an issue tracker. It's not a place for debugging code/programming help. This was the right place to post [:-)](http://stackoverflow.com/questions/37151837).

**Comment by mekanix** [comment]
Sorry about that. I've copied the question to http://stackoverflow.com/questions/37151837/flask-with-debug-flag-on-and-socket-bind.

**Comment by wgwz** [comment]
You should close the issue here as well.
