### ISSUE TITLE
stop/terminate flask outside request context

### ISSUE THREAD

**Issue by SepehrHml** [pallets/flask#1807]
is it possible to stop flask outside request context ? as i know there's no way for it .

maybe a function( stop() ) that changes a flag( shutdown_signal=False ==> True ) for werkzeug that stops server for listening on new connections ?
i can contribute on making this feature if you allow me ...

**Comment by ThiefMaster** [comment]
Why do you want this? `app.run()` is only meant for development anyway.

**Comment by SepehrHml** [comment]
i am developing a thing that use flask in another thread (maybe i should bring it to main one) ... i should try os.kill() i guess ...

**Comment by ThiefMaster** [comment]
Using `app.run()`? Sound like a bad idea.

**Comment by SepehrHml** [comment]
what about using cherrypy server since werkzeug is only for developement ?
http://flask.pocoo.org/snippets/24/

**Comment by SepehrHml** [comment]
using cherrypy server worked well for me ... thanks
