### ISSUE TITLE
flask.Flask.register_blueprint is poorly documented

### ISSUE THREAD

**Issue by JeromeJ** [pallets/flask#1809]
http://flask.pocoo.org/docs/0.10/api/#flask.Flask.register_blueprint

The documentation doesn't list or explain any of the arguments used by `flask.Flask.register_blueprint`.

It only says:

```
register_blueprint(*args, **kwargs)¶
Registers a blueprint on the application.

New in version 0.7.
```

For one, I know there should be at least `use_prefix` and maybe (or surely) more than that.

**Note:** All Flask version's documentation seems to be affected by this.

**Comment by Sanjurjo7** [comment]
I'd like to work on this. What would you recommend looking at as a good example of documentation in Flask already?

**Comment by jeffwidman** [comment]
@Sanjurjo7 Go for it! 

I haven't looked at it in-depth, but the API docs are probably auto-generated by Sphinx using the function's docstrings. So probably what you need to do is expand this a bit: https://github.com/pallets/flask/blob/master/flask/app.py#L936

While I'm not sure it's a canonically good example, there's certainly more info in the `add_url_rule` docstring: https://github.com/pallets/flask/blob/master/flask/app.py#L962

Hopefully that's enough to get you started.

**Comment by Sanjurjo7** [comment]
Okay, this is what I've got:
"""Registers a blueprint on the application.
        Blueprint name is passed in as first argument
        options passed as additional keyword arguments
        and forwarded to blueprints in the 'options' dict.
        options include:
                subdomain, url_prefix, url_defaults,
                static_folder, static_url_path,
                template_folder, root_path
        All options set to None by default, (i.e.
        static_folder=None, etc) and are handled by
        blueprints.py
        see :ref:blueprints for option usage

        .. versionadded:: 0.7
        """
I'm new to contributing though, so I've got a named branch (iss1809_register_blueprint_docs) with commits, but I'm not sure how to start a pull request...

**Comment by Sanjurjo7** [comment]
Oh, sweet, nm, I think I figured it out.

**Comment by Sanjurjo7** [comment]
Done with this one. Pull #1811 got it. :^)

**Comment by JeromeJ** [comment]
Thanks for the hard work! I don't know if I would have been able to pull it off myself!

**Comment by untitaker** [comment]
I'm reopening this issue because #1811 contains incorrect information and was reverted in #1912
