### ISSUE TITLE
Reference to Flask 1.0 in Flask 0.10 docs

### ISSUE THREAD

**Issue by roganov** [pallets/flask#1816]
I think there shouldn't be reference to future (not released) versions in current docs, it's very confusing.

http://flask.pocoo.org/docs/0.10/server/
> Starting with Flask 1.0 there are multiple built-in ways to run a development server. 

Also http://flask.pocoo.org/docs/0.10/cli/#cli link is broken.

**Comment by untitaker** [comment]
I have no idea how this ended up here. @mitsuhiko?

**Comment by ThiefMaster** [comment]
I think there are also a few `:versionadded:` markers that point to 0.11 / 1.0 - those should also be unified to 0.11

**Comment by mitsuhiko** [comment]
Not even sure. But 0.11 is out very soon now so this should be fixed with that.
