### ISSUE TITLE
Consider making StrictUndefined the default in Flask 1.0

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [pallets/flask#1824]
Of all Undefined variants, it comes closest to "Explicit is better than implicit" and "Errors should never pass silently".

I'm not sure it's worth changing in Jinja2 because of backward compatibility requirements, but Flask 1.0 seems like a reasonable point where behavior changes are expected anyway.

**Comment by mitsuhiko** [comment]
Generally not a fan of this at all. This drags down iteration times, breaks a ton of valuable patterns and makes templates harder to read. I understand that this is something that some people disagree with but I rather not change the defaults now.
