### ISSUE TITLE
Flask 0.11/httpbin: TypeError: <generator object MultiDict.lists at ...> is not JSON serializable

### ISSUE THREAD

**Issue by The-Compiler** [pallets/flask#1825]
Since updating from Flask 0.10.1 to 0.11.0, when trying to request `/response-headers` using [httpbin](https://github.com/Runscope/httpbin) I get:

```
[...] ERROR in app: Exception on /response-headers [GET]
Traceback (most recent call last):
  File ".../site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File ".../site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".../site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File ".../site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File ".../site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File ".../site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".../site-packages/httpbin/core.py", line 314, in response_headers
    response = jsonify(headers.lists())
  File ".../site-packages/httpbin/core.py", line 40, in jsonify
    response = flask_jsonify(*args, **kwargs)
  File ".../site-packages/flask/json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File ".../site-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File ".../json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File ".../json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File ".../json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File ".../site-packages/flask/json.py", line 83, in default
    return _json.JSONEncoder.default(self, o)
  File ".../json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <generator object MultiDict.lists at ...> is not JSON serializable
```

This is on Python 3.5 with httpbin 0.4.1

**Comment by untitaker** [comment]
That appears to be a bug in httpbin when using newer Werkzeug documentations on Python 3. This line in particular:

      File ".../site-packages/httpbin/core.py", line 314, in response_headers
        response = jsonify(headers.lists())

**Comment by The-Compiler** [comment]
I don't really follow, as I only upgraded Flask and not Werkzeug and I haven't seen this before - also, it seems the [Werkzeug documentation says](http://werkzeug.pocoo.org/docs/dev/datastructures/#werkzeug.datastructures.MultiDict.lists) that `MultiDict.lists()` should return a list?

**Comment by ThiefMaster** [comment]
maybe the docs needs to be updated. it does make sense for it to return an iterator in python3 though since that's what `dict.values()` etc. do

**Comment by untitaker** [comment]
The behavior of all the iter-* methods and related ones is like dict in the respective version.

In particular, lists returns a list in Py2 and an iterator in Py3.

On 30 May 2016 10:26:00 CEST, Florian Bruhin <notifications@github.com> wrote:
>I don't really follow, as I only upgraded Flask and not Werkzeug and I
>haven't seen this before - also, it seems the [Werkzeug documentation
>says](http://werkzeug.pocoo.org/docs/dev/datastructures/#werkzeug.datastructures.MultiDict.lists)
>that `MultiDict.lists()` should return a list?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/1825#issuecomment-222440025

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
And yes, the docs are a bit unfortunate right now.

On 30 May 2016 10:27:37 CEST, Adrian <notifications@github.com> wrote:
>maybe the docs needs to be updated. it does make sense for it to return
>an iterator in python3 though since that's what `dict.values()` etc. do
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/1825#issuecomment-222440350

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by The-Compiler** [comment]
Okay - I'll open a httpbin bug then. However I still wonder why this worked before the Flask update? Did `flask.jsonify` just happen to accept generators (and convert them to lists?) and doesn't anymore with the json changes in 0.11?

**Comment by ThiefMaster** [comment]
I think previously it did something similar to `dict(value or {}, **kwargs)` since it only accepted a single dict or kwargs anyway.

**Comment by mitsuhiko** [comment]
I can't see how Flask would change this. This is an ancient change in Werkzeug itself. I suppose this might just have forced Werkzeug to update elsewhere. This also is a Python 3 specific issue in httpbin.

**Comment by mbra** [comment]
The reasons for breaking are different on python 2 and 3, on python 2 it breaks because of https://github.com/pallets/flask/issues/1877 which might or might not be considered a Flask "bug".

The error on python 3 is IMHO really not something Flask can do anything about.

**Comment by untitaker** [comment]
@mbra Hence the two different issues. :)

**Comment by The-Compiler** [comment]
Yeah - I opened the httpbin bug and for now pinned Flask to 0.10 (with Werkzeug 0.11.10 FWIW) where this doesn't happen. :wink:
