### ISSUE TITLE
`flask --version` fails

### ISSUE THREAD

**Issue by singingwolfboy** [pallets/flask#1828]
The `flask` CLI utility that ships with Flask 0.11 does not respond to the `--version` flag. I would expect the following output:

```bash
$ flask --version
Flask 0.11
Python 3.5.1
```

Instead I get the following output:
```bash
$ flask --version
Error: no such option: --version
```

**Comment by davidism** [comment]
Deferring due to pallets/click#590.  The `--` options were removed from Flask (#1820) due to issues with Click's pipeline, so I'm hesitant to add such an option back in before that's fixed.  @pallets/devteam-click @pallets/devteam-flask

**Comment by mitsuhiko** [comment]
`--version` could actually work. I'm happy to add this even without the fixes necessary in click. The version is hardcoded anyways.

**Comment by RaHus** [comment]
Is the above patch on the right track? I couldn't find how to reuse click.version_option due to it being a decorator so i followed the docs and the previous (now removed) implementation of the '--' options to compose this patch

**Comment by mitsuhiko** [comment]
@RaHus generally yes but don't use `sys.version_info[:3]` in case we ever get Python 3.10 etc.

**Comment by mitsuhiko** [comment]
@RaHus generally just print the entire version.

**Comment by RaHus** [comment]
@mitsuhiko Done. Is there any docs i need to add somewhere? I figure its too standard an option to document.

**Comment by mitsuhiko** [comment]
Can you send a pull request?

**Comment by RaHus** [comment]
@mitsuhiko I did make a pull request and i see it listed above. I case i messed something up ts here https://github.com/pallets/flask/pull/1848

**Comment by mitsuhiko** [comment]
Sorry, github did not show it with the out update. Merged. Thanks!
