### ISSUE TITLE
Document Auth&Auth

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/flask#183]
People seem to be put off by the lack of auth&auth in Flask. Just because it's not there it does not mean it's hard. Documentation should show an example, maybe with Flask-SQLAlchemy.

Related feedback issues:

* http://feedback.flask.pocoo.org/message/54

**Comment by jeffwidman** [comment]
Auth is part of the current tutorial and some general pointers toward security extensions were added in #1854

**Comment by untitaker** [comment]
this issue was about auth&auth (which seems to be an ebay-thing?), but I don't know if it's relevant anymore.

**Comment by jeffwidman** [comment]
Ah, I didn't realize auth&auth was a specific authentication implementation... agree though, it doesn't really seem to be a thing anymore.
