### ISSUE TITLE
Failing test: test_egg_installed_paths

### ISSUE THREAD

**Issue by djc** [pallets/flask#1835]
While trying to package 0.11 on Gentoo Linux, I've run into the following test failure:

```
============================================= FAILURES =============================================
_____________________________________ test_egg_installed_paths _____________________________________

install_egg = <function inner at 0x7f5eebfa9668>
modules_tmpdir = local('/var/tmp/portage/dev-python/flask-0.11/temp/pytest-of-portage/pytest-0/test_egg_installed_paths0/modules_tmpdir')
modules_tmpdir_prefix = local('/var/tmp/portage/dev-python/flask-0.11/temp/pytest-of-portage/pytest-0/test_egg_installed_paths0/modules_tmpdir')

    def test_egg_installed_paths(install_egg, modules_tmpdir,
                                 modules_tmpdir_prefix):
        modules_tmpdir.mkdir('site_egg').join('__init__.py').write(
            'import flask\n\napp = flask.Flask(__name__)'
        )
>       install_egg('site_egg')

tests/test_instance_config.py:111: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/conftest.py:116: in inner
    egg_path, = modules_tmpdir.join('dist/').listdir()
/usr/lib64/python2.7/site-packages/py/_path/local.py:379: in listdir
    names = py.error.checked_call(os.listdir, self.strpath)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <py._error.ErrorMaker object at 0x7f5eee4382d0>, func = <built-in function listdir>
args = ('/var/tmp/portage/dev-python/flask-0.11/temp/pytest-of-portage/pytest-0/test_egg_installed_paths0/modules_tmpdir/dist',)
kwargs = {}, __tracebackhide__ = False, cls = <class 'py.error.ENOENT'>
value = OSError(2, 'No such file or directory'), tb = <traceback object at 0x7f5eebfa6c68>
errno = 2

    def checked_call(self, func, *args, **kwargs):
        """ call a function and raise an errno-exception if applicable. """
        __tracebackhide__ = True
        try:
            return func(*args, **kwargs)
        except self.Error:
            raise
        except (OSError, EnvironmentError):
            cls, value, tb = sys.exc_info()
            if not hasattr(value, 'errno'):
                raise
            __tracebackhide__ = False
            errno = value.errno
            try:
                if not isinstance(value, WindowsError):
                    raise NameError
            except NameError:
                # we are not on Windows, or we got a proper OSError
                cls = self._geterrnoclass(errno)
            else:
                try:
                    cls = self._geterrnoclass(_winerrnomap[errno])
                except KeyError:
                    raise value
>           raise cls("%s%r" % (func.__name__, args))
E           ENOENT: [No such file or directory]: listdir('/var/tmp/portage/dev-python/flask-0.11/temp/pytest-of-portage/pytest-0/test_egg_installed_paths0/modules_tmpdir/dist',)

/usr/lib64/python2.7/site-packages/py/_error.py:84: ENOENT
```

Also note that it's pretty unclear that you now require py.test for test running, might want to add that as an explicit dependency somehow.

**Comment by untitaker** [comment]
This test runs `python setup.py bdist_egg` before asserting that the `dist` directory exists ([see code](https://github.com/pallets/flask/blob/ba07f5b/tests/conftest.py#L112) My suspicion is that this call fails silently, although we do check the exit code.

Could you `cd` into `modules_tmpdir` for the failing testrun and run `python setup.py bdist_egg` manually?

**Comment by untitaker** [comment]
Regarding the bad documentation, see https://github.com/pallets/meta/issues/17

**Comment by djc** [comment]
That seems to work.

The problem might be that the packager runs the test suite in a sandbox, maybe this somehow affects what happens?

As for your documentation; it's great that there's a Makefile and stuff. Still, I'd argue your project should do a little more work to align with the ecosystem standards. Even if I use the Makefile, there should be like a `test_requires` in `setup.py` to tell me that `py.test` is needed.

**Comment by djc** [comment]
(`make test` fails the same way as invoking `py.test`.)

**Comment by untitaker** [comment]
To clarify, does the command work within the sandbox as well?

**Comment by mitsuhiko** [comment]
@djc test_requires is stupid because it installs eggs into the working directory. Is there an alternative we could use that would be equally acceptable but does not do that?

**Comment by djc** [comment]
It's all about it being in a standard place where we'll look for it. So either `setup.py` (but a comment is fine, too -- maybe still include `require` somehow?) or some `*-requirements.txt`. IMO dependency changes should also feature prominently in the changelog (IIRC in this case there is mention of it, somewhere deep at the bottom).

**Comment by jeffwidman** [comment]
@djc does @mitsuhiko's fix in fd1a355899691215bda059f410256e6fff470955 suffice and can we close this issue?

**Comment by djc** [comment]
I think it suffices for documentation of the test requirements; however, I don't think it solves the test failure?

**Comment by untitaker** [comment]
I have no idea why the tests fail for you -- we can leave this open, but we don't know how to help.
