### ISSUE TITLE
ExtDeprecationWarning show file path with deprecated import

### ISSUE THREAD

**Issue by sibeliusseraphini** [pallets/flask#1836]
It should be very useful to warning which files have deprecated imports

**Comment by ThiefMaster** [comment]
You could use [flask-ext-migrate](https://github.com/pallets/flask-ext-migrate) to automatically update your files to use `flask_*` imports instead.

**Comment by sibeliusseraphini** [comment]
it just work with one file per time this script, and I did update all my imports, but I still receiving this warning.

maybe it is a dependency, but how can I check which one if I don't know which file is generating this warning

**Comment by ThiefMaster** [comment]
search for `flask.ext` ;)

Anyway, I believe #1831 solved your problem (but it's not in the latest release).

**Comment by sibeliusseraphini** [comment]
I will try with master version, thanks

**Comment by sibeliusseraphini** [comment]
fixed on master, maybe you should release as 0.11.1

**Comment by ThiefMaster** [comment]
I don't think it makes much sense to push out an extra release just for this - it doesn't break anyone's code and is not a showstopper for anything. I think it makes more sense to wait until there are more improvements/fixes and then do another release.

**Comment by sibeliusseraphini** [comment]
break.feature.fix, I can wait, no problem
