### ISSUE TITLE
[CLI] Option to pass the FLASK_APP variable as an argument 

### ISSUE THREAD

**Issue by yashmehrotra** [pallets/flask#1842]
For the latest CLI feature (Thanks a lot for that BTW), to run a app, we currently do:
```
$ export FLASK_APP=/path/to/hello.py
$ export FLASK_DEBUG=1
$ flask run
```

Wouldn't it be nice, if app and debug variables could also be passed as arguments, That way, we can also do
```
$ flask --app=/path/to/hello.py --debug run
```

I as a user would prefer the first option in a production environment, but for development, the second option (CLI arguments) would be much comfortable.

What do you guys think about this ?

**Comment by RonnyPfannschmidt** [comment]
thats planned, there is a click bug preventing it (we had it on master for a while and it "broke the world")
once the click bug is fixed it will be introduced again

**Comment by yashmehrotra** [comment]
@RonnyPfannschmidt Ah, yeah, I saw the other issue. Thanks!
