### ISSUE TITLE
Middleware doesn't execute inside test_request_context()

### ISSUE THREAD

**Issue by amorey** [pallets/flask#1844]
I'm trying to write a unittest for a custom middleware layer in my app and I'm having difficulty getting the middleware to execute inside a test request context. Here's a simple script that illustrates the problem:

```python
from flask import Flask, url_for

class Middleware(object):
    def __init__(self, app):
        print ' - initialized middleware'
        self.app = app

    def __call__(self, environ, start_response):
        print ' - executed middleware'
        return self.app(environ, start_response)

# create app
app = Flask(__name__)

# add middleware
app.wsgi_app = Middleware(app.wsgi_app)

# add route
@app.route('/')
def index():
    return 'index'

# test GET                                                                      
print '\nTesting GET...'
resp = app.test_client().get('/')
print ' - Response: ' +	resp.data

# test context                                                                  
print '\nTesting request context...'
with app.test_request_context('/'):
    app.preprocess_request()
    ret = app.dispatch_request()
    resp = app.make_response(ret)
    resp = app.process_response(resp)
    print ' - Response: ' + resp.data
```

The middleware executes inside the test client GET request but not inside the test request context. Here's the output:
```bash
$ python test.py
 - initialized middleware

Testing GET...
 - executed middleware
 - Response: index

Testing request context...
 - Response: index
```

Am I doing something wrong or is this the intentional behavior inside a test request context? I'm using Flask 0.11 and Werkzeug 0.11.10.

Thanks for your help!

**Comment by mitsuhiko** [comment]
WSGI middlewares cannot access a request context. That would be a violation of separation of concerns here.

**Comment by davidism** [comment]
If you're in a request context, you're already in Flask, not the middleware around it.

**Comment by amorey** [comment]
Thanks, that makes sense.

What's the best way to test middleware inside a Flask app? I see how to write a test for each individual middleware layer but if you want to test how the middleware behaves inside the app it seems like the only option is to execute a full request. Is there a better way to write a more targeted app-level test?

**Comment by jeffwidman** [comment]
@amorey it's a good question, but a better fit for StackOverflow rather than the issue tracker.
