### ISSUE TITLE
Add tests target that uses simplejson

### ISSUE THREAD

**Issue by davidism** [pallets/flask#1846]
https://github.com/pallets/flask/issues/1602#issuecomment-154127373

Should add tox envs for testing `flask.json` with simplejson installed.  Possibly add this to the travis matrix.

**Comment by JamesTFarrington** [comment]
Are there any specific features of simplejson we want to test, or just run the regular tests with simplejson?

**Comment by ThiefMaster** [comment]
Just for the future, "Fixed #1846" is not a really good commit message. It's meaningless without extra context (going to github). Also, your Git is configured to commit with the email "james@localhost.localdomain" - might want to fix that :)

**Comment by jeffwidman** [comment]
Good catch @ThiefMaster sorry I overlooked this. <sheepish>

**Comment by davidism** [comment]
#1869
