### ISSUE TITLE
Link to contributing.rst from the main Flask docs

### ISSUE THREAD

**Issue by jeffwidman** [pallets/flask#1880]
Make it easier for folks to find our contributing docs. 

Not sure where in the main Flask docs to put this, but it would be good to add somewhere. There's been a few Pycon sprinters who tried searching our docs for the contributing info rather than looking in the source repo.

**Comment by karlw00t** [comment]
Linked from README, not the sure if it's going to build into the the docs, but is making it more visible
https://github.com/pallets/flask/pull/1883

**Comment by jeffwidman** [comment]
I think that's probably good enough for now
