### ISSUE TITLE
Blueprint static content only works when response.direct_passthrough is False

### ISSUE THREAD

**Issue by joaodlf** [pallets/flask#1895]
I'm using the latest version of Flask (0.11.1) and the built in dev server, with the following Blueprint:

`blueprint = Blueprint("admin", __name__, url_prefix="/admin", template_folder="templates", static_folder="static")
`
The template folder is working as expected, but any resources inside the static folder throw a **RuntimeError: Attempted implicit sequence conversion but the response object is in direct passthrough mode.**

After searching around for this error, I found the following discussion:
https://github.com/closeio/Flask-gzip/issues/7

The solution used in that third party extension was to put in place the following code on app.after_request:
`response.direct_passthrough = False`

My static content loads fine with the above. 

I was wondering if anyone has run into this issue with Blueprints and if there is a better workaround.

**Comment by davidism** [comment]
As I said on the SO question, I can't reproduce your issue.  If this is a bug with Flask, you'll need to post an example demonstrating that.  Please use SO for questions about using Flask.
