### ISSUE TITLE
Missing import on Flask 0.11.1

### ISSUE THREAD

**Issue by wschmrdrNS** [pallets/flask#1897]
```
Traceback found (redacted for relevancy to Flask):
  File "/usr/local/lib/python2.7/dist-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 27, in <module>
    from . import json, cli
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 17, in <module>
    import click
ImportError: No module named click
```

Just recently upgraded from 0.10 to 0.11. Did not see a requirements.txt for 3rd party dependencies.

**Comment by ThiefMaster** [comment]
https://github.com/pallets/flask/blob/master/setup.py#L77

**Comment by wschmrdrNS** [comment]
OK. Please be aware that going from 0.10.1 to 0.11.1 did not install click for me; I had to upgrade to 0.11 and THEN to 0.11.1 for it to work.

**Comment by untitaker** [comment]
@wschmrdrNS How did you install Flask?

**Comment by wschmrdrNS** [comment]
sudo pip install --upgrade -r requirements.txt

Inside of requirements.txt for my project, I have:
Flask==0.11.1

**Comment by davidism** [comment]
I can't reproduce your issue.  I created a Python 2.7 env, added `Flask==0.10.1` in `requirements.txt`, `pip install -r requriements.txt`, modified to `==0.11.1`, `pip install -U -r requirements.txt`.  Flask was upgraded and Click was installed.

Unrelated, but never `sudo pip install`.  Install in a virtualenv.

**Comment by jonathansp** [comment]
Please, remove 0.11 from https://pypi.python.org/pypi

**Comment by untitaker** [comment]
Why?

**Comment by jonathansp** [comment]
Sorry @untitaker, it happened to me as I use --no-deps in production environment. Solved here.
