### ISSUE TITLE
Should link to Werkzeug’s docs prominently

### ISSUE THREAD

**Issue by SimonSapin** [pallets/flask#190]
Many Flask questions on the mailing list or IRC are easily answered by reading Werkzeug documentation. Maybe Flask docs should make more obvious (and repeat everywhere) that many thing (Request and Response objects, routing, ...) are just inherited from Werkzeug, and link to the relevant documentation.

**Comment by doobeh** [comment]
I'll give this a go

**Comment by frankV** [comment]
Can we merge this with #1430?

**Comment by frankV** [comment]
If we want to these to be "more prominent" could we use an admonition?

example:
<img width="751" alt="screen shot 2016-06-02 at 2 47 56 pm" src="https://cloud.githubusercontent.com/assets/503796/15762152/10b38df4-28d1-11e6-9a1a-33a2890b8324.png">

**Comment by brianrusso** [comment]
The flask [docs](http://flask.pocoo.org/docs/0.12/) prominently mention Werkzeug and link to it.

**Comment by davidism** [comment]
We could always link more, but this is too broad to evaluate.
