### ISSUE TITLE
Google App Engine ImportError: No module named msvcrt

### ISSUE THREAD

**Issue by dhstack** [pallets/flask#1901]
Because [Click](http://click.pocoo.org/5/) was added to Flask 0.11 for the [New Command Line Interface](http://flask.pocoo.org/docs/0.11/cli/), and Click imports the Windows only module [msvcrt](https://docs.python.org/2/library/msvcrt.html), and the [Google App Engine local development server](https://cloud.google.com/appengine/docs/python/tools/using-local-server) doesn't contain this module, an import error is thrown.

![image](https://cloud.githubusercontent.com/assets/2013388/15935738/36ee00b6-2e1d-11e6-85a7-3b04de953659.png)

I've [created a workaround](https://github.com/gae-init/gae-init/pull/527) for the [gae-init project](https://github.com/gae-init/gae-init) (by modifying the App Engine config file), but it would be best to have a fix come directly from Flask/Click since there are likely many more people who will experience this issue when using Flask 0.11 with Google App Engine.

**Comment by dhstack** [comment]
Click Issue:
https://github.com/pallets/click/issues/594

**Comment by mitsuhiko** [comment]
Closing this because this is a click thing.

**Comment by pvlele** [comment]
I am also facing same issue.. How did you resolved this?
