### ISSUE TITLE
AttributeError: 'module' object has no attribute 'exc_clear'

### ISSUE THREAD

**Issue by losintikfos** [pallets/flask#1903]
We are getting below error when building `flask-mongoengine` with `pypy3` on travis-ci:

    1) ERROR: Failure: AttributeError ('module' object has no attribute 'exc_clear')

     ----------------------------------------------------------------------

     Traceback (most recent call last):

    .eggs/nose-1.3.7-py3.2.egg/nose/failure.py line 39 in runTest

      raise self.exc_val.with_traceback(self.tb)

    .eggs/nose-1.3.7-py3.2.egg/nose/loader.py line 418 in loadTestsFromName

      addr.filename, addr.module)

    .eggs/nose-1.3.7-py3.2.egg/nose/importer.py line 47 in importFromPath

      return self.importFromDir(dir_path, fqname)

    .eggs/nose-1.3.7-py3.2.egg/nose/importer.py line 94 in importFromDir

      mod = load_module(part_fqname, fh, filename, desc)

    tests/__init__.py line 1 in <module>

      import flask

    .tox/pypy3-medev/site-packages/flask/__init__.py line 21 in <module>

      from .app import Flask, Request, Response

    .tox/pypy3-medev/site-packages/flask/app.py line 24 in <module>

      from .helpers import _PackageBoundObject, url_for, get_flashed_messages, \

    .tox/pypy3-medev/site-packages/flask/helpers.py line 42 in <module>

      from ._compat import string_types, text_type

    .tox/pypy3-medev/site-packages/flask/_compat.py line 82 in <module>

      raise AssertionError()

    .tox/pypy3-medev/site-packages/flask/_compat.py line 78 in __exit__

      sys.exc_clear()

       AttributeError: 'module' object has no attribute 'exc_clear'

Could this be a bug?

**Comment by ThiefMaster** [comment]
Same issue as mentioned in #1841?

**Comment by losintikfos** [comment]
@ThiefMaster same issue indeed.
