### ISSUE TITLE
Documentation with minor incorrection?!?

### ISSUE THREAD

**Issue by gustavooferreira** [pallets/flask#1905]
Hi,

On the **A Minimal Application** under Quickstart, you have code for a minimal Flask implementation, although it should be added the app.run so it can actually run the app, and load the server.
This is the form for applications that are connected to a WSGI server, which I believe beginners won't be doing that as one of their first steps.

Another minor correction, is on **URL Building** also under Quickstart, it has:
print url_for('profile', username='John Doe')
I believe should be : print url_for('user', username='John Doe')

**Comment by davidism** [comment]
The recommended way to run applications is with the `flask run` command, detailed below that.

`route` takes the name of the view function as the endpoint name by default.  The view function is `profile`.

**Comment by gustavooferreira** [comment]
Oh, I just realized this was a new feature from the 0.11 version, thank you for the clarifications on both points.

So I believe the snippet on the Python Package Index, should also be updated.
