### ISSUE TITLE
SessionInterface shouldn't hard code a fix for localhost when it comes to cookies

### ISSUE THREAD

**Issue by nickjj** [pallets/flask#1906]
The `get_cookie_domain` function specifically fixes issues with webkit browsers by doing this:

```python
# https://github.com/pallets/flask/blob/0.11.1/flask/sessions.py#L198-222
if rv == '.localhost':
    rv = None
```

The problem is that nowadays many people are using Docker and other techniques (Vagrant, etc.) to create a better development environment so they are no longer running Flask on `localhost`.

In Docker's case, you'd likely end up with an IP address based host name which means you'd set your `SERVER_NAME` to something like `192.168.99.100`.

At this point Chrome and other webkit based browsers will freak out by reject setting the cookie which in turn will make your Flask app throw CSRF token related issues when submitting forms.

Since Flask is already hard coding a fix for this, I think you should allow users to configure which domain name gets skipped with a proper config option.

This could be named something like `SESSION_COOKIE_IGNORE_DOMAIN` (feel free to improve the name :)). It could default to localhost so that it's backwards compatible and nothing changes for most users.

Right now the work around is to modify your `/etc/hosts` file to map an IP address to a FQDN with a TLD if you're stuck using an IP based `SERVER_NAME`. That seems a little lame and preventable at the Flask level.

What do you think?

**Comment by untitaker** [comment]
Better workarounds:

* explicitly set `SESSION_COOKIE_DOMAIN`
* Subclass `SessionInterface` and set `app.session_interface` to the new subclass

**Comment by nickjj** [comment]
If you set `SESSION_COOKIE_DOMAIN` to an IP address wouldn't Chrome still reject it?

**Comment by untitaker** [comment]
You can set it to `None` though.

I don't think this can be properly worked around at a Flask level. And actually I consider the workaround of assigning your dev server a proper hostname to be a good solution.

**Comment by nickjj** [comment]
Setting it to `None` results in the same issue as not setting it.

**Comment by untitaker** [comment]
Sorry, I misread the code

**Comment by untitaker** [comment]
Actually, as far as I understand, `SERVER_NAME` does not support IP addresses at all, and setting cookies on IP addresses is not supported at all: https://tools.ietf.org/html/rfc6265#section-5.1.3

**Comment by nickjj** [comment]
I have a bunch of students using an IP based `SERVER_NAME` and cookies are correctly set as long as they don't use a webkit based browser.

A couple of months ago I swear the spec was different. It was written such that IP addresses were valid.

**Comment by untitaker** [comment]
Are you possibly referring to RFC 2616 instead of the set of RFCs that
superseded it?

**Comment by dpalharini** [comment]
It is to late do add something in this post?   I hope not. 

I've been fought this problem for a week and find out that is possible to create session in the Chrome browser using IP. 

My config file has this configurations:

```
        SERVER_NAME = '192.168.0.6:5000'
        SESSION_COOKIE_NAME = '192.168.0.6:5000'
        SESSION_COOKIE_DOMAIN = '192.168.0.6:5000'
```

It allowed me to use a local virtual machine and the cookie worked perfectly on Chrome, without the need o a local FQDN .

**Comment by davidism** [comment]
It doesn't make sense to set `SESSION_COOKIE_NAME` to the IP addres, it can remain as the default, `'session'`. Other than that, yes, it appears Chrome allows IP addresses if they don't look like they're trying to be a match pattern (start with '.').

**Comment by untitaker** [comment]
It appears we have the exact same function in werkzeug.security that is also
vulnerable to this.

I suggest that this is fixed in a maintenance branch of Werkzeug, Flask is
changed to call the function from Werkzeug and then I will create a new
Werkzeug release. I don't know how to file a CVE though.

**Comment by davidism** [comment]
See #5051
