### ISSUE TITLE
TaggedJSONSerializer does not preserve int keys in dicts

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/flask#1908]
The `TaggedJSONSerializer` used for session serialization is rather smart when it comes to preserving types that usually cannot be JSON-encoded. However, it still has the problem that dict keys are converted to strings.

```
>>> from flask.sessions import TaggedJSONSerializer
>>> tj = TaggedJSONSerializer()
>>> tj.loads(tj.dumps({123: u'blah'}))
{u'123': u'blah'}
```

I think it would make sense to also tag the key here:

```
elif isinstance(value, dict):
    return dict((k, _tag(v)) for k, v in iteritems(value))
```

The one drawback I see is that there could be code relying on the implicit conversion right now..

**Comment by RonnyPfannschmidt** [comment]
a json mapping key is defined to be a string, it cannot be replaced by a tagged value without changing the way mappings are represented

you'd need list of key value paris in mappings with tagged values

**Comment by ThiefMaster** [comment]
ah true :/ would have to change the whole serialization logic for dicts to do that..

**Comment by RonnyPfannschmidt** [comment]
i would suggest documenting the use of tags only on what json considers a value
a separate serialier should be used for tagging on mapping keys
