### ISSUE TITLE
Wrong import json library

### ISSUE THREAD

**Issue by rearn** [pallets/flask#1911]
[This code](https://github.com/pallets/flask/blob/c5900a1adf8e868eca745225f3cf32218cdbbb23/flask/json.py#L23) is always import error.
(`simplejson` is not included in the `itsdangerous`.)
See: https://github.com/pallets/itsdangerous/blob/master/itsdangerous.py

**Comment by RonnyPfannschmidt** [comment]
indeed, how about a quick pull request removing the unnecessary lines?

**Comment by davidism** [comment]
That's the problem though, `itsdangerous` will never have `simplejson`, it's aliased to `json`.  Flask should just do its own check, we're not getting anything by importing itsdangerous's or werkzeug's import.

**Comment by mitsuhiko** [comment]
For the record: older versions of itsdangerous had this named `simplejson` which is why this was a import that supported both.

**Comment by mitsuhiko** [comment]
At the very least we should bump the dependency to a version of itsdangerous that includes `json` always.

**Comment by untitaker** [comment]
What about just copying the logic from itsdangerous?

**Comment by ThiefMaster** [comment]
Seems more sensible to me than relying on an import in another library. I've always found it weird to make imports part of the public API.

**Comment by mitsuhiko** [comment]
Personally I would prefer if we documented the json attribute in itsdangerous and make it part of the public API then import it and require a specific version of it. I do not like the idea of having different json modules for Flask and itsdangerous because it becomes confusing for a user if different ones are picked up due to the different behavior on simplejson vs json on Python 3.

**Comment by davidism** [comment]
Of course, the import is duplicated anyway in Werkzeug for its json support, and we can't get that one from itsdangerous.  When would there ever be a situation where itsdangerous imports one but Flask imports the other?  My vote is for just duplicating the import.

**Comment by mitsuhiko** [comment]
The only json import that is user facing in Werkzeug is in contrib so that's not really a concern there.

**Comment by davidism** [comment]
Except we're talking about moving it into main right now.

**Comment by mitsuhiko** [comment]
If we move Json code into main werkzeug then we need to figure out a long term solution for this problem. Getting the imports right everywhere is tricky. If we do it this way then we should add comments everywhere that clarify the import order so that if anyone ever changes it anywhere, we fix it in all libraries.

**Comment by ThiefMaster** [comment]
Would using something like `anyjson` make sense?

**Comment by mitsuhiko** [comment]
I don't want to go down that path. But I can see that in the future there might be a simplejson2 or something like this. Why? Because stuff like this keeps happening in the Python world :(

**Comment by mitsuhiko** [comment]
JFTR. The stdlib json inclusion was supposed to fix this but it turns out that the JSON module in the stdlib is inferior to the one in simplejson.

**Comment by davidism** [comment]
Maybe it's time to just pick one?  https://github.com/pallets/flask/issues/1602#issuecomment-154135639

**Comment by mitsuhiko** [comment]
I don't think that is possible. We had issues before forcing simplejson on people.

**Comment by davidism** [comment]
Then just go with `json`?  The tests pass for both, and there's only one line of code that does anything different between the two (dealing with slash escapes in some version of simplejson).

**Comment by davidism** [comment]
If we decide to figure out #1602, then users will have the option of adding simplejson back in if it's something they want.  Honestly, I'm not sure how many people are even *aware* that Flask will use simplejson if it's available.  It's not documented anywhere.

**Comment by mitsuhiko** [comment]
We should definitely not go with `json`. It's slower, it's very unmaintained, it heavily varies between different versions of Python.

**Comment by sahildua2305** [comment]
@mitsuhiko Is this resolved?

**Comment by davidism** [comment]
The part that's marked "beginner friendly" is.

**Comment by sahildua2305** [comment]
@davidism So what's the next step with this now? I'd love to dive into this.
