### ISSUE TITLE
Use pip in upgrade documentation instead of easy_install

### ISSUE THREAD

**Issue by johnthagen** [pallets/flask#1915]
In the upgrade docs, `easy_install` is listed as the example to use to upgrade: 
http://flask.pocoo.org/docs/0.11/upgrading/

But in the installation docs, both `pip` and `easy_install` are listed, though `pip` is used more and is recommended:
http://flask.pocoo.org/docs/0.11/installation/

I would recommend the upgrading section be switched to use `pip`.

**Comment by jeffwidman** [comment]
Fixed by #1918
