### ISSUE TITLE
Remove easy_install from installation docs

### ISSUE THREAD

**Issue by jeffwidman** [pallets/flask#1919]
As pointed out in #1915, http://flask.pocoo.org/docs/0.11/installation/ mentions both `pip` and `easy_install`. 

`pip` seems to be the canonical way to manage packages these days, so I vote we drop `easy_install` from the install docs.

**Comment by WenchenLi** [comment]
vote for ```pip``` as well! It's well managed than `easy_install`

**Comment by jeffwidman** [comment]
Fixed in #1920
