### ISSUE TITLE
Next/Back Buttons in Documentation

### ISSUE THREAD

**Issue by SwampYeti** [pallets/flask#1924]
I would like to request adding a **Next/Back** Button at the end of each page within the official documentation. Once you get to the end of the document you have to scroll all the way back up to the very top of the page and go to the next article. I think it would be much nicer to have this feature and the documentation would flow much better.

**Comment by davidism** [comment]
<kbd>Home</kbd>?

They're already in the sidebar.  I'd rather have a fixed sidebar.

**Comment by SwampYeti** [comment]
That would work as well, just something that would make it easier to navigate through the docs wherever your at on the page.

**Comment by jeffwidman** [comment]
I'm going to close this as I think it's unlikely to change. I know [several maintainers would like to see the project move to using RTD](https://github.com/pallets/meta/issues/15), and if we used their default theme that'd hopefully make navigation simpler. So many projects use RTD that my eyes are very accustomed to navigating the default RTD theme.
