### ISSUE TITLE
Unhelpful Error Message on FLASK_APP to Bad Path

### ISSUE THREAD

**Issue by cancan101** [pallets/flask#1926]
If the path specified in `FLASK_APP` does not exist (for example it is a typo), then the unhelpful error message is shown:
```
ImportError: Import by filename is not supported.
```

This is even though I have:
```
FLASK_APP=alex/server2.py
```
which is "path-like" and not module like.

Perhaps [this line](https://github.com/pallets/flask/blob/cd1a9b7d545a9566b6d8ab861572f2e80c67916e/flask/cli.py#L106) should be modified to return `True` for file-like objects.

**Comment by robbielaldrich** [comment]
How about 

```python
if os.path.isfile(app) or os.path.isdir(app):
    return prepare_exec_for_file(app)
```

**Comment by untitaker** [comment]
Fixed by https://github.com/pallets/flask/pull/1950
