### ISSUE TITLE
JSON Parsing on empty request content with RequestParser

### ISSUE THREAD

**Issue by thanhtungka91** [pallets/flask#1933]
From flask-restful/flask-restful#163.

**Comment by tdpsk** [comment]
I agree that this is weird but acceptable behavior on the client side. Therefore I created a pull request to fix this. However there is a larger discussion surrounding this, see pull request.

**Comment by untitaker** [comment]
This behavior is completely incompliant, if you really need this you should rather catch ValueError. But an empty file is not valid JSON.
