### ISSUE TITLE
May flask support live settings like django-constance

### ISSUE THREAD

**Issue by Colstuwjx** [pallets/flask#1957]
Hi, I'm new to flask, and just wonder if flask could support editing the settings on admin and hot reload, like the django-constance worked.

Thx.

**Comment by ThiefMaster** [comment]
This is impossible to do if you have more than one webserver/process. Also, in production it's not a good idea anyway. `app.config`-level settings are usually system related and not things that a regular "admin" should be able to change.

**Comment by davidism** [comment]
Nothing stopping you from implementing a similar extension, but it's not something Flask will support directly.
