### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by MustafaAdam** [pallets/flask#1962]
running py.test on the tests folder, I get a few failures

test_safe_join and test_safe_join_exceptions both fail.
The first one fails with a 'TypeError: safe_join() missing 1 required positional argument: 'filename'
The second fails with a 'TypeError: safe_join() takes 2 positional arguments but 3 were given'

Also

test_send_file_last_modified fails. 
'rv.last_modified' is None. Hence, 'assert rv.last_modified == datetime.datetime(1999,1,1,0,0) fails

I'm somewhat of a amatuer programmer so maybe it's just me :)

**Comment by wgwz** [comment]
did you follow [here](https://github.com/pallets/flask/blob/master/CONTRIBUTING.rst#running-the-testsuite)? (how-to running test suite)

**Comment by MustafaAdam** [comment]
Just did. Sorry i didn' read that beforehand :).  tox succeeds, py.test still fails.
I don't understand how tox works, but I guess everything works as it supposed to do
