### ISSUE TITLE
Logbook integration?

### ISSUE THREAD

**Issue by jab** [pallets/flask#1964]
Just noticed Logbook 1.0 was released a month ago, and was reminded of discussion about it on the mailing list (e.g. http://librelist.com/browser/flask/2011/12/28/flask-+-logbook/). Armin mentioned his desire to add Logbook integration to Flask in that 5-year-old thread, but I didn't see any mention of it here in the tracker, so I figured I'd open a ticket. If that's no longer the intention please close, but either way looking forward to finding out the latest plans.

**Comment by jab** [comment]
Probably also worth adding at least a mention of Logbook somewhere on the flask.pocoo.org/docs site. (Fans of both Flask and Logbook who know they're by the same author naturally wonder what the vision is and why neither's site currently mentions the other.) Will be especially good if Logbook ends up moving under the Pallets umbrella: getlogbook/logbook#203

**Comment by untitaker** [comment]
Sorry for the slow reply, I don't think integrating logbook is currently a priority. It would be a nice-to-have, but not in core-Flask.

**Comment by jab** [comment]
Thanks for the update.
