### ISSUE TITLE
Implement RFC 7233

### ISSUE THREAD

**Issue by magne4000** [pallets/flask#1971]
It would be great to support [RFC 7233 : Hypertext Transfer Protocol (HTTP/1.1): Range Requests](https://tools.ietf.org/html/rfc7233) for next major version, at least for non multipart/byteranges media type.

I'm willing to implement this, so please share your thoughts about this.

What must be done:
- Modify `send_file` method to support Range Requests
 - Use existing `conditionnal` parameter to enable Range Requests support ?

**Comment by davidism** [comment]
> I'm willing to implement this

Go for it.

**Comment by magne4000** [comment]
This will actually need some modifications on werkzeug side also, like a more complete approach of https://github.com/pallets/werkzeug/pull/868/files

**Comment by magne4000** [comment]
Also https://github.com/pallets/werkzeug/issues/978

**Comment by magne4000** [comment]
The doc of `send_file` method is already quite heavy, I was thinking of adding something like this:
```
If `add_etags=True`, `conditional=True` and `filename` is provided, this
method will try to upgrade the response stream to support range requests.
This will allow the request to be answered with partial content response.
```
Does some of you have a better idea ?

**Comment by untitaker** [comment]
I don't think it makes sense anymore to invoke `make_conditional` only when `add_etags` is set (i.e. dedent the `if conditional` block)

**Comment by magne4000** [comment]
See PR https://github.com/pallets/flask/pull/2031
