### ISSUE TITLE
"Larger Applications" docs don't play nicely with flask run

### ISSUE THREAD

**Issue by aaronkavlie-wf** [pallets/flask#1980]
The [Larger Applications docs](http://flask.pocoo.org/docs/0.11/patterns/packages/) recommend creating a `runserver.py` as follows:

```python
from yourapplication import app
app.run(debug=True)
```

This runs counter to the advice in the [Development Server](http://flask.pocoo.org/docs/0.11/server/) doc for working with the `flask run` command — the `app.run()` call should be under `if __name__ == '__main__'`.

That makes it work properly, anyway. But when using `flask run`, the `runserver.py` file can be removed altogether.

**Comment by untitaker** [comment]
@wgwz Are you interested in fixing this as well?

**Comment by wgwz** [comment]
Sure, I've actually had this on my to-do list :) I will work on it this week.

**Comment by wgwz** [comment]
Do we want to add a *setup.py* into this pattern? Or use `export FLASK_APP=runserver.py`? It seems that the only way to remove *runserver.py*, is if we install *yourapplication/* as a package or use `export FLASK_APP=yourapplication/__init__.py`? @untitaker What do you think we should do here?

**Comment by untitaker** [comment]
Adding a setup.py is the correct thing to do.

On 9 September 2016 23:45:00 CEST, Kyle Lawlor <notifications@github.com> wrote:
>Do we want to add a *setup.py* into this pattern? Or use `export
>FLASK_APP=runserver.py`? It seems that the only way to remove
>*runserver.py*, is if we install *yourapplication/* as a package or use
>`export FLASK_APP=yourapplication/__init__.py`? @untitaker What do you
>think we should do here? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/1980#issuecomment-246049285

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
Does #2021 close this issue completely @wgwz?

**Comment by wgwz** [comment]
Yup.

**Comment by untitaker** [comment]
:100:
