### ISSUE TITLE
examples/flaskr test error

### ISSUE THREAD

**Issue by janreyho** [pallets/flask#1982]
```
import os
import flaskr
import unittest
import tempfile

class FlaskrTestCase(unittest.TestCase):

    def setUp(self):
        self.db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
        flaskr.app.config['TESTING'] = True
        self.app = flaskr.app.test_client()
        with flaskr.app.app_context():
            flaskr.init_db()

    def tearDown(self):
        os.close(self.db_fd)
        os.unlink(flaskr.app.config['DATABASE'])
        
    def test_empty_db(self):
        rv = self.app.get('/')
        assert b'No entries here so far' in rv.data
if __name__ == '__main__':
    unittest.main()
```

(flask) ➜  flask-demo git:(master) ✗ python tests/flaskr_tests.py
ERROR: test_empty_db (__main__.FlaskrTestCase)
Traceback (most recent call last):
  File "tests/flaskr_tests.py", line 9, in setUp
    self.db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
AttributeError: 'module' object has no attribute 'app'

Ran 1 test in 0.004s
FAILED (errors=1)

**Comment by untitaker** [comment]
This should be fixed by https://github.com/pallets/flask/pull/1945. @janreyho Could you test with the version in the master branch?
