### ISSUE TITLE
Setting items on `response.header` with bytestrings results in new headers in Python 3

### ISSUE THREAD

**Issue by jameshiew** [pallets/flask#1986]
Minimal example below

``` python
# coding=utf8
from flask import Flask, Response

app = Flask(__name__)

@app.route('/')
def hello():
    response = Response("!!!")
    response.headers[b'Server'] = 'Flask'
    return response
```

In Python 2.7.12, the resulting response has a HTTP header of `Server: Flask`. In Python 3.5.2, the resulting response has HTTP headers of `Server: Werkzeug/0.11.10 Python/3.5.2` and `b'Server': Flask`.  Python 2 has the expected behavior.

Testing from within a Python 3 venv, `pip freeze` output is:

```
click==6.6
Flask==0.11.1
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.10
```

**Comment by qingyunha** [comment]
Maybe because of this, in python 2
```
b"Server"  ==  "Server"
True
```

in Python 3
```
b"Server"  ==  "Server"
False
```

**Comment by mitsuhiko** [comment]
It's not super great but the API does not support bytes on 3.x for keys. Technically not a bug.

**Comment by davidism** [comment]
I'm curious why you have a `b` string for the header name in the first place. Anyway, this is Werkzeug behavior, not Flask. If you really need this please file against Werkzeug, should be a pretty straightforward fix if you're interested in making a PR.
