### ISSUE TITLE
Disable OS-level autocorrect in the interactive debugger

### ISSUE THREAD

**Issue by alexwlchan** [pallets/flask#1989]
If you’re using the interactive debugger in the web browser, and autocorrect is feeling aggressive, it can kick in and try to “fix” the Python commands you’re typing. This is annoying for the end-user, and rarely helpful as autocorrect doesn’t know about Python. More than once this has bitten me, causing me to write invalid Python, or for variable names to change case mid-command.

I don’t have time to create a patch now, but I think the fix is just adding the following attribute to the `<input>` tag where you type commands:

    autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"

This probably isn’t really Flask’s fault – the OS is what actually makes the unhelpful autocorrections – but it seems like something Flask should be able to fix.

I spotted this on the developer builds of OS&nbsp;X Sierra, where autocorrect seems noticeably keener (especially in `<input>` fields) than older versions.

* Python 3.5.0
* Flask 0.11.1
* Werkzeug 0.11.10

**Comment by ThiefMaster** [comment]
Good idea, spell checking etc makes zero sense for fields where you enter code

**Comment by alexwlchan** [comment]
Fixing the debugger seems to be a single-line change: https://github.com/alexwlchan/werkzeug/commit/7a427e914a7075f0e50b207995b183b0d0ac72eb

I’m going to run with this fix locally for a few days and see if I spot any untoward behaviour; if not, I’ll open a pull request against the Werkzeug repo.

(I only did the interactive Python prompt in the debugger, because that’s the only place I can think of where you enter code. Is there anywhere in the debugger I should sort out at the same time?)

**Comment by untitaker** [comment]
Thanks, could you file a pull request?
