### ISSUE TITLE
access app.config via dot

### ISSUE THREAD

**Issue by qingyunha** [pallets/flask#1992]
How about implementing `__getattr__`  and ` __setattr__ ` for `flask.config.Config` to support dot access?  
instead of writing  `app.config["DATABASE"]`, I'd like to write `app.config.DATABASE`

**Comment by ThiefMaster** [comment]
Any special reason for this besides personal preference?

**Comment by ThiefMaster** [comment]
Actually, you can easily change this locally if you want this by simply subclassing Flask and setting `config_class = AttrConfig` after defining this class (or a more fancy version):

```python
class AttrConfig(Config):
    def __getattr__(self, attr):
        try:
            return self[attr]
        except KeyError:
            raise AttributeError('Invalid config option: ' + attr)
```

**Comment by qingyunha** [comment]
Thanks for you advice. Just personal preference, Closing

**Comment by qingyunha** [comment]
Maybe `get_namespace` could also return a Config instance.

**Comment by ThiefMaster** [comment]
not a good idea since you don't want the loading methods etc on those dicts - they return purely read-only views and any changes in a namespace wouldn't affect the main config (or vice versa)
