### ISSUE TITLE
No response and No exception traceback when render_template failed and DEBUG=True

### ISSUE THREAD

**Issue by guyskk** [pallets/flask#1995]
Here is the code:

app.py

```
from flask import Flask, render_template

app = Flask(__name__)
app.config['DEBUG'] = True

@app.route('/')
def index():
    return render_template('unknown')

if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('127.0.0.1', 5000, app)
```

Run it by 

```
python app.py
```

or  

```
export FLASK_APP=app.py 
flask run
```

then visit `http://127.0.0.1:5000` will see `ERR_EMPTY_RESPONSE` in browser and nothing in console.

**Comment by luke0922** [comment]
you are using werkzueg's `simple_run`, in this way , `app.config.DEBUG` will not work, if you want it to work , you should use:
`run_simple('127.0.0.1', 5000, app, use_debugger=True)` 
or 
`app.run('127.0.0.1', 5000, debug=True)`

if you want to use `config.DEBUG = True ` work, you may should run as wsgi server.

**Comment by guyskk** [comment]
I expect it print exception traceback in console and show 500 internal server error in browser.
when DEBUG is False, it will print exception traceback and show 500 in browser, but when DEBUG is True, it not, so I think it is a bug.

**Comment by luke0922** [comment]
@guyskk  which version Flask does you using?
i checkout at v0.10.1 it print exception trackback in console when DEBUG is True and not print when DEBUG is False
and at v0.11.1 both DEBUG is True or False, it show trackback in console.

**Comment by guyskk** [comment]
@luke0922 flask 0.11.1 and python3.5

**Comment by luke0922** [comment]
@guyskk  it seems work as you said, i just try in python 3.5.1 and get the same result, maybe it's a bug.

**Comment by untitaker** [comment]
Can reproduce. No problems with Python 2.

**Comment by qingyunha** [comment]
I reproduced this with flask 0.11.1 and python 3.5.2

**Comment by qingyunha** [comment]
I found the `jinja2.exceptions.TemplateNotFound` exception was catch by wrong place
```python
        try:
            execute(self.server.app)
        except (socket.error, socket.timeout) as e: # go here
            self.connection_dropped(e, environ)
        except Exception:
            if self.server.passthrough_errors:
                raise
```
and  in python3.5
```python
issubclass(jinja2.exceptions.TemplateNotFound, socket.error) 
True
```

**Comment by qingyunha** [comment]
here is the thing:
```python
In [23]: jinja2.exceptions.TemplateNotFound.__bases__
Out[23]: (OSError, LookupError, jinja2.exceptions.TemplateError)

In [24]: socket.error is OSError
Out[24]: True

```

**Comment by untitaker** [comment]
I see, I think under Python 3 we should use one of the other error types that the socket module has to offer: https://docs.python.org/3/library/socket.html#exceptions -- not sure if `herror` and `gaierror` catch everything though.

**Comment by untitaker** [comment]
Also thank you so much @qingyunha for finding this!

**Comment by mitsuhiko** [comment]
Cool stuff. I think we could keep a tuple of error types for socket stuff in the compat module and catch on that.

Not my favorite change.

**Comment by untitaker** [comment]
Apparently this change was done in Python 3.3 too.

**Comment by untitaker** [comment]
However, an alternative would be to stop subclassing OSError in Jinja2. Thoughts?

**Comment by untitaker** [comment]
BTW, the reason this exception even bubbles up this far is https://github.com/pallets/werkzeug/issues/954

**Comment by mitsuhiko** [comment]
We could try to detect the actual error codes relevant for socket loss.

**Comment by qingyunha** [comment]
is this reasonable that  Template-Not-Found is an OS error?

**Comment by untitaker** [comment]
I don't really know but changing it won't solve the problem (because there might be other errors that get accidentally caught)

On 28 August 2016 11:58:09 CEST, qingyunha <notifications@github.com> wrote:
>is this reasonable that  Template-Not-Found is an OS error?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/1995#issuecomment-242966274

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
We could also detect if the exception is of the exact type `socket.error`, and not a subclass.

**Comment by Luavis** [comment]
We can probably determine error is not subclass of ```OSError``` but ```socket.error```. ```socket.error``` inherit not only ```OSError``` but also ```IOError``` ([FYI](https://www.python.org/dev/peps/pep-3151/#socket)).

```python
issubclass(socket.error, IOError)  # True
issubclass(socket.error, OSError)  # True
```

**Comment by untitaker** [comment]
Yes, but also:

```python
issubclass(OSError, IOError)  # True
issubclass(IOError, OSError)  # True
```

So I don't think this will help us much.

**Comment by davidism** [comment]
~~~
>>> socket.error is OSError
True
>>> socket.error()
OSError()
~~~

In Python 3, `socket.error` isn't a subclass, it's just an alias of `OSError`.  In Python 2 it is a distinct type.

**Comment by guyskk** [comment]
I wrote a script which can print class tree: https://gist.github.com/guyskk/9545d7a6a31c2379c5a319bd37551775

Here is result of OSError in Python 3.6:
```
OSError
----BlockingIOError
----ChildProcessError
----ConnectionError
--------BrokenPipeError
--------ConnectionAbortedError
--------ConnectionRefusedError
--------ConnectionResetError
------------http.client.RemoteDisconnected(ConnectionResetError,http.client.BadStatusLine)
----FileExistsError
----FileNotFoundError
----InterruptedError
----IsADirectoryError
----NotADirectoryError
----PermissionError
----ProcessLookupError
----TimeoutError
----io.UnsupportedOperation(ValueError,OSError)
----jinja2.exceptions.TemplateNotFound(OSError,LookupError,jinja2.exceptions.TemplateError)
--------jinja2.exceptions.TemplatesNotFound
----shutil.Error
--------shutil.SameFileError
----shutil.ExecError
----shutil.ReadError
----shutil.SpecialFileError
----signal.ItimerError
----socket.gaierror
----socket.herror
----socket.timeout
----ssl.SSLError
--------ssl.SSLEOFError
--------ssl.SSLSyscallError
--------ssl.SSLWantReadError
--------ssl.SSLWantWriteError
--------ssl.SSLZeroReturnError
----urllib.error.URLError
--------urllib.error.ContentTooShortError
--------urllib.error.HTTPError(urllib.error.URLError,urllib.response.addinfourl)
```

**Comment by davidism** [comment]
This is an issue with Werkzeug's dev server, not with Flask. Other servers such as Gunicorn do not have the issue. Reported at pallets/werkzeug#1127.
