### ISSUE TITLE
Prevent setting `SERVER_NAME` and `SESSION_COOKIE_DOMAIN` to an IP address

### ISSUE THREAD

**Issue by untitaker** [pallets/flask#2007]
See #1946 and #1906. I think we should prevent setting those things to IP addresses in the first place and only allow `None` and domain names != `localhost`.

**Comment by untitaker** [comment]
From #1955: We should also check that no port is contained.

**Comment by davidism** [comment]
Given that `SERVER_NAME` is used with `url_for(..., _external=True)` when not in a request context, preventing ports would break links.  Maybe there's a more correct way to do external links outside request contexts, but I couldn't find it at the time.

**Comment by untitaker** [comment]
>Given that SERVER_NAME is used with url_for(..., _external=True) when not in a request context, preventing ports would break links.

It rather seems to me that using ports there only accidentally worked and was never expected by the API authors. `SERVER_NAME` is [passed in Flask](https://github.com/pallets/flask/blob/9e41eca7f839db16cdf064f827fada0cabf6f54f/flask/app.py#L1781), yes. However, I don't think Werkzeug's `Map.bind` expects a port either, since 1.) the parameter is also called `server_name` 2.) `server_name` [is then idna-encoded](https://github.com/untitaker/werkzeug/blob/b617036ff9173fdc527177493ac518dae01503b4/werkzeug/routing.py#L1245), which is nonsensical for host + port combinations and actually breaks for certain hostnames:

    >>> 'foobar:443'.encode('idna')
    'foobar:443'
    >>> 'fööbar:443'.encode('idna')
    b'xn--fbar:443-n4aa'

However, apparently `app.run` derives its default port from `SERVER_NAME`.

This is so broken...

**Comment by davidism** [comment]
This and the propagate exceptions issue are both cases of one option doing more than it should.  We should probably do a more thorough review of what each option does and maybe add some more to disambiguate stuff before 1.0.

**Comment by untitaker** [comment]
Something like:

* Prevent ports in `SERVER_NAME`
* Add `SERVER_PORT`
* Change `app.run` behavior and `url_for` implementation accordingly.

**Comment by davidism** [comment]
Might be nice to make `SERVER_NAME` separate from `bind`, so that multiple domains / proxies don't cause 404s when you're really just trying to use `SERVER_NAME` for `url_for`.

**Comment by untitaker** [comment]
I don't understand, SERVER_NAME is already the frontend hostname.

On 10 September 2016 20:17:51 CEST, David Lord <notifications@github.com> wrote:
>Might be nice to make `SERVER_NAME` separate from `bind`, so that
>multiple domains / proxies don't cause 404s when you're really just
>trying to use `SERVER_NAME` for `url_for`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/2007#issuecomment-246127048

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davidism** [comment]
@untitaker yeah never mind, not sure what I was thinking with that one.

**Comment by amneher** [comment]
would you guys mind if I had a go at this one? I'd like to help and also squash my first bug. Thanks!

**Comment by untitaker** [comment]
Ah, this isn't actually that beginner friendly since we still need to decide what to actually do.

**Comment by untitaker** [comment]
I do think that adding `SERVER_PORT` would be correct, but somebody might disagree!

**Comment by mferreira96** [comment]
I didn´t fully undestand this bug. Please correct me if I'm wrong. I think that one solution  for this problem is check if the variables SERVER_NAME and SESSION_COOKIE_DOMAIN are an IP address and if so what should I do? Abort the program? Give a warning message? And do you want me to check if it is IPV4 or IPV6 or only IPV4?

**Comment by untitaker** [comment]
@mferreira96 IP addresses don't work when used in cookies, only domains do, this is why setting SESSION_COOKIE_DOMAIN to an IP is nonsensical. I can't remember why I wanted to prevent setting SERVER_NAME to an IP though (IPs should work for url_for).

Warning message sounds actually more reasonable. Both v4 and v6.

**Comment by mferreira96** [comment]
i am having some difficults in find where i should call the function that i build to give a warning when the person use an IP address in SESSION_COOKIE_DOMAIN, can you help me?

**Comment by HeyManLean** [comment]
I set the SESSION_COOKIR_DOMAIN as "mysite.com", but browser domain remain be ".mysite.com" and my subdomains can see my main site cookie.
