### ISSUE TITLE
Document not updated after the removal of argument -a and --app

### ISSUE THREAD

**Issue by sunqingyao** [pallets/flask#2009]
In short, the documents(both [the online one](http://flask.pocoo.org/docs/0.11/quickstart/#invalid-import-name) and the output of `flask --help`) is not fully updated after CLI interface is [simplified](https://github.com/pallets/flask/commit/523e27118359425048541d92892f20ee048c0b76). The `-a`/`--app` argument has been removed, but the document is somewhat misleading.

This issue comes from [a SO post](http://stackoverflow.com/q/39360392/5399734).  Please read through the comments for more information.

**Comment by mrecachinas** [comment]
This issue can now be closed! :)
