### ISSUE TITLE
Permission to generate stubs for Flask in typeshed

### ISSUE THREAD

**Issue by rowillia** [pallets/flask#2012]
Howdy,

I'd like to add stubs for Flask to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the python stdlib and  popular third party libraries.  As per PEP 484, permission is required from the library owner before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo

Here's the corresponding typeshed issue -
https://github.com/python/typeshed/issues/28

**Comment by untitaker** [comment]
I think it's fine. @davidism @thiefmaster?

**Comment by untitaker** [comment]
Also while we're at it, if we give you permission for Flask, this permission also holds for Jinja and Werkzeug.

**Comment by ThiefMaster** [comment]
:+1: seems like a good idea

**Comment by rowillia** [comment]
Sweet!  Thanks @ThiefMaster and @untitaker!

**Comment by davidism** [comment]
Sure, would be interested to see what's produced.

**Comment by rowillia** [comment]
@davidism @untitaker @ThiefMaster mind taking a look at https://github.com/pallets/itsdangerous/issues/69?  I link to the typestubs there as well as some interesting (I think) bugs found by adding types.
