### ISSUE TITLE
request.args uncompatible with quote, which lead decode error

### ISSUE THREAD

**Issue by eromoe** [pallets/flask#2016]
I think it is a bug.

My code:

    from __future__ import unicode_literals, absolute_import
    from flask import Blueprint, request, jsonify
    from flask_restful import Api, Resource
    from six.moves.urllib.parse import unquote
    from src.share import filemgr

    api = Blueprint('api', __name__, url_prefix='/api')
    api_wrap = Api(api)

    @api.route('/list', methods=['get'])
    def list():
        path = unquote(request.args.get('path', '/'))
        only_folder = request.args.get('only_folder', False)
        nodes = filemgr.list(path)
        if only_folder:
            nodes = filter(lambda x:x.isfolder, nodes)
        return jsonify(nodes)

-------------
ajax get:

    var path = 'c - 副本'
    ajax({
      url: 'http://localhost:5000/api/list',
      params: {
        path: encodeURI(path)
      }
    });

--------------

But get `path` decode incorrectly : `u'c - \xe5\x89\xaf\xe6\x9c\xac'`.

It should be `'c - \xe5\x89\xaf\xe6\x9c\xac'` or `u'c - \u526f\u672c''`

I debug into  `list()` and found:

```
>>> request.url
u'http://localhost:5000/api/list?path=c%2520-%2520%25E5%2589%25AF%25E6%259C%25AC'

>>> request.args.get('path', '/')
u'c%20-%20%E5%89%AF%E6%9C%AC'

>>> unquote(request.args.get('path', '/'))
u'c - \xe5\x89\xaf\xe6\x9c\xac'
```
Here the string can not be decode, the correct string is 'c - \xe5\x89\xaf\xe6\x9c\xac', without `u` prefix.

Debug into `request.args at Lib\site-packages\werkzeug\wrappers.py `

in line 431

    @cached_property
    def args(self):
        """The parsed URL parameters.  By default an
        :class:`~werkzeug.datastructures.ImmutableMultiDict`
        is returned from this function.  This can be changed by setting
        :attr:`parameter_storage_class` to a different type.  This might
        be necessary if the order of the form data is important.
        """
        return url_decode(wsgi_get_bytes(self.environ.get('QUERY_STRING', '')),
                          self.url_charset, errors=self.encoding_errors,
                          cls=self.parameter_storage_class)

I try some value:

    >>> wsgi_get_bytes(self.environ.get('QUERY_STRING', ''))
    'path=c%2520-%2520%25E5%2589%25AF%25E6%259C%25AC'

    >>> url_decode(wsgi_get_bytes(self.environ.get('QUERY_STRING', '')),
                              self.url_charset, errors=self.encoding_errors,
                              cls=self.parameter_storage_class)
    ImmutableMultiDict([('path', u'c%20-%20%E5%89%AF%E6%9C%AC')])

    `url_decode` decode querystring into wrong.

The problem is `url_decode`, should not decode here, because the querystring maybe quote(like my situation)

**Comment by luke0922** [comment]
i try it in Flaks==0.11.1 and not found problems, my test case is: [flask-issue-2016-test](https://gist.github.com/luke0922/51a44883197813af77870c0d7c2c3898)

can you tell your flask version and system encode?

**Comment by eromoe** [comment]
@luke0922

My env:
Python 2.7.10 32 bit
Flask (0.11.1) 
Win 8.1 x64

And, you test is not correct. 
If you use a web browser, there is a method call `encodeURI` , as I write in the question.
I am not familiar with curl, but it must has some option like `encodeURI` to encode `i'am中国人`

**Comment by luke0922** [comment]
it also works with `encodeURI` ,you can try this:
`curl -X GET "http://127.0.0.1:9090?type=i'am%20%E4%B8%AD%E5%9B%BD%E4%BA%BA"`

i think it is not a Flask case, but  your runtime encode not in UTF-8

**Comment by eromoe** [comment]
Oh,  my bad. It is not unicode encoding problem, but encodeURI twice in frontend.

The frontend is a reactjs app. There is a piece code:

`var querystring = options.params ? urllib.format({ query: options.params })
`
to build querystring. Here , `urllib.format` encode `options.params` again.

1. `urllib.format({ query: {'path':'中国'} })`
"?path=%E4%B8%AD%E5%9B%BD"

2. `urllib.format({ query: {'path':encodeURI('中国')} })`
"?path=%25E4%25B8%25AD%25E5%259B%25BD"

The second one make the problem. 

But I still think there is a problem, flask should not break the flow when one encode twice.

**Comment by ThiefMaster** [comment]
Decoding a string once that was encoded twice should give you the string as it was after the first encoding.

**Comment by untitaker** [comment]
You should not have to use `unquote` on `requests.args` in your Flask app, and a simple app like this works fine for me:

    @app.route('/')
    def index():
        return requests.args['path']

If I open `http://127.0.0.1:5000/?path=%E4%B8%AD%E5%9B%BD` in my browser, the correct characters are returned. This must be a problem in your frontend.

>u'\xe4\xb8\xad\xe5\x9b\xbd' this can not be decode

It *is* decoded. Try to print it!

Sorry, but this is not a proper bugreport for Flask, closing.
