### ISSUE TITLE
time.sleep() swallow FLASH_DEBUG message

### ISSUE THREAD

**Issue by kienpham2000** [pallets/flask#2032]
In the sample code below, Testing... never show if I have time.sleep(1) there. If I remove it, I can see the debug message. I'm on macOS 10.11.6, Flask==0.11.1, Python 3.5.2, running inside virtualenv==15.0.2

```
from flask import Flask
import time

app = Flask(__name__)
app.DEBUG = True

@app.cli.command()
def streaming():
   app.logger.debug('Testing...')
   time.sleep(1)

```

**Comment by barischj** [comment]
Shows for me on macOS 10.11.6, Flask==0.11.1, Python 3.5.2, running inside virtualenv==15.0.**3**

**Comment by kienpham2000** [comment]
Sorry my script ran too fast I thought it was swallowing the debug message. All good now.
