### ISSUE TITLE
Feature packt book in docs

### ISSUE THREAD

**Issue by packtpartner** [pallets/flask#2036]
Hi,

Packt is proud to publish a new book on Flask this year
[Flask By Example](https://www.packtpub.com/web-development/flask-example)

I would appreciate if you could fearure this book on http://flask.pocoo.org/ to help developers in their learning of Flask.

Let me know what you think.

Many thanks.

**Comment by ThiefMaster** [comment]
I can't speak for the other maintainers but I wouldn't feel comfortable featuring a book I haven't read myself (and thus cannot judge the quality of it).

**Comment by untitaker** [comment]
My personal stance on this is that we may recommend books when a certain amount of people have read it and found it to be good.

**Comment by packtpartner** [comment]
Hi @ThiefMaster and @untitaker , I would be happy to provide you with an eBook copy to review. You can go through the book and then decide to put it up. What do you think?

**Comment by untitaker** [comment]
Unfortunately I don't think I have the time to review your book. I'd suggest
that we leave this issue open if somebody else wants to do it.

**Comment by ThiefMaster** [comment]
I don't have that much time right now but I might need something to do on a long-distance flight in two weeks so I could probably have a look then.

**Comment by packtpartner** [comment]
That's not a problem @untitaker 
@ThiefMaster can we continue this discussion over email? Will your email address on Github work for communication?

**Comment by untitaker** [comment]
As said I don't have time to review the book.

**Comment by ThiefMaster** [comment]
> Will your email address on Github work for communication?

yes

**Comment by davidism** [comment]
I've already been emailed by you guys multiple times in the past and since it was unsolicited I treated it as spam. I'm -1 in this, Flask doesn't need to be doing marketing for paid content.

**Comment by untitaker** [comment]
Fair enough, let's close this then.
