### ISSUE TITLE
do you have Extensions for VScode ?

### ISSUE THREAD

**Issue by iloveyo123u1** [pallets/flask#2037]
https://marketplace.visualstudio.com/search?term=flask&target=VSCode&sortBy=Relevance

i don't find it

can you help me  ?

my friend

**Comment by ThiefMaster** [comment]
No. What would such extensions do? Flask is just a Python package so any decent IDE should be able to introspect most of it without special support from our side.

**Comment by iloveyo123u1** [comment]
@ThiefMaster hi   https://marketplace.visualstudio.com/search?term=flask&target=VSCode&sortBy=Relevance
