### ISSUE TITLE
Flask Extension that doesn't require user code changes

### ISSUE THREAD

**Issue by shaicantor** [pallets/flask#2041]
Hi,

Can a flask extension be installed using pip and run without user code changes at all?

I want to write a flask extension that uses flask's before_request and after_request hooks.
The user will just need to `pip install flask_<my_extension>` and that's it.

Thanks in advance.

**Comment by ThiefMaster** [comment]
No. Flask extensions are not plugins but libraries developers can use in their Flask applications.

It sounds more like you want some kind of plugin system...

**Comment by untitaker** [comment]
Please dont write such an extension that automatically hooks itself into Flask, it makes everything harder to debug, if you have some behavior you don't know where it came from.
