### ISSUE TITLE
Assert should not be used outside of testing

### ISSUE THREAD

**Issue by coltonlw** [pallets/flask#2043]
assert should not be used in production because assert statements are discarded if the program is compiled to bytecode with the PYTHONOPTIMIZE turned on

https://github.com/pallets/flask/blob/master/flask/views.py#L148

**Comment by untitaker** [comment]
Yes, that is an internal assertion.

**Comment by coltonlw** [comment]
@untitaker Can you explain what you mean by internal assertion?  If someone compiled flask to bytecode with PYTHONOPTIMIZE enabled that assert statement would be removed.

**Comment by untitaker** [comment]
This assertion should never fail if Flask behaves correctly, so it's ok if it's removed in production.

**Comment by ThiefMaster** [comment]
Not having the check won't cause any bugs or security issues. In the very worst case you'd get a TypeError about NoneType not being callable. But that's imply that the a wrong method is allowed on the Flask routing level. So if everything is setup properly this assertion can't fail anyway.

**Comment by coltonlw** [comment]
@untitaker @ThiefMaster Understood, thank you
