### ISSUE TITLE
MethodView requires settings "methods" attribute

### ISSUE THREAD

**Issue by coltonlw** [pallets/flask#2044]
In the example for MethodView, post() will not be called unless methods is set on the class or with add_url_rule

https://github.com/pallets/flask/blob/master/flask/views.py#L123

A fix might be having MethodView.methods set to a copy of http_method_funcs i.e. all available methods

If I am missing something here my apologies

**Comment by coltonlw** [comment]
It seems this may be intended behavior based on another example of MethodView in the docs:

http://flask.pocoo.org/docs/0.11/views/#method-views-for-apis

Maybe the fix is to change the docstring example for MethodView to show that you must set methods, I can submit a PR for that doc fix if requested

**Comment by acatton** [comment]
Isn't this the problem exposed by #1936 ?

**Comment by davidism** [comment]
Not sure what's going on here. `methods` is populated automatically if it is not set by the class. #1936 improves on this by allowing mixins, but it should always have worked. If it doesn't, please add an example and I'll reopen this.
