### ISSUE TITLE
add_resource does not preserve api function docstring

### ISSUE THREAD

**Issue by izmailoff** [pallets/flask#2062]
I'm trying to auto generate API help using this piece of code:

```
@app.route('/api/help', methods=['GET'])
def api_help():
    """Returns all registered APIs available in this application."""
    func_list = {}
    for rule in app.url_map.iter_rules():
        if rule.endpoint != 'static':
            func_list[rule.rule] = app.view_functions[rule.endpoint].__doc__
    return jsonify(func_list)
```

It relies on `__doc__` of a function and works fine for APIs defined with a `route` decorator:

`@app.route('/someapi'...`

However, when a route is registered with `add_resource` the docstring is lost.

The help api returns data in this format:

```
{
  "/api/help": "Returns all registered APIs available in this application.", 
  "someapi": null
}
```

tried on latest versions:

> Name: Werkzeug
> Version: 0.11.11
> 
> Name: Flask
> Version: 0.11.1
> 
> python --version
> Python 3.5.1 :: Anaconda 4.0.0 (64-bit)

**Comment by davidism** [comment]
`add_resource` is not a Flask method.

**Comment by izmailoff** [comment]
Oh yes, my bad. It's from Flask-RESTful extension:

http://flask-restful-cn.readthedocs.io/en/0.3.4/api.html

**Comment by zedrdave** [comment]
Sorry to keep the discussion going here, but have you found a solution to that problem with Flask-RESTful?

**Comment by izmailoff** [comment]
Just opened an issue here: https://github.com/flask-restful/flask-restful/issues/643. It was low priority for me so I forgot to open it right away.
