### ISSUE TITLE
Application did not run with `flask run` with FLASK_DEBUG=1(But can run by using command`python -m flask run`) in Win10

### ISSUE THREAD

**Issue by future0906** [pallets/flask#2083]
Error message:
`d:\projects\cfblog2_env\scripts\python.exe: can't open file 'D:\projects\cfblog2_env\Scripts\flask': [Errno 2] No such file or directory`

Environment: Win 10, Py 3.5.2(VirtualEnv)，Flask 0.11
This error was came from '_reload.py' in werkzeug.It seems like when run with flask.exe, sys.executable still equal to python's exe path and sys.argv is something like this:`'D:\\projects\\cfblog2_env\\Scripts\\flask', 'run'`

I am not sure what cause this problem actually(werkzeug,packer of flask.exe or flask itself).But this error happend when I using flask. So I put the issuse here.

To whom has the same error, you can use`python -m flask run` for workaround.
And last, sorry for my poor english.

**Comment by wgwz** [comment]
did you set FLASK_APP=</path/to/file/containing/app/instance>.py?

**Comment by saalaa** [comment]
It seems it can't find `flask`; which leads me to believe you either have not installed `flask` or you haven't activated your virtual environment.

To activate your virtual environment:

    $ virtualenv env
    $ source env/bin/activate

To install `flask`:

    $ pip install flask

**Comment by untitaker** [comment]
@future0906 does it work when not using debug mode?

**Comment by future0906** [comment]
@untitaker 
Yes, both ways(`python -m flask run` or `flask run`) work when not using FLASK_DEBUG=1.
@wgwz @saalaa 
Sure I did.And as I said before, this didn't work only when I use `flask run` and set the debug flag 1.

**Comment by cpxander** [comment]
@future0906 Create a copy of flask.exe and rename it "flask" without the extension. This is a temporary fix.

**Comment by ferbecab03** [comment]
@untitaker Is this issue similar to #1829 ?

**Comment by untitaker** [comment]
Yes, appears to be a dupe

**Comment by saba-projects** [comment]
> It seems it can't find `flask`; which leads me to believe you either have not installed `flask` or you haven't activated your virtual environment.
> 
> To activate your virtual environment:
> 
> ```
> $ virtualenv env
> $ source env/bin/activate
> ```
> 
> To install `flask`:
> 
> ```
> $ pip install flask
> ```
> 
> Hardly a bug.
> 
> Edit: misread, disregard my answer. It indeed looks like a bug figuring out `flask`'s path.

**Comment by saba-projects** [comment]
Hello. i can't run flask.
The error message is "use a production WSGI server instead "
please help me

**Comment by pipinstallwin** [comment]
Solution:

Your file/ folder structure should look like this 

Getting errors trying (flask run) 
my project is a portfolio
--- portfolio/
----- | virtualenv (name)/
----- | app/
--------- | __init__.py
--------- | routes.py
----- | flaskrun.py
(nam)\scripts\activate
now you can set FLASK_APP = flaskrun.py
then flask run

**Comment by elizaench16** [comment]
> Error message:
> `d:\projects\cfblog2_env\scripts\python.exe: can't open file 'D:\projects\cfblog2_env\Scripts\flask': [Errno 2] No such file or directory`
> 
> Environment: Win 10, Py 3.5.2(VirtualEnv)，Flask 0.11
> This error was came from '_reload.py' in werkzeug.It seems like when run with flask.exe, sys.executable still equal to python's exe path and sys.argv is something like this:`'D:\\projects\\cfblog2_env\\Scripts\\flask', 'run'`
> 
> I am not sure what cause this problem actually(werkzeug,packer of flask.exe or flask itself).But this error happend when I using flask. So I put the issuse here.
> 
> To whom has the same error, you can use`python -m flask run` for workaround.
> And last, sorry for my poor english.

THANK YOU!!!! I've been trying to get this to work for almost a week, no one could help. Also, your English is great!
