### ISSUE TITLE
add rails style model

### ISSUE THREAD

**Issue by ycz0926** [pallets/flask#2098]
now, when we want to operate the model, we have to define the database model every time, whether we can add some code to the flask, so that we do not need to define the database like the cakephp model style....

**Comment by ycz0926** [comment]
in cakephp， if we want to use the model in the controllers, we just need to add the code in the controllers class:
```php
<?php 
class HelloController extends AppController {
    ....
    var $uses = array('User');
    ....
?>
```

**Comment by untitaker** [comment]
Flask does not enforce usage of a particular db, so this is out of scope.
