### ISSUE TITLE
Authenticating with NTLM

### ISSUE THREAD

**Issue by jithurjacob** [pallets/flask#2101]
How can I authenticate a user with NTLM Authentication in Windows?

I have a Python Flask Application hosted in IIS server with Windows Authentication enabled. When a user visits the site within our network I want the user to be auto logged in else redirect the user to login page.

How can this be achieved?

**Comment by jirikuncar** [comment]
@jithurjacob check https://github.com/requests/requests-ntlm/blob/master/tests/test_server.py

--
PS: Better place to ask is [IRC](http://flask.pocoo.org/community/irc/) or http://stackoverflow.com/questions/tagged/flask

**Comment by ThiefMaster** [comment]
Indeed, SO is not the place for support questions.
