### ISSUE TITLE
API exception pattern docs do not mention PROPAGATE_EXCEPTIONS

### ISSUE THREAD

**Issue by philmayers** [pallets/flask#2107]
http://flask.pocoo.org/docs/0.11/patterns/apierrors/

...discusses a pattern for defining and catching custom exceptions. However, this pattern does not work unless PROPAGATE_EXCEPTIONS is set, because the exception gets eaten and turned into a 500.

Confusingly it will work in DEBUG=True mode then break in production.

Can the docs be updated? Or am I missing something?

**Comment by r0fls** [comment]
It sounds like you forgot to register an error handler: http://flask.pocoo.org/docs/0.11/patterns/apierrors/#registering-an-error-handler

>At that point views can raise that error, but it would immediately result in an internal server error. The reason for this is that there is no handler registered for this error class. 

I just tried with this:

```python
from flask import jsonify
from flask import Flask
app = Flask(__name__)

class InvalidUsage(Exception):
    status_code = 400

    def __init__(self, message, status_code=None, payload=None):
        Exception.__init__(self)
        self.message = message
        if status_code is not None:
            self.status_code = status_code
        self.payload = payload

    def to_dict(self):
        rv = dict(self.payload or ())
        rv['message'] = self.message
        return rv

@app.errorhandler(InvalidUsage)
def handle_invalid_usage(error):
    response = jsonify(error.to_dict())
    response.status_code = error.status_code
    return response

@app.route('/foo')
def get_foo():
    raise InvalidUsage('This view is gone')
```

It works as expected:

```
$ curl localhost:5000/foo
{
  "message": "This view is gone"
}
$ curl -I localhost:5000/foo
HTTP/1.0 400 BAD REQUEST
Content-Type: application/json
Content-Length: 37
Server: Werkzeug/0.11.11 Python/2.7.12
Date: Mon, 26 Dec 2016 21:13:35 GMT
```

**Comment by philmayers** [comment]
No, that's not correct. I have done exactly that, registered an error handler, and it *specifically* doesn't work unless PROPAGATE_EXCEPTIONS is set, which is not clearly documented at the link you cite - which is exactly the same link I gave.

**Comment by pmayers** [comment]
This appears to be something inside flask-restful, not flask itself. I thought I'd located code in flask/werkzeug that was causing it but have retested and proven myself wrong. Sorry for the noise, this can be closed.
