### ISSUE TITLE
Template File will not download file (window.open command in HTML) when run from flask

### ISSUE THREAD

**Issue by Netuser-Py** [pallets/flask#2114]
I have an HTML template that works correctly and downloads a file when open it directly in the browser (Chrome or Firefox), but the window.open command does not run (does not download the file) when the HTML is called from flask.

<script>
window.open("file:///C:/mypath/mywordfile.docx")
</script>

see attached sample
[issue.txt](https://github.com/pallets/flask/files/659321/issue.txt)

**Comment by ThiefMaster** [comment]
This has nothing to do with Flask. Probably browsers don't allow navigation between file and other protocols.

**Comment by Netuser-Py** [comment]
I solved it using flask' send_file:

from flask import Flask, request, session, g, redirect, url_for, \
     abort, render_template, flash
from flask import send_file

app = Flask(__name__)
app.config.from_object(__name__)

app.config.from_envvar('FLASKR_SETTINGS', silent=True)

@app.route('/view_method')
def view_method():
    path_to_file = r'C:\mypath\mywordfile.docx'
    return send_file(
	        path_to_file, 
	        mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
	        as_attachment=True, 
	        attachment_filename="mywordfile.docx")

if __name__ == '__main__':
    app.run()
`
