### ISSUE TITLE
code icon show other

### ISSUE THREAD

**Issue by brunodskoo** [pallets/flask#2124]
'code icon', 'file code outline icon' is showing different then the link http://semantic-ui.com/elements/icon.html

http://jsfiddle.net/efp8z6Ln/428/

**Comment by ThiefMaster** [comment]
How is this related to Flask? Flask does not integrate Semantic UI - it's a server-side framework...

**Comment by brunodskoo** [comment]
http://jsfiddle.net/efp8z6Ln/428/

**Comment by ThiefMaster** [comment]
You already posted this link. What does it have to do with Flask?

**Comment by brunodskoo** [comment]
im sorry, im posting in other but...
