### ISSUE TITLE
Flask documentation inconsistent with implementation for form parsing

### ISSUE THREAD

**Issue by puiterwijk** [pallets/flask#2132]
Since Werkzeug 0.9, request.form is populated for all requests as long as they contain a Content-Type header (https://github.com/pallets/werkzeug/blob/master/werkzeug/wrappers.py#L328).
The Flask documentation however implies that request.form is only available with POST and PUT requests, and that is the case with Werkzeug<0.9 (well, 0.8.3 parses for POST, PUT and PATCH).

**Comment by untitaker** [comment]
To be clear, is the new Werkzeug behavior a problem for you?

**Comment by puiterwijk** [comment]
No, this is purely a documentation ticket, as it's just an indicator that the docs are wrong.

**Comment by puiterwijk** [comment]
(I think the werkzeug change could be documented in the Flask docs, since I've seen Flask apps that depended on this change, and thus fail to work with older versions of Flask/Werkzeug, without the authors knowing)

**Comment by untitaker** [comment]
@puiterwijk please take a look at #2135 and pallets/werkzeug#1057

**Comment by puiterwijk** [comment]
@untitaker that looks good to me :+1:, thanks!
