### ISSUE TITLE
Website still lists 0.11 as the latest release even though 0.12 is release

### ISSUE THREAD

**Issue by cdman** [pallets/flask#2142]
http://flask.pocoo.org/ (BTW, can I haz HTTPS please?) says:

>  Latest Version: 0.11 

It should say:

>  Latest Version: 0.12 

(with the correct link).

:sparkles:

**Comment by infinite-Joy** [comment]
This is a beginner task. Please label it for first timers. Maybe a more long term approach can be taken like getting the present version number directly from pypi.

Hint: add the appropriate version number to "releases" variable in https://github.com/pallets/flask-website/blob/master/flask_website/listings/releases.py

**Comment by ThiefMaster** [comment]
@infinite-Joy: only people with commit access to the repo can label tasks. and to be honest, it's a one-line change, it's not really worth labelling it and waiting for someone else to contribute the change instead of just doing it yourself...

**Comment by infinite-Joy** [comment]
Just saw there is already a PR pending for this.

https://github.com/pallets/flask-website/pull/43

**Comment by ThiefMaster** [comment]
Merged the PR. Not sure if there's any automated update on the live website though.

ping @mitsuhiko

**Comment by mitsuhiko** [comment]
Restarted. Should improve this deployment.

**Comment by cdman** [comment]
Thank you all for the prompt update! It now displays the correct version.
