### ISSUE TITLE
Connection refused for flask redis session

### ISSUE THREAD

**Issue by jeff1evesque** [pallets/flask#2150]
I attempted to replace flask's internal [`session`](http://flask.pocoo.org/docs/0.12/quickstart/#sessions) by [implementing](http://flask.pocoo.org/snippets/75/) redis.  I thought this was a good idea, since it would mean more secure sessions, since they are not stored as cookies, rather on the redis-server:

- http://flask.pocoo.org/snippets/75/
- https://github.com/mrichman/flask-redis/blob/master/redissession.py

After copying the latter [reference](https://github.com/mrichman/flask-redis/blob/master/redissession.py), as [`redis_session.py`](https://github.com/jeff1evesque/machine-learning/blob/340e19ab43cd2162b712d1f485e69411ec83fe91/brain/cache/redis_session.py), followed by adjusting [`factory.py`](https://github.com/jeff1evesque/machine-learning/commit/4eea9251f69e392d2ce2e5ca6bbd2d53c964d2b0):

```python
            # replace default cookie session with server-side redis
            app.session_interface = RedisSessionInterface()
```

My travis ci indicated a [failed](https://travis-ci.org/jeff1evesque/machine-learning/builds/190594385#L3623-L3725) build:

>E           ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

I'm not sure why my application failed to connect to redis.  The redis-server should have properly started via [`redis.dockerfile`](https://github.com/jeff1evesque/machine-learning/blob/962cfee5d8031fc09802da82f04b04a6280d4242/redis.dockerfile#L12), which is implemented by the overall [`travis.yaml`](https://github.com/jeff1evesque/machine-learning/blob/e801c5f8bffdf1b402af760c4ccbb2faf9991d76/.travis.yml#L105).  Prior to actually implementing `redis_session.py`, my application was already using redis successfully for other things (like serializing sciki-learn objects, and storing it into redis), as indicated by [prior builds](https://travis-ci.org/jeff1evesque/machine-learning/builds/190431244#L3624).  Specifically, the `test_model_generate` function from [`pytest_svm_file_upload.py`](https://github.com/jeff1evesque/machine-learning/blob/203ec97281314c9ca97ab58b0e3a3e7342990bd5/test/live_server/programmatic_interface/file_upload/pytest_svm_file_upload.py#L106-L125), basically computes a prediction object, then stores it into redis via a custom [`cache`](https://github.com/jeff1evesque/machine-learning/blob/203ec97281314c9ca97ab58b0e3a3e7342990bd5/brain/cache/cache_model.py#L45-L58) method:

```python
    def cache(self, hash_name, key):
        '''@cache
        This method serializes, then caches the provided model into a redis
        hash cache.
        '''

        try:
            serialized = Serialize_Model(self.model).serialize()
            self.myRedis.hset(hash_name, key, serialized)
        except Exception, error:
            self.list_error.append(str(error))
            print self.list_error
```

If the model was not properly cached into redis, then my successive unit test, [`test_model_predict`](https://github.com/jeff1evesque/machine-learning/blob/203ec97281314c9ca97ab58b0e3a3e7342990bd5/test/live_server/programmatic_interface/file_upload/pytest_svm_file_upload.py#L128-L147) which uncaches the same model, in order to perform corresponding computation, would fail.

Because my travis ci [builds](https://travis-ci.org/jeff1evesque/machine-learning/builds) began breaking with the introduction of overloading [`app.session_interface = RedisSessionInterface()`](https://github.com/jeff1evesque/machine-learning/commit/4eea9251f69e392d2ce2e5ca6bbd2d53c964d2b0#diff-ab2c5ef35603caa654ec40f8cad9162aR53) in my app factory, I'm wondering if the problem is redis, flask, docker, or a combination of the three?

**Comment by jeff1evesque** [comment]
I temporarily [removed](https://github.com/jeff1evesque/machine-learning/commit/7f5ce43be1c074a6657c5ade4a831c51489b5ec7) `app.session_interface = RedisSessionInterface()` from my `factory.py`, and noticed the corresponding travis ci [build](https://travis-ci.org/jeff1evesque/machine-learning/builds/191835620#L3616-L3662) did not have the above mentioned error.  Then, I reverted back the redis implementation, with a corresponding commit.  So, it seems I have two choices, either use the default flask session, or carry on debugging the redis implementation within flask.

**Comment by jeffwidman** [comment]
Questions should be asked over on StackOverflow or the Flask mailing list. 

Issue tracker is for bugs/feature requests. Thanks.

**Comment by jeff1evesque** [comment]
@jeffwidman couldn't this potentially be a bug with the redis integration, with respect to flask `session`?

**Comment by jeffwidman** [comment]
Last I checked, Flask core has no built-in redis integration, you have to extend the session either by hand (eg, by copying the Flask snippet you linked to) or using a Flask extension. Both of those are not maintained by core, hence why I closed this. If you're using an extension, file an issue with them. IIRC, the snippets aren't maintained much anymore, so if you want to handcraft the Redis integration, check StackOverflow or look for examples others have posted on Github etc.

**Comment by ThiefMaster** [comment]
"Connection refused" means the redis library cannot connect to the redis server. This *cannot* be caused by Flask.

And as others said, the redissession module is not part of flask...

However, I think I see the problem there: It creates a new Redis instance if none is passed - this happens when the RedisSessionInterface is instantiated, something that usually happens at import time or at app factory execution time. Neither is a good time to open a connection that'll be used throughout the app's lifetime. Connecting to redis should probably be done when the connection will actually be used. When a Redis instance is passed to the constructor it also needs to be available when the constructor is executed, i.e. it has the same problem.
