### ISSUE TITLE
AssertionError with webtest when returning 204

### ISSUE THREAD

**Issue by Erfa** [pallets/flask#2156]
I have a handler that returns a 204 with no Content-Type, like this:
```python
from flask import Response

def make_204_response():
    resp = Response('', 204)
    del resp.headers['Content-Type']
    return resp
```

It works as expected, but when I run my unit tests using webtest I get this error:
```
Exception AssertionError: AssertionError(u'Iterator garbage collected without being closed',) in <bound method IteratorWrapper.__del__ of <webtest.lint.IteratorWrapper object at 0x7f90f7a6b550>> ignored
```

It looks like webob had pretty much the same problem:
https://github.com/Pylons/webob/issues/305

**Comment by davidism** [comment]
What is webtest? How are you using it to produce this error? When reporting bugs, please include a self-contained example that we can reference.

**Comment by Erfa** [comment]
Seems like this was actually caused by something else in my dependencies. I upgraded all packages to the latest version and the problem is no more.
