### ISSUE TITLE
Error accessing static components in subfolder

### ISSUE THREAD

**Issue by javixeneize** [pallets/flask#2165]
I am having issues when retrieving static components on subfolders in my project. Let me explain

My structure is as follows:

Main.py
--- App1.py
--- App2.py

It is, i have a main page that has links that refers to App1.py or App2.py, which are also flask programs

When i access App1.py, i dont have static content displayed. The html of the page is correctly displayed (under templates/App1/app1.html), but, looks like it is unable to find the static component referred in that page (i am referring from the html to static component under static/app1/css/app1.css). I have a 404 response

Is that something that is not supported by flask?

Thanks

**Comment by untitaker** [comment]
Please ask questions on StackOverflow.
