### ISSUE TITLE
The default static folder is being ignored if the number of params to the route are 3

### ISSUE THREAD

**Issue by amehta** [pallets/flask#2171]
[@app.route('/<date>/<username>/<path:filename>')
@login_required
@nocache
def custom_static(filename, username, date):
    path = os.path.join(app.config['CUSTOM_STATIC_PATH'],"username", username, date)
    print "Path: {}".format(path)
    if os.path.isfile(os.path.join(path, filename)):
        return send_from_directory(path, filename)
    else:
        print "File does not exist: {}".format(filename](url))
        return

[Path: ./DataWebserver/username/js/static
File does not exist: bootstrap-datepicker.min.js
    enter code here](url)

**Comment by untitaker** [comment]
Please provide a minimal reproducible example, not a random piece of code from your software.
