### ISSUE TITLE
multiple Set-Cookie fold in one line HTTP Header

### ISSUE THREAD

**Issue by pedia** [pallets/flask#2172]
First, [RFC 6265](https://tools.ietf.org/html/rfc6265) said:
> Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field.

But in flask-admin login(with flask-user) login response, multiple set-cookie(s) are folded:
> Set-Cookie: remember_token=...; Expires=Tue, 06-Feb-2018 05:23:25 GMT; Path=/
session=...; HttpOnly; Path=/

**CAUTION: Path=/[without a space]session=**

And in werkzeug, multiple Set-Cookie unittest(I added this code in werkzeug/tests/test_wrappers.py below), and passed.

    # set multi cookie once
    response = wrappers.BaseResponse()
    response.set_cookie('foo', 'bar', 60, 0, '/blub', 'example.org')
    response.set_cookie('blar', 'zag', 60, 0, '/blob', 'example.org')
    strict_eq(response.headers.to_wsgi_list(), [
        ('Content-Type', 'text/plain; charset=utf-8'),
        ('Set-Cookie', 'foo=bar; Domain=example.org; Expires=Thu, '
         '01-Jan-1970 00:00:00 GMT; Max-Age=60; Path=/blub'),
        ('Set-Cookie', 'blar=zag; Domain=example.org; Expires=Thu, '
         '01-Jan-1970 00:00:00 GMT; Max-Age=60; Path=/blob')
    ])

So I think this maybe a bug or flask. 
Any thought appreciated.

**Comment by AnubhaAgrawal** [comment]
Hi pedia,
can you please provide that on which file or folder of flask this issue exist.

**Comment by pedia** [comment]
I cannot prove it. Close it now.
