### ISSUE TITLE
Callback on `app.run`

### ISSUE THREAD

**Issue by barischj** [pallets/flask#2178]
When writing local-only apps we want to open the web browser after the flask app starts up.

Currently we do:
```
threading.Timer(1.25, lambda: webbrowser.open(url) ).start()
app.run(port=port)
```

However it would be nice not to have a guessed time like `1.25`, also it would be nice for the opening of the browser to be cancelled incase starting the flask app fails.

Possibly would look like:

`app.run(port=port, onstart=lambda: webbrowser.open(url))`

**Comment by ThiefMaster** [comment]
To be honest, I don't think this would be a very useful feature - it's not too uncommon to restart the dev server during development and at least I wouldn't want to have another browser window/tab open all the time. Especially since it takes less than a second to open a tab and start typing `localhost` or whatever hostname you use and select the entry from history.

**Comment by barischj** [comment]
I'm not talking about development servers, but rather local only applications which use the web browser as a display.

**Comment by ThiefMaster** [comment]
`app.run()` (or to be more exact: the builtin dev server) is not intended to be used in any kind of production setup - including local non-development use (even if the drawbacks are less noticable in that case when threading is enabled)...

**Comment by untitaker** [comment]
@barischj As far as I recall there is no "direct" way to determine when the server is listening, so your best bet is spawning a new thread and poll that port. If it responds you can then open the browser.

**Comment by barischj** [comment]
Thanks for the help :)

**Comment by mohamed-aziz** [comment]
@barischj I don't think that Flask.run should accept a callback method, but you can do something like @untitaker suggests

    from flask import Flask
    from threading import Thread
    import socket
    import time
    import webbrowser


    app = Flask(__name__)

    class OpenBrowser(Thread):

        def __init__(self):
            super(OpenBrowser, self).__init__()

        def notResponding(self):
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            return sock.connect_ex(('127.0.0.1', 5000))

        def run(self):
            while self.notResponding():
                print('Did not respond')
            print('Responded')
            webbrowser.open_new('http://127.0.0.1:5000/') 

    @app.route('/')
    def index():
        return 'Hello World'

    th = OpenBrowser()

    th.start()

    app.run()

**Comment by lixk** [comment]
You can do it like this:

import webbrowser
from application import app
import threading
import time
from urllib import request

INDEX_URL = "http://127.0.0.1:5000"


def open_browser():
    print('server starting...')
    while True:
        try:
            request.urlopen(url=INDEX_URL)
            break
        except Exception as e:
            print(e)
            time.sleep(0.5)
    print('server started !')
    # server started callback
    webbrowser.open(INDEX_URL)

threading.Thread(target=open_browser).start()
# start server
app.run(host="0.0.0.0", port=5000)

**Comment by arvindsree** [comment]
I would like to request for this feature. I would require a callback on successfull app.run( ) afgter it has loaded the files. My use case is that I want to delete private key file after the server has been run on this callback

**Comment by davidism** [comment]
If it wasn't clear from being closed, tgis is not happening. The dev server is only for dev, so any solution would only work in that one case anyway.

**Comment by arvindsree** [comment]
I don't agree.. The module is incomplete without status messages on whether the run was was successfull or not.  Since it is runs on its own thread, it must provide some sort of callback for success and failure (port, ioerror etc) cases.

The solution provided above is a work around
