### ISSUE TITLE
before_request versus HTTP exceptions

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/flask#219]
Right now before_request cannot emit HTTP exceptions. This should be improved by allowing a certain useful subset of exception functionality there.

**Comment by mathiasbc** [comment]
This is replicable with:
```
from flask import Flask
from werkzeug.exceptions import HTTPException

app = Flask(__name__)

@app.before_request
def f():
    raise HTTPException("This is not propagated as an Exception")

@app.route('/')
def test():
    return 'This is a view'

if __name__ == '__main__':
    app.run()
```

Where is flask filtering/swallowing HTTPExceptions ?

**Comment by davidism** [comment]
This seems to work correctly. Raising exceptions are handled by the error handler mechanism. `HTTPException` itself has no associated error or default handler, so it returns "Unknown Error" as expected.
