### ISSUE TITLE
testing.rst is missing flask import

### ISSUE THREAD

**Issue by SergioDS** [pallets/flask#2190]
When following the tutorial first test was failing because it does not find init_db()
Searching I found [this question](http://stackoverflow.com/questions/41612996/running-unit-tests-on-the-flaskr-tutorial-micro-blogging-app-in-flask) that fixed it, so the rest should be modified 
from
`import flaskr`
to
`from flaskr import flaskr`
I can not push a branch with the change (I suppose I have no permission)

**Comment by lepture** [comment]
The documentation has nothing wrong if you follow the the [tutorial section](http://flask.pocoo.org/docs/0.12/tutorial/#tutorial).

The confusing part is that the tutorial doesn't match the code in current example folder.

**Comment by lepture** [comment]
> I can not push a branch with the change (I suppose I have no permission)

You need to **fork** this repo, and send a pull request.

**Comment by wgwz** [comment]
@lepture which other parts do not match what is in the example folder? i thought i had covered everything but testing. i decided to [lead readers into the separate testing with flask section](http://flask.pocoo.org/docs/0.12/tutorial/testing/#adding-tests-to-flaskr)

**Comment by SergioDS** [comment]
Well, if you follow the tutorial you reach that link http://flask.pocoo.org/docs/0.12/testing/#testing where you can see the mismatch between the documentation and the code. Thus, the documentation does not permit to finish the tutorial. 

Sergio Díaz

**Comment by lepture** [comment]
@wgwz http://flask.pocoo.org/docs/0.12/testing/

**Comment by davidism** [comment]
Duplicate / part of #1374.
