### ISSUE TITLE
Add instructions for running Flask with PyCharm

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2198]
With the introduction of the `flask` command, setting up PyCharm is not as straightforward. Some screenshots and instructions would be useful. Similar to the section on how to deploy to common platforms.

**Comment by ThiefMaster** [comment]
Maybe PyCharm should have some shortcut to run an app tthrough the `flask` cli since they already have claim to support flask?

**Comment by pmayer** [comment]
I added a feature request in YouTrack: https://youtrack.jetbrains.com/issue/PY-23190

**Comment by davidism** [comment]
While we now document this in Flask, I encourage anyone who comes across this to go vote for the linked PyCharm issue. You'll need to log in, then there's a small checkmark at the bottom of the right-hand sidebar (the star is not the same as the vote button).
