### ISSUE TITLE
Connection reset when posting data

### ISSUE THREAD

**Issue by deelaka** [pallets/flask#2205]
When posting data with an mimetype unknown to flask unless `request.get_data()` is accessed in whatever way the connection is dropped.

```
@app.route('/abc', methods=['POST'])
def get_history():
    # print request.get_data()  # uncommenting this line fixes the bug
    return 'OK', 200
```

Below is a curl stacktrace:
```
> curl -X POST -d 'a:1' "http://127.0.0.1:5000/abc"
curl: (56) Recv failure: Connection was reset
```

The most confusing fact is that the flask server reports as if the connection was successful:

`127.0.0.1 - - [14/Mar/2017 20:03:16] "POST /abc HTTP/1.1" 200 -`

Flask (0.12) & Python 2.7.12

**Comment by davidism** [comment]
Possibly related to #2188

**Comment by brianrusso** [comment]
Cannot replace with Python 2.7.12 & Flask 0.12.1

127.0.0.1 - - [22/May/2017 17:11:36] "POST /abc HTTP/1.1" 200 -
127.0.0.1 - - [22/May/2017 17:11:36] code 400, message Bad request syntax ('a:1')
127.0.0.1 - - [22/May/2017 17:11:36] "a:1" 400 -

curl responds with 'OK' as I would expect.

**Comment by andreypanin** [comment]
Two years after I encountered the very same problem. Flask 1.1.0, Python 3.7.3.
Don't have hopes for it to be fixed, just wanted to thank @deelaka for the workaround.
