### ISSUE TITLE
Do not swallow exceptions if CLI fails to load

### ISSUE THREAD

**Issue by svenstaro** [pallets/flask#2208]
I think the changes introduced in https://github.com/pallets/flask/commit/fa6eded6f572dd4bc23b030f025156cdd1e63305 that swallow ALL exceptions if loading a custom CLI command fails are not good for the general development flow. I often do `flask --help` to see whether my custom command comes up fine and when it doesn't I don't get exceptions and I don't really know what I've done wrong.

I think this `try-except` should be removed. I really think the CLI _should_ fail loudly instead of ignoring errors. Let's discuss this and if you guys agree I'll make a PR.

**Comment by ThiefMaster** [comment]
Especially the `run` command should not fail loudly when loading the app fails. Otherwise you need to restart it manually when you e.g. saved a file with a syntax error.

However, printing the traceback could be useful...

**Comment by svenstaro** [comment]
Alright fair enough. I propose adding a traceback, in that case.

**Comment by svenstaro** [comment]
Alright I did what you said in a PR. Does that look ok to you?
