### ISSUE TITLE
Documentation: Installing and virtual environment under python3

### ISSUE THREAD

**Issue by runartrollet** [pallets/flask#2212]
For installing Flask under a virtual environment with python3, the procedure is somewhat different that what is proposed in the Documentation, under Installation, virtuallenv. See [Answer by _geckon_ to question _Using Python 3 in virtualenv_
](http://stackoverflow.com/a/30233408/3493586)

This is a minor change, just 
`python3 -m venv /path/to/new/virtual/environment`
instead of 
`virtualenv venv`

I would be willing to contribute with this if assigned the task.

**Comment by ThiefMaster** [comment]
Go for it, just make sure it's clear how to do it in both Python2 and Python3

**Comment by jeffwidman** [comment]
@runartrollet it looks like you created a commit for this, but never opened a pull request for this. Are you planning to do so?

**Comment by davidism** [comment]
Oh, that was me rewriting the docs some more. This should be addressed now.
