### ISSUE TITLE
Flask blames FLASK_APP on all ImportErrors

### ISSUE THREAD

**Issue by edbrannin** [pallets/flask#2214]
(Observed on Python 2.7; untested on 3.x)

## Steps to reproduce:

```
echo "import thisisnotarealpackage" > error_app.py
export FLASK_APP=error_app.py
flask run
```

## Expected result:

* Some indication that `thisisnotarealpackage` is not a real package

## Observed result:

```
Usage: python -m flask run [OPTIONS]

Error: The file/path provided (error) does not appear to exist.
Please verify the path is correct.
If app is not on PYTHONPATH, ensure the extension is .py
```

(Newlines added)

## Why Bother

This has been causing some confusion on my team because `cx_Oracle` can fail to import (from the bowels of SQLAlchemy) if it can't find certain Oracle support files on the host machine.

**Comment by mohamed-aziz** [comment]
why not importing error_app and seeing if it raises an ImportError?

**Comment by edbrannin** [comment]
@mohamed-aziz Trying to import (or run directly) error_app _is_ how we figured out what was going on. :)  It just took a while to get there before we discovered this.

**Comment by ThiefMaster** [comment]
I think the best solution would be just showing the exception/traceback in this case.

**Comment by kblomqvist** [comment]
Did you try with the code in master? The issue related to this seems to be fixed in https://github.com/pallets/flask/commit/0f1cf50f97a617114078be3dbae3152339ff13ad and https://github.com/pallets/flask/commit/0832e77b145b226bac4ee82144221800a0f7d34a.

**Comment by edbrannin** [comment]
Oh!  Yes, that's much better.  Sorry to bother you. :)

Actually -- before I tried, I had already added a `traecback.print_exc()` in `cli.py` and its output is much more concise (2 lines of stack trace instead of 17).

I'll submit a PR with this for further consideration.

**Comment by edbrannin** [comment]
Merged, yay!

**Comment by mscheper** [comment]
FWIW, I can confirm that this problem also occurs in Python 3.6 (and Flask 0.12). @edbrannin: Is there a schedule for when the master branch will become a 0.13 release?

**Comment by davidism** [comment]
@mscheper there is no official release schedule (also, the person you pinged is just a contributor, not a maintainer). If you need a change that has not been released, you can always install the dev version:

    pip install https://github.com/pallets/flask/tarball/master
