### ISSUE TITLE
Support for dict-like arguments in request.args

### ISSUE THREAD

**Issue by Mahi** [pallets/flask#2215]
Sometimes you need key-value pairs in your query params, and at those times it would be nice to have a built-in support. Here's what I've seen some APIs use, which looks reasonable to me:

    http://example.com/api/search?name=Markus&hobby[football]=1&hobby[basketball]=0

Which would construct `request.args` like so:

    {
        'name': 'Markus',
        'hobby': {
            'football': 1,
            'basketball': 0,
        }
    }

**Comment by ThiefMaster** [comment]
I think the better solution for this is to POST a JSON payload.

Either way, the format of such nested values would probably be application-specific - some use `foo[bar]`, others would prefer `foo.bar`. Flask on the other hand isn't really opinionated in most regards.

FWIW, in your example a URL like this would be much cleaner (not sending deselected values at all.

    /api/search?name=Markus&hobby=football

To handle multiple values for an option you'd  use `request.args.getlist('hobby')`


PS: Letting the client change the type of `request.*` items is unacceptable for sure, this was (is?) already cancerous in PHP (code expecting a string suddenly getting an array etc). So you'd need something like `.getstruct()` similar to `.getlist()` but I'm strongly 👎 to this idea nonetheless.

**Comment by Mahi** [comment]
> FWIW, in your example a URL like this would be much cleaner (not sending deselected values at all.
>
> `/api/search?name=Markus&hobby=football`

This wouldn't quite work, since I want to particularly search for Markus who *does* play football and *does not* play basketball. I don't care if he plays ice hockey or not. Surely I could add `hobby_not` param, but the more complex the search gets, the more complex this would get.

> I think the better solution for this is to POST a JSON payload.

Better in terms of programming, but worse for the clients using the search, unfortunately.

> some use `foo[bar]`, others would prefer `foo.bar`

Everyone has their preferences, sure, but right now we have no option at all to do this. I don't mind if it's `foo[bar]` or `foo.bar` or `<:foo:>//--->@bar@` (okay I do mind that) as long as we'd have *some* way of doing this. Yes of course someone might argue that `foo.bar` would've been better than `foo[bar]`, but I don't think anyone would argue at that point that having nothing would've been better than having the "less preferred" one.

**Comment by ThiefMaster** [comment]
I think you should be doing it in your application. `args = parse_structured_args(request.args)` wouldn't be too ugly. And if you want to use it for `request.args` you can always override the storage class for `request.args` on your Flask instance (but in that case I'd really go for a subclass that only exposes structured data when using e.g. `.getstruct()`)

**Comment by Mahi** [comment]
Yeah that's what I'm doing right now, but I was thinking others might want it too. What's the main reason not to have it built-in though? Adding `.getstruct()` would still be completely backwards compatible.
