### ISSUE TITLE
Werkzeug 0.12.0 changed how abort works

### ISSUE THREAD

**Issue by aluttik** [pallets/flask#2218]
[This line in flask.\_\_init\_\_.py](https://github.com/pallets/flask/blob/master/flask/__init__.py#L17) breaks everything now that `werkzeug==0.12.0` was released.

`werkzeug.exceptions.abort` is now a function, so `abort.mapping` throws an error.

[This line in setup.py](https://github.com/pallets/flask/blob/master/setup.py#L74) definitely needs to be updated - preferably with a frozen Werkzeug version so this doesn't happen again.

**Comment by untitaker** [comment]
`abort` was always documented to be a function in the Werkzeug docs. We will definetly not pin Werkzeug to a specific version.
