### ISSUE TITLE
Flask treats SystemExit and other BaseExceptions as indicating success

### ISSUE THREAD

**Issue by Diggsey** [pallets/flask#2221]
See here:
https://github.com/pallets/flask/blob/master/flask/app.py#L1991

When combined with a database layer, this completely breaks transaction guarantees, as the request context "pop" handler will see no error and assume the transaction was successful, resulting in it being committed while in an inconsistent state.

**Comment by ThiefMaster** [comment]
https://github.com/pallets/flask/blob/master/flask/app.py#L1528

I don't see why you would have database logic running outside your flask app (wsgi middleware?) but if you tell Flask to propagate exceptions they'll be re-raised.

**Comment by ThiefMaster** [comment]
Also, see https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L846-L850 - in teardown_appcontext you can check whether there has been an exception or not and commit/rollback accordingly.

The request context callbacks are not the right place for this - a database transaction usually does not need an actual HTTP request.

**Comment by untitaker** [comment]
I'm not sure I understand. Why does your db driver raise `SystemExit`?

**Comment by Diggsey** [comment]
@ThiefMaster `handle_exception` is not called on `BaseException`s so is not useful. Yes, we use retry middleware to automatically retry transactions which are rolled back due to deadlock. Regardless of whether you consider this good practice, flask should not be treating `BaseException`s as though no error occurred.

@untitaker My DB driver doesn't raise `SystemExit`, it is raised externally whenever the orchestration system (in this case kubernetes) decides to shutdown a pod. This should be a clean shutdown, and should not be corrupting the database...

**Comment by ThiefMaster** [comment]
Oh now I see, you want this code to handle non-Exception-subclass exceptions too...

**Comment by ThiefMaster** [comment]
Even though I'm still not sure why you would ever get a SystemExit from application code - where does Kubernetes inject the exception?

**Comment by Diggsey** [comment]
It may be `KeyboardInterrupt` rather than `SystemExit`, I'm not sure. Since flask quits and none of our error handlers trigger we don't get any log output! (This was a huge PITA to debug).

**Comment by ThiefMaster** [comment]
That sounds like you are using the `app.run()` / `flask run` dev server. I'd expect proper wsgi servers to finish processing a request and then shutting down cleanly instead of sending KeyboardInterrupt when shut down.

**Comment by untitaker** [comment]
Yes, just changing this to `BaseException` will likely prevent users from stopping the dev server, though I haven't actually tried this. If you could find out which exception is actually raised, this would make decision-making easier. Perhaps we could only re-raise `SystemExit` and `KeyboardInterrupt`.

**Comment by Diggsey** [comment]
@ThiefMaster I will look into that, thanks.

@untitaker I would expect non-`Exception` exceptions to be re-raised. The important thing as far as I'm concerned is that `auto_pop` is not called with `None` as the argument, because that indicates success.

**Comment by Diggsey** [comment]
@ThiefMaster We're using gunicorn, and it does wait for the worker to finish in response to `SIGTERM`, but it appears that docker/kubernetes may be sending `SIGINT` (maybe if the container takes too long to shut down?), which results in a `SystemExit` exception being raised in the gunicorn workers.
