### ISSUE TITLE
flask.pocoo.org not updated with latest release (0.12.1)

### ISSUE THREAD

**Issue by klaplong** [pallets/flask#2227]
I was trying to find out what changed from 0.12 to 0.12.1 and had to come here. Please update the changelog on the website.

**Comment by ThiefMaster** [comment]
https://github.com/pallets/flask/blob/master/CHANGES#L18-L31

**Comment by klaplong** [comment]
Please actually read my message. 

> Please update the changelog **on the website**.

**Comment by untitaker** [comment]
I updated the doc builder but I'm not sure if this will automatically deploy
itself.

@mitsuhiko the werkzeug builder is broken in a similar way and the server
builder is a blackbox for me. Could you give me SSH access?

**Comment by aalhour** [comment]
The doc is not updated with the latest v0.12.2 release as well.
