### ISSUE TITLE
FLASK_DEBUG=1 causes ModuleNotFoundError: No module named 'flask' 

### ISSUE THREAD

**Issue by hniedner** [pallets/flask#2232]
A similar phenomenon has been described on Win10, however this occurs on a Mac (10.12.5 Beta) after upgrading to Python Version 3.6.1. The Flask application runs fine without DEBUG enabled. 
Before filing this as a dupe please consider that I am using Werkzeug (0.12.1) already.

pip3 list:
appdirs (1.4.0)
argh (0.26.2)
click (6.7)
dominate (2.3.1)
Flask (0.12.1)
Flask-Bootstrap (3.3.7.1)
Flask-Bower (1.2.1)
Flask-WTF (0.14.2)
itsdangerous (0.24)
Jinja2 (2.9.6)
MarkupSafe (1.0)
packaging (16.8)
pathtools (0.1.2)
pbr (1.10.0)
pip (9.0.1)
pyparsing (2.1.10)
PyYAML (3.12)
requests (2.13.0)
setuptools (28.8.0)
six (1.10.0)
stevedore (1.20.0)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
visitor (0.1.3)
Werkzeug (0.12.1)
wheel (0.29.0)
WTForms (2.1)

**Comment by waynew** [comment]
Double check - is Flask reporting the correct path? I'm getting weird issues with it launching from 3.6 and then re-launching with 3.5 😕

**Comment by hniedner** [comment]
@waynew I am using a python 3 virtual environment:
```
(venv) ➜  ctrp_rest_client git:(master) ✗ which python
/Users/hannes/PycharmProjects/ctrp_rest_client/venv/bin/python
(venv) ➜  ctrp_rest_client git:(master) ✗ python --version
Python 3.6.1
(venv) ➜  ctrp_rest_client git:(master) ✗ pip show flask
Name: Flask
Version: 0.12.1
Summary: A microframework based on Werkzeug, Jinja2 and good intentions
Home-page: http://github.com/pallets/flask/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /Users/hannes/PycharmProjects/ctrp_rest_client/venv/lib/python3.6/site-packages
Requires: itsdangerous, Werkzeug, Jinja2, click
```
Is there anything else I should check?

**Comment by hniedner** [comment]
@waynew It looks like you had the right hunch. I did find a flask script that seems to be the culprit:
```
#!/usr/local/opt/python3/bin/python3.5

# -*- coding: utf-8 -*-
import re
import sys

from flask_appconfig.cli import cli

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
/usr/local/bin/flask (END)
```
Will report back shortly.

**Comment by hniedner** [comment]
@waynew Still now dice:
```
venv) ➜  ctrp_rest_client git:(master) ✗ export FLASK_APP=ctrp_rest_client     
(venv) ➜  ctrp_rest_client git:(master) ✗ export FLASK_DEBUG=0          
(venv) ➜  ctrp_rest_client git:(master) ✗ pip install -e .                      
Obtaining file:///Users/hannes/PycharmProjects/ctrp_rest_client
Requirement already satisfied: flask in ./venv/lib/python3.6/site-packages (from ctrp-rest-client==0.0.0)
Requirement already satisfied: Flask-Bootstrap in ./venv/lib/python3.6/site-packages (from ctrp-rest-client==0.0.0)
Requirement already satisfied: Flask-WTF in ./venv/lib/python3.6/site-packages (from ctrp-rest-client==0.0.0)
Requirement already satisfied: itsdangerous>=0.21 in ./venv/lib/python3.6/site-packages (from flask->ctrp-rest-client==0.0.0)
Requirement already satisfied: click>=2.0 in ./venv/lib/python3.6/site-packages (from flask->ctrp-rest-client==0.0.0)
Requirement already satisfied: Werkzeug>=0.7 in ./venv/lib/python3.6/site-packages (from flask->ctrp-rest-client==0.0.0)
Requirement already satisfied: Jinja2>=2.4 in ./venv/lib/python3.6/site-packages (from flask->ctrp-rest-client==0.0.0)
Requirement already satisfied: dominate in ./venv/lib/python3.6/site-packages (from Flask-Bootstrap->ctrp-rest-client==0.0.0)
Requirement already satisfied: visitor in ./venv/lib/python3.6/site-packages (from Flask-Bootstrap->ctrp-rest-client==0.0.0)
Requirement already satisfied: WTForms in ./venv/lib/python3.6/site-packages (from Flask-WTF->ctrp-rest-client==0.0.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./venv/lib/python3.6/site-packages (from Jinja2>=2.4->flask->ctrp-rest-client==0.0.0)
Installing collected packages: ctrp-rest-client
  Found existing installation: ctrp-rest-client 0.0.0
    Not uninstalling ctrp-rest-client at /Users/hannes/PycharmProjects/ctrp_rest_client, outside environment /Users/hannes/PycharmProjects/ctrp_rest_client/venv
  Running setup.py develop for ctrp-rest-client
Successfully installed ctrp-rest-client
(venv) ➜  ctrp_rest_client git:(master) ✗ flask run                      
Traceback (most recent call last):
  File "/Users/hannes/PycharmProjects/ctrp_rest_client/venv/bin/flask", line 7, in <module>
    from flask.cli import main
ModuleNotFoundError: No module named 'flask'
```

**Comment by davidism** [comment]
What does `type flask` from within your env say? If it gives something under `/usr/local/opt/python3/bin`, then there's a problem with your env.

**Comment by hniedner** [comment]
@davidism Here it is. I think the file I referenced above was a body from a prev install
```
(venv) ➜  ctrp_rest_client git:(master) ✗ flask
Traceback (most recent call last):
  File "/Users/hannes/PycharmProjects/ctrp_rest_client/venv/bin/flask", line 7, in <module>
    from flask.cli import main
ModuleNotFoundError: No module named 'flask'
(venv) ➜  ctrp_rest_client git:(master) ✗ 
```

**Comment by hniedner** [comment]
Hmm, it looks like my venv has a ```flask``` script:
```
#!/usr/local/opt/python3/bin/python3.6

# -*- coding: utf-8 -*-
import re
import sys

from flask.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
I assume this is put there by pip install flask but I am not sure. Still I am puzzled that it would not reference the venv/bin/python???

**Comment by hniedner** [comment]
@waynew @davidism Thank you both. I am not sure what, but there may indeed have been something wrong with my venv. I recreated it and now it works. Still I am not sure I deterministically understand what the actual problem was.

**Comment by davidism** [comment]
Yes, something went wrong with your virtualenv. The venv's `flask` executable should point at the venv's Python.

**Comment by hniedner** [comment]
Yes, it does now. I could have sworn I repeated the same steps as before, but human memory os faulty - the compiler never lies ;-)

**Comment by zibuyu1995** [comment]
Flask is installed in your global env,  remove global Flask

**Comment by davidism** [comment]
Don't mess with system packages. If Flask is installed in the system, let the system mangage it. The entire point of virtual environments is to be isolated from the system packages, so uninstalling it will do absolutely nothing and may break other system-installed software.
