### ISSUE TITLE
Bug in url_for() function when you run a Flask application through CGI

### ISSUE THREAD

**Issue by koddr** [pallets/flask#2236]
*Note: I don't observe this bug if I run application on a dedicated server (VDS) with Nginx and uWSGI or Gunicorn, only on an shared hosting (Apache2).*

My application structure:

```bash
└─ site.com
     └── public_html
             ├─ venv             <-- virtualenv dir with Python 3.4.3
             ├─ templates        <-- templates dir with `page.html`
             ├─ .htaccess        <-- HTACCESS file
             ├─ app.cgi          <-- CGI script
             └─ app.py           <-- Very basic Flask application
```

Files ```.htaccess``` and ```app.cgi``` I take from [official docs](http://flask.pocoo.org/docs/0.12/deploying/cgi/), but duplicate for comfort.

And this is **.htaccess** file:

```bash
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /home/XXXX/site.com/public_html/app.cgi/$1 [L]
```

Yep, it's **app.cgi**:

```cgi
#!/home/XXXX/site.com/public_html/venv/bin/python3.4
# -*- coding: utf-8 -*-

from wsgiref.handlers import CGIHandler
from app import app

CGIHandler().run(app)
```

This is my **app.py** file:

```python
# -*- coding: utf-8 -*-

from flask import Flask, render_template, url_for

app = Flask(__name__)

@app.route('/<slug>')
def page(slug):
    return render_template('page.html', slug=slug)

if __name__ == '__main__':
    app.run(host='0.0.0.0')
```

Template is:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{{ slug }}</title>
</head>
<body>
    <a href="{{ url_for('page', slug='about') }}">About page</a>
    <a href="{{ url_for('page', slug='contacts') }}">Contacts page</a>
</body>
</html>
```

All working fine, but if I go to ```http://site.com/about``` and click to ```Contacts page``` link — URL on browser adress is ```http://site.com/app.cgi/contacts``` instead ```http://site.com/contacts``` O_o I delete ```/app.cgi/``` from adress stroke and get the same page!

What is this? Bug in ```url_for()``` functon? Fix it please.

**Comment by davidism** [comment]
You're missing `ScriptAlias`. Either add the alias in the config, or if you don't have access to that (shared hosting), apply apply [`CGIRootFix`](http://werkzeug.pocoo.org/docs/0.11/contrib/fixers/#werkzeug.contrib.fixers.CGIRootFix).

~~~python
from werkzeug.fixers import CGIRootFix

app.wsgi_app = CGIRootFix(app.wsgi_app)
~~~

**Comment by koddr** [comment]
Oh, many thanks! But give me a link on Flask docs with this fix, please 👍

**Comment by koddr** [comment]
@davidism hmm.. maybe I wrong, but this is NOT solve this problem!

This is my **app.cgi** after install ```Werkzeug```:

```bash
#!/home/XXXX/site.com/public_html/venv/bin/python3.4
# -*- coding: utf-8 -*-

import sys
from wsgiref.handlers import CGIHandler
from werkzeug.contrib.fixers import CGIRootFix
from app import app

wsgi_app = CGIRootFix(app, app_root='/home/XXXX/site.com/public_html/')

CGIHandler().run(app)
```

And I still seen ```/app.cgi/``` on every ```url_for()``` link.. T_T

**Comment by ThiefMaster** [comment]
You assign to `wsgi_app` but use `app` in the CGIHandler.

**Comment by koddr** [comment]
@ThiefMaster yes, my bad. After change to ```CGIHandler().run(wsgi_app)``` I've 404 for all site's urls.

What's wrong now? Can you help me plase?

**Comment by ThiefMaster** [comment]
I think you should continue this on IRC. This place isn't really intended for support... Not sure how succesful that'll be though, using CGI for WSGI apps is not a very good idea and thus few people do it.

**Comment by davidism** [comment]
The root is the *URL root*, not the *filesystem* root. Leave it as `/` (the default).

**Comment by koddr** [comment]
@davidism for any changes I've 404 error for all URLs.. T_T

**Comment by koddr** [comment]
@davidism if I use this CGI file:

```python
#!/home/XXXX/site.com/public_html/venv/bin/python3.4
# -*- coding: utf-8 -*-

from wsgiref.handlers import CGIHandler
from werkzeug.contrib.fixers import CGIRootFix
from app import app

app.wsgi_app = CGIRootFix(app)

CGIHandler().run(app.wsgi_app)
```

I've error 500 and logs tell me:

```bash
[cgi:error] [pid 24626] [client X.X.X.X:45749] AH01215:   File "/home/XXXX/site.com/public_html/venv/lib/python3.4/site-packages/werkzeug/contrib/fixers.py", line 59, in __call__
```

Very bad day for deploy Flask project on shared hosting T_T
