### ISSUE TITLE
Take advantage of Py3.6 json support for bytes

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2243]
[Python 3.6 added support for loading json from str or bytes.](https://docs.python.org/3.6/library/json.html#json.loads) It handles detection of the three encodings supported by JSON. Would be nice to take advantage of this if the user is using 3.6+ instead of our basic "assume it's UTF-8" approach.

Would have to make sure simplejson also allows this (I think it does).

Then again, I'm not sure there have been any reports of Flask decoding JSON incorrectly. Maybe no real clients are encoding with anything besides UTF-8?

**Comment by akohli96** [comment]
[json.py](https://github.com/pallets/flask/blob/46f83665ef74880bbc4a1c1f17ccededa7aaa939/flask/json.py)
shows 

````python
def loads(s, **kwargs):
    """Unserialize a JSON object from a string ``s`` by using the application's
    configured decoder (:attr:`~flask.Flask.json_decoder`) if there is an
    application on the stack.
    """
    _load_arg_defaults(kwargs)
    if isinstance(s, bytes):
        s = s.decode(kwargs.pop('encoding', None) or 'utf-8')
    return _json.loads(s, **kwargs)


def load(fp, **kwargs):
    """Like :func:`loads` but reads from a file object.
    """
    _load_arg_defaults(kwargs)
    if not PY2:
        fp = _wrap_reader_for_text(fp, kwargs.pop('encoding', None) or 'utf-8')
    return _json.load(fp, **kwargs)
```

**Comment by davidism** [comment]
We're the ones doing the decoding. In Py36, `_json.loads` does the decoding.

**Comment by akohli96** [comment]
Okay, I see what you are saying. 
Would a simple 

````python
if not PY2:
     return _json.loads(s, **kwargs)
else:
    if isinstance(s, bytes):
        s = s.decode(kwargs.pop('encoding', None) or 'utf-8')
    return _json.loads(s, **kwargs)
````
solve this problem

**Comment by akohli96** [comment]
````python
if PY2:
    if isinstance(s, bytes):
        s = s.decode(kwargs.pop('encoding', None) or 'utf-8')
return _json.loads(s, **kwargs)
````

This looks better

**Comment by davidism** [comment]
No, because only Py3.6 supports this, but we support Py3.3+.

**Comment by akohli96** [comment]
Alright, so essentially check if its Py3.6 specifically and then implement what I was doing?

[_compat.py](https://github.com/pallets/flask/blob/0664a3f2ddfc227797b5a8f0654e9959b15d9e64/flask/_compat.py)

A check would be needed here for Py3.6

I could have a crack at it.

**Comment by akohli96** [comment]
I thought I fixed it @ #2262 but it is failing on builds on REQUIREMENTS with no simplejson ([devel](https://travis-ci.org/pallets/flask/jobs/227018214) and [release](https://travis-ci.org/pallets/flask/jobs/227018212)).
See here :  [https://travis-ci.org/pallets/flask/builds/227018178](https://travis-ci.org/pallets/flask/builds/227018178)

**Comment by akohli96** [comment]
````Then again, I'm not sure there have been any reports of Flask decoding JSON incorrectly. Maybe no real clients are encoding with anything besides UTF-8?````

**Comment by akohli96** [comment]
#2262 [Build is now successful](https://travis-ci.org/pallets/flask/builds/227148904?utm_source=github_status&utm_medium=notification)

Commit : [d93cfb92823143c0127abc91827f79a30056a936](https://github.com/pallets/flask/pull/2262/commits/d93cfb92823143c0127abc91827f79a30056a936)

**Comment by davidism** [comment]
@untitaker @ThiefMaster a failing test uses an invalid JSON charset. Do we want to support invalid JSON charsets?

**Comment by untitaker** [comment]
Yeah, I think we should keep that feature. I don't really see how that's an
invalid charset too.

You earlier say that Flask assumes JSON is UTF-8, but according to the failing
test it doesn't.

**Comment by davidism** [comment]
Technically, the only valid charsets for JSON are UTF-8, -16, and -32. On the one hand, us accepting charsets means we can support invalid charsets. On the other hand, 8, 16, and 32 can be autodetected without relying on the specified charset.

**Comment by untitaker** [comment]
That's fair enough. I suppose we could deprecate other charsets for JSON, but I would wish for a softer kind of deprecation.

**Comment by akohli96** [comment]
@davidism could #2262 be modified in any way to resolve this issue?

**Comment by davidism** [comment]
@untitaker it adds some complexity, but what do you think of this:

1. If an unsupported encoding is specified on any version, show a warning.
2. If < 3.6, or > 3.6 with an unsupported encoding, decode.

The important path here is 3.6 and no encoding for autodetection, while still supporting other encodings if they are specified. Alternatively, we could always prefer the encoding if it is specified, even on 3.6, so that the client could override the detection.

Not sure if we should actually deprecate the unsupported encodings, given this comment in `flask.wrappers.Request.get_json`: 

>     # We accept a request charset against the specification as
>     # certain clients have been using this in the past.  This
>     # fits our general approach of being nice in what we accept
>     # and strict in what we send out.

We wouldn't actually reduce complexity by deprecating them, since we still need all the code to support < 3.6.

---

`flask.json`:

~~~python
# normalized names of the supported JSON encodings
json_encodings = set(codecs.lookup('utf-{0}'.format(x)).name for x in (8, 16, 32))
~~~

`flask.json.loads`:

~~~python
# normalize incoming encoding name
codec = codecs.lookup(kwargs.pop('encoding', None) or 'utf-8')
supported = codec.name in json_encodings

if not supported:
    warnings.warn(
        'JSON must be encoded UTF-8, -16, or -32, but got {codec.name}.'.format(codec=codec),
        stacklevel=2
    )

# < 3.6 or unsupported encoding, decode manually
if isinstance(s, bytes) and not (PY36PLUS and (encoding is None or supported):
    s = codec.decode(s)
~~~

**Comment by untitaker** [comment]
The problem I have with this is that Flask now behaves differently across minor versions of Python (accepting JSON without encoding for some). Perhaps encoding detection should be explicitly enabled via a config param, which fails for any version other than 3.6. That would make the behavioral change more explicit.

On 1 May 2017 18:23:12 GMT+02:00, David Lord <notifications@github.com> wrote:
>@untitaker it adds some complexity, but what do you think of this:
>
>1. If an unsupported encoding is specified on any version, show a
>warning.
>2. If < 3.6, or > 3.6 with an unsupported encoding, decode.
>
>The important path here is 3.6 and no encoding for autodetection, while
>still supporting other encodings if they are specified. Alternatively,
>we could always prefer the encoding if it is specified, even on 3.6, so
>that the client could override the detection.
>
>Not sure if we should actually deprecate the unsupported encodings,
>given this comment in `flask.wrappers.Request.get_json`: 
>
>>     # We accept a request charset against the specification as
>>     # certain clients have been using this in the past.  This
>>     # fits our general approach of being nice in what we accept
>>     # and strict in what we send out.
>
>We wouldn't actually reduce complexity by deprecating them, since we
>still need all the code to support < 3.6.
>
>---
>
>`flask.json`:
>
>~~~python
># normalized names of the supported JSON encodings
>json_encodings = set(codecs.lookup('utf-{0}'.format(x)).name for x in
>(8, 16, 32))
>~~~
>
>`flask.json.loads`:
>
>~~~python
># normalize incoming encoding name
>codec = codecs.lookup(kwargs.pop('encoding', None) or 'utf-8')
>supported = codec.name in json_encodings
>
>if not supported:
>    warnings.warn(
>'JSON must be encoded UTF-8, -16, or -32, but got
>{codec.name}.'.format(codec=codec),
>        stacklevel=2
>    )
>
># < 3.6 or unsupported encoding, decode manually
>if isinstance(s, bytes) and not (PY36PLUS and (encoding is None or
>supported):
>    s = codec.decode(s)
>~~~
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/flask/issues/2243#issuecomment-298366281

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davidism** [comment]
If we take the most conservative approach and only use the autodetection if no encoding is specified, I don't think it's a big deal that >= 3.6 will autodetect while < 3.6 will assume UTF-8.

We can also just drop this, I'm ok with still requiring the charset to be passed if it's needed. Maybe keep the warning.

**Comment by untitaker** [comment]
As far as I understand you're arguing that the set of inputs accepted with 3.6
is a strict superset of the otherwise accepted inputs. That makes it less
worse, however, my fear is that this might send the app dev on a debugging tour
why his app works on their ArchLinux laptop (which has bleeding edge Python)
and fails on their CentOS server (which has god-knows-which version).
