### ISSUE TITLE
file input request filepath.

### ISSUE THREAD

**Issue by faststare** [pallets/flask#2245]
hello flask,

I just need help regarding request.files['spam'].
why request.files not have filepath attribute?

here my stackflow issue http://stackoverflow.com/questions/41882959/get-path-of-file-uploaded-to-flask
that needed a fullpath attribute.

please kindly support it.

**Comment by ThiefMaster** [comment]
Browsers do not send meaningful information there to avoid leaking information the server has no need to know so it makes not much sense to expose more than just the filename in Flask.
