### ISSUE TITLE
circular import error with flask cli is misleading

### ISSUE THREAD

**Issue by eMerzh** [pallets/flask#2250]
I got a circular import error in my flask app, 
and i launch it using flask run.

it seems to launch but when i go the endpoint with my browser, 
i got a pretty misleading error message : 

>NoAppException: The file/path provided (run) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py

but when i run it using the run.py file i got:
>ImportError: cannot import name XXXX

it can be great to have a better exception when there is an import error

**Comment by davidism** [comment]
Please try again with the dev version:

    pip install -U https://github.com/pallets/flask/archive/master.tar.gz

**Comment by eMerzh** [comment]
Yes it works!
Thanks and sorry for delay
