### ISSUE TITLE
QueueHandler logging does not work behind uwsgi

### ISSUE THREAD

**Issue by vimalloc** [pallets/flask#2257]
(I'm not sure if I should open this here or at uwsgi, feel free to close if this is not appropriate).

Using a QueueHandler with flask works fine when using the built in flask server, but it fails to log to any of the handlers specified in the QueueHandler when run behind uwsgi (Flask==0.12.1, uWSGI==2.0.15, python==3.5.2). 

Here is an example app to demonstrate this:

```python
import logging
from logging.handlers import SMTPHandler, QueueHandler, QueueListener
from queue import Queue
from flask import jsonify, Flask

app = Flask(__name__)
app.debug = False
app.logger.setLevel(logging.INFO)

# Setup logging formatting
log_fmt = logging.Formatter(
    fmt='%(levelname)s: %(asctime)s - %(name)s - %(message)s',
    datefmt='%m/%d/%Y %H:%M:%S'
)

# Setup file log handler
file_handler = logging.FileHandler('/tmp/test_logger.log')
file_handler.setLevel(logging.INFO)
file_handler.setFormatter(log_fmt)

# Setup email log handler
mail_handler = SMTPHandler(
    'localhost',
    'flask_app_error@domain.tld',
    ['email@domain.tld'],
    'Error in flask app'
)
mail_handler.setLevel(logging.ERROR)
mail_handler.setFormatter(log_fmt)

# Setup a queue handler which will handle logs on a separate thread
log_queue = Queue(-1)
queue_handler = QueueHandler(log_queue)
queue_listener = QueueListener(log_queue, mail_handler, file_handler,
                               respect_handler_level=True)
app.logger.addHandler(queue_handler)
queue_listener.start()

log = logging.getLogger(__name__)

@app.route('/error')
def error_test():
    log.error("Test logging")
    return jsonify({'foo': 'bar})

if __name__ == '__main__':
    app.run()
```

And I run it with:
```bash
uwsgi --http :5000 --mount /=test_logger:app --manage-script-name
```

If instead of using a QueueHandler/QueueListener, I pass the log handlers to the app.logger directly, things work as expected.
```python
app.logger.addHandler(file_handler)
app.logger.addHandler(mail_handler)
```
 However, I would like to be able to utilize QueueHandler and QueueListener to do logging on a separate thread if possible.

**Comment by davidism** [comment]
Need to use `multiprocessing.Queue`, since uWSGI spawns processes for workers not (necessarily) threads. This doesn't appear to be a Flask issue (or a uWSGI issue).

**Comment by vimalloc** [comment]
Hrm. I tried dropping a ```multiprocessing.Queue``` in place of the normal queue, and running uwsgi with only 1 thread and 1 process, and I'm getting the same results.

I'll dig into it more. Thanks!

**Comment by vimalloc** [comment]
Sorry for the noise, was totally user error :(

In case anyone else looks at this I had to pass ```--enable-threads``` to uwsgi. I imagine you could use a normal ```Queue``` instead of ```multiprocessing.Queue``` as well if you use the ```--lazy-apps``` option. Relevant docs:


> By default the Python plugin does not initialize the GIL. This means your app-generated threads will not run. If you need threads, remember to enable them with enable-threads. Running uWSGI in multithreading mode (with the threads options) will automatically enable threading support. This “strange” default behaviour is for performance reasons, no shame in that.

and

> uWSGI tries to (ab)use the Copy On Write semantics of the fork() call whenever possible. By default it will fork after having loaded your applications to share as much of their memory as possible. If this behavior is undesirable for some reason, use the lazy-apps option. This will instruct uWSGI to load the applications after each worker’s fork(). Beware as there is an older options named lazy that is way more invasive and highly discouraged (it is still here only for backward compatibility)
