### ISSUE TITLE
Static files in non-url_prefixed modules don't work.

### ISSUE THREAD

**Issue by tomekwojcik** [pallets/flask#226]
Hi,
I've encountered a strange bug while working with Flask. When I have two modules (say 'frontend' and 'admin') static files aren't found in frontend module. Admin module is url_prefixed with '/admin' and everything is fine with it.

The only workaround I found was to add a /static route in frontend module and serve files manually.

I've created a simple demo app to show the bug. It's available here: https://github.com/tomekwojcik/Flask-Module-Static-Files

Best ragards.

**Comment by jeffwidman** [comment]
This seems like it's a bug with the old Flask module system, which has been deprecated in favor of blueprints for quite a while. Blueprints do have a similar problem which is tracked over in #348.
