### ISSUE TITLE
Documentation: Term "development mode" is unclear

### ISSUE THREAD

**Issue by dradetsky** [pallets/flask#2261]
I'm doing some work which requires defining some context hooks for our flask app. When reading the documentation for [request contexts*](http://flask.pocoo.org/docs/dev/reqcontext/#callbacks-and-errors) I came across the passage:

>>> In production mode if an exception is not caught, the 500 internal server handler is called. In development mode however...

As a user, I want to know: What is 'development mode?' I _think_ it's debug mode (e.g. `app.run(debug=True)`). I've seen several people use the terms interchangeably when searching for help, but not either the flask developers or the official documentation. The flask docs don't appear to have an index (is it hidden somewhere?), and quick search does not appear to work. Google site search of the dev docs does not immediately turn up an obvious answer.

IMO, this is a bug in the documentation. Assuming for the sake of argument I'm right about dev=debug, that passage should be either:

0. "In development mode (i.e. with `debug=True`) however..." or
1. The text 'development mode' is a link to a list of terms & their definitions
2. Something along those lines.

Maybe if I had carefully read all of the docs from beginning to end, or at least carefully read the tutorial twice, I might not be confused about this. But lots of your users won't do that. That's why I call it a bug (it's sorta like failing to validate input).

*I was in fact reading the docs for the version of flask I'm using, but pointing to dev-version docs b/c I presume they represent the current state of the documentation

**Comment by davidism** [comment]
In that case, it looks like it means debug mode, although it can also mean "while using the dev server" which refers to `app.run`, `flask run` or really just doing development. Do you want to submit a PR changing it to "In debug mode, however, ..."?

**Comment by dradetsky** [comment]
@davidism I sorta don't want to submit a PR inasmuch as it's almost no work to make the required change, but it requires knowledge of Flask I don't actually have. I'd basically be repeating what you told me & assuming it's correct (and maybe you're just fucking with me for the lulz), but also speaking _ex cathedra_ to the Flask n00bs of the world, who deserve to have their docs written by somebody who knows what he's talking about (to the extent that they deserve anything with a free project, but still). It doesn't strike me as a very sensible way to run a project.

But supposing I was going to make a PR: what is the operational definition of "just doing development?" And am I correct in thinking that flask is in development mode both when running on the builtin server with debug=False _and_ when running on (say) uwsgi with debug=True?

**Comment by miguelgrinberg** [comment]
> am I correct in thinking that flask is in development mode both when running on the builtin server with debug=False and when running on (say) uwsgi with debug=True?

I would avoid using "development mode" in reference to a Flask application altogether. For consistency, I think the mode should always be called "debug mode". I think calling the opposite of debug mode "production mode" is also a bit misleading, since this is a mode that you can certainly run on the Flask development server, which is not meant to be used in production.

So regarding your question @dradetsky, in my opinion there is just "debug mode", and it can be on or off, regardless of the server being the builtin one or uwsgi, gunicorn, etc.

There are a couple more references to "production mode" and 'development mode" in the docs besides the one you found that I think would also benefit if they are rephrased in terms of debug mode.

**Comment by davidism** [comment]
There is a distinction to be made between running the development server and running a production server, since the dev server is not intended for production, but I think that's already handled in the deployment page. Most of the docs only care about debug mode on or off.
