### ISSUE TITLE
"Cookie header" munge bad and good cookies together

### ISSUE THREAD

**Issue by dorfsmay** [pallets/flask#2263]
As I am trying to understand how different apps servers and libraries deal with invalid Cookie inside the "Cookie header" (see https://github.com/dorfsmay/Invalid_cookies_in_Cookie_header ), I realised that Flask is munging the invalid cookie with the next one, together:

`curl -b 'SID=31d4d96e407aad42; muffin ; lang=en-US;' localhost:8080` 

==> `{'SID': '31d4d96e407aad42', 'muffin ; lang': 'en-US'}`

I'm sure this was not the desired behaviour, wouldn't it better to just ignore any string between semi-colons that cannot be translated into a valid cookie (so any string without an equal sign)?

**Comment by ThiefMaster** [comment]
Sounds useful, even though I'd say it's garbage either way - are there any clients that send such garbage, ever?

**Comment by dorfsmay** [comment]
Not clients, but I have seen "intermediates" (Load Balancer, intermediate servers (setups where one server flips around and send the request to an upstream service, re-adding all the cookies)) injecting garbage cookies, yes. So this would render the server more robust to this cases.

**Comment by davidism** [comment]
Thanks for looking into this. This was already reported in pallets/werkzeug/#841. Patches would be appreciated. There was one but it was inactive, although the solution seemed on track.
