### ISSUE TITLE
Handle app factory in FLASK_APP

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2264]
`FLASK_APP=myproject.app:create_app('dev')`
[
Gunicorn does this with `eval`](https://github.com/benoitc/gunicorn/blob/fbd151e9841e2c87a18512d71475bcff863a5171/gunicorn/util.py#L364), which I'm not super happy with. Instead, we could use `literal_eval` to allow a simple list of arguments. The line should never be so complicated that `eval` would be necessary anyway.

~~~python
# might need to fix this regex
m = re.search(r'(\w+)(\(.*\))', app_obj)

if m:
    app = getattr(mod, m.group(1))(*literal_eval(m.group(2)))
~~~

**Comment by wgwz** [comment]
Should be `re.search` instead `re.match`, right?

**Comment by davidism** [comment]
Also handle `myproject.app:create_app` without parens. This solution only allows positional arguments (and named `script_info` argument implicitly), but I'm ok with not supporting keyword arguments.

**Comment by lepture** [comment]
Down vote on this feature.

The environ `FLASK_ENV=dev` way would be better.

**Comment by ThiefMaster** [comment]
Something like `FLASK_ENV`  would not belong into the core of a microframework like Flask. You don't necessarily have multiple configs available - actually, if you want to be able to specify which config to use I'd just use `app.config.from_envvar('MYAPP_CONFIG')`.

I'm ±0 on this PR: It does make `FLASK_APP` more flexible, but on the other hand always calling the app factory with no arguments - which. in my opinion, should use the most common default values - keeps things nice and simple.

**Comment by lepture** [comment]
@ThiefMaster Actually I don't use `FLASK_ENV` either. The `FLASK_ENV` way is a suggested replacement for this issue.

I've always been using the `MYAPP_CONF=/path/to/conf.py` to bootstrap the flask app.

**Comment by Kamekameha** [comment]
I'm not that fond either with such flexibility in `FLASK_APP`, a simple call with no arguments to the application factory might be enough, IMO. By looking at the deployment options in the docs we may need to write our own `wsgi.py` (or something similar) application file for a handful of cases anyway.

**Comment by kennethreitz** [comment]
I merged a pull request yesterday which [provides this functionality](https://github.com/pallets/flask/pull/2326)

**Comment by davidism** [comment]
I *really* like the shortcut of being able to call the factory in uWSGI and Gunicorn config. We don't control how people design their factories beyond "has to return a Flask instance". I think the ease of setup outweighs the complexity here. If users want to use env vars instead, that's fine and should probably be documented as an alternative.
