### ISSUE TITLE
Detect `create_app` when FLASK_APP doesn't specify app object

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2265]
`find_best_app` only looks for `app` and `application`. If it can't find those but finds the name `create_app`, it should try to call that with no arguments to get the Flask app.

If we modify `ScriptInfo.load_app` to pass itself to `locate_app` and `find_best_app`, we can make this consistent with #2266.

**Comment by greyli** [comment]
In this case, how to use `@app.cli.command`?  Since blueprint doesn't support `cli.command`, we need to import `app` from the place where the application instance was created (e.g. `wsgi.py`) .

**Comment by davidism** [comment]
`app.cli.add_command` in the factory, just like any of the other non-decorator methods to register things.

**Comment by greyli** [comment]
I have many commands, now I put it in a separate file named `commands.py` (without factory). Is it possible to make it work outside the factory? By the way, what's the best place for the factory, `app/__init__.py` or `app/application.py`? Thanks!
