### ISSUE TITLE
Support create_app that doesn't take ScriptInfo as first argument

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2266]
Use `inspect` to check if the factory takes an argument before passing the script info instance to it.

Preferably pass the info as a keyword instead of positional argument, so that the developer could do something like `def create_app(config=None, script_info=None)`. Still check if the function takes a `script_info` argument before passing it.

Alternatively (or additionally), show how to pass arguments to the factory through the info. I *think* this can be done by overriding `run`, adding an option like `--config`, and setting `info.data['config']` before invoking the built-in run command.

**Comment by aliegha** [comment]
I will work on this one
