### ISSUE TITLE
after_request func called too early for streaming responses

### ISSUE THREAD

**Issue by savvopoulos** [pallets/flask#2270]
`process_response()` calls the `after_request` handlers as soon as a response object is returned.

In the case of streaming responses, it would be more desirable to call after_request handlers at the same time as response.close() is called.

**Comment by untitaker** [comment]
I don't think this API can change anymore. Of course we could add new ones, but you can also modify your response object to add custom hooks on `close`.

**Comment by savvopoulos** [comment]
Thanks. That's what I ended up doing. Feel free to close.

**Comment by untitaker** [comment]
Ok cool.
