### ISSUE TITLE
[Future] Option to get decoded urls in log

### ISSUE THREAD

**Issue by dima74** [pallets/flask#2272]
Hello! Flask logs urls as encoded strings. For example if I have route with cyrillic characters: @app.route('/привет') (https://gist.github.com/dima74/5e025da90ee90a78b65bc3e3c69623ea), than flask will log "GET /%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82 HTTP/1.1". It would be very nice if there is option to get that Flask logs urls decoded. (Thanks for Flask!)

**Comment by davidism** [comment]
Please report this against Werkzeug. Flask does not provide the dev server.

**Comment by dima74** [comment]
OK, thank you a lot.
