### ISSUE TITLE
request.input_stream inconsistency btw debug and normal mode

### ISSUE THREAD

**Issue by FurkanIpek** [pallets/flask#2273]
When `app.config['DEBUG] = True`, `request.input_stream` object has `__enter__` and `__exit__` methods which is cool because we can use it with `with` clause.

When not in debug mode though, using `input_stream` object with `with` clause causes an `AttributeError: __exit__` to be thrown.

I am using `request.input_stream` object in a flask-restplus end-point to retrieve a file whose size is larger than RAM. I also realized that this stream object will not be there if the file size is small.

python version = 2.7.12

**Comment by davidism** [comment]
Debug mode doesn't affect the `input_stream`, it's set by the WSGI server (the dev server is provided by Werkzeug, not Flask). You should not be using `input_stream` anyway, you should be using `stream` for safety. Even so, what would `with` even mean in that context? The stream is already open, and will be closed during the response cycle.
