### ISSUE TITLE
Cannot add headers to static files

### ISSUE THREAD

**Issue by Code-ReaQtor** [pallets/flask#2280]
Hi,

It seems that it is not possible to add HTTP headers to static files. Using this [link](http://stackoverflow.com/questions/30717152/python-flask-how-to-set-response-header-for-all-responses) as reference, it was only able to modify headers for routes (not static files).

**Comment by ThiefMaster** [comment]
Don't serve your static files through Flask in production. Use your webserver (e.g. nginx) to serve these files and add whatever headers you need there.

**Comment by davidism** [comment]
You absolutely can add headers to static files, they're responses like everything else. Unless you're serving the files with your web server in production, then the server controls that.
