### ISSUE TITLE
Flask development server segmentation fault on Alpine Linux

### ISSUE THREAD

**Issue by rossgray** [pallets/flask#2283]
Hi,

I am getting a segmentation fault when running the flask development server on Alpine Linux. Oddly, this issue only appears to occur when I install a recent version of the `requests` library (>= v2.13.0). In addition, this issue occurs even if my application is not using or importing the `requests` lib.

**Environment:**
- `python:3.6-alpine` Docker image
- Python 3.6.1
- Flask 0.12
- Werkzeug 0.12.1

**Commands ran:**

```
/app # flask run
 * Serving Flask app "service"
 * Forcing debug mode on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 960-427-520


/app # pip install requests==2.12.5
...
Successfully installed requests-2.12.5
/app # flask run
 * Serving Flask app "service"
 * Forcing debug mode on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 960-427-520


/app # pip install requests==2.13.0
...
Successfully installed requests-2.13.0
/app # flask run
 * Serving Flask app "service"
 * Forcing debug mode on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Segmentation fault
/app #  * Debugger is active!
 * Debugger PIN: 960-427-520
```

Thanks in advance

**Comment by wgwz** [comment]
I'm tempted to say this is an Alpine Linux bug. Can you try with `python:slim` and see if you get the same behavior?

**Comment by rossgray** [comment]
It only occurs in Alpine. I believe it might be an issue with the Raven package since the issue goes away if I uninstall that. I will raise an issue with the maintainers of that package instead. Thanks
