### ISSUE TITLE
Review HTTP security

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2285]
We should make sure we're providing good, thorough security defaults, or at least documentation on the available options. Not sure if this fits better as Flask config, Werkzeug middleware, or a separate Flask-HTTP-Security extension.

Overview of HTTP security headers: https://blog.appcanary.com/2017/http-security-headers.html
Django's security options: https://docs.djangoproject.com/en/1.11/topics/security/ (some things, such as CSRF and SQL are handled by other libraries, not Flask)

As a first step, good for beginners, it would be nice to get a writeup here of what's already covered and what's not.

**Comment by davidism** [comment]
Setting HSTS and redirecting HTTP to HTTPS might be interesting, cc @kennethreitz

**Comment by aqt01** [comment]
@davidism 


Below a list of security considerations that flask supports, links to their definition and their repo's:

- [x] [Cross-Site Scripting](http://flask.pocoo.org/docs/0.12/security/#cross-site-scripting-xss) (XSS) 
- [x] [Cross-Site Request Forgery](http://flask.pocoo.org/docs/0.12/security/#cross-site-request-forgery-csrf)  (CSRF)
- [x] [JSON Security](http://flask.pocoo.org/docs/0.12/security/#json-security)
- [x] [Content Security Policy](https://csp.withgoogle.com/docs/index.html) (CSP)
-- [flask-csp](https://github.com/twaldear/flask-csp) - last commit feb 23
-- [flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman)
-- [flask-secure-headers](https://github.com/twaldear/flask-secure-headers)
- [x] [HTTP Strict Transport Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) (HSTS)
-- [flask-sslify](https://github.com/kennethreitz/flask-sslify) 
-- [flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman)
-- [flask-secure-headers](https://github.com/twaldear/flask-secure-headers)
- [x] SSL/HTTPS
-- [flask-sslify](https://github.com/kennethreitz/flask-sslify) 
-- [flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman)
-- [flask-secure-headers](https://github.com/twaldear/flask-secure-headers)

- [x] [X-FRAME-OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) (Clickjacking protection)
-- [flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman)
-- [flask-secure-headers](https://github.com/twaldear/flask-secure-headers)
- [x] [X-Content-Type-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options)
-- [flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman)
-- [flask-secure-headers](https://github.com/twaldear/flask-secure-headers)
- [x] [Cookie options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies)
-- [flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman)
-- [flask-secure-headers](https://github.com/twaldear/flask-secure-headers)
- [x] [HTTP Public Key Pinning](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning) (HPKP) 
-- [flask-secure-headers](https://github.com/twaldear/flask-secure-headers)
-- [flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman)
