### ISSUE TITLE
can i preserve my json output ?

### ISSUE THREAD

**Issue by Dj-jom2x** [pallets/flask#2290]
example
```
test = {
    "b": "test",
    "a": "test",
    "h": "test",
    "f": "test"
}
```
they should return
```
 {
    "b": "test",
    "a": "test",
    "h": "test",
    "f": "test"
}
```

adding this app.config["JSON_SORT_KEYS"] = False   will not follow my desire output
```
 {
    "h": "test",
    "b": "test",
    "f": "test",
    "a": "test"
}
```

removing that it will sort ...
```
 {
    "a": "test",
    "b": "test",
    "f": "test",
    "h": "test"
}
```
i just want like JSON.stringify output ... preserving its order..

**Comment by davidism** [comment]
JSON objects and Python dicts are unordered. Alphabetical order is useful for caching. Any other order is not going to be implemented. Use Python 3.6 if you want a dict that is ordered as an implementation detail, but still don't rely on that order.
