### ISSUE TITLE
Investigate adding app and debug args back into the CLI

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2292]
The `-a myapp:app` and `--debug` flags were removed from the CLI and became environment variables instead. I'm not very clear on the reasons behind that, but at the time it was stated that Click could be fixed to support that again. Has Click been fixed? Let's try adding it back.

**Comment by davidism** [comment]
http://click.pocoo.org/6/commands/ seems to indicate it's still a supported pattern.

**Comment by clouds56** [comment]
+1 for `--app`.

Is there any link for why it was removed from cli?

**Comment by davidism** [comment]
That's what this it's is asking.

**Comment by davidism** [comment]
OK, dug around:

* Removed in #1820 
* Partially due to #1124, `--help` wouldn't pick up custom commands due to the order Click would execute things to load the `--app` option.
* Click issue, still open, pallets/click#590

This might only apply to `--app`, maybe `--debug` can be added back in?

**Comment by davidism** [comment]
From IRC:

```
<davidism> mitsuhiko am I right in saying that --debug can be added back to the cli but --app can't? https://github.com/pallets/flask/issues/2292
<mitsuhiko> davidism: right now i do not remember the details but i did not find a way to reconfigure click itself early enough based on parameters
<mitsuhiko> which means if --app is able to change the app then commands in click that would be available through the app might not be loaded in all situations
<mitsuhiko> --debug probably is fine if we are happy to flip the flag late
<mitsuhiko> eg: it would only be changed later when the server boots
<mitsuhiko> but it would have issues setting the initial value of debug
<davidism> Hmm, since the reloader and debbuger are enabled based on the debug flag, it's probably still safer to leave it as an env var until Click fixes things.
```

**Comment by davidism** [comment]
I've done more investigation, and have figured out how to implement `--app`, `--env`, `--debug/--no-debug`, and `--env-file` options. It turned out to be pretty straightforward to implement using parameter callbacks, once I better understood how Click's processing pipeline works.
