### ISSUE TITLE
Support for unregistering blueprints (or endpoints).

### ISSUE THREAD

**Issue by iptq** [pallets/flask#2308]
>The downside is that you cannot unregister a blueprint once an application was created without having to destroy the whole application object.

this statement appears in the [docs](http://flask.pocoo.org/docs/0.12/blueprints/), but is there a design reason behind this, or is it just because it hasn't been implemented yet? if it's not possible, what are alternatives for disabling an endpoint other than using some kind of variable to store whether an endpoint should be active?

**Comment by davidism** [comment]
The same reason you can't unregister anything else. You're meant to build up your app first, then run it. If you need to disable an enpoint while the app is running, checking flags is the only way. Modifying the app object is not thread safe.

**Comment by revmischa** [comment]
I'd like to unregister a blueprint an extension creates during testing

**Comment by ThiefMaster** [comment]
Then you should pass an argument to your app factory to avoid initializing the extension / registering the blueprint altogether.
