### ISSUE TITLE
Replace `modules_tmpdir` fixture with pytest's built-in `tmpdir` fixture

### ISSUE THREAD

**Issue by jeffwidman** [pallets/flask#2312]
I'm wondering if the [`modules_tmpdir` fixture](https://github.com/pallets/flask/blob/c8e56d58077d29e2c9478f133b3c69ba73deead5/tests/conftest.py#L68-L79), could be removed/replaced in the tests with `pytest`'s built-in [`tmpdir` fixture](https://docs.pytest.org/en/latest/tmpdir.html)? 

Not 100% confident this is possible/the right move, but it's worth investigating.

**Comment by RonnyPfannschmidt** [comment]
its based uppon it and adds extra behaviour

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pallets/flask/blob/master/tests/conftest.py#L68-L91 are pretty much layering behavior on top of it and its a good idea to give it a different name

**Comment by jeffwidman** [comment]
Agreed, I just missed that it was already using it.
