### ISSUE TITLE
Organize the gevent tests into a single class

### ISSUE THREAD

**Issue by jeffwidman** [pallets/flask#2313]
https://github.com/pallets/flask/blob/c8e56d58077d29e2c9478f133b3c69ba73deead5/tests/test_reqctx.py#L147-L196 could be organized into a single class specifically for tests about greenlets. 

This is cleaner because Pytest supports conditionally skipping the entire class if greenlets are missing rather than having to mark each test separately. And can trigger just that class of tests etc.

**Comment by RonnyPfannschmidt** [comment]
a potential alternative is to declare `greenlet_required = pytest.mark.skipif(greenlet is None, reason='greenlet is missing`

and use that decorator multiple times

**Comment by Tafkas** [comment]
I looked into it. Right now there are only two functions. Does this justify it to bundle them into a class? I would say, once there are three it makes sense.

**Comment by rzelayafavila** [comment]
Ok, I am tackling this, about to open a PR where I create a class with these two functions.

**Comment by rzelayafavila** [comment]
Submitted PR #2324 to address this.
