### ISSUE TITLE
Don't overwrite Vary header when setting for cookie access

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2317]
If the `Vary` header is already set, the current session code just adds another header line. What it should do is update the existing header by splitting, adding the new option to the set, joining, and setting the new value. See Django's [`patch_vary_headers`](https://github.com/django/django/blob/1ce04bcce0076360623ae164afd3541a5c031af2/django/contrib/sessions/middleware.py#L45).

Related to #2288

**Comment by davidism** [comment]
Current code is here: https://github.com/pallets/flask/blob/e2067649551033c74e7937b89af9a9874a96d279/flask/sessions.py#L408

**Comment by nnja** [comment]
I'll work on this during pycon sprints.
