### ISSUE TITLE
Docs theme not responsive

### ISSUE THREAD

**Issue by mixmastamyk** [pallets/flask#2327]
Hi,  I'm reading the docs and working on code at the same time with somewhat narrow windows.  
The Flask docs have a big sidebar on the left that is not always useful, and worse the body text has a fixed width that pushes it off the right side of the page.  Makes it very hard to read without constantly scrolling.

Doesn't fit in with old-school html wrapping or new responsive hotness.  Disabling:

```
div.document {
	/* width: 940px; */
}
```

with the dev tools fixed the width problem, responsive css could disable the sidebar when the window is narrow.  Cheers,

**Comment by mixmastamyk** [comment]
Just changed it to `max-width` instead and it is probably closer to what was intended.

**Comment by kennethreitz** [comment]
Switching to alabster or kr-theme would fix this.

**Comment by kennethreitz** [comment]
Closing for https://github.com/pallets/flask/issues/2336

**Comment by kennethreitz** [comment]
docs theme is now responsive (in the codebase, not online)
