### ISSUE TITLE
If FLASK_APP accept one argument and I do not send it, the default value is not correct, instead I get a ScriptInfo object.

### ISSUE THREAD

**Issue by jrbaez01** [pallets/flask#2341]
An example is in the Flickr app [link here](https://github.com/pallets/flask/blob/master/examples/flaskr/flaskr/factory.py#L19)

As a newcomer it is confusing when I follow the [README.md](https://github.com/pallets/flask/blob/master/examples/flaskr/README#L24), but the when running the app it results in the following error. 
![image](https://cloud.githubusercontent.com/assets/11146130/26524504/51b31274-4302-11e7-8dd6-21426b08bbbf.png)

**Comment by jrbaez01** [comment]
Hello @davidism, 

Suggested solution to this issue: https://github.com/pallets/flask/pull/2342, hope it is useful.

Cheer.

**Comment by davidism** [comment]
Closed by PR.
