### ISSUE TITLE
How to set connection read timeout and support flask run in multi-thread mode?

### ISSUE THREAD

**Issue by haolujun** [pallets/flask#2351]
Hi 
   When I use Flask as my web server, I meet a diffcult problem.
   Because of network problem, the flask server sometimes hang forever(The client build a connection to server and then died before send anything). And I found it hanged at socket read function. The server was started by  "app.run()" (The way you don't suggest to use) . So I readed the flask and werkzeug code and found werkzeug didn't set socket timeout default. So I must writed a class extends serving.WSGIRequestHandler and set the timeout = 0.5 and  made it as a parameter for "app.run()" , it worked well.

 But there was another problem, I couldn't run this server in multi-thread mode, because when I used flask commod to run this server, there was no way to set timeout, it didn't make "app.run()" as the  start point。

I also tried gunicorn and still couldn't find a way both set timeout and run server in muti-thread mode. 

what should I do ?

**Comment by ThiefMaster** [comment]
`app.run()` / `flask run` is using the dev server which is not suitable for production. Use a real webserver instead, e.g. gunicorn or nginx+uwsgi.

**Comment by haolujun** [comment]
Thanks。I found that gunicorn can set keep-alive and may solve my problem.

**Comment by prasanthv218** [comment]
Hi haolujun, how you attached wsgirequesthandler in app.run() parameter, need some code snippet. Thanks in advance
