### ISSUE TITLE
Wrong release version

### ISSUE THREAD

**Issue by simonsmiley** [pallets/flask#2355]
In the 0.12.2 release the version in `flask/__init__.py` is still 0.12.2-dev

This is causing problems with programs checking the flask version.

**Comment by davidism** [comment]
I can bump it, but what problems is it causing?

**Comment by simonsmiley** [comment]
It's causing problems with [onionshare](https://aur.archlinux.org/packages/onionshare) on archlinux.

It boils down to:
```
In [1]: from flask import __version__ as flask_version

In [2]: from distutils.version import StrictVersion

In [3]: StrictVersion(flask_version)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-5a786cd67f67> in <module>()
----> 1 StrictVersion(flask_version)

/usr/lib/python3.6/distutils/version.py in __init__(self, vstring)
     38     def __init__ (self, vstring=None):
     39         if vstring:
---> 40             self.parse(vstring)
     41 
     42     def __repr__ (self):

/usr/lib/python3.6/distutils/version.py in parse(self, vstring)
    135         match = self.version_re.match(vstring)
    136         if not match:
--> 137             raise ValueError("invalid version number '%s'" % vstring)
    138 
    139         (major, minor, patch, prerelease, prerelease_num) = \

ValueError: invalid version number '0.12.2-dev'
```

**Comment by davidism** [comment]
Flask 0.12.2, the released version, has `__version__ = '0.12.2'`, which is correct. Flask master, the dev version, has `__version__ = '0.13-dev'`, which is also correct. Flask has always used "-dev" for it's dev designator. The version scheme we use is [PEP 440](https://www.python.org/dev/peps/pep-0440/) compliant and has not changed format as far as I can remember.

It looks like while the onionshare AUR allows `python-flask-git` as an alternative to `python-flask`, it doesn't actually expect its version scheme. It should use `pkg_resources.parse_version` instead of `distutils.version.StrictVersion` (or at least `LooseVersion` if you don't want to depend on setuptools).

**Comment by simonsmiley** [comment]
The released version does not! bb83ae9
https://github.com/pallets/flask/blob/bb83ae9843fd1e170a97139d489399c4823ba779/flask/__init__.py

**Comment by simonsmiley** [comment]
at least not the archive generated in github. I didn't try pypi

**Comment by davidism** [comment]
That's weird, I'll check our release script. The only supported builds are on PyPI though, which do have the right versions.

**Comment by davidism** [comment]
Looks like I need to report a bug to the Arch package maintainer though. Funnily enough, I use Arch but have never had a reason to check its Flask package. I wonder if other distros have the same problem.

**Comment by davidism** [comment]
Reported to Arch here: https://bugs.archlinux.org/task/54288
Reported to onionshare here: https://github.com/micahflee/onionshare/issues/442

**Comment by simonsmiley** [comment]
I know for a fact that arch doesn't like using pypi to fetch python packages...
Either way I think github tags should be identical to the builds. There is no reason why this shouldn't be the case

**Comment by davidism** [comment]
Totally agree. Can't adjust the old ones, but we'll fix this for the next release.

**Comment by davidism** [comment]
We can possibly upload sdists on GitHub too.

**Comment by davidism** [comment]
OK, 0.12.2 sdist is uploaded to GitHub: https://github.com/pallets/flask/releases/download/0.12.2/Flask-0.12.2.tar.gz. These URLs should work for Arch. Should be able to use the GitHub API to upload these as part of the release process. https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by davidism** [comment]
The tag has been fixed. Arch needs to rebuild their package.
