### ISSUE TITLE
flask command should auto-detect module

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2376]
Even when installed as a package, it can be useful in complex situations to have a `wsgi.py` file for setting the app up to run. The `flask` command should detect this file if no `FLASK_APP` is specified at all.

Additionally, it's common to name quick demo apps `app.py`, so that should be detected too.

From discussion in #2375.

**Comment by ThiefMaster** [comment]
is `wsgi.py` even a common name? when using it in a wsgi container i think it's more common to name it `something.wsgi` (after all, it's not referenced as a python module but rather using a fileystem path)

**Comment by davidism** [comment]
The problem is that `something` is not standard, so there's no way to autodetect it. One strategy could be to also support importing `something.wsgi` if `something` is specified before trying `create_app`.

**Comment by miguelgrinberg** [comment]
Django defines the application in a `wsgi.py` module.
