### ISSUE TITLE
Odd behavior with send_from_directory

### ISSUE THREAD

**Issue by vmp32k** [pallets/flask#2379]
I wrote some code for on-demand thumbnail generation but ran in to some weirdness with `send_from_directory`:

```py

# Just a relative directory called "thumbs" that's supposed to hold a replica directory tree, only with thumbnails
thumbcache = 'thumbs'

# ...

@app.route('/thumb/<path:path>')
def thumbnail(path):
    
    # Simple True/False return for success/failure.
    success = cache_thumbnail(path)
    if not success:
        raise Exception("Thumbnail generation failed!")

    # All thumbnails are jpg so I need to replace the file extension:
    thumbpath, _ = os.path.splitext(path)
    thumbpath += ".jpg"

    ## thumbpath = thumbpath.replace('\\', '/')

    #return send_file(thumbcache + '/' + thumbpath)
    return send_from_directory(thumbcache, thumbpath)
```

The `'/thumb/<path:path>` URL is being generated by: 
```html
<img id="{{loop.index}}" src="{{ url_for('thumbnail', path=file) }}">
```

The requests look like: `"GET /thumb/gw%5Calpha%5C1430f690aa3fcfda5c10beceb9c120ea.jpg HTTP/1.1"`

### Actual Behavior

The code above, as is, results in a 404 - File not found error. No exception.

### Expected Behavior

The file should be served.

If I uncomment the line `return send_file(thumbcache + '/' + thumbpath)` and thereby bypassing any security, it works but that's an undesirable workaround.

If I uncomment the line `thumbpath = thumbpath.replace('\\', '/')` to replace all backslashes with forward slashes, it works fine.  
I don't know why `url_for` generated backslashes in the first place. Maybe an artifact because I am running this code on a Windows machine?

### Environment

* Python version: Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
* Flask version: 0.12.2
* Werkzeug version: 0.12.2

**Comment by davidism** [comment]
What is `file` in `url_for(path=file)`? What is `print(path)` in `thumbnail`?

**Comment by vmp32k** [comment]
Aw dang, that pointed me in the right direction.  
The array I'm iterating over in the template indeed uses backslashes! I'm surprised the browser didn't complain since I use it for links and img-src's, all of which worked!

My picture paths have backslashes in them (thanks windows), `url_for` correctly encodes them and trips up `send_from_directory`. I'm guessing this is expected behavior for my less-than-standard input. Closing.

I've been spending too many hours looking at this and still didn't see it. I feel silly now. :)

**Comment by dhinkris** [comment]
any luck on this issue? I am trying to send a video file as a response. I am getting binary data in my frontend.
