### ISSUE TITLE
Problem with partial video content: send_from_directory() + x-sendfile + mod_wsgi

### ISSUE THREAD

**Issue by xplwowi** [pallets/flask#2384]
I found that using send_file() to serve video (mp4) files works fine but the same content is not served using send_from_directory(). Only small parts (hundreds of bytes) are delivered to browser.
On Firefox video embedded through \<video\> tags is playable in most cases but opened directly from address bar not. On Chrome both methods are not working.

With x-sendfile switched off, send_from_directory() works ok.

Tested on:
Debian: python 3.5.3, flask  0.12.2, apache 2.4.25, mod_wsgi 4.5.11
Ubuntu: python 3.5.2, flask 0.12.2, apache 2.4.18, mod_wsgi 4.3.0

**Comment by davidism** [comment]
I can unreliably reproduce this. Firefox or Chrome, page or direct viewing, sometimes the page will just hang getting a bunch of 206 responses. Other times it will work fine. Once it works, it seems to keep working until the cache is cleared.

However, I have no idea who's fault it is. If you pass `conditional=False` to `send_from_directory`, it works reliably. But that doesn't seem ideal. And the responses look fine (although I'm not completely sure what I'm looking for). So is it the browser thinking it needs to load more data? Is it xsendfile not handling range requests correctly? I don't know.

**Comment by davidism** [comment]
I'm going to guess that since range requests work when serving with Flask directly, it's probably not Flask at fault.
