### ISSUE TITLE
Flask app doesn't run when importing Python-Markdown module

### ISSUE THREAD

**Issue by ahota** [pallets/flask#2387]
### Expected Behavior

Import the Python-Markdown module and run the Flask app

```python
# flask_test.py
from flask import Flask
import markdown

app = Flask(__name__)

@app.route('/')
def index():
    return 'Hello, world!'
```

### Actual Behavior

```shell
export FLASK_APP=flask_test.py
flask run

Usage: flask-script.py run [OPTIONS]

Error: The file/path provided (flask_test) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py
```

If I simply comment out the `import markdown` line, the app launches/works just fine.

### Environment

* Python version: 2.7.12
* Flask version: 0.12
* Werkzeug version: 0.11.2
* Python-Markdown version: 2.6.8

I'm running on Windows 10 using Git Bash (mintty), which lets me use `export` instead of `set` for `FLASK_APP`. However I found that `set` doesn't change the outcome.

**Comment by mohamed-aziz** [comment]
This doesn't seem to be an issue related to Flask, maybe make sure that you are in the right directory?

**Comment by lepture** [comment]
Not related to Flask, try to ask on stackoverflow.

**Comment by kblomqvist** [comment]
Install the latest master instead of the latest release and you will get an error, which tells you what you did wrong.

**Comment by RonnyPfannschmidt** [comment]
@kblomqvist did you `export PYTHONPATH=.`

**Comment by RonnyPfannschmidt** [comment]
my mistake, in the most recent version its not needed anymore, sorry

**Comment by kblomqvist** [comment]
Nope. I just know that the current release masks the import error with the one given above.

**Comment by RonnyPfannschmidt** [comment]
@kblomqvist i just made a new virtualenv on fedra, installed markdown and flask and created the file, i see no issue running your script


```
$ pip install flask markdown
Collecting flask
  Using cached Flask-0.12.2-py2.py3-none-any.whl
Collecting markdown
  Downloading Markdown-2.6.8.tar.gz (307kB)
    100% |████████████████████████████████| 317kB 1.2MB/s 
Collecting itsdangerous>=0.21 (from flask)
Collecting Jinja2>=2.4 (from flask)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from flask)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting click>=2.0 (from flask)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->flask)
Building wheels for collected packages: markdown
  Running setup.py bdist_wheel for markdown ... done
  Stored in directory: /home/rpfannsc/.cache/pip/wheels/85/a7/08/33ee5cd488d0365d8bed79d1d4e5c28dd3fbfc7f6d0ad4bb09
Successfully built markdown
Installing collected packages: itsdangerous, MarkupSafe, Jinja2, Werkzeug, click, flask, markdown
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 Werkzeug-0.12.2 click-6.7 flask-0.12.2 itsdangerous-0.24 markdown-2.6.8
```

```
$ cat flask_test.py
# flask_test.py
from flask import Flask
import markdown

app = Flask(__name__)

@app.route('/')
def index():
    return 'Hello, world!'
```

```
$ flask run
 * Serving Flask app "flask_test"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

**Comment by RonnyPfannschmidt** [comment]
i suspect it could be a platform issue on windows - someone with a similar box has to take a look

**Comment by RonnyPfannschmidt** [comment]
@kblomqvist does it happen without any extra imports as well?

**Comment by ahota** [comment]
Actually, it looks like I was a little too sleepy last night. Turns out I was actually running Flask 0.10. Upgrading seems to have made the problem go away. I haven't tried running from the latest master as @kblomqvist suggested.

**Comment by RonnyPfannschmidt** [comment]
very well, closing as invalid then
