### ISSUE TITLE
Flaskr fails being run from cli

### ISSUE THREAD

**Issue by JervisTetch** [pallets/flask#2389]
### Expected Behavior

According to this [README](https://github.com/pallets/flask/blob/master/examples/flaskr/README) the Flaskr example application should run after doing following:

`pip install --editable .`
`flask initdb`
`export FLASK_APP=flaskr.factory:create_app()`

### Actual Behavior

Flaskr fails running throwing a NoAppException.

```pytb
NoAppException: The file/path provided (flaskr.factory) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py
```

### Environment

* Python version: 2.7
* Flask version: 0.12.2
* Werkzeug version: 0.12.2

**Comment by JervisTetch** [comment]
Can anyone reproduce this or is it me? I was looking for a way to run my own application (also using an app factory) and stumbled over the Flaskr example which doesn't work for me either. Is the way of running an app like described in the linked README still valid?

**Comment by davidism** [comment]
You have to export FLASK_APP before running flask.

**Comment by JervisTetch** [comment]
Oh sorry that was just wrongly pasted. I did the import before running the flask command - so basically I tried this:

`pip install --editable .`
`export FLASK_APP=flaskr.factory:create_app()`
`flask initdb`
`flask run`

the last two commands both fail.

**Comment by GillesP** [comment]
Hello,

I have the same issue:
$ pip install --editable .
... Successfully installed Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 flask-0.12.2 flaskr itsdangerous-0.24
$ export FLASK_APP="flaskr.factory:create_app()"
$ flask initdb
```
Usage: flask [OPTIONS] COMMAND [ARGS]...

Error: No such command "initdb".
```

$ flask run
Usage: flask run [OPTIONS]

Error: The file/path provided (flaskr.factory) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py


The file factory.py was not modified from the original version provided
`-rw-r--r-- 1 gilles gilles 1572 janv. 25 19:47 flaskr/factory.py`

Tell me if you can help/need more information ! Thanks in advance.

**Comment by davidism** [comment]
Look at the output from pip. You installed flaskr from source, but that pulled in Flask 0.12 from PyPI. You need to install Flask from source too. Duplicate of #2413
