### ISSUE TITLE
render_template_string() recompiles the template every time

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [pallets/flask#2402]
When `flask.render_template_string()` is invoked with the same template string multiple times, it still compiles it on every invocation. This makes it pretty much unusable in any application where performance is of any concern.

As a dirty workaround, I use memoized version.
It only makes sense if template strings are not generated dynamically, but that sounds like a reasonable assumption.

```python
import flask.globals
import flask.templating

_compiled_templates = {}

def memoized_render_template_string(source, **context):
    """Same as flask.render_template_string(), but does not recompile.

    No cache expiration.
    Assumes that Jinja environment configuration does not change at runtime.
    """
    ctx = flask.globals._app_ctx_stack.top
    ctx.app.update_template_context(context)
    jinja_env = ctx.app.jinja_env
    k = jinja_env, source
    if k in _compiled_templates:
        template = _compiled_templates[k]
    else:
        template = _compiled_templates[k] = jinja_env.from_string(source)
    return flask.templating._render(template, context, ctx.app)
```

Perhaps this problem should be addressed in the actual implementation of `render_template_string()`?
I'm not sure what would be the proper way to do it, though.

**Comment by ThiefMaster** [comment]
For what are you using it so much that the performance difference really matters?

**Comment by davidism** [comment]
If you need to cache the results, you should implement that yourself. Note that a global like you're using will not perform much better in production environments, where there are multiple worker processes spawning and dying independent of each other. Use memcached, redis, or something else external. Werkzeug has cache implementations and Flask-Caching provides some too.

**Comment by Vlad-Shcherbina** [comment]
@ThiefMaster , I use it in helper functions and template filters that render small UI elements.
For example, a date that is a hyperlink to timeanddate.

I observed that even for fairly simple templates compilation times are in milliseconds.
Put a hundred of such elements on a page and the app is sluggish.

**Comment by davidism** [comment]
A better strategy would be to use loaded templates, so that they get cached using Jinja's internal cache.

**Comment by ThiefMaster** [comment]
Sounds like you should put them in an actual template file and create a jinja module from it if you want to execute it from non-template Python code.

**Comment by Vlad-Shcherbina** [comment]
These are valid approaches. They offer good performance, but have some minor drawbacks (perhaps, subjective).

Dedicated template files hurt readability through unnecessary indirection (many of my templates are one or two lines).

Template file with a collection of macros is ok as long as rendering doesn't require any actual python code, otherwise code locality suffers again.

I was convinced that `render_template_string` is a perfect fit, designed specifically for my scenario, until I discovered that it's slow. Out of curiosity, what are legitimate uses for `render_template_string` then? (Does it have any?)

**Comment by davidism** [comment]
There are other loaders besides the filesystem. You can probably use something in http://jinja.pocoo.org/docs/dev/api/#loaders or implement your own loader to get caching with strings. I think the key is that the template has some associated metadata to build a cache key.

As I said though, if you need caching that's something you need to implement based on your application's requirements and setup.

**Comment by jpassaro** [comment]
> what are legitimate uses for `render_template_string`

For me, mostly just poking around for debug purposes.

If keeping small templates is truly cumbersome, you could use one of the caches @davidism mentioned as implemented in werkzeug (e.g. memcached, redis): create a function that checks the database cache for some string identifier and the template parameters, if present then use that, otherwise use `render_template_string` to generate and store to that cache.

The string identifier could, if truly short enough, just be the string itself, or a sha1 or something. On the other hand, you could store as class docstrings and use the class name as an identifier [[gist](https://gist.github.com/jpassaro/6b0942c2affc63084b3328466ca3e2a4)].
