### ISSUE TITLE
datetime json encoding is one sided: Fix for JSONDecoder is needed

### ISSUE THREAD

**Issue by aop** [pallets/flask#2404]
### Expected Behavior

When using Flask json to encode, datetime is encoded to a string and it would be expected that the reverse operation also works.

```python
>>> import datetime
>>> from flask import json
>>> json.dumps({'a': datetime.datetime.utcnow()})
'{"a": "Mon, 03 Jul 2017 09:13:33 GMT"}'
>>> json.loads(json.dumps({'a': datetime.datetime.utcnow()}))
{'a': 'Mon, 03 Jul 2017 09:13:42 GMT'}
```
Expected would be
```python
>>> json.loads(json.dumps({'a': datetime.datetime.utcnow()}))
{'a': datetime.datetime(2017, 7, 3, 9, 13, 42, 564641)}
```

### Environment

* Python version: 3.6.0
* Flask version: 0.12
* Werkzeug version: 0.11.15

**Comment by ThiefMaster** [comment]
That's not possible, since there is no way of knowing whether it should be just a string or a datetime object. Use a custom json decoder if you want this behavior.
