### ISSUE TITLE
Flask CLI doesn't support application context in argument callbacks

### ISSUE THREAD

**Issue by runfalk** [pallets/flask#2410]
I recently converted an old managing script to use Flask's built in CLI instead. I have a table for clients that are identified using a shortname/slug. I thought about using Click's argument callback for this. Given a shortname my function would get an instance of the client from my ORM. The problem is that the application context is not active when the callback is run.

### Expected Behavior

Since many scripts will rely on a database connection it makes sense to have the application context be available in arguments.

```python
import click
from flask import current_app, Flask

app = Flask("demo")

def example_callback(ctx, param, value):
    # Access the application context to trigger an exception
    click.echo(current_app.config)
    return {"id": 1, "shortname": value}

@app.cli.command()
@click.argument("arg", callback=example_callback)
def view(arg):
    click.echo(arg)
```

I run this using `flask view foobar`.

### Actual Behavior

```pytb
Traceback (most recent call last):
  File "/dev/flask-cli-demo/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/dev/flask-cli-demo/app.py", line 8, in example_callback
    click.echo(current_app.config)
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/dev/flask-cli-demo/venv/local/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
```

### Environment
```
click==6.7
Flask==0.12.2
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
pkg-resources==0.0.0
Werkzeug==0.12.2
```

### Workaround
The only workaround I've found is doing the same thing `@with_appcontext` does which is:

```python
with ctx.ensure_object(ScriptInfo).load_app().app_context():
```

Using `@with_appcontext` on `example_callback` doesn't work since that gives a warning about using a deprecated function signature (from before Click 2.0).

### Why is this a problem?
This results in two separate instantiations of my ORM. Some ORM's (like the one I'm using) doesn't allow sharing objects across instances (for good reason) which makes the client object I produce unusable anyway.

**Comment by homeworkprod** [comment]
I've run into the issue of the app context not being available to argument callbacks as well.

Specific example: Pass a user name as command line argument, than have the argument callback function look it up in the database and return the entity to work with it in the command's implementation.

Considering that Click was designed long after Flask existed (and both by the same author), and is now required by the latter, my personal experience with attempting to port CLI scripts/commands (built with Flask-Script or not) over to the `flask` command in the last few *years* has been, surprisingly, *extremely* frustrating.

Examples seem to be quite scarce, distributed, specific, limited, and in need of more consistency (e.g. regarding filenames for app factories and CLI command files). I can't even remember to have seen an example or other piece of code that uses both `app.cli` and `click.argument` on the same function; at least not in the official docs, the "Flaskr" example app, and Flask's source code.

Also it seems to me that it's not really possible to define commands in separate modules (i.e. ones that don't have access to the readily-created app instance; this has been solved with blueprints for another use case) without wrapping their function definitions in another function that gets passed and app argument to call `app.cli.command()` on.

After the annoying delay until improved shells like iPython could be used in `flask shell` (pointer for anyone looking for that: check out the `flask-shell-ipython` package and similar ones) and `.flaskenv` being on the horizon with v0.13, I'm really looking forward to the remaining holes in Flask's CLI system getting (discovered and) fixed.

(End of long-accumulated, partially off-topic rant.)

So yeah, please let's come up with a reasonable way to provide the app context to argument (and option) callbacks.

**Comment by runfalk** [comment]
Thank you for getting back to this issue after all this time.

In my example I explicitly didn't use a click group as you noted. Would there be a way to support this without groups or are groups required for this workaround. I'm not sure which project I wanted this for, so I can't say whether it matters or not :shrug:.

**Comment by davidism** [comment]
If you're willing to sacrifice lazy loading, you can assign a callback function to the top-level group that is the `flask` command.

```python
import click
from flask.cli import cli

@click.pass_context
def push_app_ctx(ctx):
    ctx.call_on_close(ctx.obj.load_app().app_context().push().pop)

cli.callback = push_app_ctx
```

Or create your own `FlaskGroup` and use an entry point to make it executable (this also affects lazy loading). Based on the way loading works for the `flask` command, I don't think it's possible to have the `app.cli.callback` invoked.

**Comment by runfalk** [comment]
Ok, thanks!

**Comment by davidism** [comment]
After looking into this more, I've figured out how to modify `FlaskGroup` so that an app context is always active before `app.cli` commands are invoked, including for parameters, so `@with_appcontext` will no longer be required in most cases.

**Comment by davidism** [comment]
After looking into this more, I've figured out how to modify `FlaskGroup` so that an app context is always active before `app.cli` commands are invoked, including for parameters, so `@with_appcontext` will no longer be required in most cases.
