### ISSUE TITLE
404 error when using debug=True

### ISSUE THREAD

**Issue by jodhi** [pallets/flask#2415]
I created simple script using flask, it run smoothly, but when using `app.run(debug=True)` it returns 404 error
Run with:
`export FLASK_APP=main.py`

`flask run`

```python
from flask import Flask,request
app = Flask(__name__)
app.run(debug=True)
@app.route('/')
def hello_world():
    return 'hellow'
```

It return 404 error

```pytb
127.0.0.1 - - [15/Jul/2017 16:41:56] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [15/Jul/2017 16:43:03] "GET /favicon.ico HTTP/1.1" 404 -

```

### Environment

* Python version: 3.5.3
* Flask version: 0.12.2
* Werkzeug version: 0.12.1

**Comment by davidism** [comment]
You need to call `app.run` last, as it blocks execution of anything after it until the server is killed. Preferably, use the `flask run` command instead.

**Comment by DanishKhajuria** [comment]
i have the same issue and im using `flask run`
