### ISSUE TITLE
TCP port 5000 blocked by corporate firewalls

### ISSUE THREAD

**Issue by hex-m** [pallets/flask#2431]
Using TCP/5000 as the default port for flask may be a bad choice. I just had to debug a problem where I wasn't able to reach my service from outside of my network because the firewall (and I assume many firewalls do this) blocks incoming requests on port 5000.

This port is used for universal plug-and-play (UPNP) and it's considered a security problem if it's reachable from the internet says [source1](http://www.linklogger.com/TCP5000.htm) and [source2](https://www.grc.com/port_5000.htm).

I therefore suggest to change the default port or mention this possible problem in the [documentation](http://flask.pocoo.org/docs/dev/quickstart/#public-server) so others don't have to search for this problem as long as I did.

**Comment by ThiefMaster** [comment]
The dev server is only for development, usually on localhost - so no corporate firewall will be between you and the app.

If you use Flask in production you should use a real WSGI server behind a real webserver (running in port 80/443).
