### ISSUE TITLE
Execute/debug flask CLI from IDE

### ISSUE THREAD

**Issue by fgblomqvist** [pallets/flask#2435]
How does one debug flask CLI commands from an IDE?
E.g. if I want to debug the `flask run` command, or even more importantly my custom commands (in my case, `flask initdb`).

Do I have to manually create a separate script file that executes the functions that I want to debug?

**Comment by davidism** [comment]
At least in PyCharm, you can create a run configuration for the Flask command, just like you would for a normal Python script. Presumably you can do that in any other debugger. Then you set breakpoints like normal.

Click also has facilities for calling commands programmatically, if you do want to write a separate script. http://click.pocoo.org/dev/testing/
