### ISSUE TITLE
web: URL to PDF on home doesn't work

### ISSUE THREAD

**Issue by plavcik** [pallets/flask#2441]
URL to download documentation in PDF on http://flask.pocoo.org/

http://flask.pocoo.org/docs/0.12/.latex/Flask.pdf

returns

Chapter 404: The Lost Page
A careful and diligent search has been made for the desired page, but it just cannot be found.
And so they returned to familiar waters.

**Comment by davidism** [comment]
Already reported to doc builder repo.
