### ISSUE TITLE
While streaming back long responses, Flask loses encodings or alters the stream

### ISSUE THREAD

**Issue by priyaananthasankar** [pallets/flask#2444]
I have a large response in the order of 2MB. I generate it in my Python code and send it back using jsonify(resp) and the server cut short the response and delivered partial response. - Issue 1

to overcome this issue I streamed the response into a file and exposed a GET api using send_from_directory(absolute_file_path, filename) - it sends back the file but has compressed some items like byte streams inside! 

Please find attached an example of this file.
[train_response.zip](https://github.com/pallets/flask/files/1209855/train_response.zip)

**Comment by priyaananthasankar** [comment]
It worked perfectly fine in a docker container based off python35 but fails when I deploy it on cloud. Does OS or anything affect the streamed response of a file? I use send_from_directory. Other people reported similar issues here: see this stackoverflow. https://stackoverflow.com/questions/43483925/nginx-cuts-off-static-files-downloads-early

**Comment by davidism** [comment]
This sounds like an issue with the web server configuration, not Flask.

**Comment by priyaananthasankar** [comment]
There is no web server. I am directly responding through Flask.

**Comment by davidism** [comment]
Don't use the development server in production. Also, we have no idea what configuration is between docker and the internet on "the cloud".
