### ISSUE TITLE
Changing SESSION_COOKIE_NAME invalidates session cookies earlier than permanent_session_lifetime

### ISSUE THREAD

**Issue by Ginkoid** [pallets/flask#2448]
### Expected Behavior
Normally, if you want a permanent cookie, you can set
```python
session.permanent = True
app.permanent_session_lifetime = datetime.timedelta(weeks=156)  # 3 years
```
However, if you also change `SESSION_COOKIE_NAME` in app.config to something else, this should only change the name of the cookie, however, it also makes the session cookies invalidate after a browser session, not the `permanent_session_lifetime`.

Demo:
```python
import datetime
from flask import Flask, session

app = Flask(__name__)
app.secret_key = 'super_secret'

@app.before_request
def settings():
    app.config['PERMANENT_SESSION_LIFETIME'] = datetime.timedelta(weeks=156)  # 3 years
    # app.config['SESSION_COOKIE_NAME'] = 'other_name'

@app.route('/')
def index():
    if 'test' in session:
        return 'You have a cookie'
    return 'You do not have a cookie'
    
@app.route('/get_cookie')
def get_cookie():
    session['test'] = 'testcookie'
    return 'Cookie sent'

app.run()
```

### Actual Behavior

If you run the above script, and visit `/get_cookie`, then visit `/`, notice that it works as expected. You can also close and reopen the browser, and the cookie stays, as expected, because of the `permanent_session_lifetime`.

However, if you uncomment the bit that sets the `SESSION_COOKIE_NAME`, then re-run the script, and follow the above steps again (including reopening the browser), you will notice that the session is invalidated upon reopening the browser.

### Environment

* Python version: 3.5.2
* Flask version: 0.12.2
* Werkzeug version: 0.12.2

**Comment by untitaker** [comment]
If you change that setting, Flask won't use the old cookie anymore. How could it? It can't know what it was called. This is expected behavior. Don't change the setting halfway through and expect everything to still work.

**Comment by untitaker** [comment]
Also don't modify your config in a request handler...

**Comment by Ginkoid** [comment]
Please test this fully.

I am not expecting flask to recognise a cookie that it doesn't know the name of.
I tested this the exact same way both times, and the cookie name **does** make the cookie be invalidated after the browser restarts.

**Comment by ThiefMaster** [comment]
You are not supposed to change ANYTHING in `app.config` during requests (it wouldn't work nicely with more than one process for example).

Does it work fine when you set the cookie name earlier? Without checking the code (so I may be wrong): `before_request` is probably too late to change anything related to the session config.

**Comment by Ginkoid** [comment]
Seems like that was it...oops

**Comment by untitaker** [comment]
@Ginkoid I see, sorry I misread your report. Still the advice from @ThiefMaster probably applies.
