### ISSUE TITLE
Feature request : Highlight 'user code' in traceback interpreter output

### ISSUE THREAD

**Issue by elliotwoods** [pallets/flask#2452]
### Expected Behavior

In debug mode, a very helpful call trace page comes up when an exception is thrown. Thanks for that!

A quick improvement would be to highlight the blocks which represent user's code. I believe this would give a decent speed boost when recognizing where errors come from. I think this could be as simple as giving a light red-tint on any code boxes which comes from the file defined in the FLASK_APP variable.

This would be unobtrusive, and would help speed up use for many users.

e.g. we could highlight this line:

![image](https://user-images.githubusercontent.com/328294/29567073-ffdc8b52-8743-11e7-95fd-be26eb6c93be.png)

Alternatively, the call trace could automatically collapse the 'app runner' code which the user is likely uninterested in.

Apologies if this place is for bugs only (not features)

**Comment by ThiefMaster** [comment]
FLASK_APP rarely points to just a single file, so this would require to consider the whole package containing whatever FLASK_APP points to as user code.

However, the debugger is part of Werkzeug which does not even know about flask or FLASK_APP.

**Comment by elliotwoods** [comment]
A better example screenshot :
![image](https://user-images.githubusercontent.com/328294/29567360-dc31f9ca-8744-11e7-8b98-1754499be179.png)

**Comment by elliotwoods** [comment]
OK. I presumed it wouldn't be trivial considering that flask is so far developed. Anyway, seems like this isn't the place to discuss/consider whether a feature is useful. Apologies for distraction

**Comment by ThiefMaster** [comment]
Feature requests do belong into the issue tracker - it's just that this would be better suited in pallets/werkzeug instead of pallets/flask
