### ISSUE TITLE
The link for downloadable PDF documentation is not working

### ISSUE THREAD

**Issue by Itisfilipe** [pallets/flask#2455]
I have tried to download the documentation in PDF from the official site (http://flask.pocoo.org/) and the link there (http://flask.pocoo.org/docs/0.12/.latex/Flask.pdf) is returning error 404.

**Comment by jacquerie** [comment]
Duplicate of https://github.com/pallets/flask-docs/issues/3, and several others in this repo: https://github.com/pallets/flask/search?q=PDF&type=Issues&utf8=%E2%9C%93
