### ISSUE TITLE
The request method to another website in views function didn't run correctly

### ISSUE THREAD

**Issue by peakhell** [pallets/flask#2456]
### Unexpected Behavior

   I have a simple function to get json data from a website using "POST" method, for convenience, I save it as get_music.py file. Here is the code.
   ```python
import requests
def get_music():
    baseUrl = "http://music.163.com/api/search/get/"
    parameters = {
        's': "acg",
        'limit': 100,
        'type': 1
    }
    response = requests.post(baseUrl, data=parameters)
    answer = response.json()
    return answer
```
and when we call the function, a json data will returned, that's no problems. But when i call it in the views function, things become strange. here is views.py.
```python
from .get_music import get_music
from flask import render_template
from . import main

@main.route('/', methods=['GET', 'POST'])
def index():
    music = get_music()
    return render_template("index.html", music=music)
```
  When I run the flask program, the json data is " {'msg': "Request method 'GET' not supported", 'code': 400}", it's not correct. 
  After debug i found the request method is "GET" when i use flask, but if  run the get_music.py without flask , the request method is "POST". it's any problem in views funtion change the request method?

**Comment by Caratpine** [comment]
I use your usecase, it did not raise error. Can you show me additional messages?
我运行你的代码，没有抛错误，还有额外的信息吗？

**Comment by RonnyPfannschmidt** [comment]
unless you trigger the import of your views in your app, the views will be unknown,

since there isn't enough data supplied to understand whats happening its presumably a user error

**Comment by peakhell** [comment]
@Caratpine  As you say, I run my code in another computer, it runs well, So I think there might be a problem with my computer's flask configuration.
   What's more, i find something interesting in my problem, the request url is "http://music.163.com/api/search/get/", but when i run it in my flask program, it changes to "https://music.163.com/api/search/get/".
![](https://raw.githubusercontent.com/peakhell/picture/master/problem.png)
