### ISSUE TITLE
Error: The file/path provided (server) does not appear to exist.  Please verify the path is correct. 

### ISSUE THREAD

**Issue by BorisVerk** [pallets/flask#2473]
### Expected Behavior

When I `import some_package_that_doesnt_exist` I should get `ImportError: No module named 'some_package_that_doesnt_exist'`, but something is swallowing the `ImportError` and assuming it means I mistyped the filename of my server code.

```python
from flask import Flask
app = Flask(__name__)

import aoeu
```

what happens

```bash
$ export FLASK_APP='flask_error_demonstration.py'
$ flask run
Usage: flask run [OPTIONS]

Error: The file/path provided (flask_error_demonstration) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py
```

what should happen

```bash
$ export FLASK_APP='flask_error_demonstration.py'
$ flask run
ImportError: No module named 'aoeu'
```

* Python version: 3.5.3
* Flask version: 0.12.2

**Comment by davidism** [comment]
This is fixed in master. Please try it out there and report back if it doesn't work.
