### ISSUE TITLE
stop travis irc notifications from forks

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2481]
See https://github.com/travis-ci/travis-ci/issues/1094#issuecomment-215019909 and 
https://github.com/mozilla/build-tools/commit/c13a297. Using a secure value for the IRC channel prevents notifications from forks.

**Comment by davidism** [comment]
Maybe I should just remove IRC notifications. Does anyone use them instead of looking at Travis anyway?

**Comment by lepture** [comment]
Just remove it.

**Comment by davidism** [comment]
Yeah, I'm going to remove them from all Pallets projects. If Travis continues to post we can always block it.
