### ISSUE TITLE
 "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.

### ISSUE THREAD

**Issue by balaraju1278** [pallets/flask#2488]
I working from i didn't face any issues but now i'm getting issues when i am submitting form data like this  "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.

**Comment by ThiefMaster** [comment]
Clearly that means you should update references to flask_wtf.Form to flask_wtf.FlaskForm. Also, this is not a Flask issue but a Flask-WTF issue.
