### ISSUE TITLE
Support "immutable" Cache-Control extension

### ISSUE THREAD

**Issue by mfr-itr** [pallets/flask#2497]
https://bitsup.blogspot.fr/2016/05/cache-control-immutable.html

It would mean adding the `immutable` attribute to [ResponseCacheControl](http://werkzeug.pocoo.org/docs/0.12/datastructures/#werkzeug.datastructures.ResponseCacheControl) (default to False).

**Comment by davidism** [comment]
Please report this against Werkzeug.
