### ISSUE TITLE
WAV files cannot play in Safari

### ISSUE THREAD

**Issue by evanmiltenburg** [pallets/flask#2503]
### Expected Behavior

I'm trying to embed an audio player in my Flask website. Here's the relevant part of my `index.html`:

    <audio controls>
    <source src="/static/{{audio_file}}" type="audio/wav">
    Your browser does not support the audio element.
    </audio>

This works well in Firefox, but not in Safari.

### Actual Behavior

- Safari does show the audio controls, but the audio doesn't load.  
- I can download the file in Safari if I right-click the audio player.
- 'Open audio in new window' gives me a window with the 'play' button with a line struck through, indicating that Safari cannot play the file.

What's frustrating is that *the exact same HTML* (replacing `{{audio_file}}` with the actual filename) does work in Safari when I'm not using Flask (i.e. just opening static html in Safari). So something inside Flask keeps the audio from working.

I just tried a different file type (mp3, using `house_lo.mp3` copied from the pygame examples), and that works fine in Safari. So the problem only occurs when using `.wav` files. mp3 could solve the problem for me (just convert everything), but it's not ideal.

    <audio controls>
    <source src="/static/house_lo.mp3" type="audio/mp3">
    Your browser does not support the audio element.
    </audio>

### Environment

* Python version: 3.6.1 , Anaconda, OS X Sierra
* Flask version: 0.12
* Werkzeug version: 0.11.15

I've posted this issue on [StackOverflow](https://stackoverflow.com/questions/46914468/how-to-make-embedded-wav-audio-work-in-safari-using-flask) as well.

**Comment by italomaia** [comment]
Can you provide a demo, showing the problem?

**Comment by evanmiltenburg** [comment]
Sure, here's a minimal Flask example: [flask-issue.zip](https://github.com/pallets/flask/files/1424691/flask-issue.zip)

Works in Firefox, doesn't work in Safari.

**Comment by karlcow** [comment]
I tested your mini app in both Firefox and Safari and it's working without issues.
`Server: Werkzeug/0.12.2 Python/2.7.10`


Firefox

```
127.0.0.1 - - [01/Nov/2017 15:27:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Nov/2017 15:27:21] "GET /static/cello.wav HTTP/1.1" 200 -
```

Safari does something slightly different but it's working too.

```
127.0.0.1 - - [01/Nov/2017 15:29:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Nov/2017 15:29:02] "GET /static/cello.wav HTTP/1.1" 206 -
127.0.0.1 - - [01/Nov/2017 15:29:02] "GET /static/cello.wav HTTP/1.1" 200 -
```

206 is partial content. It means that safari didn't request the full resource but just a couple of bytes  to identify the resource. In this case `Range: bytes=0-1`
And your server needs to reply with `Content-Range: bytes 0-1/811826`


You are using werkzeug 0.11.15 which has been released on  Dec 31, 2016
On september 2016 range request have been implemented so it should be working.

@evanmiltenburg What is the http response from your flask application when using Safari?

**Comment by evanmiltenburg** [comment]
HTTP response:

```
127.0.0.1 - - [01/Nov/2017 09:46:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Nov/2017 09:46:01] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [01/Nov/2017 09:46:01] "GET /static/cello.wav HTTP/1.1" 200 -
```

So I don't get the 206 request in Safari (Version 11.0.1 (12604.3.5.1.1)). 
And, of course, the playback functionality doesn't work.

**Comment by ThiefMaster** [comment]
Does it work with a real webserver? Could it be that there is more than one connection? The flask/werkzeug dev server is single-threaded by default and thus does not process more than one request at a time.

**Comment by evanmiltenburg** [comment]
> Does it work with a real webserver? 

I wouldn't know how to test this right now.

> Could it be that there is more than one connection? The flask/werkzeug dev server is single-threaded by default and thus does not process more than one request at a time.

I don't think so. I'm only running this app, with a single browser accessing it. And it does work with `.mp3` files.

**Comment by ThiefMaster** [comment]
You should. Running uwsgi in http mode or gunicorn is pretty easy. Like this you can know for sure that your problem is caused by the dev server. Also, try `--with-threads` in `flask run` to run it in multithreaded mode.

**Comment by evanmiltenburg** [comment]
`app.run(threaded=True)` doesn't result in different behavior.

Unfortunately I have no time to figure out how to run uwsgi in http mode or gunicorn.
