### ISSUE TITLE
Improve README for flaskr example

### ISSUE THREAD

**Issue by Bubblemelon** [pallets/flask#2510]
Please improve the [readme file](https://github.com/pallets/flask/blob/master/examples/flaskr/README) for the flaskr example.

Include more details on how to set it up, **especially for step 1**.  

I could not get step 3 to work probably because I didn't get step 1 to work. This is the error I'm getting:
`$ export FLASK_APP=flaskr.factory:create_app() `
`-bash: syntax error near unexpected token `(' `

Thanks !

**Comment by tropiano** [comment]
You are right, It should work with 
`export FLASK_APP="flaskr.factory:create_app()"`

**Comment by davidism** [comment]
continued in #2513
