### ISSUE TITLE
No documentation for how to test CLI commands

### ISSUE THREAD

**Issue by fgblomqvist** [pallets/flask#2511]
There is currently no documentation for how to "officially" test Flask CLI commands. It seems appropriate that there should be a section about it on this page: http://flask.pocoo.org/docs/0.12/testing/.

I know there was a previous issue (#1709) that got closed, but I do believe it is an issue that there is no documentation on this very important topic. Furthermore, it is also very hard to find information about how to do it online (that old issue is literally the only page I found that is relevant).

**Comment by davidism** [comment]
Click is already documented, and Flask's CLI docs link to Click. http://click.pocoo.org/5/testing/

**Comment by fgblomqvist** [comment]
Right, that's true. Tried to make sense of it in the flask context before but couldn't figure it out. Figured out how to do it a couple of days ago by combining information from several sources (and spending a couple of hours), so now it makes perfect sense. But it could just be that I didn't fully understand click before I suppose. If you think it's enough with the click docs, I understand.

**Comment by davidism** [comment]
Flask 1.0 will add `app.test_cli_runner` to make this more straightforward. #2636
