### ISSUE TITLE
Idea: `flask run`-like command for production

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/flask#2512]
Sentry has this for example, and they simply run uWSGI (which can be installed via `pip`); configured with sane defaults through environment variables: https://github.com/getsentry/sentry/blob/master/src/sentry/services/http.py

I think this would make sense for Flask too since it'd make simple use cases easier (people just wanting to run a small application without having to configure much).

---

This could be done in a separate standalone package providing a new cli command instead of having it in the Flask core, but I think having an issue here is a good idea anyway in case someone is looking for something to contribute.

**Comment by davidism** [comment]
@doobeh put together [flask-gunicorn](https://github.com/doobeh/flask-gunicorn) at PyCon.

**Comment by doobeh** [comment]
Yeah, which needs to be dusted off— been a bit disengaged with external projects recently.  I'll take this as a kick to get back in motion.

**Comment by RyanSquared** [comment]
So in relation to `FLASK_ENV`, perhaps there should be a system inside of the Flask's base `run` command that delegates the "running" of the program to some kind of interface. So there could be a `flask.run.debug` which starts the debug server, `flask.run.gunicorn` which starts up gunicorn, `flask.run.tornado` which uses Tornado's WSGI and internal HTTP server. Then, the user-customized environments will choose which of these versions will trigger what, so `FLASK_ENV=dev` sets `FLASK_RUN_BACKEND=debug`, `FLASK_ENV=testing` sets whatever is used for testing...?

**Comment by jgrasser** [comment]
It might be preferable to instead run the flask app using an apache docker image with mod_wsgi. If there is suitable interest within the community, I would be happy to build out the necessary docker config.

**Comment by miguelgrinberg** [comment]
This discussion clearly indicates that it is going to be hard to create a production server command that can satisfy the needs of all users, so I favor the idea of using separate extensions such as `flask-gunicorn`.

Also, specifically regarding the original proposal of using uWSGI for this, I think that is going to cause trouble for a lot of people, because uWSGI only has a source distribution on pypi. For example, installing uWSGI on Windows is nearly impossible unless you use the Ubuntu/WSL or Cygwin.

**Comment by jwg4** [comment]
What would `flask-gunicorn` do though @miguelgrinberg ? Would it just be a wrapper around gunicorn which invokes it in a specific way? For this to be helpful wouldn't all `flask-foo-server` extensions have to have the same options/arguments?

**Comment by miguelgrinberg** [comment]
@jwg4 have you seen the code for flask-gunicorn? https://github.com/doobeh/flask-gunicorn

Basically it overrides `flask run` and starts gunicorn instead.

**Comment by jwg4** [comment]
Oh sorry, @miguelgrinberg I didn't realize you were talking about something that already exists. Definitely seems like the right approach, Flask itself probably doesn't want to make any determination as to how you want to run your app in production.

**Comment by RyanSquared** [comment]
I like the usage of extensions being used to replace the `flask run` as it can be done inside a virtualenv or container and (hopefully) requires no work at all from the Flask side. Is there any considerations to be done except for polishing potential and existing `flask-run` extensions? I'd like to help on this if possible.

**Comment by davidism** [comment]
While I still might consider some sort of extensibility of the `run` command for other WSGI servers in the future, at this point I don't think it's worth adding the complexity to the run command. Or at least I think we need to focus on fixing the disconnect between `app.run` and `flask run` first. I'm working on refreshing the deploy docs, so hopefully that will help people understand how to deploy in production better.
