### ISSUE TITLE
Rewrite tutorial and example

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2513]
Rewrite the tutorial and corresponding example, taking into account new and common patterns for Flask.

- [x] example
- [x] tutorial

**Comment by davidism** [comment]
I'm working on this. I will take into account the feedback on other issues, but I am closing them so there is a single point of discussion about the tutorial.

**Comment by changeling** [comment]
Thanks, @davidism. I posted over there thinking it was the single point of discussion. Your issue does a better job of consolidation.

To be clear, my comment (https://github.com/pallets/flask/issues/1374#issuecomment-342945368) isn't addressing differences between the repo and the release or even the release code. Only problems in the currently released docs (0.12.x) via http://flask.pocoo.org/docs/0.12/.

**Comment by wlongxiang** [comment]
Hi, I am currently using flask to build a small web service, and I was looking at this doc page about "deploying flask using setuptools", and found a minor issue.
In this chapter: [Tagging Builds](http://flask.pocoo.org/docs/0.12/patterns/distribute/),
there is a missing double quote about the aliases settings, also it might be better to have newlines.

**Comment by morenoh149** [comment]
@wlongxiang that would probably be better as a separate issue and if @davidism chooses to address in their PR they can close it.

**Comment by pbouda** [comment]
To run the current flaskr app I had to change:

    export FLASK_APP="flaskr.factory:create_app()"

to:

    export FLASK_APP="flaskr.factory:create_app"

**Comment by pbouda** [comment]
Actually I was wrong, that did not solve my problem. What I did is adding a line to the factory:

    app = create_app()

Then:

export FLASK_APP="flaskr.factory:app"

The basic problem is that the flask cli does not find any attribute "create_app()" if you specify the attribute with the brackets. It seems like this is solved in current master...?

**Comment by ThiefMaster** [comment]
If you use the 'latest' docs  you need to use the latest (git master) flask. Use the 'stable' docs otherwise.

**Comment by pbouda** [comment]
Understand. I browsed the docs on github, so I used the latest doc. But then I installed just as described in the README, and that installed the flask/cli stable. This does not work atm.

**Comment by davidism** [comment]
That's already been addressed in one of the linked issues. You need to install flask from master, then flaskr from master, then follow the docs from master.

**Comment by wgwz** [comment]
Hey, @davidism. Do you have branch set up for this? I am interested in helping with this

**Comment by davidism** [comment]
I can push it soon, traveling right now. If you want to look at something related, the patterns directory could probably use a refresh.

**Comment by nanomosfet** [comment]
Will this include using blueprints in the tutorial? I'm guessing the answer is yes because the example on the repository uses blueprints. @davidism I wouldn't mind helping on this if help is needed.

**Comment by ErwinBaeyens** [comment]
I'm trying to follow the tutorial on the flask website.  I got to step 5 Creating the database. Despite checking several times if I got everything right running flask initdb  keeps reporting that there is no command initdb.  When followed the link to your github account to check for errors, 
it seems that the code in here is very different from the one on the website e.g:  the main file here is called factory.py instead of flaskr.py.  in it there is an import statement containing workzeug which is not in the website.  At this point the tutorial is severely broken and any newcomer will not continue the tutorial, and as such will not be taking up flask.

**Comment by davidism** [comment]
You're looking at the master version of the repository, but the latest release for the docs. Look at the same versions on both. This has been fixed in master.

**Comment by davidism** [comment]
@lepture @ThiefMaster here's the new tutorial example: https://github.com/davidism/flask/tree/examples/examples/tutorial

I think it demonstrates a good structure and most common patterns. There's of course more it could do but I didn't want to get more complicated, it's already a lot of code, especially if we count the 100% test coverage.

Give it a look and let me know what you think. I'm going to write the tutorial based on it.

**Comment by ThiefMaster** [comment]
I'll have a look later. the one thing I found so far is lack of `include_package_data=True` and a `MANIFEST.in`, so right now you couldn't build a wheel (or well, you could, but it would not contain templates etc). I think if you have a setup.py, it makes sense to have this as well so it's usable not only in editable/develop mode.

**Comment by ThiefMaster** [comment]
.gitignore: add trailing slashes for things that are always directories (e.g. `.idea/`)? also `*.swp` (vim swap files) is missing in there, `*~` as well (emacs backups iirc.)

setup.py: `zip_safe=False`? Not sure if any recent pip/wheel versions even look at it. But if they do, better add it.

Would it make sense to have the app context as a fixture? I think most test cases will require one. Usually I even go as far as having it as `autouse=True`.

What about adding a decorator to require login?

`update()` is huge and I would split it into smaller functions (e.g. `_get_post(id)`)

> create a temporary file to isolate the database for each test

We should make it clear that this is fine for a small app but a bigger (sqlalchemy-based) app should use other ways of separation (e.g. nested transactions) to avoid the - somewhat slow - `create_all()` during all tests

>  os.makedirs(app.instance_path, exist_ok=True)

`exist_ok=True` is Python3-only

> app.add_url_rule('/', view_func=blog.index)

That's gonna be duplicate content. Why not redirect instead?

**Comment by davidism** [comment]
Re: `zip_safe`: I can add it, but I don't think it's needed. It only affects `bdist_egg`, autodetection sets `False` when it finds data files, and `pip` always unzips packages.

Re: temporary database: I realized while training an intern recently that Flask-SQLAlchemy, Flask-WTF, and most extensions don't have a section on testing patterns. I think those projects' docs should be improved instead. If you can think of a clean way to do it with plain SQLite, I'll add it, but it's pretty complex even with SQLAlchemy.

**Comment by gpbaculio** [comment]
I have followed the readme on the master but failed on windows 10
