### ISSUE TITLE
Flask.create_url_adapter should use SCRIPT_NAME, not APPLICATION_NAME

### ISSUE THREAD

**Issue by rhymoid** [pallets/flask#2521]
When [`Flask.create_url_adapter`](https://github.com/pallets/flask/blob/c74f46979a8b8358437bd7f76e478d04248a9c72/flask/app.py#L1923) is supplied with a request, it passes the request on to [`Map.bind_to_environment` from `werkzeug.routing`](https://github.com/pallets/werkzeug/blob/master/werkzeug/routing.py#L1253). This will result in a call to `Map.bind`, where the `script_name` argument is set to the value of the environment variable `SCRIPT_NAME`.

However, when it isn't supplied with a request, `Flask.create_url_adapter` will call `Map.bind` directly. Instead of `SCRIPT_NAME`, it passes the value of `APPLICATION_NAME` via the `script_name` argument. Per #1714, I understand that `APPLICATION_NAME` has nothing to do with routing. I guess this should change, but I'm not sure.

I discovered this when debugging a tangentially related issue that turned out to be in my own code (I assumed `MapAdapter` could ultimately be used to translate whole URL paths to endpoints, but it seems I have to strip off `SCRIPT_NAME` myself).

**Comment by davidism** [comment]
The argument is `server_name`, not `script_name`. The script name is not the server name.

**Comment by rhymoid** [comment]
I don't intend to point to this:

    return self.url_map.bind_to_environ(request.environ,
        server_name=self.config['SERVER_NAME'])

I want to pointing to this:

    return self.url_map.bind(
        self.config['SERVER_NAME'],
        script_name=self.config['APPLICATION_ROOT'],  # <--- this line
        url_scheme=self.config['PREFERRED_URL_SCHEME'])

*That* line seems wrong.

**Comment by davidism** [comment]
Please provide an example that reproduces the issue you're having.

**Comment by mitsuhiko** [comment]
@rhymoid the parameter passed is `APPLICATION_ROOT` to the `script_name` parameter. Flask calls it application root because script name is very confusing. So this is intended behavior.

**Comment by rhymoid** [comment]
@Larivact's [comment in #1714](https://github.com/pallets/flask/issues/1714#issuecomment-287263356) says otherwise. So [does the documentation](https://github.com/Larivact/flask/commit/2995366dde63b8acd1f246bcd5a4cf7d61f0c1fa).

**Comment by mitsuhiko** [comment]
The documentation is slightly misleading here. It's *also* used for the session cookie but not exclusively.

**Comment by mitsuhiko** [comment]
I'm a little bit confused right now what the exact issue is you're running into here.

**Comment by davidism** [comment]
That comment is misleading. The dev docs are already updated to explain both places it's used. I agree with mitsuhiko that it's not clear what the issue is at this point.

**Comment by rhymoid** [comment]
Alright, then it's probably nothing but a documentation bug. If the documentation had been accurate, I'd think this would be a bug waiting to happen for cases where `APPLICATION_ROOT` and `SCRIPT_NAME` were not equal.

**Comment by mitsuhiko** [comment]
@davidism for what it's worth i would not be opposed to a mode where we forcefully override the wsgi server for prefixes, server name, ssl etc. I am in fact running myself a wsgi middleware usually that forces stuff to be consistent.
