### ISSUE TITLE
Missing import statement in "Uploading Files" doc section

### ISSUE THREAD

**Issue by wrznr** [pallets/flask#2523]
### Expected Behavior

Examples in the documentation should be running after copying them. In this case the import statement for the `flash` function is missing in the example code.

### Actual Behavior

Running the example from [Uploading Files](http://flask.pocoo.org/docs/0.12/patterns/fileuploads/) results in
```console
NameError: global name 'flash' is not defined
```

**Comment by davidism** [comment]
PRs welcome

**Comment by raynae** [comment]
I was planning to make this edit, but it looks like this may have been fixed in #2230

**Comment by davidism** [comment]
Thanks for checking @raynae, didn't notice that the link wasn't to the dev version.
