### ISSUE TITLE
Docs for change default logging format / Log would print twice after add a stream handler

### ISSUE THREAD

**Issue by eromoe** [pallets/flask#2524]
Hello,

flask stable version 0.12 , docs  doesn't cover this.   Only dev version has , which not work for 0.12.

I want to change the logging format , after  I add below code 
```
    steam_formatter = logging.Formatter("[STREAM][%(levelname)s][%(asctime)s][%(name)s][Line:%(lineno)d] %(message)s")
    stream_handler = logging.StreamHandler()
    stream_handler.setLevel(logging.DEBUG)
    stream_handler.setFormatter(steam_formatter)
    app.logger.addHandler(stream_handler)
```

I find flask would print two log message with different format .  Soon I understand flask still keep its original stream handler . I think reset logging format should be clarified in stable docs.

**Comment by davidism** [comment]
Due to the way docs are built, released docs can not be updated.
