### ISSUE TITLE
MD채용공고

### ISSUE THREAD

**Issue by parkyunji** [pallets/flask#2533]
![_md _](https://user-images.githubusercontent.com/33747994/33298671-fab447f8-d42a-11e7-8e29-9f9bd8d27c86.png)

**Comment by ThiefMaster** [comment]
Go screw yourself.

**Comment by lepture** [comment]
@ThiefMaster I've reported it to GitHub. You should do the same thing.

**Comment by ThiefMaster** [comment]
Already done (also blocked him from all pallets repos)
