### ISSUE TITLE
export FLASK_APP=run.py doesn't recompile .pyc files (BUG)

### ISSUE THREAD

**Issue by patientplatypus** [pallets/flask#2534]
I noticed the following error while compiling something and it was irksome. Maybe it is worth looking at idk. 

The issue is the following. 

Say I have the entrypoint to my app be main.py and I export it with `export FLASK_APP=main.py`. If I then later go back and rename the entrypoint run.py and export it, then sometimes flask will continue to use the main.pyc file which will break the application. It may be that this sometimes also occurs with other .pyc files in general, I am not sure - it irks me that previous .pyc files are not destroyed between FLASK_APP runs if shadowing is a possibility. 

Just thought I would point this out - it took me some debugging time and maybe it will save someone else a bit of time. 

Thanks.

**Comment by davidism** [comment]
You're saying that if you completely stop the server, rename the file, export the var, and start the server, it uses the old file? You'll need to provide a reproducible example if that's the case, that's not how Python works.

**Comment by davidism** [comment]
If you just mean that renaming / exporting while the server is still running doesn't work, then that's expected, don't do that. Python doesn't reload files when they're renamed, and the reloader only knows about what started the app, not what it became later.

**Comment by patientplatypus** [comment]
Honestly, (and I know that this will sound bad), I'm not sure that I can reproduce the exact sequence of steps that led to this error. What I do know is that to get it fixed, I had to delete all of my .pyc files and re-export and re-run everything. So *something* in my .pyc files was shadowing the compile, and the above is my best guess. What is frustrating is that I wish that export flask app had an option to delete the .pyc files in the parent directory on down and recompile them to make sure potential shadowing does not occur. I am relatively new to python, please forgive my ignorance.

**Comment by patientplatypus** [comment]
Also, I did stop the server, re-export and rerun.

**Comment by patientplatypus** [comment]
-- I'll close the issue for now.
