### ISSUE TITLE
typos in docs/patterns/distribute page

### ISSUE THREAD

**Issue by wlongxiang** [pallets/flask#2544]
Hi, I am currently using flask to build a small web service, and I was looking at this doc page about "deploying flask using setuptools", and found a minor issue.
In this chapter: [Tagging Builds](http://flask.pocoo.org/docs/0.12/patterns/distribute/),
there is a missing double quote about the aliases settings, also it might be better to have newlines.

The correct formatting should be like below:
![screenshot-2017-12-6 deploying with setuptools flask 0 13 dev documentation](https://user-images.githubusercontent.com/10107120/33655364-1fc8f220-da73-11e7-8849-3f8ea70c6c75.png)
@davidism

**Comment by lepture** [comment]
It is already fixed in the master.
