### ISSUE TITLE
send_from_directory() and send_file() fails on Windows

### ISSUE THREAD

**Issue by kuba-baku** [pallets/flask#2546]
On Windows send_from_directory() fails because posix path from safe_join() and Windows path from current_app.root_path gets mixed up.

I see problem in this line:
https://github.com/pallets/flask/blob/eb1c2faf9f1fd785616203dc00f6dd680682dc38/flask/helpers.py#L691
E.g. running app from C:\PythonApps\FlaskApp: 
```python
send_from_directory("instance/data", "file1.txt")
filename = safe_join(directory, filename)
# filename == "instance/data/file1.txt"
if not os.path.isabs(filename):
        filename = os.path.join(current_app.root_path, filename)
        # here's the problem -> filename == "C:\\PythonApps\\FlaskApp\\instance/data/file1.txt"
    try:
        if not os.path.isfile(filename):
            # here it fails
            raise NotFound()
```
Returning posix path from safe join is imo ok (see #2284) but joining with non posix path fails.
I think solution can be using os.path.normpath after joining path parts:
```python
filename = os.path.normpath(os.path.join(current_app.root_path, filename))
```
Same problem is with send_file():
https://github.com/pallets/flask/blob/d08d96acbcabcde23307ed060f71f95ba9cb7b8d/flask/helpers.py#L520

### Environment

* Python version 3.5.4:
* Flask version 0.12.2:
* Werkzeug version 0.12.2:

**Comment by davidism** [comment]
Does serving static files work?

**Comment by kuba-baku** [comment]
Eh, sorry, it's a problem between my keyboard and chair.
I just tried some workarounds and nothing helped and then I saw, that I had the folder in wrong location (one level up from app's root path).

**Comment by davidism** [comment]
Yeah, it's a bit unfortunate that the path mixes back and forward slashes, but Python on Windows should be able to handle that without intervention.

**Comment by sbarzowski** [comment]
I'm having a very similar problem on `1.0.3`. When migrating some code to Windows I found out that the following results in 404 for me:
```
    response = flask.send_from_directory('D:\\Work\\x\\blah', 'a\\b\\c\\d.jpg')
```
But this works:
```
    response = flask.send_from_directory('D:\\Work\\x\\blah', 'a/b/c/d.jpg')
```

The only difference is slashes vs backslashes in the filename part. 

I think this is so, because in `safe_join` this function doesn't do anything with the backslashes: https://github.com/pallets/flask/blob/1.0.3/flask/helpers.py#L669 and here there's a check for any non-slash separators: https://github.com/pallets/flask/blob/1.0.3/flask/helpers.py#L672

**Comment by tunnelr** [comment]
> Sorry for reviving an old issue, but I'm having a very similar problem on `1.0.3` and perhaps the context here could be relevant. When migrating some code to Windows I found out that the following results in 404 for me:
> 
> ```
>     response = flask.send_from_directory('D:\\Work\\x\\blah', 'a\\b\\c\\d.jpg')
> ```
> 
> But this works:
> 
> ```
>     response = flask.send_from_directory('D:\\Work\\x\\blah', 'a/b/c/d.jpg')
> ```
> 
> The only difference is slashes vs backslashes in the filename part.
> 
> I think this is so, because in `safe_join` this function doesn't do anything with the backslashes: https://github.com/pallets/flask/blob/1.0.3/flask/helpers.py#L669 and here there's a check for any non-forward-slash separators: https://github.com/pallets/flask/blob/1.0.3/flask/helpers.py#L672

Same here with version `1.1.1`. Arguments (paths) with "\\" give 404.
Hackish solution to get what I expect from a "safe join"

`import os
from flask import safe_join as _safe_join
safe_join = lambda r,*paths: os.path.normpath(_safe_join(r,*[p.replace(os.path.sep,"/") for p in paths]))
`
