### ISSUE TITLE
Document which servers support wsgi.input_terminated

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [pallets/flask#2547]
I learned from multiple issues (like https://github.com/kennethreitz/httpbin/issues/340, https://github.com/pallets/werkzeug/issues/1149, https://github.com/pallets/flask/issues/367) that Flask developers are making a push to implement `wsgi.input_terminated` as a way for wsgi servers and apps to support chunked requests.

However, it is extremely hard to navigate these issues and figure out what works and what does not. Is there an intention to document the support for this flag? This is a great feature, but from the user's perspective it is currently very hard to even figure out how it works. I propose at least keeping an issue alive with information on which environments will support it.

Here is what worked for me:
Flask 0.12.2 + Gunicorn 19.7.1
Flask 0.12.2 + Werkzeug 0.13

What did not work for me
Flask 0.12.2 + uWSGI 2.0.15

**Comment by davidism** [comment]
I think it's up to each WSGI server to document that it supports chunked encoding. It's not feasible for us to keep a list up to date in Werkzeug's docs.

Not sure how Gunicorn is working, since it doesn't set the flag yet.

**Comment by mitsuhiko** [comment]
Going to close this for the reasons outlined above. We can't stay up to date with what other servers do.
