### ISSUE TITLE
Some of tests fail on running pytest

### ISSUE THREAD

**Issue by djmgit** [pallets/flask#2550]
### Expected Behavior

On running ```pytest``` all tests should pass.

To reproduce please execute ``` pytest ```
### Actual Behavior

5 tests fail 

Here is the full output of pytest: https://paste.ubuntu.com/26177622/

### Environment

* Python version: 3.5.2

**Comment by djmgit** [comment]
I would like to work on this, any pointers regarding from where to start would be of great help.
I have build Flask from master branch.

**Comment by davidism** [comment]
Right, I noticed this too. A recent PyTest update added automatic capture of log messages. To do this, I think they add a logging handler. Flask only adds a logging handler if there are no loggers already registered, so it fails to add its default logger.

The ideal fix here is to disable logging capture for these tests, although I haven't looked into how PyTest handles this yet.

**Comment by camilojimenez** [comment]
I tracked the issue to this release of pytest

https://github.com/pytest-dev/pytest/blob/6cdd85122705393cfcfe08570bae581bf9f2d157/CHANGELOG.rst

According to the changelog:

- Pytest now captures and displays output from the standard logging module. The user can control the logging level to be captured by specifying options in pytest.ini, the command line and also during individual tests using markers. Also, a caplog fixture is available that enables users to test the captured log during specific tests (similar to capsys for example). For more information, please see the logging docs. This feature was introduced by merging the popular pytest-catchlog plugin, thanks to Thomas Hisch. Be advised that during the merging the backward compatibility interface with the defunct pytest-capturelog has been dropped. (#2794)

The actual logging code is here

https://github.com/pytest-dev/pytest/blob/6cdd85122705393cfcfe08570bae581bf9f2d157/_pytest/logging.py#L259

I skimmed over the logging code and could not find any way to disable logging capture in a documented way.

What are the thoughts about

- Pinning the pytest version to 3.2.5
- Updating the test to support this
- Write a setup/teardown method to remove any existent loggers

**Comment by davidism** [comment]
I would go with option three. It should work out similar to some other tests in that module that modify the handlers.

**Comment by camilojimenez** [comment]
Does this seem like an appropriate solution?

~~~~
@pytest.fixture
def no_logging_handlers(app):
    logging.root.handlers[:] = []
    app.logger

def test_logger(app, no_logging_handlers):
    assert app.logger.name == 'flask.app'
    assert app.logger.level == logging.NOTSET
    assert app.logger.handlers == [default_handler]
~~~~

**Comment by davidism** [comment]
Refer to the `reset_logging` fixture. It can probably be changed to clear and restore the root handlers.

**Comment by camilojimenez** [comment]
I thought of doing that, but this would clear and restore the handlers for every test. Is this preferred?

**Comment by davidism** [comment]
I don't know, I'm not looking into it directly because @djmgit offered to do so, then you started to. Do you want me to write this instead?

**Comment by camilojimenez** [comment]
Also, I need to call app.logger to force logger creation before the pytest logger gets added. That would require changing the signature from 

~~~~
def reset_logging(monkeypatch)

to

def reset_logging(monkeypatch, app)
~~~~

I apologize if I am asking too many questions. I'll prepare the PR now

**Comment by djmgit** [comment]
@camilojimenez @davidism please go ahead with this issue, I would love collaborating as well.
@camilojimenez I tried your solution, it solves 1 error, still its showing 4 errors.
