### ISSUE TITLE
teardown_request not executing on first request in debug/uwsgi (works without debug)

### ISSUE THREAD

**Issue by iScrE4m** [pallets/flask#2563]
### Expected Behavior

Given we have an app with a `teardown_request` and a `route` that always raises exception, when the app is first launched either with `debug=True` or through `uWSGI`, the teardown request should execute. 

```python
from flask import Flask

app = Flask(__name__)


@app.teardown_request
def teardown(exc):
    print('Teardown request executed')

@app.route('/')
def error_route():
    e = 3 / 0

if __name__ == '__main__':
    app.run(debug=True)
```

### Actual Behavior

Instead for the first request (in uWSGI case, for each worker's first request), the teardown does not execute. After few hours debugging with PyCharm the best information we can share (I hope it's actually useful) is that in `flask.ctx.RequestContext.push()` the `_request_ctx_stack.top` is None.

### Environment

* Python version: 3.5
* Flask version: 0.12.2
* Werkzeug version: 0.13

**Comment by wgwz** [comment]
Why not do something like this? 
```from flask import Flask

app = Flask(__name__)

@app.teardown_request
def teardown(exc):
    print('Teardown request executed')

@app.route('/')
def error_route():
    try:
    	e = 3 / 0
    except ZeroDivisionError:
        pass
    return 'error route'
	
if __name__ == '__main__':
    app.run(debug=True)
```
By the way, this seems is a question better suited for Stackoverflow.

**Comment by iScrE4m** [comment]
Because I don't want to catch the exception. Teardown request should execute every single time. The real solution is to set `PRESERVE_CONTEXT_ON_EXCEPTION` to False. 

At first I thought it was a bug, then I learned it's somewhat intended, but the documentation surrounding `PRESERVE_CONTEXT_ON_EXCEPTION` is very poor and in no way does it suggest it's connected. It also doesn't make sense that uWSGI is setting this variable to `True`.

**Comment by wgwz** [comment]
I checked what you mean by `PRESERVE_CONTEXT_ON_EXCEPTION` being the solution. It seems like the teardown request gets executed either way. I think the key word in the doc is "immediately". So it seems like this is an intended behavior which seems reasonable to me. Do have suggestions on how to improve the docs?
>In debug mode Flask will not tear down a request on an exception immediately. Instead it will keep it alive so that the interactive debugger can still access it. This behavior can be controlled by the PRESERVE_CONTEXT_ON_EXCEPTION configuration variable.
- http://flask.pocoo.org/docs/dev/api/#flask.Flask.teardown_request. 
```
from flask import Flask

app = Flask(__name__)
app.config.update({
    'PRESERVE_CONTEXT_ON_EXCEPTION': True
})
app.logger.info(app.config)

@app.teardown_request
def teardown(exc):
    app.logger.info('Teardown request executed')

@app.route('/')
def error_route():
    e = 3 / 0
    return 'error route'
```

**Comment by iScrE4m** [comment]
I see, so the executed request is just delayed. I (and my colleagues) somehow missed that 😨 . So if there's an ok request following the error request, you see two teardowns executing. That also means that if a life of a process ends with a error request, that error disappears from any evidence.  As it's a debug intended behavior, it's very reasonable. I am confused by uWSGI, but that's not a Flask issue.

Since you found it in the doc quickly, I guess the doc is okay too.  What still doesn't make much sense to me is the name of the variable - preserve context != delay teardown until another request is made - but that might be just us being non-native speakers, since now that I'm trying to provide an argument and analyzing it, it started making lots of sense.

Closing it, as it was very obviously my fault. Thanks for the breakdown!

**Comment by wgwz** [comment]
I also agree it is not obvious at first glance what that configuration parameter name means, but that doesn't mean its not well-named. To the documentations credit, there is a big disclaimer "Debug Note" in the section for `teardown_request`. I'm glad it's making sense now!
