### ISSUE TITLE
Override env var when using python-dotenv 

### ISSUE THREAD

**Issue by greyli** [pallets/flask#2572]
Currently, the env var in `.env` or `.flaskenv` will not override existing value. However, if a user installed `python-dotenv` and created a `.flaskenv`, he will expect the variables in `.flaskenv` override the old values. It's inconvenience when you develop multiple applications at the same time.

**Comment by wgwz** [comment]
MCVE? I'm interested in testing this and seeing the problem

**Comment by greyli** [comment]
It's no need for a demo. Considering the condition below:
1. You run application A via `flask run`, the `FLASK_APP` in `.flaskenv` or `.env` was set to `myappA`.
2. You change the current work directory to application B.
3. You run application B via `flask run`, but the env var is already set to `myappA` and python-dotenv will not override it (default behavior), so you get import name error.

**Comment by wgwz** [comment]
> It's no need for a demo.

I get that it is not a lot of code and setup, but it is important for nailing down the issue.  This way others can do the exact same thing you are, without having to duplicate your work. Someone might be able to answer without running the code if they see all the relevant information.

**Comment by wgwz** [comment]
I was curious about this so I put this together: https://github.com/wgwz/flaskenv-two-app-test
In this case the requirements are the same, so I used the same virtualenv for testing this. 
I have two separate apps, each with a `.flaskenv`, specifying `FLASK_APP` correctly for each.
When I switch between directories and do `flask run` it works fine for each application. 

Am I misunderstanding your issue @greyli ?

**Comment by greyli** [comment]
@wgwz Wow, you provided a good example! But you have to use the flask at the master branch.

**Comment by davidism** [comment]
So, no problem then?

**Comment by greyli** [comment]
@davidism Actually, no. The current behavior was not overridden, IMO it's better to override exist env var instead.

**Comment by davidism** [comment]
I can't control how python-dotenv works. There's nothing really weird going on here, you'd get the same behavior if you set an env var manually then cd'd to another directory.

**Comment by greyli** [comment]
Why don't just override the old value? Then you don't need to set env var manually.

**Comment by greyli** [comment]
@davidism If you think it's ok, I'll make a PR.

**Comment by davidism** [comment]
python-dotenv  uses `os.environ['key'] = value`. This only sets the environment for the current process, it doesn't "break out" of Python and apply to the terminal's env.

**Comment by davidhariri** [comment]
Respectfully, I think this was misunderstood @davidism. The issue here is as described. Within the shell, the env vars are not getting overriden after being changed, despite re-running flask from the CLI. It's the same issue I'm having in #2893.

**Comment by ThiefMaster** [comment]
It is technically impossible to change the environment of the caller. (that's actually the reason why you need to `source` virtualenv's activate script and why `pipenv shell` spawns a subshell.)

**Comment by davidhariri** [comment]
@ThiefMaster does that jive with `PIPENV_DONT_LOAD_ENV=1 pipenv shell` solving the issue?
