### ISSUE TITLE
TypeError when serving static files (304 NOT MODIFIED)

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [pallets/flask#2573]
### Repro

1. Create minimal hello world application as in http://flask.pocoo.org/
2. Also create file `/static/my_style.css` with arbitrary content
3. Run the application: `FLASK_APP=hello.py flask run`
4. Visit `http://localhost:5000/static/my_style.css`
5. Refresh the page to trigger "not modified" response

### Expected behavior

Only request log to appear in stderr:
```
127.0.0.1 - - [31/Dec/2017 22:24:38] "GET /static/my_style.css HTTP/1.1" 200 -
127.0.0.1 - - [31/Dec/2017 22:24:38] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [31/Dec/2017 22:24:43] "GET /static/my_style.css HTTP/1.1" 304 -
```

### Actual behavior

The following also appears in stderr:

```pytb
Error on request:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "c:\python36\lib\site-packages\werkzeug\serving.py", line 263, in execute
    write(b'')
  File "c:\python36\lib\site-packages\werkzeug\serving.py", line 232, in write
    status < 200 or status in (204, 304)):
TypeError: '<' not supported between instances of 'str' and 'int'
```

When this happens, `status` is `'304 NOT MODIFIED'`.

I think this defect became visible after [0c5cad57](https://github.com/pallets/werkzeug/commit/0c5cad57c2370c4b916b3651adb4d82eb9fbf5ec).

### Environment

* Python version: Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
* Flask version: 0.12.2
* Werkzeug version: 0.14

**Comment by mitsuhiko** [comment]
Indeed. I fixed that in a 0.14.1 release of Werkzeug. Sorry for that :(
