### ISSUE TITLE
How to set up the flask listen backlog？

### ISSUE THREAD

**Issue by wangfakang** [pallets/flask#2578]
As the title says, I didn't find the parameters to set the listen backlog.

```
def run(
        self, host=None, port=None, debug=None, load_dotenv=True, **options
    ):
```

**Comment by davidism** [comment]
What is the "listen backlog"?

**Comment by davidism** [comment]
You appear to be talking about Flask-Listen. You should consult the documentation of that project.

**Comment by mitsuhiko** [comment]
Currently the only way to reconfigure the listen backlog is to change this constant in werkzeug.serving: https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L97

We can make it configurable but the development server really should not be used in production.

**Comment by davidism** [comment]
My bad, I'd never seen that term before. I agree though, this shouldn't be exposed for configuration.
