### ISSUE TITLE
Bump dependency versions

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2586]
Currently we require:

* Werkzeug>=0.9 (4.5 years ago) (latest 0.14)
* Jinja2>=2.4 (8 years ago) (latest 2.10)
* itsdangerous>=0.21 (4.5 years ago) (latest 0.24)
* click>=4.0 (3 years ago) (latest 6.0, stable 5.0)

Should we bump these all to the latest versions?

**Comment by davidism** [comment]
Or at least we should analyze if we're doing anything specific to support these old versions. If we're not it's probably OK to leave as-is.

**Comment by davidism** [comment]
Should we have a policy in the future of updating to the latest dependencies before each release? Or should we remove version information and instead say "you may be able to use older versions, but we don't guarantee it." The former keeps all the projects moving forward and I'd prefer it, but the later is more forgiving, especially if there's no actual incompatibility.

**Comment by jeffwidman** [comment]
> you may be able to use older versions, but we don't guarantee it.

I have a slight preference for this. At my day job, a (bad) decision was made long ago to run everything under a single global shared venv...  we are in the middle of a multi-year migration to fix that, but in the meantime it'd be nice to not have our hands tied on an old flask version just because we can't upgrade a few of the dependencies.

That said, it feels dangerous to fully remove versions... I would still leave minimum requirements in `setup.py` to prevent installing versions that are _already_ known to break.

What about adding something to the docs like:
> We only develop/test with the latest stable versions of our dependencies. You may be able to use older versions, but we don't guarantee it. If you find a version incompatibility, please file an issue on our GitHub repo so that we can bump the minimum required version for that dependency.

And then also bump the dependencies to latest in `tox.ini`?

**Comment by davidism** [comment]
Maintaining a list of minimum versions doesn't really guarantee anything, since we could change that minimum at any time anyway. It just means we have to keep testing what we say is the minimum, to make sure it's still the minimum.

**Comment by lepture** [comment]
Versioning is a hard thing.

However, all dependencies of Flask are pallets projects, which makes things easier to maintain than NodeJS. When people using Flask, should we expect that they are also using Werkzeug, Jinja2, itsdangerous and click directly? I don't think so. Even if they are using them directly, it won't break things too much/often.

The situation of @jeffwidman is really bad. But it has nothing to do with Flask's versions. That global environment will fail sooner or later if they are going to upgrade something.

My suggestion is that we keep a newer version of the dependencies, but not necessary to be the latest.

**Comment by davidism** [comment]
So should I put a compat check in to the session cookie samesite support so that Werkzeug 0.14 isn't required? Or should I not worry about compat, and bump the version to whatever is needed, when it's needed?

What version should we bump Jinja to? 2.4 is *8 years old*, no one should be using that with Flask 1.0, but any other choice seems equally arbitrary.

**Comment by lepture** [comment]
If it is a MUST, we should bump the version to that certain version. For Flask 1.0, I think we can bump everything to the latest versions.

However, if this is a long time decision, I don't like the forcing latest way.

**Comment by davidism** [comment]
Having Flask 1.0 be a "reset point" where everything is bumped, but keep compatibility going forward, seems like a good compromise.

I would like to figure out some sort of sane upgrade schedule, such as "we can remove compat after 1 year or 2 releases, whatever comes first", but that can be taken to meta and decided later.

**Comment by davidism** [comment]
I'm going to use 1.0 as a "reset point", bumping everything to the latest version. Going forward, I'll bump a version rather than adding a compat check, but won't bump if not needed.

**Comment by lepture** [comment]
Yes, that is my point. Bump it if necessary.
