### ISSUE TITLE
Unclear documentation on 'Request' object

### ISSUE THREAD

**Issue by rangerscience** [pallets/flask#2598]
Regarding this documentation: http://flask.pocoo.org/docs/0.12/api/#incoming-request-data

(Note: I'd just edit and PR myself, but I can't find these docs in this repo, or any instructions for contributing to it)

1. What mime-types does Flask recognize, and what does it do when it encounters them?
1. Reading `data` also reads `stream`, so if you call `data` and then `stream`, `stream` will be empty.
1. Similarly, reading `stream` before `data` results in an empty `data`
1. Sending a JSON payload in a GET request results in a populated `form` attribute (which, as per docs, only populates on POST and PUT)

These are very much not clear from the documentation, and led me to great frustration.

Note 2: Although it's reasonable that `form` does not automagically take JSON payloads and interpret them as form data.... it might be nice to point that out explicitly, given how much use JSON has.

**Comment by davidism** [comment]
This is part of Werkzeug. You may open a PR there if you can make the docs more clear.

**Comment by rangerscience** [comment]
The Flask documentation is part of Werkzeug? I thought they were different projects.

**Comment by davidism** [comment]
The request class is from Werkzeug. Flask renders some docstrings from there.

**Comment by rangerscience** [comment]
Do you know if the documentation I linked to is present in either this repo, or the main Werkzeug repo (https://github.com/pallets/werkzeug)?
