### ISSUE TITLE
Usage of deprecated function `Request.is_xhr` in flask.jsonify

### ISSUE THREAD

**Issue by RyanSquared** [pallets/flask#2599]
```
owner@Owners-MacBook-Pro ~/Library/Python 14:12:19 % ag "is_xhr"
2.7/lib/python/site-packages/flask/json.py
251:    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:

2.7/lib/python/site-packages/werkzeug/wrappers.py
687:    def is_xhr(self):
697:            'Request.is_xhr is deprecated. Given that the X-Requested-With '
```

Full error:
>  /Users/owner/Library/Python/2.7/lib/python/site-packages/werkzeug/local.py:347:
DeprecationWarning: Request.is_xhr is deprecated. Given that the X-Requested-With
header is not a part of any spec, it is not reliable

### Environment

* Python version: 2.7.10
* Flask version: 0.12.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
This is fixed in master.

**Comment by RyanSquared** [comment]
I'm sorry D: I did a search but didn't think to check closed issues :(
