### ISSUE TITLE
Server Side Template Injection?

### ISSUE THREAD

**Issue by benjaminweb** [pallets/flask#2602]
Is this relevant?

https://www.lanmaster53.com/2016/03/11/exploring-ssti-flask-jinja2-part-2/

https://twitter.com/_qll_/status/707714873774448640

If, how can it be mitigated?

### Environment

* Flask version: all

**Comment by ThiefMaster** [comment]
No, you are not supposed to run untrusted templates.

If this worked with the SandboxedEnvironment on the other hand, it would be very relevant.

**Comment by davidism** [comment]
I'd be interested if they took a look at Jinja's `SandboxedEnvironment`, but don't take that as an endorsement to use untrusted template code.

**Comment by benjaminweb** [comment]
Does some part in the doc teach about the best practice how to get it right?

**Comment by davidism** [comment]
I'm not sure. If you want to take a look and add a message like "Rendering templates can execute arbitrary code. Do not render untrusted templates, such as from user input." that would be fine.
