### ISSUE TITLE
Flask shell: Give readline a completer that is aware of shell context

### ISSUE THREAD

**Issue by CookiesBestDinner** [pallets/flask#2604]
### Problem
`cli.py:shell_command` (flask shell) creates a context and passes it to `code.interact`
This leaves tab completion broken:

```
>>> stuff = 5
>>> stuTABTABTABTAB <- no match
```
### Suggestion
This can be remedied by supplying a completer to readline:

```
>>> import readline
>>> import rlcompleter
>>> readline.set_completer(rlcompleter.Completer(globals()).complete)
>>> stuTAB <- stuff! yay!
```

Or perhaps `flask/__main__.py` could be used as the context:

*file: flask/cli.py*
```
...
def shell_command():
...
    import __main__
    ctx = __main__.__dict__
...
```

**Comment by davidism** [comment]
This requires setting up an `InteractiveConsole` instead of using the `code.interact` shortcut. Then we can call `runcode` on the interpreter before calling `interact` on it. If possible, check if the completer is already set up.

**Comment by CookiesBestDinner** [comment]
Pardon me, what's wrong/missing with

```
readline.set_completer(rlcompleter.Completer(globals()).complete)
```
?
It "works for me", but what am I missing?

**Comment by davidism** [comment]
I was under the impression it had to be called from within the new shell. It looks like you've already done all the work, why not make a PR?

**Comment by CookiesBestDinner** [comment]
Is this sufficient indication of that it is the full context?


```
rlcompleter.holdontothisplease = ctx
```
```
$ flask shell
>>> import rlcompleter
>>> rlcompleter.holdontothisplease is globals()
True
```

**Comment by davidism** [comment]
I've been looking into this, this is not enough to match how the standard shell behaves. It looks like `venv` messes with `site.py` and doesn't set up the completer the same way as the default `site.py`.

**Comment by davidism** [comment]
Essentially need to copy Python's `site.enablerlcompleter`.

https://github.com/python/cpython/blob/22feeb88b473b288950cdb2f6c5d28692274b5f9/Lib/site.py#L401-L449

**Comment by davidism** [comment]
Looks like `venv` makes `sys.__interactivehook__` available and `code.interact` just doesn't call it like the standard shell. But when using `virtualenv` or `mkvirtualenv` it's undefined.

**Comment by davidism** [comment]
Unfortunately, `sys.__interactivehook__` doesn't pick up the added context, so it's not available for completion.

**Comment by CookiesBestDinner** [comment]
Right. It got complicated real quick. I copied over CPython's Lib/site.py's setting of the completion key and reading .inputrc (`sys.__interactivehook__` doesn't exist because of venv), while leaving historyfile untouched, and only if successfully importing readline and rlcompleter. <- this is now in the pull request.

But now I'm patching holes and being unable to reason about things, so perhaps I should drop it.
I don't mean to be pushy with the pull request, that was just *giving it a try*

**Comment by davidism** [comment]
I appreciate the pull request, often it's a lot better to have something to actually test and comment on.

I agree that this is too complicated, I don't like that we have to duplicate a bunch of code. Looks like it's already to reported to pypa/virtualenv#967.

For what it's worth, I don't use the default shell, I install Flask-Shell-IPython. IPython handles all this without hassle.
