### ISSUE TITLE
Flask does not terminate on CTRL+C

### ISSUE THREAD

**Issue by andydevs** [pallets/flask#2615]
### Expected Behavior
Flask terminates when CTRL+C is pressed

### Actual Behavior
Nothing happens.... even when you hold CTRL+C down for a long time

### Environment
Flask 0.12.2 (Werkzeug 0.14.1)
Python 3.6.3 (py launcher)
Windows CMD line (Windows 10 v1709 build 16299.192 on Intel Core i7-5500U @ 2.40 GHz / 2.39 GHz with 8 GB of RAM)

**Comment by davidism** [comment]
I can't reproduce your issue. If you can create a reproducible example, this would be a Werkzeug issue anyway.

**Comment by truonghoangnguyen** [comment]
@davidism : I have same problem

**Comment by umdstu** [comment]
For what it's worth, I too have this issue semi-frequently. It doesn't happen every time, sometimes ctrl+c kills the process, other times it just appears to hang for a minute or so, then will close. It's like something has a lock on a process or something.

**Comment by davidism** [comment]
Thank you for your interest. However, "I have this too" doesn't help us solve issues. If you can construct a minimal reproducible example demonstrating an issue specifically with Flask or Werkzeug, please open a new, specific issue in the correct project.
