### ISSUE TITLE
Document "routes" command

### ISSUE THREAD

**Issue by italomaia** [pallets/flask#2618]
Command "routes" is available at https://github.com/pallets/flask/blob/master/flask/cli.py#L798 but not documented. I tried it here, locally and it did not work ('function' object has no attribute 'make_context'). Not sure if I'm missing something or if the command is broken. Anyways, reporting.

### Environment

* Flask version: 0.12.x

**Comment by davidism** [comment]
It's not documented on purpose. I can't repressive your issue, all the tray cases pass on matter.

**Comment by lepture** [comment]
command `routes` is not available in 0.12.x.
