### ISSUE TITLE
Can't capture custom validator Exception

### ISSUE THREAD

**Issue by grillorafael** [pallets/flask#2621]
### Expected Behavior
`_Validator` throw a custom exception if it fails which I was expecting to capture through `@errorhandler`.

```python
_Validator = ???
class MyConverter(BaseConverter):
    def to_python(self, value):
        return _Validator.parsed(value)

    def to_url(self, value):
        return ','.join(value)

app.url_map.converters['my'] = MyConverter
```

### Actual Behavior

Causes Internal Server Error not going through my `500` handler.

### Environment

* Python version: 3.6
* Flask version: 0.12.2
* Werkzeug version: 0.14.1

**Comment by grillorafael** [comment]
```python
@app.errorhandler(500)
def internal_error(e):
    alert_request_error()
    return render_template("error.html", code=500, message="Oh no! Something went wrong.", title="Oh no!"), 500
```

The handler works if the exception is thrown inside the route handler.

**Comment by davidism** [comment]
Best solution for now is to make sure your converter doesn't raise an exception, or at least raises an `HTTPException` subclass.

**Comment by grillorafael** [comment]
Let me try now.

**Comment by grillorafael** [comment]
Works fine. Thanks!
