### ISSUE TITLE
Docs are inconsistent on what test_request_context() returns

### ISSUE THREAD

**Issue by anowlcalledjosh** [pallets/flask#2627]
Some of the docs say (afaict, correctly) that `app.test_request_context()` returns a `RequestContext`:

> The test_request_context method can create us a RequestContext:
>
> ```python
> >>> ctx = app.test_request_context('/?next=http://example.com/')
> ```

from http://flask.pocoo.org/docs/0.12/reqcontext/

However, the API reference says that `app.test_request_context()` returns "a WSGI environment":

> Creates a WSGI environment from the given values (see werkzeug.test.EnvironBuilder for more information, this function accepts the same arguments).

from http://flask.pocoo.org/docs/0.12/api/#flask.Flask.test_request_context

**Comment by Derrreks** [comment]
I believe the correct answer here is that it returns a `RequestContext` as far as I see from the code, making the docstring for this function incorrect as well.

In `test_request_context()`:
``` python
return self.request_context(builder.get_environ())
```

In `request_context()`:
``` python
return RequestContext(self, environ)
```

**Comment by davidism** [comment]
It returns a request context, which is usually immediately used for a `with` block to push it. If you can submit a PR making this consistent, that would be helpful.
