### ISSUE TITLE
Unique URLs and relative URLs

### ISSUE THREAD

**Issue by SergiyKolesnikov** [pallets/flask#2632]
In the documentation, under [Quick Start/Unique URLs](https://github.com/pallets/flask/blob/master/docs/quickstart.rst#unique-urls--redirection-behavior) it is stated: "This behavior allows relative URLs to continue working even if the trailing slash is omitted" It is unclear what the described behavior has to do with relative URLs and how it helps to keep them working. Please clarify.

**Comment by RyanSquared** [comment]
The documentation is missing context on what is considered a "relative" URL in this example. Consider the following:

This behavior allows relative URLs to continue working even if the trailing slash is omitted, consistent with how Apache and other servers work. If there is a slash at the end of the URL, as per `/projects/`, relative URLs (such as `<link rel="stylesheet" href="style.css">`) will resolve to `/projects/style.css`. However, URLs with no slash on the end, such as `/about`, will resolve to the slash closest to the end, in this example `/style.css`.

The phrase that I have left out, "Also, the URLs will stay unique, which helps search engines avoid indexing the same page twice.", I believe would be better fitted appended to the first paragraph of that section, as it directly relates only to the redirect for that single case.
