### ISSUE TITLE
flask.pocoo.org points to jinja2 docs

### ISSUE THREAD

**Issue by yprez** [pallets/flask#2639]
![screenshot from 2018-02-25 16-47-26](https://user-images.githubusercontent.com/667418/36642668-96910ce0-1a4b-11e8-958f-aa64e99b7113.png)

Pretty self explanatory :)

**Comment by ThiefMaster** [comment]
Looks fine for me. Which browser is that?

**Comment by yprez** [comment]
Checked in firefox and chrome on linux. Maybe a dns issue? It's on readthedocs, right?

**Comment by yprez** [comment]
![screenshot from 2018-02-25 16-51-45](https://user-images.githubusercontent.com/667418/36642702-460630e2-1a4c-11e8-97b9-e1b7a43fc8db.png)
This is on chrome

**Comment by ThiefMaster** [comment]
nope, not on RTD

```
[adrian@pluto:~]> host flask.pocoo.org
flask.pocoo.org has address 148.251.50.164
[adrian@pluto:~]> host 148.251.50.164
164.50.251.148.in-addr.arpa domain name pointer flow.srv.pocoo.org.
```

**Comment by yprez** [comment]
Ok, I get the same so not a dns issue... really weird

**Comment by ThiefMaster** [comment]
I'd try with curl/httpie to see what headers are actually being sent

**Comment by yprez** [comment]
curl returned the right page, so I did a hard refresh and it worked.
Probably a temporary bug because I hit it with two browsers, and I didn't have it cached before...
