### ISSUE TITLE
Url path params <int: matches only unsigned int

### ISSUE THREAD

**Issue by KromDaniel** [pallets/flask#2643]
I'm having this small issue where match route by type int matches actually unsigned int

---
### Expected Behavior

Doing a request with negative integer should match the route

```python
@app.route('/by_user/<int:user_id>', methods=["GET"])
def handle_user(user_id):
  # rest of the code
```

### Actual Behavior
when doing a GET request to the server, with the path `/by_user/-1` it won't match
when doing with unsigned int `/by_user/1` it works

### Environment

* Python version: Python 3.6.3
* Flask version: Flask 0.12.2

#### Note
I'm running the server via gunicorn, if it matters

Thanks a lot

**Comment by ThiefMaster** [comment]
I think unsigned int is much more common so changing this doesn't seem like a good idea. But you can easily do it yourself: Subclass `IntegerConverter` and set `regex = r'-?\d+'` on the class:

```python
class SignedIntConverter(IntegerConverter):
    regex = r'-?\d+'

app.url_map.converters['signed_int'] = SignedIntConverter
```

then use `<signed_int:user_id>` in your route.

**Comment by KromDaniel** [comment]
Hey, thanks for the answer.
wouldn't you expect that int would be also negative number?
From the docs it says it matches int, -80 is also an integer

**Comment by ThiefMaster** [comment]
I'd update the docs to mention it's a positive integer. People might be relying on the current behavior and the most common case for `<int:..>` are probably database IDs which are usually non-negative. And when using it for other things (like image sizes) suddenly accepting negative values could be even worse.

**Comment by davidism** [comment]
See pallets/werkzeug#729.

**Comment by KromDaniel** [comment]
@ThiefMaster 
All you are saying is right, but integer is an integer.
if someone sends a negative image size, i'd say he has bigger problems.

What would you expect, if for example you'd be writing c++ code and
```cpp
int number = -30; 
```
wouldn't be -30?

And for very reasonable reason I thought -1 should match an integer.

Another thing, even worse.
you said "People might be relying on the current behavior "
What if they are relying on the behavior I was expecting and they have no idea that -1 isn't integer by your point of view? I found it with some luck during development, could have gone with it to production easily.

Anyway, I see it as an issue, and you don't
since this is your library there's nothing much I can do

Thanks anyway
