### ISSUE TITLE
Broken link to flaskext_compat.py in all versions of the docs

### ISSUE THREAD

**Issue by glenwinters** [pallets/flask#2644]
### Expected Behavior

Each published version of the "Flask Extensions" docs page should have a valid link to `scripts/flaskext_compat.py` under the "Flask Before 0.8" section.

Links:
http://flask.pocoo.org/docs/0.10/extensions/  
http://flask.pocoo.org/docs/0.11/extensions/  
http://flask.pocoo.org/docs/0.12/extensions/  
http://flask.pocoo.org/docs/dev/extensions/

### Actual Behavior

Each version of the docs points to `scripts/flaskext_compat.py` on Flask's master branch on GitHub. Since that file was removed from the current master branch via https://github.com/pallets/flask/commit/715a9a3e7bd65421c36428ba9d4a1ee06b98bbc1, all of the links to this script are broken.

For example, the docs for the version 0.12 uses this URL, which results in a 404:
https://raw.githubusercontent.com/pallets/flask/master/scripts/flaskext_compat.py

Also, the master branch version of the docs still show how to use this script that's been removed:
https://github.com/pallets/flask/blob/master/docs/extensions.rst

### Environment

Viewing different versions of Flasks docs on flask.pocoo.org in Google Chrome 64 on Windows 10.

**Comment by ThiefMaster** [comment]
Maybe we should just remove that section from the docs and replace it with 
something saying old flask versions are obsolete and should not be used nor 
supported by extensions?

**Comment by glenwinters** [comment]
I see the PR to close this issue removed the docs section about `flaskext_compat.py`, but the old docs are still broken. Could at least the docs for the latest stable version 0.12 be updated with the correct link pointing to the file in that release?

Example link:
https://github.com/pallets/flask/blob/0.12.2/scripts/flaskext_compat.py

**Comment by ThiefMaster** [comment]
That's not possible without tagging a new release.

**Comment by glenwinters** [comment]
Ah, probably not worth it then. Thanks.
