### ISSUE TITLE
Flask.test_client() methods should support files argument

### ISSUE THREAD

**Issue by aparamon** [pallets/flask#2645]
Currently `Flask.test_client()` methods `get()`, `put()`, `post()` accept "data" argument but not "files" argument, which makes it incompatible with `requests`:
http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file

Making `Flask.test_client()` compatible with `requests` enables seamless transition between Flask unit and integration testing, e.g. via `pytest` fixtures.

A work-around via monkey-patching:
```python
orig_make_test_environ_builder = flask.testing.make_test_environ_builder
def make_test_environ_builder(*args, files=None, **kwargs):
    env = orig_make_test_environ_builder(*args, **kwargs)
    if files:
        env.files.update(files)
    return env
flask.testing.make_test_environ_builder = make_test_environ_builder
```

**Comment by davidism** [comment]
This can be added in Werkzeug. Please reopen there. https://github.com/pallets/werkzeug/issues/
