### ISSUE TITLE
CSRF session Token is missing(400 Bad Request)

### ISSUE THREAD

**Issue by guruganesh26** [pallets/flask#2655]
In our Flask web application we are facing 'CSRF Session Token is missing' only when morning first request. we have used the default session, csrf configuration not changed anything. cookie secret key only given.

We are using Nginx as our load balancer. We debugged the problem, For our HTML page Rquest cookies don't send 'session cookie', So we are Receiving  session cookie in 'Response Cookies'

The logic here used is if we not send session cookie, server returns session cookie in response as per our understanding.
So can anyone help why there is session cookie not received in response for first time of a day in a HTML page or is that cookie expired and due to that we are facing this problem?(Note: we are not using any cookie expiration time using default value)

### Environment

* Python version: 2.7.3
* Flask version:0.12
* Werkzeug version:0.11.15

**Comment by lepture** [comment]
Flask itself doesn't provide CSRF. You are asking in a wrong place.
