### ISSUE TITLE
Documentation is wrong at https://www.palletsprojects.com/p/flask/

### ISSUE THREAD

**Issue by jonassteinberg1** [pallets/flask#2656]
---

### Expected Behavior

Taken directly from https://www.palletsprojects.com/p/flask/

```
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    app.run()  # claim is that argument port=some_port is not needed
```

### Actual Behavior

Nothing happens.  Script executes, but flask web server never starts.

### Seems like

...this is required

```python
app.run(port=5000)
```

### Environment

* Python version: 3.6.4
* Flask version: 0.12.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
That's not required. I can't reproduce your issue, the example as shown works fine.

**Comment by jonassteinberg1** [comment]
Hm, must be my internals somewhere.  Thanks!
