### ISSUE TITLE
Flask test_client retaining lock on files, preventing os.remove() on Windows

### ISSUE THREAD

**Issue by andymantell** [pallets/flask#2659]
### Expected Behavior

Given the barest possible flask app (_See this repo for full example: https://github.com/andymantell/flask-test-client-sendfile-lock_)

```python
from flask import Flask


app = Flask(__name__)

if __name__ == "__main__":
    app.run()
```

And the following test script:

```python
import os
from app import app


test_client = app.test_client()

filename = 'static/test.txt'
with open(filename, 'w+') as file:
    file.write('Hello')

response = test_client.get('/static/test.txt')

response_data = response.data.decode('utf-8')
assert response_data == 'Hello'

os.remove(filename)  # This throws an exception on windows, claiming that the file is busy
```

I would expect that the file /static/test.txt will be created, requested from the test_client, and then removed again. And indeed this is what happens on Linux.

### Actual Behavior

On Windows, the `os.remove` line throws an exception saying that the file is busy. It appears as if something inside the test client is locking the file.

If I switch to `requests.get` and fetch /static/test.txt over http instead of through the test client, the error does not occur, the file is not locked, and Windows successfully deletes the file.

```pytb
(env) C:\projects\flask-test-client-sendfile-lock-master>python test.py
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    os.remove(filename)  # This throws an exception on windows, claiming
 that the file is busy
PermissionError: [WinError 32] The process cannot access the file because it is
being used by another process: 'static/test.txt'
```

### Environment
* Windows 7
* Python version: 3.4
* Flask version: 0.12
* Werkzeug version: 0.7

**Comment by davidism** [comment]
The example you've shown here doesn't pass the file to the test client at any time. It's not demonstrating an issue with Flask.

**Comment by andymantell** [comment]
> The example you've shown here doesn't pass the file to the test client at any time. It's not demonstrating an issue with Flask.

@davidism Not sure where this comment went, it arrived in my email but I can't find it here? 

At any rate, I think it is flask related? The file gets written to disk and then Flask reads it before sending it. When I hit a "real" flask app via `requests.get` the behaviour doesn't occur.

I've been thinking about this a bit and wondered - when does Flask actually close the file again? I can see it get opened inside `send_file` but without knowing more about Flask's internals I'm not sure where it gets closed.

Is there something extra that I need to call, to tear down something more? Perhaps this isn't a bug with Flask, and it's more that I'm using it wrong?

**Comment by davidism** [comment]
I deleted it because I realized the static route is what's loading it, not your code. You're still hitting the real app with the test client, the difference is the client not the app. Werkzeug closes open files after the request is over. This should be reported against Werkzeug, Flask isn't doing anything different here.

**Comment by andymantell** [comment]
@davidism Ah ok fair enough. I'll have a peep in werkzeug on Monday and see if I can work out what might be going on. Thanks very much
