### ISSUE TITLE
Allow wsgi files to specify the application instance in FLASK_APP

### ISSUE THREAD

**Issue by wgwz** [pallets/flask#2675]
I'm wondering if we can be slightly more permissive in the type of file we can use to specify the application instance. `.wsgi` seems to be a paradigm that it might sense to include. Look forward to hearing back on this!

### Expected Behavior
```
export FLASK_APP=/path/to/app.wsgi
flask shell
>>> working terminal yay! (i can import the sqla db object and do stuff)
```
### Actual Behavior

```
export FLASK_APP=/path/to/app.wsgi
flask shell
```
```
Traceback (most recent call last):
 ...
 ...
flask.cli.NoAppException: The file provided (/path/to/python.wsgi) does exist but is not a valid Python file.  This means that it cannot be used as application.  Please change the extension to .py
```
### Environment

* Python version: Python 3.5.2
* Flask version: Flask==0.12.2
* Werkzeug version: Werkzeug==0.14.1

**Comment by davidism** [comment]
`.wsgi` isn't a real extension, it's really a `.py` file. Python only recognizes `.py` files as importable. Other files can be read in, compiled, then evaluated; but not imported.

`flask` already detects `app.py` and `wsgi.py` automatically.

To handle other files, we'd need to either mess with `importlib` to make Python find and import other extensions, which I really don't think Flask should mess with. Or we'd need to tack on `read, compile, eval` to what is already a pretty complicated loading scheme.

**Comment by davidism** [comment]
I'd much rather people stop using the `.wsgi` extension. No idea what the history of that is, I think it's a filename Django decided to generate instead of `wsgi.py` for some reason.

**Comment by davidism** [comment]
Had a chat about this, appears to be an ancient holdover from when Apache CGI was in wide use. `mod_wsgi` kept the pattern even though it's not required, and everyone else followed suite. https://chat.stackoverflow.com/transcript/message/41855462#41855462

If you really want to keep the name, use a symlink to also name it `wsgi.py`.

**Comment by wgwz** [comment]
I indeed am working in system using `mod_wsgi`, I should have mentioned that sooner. I will go the symlink direction, thanks for asking around and for the suggestion!

**Comment by davidism** [comment]
mod_wsgi doesn't need the file extension to be .wsgi

**Comment by wgwz** [comment]
I apologize because I've let an internal constraint bubble up into the framework. This is clearly not the right place to handle the issue. I knew that we don't need to specify a `.wsgi` file, but I've been hesitant to make the change in the system. Either I'll work w the symlink or change the config to read from `.py`.
