### ISSUE TITLE
Incorrect endpoint name in fileuploads doc

### ISSUE THREAD

**Issue by MayankVachher** [pallets/flask#2678]
### Expected Behavior

http://flask.pocoo.org/docs/0.12/patterns/fileuploads/ should have the following code snippet:

``` file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            return redirect(url_for('upload_file',
                                    filename=filename))
```

### Actual Behavior

The doc instead has:

``` file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            return redirect(url_for('uploaded_file',
                                    filename=filename))
```

It's a quick fix. Just need to rename `url_for('uploaded_file', ` to `url_for('upload_file', `

### Environment

* Python version: Any
* Flask version: 0.12
* Werkzeug version: Any

**Comment by ThiefMaster** [comment]
So why not send a Pull Request for this? :)

**Comment by ThiefMaster** [comment]
Actually, I just checked again, and the code is correct. The redirect goes to an endpoint that lets you download the uploaded file.

**Comment by MayankVachher** [comment]
Ah okay. My bad. It's a bit further down. Didn't see that.
