### ISSUE TITLE
[New Feature] Flask init utility

### ISSUE THREAD

**Issue by DefCon-007** [pallets/flask#2683]
Every time we use flask there is some basic code we need to write and some directories we need to create. We can automate that particular cumbersome task by something like `flask init` which will let's say create an app.py file containing the basic imports statements, a basic hello world route, code to start the server on the default port, basic directories like a template, static etc. 
Basically something like Django's `django-admin startproject `.

**Comment by davidism** [comment]
There are plenty of projects that do this already, some better than others. Flask does not require any specific layout, there are many decisions that should be made and understood by the developer.
