### ISSUE TITLE
Suggest: support post json.dumps with unicode.

### ISSUE THREAD

**Issue by ahui132** [pallets/flask#2687]
I found that flask post not supports json.dumps with unicode. 

```
import request as 
r.post('http://localhost/test', json={'bar':'程序员'})
```
So I suggest that support unicode in `vim modles.py +458`:

`body = complexjson.dumps(json, ensure_ascii=True)`

**Comment by ThiefMaster** [comment]
Umm, what? Flask has no models.py, and the code you posted isn't even valid Python...
