### ISSUE TITLE
Cannot change default formatter

### ISSUE THREAD

**Issue by achanda** [pallets/flask#2704]
### Expected Behavior

I am trying to add an extra header to flask logs, code below. I expected that flask will log in the new format that I put in.

```python
from pomegranate.routes import app
import os

from flask import request
from flask.logging import Formatter, StreamHandler, DEBUG

class RequestFormatter(Formatter):
    def format(self, record):
        record.url = request.url
        record.remote_addr = request.remote_addr
        record.request_id = request.headers.get('X-Request-Id', '')
        return super().format(record)

formatter = RequestFormatter(
    '[%(asctime)s] %(request_id)s %(remote_addr)s %(url)s\n'
    '%(levelname)s %(module)s: %(message)s'
)

stream_handler = StreamHandler()
stream_handler.setLevel(DEBUG)
app.logger.addHandler(stream_handler)
for handler in app.logger.handlers:
    handler.setFormatter(formatter)

dev = int(os.getenv('FLASK_DEBUG', 0))

if __name__ == '__main__':
    host = '0.0.0.0' if dev == 1 else '127.0.0.1'
    app.run(host=host, port=8081, debug=True)
```

### Actual Behavior

Flask continues to use the default format.

### Environment

* Python version: `Python 3.6.1 :: Continuum Analytics, Inc.`
* Flask version: `0.12.2`
* Werkzeug version: `0.14.1`

**Comment by ThiefMaster** [comment]
General advice: Don't use `app.logger` for more complex apps. Instead, just use Python's logging module directly.

Also, keep in mind that `app.run()` is not suitable for production - so you should never have the `dev == 0` case ;)

**Comment by davidism** [comment]
The request logs are displayed by Werkzeug's dev server, through the `'werkzeug'` logger.

In Flask 1.0, `app.logger` will be a lot easier to use. In fact, it looks like you may be using a pattern from the dev docs right now.
