### ISSUE TITLE
Different app discovery behavior on commands run and shell 

### ISSUE THREAD

**Issue by rochacbruno** [pallets/flask#2706]
The commands `run` and `shell` are behaving differently to locate the `app`, I can send a PR but first I want to confirm if this is a problem or expected behavior.

### Expected Behavior

Assuming the tree

```bash
/topdir
|____/appdir
|_________/app.py 
```
then

```bash
export FLASK_APP=app.py
cd topdir
```

If you run

```bash
flask run
```

The command can find the `app` in the subfolder and run successfully

Expected the same to happen for `shell` 

```bash
cd topdir
flask shell
>>> 
```

### Actual Behavior

```bash
cd topdir
flask shell

# in 0.12.2
Error: The file/path provided (app.py) does not appear to exist.  Please verify the path is correct.  If app is not on PYTHONPATH, ensure the extension is .py

# n 0.13.dev
Error: Could not import "app"."

```

Looks like the `run` command is traversing the subfolders to locate an app while the `shell` command is not doing the same.

and the same applies for the new `routes` on master

```bash
$ cd topdir
$ flask routes                                                          
Usage: flask routes [OPTIONS]

Error: Could not import "app"."
```

### Environment

* Python version: 3.6.0
* Flask version: 0.12.2 & 0.13.dev (master branch)
* Werkzeug version: 0.14.1

**Comment by rochacbruno** [comment]
I just figured out that the behavior of app loading is the same for `run` just the exception behavior is not the same.

The `run` command seems to "run" an `app.py` but fails later on the first request it throws:

```
flask.cli.NoAppException
flask.cli.NoAppException: Could not import "app"."
```

So the expected behavior is to do the same exception catch in `run` command if `app` cannot be located and fail early in the command and not after first request.

**Comment by rochacbruno** [comment]
```
flask.cli.NoAppException
flask.cli.NoAppException: Could not import "app"."

Traceback (most recent call last)
File "/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py", line 325, in __call__
self._flush_bg_loading_exception()
File "/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py", line 313, in _flush_bg_loading_exception
reraise(*exc_info)
File "/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py", line 302, in _load_app
self._load_unlocked()
File "/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py", line 317, in _load_unlocked
self._app = rv = self.loader()
File "/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py", line 372, in load_app
app = locate_app(self, import_name, name)
File "/home/videos/flask_drops_repo/venv/lib/python3.6/site-packages/flask/cli.py", line 246, in locate_app
Open an interactive python shell in this frame'Could not import "{name}"."'.format(name=module_name)
flask.cli.NoAppException: Could not import "app"."
```

**Comment by davidism** [comment]
Because the app is `FLASK_APP=appdir/app.py`.

**Comment by rochacbruno** [comment]
@davidism I found the issue is when `--lazy-loader` is enabled, which is the default when `FLASK_DEBUG=1`

Now my only concern is that `run` `shell` and `routes` behave differently as `shell` and `routes` has no `lazy-loader` at least this behavior should be documented.

**Comment by davidism** [comment]
You're confusing the fact that the CLI will lazily load the module in order to show any import or syntax errors in the debugger and allow reloading in the face of such errors, with the fact that you've provided a path that's not correct.

**Comment by rochacbruno** [comment]
Exactly!

The issue that I am reporting is that `people can get confused` when running `flask run` and see `app is running` while it is not (because it will be lazily loaded` and then run `flask shell` and get immediate error.

@davidism maybe adding message?

insted of:

```bash
$ flask run                                                    
 * Serving Flask app "app.py"
```

In such case change to:

```
$ flask run 
 * Serving Flask app WARNING: "app.py" will be lazily loaded!!!

```

**Comment by rochacbruno** [comment]
```bash
$ flask run                                                                    
 * Serving Flask app "app.py"
 * Environment: development
 * Debug mode: on
 * Starting in lazy loader mode
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Starting in lazy loader mode
 * Debugger is active!
 * Debugger PIN: 189-281-652

```
