### ISSUE TITLE
flask.flash() not working

### ISSUE THREAD

**Issue by PyDever** [pallets/flask#2708]
whenever I try using flash, which everything says should display a message, I get nothing. 

```python
@app.route('/')
def home():
      flash('hello')
```
the above does not work. i have been using Flask for a while but never used this feature.

I checked stack exchange for answers already. Sorry to open an issue.

**Comment by davidism** [comment]
`get_flashed_messages()` retrieves the messages, as described in the docs: http://flask.pocoo.org/docs/0.12/patterns/flashing/ and http://flask.pocoo.org/docs/0.12/api/#flask.flash
