### ISSUE TITLE
Typo in fileuploads guide?

### ISSUE THREAD

**Issue by davejonesbkk** [pallets/flask#2712]
Just a typo here with the fileuploads guide I guess?

http://flask.pocoo.org/docs/0.12/patterns/fileuploads/

### Expected Behavior

When running the code from the quickstart guide for fileuploads the return statement should call 'upload_file' and not 'uploaded_file'

### Actual Behavior

The following error and recommendation is returned:

```pytb
 raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'uploaded_file' with values ['filename']. Did you mean 'upload_file' instead?
```

### Environment

* Python version: 3.5.1
* Flask version: 0.12.2
* Werkzeug version: 0.14.1

**Comment by KhaledTo** [comment]
Hi @davejonesbkk,

Did you write this function?
``` Python
@app.route('/uploads/<filename>')
def uploaded_file(filename):
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)
```

**Comment by davidism** [comment]
There are two views. `upload_file` handles showing the upload form and saving the file. `uploaded_file` handles serving the saved files.

**Comment by 0-coding** [comment]
Thanks, just for remind other beginners who read this document, paste how to modify the code here:
`@app.route('/', methods=['GET', 'POST'])
def upload_file():
......
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            return redirect(url_for('uploads.uploaded_file',
                                    filename=filename))       # 
    return '''
    <!doctype html>
    <title>Upload new File</title>
    <h1>Upload new File</h1>
    <form method=post enctype=multipart/form-data>
      <p><input type=file name=file>
         <input type=submit value=Upload>
    </form>
    '''`
