### ISSUE TITLE
Flask website has broken links

### ISSUE THREAD

**Issue by KeithCu** [pallets/flask#2714]
If you go to: http://flask.pocoo.org/

And you try to click on the microblog link or the twitter clone link, neither of them work because the URLs have changed.

**Comment by KeithCu** [comment]
Also, the PDF download link doesn't work.

**Comment by davidism** [comment]
I've already adressed these in the flask-docs repo, they will be removed in the next build.

**Comment by technolingo** [comment]
> flask-docs

Ironically, the flask-docs repo lacks docs on how to build PDF. Following the commands in ReadMe results in an error complaining there's no theme.
