### ISSUE TITLE
E-commerce

### ISSUE THREAD

**Issue by KeithCu** [pallets/flask#2715]
Flask is a very well-designed project to build many kinds of small to big websites, but you run into a problem if you want to do e-commerce.

I think you should consider porting this to Flask:
https://github.com/django-oscar/django-oscar

It seems to be the most popular Django e-commerce solution.

I'm not sure how much would have to be changed. Note you would need to port over some of the plugins like for Paypal, which is 1200 lines.

Maybe it is even possible to have some if Django and if Flask lines and keep it all in one codebase.

I realize this is not an easy bug, but maybe if enough people are interested, something could happen one day.

**Comment by lepture** [comment]
Not a bug of Flask. You can create an extension yourself.

**Comment by KeithCu** [comment]
I don't need it Flask-based. It's just a good framework to handle everything else I would need. It's very clean, powerful, etc.

I could put them on separate subdomains. I just have to figure out a way to share or link the user accounts, etc. Running Flask and Django is complicated and defeats the point and simplicity of Flask.
