### ISSUE TITLE
Port Issue

### ISSUE THREAD

**Issue by PyDever** [pallets/flask#2716]
Not sure if this is a bug or a system issue.

`(debug=True, port=3000)`

yet my app still runs on `5000` (default port)

**Comment by davidism** [comment]
You're presumably referring to passing arguments to `app.run`. But the `flask` command doesn't execute that function. Use the `--port` option: `flask run --port 3000`.

**Comment by PyDever** [comment]
thank you.

**Comment by PyDever** [comment]
i usually dont build with flask, i just do `make`
