### ISSUE TITLE
Where are all the issues?

### ISSUE THREAD

**Issue by westonplatter** [pallets/flask#2723]
Asking because I'm interested in contributed and would think there are more than 18 issues.

Feel free to close this.

**Comment by ThiefMaster** [comment]
uh yeah, I don't really see the point of this issue...

but here are more issues - they are closed though ;)

https://github.com/pallets/flask/issues?q=is%3Aissue+is%3Aclosed

**Comment by davidism** [comment]
I closed them all out over the past year. 😄

**Comment by davidism** [comment]
We still need a lot of help though. Most open issues are in the other Pallets libraries, especially Jinja and Werkzeug.
