### ISSUE TITLE
[help] flask 1.0 app run in click 

### ISSUE THREAD

**Issue by ngxlua** [pallets/flask#2725]
### Expected Behavior

When I try to upgrade to 1.0, my code is not compatible with 1.0 flask, how should I solve it?

```python
@cli.command("run", help="run server")
@click.option('--mode', help="Application running mode", default="dev")
def runserver(mode, daemon, reload, preload, spew):
    if mode == 'prod':
        """
        do something
        """

    app.run(host=app.config["HOST"], port=app.config["PORT"], use_reloader=True)

if __name__ == '__main__':
    sys.exit(cli.main())
```

### Actual Behavior

```pytb
manage.py:110: Warning: Silently ignoring app.run() because the application is run from the flask command line executable.  Consider putting app.run() behind an if __name__ == "__main__" guard to silence this warning.
  app.run(host=app.config["HOST"], port=app.config["PORT"], use_reloader=True)
```

### Environment

* Python version: 3.6.4
* Flask version: 1.0

**Comment by lepture** [comment]
Flask itself has a `run` command. Consider to remove your `run` command.

**Comment by ngxlua** [comment]
@lepture  can I override this method?

**Comment by lepture** [comment]
@ngxlua I think it is impossible to call `app.run` with `flask cmd`. Even when you rename it to other names. When run a cli with `flask ${cmd}`, it will set a `FLASK_RUN_FROM_CLI` flag, which will disable `app.run` function.

**Comment by lepture** [comment]
I didn't see the point of your usage. From what you provide, it seems Flask v1.0 has all the stuff you want.

**Comment by davidism** [comment]
If you want to configure your application, you should use the factory pattern. You can pass arguments to it using the `FLASK_APP` env var, or you can use the `app.env` property to get what `FLASK_ENV` was set to. You should use the standard `run` command to run your application with the dev server.

```python
# app.py
def create_app():
    app = Flask(__name__)
    if app.env == 'production':
        ...
    return app
```

```
FLASK_ENV=development flask run
```
