### ISSUE TITLE
New tuple requirement for response is restrictive

### ISSUE THREAD

**Issue by harveyslash** [pallets/flask#2726]
I had written a simple wrapper to take all the response primitives, and jsonify them before returning to client like so: 

```python
class JSONifyResponseWrapper(Response):
    default_mimetype = 'application/json'

    @classmethod
    def force_type(cls, rv, environ=None):
        try:
            rv = jsonify(rv)
        finally:
            return super(JSONifyResponseWrapper, cls).force_type(rv, environ)
```
Then i set app.response_class to the class above. 

However, in flask 1.0 , the routes are required to return a tuple. 
This means if I have a route like this: 

```python
@base_blueprint.route('', methods=['Post'])
def hello():
    a = {"hello":"world"} 
   return a
```

The client receives a valid json object. 

But if I do this: 

```python
@base_blueprint.route('', methods=['Post'])
def hello():
    a = [i for i in range(100)]
   return a
```
Flask will throw this error: 

> TypeError: The view function did not return a valid response tuple. The tuple must have the form (body, status, headers), (body, status), or (body, headers)`

**Comment by lepture** [comment]
That change is made a year ago. You need to wrap the response yourself. Before the change, Flask detect it in this way:

```py
if isinstance(rv, tuple)
```

After the change, it is:

```py
if isinstance(rv, (tuple, list))
```

So the list you returned is going to behave like this. It is the right response.

**Comment by ThiefMaster** [comment]
I don't think that's a solution. His goal is to apply a custom function on everything returned from a view function to convert it to JSON.

I think the solution here is to not override `force_type` but rather `finalize_request` or `make_response` of the Flask class.

**Comment by harveyslash** [comment]
I just tested returning a list like in my example in flask .12 and it works just fine.

**Comment by lepture** [comment]
Yes, it should work fine in 0.12. There is nothing wrong. What you need is a solution to get the same result as before. Try @ThiefMaster ‘s solution.

**Comment by harveyslash** [comment]
i have whipped up a hack that seems to work , but I would like to know if this is a correct solution. 
Also, It would be nice if i could override the ResponseWrapper on a blueprint basis instead of my entire app. 

```python

    def Wrapper(self, *rv): # relax tuple requirements , even accept none as return type. 
        return Flask.make_response(current_app, ('hello', 200)) # handle the return value in whatever way you want. 

    app.make_response = Wrapper 
```

**Comment by ThiefMaster** [comment]
No, don't monkeypatch. Subclass instead:

```python
class MyFlask(Flask):
    def make_response(self, rv):
        # do your stuff with rv
        return super(MyFlask, self).make_response(rv)
```

**Comment by harveyslash** [comment]
along the same thread, is there a way to have such overriding capability for blueprints also?

**Comment by ThiefMaster** [comment]
Blueprints do not have their own `make_response`, since they just add stuff to the app. But yes, you can subclass e.g. `Blueprint` or `BlueprintSetupState` as well..
