### ISSUE TITLE
Documentation search broken

### ISSUE THREAD

**Issue by lepture** [pallets/flask#2743]
## How to reproduce

1. Try search "request", it goes to this page: `http://flask.pocoo.org/docs/1.0/search/?q=request`
2. Click on the result, it will be 404

---

The urls built on the search page are wrong, for instance:

```
http://flask.pocoo.org/docs/1.0/search/api/?highlight=request#flask.request
```

Should be

```
http://flask.pocoo.org/docs/1.0/api/?highlight=request#flask.request
```

@davidism this should be fixed in the pallets themes.

**Comment by davidism** [comment]
This appears to be an issue with the `dirhtml` builder. Not sure exactly how to fix it.

**Comment by davidism** [comment]
This is due to sphinx-docs/sphinx#4295, which moved the documentation options from inline JS that generated the correct URL into a separate file that can't understand subdirectory pages.

I'll need to figure out how to override that, or pin at Sphinx < 1.7 until it's fixed.
