### ISSUE TITLE
Broken links on pypi

### ISSUE THREAD

**Issue by guillaumevincent** [pallets/flask#2750]
Hello,
on https://pypi.org/project/Flask/ `issue tracker` and `code` links in the left menu are pointing to `https://github.com/pallets/pallets-sphinx-themes/issues` not `https://github.com/pallets/flask/issues`.

![screenshot from 2018-05-02 09-00-17](https://user-images.githubusercontent.com/943762/39509638-44544f30-4de7-11e8-8a03-c750c072e151.png)

**Comment by davidism** [comment]
It's fixed in the next release.
