### ISSUE TITLE
functions added by after_request execute in reversed order

### ISSUE THREAD

**Issue by joshuaavalon** [pallets/flask#2757]
### Expected Behavior
Print in following order:

foo
bar

```python
def foo(response):
    print("foo")
    return response
def bar(response):
    print("bar")
    return response

app = Flask(__name__)
app.after_request(foo)
app.after_request(bar)
```

### Actual Behavior
Print in following order:

bar
foo

### Environment

* Python version: 3.6.5
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

This is very counter intuitive. Is there a reason to execute reversed order? It seems like it is reversed on purpose in `process_response` in `app.py`. The order actually matters. I found out this when I apply gzip and html minifier which gzip is apply first and the minifier is unable to read the data as string.

**Comment by davidism** [comment]
This is intentional. Imagine that you as an extension that does the gzip. You'd totally add this early, before setting up your tires and callbacks. If it were to execute first, none of your own callbacks could modify the response body, it would be zipped already.

**Comment by joshuaavalon** [comment]
@davidism How about mention it on documentation?
