### ISSUE TITLE
Flask in subpath doesn't work as expected

### ISSUE THREAD

**Issue by galuszkak** [pallets/flask#2759]
### Expected Behavior

Flask should work on subpath with proper url generation by `url_for`.
So url in example below should be: `/myapp/static/css/bootstrap.min.css`

```python
from flask import Flask
from flask.views import MethodView

class ListConsumer(MethodView):
    def get(self):
        return render_template('list.html')

app = Flask(name)
app.config['APPLICATION_ROOT'] = '/myapp'
app.add_url_rule('/', view_func=ListView.as_view('list_view'))

# list.html
# <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
```

### Actual Behavior

Actual generated URL is `/static/css/bootstrap.min.css` and this should be `/myapp/static/css/bootstrap.min.css`. Although this is when application just work.

If I add env SCRIPT_NAME=/myapp I get error: 
```
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 167, in handle_request
    listener.getsockname(), self.cfg)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 193, in create
    path_info = path_info.split(script_name, 1)[1]
IndexError: list index out of range
```

### Environment

* Python version: 3.6.4
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by galuszkak** [comment]
@davidism oh I forgot about this. This happens on gunicorn.

**Comment by davidism** [comment]
What I wrote above applies to gunicorn.

**Comment by galuszkak** [comment]
@davidism oh I see confusion. I don't want this in WSGI to mount in other path. I'm doing this in kong having (which is based on nginx) mounting this on `/myapp`

This locally works perfectly fine on `/` path. But after deployment on kong with forwarding headers it doesn't work correctly.

**Comment by davidism** [comment]
You need to apply `ProxyFix` middleware if you're setting `Forwarded` headers.

```python
from werkzeug.contrib.fixers import ProxyFix

app.wsgi_app = ProxyFix(app.wsgi_app)
```

**Comment by davidism** [comment]
See #3219 for another explanation of this that I wrote, might be a good start for a docs page.

**Comment by paulgb** [comment]
Des and I are working on this as part of the TS Open event.
