### ISSUE TITLE
url_for() breaks just before POSTing to a specific endpoint

### ISSUE THREAD

**Issue by Kangaroux** [pallets/flask#2762]
### The Problem

I have a few routes which are as follows:

```
api.auth -> /api/auth
api.user -> /api/user
         -> /api/user/<user_id>
```

Anytime I do a POST to `api.auth`, the variable rules for my routes break when I call `url_for`.

```python
# Prints `/api/user/1`
print(url_for("api.user", user_id=1))

# Login
client.post(url_for("api.auth"), json={
  "email": "test@test.com",
  "password": "password123"
})

# Prints `/api/user?user_id=1`
print(url_for("api.user", user_id=1))

# Logout
client.delete(url_for("api.auth"))

# Prints `/api/user/1`
print(url_for("api.user", user_id=1))
```

The URL lookups breaking are not a result of something in the `api.auth` views. If I call `url_for` in `post()` or `dispatch_request()` of my AuthAPI view class, it's already broken.

Calling `client.post(url_for("api.auth"), json={...})` multiple times does not undo the problem.

### Relevant Code

- The test that is failing: https://github.com/Kangaroux/Kanban/blob/master/tests/user/test_user.py#L75
- The test app and client: https://github.com/Kangaroux/Kanban/blob/master/tests/conftest.py#L39
- The full app factory: https://github.com/Kangaroux/Kanban/blob/master/config/app.py#L9

### Environment

* Python version: 3.6.5
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
I tried to take a look at your code, but it's such a tagle of indirection that I gave up. If you're having an issue with Flask (not your code), please create a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).

The only thing that seemed immediately suspicious was that you're doing

```python
with app.app_context():
    yield app

with app.test_client() as c:
    yield c
```

Which causes the contexts to persist. This is most likely not what you want. You should only push these contexts for the length of time during a test that you actually need persistent access to them.

**Comment by Kangaroux** [comment]
@davidism I removed the yield on the client and wrapped the login method with a `with client` statement, that fixed the issue. Thanks
