### ISSUE TITLE
[Regression] Test client's response.status_code is always 500 when an exception is raised

### ISSUE THREAD

**Issue by Depau** [pallets/flask#2767]
### Expected Behavior
What used to happen before, i.e. on

```python
raise NotFound()
```

the test client's response.status_code should be `404`.

### Actual Behavior

It's always `500`.

### Environment

See my failing Travis CI builds:
- https://travis-ci.org/poliedro-polimi/Crowdfunding-Backend
- One of the tests that fails because of this issue: [link](https://github.com/poliedro-polimi/Crowdfunding-Backend/blob/master/tests/test_views.py#L157)
- Code that makes it fail: [link](https://github.com/poliedro-polimi/Crowdfunding-Backend/blob/master/poliedro_donate/blueprints/donations.py#L60)

* Python version: >3.5, pypy3 (not tested on other versions)
* Flask version: 1.0.2 from pypi (worked as expected in 0.12.2)
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
I can't reproduce the issue. Please include a minimal example here to demonstrate the issue.

The following does not raise an assertion error:

```python
from werkzeug.exceptions import NotFound
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
    raise NotFound()

client = app.test_client()
response = client.get('/')
assert response.status_code == 404
```
