### ISSUE TITLE
Blueprint error handling with url_prefix and lang_code

### ISSUE THREAD

**Issue by ufo911** [pallets/flask#2780]
Please add error handlers to Blueprint (404 and others)
For multi language Site I had to write app error handlers and cookies and after requests with session and cookie and a bit mess in my code so may error handling inside blueprint is good idea 

Thanks

**Comment by davidism** [comment]
There are already blueprint error handlers.

**Comment by ufo911** [comment]
I need to handle page not found but it refers to app not blueprint and can you provide more clear examples or documentation on this ?  thanks

**Comment by ufo911** [comment]
@ThiefMaster 
thanks for answer ! https://stackoverflow.com/questions/49496761/two-language-flask-site-with-or-without-blueprints/49948870#49948870 My app example is this, I was trying to get multiple lang site for about 2-3 months and got that solution on my own (in documentation there are so little examples) now I am stuck on error handling, I can share full project with you to see (it is not big) I had to have after requests for cookie for lang and other little things to handle languages and it is bit tricky and not standard way to handle application problems I think..
can you tell me more about this ? 

> However, I think we should consider adding a way of registering an error handler for a base URL so you could do something like @app.errorhandler(NotFound, path='/api/')
