### ISSUE TITLE
Python flask threads does not close

### ISSUE THREAD

**Issue by sjd12** [pallets/flask#2794]
My python flask app runs using `nohup`. ie it is always live. I see that it creates a thread every time user submits from page. It is because flask.run is with `multithread=true`. But my problem is even after the processing is over, the thread doesn't seem to be closed. I'm checking this with the `ps -eLf |grep userid` command. where i see many threads still active long after the code execution is over. and it gets added when another submit is done. All threads are removed when the app itself is restarted.

What is the criteria for the thread to close without restarting the app?
is it because the memory not getting released?

```
app = Flask(__name__)
@app.route('/submit',methods = ['GET','POST'])
def submit():
    #obj1=class1()
    #obj2=class2(obj1)
    #obj3=class3(obj1)
    #refer objects
    #process data
    #done

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=4000, threaded=True, debug=False)
```

**Comment by davidism** [comment]
Don't use the dev server in production. It is not designed to be particularly resource efficient. That said, I can't reproduce the issue you describe, threads are joined after they finish their work.

**Comment by davidism** [comment]
I'm not sure what you mean by "its user base is limited", but glad you solved it.
