### ISSUE TITLE
Flask start new thread - RuntimeError: Working outside of request context

### ISSUE THREAD

**Issue by ryrithgithub** [pallets/flask#2812]
I am using flask to run my long process that already related to session which hold user id and other information. i try to use new thread with both following methods but still got error 'RuntimeError: Working outside of request context.'

Method 1

```
import threading
Thread(target=lambda: fn(**args)).start()
```

Method 2

```
import thread
thread.start_new_thread(fn, (), args)
```

**Comment by ThiefMaster** [comment]
Contexts are thread-local, so if you REALLY want to use threads (better use a celery worker to run it in a background process), provide all the data directly instead of accessing the proxies from your thread.
