### ISSUE TITLE
Tutorial fails with error

### ISSUE THREAD

**Issue by Nadav-Eyesight** [pallets/flask#2815]
### Expected Behavior

Following the steps documented in https://github.com/pallets/flask/tree/1.0.2/examples/tutorial results in a functioning website in http://127.0.0.1:5000

### Actual Behavior

Tell us what happens instead.

```pytb
(venv) Main@DESKTOP-4DUIS04 C:\Git\flask\examples\tutorial
$ flask run
 * Serving Flask app "flaskr" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 204-731-212
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [04/Jun/2018 11:35:09] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "c:\git\flask\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\git\flask\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "c:\git\flask\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\git\flask\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\git\flask\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\git\flask\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\git\flask\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\git\flask\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\git\flask\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\git\flask\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Git\flask\examples\tutorial\flaskr\blog.py", line 17, in index
    'SELECT p.id, title, body, created, author_id, username'
sqlite3.OperationalError: no such table: post
127.0.0.1 - - [04/Jun/2018 11:35:09] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 11:35:09] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 11:35:09] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 11:35:09] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 11:35:10] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 11:37:07] "GET / HTTP/1.1" 500 -
```

### Reproduction steps
I've tried this multiple times, using both Windows python and Ubuntu on WSL, same issues. I've made sure to both read the documentation from 1.0.2 and checkout 1.0.2 from the documentation. I have made sure not to have flask or flaskr installed on my actual environments in case that matters, only in venv.

### Environment

* Python version: 3.6
* Flask version: 1.0.2
* Werkzeug version: Don't know what that is. It is not mentioned in the tutorial.

**Comment by mozartilize** [comment]
there is error: post table was not created
check http://flask.pocoo.org/docs/1.0/tutorial/database/#create-the-tables

**Comment by davidism** [comment]
You didn't run init-db.

**Comment by Nadav-Eyesight** [comment]
Thank you for the quick reply. I wasn't aware that's a thing I need to do.
My way to this tutorial was:
1) Searching Google for what Flask is.
2) Reaching http://flask.pocoo.org/ .
3) Reaching the docs here: http://flask.pocoo.org/docs/1.0/ .
4) Reaching the tutorial here: http://flask.pocoo.org/docs/1.0/tutorial/#tutorial .
5) The tutorial directly links here: https://github.com/pallets/flask/tree/1.0.2/examples/tutorial

The example at https://github.com/pallets/flask/tree/1.0.2/examples/tutorial bears no mention of creating a table etc.
I suggest that any such necessary steps are added to https://github.com/pallets/flask/blob/1.0.2/examples/tutorial/README.rst

**Comment by davidism** [comment]
Read the tutorial, it's multiple pages in the docs, not just a link to code.

**Comment by Nadav-Eyesight** [comment]
What is the purpose of the text in https://github.com/pallets/flask/blob/1.0.2/examples/tutorial/README.rst then?

**Comment by NathanDrakeHat** [comment]
Run "flask init-db" before "flask run".
