### ISSUE TITLE
Traceback not flushed immediately 

### ISSUE THREAD

**Issue by Faboor** [pallets/flask#2819]
### Expected Behavior
When an error occurs and traceback is printed out, the stderr should be flushed.

File `app.py`:
```python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def err():
  return i_will_cause_an_error(" :'( ")

if __name__ == '__name__':
  app.run()
```
And then run it with `python app.py 2>out.txt` and connect to the server, e.g. using `curl http://localhost:5000/`

Here I'd expect to see the `127.0.0.1 - - [<date>] "GET / HTTP/1.1 500 -` and a full traceback for the `AttributeError` raised in the file `out.txt`

### Actual Behavior
Only `127.0.0.1 - - [<date>] "GET / HTTP/1.1 500 -` shows up in the `out.txt` file. Only when a new request is made the full traceback is flushed to the file, together with the new response log line.

### Environment
| | version|
| ------------- |:-------------:|
| Python | 3.5.2 |
| Flask | 1.0.2 |
| Werkzeug | 0.14.1 |

**Comment by davidism** [comment]
Are you sure you're not in debug mode?

**Comment by Faboor** [comment]
Sorry, my bad.. it actually is in `FLASK_ENV='development'`, but I'd still expect the traceback to be flushed immediately to stderr, rather than only with the next request (especially when in production environment it does that already).

Is this some particular feature of the debug mode that I've missed? What's the reasoning behind it?

**Comment by davidism** [comment]
Flask hold on to the request when there's an error in debug mode so that the debugger works as expected. This is intentional behavior.
