### ISSUE TITLE
Inconsistent behavior of `static_url_path`

### ISSUE THREAD

**Issue by dimmg** [pallets/flask#2820]
I've encountered a strange behavior when passing the `static_url_path` on Flask app initialization and on a already instantiated app.

Below examples are built based  on a structure as follows:
```
run.py
static
  |_main.css
```

### Case Study 1:

```
from flask import Flask

app = Flask(__name__, static_url_path='/media')


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True)
```

#### Expected Behavior

`main.css` file should be accessible on `/media/main.css`

#### Actual Behavior

`main.css` file is accessible on `/media/main.css` as it should be

### Case Study 2:

```
from flask import Flask

app = Flask(__name__)


if __name__ == '__main__':
    app.static_url_path = '/media'    

    app.run(host='0.0.0.0', port=8080, debug=True)

```

#### Expected Behavior

`main.css` file should be accessible on `/media/main.css`

#### Actual Behavior

`main.css` file is not accessible on `/media/main.css`, instead is accessible on default `static_url_path`

```pytb
127.0.0.1 - - [08/Jun/2018 17:11:48] "GET /media/main.css HTTP/1.1" 404 -
127.0.0.1 - - [08/Jun/2018 17:11:53] "GET /static/main.css HTTP/1.1" 200 -
```

### Environment

* Python version: 3.6.5
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
Writing to configuration attributes after init / config is not supported. This is true of pretty much all the configuration, not just `static_url_path`.

**Comment by dimmg** [comment]
Hmm, thanks for pointing that out, didn't know about this though.
It would be nice for this to be added to [Application Object API Docs](http://flask.pocoo.org/docs/1.0/api/). 

I think the ticket can be closed now.
