### ISSUE TITLE
Exceptions in before_request methods prevent later before_request methods from running

### ISSUE THREAD

**Issue by skylerberg** [pallets/flask#2821]
### Expected Behavior

All methods added with `@app.before_request` should be run.

```python
Paste a minimal example that causes the problem.
```

### Actual Behavior

If an exception occurs in a single `@app.before_request` method, all following `@app.before_request` methods will not run.

### Context

For a detailed example of this causing an issue, see https://github.com/GoogleCloudPlatform/flask-talisman/issues/22.

In summary, Flask-Talisman does setup in an `@app.before_request` method which is expected to be done by the time it runs an `@app.after_request` method. However, if an exception occurs in an `@app.before_request` method that runs  before Flask-Talisman's, and that exception is caught by an `@app.errorhandler`, then Flask-Talisman's `@app.after_request` method can be run without the setup work ever being done.

**Comment by davidism** [comment]
Changing Flask's behavior would be incorrect, as before request handlers are allowed to exit early and return a response (an exception is a response). This would just cause all the before handlers that expect earlier handlers to run to fail too.
