### ISSUE TITLE
Flask complains a .env file exists when not using python-dotenv, even though that .env is a directory

### ISSUE THREAD

**Issue by jaapz** [pallets/flask#2823]
I place my virtualenvs in a `.env` directory in my project directory. Flask 1.x sees this directory and thinks it might be a "dotenv" file (even though it is a directory).

### Expected Behavior

`flask` should ignore a `.env` directory when `python-dotenv` is not installed.

### Actual Behavior

`flask` says:

> * Tip: There are .env files present. Do "pip install python-dotenv" to use them.

### Environment

* Python version: 3.6.5
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by RonnyPfannschmidt** [comment]
#2668 introduced this - if you like you can just do a pr that switches it for isfile to sort this out, it would be a easy first contrib

https://github.com/theskumar/python-dotenv/blob/master/dotenv/main.py indicates that dotenv is also handling this incorrectly (exists everywhere)
