### ISSUE TITLE
Cannot fork Flask repository

### ISSUE THREAD

**Issue by gcrsaldanha** [pallets/flask#2830]
### Expected Behavior

When I click the "fork" button or go to https://github.com/pallets/flask/fork I should be able to choose the location where I want to fork the flask repository.

I am able to fork other repositories.

### Actual Behavior

1. If I click "Fork", the following dialog is loading forever:
![image](https://user-images.githubusercontent.com/8438821/41468312-f706538e-707f-11e8-80c3-15c56f067e2b.png)

2. If I go to "fork page" (https://github.com/pallets/flask/fork) I receive a HTTP 500 as following:
![image](https://user-images.githubusercontent.com/8438821/41468400-3eaa6eb4-7080-11e8-81ea-ddd71c5c330d.png)

### Environment

* Chrome version: 67.0.3396.87 (Official Build) (64-bit)

**Comment by ThiefMaster** [comment]
Not sure what this has to do with us... if you get a 500 error that's a problem with GitHub. Please contact their support.
