### ISSUE TITLE
First example in "Testing Flask Applications" doc fails

### ISSUE THREAD

**Issue by anthony-aylward** [pallets/flask#2831]
### Expected Behavior

I am attempting to follow the example in [http://flask.pocoo.org/docs/1.0/testing/](http://flask.pocoo.org/docs/1.0/testing/)

I expect to see all tests pass after these steps:
```
git clone https://github.com/pallets/flask.git
cd flask
git checkout 1.0.2
cd examples/tutorial
python3 -m venv venv
. venv/bin/activate
pip install -e .
pip install '.[test]'
pytest
pip install pytest
printf 'import os\nimport tempfile\n\nimport pytest\n\nfrom flaskr import flaskr\n' > tests/test_flaskr.py
pytest
```

### Actual Behavior

Instead, the result of the final pytest call is:

```pytb
======================= test session starts ========================
platform darwin -- Python 3.6.5, pytest-3.6.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/anthonyaylward/Documents/web-projects/flask/examples/tutorial, inifile: setup.cfg
collected 24 items / 1 errors

============================== ERRORS ==============================
______________ ERROR collecting tests/test_flaskr.py _______________
ImportError while importing test module '/Users/anthonyaylward/Documents/web-projects/flask/examples/tutorial/tests/test_flaskr.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_flaskr.py:6: in <module>
    from flaskr import flaskr
E   ImportError: cannot import name 'flaskr'
!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!
===================== 1 error in 0.52 seconds ======================
```

### Environment

* Python version: 3.6.5
* Flask version: 1.0.2

**Comment by anthony-aylward** [comment]
1. The import statements are sufficient to reproduce the issue, so I don't think any other code is necessary for the example

2. For context, the import statements are from a code example in the section "The Testing Skeleton" of the article "Testing Flask Applications" at [http://flask.pocoo.org/docs/1.0/testing/](http://flask.pocoo.org/docs/1.0/testing/), which reads:

```
import os
import tempfile

import pytest

from flaskr import flaskr


@pytest.fixture
def client():
    db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
    flaskr.app.config['TESTING'] = True
    client = flaskr.app.test_client()

    with flaskr.app.app_context():
        flaskr.init_db()

    yield client

    os.close(db_fd)
    os.unlink(flaskr.app.config['DATABASE'])
```

While it seems clear that this example `test_flaskr.py` is not compatible with the current version of the `flaskr` example, I am not sure how I need to change it to correct the error. If possible, I'd like to learn how to create a working `test_flaskr.py` so I can follow along with the testing article.

**Comment by greyli** [comment]
It seems that the testing doc is not updated with the new flaskr tutorial. In this case, I recommend you to use the old code before the doc is updated:
```
$ git checkout 0.12.4
```

**Comment by greyli** [comment]
You are welcome. Please close this issue.

**Comment by keithmendozasr** [comment]
Did an issue get created to update the tutorial?

**Comment by davidism** [comment]
The tutorial is up to date. Many pages in the docs, including this one, need updating. There's nothing *wrong* with what the page says, it just references an old code example.

**Comment by davidism** [comment]
If you'd like to create an issue or a PR, go for it!

**Comment by isdanni** [comment]
Just reproduced the error. I will update the testing doc and create a pull request!
