### ISSUE TITLE
Documentation for testing need to be updated

### ISSUE THREAD

**Issue by greyli** [pallets/flask#2833]
The chapter [Testing Flask Applications](http://flask.pocoo.org/docs/1.0/testing)  in docs need to be updated to compatible with the rewritten flaskr application.

See #2831 for more info.

**Comment by liabifano** [comment]
Is there someone working on it? Can I work / help on it?

**Comment by davidism** [comment]
I'm happy to review PRs on this.

**Comment by kx-chen** [comment]
@davidism Would be glad to pick this up. 

Should I simplify the examples as the tests are much larger now? (i.e: not go through every single one, but just the important ones/similar ones from the old doc)

**Comment by Pradhvan** [comment]
Is anyone working on this? I recently picked up Flask and pytest would love to help out in the issue :smile:

**Comment by SarpongAbasimi** [comment]
I personally think that the documentation related to testing a flask application is too complicated and not beginner friendly. I would love to rewrite this an make it a bit simple for beginners.

**Comment by Lyla-Fischer** [comment]
I opened an issue outlining something that I thought was confusing, that surfaced during testing (specifically the app.test_request_context method). https://github.com/pallets/flask/issues/3311
