### ISSUE TITLE
Examples wiki?

### ISSUE THREAD

**Issue by Nadav-Ruskin** [pallets/flask#2852]
Hello again,

I've made a flask [example project](https://github.com/Nadav-Ruskin/configsite) for simple uses because I feel those are scarce. I wonder if you would consider making a wiki page or something for flask where example projects can be stored?

**Comment by davidism** [comment]
We don't currently have something like that. I may add it at some point when porting the extension / project lists to Pallets, but don't currently have any plans for it.
