### ISSUE TITLE
@property for configuration objects?

### ISSUE THREAD

**Issue by dougthor42** [pallets/flask#2853]
Are properties supported for configuration objects? It doesn't look like it.

Being able to use `@property` on configuration objects could simplify some of the more complex configurations out there:

```python
# Without @property
class BaseConfig(object)
    NAME = "a"
    HELLO = "Hello, " + NAME

class ProdConfig(BaseConfig):
    NAME = "b"
    HELLO = "Hello, " + NAME           # repeated code! Makes me 😢

# With @property
class BaseConfig(object)
    NAME = "a"

    @property
    def HELLO(self)
        return "Hello, " + self.NAME

class ProdConfig(BaseConfig):
    NAME = "b"                         # Don't need to define HELLO again, yay!
```

### Expected Behavior

It seems like it would be useful to be able to use properties when defining config variables using `from_object`:

```python
# my_config.py
class BaseConfig(object):
    NAME = "Terry Gilliam"

    @property
    def HELLO(self):
        return "Hello, " + self.NAME

class ProdConfig(BaseConfig):
     NAME = "Monty Python"
```

```python
# example.py
from flask import Flask
app = Flask(__name__)
app.config.from_object('my_config.ProdConfig')
print(app.config['HELLO'])
# "Hello, Monty Python"
```

### Actual Behavior

Because the config class is not actually instantiated, the `HELLO` property is simply a `<property object at 0x...>` rather than `Hello, Terry Gilliam` or `Hello, Monty Python`.

```python
# example.py
from flask import Flask
app = Flask(__name__)
app.config.from_object('my_config.ProdConfig')
print(app.config['HELLO'])
# <property object at 0x000001EC5404D458>
```

### Environment

* Python version: 3.5.2
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

### Possible Resolution

If configuration objects are called `ProdConfig()`, then the property resolves. **I'm sure that there's a reason for not instantiating the config object, but I thought it would be worth a discussion.** I'm sure it's security related.

The fix might look like:

```python
# flask.config.Config.from_object
...
for key in dir(obj):
    if key.isupper():
        self[key] = getattr(obj, key)
        # only instantiate the object if a property is detected
        if isinstance(self[key], type(property())):
            self[key] = getattr(obj(), key)

**Comment by davidism** [comment]
The method is `from_object`, it doesn't care what the object is. However, properties only evaluate on instances, you're passing a class. You'd need to do `from_object(ProdConfig())`. Or do `prod = ProdConfig()` in your config file and pass *that* name to `from_object`. I don't think Flask needs to do anything special here.

**Comment by dougthor42** [comment]
So if I'm using a string for the object name (because it's generated from env vars and various other things), I have to run:

```python
my_obj_instance = werkzeug.utils.import_string('my_config.ProdConfig')()
app.config.from_object(my_obj_instance)
```

Just seems kinda silly is all. Feels like that a lot of people wouldn't think they'd have to do that to get properties to work. Nothing in the [main docs](http://flask.pocoo.org/docs/1.0/config/#development-production) nor the [`from_object` docstring](http://flask.pocoo.org/docs/1.0/api/#flask.Config.from_object) state that the class is not instantiated. Perhaps the only bug here is adding that to the docs?

If that's the only solution, I'd be happy to open a PR to update the docs to reflect this.

**Comment by davidism** [comment]
Nothing in `from_object` says anything special about classes in general, other than they're a common namespace alternative to a module object. It's completely generic to all objects. It even says that the object is used directly, nothing is done to it.

> an actual object reference: that object is used directly

**Comment by davidism** [comment]
If you think the docs can be clearer about this, a PR would be fine though.
