### ISSUE TITLE
request.full_path shouldn't contain a trailing ? if there was none in the URL

### ISSUE THREAD

**Issue by ExplodingCabbage** [pallets/flask#2867]
### Expected Behavior

If I make a request to `http://localhost:5000/foo`, then `request.full_path` should contain `/foo`.

### Actual Behavior

It contains `/foo?`

### Minimal example

Save this to a file and run it:

```
from flask import Flask, request
app = Flask(__name__)
@app.route('/test')
def test():
    return request.full_path
app.run()
```

Then go to http://localhost:5000/test

You will see `/test?` in the browser.

### Environment

* Python version: 3.6.1
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
This would be an issue against Werkzeug, but I'm inclined to leave the behavior as is. You can subclass Request and override that behavior if you want.
