### ISSUE TITLE
Flask reloader problems in development mode using Docker

### ISSUE THREAD

**Issue by angadkalra** [pallets/flask#2869]
### Expected Behavior

In development mode, flask should detect changes in my files and reload the debugger successfully. 

### Actual Behavior

It outputs to terminal: "Detected change in /flask/flaskr/api.py, reloading" then never reloads.

### Environment

* Python version: 3.6.2
* Flask version: 1.0.2

**Comment by davidism** [comment]
The reloader is part of Werkzeug. Whether it runs in Docker shouldn't affect its ability to reload. How do you know it's not reloading? You'll need to provide a Minimal, Complete, and Verifiable example demonstrating that's it's an issue with Werkzeug for us to do anything.

**Comment by zakariaboualaid** [comment]
@angadkalra I have the exact same issue as you described it. Do you remember how you fixed it?

**Comment by zakariaboualaid** [comment]
I fixed my problem, my setup has Flask-SocketIO in it. If you have the same issue and you are running Docker, then probably you are running the app using Flask command. Instead use
`python3 run.py` and it will work.

This thread helped to figure it out : https://github.com/miguelgrinberg/Flask-SocketIO/issues/817
