### ISSUE TITLE
https://flask.pocoo.org responds 400

### ISSUE THREAD

**Issue by devhero** [pallets/flask#2879]
The website https://flask.pocoo.org response 400, it's practically down.

**Comment by RonnyPfannschmidt** [comment]
pocoo.org itself seems to be down and responding that way

**Comment by greyli** [comment]
Mybe it's network issue in your region. Please try to visit http://flask.pocoo.org.

**Comment by devhero** [comment]
I've understand, it's an issue with TLS, while http://flask.pocoo.org is accessible, the (http secure protocol) https://flask.pocoo.org is not. Maybe the TLS certificate is expired?
I use the Https Everywhere plugin with my browsers, so I was fallen in this problem.

**Comment by davidism** [comment]
The site has never been set up for HTTPS, and I don't plan to since we're slowly moving away from pocoo.org anyway.

**Comment by a2x** [comment]
Please provide flask website over https

**Comment by devhero** [comment]
Ok. Could it be a good idea to move/copy the documentation to the pallets website?

**Comment by davidism** [comment]
As I said, we're slowly moving away from pocoo.org.
