### ISSUE TITLE
app.logger can't work

### ISSUE THREAD

**Issue by BeanWei** [pallets/flask#2884]
the vscode error  info:
 `"message": "E1101:Method 'logger' has no 'info' member",`
`"message": "E1101:Method 'logger' has no 'addHandler' member",`

but I can still run it `python test.py`, I don't know why and i get nothing in app.log.

***test.py***
```python
from flask import Flask

import logging
from logging.handlers import RotatingFileHandler

app = Flask(__name__)

hand_log = RotatingFileHandler('app.log')
hand_log.setFormatter(logging.Formatter(
    '[%(asctime)s]%(levelname)s: %(message)s'))
hand_log.setLevel(logging.INFO)
app.logger.addHandler(hand_log)

@app.route('/')
def foo():
    app.logger.info('welcome')
    return "hello"

app.run(debug=True)
```

### Environment

* Python version: 3.6.2
* Flask version: 1.0.2

**Comment by greyli** [comment]
You also need to set log level for `app.logger`:
```py
app.logger.setLevel(logging.INFO)
```

**Comment by BeanWei** [comment]
Thank you. You are right. But I still don't know the reason that the VSCode show the error `Method 'logger' has no 'addHandler' member"`

**Comment by greyli** [comment]
IMO, VSCode's code inspector is not smart enough. You can just ignore it and it has nothing to do with Flask.
