### ISSUE TITLE
No post information from firefox form

### ISSUE THREAD

**Issue by felixletsplayYT** [pallets/flask#2888]
### Expected Behavior

Flask gets POST Data from form in every browser via request.form

```python
@app.route('/backend', methods=['GET', 'POST'])
def backend():
    print(request.form)
```

### Actual Behavior
In Chrome it gets the information of the form correctly, in firefox not.
(I have not tested more browser)

The echoed request.form in firefox
```pytb
ImmutableMultiDict([])
```

### Environment

* Python version: Python 3.6.5
* Flask version: 1.0.2 
* Werkzeug version: 0.14.1

**Comment by ThiefMaster** [comment]
Sounds a lot like there is no POST data. Impossible to answer without seeing what is actually being sent (use your browser's developer tools) but I highly doubt this is a problem with flask.

**Comment by felixletsplayYT** [comment]
I will have a look there.
What I have forgotten to write is that there is another user on stackoverflow who has the same problem.
https://stackoverflow.com/a/36082762

**Comment by felixletsplayYT** [comment]
Sorry, problem isn't there after changing a few things in my code.
I do not know why the dictionary is filled now, but it looks like it works for me.
