### ISSUE TITLE
Broken RTD builds/links

### ISSUE THREAD

**Issue by lafrech** [pallets/flask#2890]
Apparently there's been some changes in the way the docs are generated on RTD.

I see there's a rtd branch with a commit (https://github.com/pallets/flask/commit/86acd842cebe0174870d399228bb25c1693ae8f3) dedicated to RTD adding `docs/requirements.txt`.

The build on this branch passes but there's that warning on top of the page: 

> Warning: This is an old version. The latest stable version is Version 1.0.2..

The other builds (1.0.2 and master) fail: https://readthedocs.org/projects/flask/builds/.

I suppose the config was change in RTD to look for that `requirements.txt` file that only appears in rtd branch.

As a user, I don't mind the warning, but I'm building a documentation for a lib using Flask with this intersphinx mapping:

```py
intersphinx_mapping = {
    'flask': ('http://flask.readthedocs.io/en/latest/', None),
}
```

 I get an error due to the failed build as `http://flask.readthedocs.io/en/latest/objects.inv` is not fetchable.

Should I use `https://flask.readthedocs.io/en/rtd/objects.inv` or is this temporary?

Thanks.

**Comment by davidism** [comment]
RTD is not up yet
