### ISSUE TITLE
request.get_json(force=True) not working as expected

### ISSUE THREAD

**Issue by a2x** [pallets/flask#2891]
requesting **without** {'Content-Type': 'application/json'} 
request.get_json(force=True) returns nothing (not as expected)
request.get_json(force=False) returns None (not as expected)

requesting **with** {'Content-Type': 'application/json'} 
request.get_json(force=True) returns the JSON parsed to dict
request.get_json(force=False) returns the JSON parsed to dict

Expected behavior: 
Shouldn't request.get_json(force=True) like mentioned in the docs "Ignore the mimetype and always try to parse JSON."?

thx, and keep up the great work

**Comment by KeatingSmith** [comment]
I try it, but it works fine.

can you show some details? like what you post and how do it.

**Comment by greyli** [comment]
Please provide [a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve).
