### ISSUE TITLE
Environment variables in .env file not refreshing after re-running application

### ISSUE THREAD

**Issue by davidhariri** [pallets/flask#2893]
### Expected Behavior

Flask sets/overrides environment variables specified in .env each time `flask run` is run.

### Actual Behavior

Flask is unaware that the .env file in my project directory has changed and does not refresh it's own environment variables.

### Environment

* Pipenv
* Python version: 3.6.5
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by ThiefMaster** [comment]
The file is read once on startup, and that's it. Are you sure you aren't overriding the value in your code?
Please provide a minimal testcase to reproduce your problem.

**Comment by davidhariri** [comment]
@ThiefMaster It's possible it's an issue with pipenv? All i'm doing is changing the `FLASK_ENV` variable in my .env file from `production` to `development` and re-running `flask run`, but not seeing the application change modes.

**Comment by davidhariri** [comment]
Solved it! [As documented here](https://github.com/pypa/pipenv/blob/master/docs/advanced.rst) `PIPENV_DONT_LOAD_ENV=1 pipenv shell` solved my issue. It must be `pipenv` trying to optimistically cache `.env` or perhaps a race condition between pipenv and flask-cli?
