### ISSUE TITLE
To much logic in view url generation

### ISSUE THREAD

**Issue by riklaunim** [pallets/flask#2895]
After some use-cases of flask microservices I find `url_for` helper to be quite problematic to use. 

If I use an app via two subdomains then by default `url_for` will use the request host name to generate the full url. As I want to use only one subdomain (`app.sitename.com/view/` and not `api.sitename.com/view/`; and without subdomain routing setup) for the urls I have to handle this - `_external=False` and do it on my own.

If I use a custom flask command to execute some code that reverses an url then it needs the app context and `SERVER_NAME` even when it's explicitely `_external=False` (as url_adapter won't be present without `SERVER_NAME` set).  `SERVER_NAME`  has other usages and causes side effects (and breaks health checks on kubernetes deployment if set globally).

So there is a lot of magic going on in reversing view name to an url. There should be path-only equivalent for `url_for` to avoid all those requirements if absolute urls aren't needed.

**Comment by davidism** [comment]
Closing due to lack of information. If you'd like to report a bug, please use the issue template and address one behavior at a time.
