### ISSUE TITLE
Spyder not showing output 

### ISSUE THREAD

**Issue by 25pritesh** [pallets/flask#2896]
### Expected Behavior

Starting the server should show all the information lines:

```
* Serving Flask app "testfla" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 222-285-885
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

```python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def index():
   return 'This is the homepage'

if __name__ == '__main__':
   app.run(debug=True
```

### Actual Behavior

Only the following line is displayed when starting the server:

```
* Restarting with stat
```

### Environment

* Python version: 3.6
* Flask version: 1.0.2
* Werkzeug version:

Anaconda 5.2, Spyder 3.1

**Comment by 25pritesh** [comment]
On Running the sample code in Anaconda 5.2 with Spyder 3.1. Spyder console is not generating URL port number. Console is showing only below results and nothing
* Restarting with stat

**Comment by davidism** [comment]
I can't reproduce this. I created an environment, installed Spyder and Flask, created an `app.py` file with the basic app, and ran it. All lines were output.

Flask and Werkzeug are not doing anything in particular with console output, so I don't think they're likely to be the cause at this time. There are occasional issues with running the reloader in IPython, but my test worked fine. If you're having an issue with Spyder, you should probably bring this issue up with them.
