### ISSUE TITLE
Flask `test_client` could not find endpoints registred from namesapces

### ISSUE THREAD

**Issue by flask-pro** [pallets/flask#2906]
[Flask `test_client` could not find endpoints registred from namesapces](https://github.com/noirbizarre/flask-restplus/issues/402)
I get this problem too.
What resolve this? Or it's bug?

**Comment by davidism** [comment]
Closing due to lack of information. If you want to report a bug, please create a thorough bug report as described in the issue template. Also, this appears to be an issue with Flask-RestPlus, not Flask.

**Comment by flask-pro** [comment]
I'm not using Flask-RestPlus.

**Comment by ThiefMaster** [comment]
You linked to an issue about flaks-restplus - please provide your own minimal code if you have a problem that is similar but unrelated to that library.
