### ISSUE TITLE
Remove MongoKit page from "Patterns for Flask" docs section

### ISSUE THREAD

**Issue by igortg** [pallets/flask#2907]
I was just starting a little project with Flask + Mongo + Python3. 

Since the only reference to Mongo in the official docs is the "MongoKit in Flask" page, I went straight to install and create my schema using MongoKit. Just to find out that this lib is not updated since 2015 and has no support for recent versions of PyMongo.

Shouldn't we remove that from the docs?

**Comment by greyli** [comment]
Maybe we can rewrite it with MongoEngine/Flask-MongoEngine.

**Comment by igortg** [comment]
I'm going to to draft a 1st version #hacktoberfest
