### ISSUE TITLE
Double slashed urls are routed erroneously 

### ISSUE THREAD

**Issue by ostefano** [pallets/flask#2909]
This simple flask app has one resource routed:

```
from flask import Flask
app = Flask(__name__)
 
@app.route("/test.html")
def index():
    return "Hello World!"
 
if __name__ == "__main__":
    app.run(host='0.0.0.0', port=4000)
```

While the following returns 200 
```
http://127.0.0.1/test.html
```

And the following (correctly) returns 404:
```
http://127.0.0.1/asd/test.html
```

The following returns 200 and output `Hello World!` while it shouldn't:
```
http://127.0.0.1//asd/test.html
```

### Environment

* Python version: 2.7.15
* Flask version: 0.12.2 (but tested also 1.0.2)
* Werkzeug version: 0.12.2 (but tested also 0.14.1)

**Comment by lepture** [comment]
This is a werkzeug issue. It may be fixed by https://github.com/pallets/werkzeug/pull/1286
