### ISSUE TITLE
Inappropriate/offensive language in code

### ISSUE THREAD

**Issue by a-d3v** [pallets/flask#2919]
During a review of the code, I have encountered several terms that could offend some people:
- **19x** `master` (a term that could be associated with slavery and thus offend black people)
- **1x** `dumb`  (an extremely offensive word by itself)

Also, I found out that in the code, word `white` is mentioned **14 times**, whilst the word `black` is mentioned only **3 times**. I think this is a quite serious issue as the usage of words clearly indicates discrimination based on color (basically racism).

I'd love to see those issues fixed as soon as possible.

**Comment by ThiefMaster** [comment]
Please make meaningful contributions instead. Also, considering that your account was created today I strongly believe you're a troll.
