### ISSUE TITLE
Click==7.0 incompatibles with Flask 1.0.2

### ISSUE THREAD

**Issue by uwevil** [pallets/flask#2931]
I can not run Flask commands with Click 7.0 which is released the last week. When I replace it with the version 6.7, it works fine.

### Environment
* OS: Windows 10
* Python version: 3.6.4
* Flask version: 1.0.2
* Werkzeug version: 0.14

```
astroid==2.0.4
beautifulsoup4==4.6.0
click==6.7
cloudpickle==0.5.6
colorama==0.3.9
coverage==4.5.1
doit==0.31.1
Flask==1.0.2
gunicorn==19.9.0
isort==4.3.4
itsdangerous==0.24
Jinja2==2.10
lazy-object-proxy==1.3.1
MarkupSafe==1.0
mccabe==0.6.1
nose==1.3.7
nosexcover==1.0.11
pycryptodome==3.4.7
pylint==2.1.0
pymongo==3.7.1
PyYAML==3.12
six==1.11.0
typed-ast==1.1.0
urllib3==1.22
Werkzeug==0.14.1
wrapt==1.10.11
 

(env) flask clean_db
[2018-10-03 16:34:13,364 INFO] Running ...

```

If I install Click==7.0, my error is:
```

(env) flask clean_db
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try "flask --help" for help.
 
Error: No such command "clean_db".
```

**Comment by greyli** [comment]
Please provide the related code and the error traceback.

**Comment by davidism** [comment]
Python 2.6 is not supported by any of our projects at the versions you've listed.

**Comment by uwevil** [comment]
My bad, my python version is 3.6.4

**Comment by uwevil** [comment]
Curiously, when I test in my mac, it works fine. I will provide my error on my Win 10 as soon as possible.

**Comment by uwevil** [comment]
With my chance, I found the problem: if my command contains "_", Click (7.0) didn't work. But when I change my commande by removing "_", it works fine.
