### ISSUE TITLE
load_dotenv returns true even if no file exists

### ISSUE THREAD

**Issue by lec00q** [pallets/flask#2937]
### Expected Behavior

If no file is loaded/exists, `flask.cli.load_dotenv` should return False.

### Actual Behavior

This code:

```python
from flask import Flask
from flask.cli import load_dotenv

app = Flask(__name__)
result = load_dotenv('not-exist')
assert result
```

does not fail.

### Environment

* Python version: 3.5.5
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by greyli** [comment]
IMO, it's a default behavior of  `python-dotenv`:
```py
>>> from dotenv import load_dotenv
>>> load_dotenv('nothing')
>>> True
```
[Source](https://github.com/pallets/flask/blob/master/flask/cli.py#L600)

**Comment by jacquerie** [comment]
> it's a default behavior of `python-dotenv`:

That's true, but the docstring promises a different thing: https://github.com/pallets/flask/blob/d7eea1b49a5ea67dd9f39b9fa0a823466433f486/flask/cli.py#L587

**Comment by lec00q** [comment]
I was in fact referring to that promise. As a side note, I think that it also make sense, but this is just a personal opinion.

**Comment by greyli** [comment]
Maybe we can change this line to: `True` if a file was loaded and `path` is None.
