### ISSUE TITLE
Trouble with function send_file and range

### ISSUE THREAD

**Issue by PavelProkhorov** [pallets/flask#2943]
Hi! 

Why function send_file don't support Range header in request?
I send request with next header: Range: bytes=0-10.

 this is part of my code: 
 return send_file(file, attachment_filename=filename, conditional=True)

 But flask application return status code 200 instead 206. 

---

### Expected Behavior
status code = 206

### Actual Behavior
status code = 200

### Environment

* Python version: 3.5.3
* Flask version: 1.0.2
* Werkzeug version:

**Comment by IgnasiBosch** [comment]
Hi @PavelProkhorov I'm getting a 206 response code.
Could you provide more detailed procedure?

$ curl http://127.0.0.1:5000 -i -H "Range: bytes=0-10"
HTTP/1.0 206 PARTIAL CONTENT
Content-Length: 11
Content-Type: text/plain; charset=utf-8
Accept-Ranges: bytes

Python 3.5
Flask==1.0.2
Werkzeug==0.14.1

**Comment by PavelProkhorov** [comment]
Hi @IgnasiBosch 
curl http://127.0.0.1:5000/api/v1/video/test.mp4 -i -H "Range: bytes=0-10"

HTTP/1.0 200 OK
Content-Type: video/mp4
Cache-Control: max-age=43200, public
Expires: Tue, 16 Oct 2018 19:54:05 GMT
Date: Tue, 16 Oct 2018 07:54:05 GMT
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Connection: close
Server: Werkzeug/0.14.1 Python/3.5.3

This is my code, I download video from FTP and send:
`
@blueprint.route('/api/v1/video/<filename>')
def get_video(filename):
    with ftplib.FTP(ip, login, password, timeout=timeout) as ftp:
        output = io.BytesIO()
        ftp.retrbinary("RETR {}".format(filename), lambda data: output.write(data))
        output.seek(0)
    return send_file(output, attachment_filename=filename, conditional=True)
`

**Comment by IgnasiBosch** [comment]
Hi again @PavelProkhorov, 
just guessing, what you are trying to do has slight streaming flavor, isn't?. I wouldn't say this is the best approach as it will download from the ftp the entire file, each time! If you use a common file instead (downloading from the ftp just the first time to a temporary folder, cached or whatever) Partial content should work properly. 
Eventhough I'll take a look if there are any other constrain regarding request a range size of a bytesIO

**Comment by PavelProkhorov** [comment]
@IgnasiBosch 
Yes, you're see through me. I'm going to use Redis for cache. 

I found this code and it works fine. 
```
def send_file_partial(file, filename):
    """
    Simple wrapper around send_file which handles HTTP 206 Partial Content
    :param file - io.BytesIO object
    :param filename 
    :return - flask response object
    """
    range_header = request.headers.get('Range', None)
    if not range_header:
        return send_file(file, attachment_filename=filename, conditional=True)

    size = sys.getsizeof(file)
    byte1, byte2 = 0, None

    m = re.search('(\d+)-(\d*)', range_header)
    g = m.groups()

    if g[0]:
        byte1 = int(g[0])
    if g[1]:
        byte2 = int(g[1])

    length = size - byte1
    if byte2 is not None:
        length = byte2 - byte1 + 1

    file.seek(byte1)
    data = file.read(length)

    rv = Response(data,
                  206,
                  mimetype=mimetypes.guess_type(filename)[0],
                  direct_passthrough=True)
    rv.headers.add('Content-Range', 'bytes {0}-{1}/{2}'.format(byte1, byte1 + length - 1, size))
    rv.headers.add('Accept-Ranges', 'bytes')
    return rv
```
But this issue still open for me.

**Comment by IgnasiBosch** [comment]
@PavelProkhorov 
I must be missing some detail or I didn't get you

Controller:
```
@app.route('/api/v1/video/<filename>')
def get_video(filename):
    file = "./{}".format(filename)
    return send_file(file, attachment_filename=filename, conditional=True)
```

Request:
`curl http://127.0.0.1:5000/api/v1/video/sample.mp4 -i -H "Range: bytes=0-10"`

Response:
```
HTTP/1.0 206 PARTIAL CONTENT
Content-Length: 11
Content-Type: video/mp4
Last-Modified: Tue, 16 Oct 2018 18:41:33 GMT
Cache-Control: max-age=43200, public
Expires: Wed, 17 Oct 2018 06:44:40 GMT
ETag: "1539715293.906835-7338852-2705001102"
Date: Tue, 16 Oct 2018 18:44:40 GMT
Accept-Ranges: bytes
Content-Range: bytes 0-10/7338852
Server: Werkzeug/0.14.1 Python/3.5.3`
```


```
Flask==1.0.2
```

**Comment by PavelProkhorov** [comment]
@IgnasiBosch hi!

I don't use cached/saved file. I load it from ftp to io.BytesIO. 
Do you try get 206 code responce with io.BytesIO object and function send_file?

**Comment by IgnasiBosch** [comment]
Hi @PavelProkhorov 
Could you try this when you have a chance?
https://github.com/IgnasiBosch/flask/commit/4798133092c2a906405f88cd2b21ac43198fb6d6

**Comment by PavelProkhorov** [comment]
Hi! 
Thank you, I'm going to try this fix.
