### ISSUE TITLE
Review Flask-MailboxValidator extension for listing

### ISSUE THREAD

**Issue by MailboxValidator** [pallets/flask#2947]
Dear Flask Team,

MailboxValidator had introduced a new Flask extension that can help Flask users to validate email in various purpose. We would like to submit this extension for listing in the Flask Extension Registry.

Extension Name: Flask_MailboxValidator
PYPI link: https://pypi.org/project/flask-MailboxValidator/ 
Version: 1.0.1
Maintainer: MailboxValidator <support@mailboxvalidator.com>
Repository: https://github.com/MailboxValidator/Flask_MailboxValidator
License: MIT
Documentation link: https://flask-mailboxvalidator.readthedocs.io/en/latest/

Thank You.

**Comment by davidism** [comment]
Extensions are added by submitting a pr to the https://github.com/pallets/flask-website repo. Note that I'm not currently deploying new versions of that site (I'm working towards a new process), but please submit a PR anyway so I can keep track. Thank you!

**Comment by MailboxValidator** [comment]
OK, I have created the PR. Thanks!
