### ISSUE TITLE
Documentation "Testing Flask Applications" should show client teardown

### ISSUE THREAD

**Issue by ncraike** [pallets/flask#2949]
The `flask.testing` `FlaskClient` has clean-up which only happens if you use the test client in a `with` block:

```python
class FlaskClient(Client):

    # ...

    def __exit__(self, exc_type, exc_value, tb):
        self.preserve_context = False

        # on exit we want to clean up earlier.  Normally the request context
        # stays preserved until the next request in the same thread comes
        # in.  See RequestGlobals.push() for the general behavior.
        top = _request_ctx_stack.top
        if top is not None and top.preserved:
            top.pop()
```

This is described in the API documentation for [`app.test_client()`](http://flask.pocoo.org/docs/0.12/api/#flask.Flask.test_client), but isn't mentioned in the [Testing Flask Applications](http://flask.pocoo.org/docs/1.0/testing/) chapter of the documentation, and the "testing skeleton" code doesn't use `test_client()` in a `with` block:

```python
@pytest.fixture
def client():
    db_fd, flaskr.app.config['DATABASE'] = tempfile.mkstemp()
    flaskr.app.config['TESTING'] = True
    client = flaskr.app.test_client()

    with flaskr.app.app_context():
        flaskr.init_db()

    yield client
```

The [Testing Flask Applications](http://flask.pocoo.org/docs/1.0/testing/) chapter should demonstrate using the test client in _some way_ which does teardown.

I raise this because I used the skeleton code as basis for a `pytest` fixture, and I _believe_ I've run into intermittent test failure issues which are caused by request context leaking between tests.

**Comment by Albert-Guan** [comment]
Hi! I just start using flask and I am working on this issue. I want to test if my changes work, so I follow the 
[http://flask.pocoo.org/docs/1.0/testing/](url)
But in this line: `from flaskr import flaskr` it fails. 
I didn't see a **flaskr** under **flaskr module** in the **examples/tutorial directory. Is there any way to to test the codes?

**Comment by davidism** [comment]
The testing docs are not in sync with the tutorial right now. The tutorial itself includes a part on testing, so refer to that for now.

**Comment by Albert-Guan** [comment]
Should I create a new issue to update the testing docs? And this issue can also be fixed in the updated test docs.  I think it is not worth to fixing this issue here because the testing docs, at least this part needs to be changed sometime in the future.

**Comment by chirgjn** [comment]
👋 @davidism would like to pick this issue up and update the docs if It's not done already

**Comment by Jessicalau93** [comment]
#2949
