### ISSUE TITLE
Serial port give access denied when running flask in debug

### ISSUE THREAD

**Issue by diogorolo** [pallets/flask#2951]
### Expected Behavior

This snippet should open a serial port and start flask in debug mode.

```python
from flask import Flask
import serial 

ser = serial.Serial('\\\\.\\COM3',9600)
app = Flask(__name__)

app.run(debug=True)
```

### Actual Behavior

An exception is thrown saying that the serial port is in use.
This only happens if debug=True is present.
It works as expected if I only have app.run()

### Environment

* Python version:  3.6.5
* Flask version: 1.0.2'

**Comment by ThiefMaster** [comment]
You open the port (and thus lock it), then the reloader kicks in and starts the instance of your app that will actually serve requests, but since the port is already open it cannot open it as well.

Instead, connect from `before_first_request` or even open it in each request that needs it.

**Comment by diogorolo** [comment]
Thanks, that was it.
Setting use_reloader=False also fixes the issue.
