### ISSUE TITLE
Examples page

### ISSUE THREAD

**Issue by Jonesn11** [pallets/flask#2972]
On the examples page: http://flask.pocoo.org/community/poweredby/
many links are dead.
I think this prevents newcomers from being awe-inspired by what one can do with flask.

**Comment by davidism** [comment]
That website is in a separate repo, https://github.com/pallets/flask-website. If you'd like to submit a PR that removes sites that are down, that would be fine, but I'm not sure when I'll be able to redeploy it.

Eventually the resources on that site will be moved to https://github.com/pallets/website, where hopefully it's easier to organize and maintain.
