### ISSUE TITLE
Hot Reloader Causing Re-initialization Issues after Exception

### ISSUE THREAD

**Issue by cancan101** [pallets/flask#2980]
I am running flask dev server using the `flask` command. If an exception is thrown (such as syntax error) and then fixed. The next reload fails with some sort of issues having to due with attempting to reinitialize extensions. For example I get the following error from flask-admin (though depending on order of imports I get similar errors from other extensions):
```
AssertionError: A name collision occurred between blueprints <flask.blueprints.Blueprint object at 0x1118b96d8> and <flask.blueprints.Blueprint object at 0x1042880b8>. Both share the same name "admin". Blueprints that are created on the fly need unique names.
```
I don't think this is the same issue as https://github.com/pallets/flask/issues/2423 as I can trigger the problem with non syntax error (ie a name error a module scope).

### Environment

* Python version:
`3.7`

* Flask version:
`flask==1.0.2`

* Werkzeug version:
`werkzeug==0.14.1`

**Comment by ThiefMaster** [comment]
Please show a minimal piece of code reproducing this issue.
