### ISSUE TITLE
HTTPException handler catches non-error exceptions like RequestRedirect

### ISSUE THREAD

**Issue by taion** [pallets/flask#2984]
This is related to https://github.com/pallets/flask/issues/2841, but the emphasis is different.

### Expected Behavior

Non-error exceptions should not be caught by registered error handlers.

```python
app.register_error_handler(HTTPException, my_error_handler)

@app.route('/path-with-slash/')
def my_route():
    return '', 204
```

Attempting to visit `/path-with-slash` should redirect to `/path-with-slash/`, without invoking `my_error_handler`.

### Actual Behavior

As the `RequestRedirect` raised internally in Werkzeug is a subclass of `HTTPException`, `my_error_handler` will get called. This is unexpected because no error has occurred, and the only appropriate way to handle this case is to add boilerplate to re-raise any Werkzeug `RoutingException`s.

### Environment

* Python version: 3.7.0
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by taion** [comment]
The most straightforward fix would be to add a hard-coded exception to not handle `RoutingException` instances with the error handling logic in Flask. `RequestRedirect` instances are not errors.

**Comment by davidism** [comment]
I'm not clear how this is different than #2841.

**Comment by taion** [comment]
The difference is that the `NotFound` coming from routing is (1) actually an error and (2) is indistinguishable from a `NotFound` raised within the app. Additionally, a generic error handler that preserves the error code will still work.

None of those are true for a `RequestRedirect` raised internally by Werkzeug's routing logic. It's (1) not an error and (2) trivially distinguishable from other errors, as it extends `RoutingException`. Additionally, error handlers for generic `HTTPException`s will do something wrong here, as it's insufficient to just preserve `error.code` – one must preserve the `Location` header from the baked-in response as well, which requires reaching more deeply into the internals of the exception class.

**Comment by taion** [comment]
The issue here is that no error handler should catch instances of `RequestRedirect`, because they're not errors. The use of `RequestRedirect` is an internal implementation detail of Werkzeug. `RequestRedirect` in fact does not even show up in `exceptions.default_exceptions` in Werkzeug.

This is different from e.g. `NotFound`, in that `NotFound` is an HTTP error class, and a default exception class.

**Comment by ThiefMaster** [comment]
could we add an option either when registering error handlers or in `app.config` on whether HTTPException or even Exception error handlers catch http exceptions?

**Comment by taion** [comment]
These are the differences:

1. `RequestRedirect` is not part of `exceptions.default_exceptions`
1. One cannot normally install an error handler on status code 301; if `werkzeug.exceptions` added a `MovedPermanently` exception (with code 301), then an error handler on code 301 would, in the current implementation, not catch a `RequestRedirect`
1. `RequestRedirect` can be generally distinguished from other `HTTPException`s because it implements `RoutingException`, which is explicitly flagged in Werkzeug as a set of "special exceptions"
1. `RequestRedirect` is not semantically an error

**Comment by ThiefMaster** [comment]
> I don't think there's a difference between NotFound and RequestRedirect

Not sure - I think it's not too uncommon to register an error handler for http errors to show prettier error pages (github-unicorn-from-hell style ;)). But even I was a bit surprised when I got my error page for a 3xx! Ths workaround is super easy, but for someone less experienced with Flask I can imagine it's indeed pretty confusing.

**Comment by davidism** [comment]
Which is why it's marked as a documentation issue.

**Comment by davidism** [comment]
The problem with special casing `RoutingExcpetion` is that as soon as someone *does* want to adjust how their redirects work, they can't.

**Comment by taion** [comment]
I disagree with that statement.

For example, returning `flask.redirect` does not in general raise a `RequestRedirect`, so one cannot use error handlers on `RequestRedirect` to implement custom request behavior in the first place.

If one wishes to customize Werkzeug's routing logic, the correct way to handle that would be to do so in the router, rather than by using what should be the app's error handling logic.
