### ISSUE TITLE
Improper digest_method

### ISSUE THREAD

**Issue by travisreed-wf** [pallets/flask#2985]
### Expected Behavior
Flask should be able to read session data

### Actual Behavior
with itsdangerous >= 1.0.0 flask cannot read session data if the session data was written by itsdangerous < 1.0.0

```
Session: <SecureCookieSession {}>
```

`itsdangerous.exc.BadTimeSignature` is being raised and then caught [here](https://github.com/pallets/flask/blob/master/flask/sessions.py#L345)

itsdangerous is [allowed](https://github.com/pallets/flask/blob/master/setup.py#L39) to bump major versions

itsdangerous [recently changed](https://github.com/pallets/itsdangerous/commit/24ff6764b67d1e05ba71bbcdba006119324464fd#diff-e4eb329834da3d36278b1b7d943b3bc9R11)  its digest_method

[This digest method is now wrong](https://github.com/pallets/flask/blob/master/flask/sessions.py#L313)

### Environment

* Python version: Python 2.7.6
* Flask version: 0.10.1
* Werkzeug version: 0.14.1
* itsdangerous version: 1.1.0

**Comment by ThiefMaster** [comment]
itsdangerous 1.1.0 reverts the change and keeps compatibility with sessions from both 1.0 and older.
