### ISSUE TITLE
Flask doesn't auto-escape files not ending in html, htm, xml, xhtml

### ISSUE THREAD

**Issue by ColdHeat** [pallets/flask#2989]
```
    def select_jinja_autoescape(self, filename):
        """Returns ``True`` if autoescaping should be active for the given
        template name. If no template name is given, returns `True`.

        .. versionadded:: 0.5
        """
        if filename is None:
            return True
        return filename.endswith(('.html', '.htm', '.xml', '.xhtml'))
```

This seems odd. Why not just autoescape all file extensions. Or at least include `.j2` and `.jinja2`?

**Comment by davidism** [comment]
Because not all file extensions need HTML escaping, and there are no standard file extensions for Jinja. From Jinja's docs: "A Jinja template doesn't need to have a specific extension: .html , .xml , or any other extension is just fine."

You can override this method if you would like to autoescape a different set of files.

**Comment by ColdHeat** [comment]
There may be no accepted standard file extension to the pallets but users are definitely using extensions that aren't going to be escaped but rendered to the browser. 

Why not just include values that users are using? In what context of flask are people using render_template or render_template_string not expecting that the content will be escaped? 

This is quite a serious gotcha especially if someone decides to use an extension that is used elsewhere (Ansible for j2).

**Comment by ThiefMaster** [comment]
Ansible might use `.j2`, but I've rarely seen it in the flask world. All flask examples and tutorials i know use `.html`

**Comment by ColdHeat** [comment]
I mean this was the second result on Google: https://github.com/alex-leonhardt/flask-blog/blob/master/templates/post.html.j2

And if a user is curious and decides to search what others are using as file extensions it shows that others are using `.j2`. And it isn't clear that this causes them to be trivially vulnerable to XSS. 

Perhaps state in the documentation that `.html` is the correct template extension?

**Comment by thphd** [comment]
was infuriated by this setting when a security researcher notified me about XSS in my site.

should at least warn users on the first page of the documentation.

**Comment by thphd** [comment]
the solution is to subclass Flask and replace the method with your own extensions.
