### ISSUE TITLE
How to get a handle_request method for just handle one request

### ISSUE THREAD

**Issue by liudonghua123** [pallets/flask#2995]
### Expected Behavior

I tried to write a flask builder for now, and from the exist HTTPServer example https://github.com/liudonghua123/now-builders/blob/master/packages/now-python/now_handler.py, I should get a `handle_request` method executed when a new incoming request arrived.
But after driving into the acturally code, I could not found such a method. Some code may be add into `flask` and `werkzeug` both.

```python
import json
import requests
from __NOW_HANDLER_FILENAME import app
import _thread


def now_handler(event, context):
    _thread.start_new_thread(app.handle_request, ())
    payload = json.loads(event['body'])
    path = payload['path']
    headers = payload['headers']
    method = payload['method']
    
    res = requests.request(method, 'http://0.0.0.0:3000' + path, headers=headers)

    return {
        'statusCode': res.status_code,
        'headers': dict(res.headers),
        'body': res.text
    }


```

The __NOW_HANDLER_FILENAME file contents may like this
```python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'
```

### Actual Behavior

The `handle_request` or like method does not exist.

### Environment

* Python version: 3.7.0
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
It looks like "Now" is a serverless platform, you should take a look at Flask-Lambda and Flask-Zappa for examples of how others solved this.

From the example, it's not clear you'd need to actually start the server just to use requests to hit it, you can just use `app.test_client()` to simulate a request and get a response.

**Comment by liudonghua123** [comment]
@davidism, @frostming Thanks for you quickly replay, it really help me a lot. Thanks 👍 .

**Comment by liudonghua123** [comment]
Now, I wrote a flask builder for now on https://github.com/zeit/now-builders/pull/26.
