### ISSUE TITLE
Online documentation correction (Standalone WSGI Containers)

### ISSUE THREAD

**Issue by jefmud** [pallets/flask#3000]
Tiny correction to the documentation on GEvent as a WSGI standalone container.

http://flask.pocoo.org/docs/1.0/deploying/wsgi-standalone/#gevent

```python
from gevent.wsgi import WSGIServer # incorrect
from gevent.pywsgi import WSGIServer # correct
from yourapplication import app

http_server = WSGIServer(('', 5000), app)
http_server.serve_forever()
```

Thanks for all the hard work!
Jeff

**Comment by davidism** [comment]
Thanks, please submit a PR against 1.0-maintenance so we can fix this.

**Comment by jefmud** [comment]
Thank you, will do that shortly.
