### ISSUE TITLE
Default help messages for Flask CLI use inconsistent tenses (in English)

### ISSUE THREAD

**Issue by chardbury** [pallets/flask#3005]
### Expected Behavior

Help texts for commands (and options) should consistently use either the imperative or present tense, not a mixture of both. This has no impact on the functional behaviours of the CLI, just a minor UX error.

### Actual Behavior

Executing `flask --help` gives:

```
[... snip ...]

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  routes           Show the routes for the app.
  run              Runs a development server.
  shell            Runs a shell in the app context.
```

Note that `run` and `shell` are using present tense whereas `routes`, `--version` and `--help` are using the imperative.

### Environment

* Python version: 3.7.0
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by greyli** [comment]
@davidism I can help to update this if necessary, which tense should we use?

**Comment by davidism** [comment]
"Run a development server."

**Comment by GrugLife** [comment]
@davidism Does this still need work?

**Comment by davidism** [comment]
There is a PR linked above your comment.

**Comment by GrugLife** [comment]
Derp on my part.  I'll work on #3011
