### ISSUE TITLE
How can I achieve this structure?

### ISSUE THREAD

**Issue by acodercat** [pallets/flask#3006]
### Expected Behavior

How can I achieve this structure?
<img width="249" alt="wx20181128-172947 2x" src="https://user-images.githubusercontent.com/16076835/49143545-37844900-f336-11e8-80b3-4b22f77ad754.png">

### Environment

* Python version:3.7
* Flask version:1.0.3
* Werkzeug version:

**Comment by ThiefMaster** [comment]
I would start by creating those folders/and files... ;)

There is no scaffolding tool or something like that for Flask.
