### ISSUE TITLE
Requests stop being processed when basic auth is expected but not provided

### ISSUE THREAD

**Issue by sajohn2** [pallets/flask#3010]
### Expected Behavior

Steps to reproducing the problem:
1. Make a request that provides any basic auth
2. Make a request without basic auth
3. Make a request that provides any basic auth (this request is not being processed)

I would expect the server to continue processing requests.

```python
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route('/')
@app.route('/api')
def api():
    auth = request.authorization
    if not auth:
        return jsonify({'status': 'NO AUTH'})
    return jsonify({'status': 'GOT AUTH'})
```

### Actual Behavior

The server seems to hang on request 3.

### Environment

* Python version: 3.6.6
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

Full environment info:
MacOS 10.13.6
Python 3.6.6 (Anaconda)

All packages:
```text
aniso8601==4.0.1
Click==7.0
Flask==1.0.2
Flask-RESTful==0.3.6
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
pytz==2018.7
six==1.11.0
Werkzeug==0.14.1
```

**Comment by davidism** [comment]
I can't reproduce your issue. I made three requests as described and the server did not hang.

```python
import requests

print(requests.get("http://127.0.0.1:5000/", auth=("user", "pass")).text)
print(requests.get("http://127.0.0.1:5000/").text)
print(requests.get("http://127.0.0.1:5000/", auth=("user", "pass")).text)
```

**Comment by sajohn2** [comment]
This was happening when switching from Chrome to Postman. It looks like there are reports of similar issues with Chrome and its unrelated to the code itself. Running in threaded mode seems to fix the problem. Still not my favorite fix.

https://stackoverflow.com/questions/42519629/flask-not-processing-other-http-requests-after-chrome-browser-accesses-the-web-s
https://github.com/pallets/flask/issues/2169

**Comment by davidism** [comment]
Threaded mode is the default.
