### ISSUE TITLE
Request multiple files - New update old syntax does not work

### ISSUE THREAD

**Issue by HenryVijan** [pallets/flask#3016]
Hi

I have form(Form) which contains

```
<form method="POST" enctype="multipart/form-data" action="{{ url_for('xxx') }}">
  <input type="file" name="MultipleFileUpload" multiple="">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />     
  <input type="submit" value="add">
</form>
```

It should upload multiple files but it does not.

Python code
```
ob = request.files.getlist("MultipleFileUpload[]")
for x in ob:
     etc..
```
This was my old code which works perfectly

I presume it was caused by update

so I change it code to: 

`ob = request.files.getlist("MultipleFileUpload")`

`ob = request.files.to_dict()`

None of them works

It just upload 1 file or none

* Python version: 2.7.12 64-bit
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by ThiefMaster** [comment]
Why do you have `[]` there? You should remove that. Browsers do not add `[]` for multi-value fields; it's just some JS frameworks adding this to make PHP users happy...

**Comment by HenryVijan** [comment]
Thanks,
but it does not work.
Used same code(html) + 
`print request.files`

I tried to upload 1.png, 2.png, 3.png
 
127.0.0.1 - - [06/Dec/2018 12:10:54] "POST /xxx/test HTTP/1.1" 200 -
ImmutableMultiDict([('file', <FileStorage: u'3.png' ('image/png')>)])

it just show 1file

**Comment by ThiefMaster** [comment]
your html form uses `name="file"` and not what you posted so that's the dict key as well...
