### ISSUE TITLE
Flask==1.0.2 is not compatible with python-env

### ISSUE THREAD

**Issue by sakshi094** [pallets/flask#3027]

**Comment by sakshi094** [comment]
I am getting one issue related to dotenv and the tracebacks are when i start server i get something 

D:\wamp64\www\projects\Digital\blacklist-changes\gitclonerepo\blacklist-manager>python dev.py Traceback (most recent call last):   File "dev.py", line 23, in <module>     app.run(host='127.0.0.1', debug=True, port=port)   File "D:\wamp64\www\projects\Digital\blacklist-changes\gitclonerepo\blacklist-manager\env1\lib\site-packages\flask\app.py", line 910, in run     cli.load_dotenv()   File "D:\wamp64\www\projects\Digital\blacklist-changes\gitclonerepo\blacklist-manager\env1\lib\site-packages\flask\cli.py", line 600, in load_dotenv     path = dotenv.find_dotenv(name, usecwd=True) AttributeError: module 'dotenv' has no attribute 'find_dotenv' 

so i even found out the issue that is 
i am using python-env==1.0.0 with that it seems Flask==0.12 or lower version works.
but  i want to use flask  Flask==1.0.2 or higher version and when i do so i get that error.
 and when i use python-dotenv in place of python-env it works fine
i need to use python-env with much higher version of flask say Flask==1.0.2 or anthing greater.

**Comment by RonnyPfannschmidt** [comment]
`python-env` is a random dead package using the same module name as `python-dotenv`
