### ISSUE TITLE
request.path doesn't include request.script_root when running under a subdirectory

### ISSUE THREAD

**Issue by ColdHeat** [pallets/flask#3032]
I have an application which can be configured to run under a subdomain/domain or a subdirectory. This is controlled by setting `APPLICATION_ROOT` to a value other than `/`. 

Some of my decorators use `request.path` to determine where to redirect the user after logging in. However, when running under a subdirectory, `request.path` does not include `request.script_root` and the user could get redirected somewhere they shouldn't. Using `request.url` creates full URLs when we should only need relative ones. 

Based on [docs](http://flask.pocoo.org/docs/1.0/api/?highlight=script_root#flask.Request.url_root) it is intentional that `request.path` doesn't include `request.script_root`.

Ultimately because my application has a plugin interface and I don't want to deviate too much from Flask documentation, what is the optimal way to get this behavior to be consistent between deployment strategies? 

 * Using `url_for()` doesn't seem optimal because certain target endpoints could require arguments to be passed in which might not work without parsing `request.path` anyway. 
 * Combining `request.script_root` and `request.path` in every usage seems like an easy way to introduce bugs
 * Creating a `BaseRequest` subclass seems like the smartest solution but should there be a new request property (e.g. `request.script_path`)? Or should I replace the existing `path` and `full_path`? 

The PR I have in preparation to fix this issue uses a BaseRequest subclass but I don't feel great about it: 
https://github.com/CTFd/CTFd/pull/802/files#diff-1dec134679d6639679743763954061d5R28

**Comment by davidism** [comment]
I don't understand the bug you're reporting. Please provide a concrete, minimal example of the issue you're having when reporting a bug.

**Comment by ColdHeat** [comment]
```python
from flask import Flask, request
from werkzeug.serving import run_simple
from werkzeug.wsgi import DispatcherMiddleware

app = Flask(__name__)

@app.route('/hi')
def hello_world():
    return 'Hello, World!'

@app.before_request
def show_path():
    print request.script_root, request.path

app.config['APPLICATION_ROOT'] = '/test'

if __name__ == '__main__':
    application = DispatcherMiddleware(Flask('dummy_app'), {
        app.config['APPLICATION_ROOT']: app,
    })
    run_simple('localhost', 4000, application, use_reloader=True)
```

Here's a diluted test case based off of the Flask quickstart and here is the output. 

```
❯ python example.py
 * Running on http://localhost:4000/ (Press CTRL+C to quit)
 * Restarting with stat
/test /hi
127.0.0.1 - - [15/Dec/2018 18:41:55] "GET /test/hi HTTP/1.1" 200 -
```

Using APPLICATION_ROOT this server is running in a subdirectory but request.path is pointing to `/hi` when the true full path is `/test/hi`. 

I understand that [the docs](http://flask.pocoo.org/docs/1.0/api/?highlight=script_root#flask.Request.url_root) are clear in saying that `request.path` doesn't return the full URL path but what is the best way to grab it that doesn't involve doing `request.script_root + request.path` everywhere? Would it just be to subclass the Request object and reprepand `request.path` with `request.script_root`? 

For example: 
```
class CorrectSubDirectoryRequest(Request):
    @cached_property
    def script_path(self):
        return self.script_root + self.path
```

**Comment by davidism** [comment]
I don't understand why you need to look at the script root. The path is the path within your application, which routing is performed on. The script root is outside your application, but is handled by url_for.

**Comment by ColdHeat** [comment]
How would you restructure this decorator?

https://github.com/CTFd/CTFd/blob/master/CTFd/utils/decorators/__init__.py#L70

If I redirect purely based off request.path a user could end up redirected
to a different application.

If I use url_for I would need to reconstruct the necessary arguments to
each endpoint right? Is there a better way to do this than just appending
script root and path? At that point I might as well overload path with a
subclass.

**Comment by davidism** [comment]
`request.url` instead of `request.path`
