### ISSUE TITLE
TypeError: __name__ must be set to a string object 

### ISSUE THREAD

**Issue by chuck-bass** [pallets/flask#3033]
### Expected Behavior

I wanna write code capable of python3. So i add "from future import unicode_literals" on the top of file.Meanwhile, i use MethodView to build rest api in the same file. I wish it could work fine.

Here is an example:

```
  # -*- coding: utf-8 -*-

  from __future__ import unicode_literals
  from flask import Flask
  from flask import Blueprint, request, current_app, g, abort
  from flask.views import MethodView

  masterviews = Blueprint('newmasterviews', __name__)


  class TeamAPI(MethodView):

      def get(self):
          pass


  team_view = TeamAPI.as_view('team_api')

  app = Flask(__name__)

  app.register_blueprint(masterviews, url_prefix='/rest/master')
```

### Actual Behavior

However, when i run the web app, it thows the error,

```
"lib/python2.7/site-packages/flask/views.py", line 98, in as_view
view.__name__ = name
TypeError: __name__ must be set to a string object". 
```
I soon realize that because i use the "from future import unicode_literals" in py2 so the function name is unicode type, but the name of a function should be string type.So i wonder is it possible to change the
source code in the views.py and add the if-then workflow to convert name of function from unicode type into string type to handle the situation .

### Environment
python2.7
Flask==1.0.2
Werkzeug==0.14.1

**Comment by greyli** [comment]
Thanks for reporting on this! You can fix it temporarily by using `str()` or `bytes()`, for example:
```py
team_view = TeamAPI.as_view(str('team_api'))
```
@davidism Could we just change [flask/views.py: L102](https://github.com/pallets/flask/blob/master/flask/views.py#L102) and [L91](https://github.com/pallets/flask/blob/master/flask/views.py#L91) to this:
```py
view.__name__ = str(name)
```
Or this:
```py
if PY2:
    view.__name__ = str(name)
else:
    view.__name__ = name
```

**Comment by davidism** [comment]
This is one of the (many) downsides of using the `unicode_literals` future. It is not something we support. You'll need to be deliberate about the types you're passing in Python 2.

`unicode_literals` doesn't make your code any more capable of running on Python 3, it just makes all strings Unicode, which is not supported consistently on Python 2 in general.
