### ISSUE TITLE
yum install virtualenv instead of python-virtualenv on Fedora

### ISSUE THREAD

**Issue by rht** [pallets/flask#3035]
---

### Expected Behavior

`yum install python-virtualenv` in the install instruction doesn't lead to having a `virtualenv` binary on the path, as the problem is exactly described by https://unix.stackexchange.com/questions/27877/install-virtualenv-on-fedora-16 (the question is outdated, but it also applies to Fedora 29 I have been testing).
```shell
sudo yum install python-virtualenv
```

The solution is to do `sudo yum install virtualenv` instead, which is an alias to `python3-virtualenv`. And so an explicit `-p python2.7` is needed to start a python2 env.

### Environment

* Python version: N/A
* Flask version: N/A
* Werkzeug version: N/A

**Comment by davidism** [comment]
Would you be able to make a PR to change this?

**Comment by rht** [comment]
Will do after checking that it is better off to install `virtualenv` instead of `python-virtualenv` on CentOS as well.
