### ISSUE TITLE
Creating flask_wtf forms for a list of values  through a for loop generates the same inputs several times within each form

### ISSUE THREAD

**Issue by devalvarado200** [pallets/flask#3036]
### Expected Behavior

I want create a loop for a list of data and generate a form for every record among a edit button, this to prevent pass in url the id of the record when i use the edit button.

In this form i put a hidden field with the id value and a submit button

When i press submit it make the POST, but in the route that receive the value get nothing.

This is my code source:

```python

{% for worker in workers %}
 <form method="POST" action="{{ url_for('worker.edit_middleware') }}">
                    <td>
                      {{ form.hidden_tag() }}
                      {{ form.worker_id(value=worker.id) }}
                   <input class="btn btn-login"  type="submit" name="editar" value="Editar">
                    </td>               
                 </form>
{% endfor %}
```

When i inspect the page i see this:

```python
<td>
<input id="worker_id" name="worker_id" type="hidden" value="">
<input id="hidden_id" name="hidden_id" type="hidden" value="">
<input id="csrf_token" name="csrf_token" type="hidden" value="SECRET_ABBREV">
<input id="worker_id" name="worker_id" type="hidden" value="453">
<input class="btn btn-login" type="submit" name="editar" value="Editar">
</td>
```

The page get two times the fields for every row, in the first time all of the field in the form class appear created  with no values, although they are not called in the code, later of the crsf_token get the field that i called in my code with the values..

### Actual Behavior

To resolve this i remove the form hidden_tag and implement manual input field

```python
<form method="POST" action="{{ url_for('worker.edit_middleware') }}">
     <td>
       <input type="hidden" name="worker_id" value="{{ worker.id }}">
        <input class="btn btn-login"  type="submit" name="editar" value="Editar">
    </td>               
</form>
```

And this is that i get in inspect:

```python
<td>
    <input type="hidden" name="worker_id" value="453">
    <input class="btn btn-login" type="submit" name="editar" value="Editar">
</td>
```
But is posible to loop the form without getting two times the fields?.
I think this is a bug or maybe bad implementation

### Environment

* Python version: 3.6.4
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by ThiefMaster** [comment]
Flask-WTF is not part of Flask.
