### ISSUE TITLE
Flask auto reload does not refresh browser

### ISSUE THREAD

**Issue by glinskyc** [pallets/flask#3057]
Hello,
This is directly related to the SO question:
https://stackoverflow.com/questions/51379705/flask-auto-reload-does-not-refresh-browser

### Expected Behavior

Upon changing an HTML template file while running the Flask development server, I thought the browser view would update to reflect the new HTML.

### Actual Behavior

The browser view does _not_ update upon changing an HTML template file.  To see the HTML changes, the browser must be manually refreshed.  I did not expect this to be the case.  I am unsure if this is a bug or intended behavior of the Flask development server.

If this behavior is intended, I would like to have this considered for a Feature Request for the Flask development server.

### Environment

* Python version:  3.6.3
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by lepture** [comment]
Flask auto reload means it will auto reload the python code. You can use https://github.com/lepture/python-livereload to get what you want.

**Comment by glinskyc** [comment]
Thank you for the suggestion, I will try the `livereload` package.  Perhaps the Flask documentation would benefit from clarifying this in the following places:

http://flask.pocoo.org/docs/1.0/config/#TEMPLATES_AUTO_RELOAD
http://flask.pocoo.org/docs/1.0/server/

From reading other posts related to this topic, I believe there is some confusion about what the auto reload capability is intended to do.
