### ISSUE TITLE
send_file doesn't urlencode ':/' in unicode attachment_filename

### ISSUE THREAD

**Issue by i-akhmadullin** [pallets/flask#3074]
### Expected Behavior

When sending files with unicode filename (with `:` or `/`) they should be downloaded with name from `filename*` field.

```python
# -*- coding: utf-8 -*-
import os
from flask import Flask, send_from_directory
app = Flask(__name__)
@app.route('/test/', methods=['GET'])
def test_route():
    tmp_dir = os.getcwd()
    tmp_filename = __file__
    attachment_filename = u'тест:тест_тест.py'
    return send_from_directory(
        tmp_dir,
        tmp_filename,
        as_attachment=True,
        attachment_filename=attachment_filename
    )
if __name__ == '__main__':
    app.run(host='::', port=5000)
```
### Actual Behavior

Some browsers (Chrome-based/Safari) ignore `filename*` field when it contains colon or slash. For example file `тест:тест_тест.py` gets downloaded in Chrome/Safari as `__.py` but in Firefox as `тест_тест_тест.py` which is acceptable in my opinion.

Flask response:
`Content-Disposition: attachment; filename*="UTF-8''%D1%82%D0%B5%D1%81%D1%82:%D1%82%D0%B5%D1%81%D1%82_%D1%82%D0%B5%D1%81%D1%82.py"; filename=":_.py"`

### Environment

* Python version: 2.7.15
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by eladm26** [comment]
according to the [RFC](https://greenbytes.de/tech/webdav/rfc6266.html#disposition.parameter.filename): `both "filename" and "filename*" are present in a single header field value, recipients SHOULD pick "filename*" and ignore "filename"`
So it seems like an issue with chrome rather than flask.

**Comment by davidism** [comment]
This was working in Chrome when I implemented this. If they're changing behavior, that's incorrect and needs to be reported to them. I don't think Flask can do anything about it because it still needs to send both for compatibility with other clients.

**Comment by i-akhmadullin** [comment]
This issue is about encoding colon and slash in attachment filename, not about filename/filename*.
If we encode colon and slash characters then file gets downloaded with a utf8-name, but with underscores instead colons and slashes. But otherwise this is a lot better result than ascii-only filename (`тест_тест_тест.py` vs `_.py`).

Flask uses `url_quote` from `werkzeug` where `:/` are listed as safe characters, so maybe it just an oversight that they are not escaped.
https://github.com/pallets/flask/blob/a74864ec229141784374f1998324d2cbac837295/flask/helpers.py#L589
https://github.com/pallets/werkzeug/blob/master/werkzeug/urls.py#L518

**Comment by davidism** [comment]
Your description in "actual behavior" makes no mention of how ":/" relate to the issue, it just mentions "filename" and "filename*". Could you review and make sure the issue accurately represents what you're trying to describe?

**Comment by i-akhmadullin** [comment]
@davidism sorry for the confusion, should be clearer now
