### ISSUE TITLE
setuptools finds flask-mail instead of flask

### ISSUE THREAD

**Issue by Zethson** [pallets/flask#3078]
### Expected Behavior

Running it on a new VPS. setup.py used is:     
https://github.com/Zethson/dark-proteome-visualization/blob/development/setup.py    
with requirements.txt used:    
https://github.com/Zethson/dark-proteome-visualization/blob/development/requirements.txt

 ```python
python setup.py clean --all install
```

Finds flask and installs flask.

### Actual Behavior

Searching for flask
Downloading https://files.pythonhosted.org/packages/05/2f/6a545452040c2556559779db87148d2a85e78a26f90326647b51dc5e81e9/Flask-Mail-0.9.1.tar.gz#sha256=22e5eb9a940bf407bcf30410ecc3708f3c56cc44b29c34e1726fe85006935f41
Best match: Flask Mail-0.9.1
Processing Flask-Mail-0.9.1.tar.gz

I tried pretty much all combinations of capital/lowercase for flask and flask-mail. No success. Interestingly enough, if I run the install script again (same virtual environment), it finds flask.

```pytb
error: The 'flask' distribution was not found and is required by flask-Mail
```

### Environment

* Python version: Python 3.6.7
* Flask version: latest
* Werkzeug version: latest

**Comment by davidism** [comment]
Sounds like an issue with your Pip installation, configuration, or connection to PyPI. Try `pip install -U pip`. Flask is definitely still available and I do not see the same issue when I install Flask-Mail or Flask.

**Comment by Zethson** [comment]
https://github.com/pypa/setuptools/issues/498

This is the actual issue. Someone already pointed me to this one.

**Comment by davidism** [comment]
Huh, I've never encountered that, and I've never been particular about the order of dependencies. Thanks for the link.
