### ISSUE TITLE
Session variable is not saved

### ISSUE THREAD

**Issue by rasidmusic** [pallets/flask#3080]
Hey guys,

I have a problem with the session variable functionality.
I am assigning some variables that contain JSON Objects to session variables. 
Something like

`variable = {'modell': 'Vertrag', 'lagerort': '4-01-N', 'lagerid': 306816, 'p3barcode': 'L18100017', 'devicegroup': 'SIM Karten', 'devicegroupid': 10, 'verliehenan': 'EBP (Bernd Eppinger)', 'lagerbarcode': 'L16050068', 'hersteller': 'T-Mobile', 'status': 'Mitarbeiter zugewiesen'}`
`session['abc'] = variable`

This is working BUT
if the data in varaible gets too big, the session variable is not beeing saved.

I thought it is a issue with the cookie size, however on the https://www.tutorialspoint.com/flask/flask_sessions.htm is metioned, that sessions are stored on the server - so there should not be a limit?
Is there a way how can I store a large variable a session variable?

Thanks in advance

**Comment by davidism** [comment]
That tutorial is incorrect. If you'd like server-side sessions, use one of the various extensions that provide other session stores.

**Comment by rasidmusic** [comment]
Hey, Yeah i thoought so.  I tired Flask-Session. Works like a charm.
Thnak you very much
