### ISSUE TITLE
not able to serve html file with all the css and js linked in flask

### ISSUE THREAD

**Issue by RajibKDey** [pallets/flask#3085]
Hi i am new to the flask environment and i am currently working on a project which involves me hosting a server to run a dashboard for IoT devices (freeboard). I have already copied all the freeboard files to the static folder. But the index page of the freeboard when called through flask doesnt include any css and javascript files that have been mentioned in the index file of freeboard. 

The file structure is a follows
Myproject/static/(freeboard files)

I am expecting the freeboard index-page to load with all the necessary css and javascript files linked as mentioned in the index page.
I would like a know a way to host freeboard through flask without changing any of the original files from freeboard.

**Comment by ThiefMaster** [comment]
Maybe freeboard expects to be run from the url root. In any case, it's off-topic here since this issue trackers is for bug reports and feature requests.
