### ISSUE TITLE
banner statements not directed to log when app starts

### ISSUE THREAD

**Issue by bandtank** [pallets/flask#3087]
The initial banner messages emitted from flask to the console are not routed to the log handler as expected. The only way to work around this is to change all log statements to go to `stderr` and then redirect `stdout` to `/dev/null`. Otherwise, the statements appear in the console with no obvious way to enable suppression or reroute them to a log handler.

I suspect this is intentional, but I think the statements should be able to be suppressed or rerouted in some manner. Something as simple as a flag to show or hide the banner would suffice in `flask/app.py`:
```
938         if self.show_banner:
939             cli.show_server_banner(self.env, self.debug, self.name, False)
```

Console excerpt showing the statements not redirecting to the log handler:
```
[2019-01-30 07:20:02.254] [DBUG] [api.py:35              ] Starting API
 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[2019-01-30 07:20:02.264] [DBUG] [fps.py:23              ] FPS[0] main loop
```
Instantiation is from a class that is called as part of a larger application, which embeds the API:
```
  def __init__():
    self.app = flask.Flask(__name__)
    self.app.config.from_object("config")
    self.bp  = flask.Blueprint("fpsApi", __name__)
    self.api = flask_restful.Api(self.bp)
    self.api.add_resource(Hello, "/Hello")
    self.app.register_blueprint(self.bp, url_prefix = "/api")
    
  def run(self):
    logging.debug(f"Starting API")
    self.app.run(
      debug = self.dbgMode,
      use_reloader = self.useReloader,
      port = self.cfg["apiPort"],
      host = self.hostIp
    )
```

Version information:
```
$ python --version
Python 3.7.2

$ pip freeze
aniso8601==4.1.0
Click==7.0
Flask==1.0.2
Flask-RESTful==0.3.7
gnureadline==6.3.8
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
mysqlclient==1.4.1
pbr==5.1.1
python-dotenv==0.10.1
pytz==2018.9
schema==0.6.8
six==1.12.0
stevedore==1.30.0
virtualenv==16.2.0
virtualenv-clone==0.5.1
virtualenvwrapper==4.8.2
Werkzeug==0.14.1
```

**Comment by davidism** [comment]
The development server is not meant to be run in production, even embeded in another application. Use a production WSGI server, such as Gunicorn; it can still be called in Python code to do what you want.
