### ISSUE TITLE
"Lift" Flask (et al.) on Tidelift

### ISSUE THREAD

**Issue by jab** [pallets/flask#3089]
It's possible to [donate](https://palletsprojects.com/blog/donate/) to support Flask, but (despite several Flask *extensions* being [lifted](https://tidelift.com/subscription/pkg/supported-open-source-packages)), neither Flask *itself* nor other Pallets projects are available via Tidelift subscription.

According to current estimates, [Flask](https://tidelift.com/lifter/search?q=flask), [Werkzeug](https://tidelift.com/lifter/search?q=werkzeug), [Jinja2](https://tidelift.com/lifter/search?q=jinja2), [Click](https://tidelift.com/lifter/search?q=click), and [ItsDangerous](https://tidelift.com/lifter/search?q=itsdangerous) could each be earning USD $417/month (a total of over $2K/month).

(I recently lifted an [open source project](https://tidelift.com/subscription/pkg/pypi-bidict?utm_source=pypi-bidict&utm_medium=referral&utm_campaign=flask3089) I've been maintaining for over 10 years – which has been in use at Google, Venmo, Bank of America Merrill Lynch, et al. – and only today got my first cent of financial support thanks to Tidelift.)

Just wanted to make sure you knew about Tidelift in case it's an option for you. ❤️

**Comment by davidism** [comment]
Thanks! We are aware of them, but the discussion is happening elsewhere. Because we are part of the PSF, we need to take care in how we do things like this.

**Comment by jab** [comment]
Great you’re aware of Tidelift already! Seems like too few maintainers know about it still.

If you ever end up lifting any Pallets projects, please post an update on this issue.

**Comment by davidism** [comment]
I have some Pallets blog posts about what we're up to planned, this would definitely be announced if it happens.

**Comment by jab** [comment]
https://blog.tidelift.com/tidelift-and-the-python-software-foundation-join-up-to-support-flask-and-pallets-projects 🎉
