### ISSUE TITLE
custom error handler not being called for HTTP error 412 

### ISSUE THREAD

**Issue by GiancarloFusiello** [pallets/flask#3093]
I have created a custom error_handler function like so:
```python
def http_error_handler(error: HTTPException) -> Response:
    # rest of the code here
```
I then register all default http errors to use the above handler like so:

```python
from werkzeug.exceptions import default_exceptions

for code in default_exceptions:
    app.errorhandler(code)(http_error_handler)
```

I can confirm that my handler function has registered for all http errors in `default_exceptions`:
```python
app.error_handler_spec
{None: {400: {<class 'werkzeug.exceptions.BadRequest'>: <function http_error_handler at 0x7f0d3cd688c8>},
        401: {<class 'werkzeug.exceptions.Unauthorized'>: <function http_error_handler at 0x7f0d3cd688c8>},
        403: {<class 'werkzeug.exceptions.Forbidden'>: <function http_error_handler at 0x7f0d3cd688c8>},
        404: {<class 'werkzeug.exceptions.NotFound'>: <function http_error_handler at 0x7f0d3cd688c8>},
        405: {<class 'werkzeug.exceptions.MethodNotAllowed'>: <function http_error_handler at 0x7f0d3cd688c8>},
        406: {<class 'werkzeug.exceptions.NotAcceptable'>: <function http_error_handler at 0x7f0d3cd688c8>},
        408: {<class 'werkzeug.exceptions.RequestTimeout'>: <function http_error_handler at 0x7f0d3cd688c8>},
        409: {<class 'werkzeug.exceptions.Conflict'>: <function http_error_handler at 0x7f0d3cd688c8>},
        410: {<class 'werkzeug.exceptions.Gone'>: <function http_error_handler at 0x7f0d3cd688c8>},
        411: {<class 'werkzeug.exceptions.LengthRequired'>: <function http_error_handler at 0x7f0d3cd688c8>},
        412: {<class 'werkzeug.exceptions.PreconditionFailed'>: <function http_error_handler at 0x7f0d3cd688c8>},
        413: {<class 'werkzeug.exceptions.RequestEntityTooLarge'>: <function http_error_handler at 0x7f0d3cd688c8>},
        414: {<class 'werkzeug.exceptions.RequestURITooLarge'>: <function http_error_handler at 0x7f0d3cd688c8>},
        415: {<class 'werkzeug.exceptions.UnsupportedMediaType'>: <function http_error_handler at 0x7f0d3cd688c8>},
        416: {<class 'werkzeug.exceptions.RequestedRangeNotSatisfiable'>: <function http_error_handler at 0x7f0d3cd688c8>},
        417: {<class 'werkzeug.exceptions.ExpectationFailed'>: <function http_error_handler at 0x7f0d3cd688c8>},
        418: {<class 'werkzeug.exceptions.ImATeapot'>: <function http_error_handler at 0x7f0d3cd688c8>},
        422: {<class 'werkzeug.exceptions.UnprocessableEntity'>: <function http_error_handler at 0x7f0d3cd688c8>},
        423: {<class 'werkzeug.exceptions.Locked'>: <function http_error_handler at 0x7f0d3cd688c8>},
        428: {<class 'werkzeug.exceptions.PreconditionRequired'>: <function http_error_handler at 0x7f0d3cd688c8>},
        429: {<class 'werkzeug.exceptions.TooManyRequests'>: <function http_error_handler at 0x7f0d3cd688c8>},
        431: {<class 'werkzeug.exceptions.RequestHeaderFieldsTooLarge'>: <function http_error_handler at 0x7f0d3cd688c8>},
        451: {<class 'werkzeug.exceptions.UnavailableForLegalReasons'>: <function http_error_handler at 0x7f0d3cd688c8>},
        500: {<class 'werkzeug.exceptions.InternalServerError'>: <function http_error_handler at 0x7f0d3cd688c8>},
        501: {<class 'werkzeug.exceptions.NotImplemented'>: <function http_error_handler at 0x7f0d3cd688c8>},
        502: {<class 'werkzeug.exceptions.BadGateway'>: <function http_error_handler at 0x7f0d3cd688c8>},
        503: {<class 'werkzeug.exceptions.ServiceUnavailable'>: <function http_error_handler at 0x7f0d3cd688c8>},
        504: {<class 'werkzeug.exceptions.GatewayTimeout'>: <function http_error_handler at 0x7f0d3cd688c8>},
        505: {<class 'werkzeug.exceptions.HTTPVersionNotSupported'>: <function http_error_handler at 0x7f0d3cd688c8>}}}
```
I'm then testing each error using an endpoint that accepts requests like so `/error?code=404` which in tern calls `flask.abort(404)` that then calls `http_error_handler` I created.

I noticed that all http errors are calling my custom error function except for http error 412 even though you can see it has registered above. Any ideas?

Side note, if there is a better way of testing custom error pages then please advise.

Thanks in advance.

### Environment

* Python version: 3.7.2-alpine3.8 docker image
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
I can't reproduce this issue as described. Navigating to `/?code=412` with the following app returned "caught" as expected.

```python
from flask import Flask, request, abort

app = Flask(__name__)

@app.route("/")
def index():
    abort(request.args.get("code", type=int))

@app.errorhandler(412)
def handle_412(e):
    return "caught"
```

**Comment by GiancarloFusiello** [comment]
@davidism do you get the same result without using `errorhandler` as decorator? like so:
```python
from flask import Flask, request, abort

def handle_412(e):
    return "caught"

app = Flask(__name__)
app.errorhandler(code)(http_error_handler)

@app.route("/")
def index():
    abort(request.args.get("code", type=int))
```
I'm using the app factory pattern rather than using the @app decorator.

**Comment by davidism** [comment]
You're still using `errorhandler` as a decorator there. The non-decorator form is `add_error_handler(code, function)`. Yes, I got the same result for all three forms.

**Comment by GiancarloFusiello** [comment]
I have updated the code to use `app.register_error_handler` but I'm still getting the same issue. I even had my colleague clone the repo and he was able to reproduce.

Would you be so kind and please clone [this](https://github.com/libero/search), checkout branch `feature/add_custom_errors` and run `make tests` from the root of the project? This will build the docker container (may take a couple of minutes) and run tests.

**Comment by GiancarloFusiello** [comment]
@davidism I have spent some time debugging Flask/Werkzeug and you can see [here](https://github.com/pallets/werkzeug/blob/0.14.1/werkzeug/wrappers.py#L1250) and [here](https://github.com/pallets/werkzeug/blob/0.14.1/werkzeug/wrappers.py#L1290) that the response headers and data are stripped from the response if the status code is 412.

Therefore, I'm not sure how you were able to see your custom response data/message for http exception for status 412. Either way, this appears to be working as expected. Thanks for taking a look.

**Comment by un-def** [comment]
@GiancarloFusiello have you tried an unreleased version of Werkzeug (0.15)? I guess your issue is related to a known problem: https://github.com/pallets/werkzeug/issues/1231 https://github.com/pallets/werkzeug/pull/1255

Werkzeug <=0.13 should also work fine, but Flask 1.x requires Werkzeug >= 0.14.

**Comment by GiancarloFusiello** [comment]
@un-def thank you for pointing this out to me. PyPi doesn't have a reference to 0.15 yet but I can confirm that this is no longer an issue in version 0.15.dev0 which I was able to install from github. However, I don't feel comfortable using this in production but I'll look to upgrade to when officially released. Thanks again for you help.
