### ISSUE TITLE
未打印请求信息,直接返回数据

### ISSUE THREAD

**Issue by Ericliuzi** [pallets/flask#3097]
我遇到过两次,请求方接收到我的返回数据,但是我这边却没有任何东西打印出来

        logging.info(request)
        # logging.info(type(request.form.get("msg", type=str, default=None)))
        # logging.info(request.values)
        import json
        logging.info(request.values.to_dict())
        a = request.values.to_dict()['msg']
        dict1 = json.loads(a)
        from datetime import datetime
        dict1['resivetime'] = datetime.now()
        logging.info(dict1)
        queues.put(dict1)
        return json.dumps({'status': 1, 'receive_id': dict1['id'], 'receive_': dict1['name']})

请求方会有这个数据,但是接收方,如上,没有打印任何日志,几乎一个星期左右有一次出现

**Comment by ThiefMaster** [comment]
English please.

**Comment by Ericliuzi** [comment]
> English please.

done
