### ISSUE TITLE
Allow passing cert and key to `flask run` via env var / .flaskenv

### ISSUE THREAD

**Issue by jab** [pallets/flask#3105]
Currently the only way to pass cert and key to `flask run` is via CLI options. Would you accept a patch to allow passing via FLASK_RUN_CERT / KEY env vars (settable in .flaskenv) as well? This would make these consistent with FLASK_RUN_HOST / PORT.

**Comment by carc1n0gen** [comment]
@jab Why do you need ssl in a development server?

**Comment by davidism** [comment]
Flask does nothing special to enable `FLASK_RUN_PORT` etc., that's provided by Click. This should already be possible.

**Comment by davidism** [comment]
I just tried `FLASK_APP=example FLASK_RUN_CERT=adhoc flask run` and it worked as expected.

**Comment by jab** [comment]
Oh wow, that's awesome, thanks! I'd tested env vars corresponding to the other `flask run` options and they didn't work (e.g. `FLASK_RUN_DEBUGGER`, `FLASK_RUN_EAGER_LOADING`, `FLASK_RUN_WITH_THREADS`), I thought I'd tested `FLASK_RUN_CERT` and it didn't work either but I clearly missed that, sorry! I don't see this documented so I'll try to submit a docs PR if no one beats me to it.

Is it intentional that FLASK_RUN_\* env vars for those other options don't work, or am I missing something there too?

OT but relatedly, is it intentional that it's --eager-load*ing* but --lazy-load*er*?
