### ISSUE TITLE
Please adds init-db in readme

### ISSUE THREAD

**Issue by MagicGary** [pallets/flask#3106]
**ReadMe** 

please add ``flask init-db`` right before ``flask run`` section in the tutorial README.

**Comment by davidism** [comment]
I'd be happy to review a PR for this.

**Comment by greyli** [comment]
@MagicGary Thanks for reporting on this. There is already added `flask init-db` commands before every `flask run` in tutorial [REAMDE](https://github.com/pallets/flask/blob/master/examples/tutorial/README.rst#run) at master branch. Please try to [sync your local fork](https://help.github.com/en/articles/syncing-a-fork). 

Releated commit: [d0088e6](https://github.com/pallets/flask/commit/d0088e63d8004b17d5dd762ac3de00841bd34c00#diff-a0d0943abd9e105a0512a14b8c702d16).

**Comment by MagicGary** [comment]
👍
