### ISSUE TITLE
flask run command won't run python files with .wsgi extension (or any other than .py)

### ISSUE THREAD

**Issue by koyuch** [pallets/flask#3115]
### Description
If you have python file with wsgi extension (or any other than .py), you can't execute `flask run` command. (When you execute the script with .run() in it, it works fine).

### Example
For example when you create file `app.wsgi` with simple content:
```python
from flask import Flask
app = Flask(__name__)
```
And of course you set the environment variable `FLASK_APP=app.wsgi`
you actually get:
```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 325, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 313, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 302, in _load_app
    self._load_unlocked()
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 246, in locate_app
    'Could not import "{name}".'.format(name=module_name)
NoAppException: Could not import "app.wsgi".
```
I think it's essential to run also wsgi files (you can run "default" wsgi.py, but not anything with .wsgi in the end)

### Environment

* Python version: 2.7.15rc1
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
How do you propose to fix this? That name looks like an import, and should end with .py if it's not.

**Comment by koyuch** [comment]
Isn't there any way? https://stackoverflow.com/questions/2601047/import-a-python-module-without-the-py-extension
I didn't know how it's implemented internally, but I think there's always "the way"..

**Comment by davidism** [comment]
We're already importing python modules without the extension, that's the whole source of your issue, you've chosen a non-standard extension that instead looks like an import path.

**Comment by koyuch** [comment]
the `.wsgi` files are "standard" for apache (mod_wsgi) entrypoint files - I wanted to use the same entrypoint also for flask app.
but OK, if this cannot be done I will use the other way of execution (`python app.wsgi`)

**Comment by davidism** [comment]
`python app.wsgi` was not my suggestion. mod_wsgi will work just fine with a `.py` extension.

**Comment by koyuch** [comment]
sorry, I didn't know if it's mandatory or not (extension). thanks for your tip ;)
