### ISSUE TITLE
DeprecationWarning: python 3.8 will not work

### ISSUE THREAD

**Issue by ak-ambi** [pallets/flask#3116]
I know that problems listed below are solved in both jinja2 and werkzeug repos, but they are not released. Without new releases of both, users will be stuck with python 3.7.

Currently running pytest in my projects produces following warnings:
```
============================== warnings summary ===============================
C:\Program Files\Python37\lib\site-packages\werkzeug\datastructures.py:16
C:\Program Files\Python37\lib\site-packages\werkzeug\datastructures.py:16
C:\Program Files\Python37\lib\site-packages\werkzeug\datastructures.py:16
  C:\Program Files\Python37\lib\site-packages\werkzeug\datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Container, Iterable, MutableSet

C:\Program Files\Python37\lib\site-packages\jinja2\utils.py:485
  C:\Program Files\Python37\lib\site-packages\jinja2\utils.py:485: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping

C:\Program Files\Python37\lib\site-packages\jinja2\runtime.py:318
  C:\Program Files\Python37\lib\site-packages\jinja2\runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping
```
---

### Expected Behavior

No warning preventing usage of python 3.8 should be displayed.

### Actual Behavior

Warnings pasted above are displayed ;)

### Environment

* Python version: 3.7
* Flask version: 1.0.2
* Werkzeug version: 0.14.1
* Jinja2 version: 2.10

**Comment by ThiefMaster** [comment]
> 3.8.0 beta 1: Sunday, 2019-05-26 (No new features beyond this point.)
3.8.0 beta 2: Sunday, 2019-06-23
3.8.0 beta 3: Sunday, 2019-07-28
3.8.0 beta 4: Sunday, 2019-08-25
3.8.0 candidate 1: Sunday, 2019-09-29
3.8.0 candidate 2: Sunday, 2019-10-06 (if necessary)
3.8.0 final: Sunday, 2019-10-20

I think it's safe to say that there will be releases containing the necessary change before the release of the rc/final - probably even before the beta.
