### ISSUE TITLE
遇到一些pipenv 安装问题

### ISSUE THREAD

**Issue by JerryWuGitHub** [pallets/flask#3120]
安装虚拟环境的时候，报了如下错误，请问有什么办法解决，pipfile里面的url已经失效了，是否有新的可提供一下？
D:\personal-study\helloflask>pipenv install
Creating a virtualenv for this project...
Pipfile: D:\personal-study\helloflask\Pipfile
Using c:\python27\python.exe (None) to create virtualenv...
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals

**Comment by frostming** [comment]
@JerryWuGitHub Maybe you should have go to https://github.com/greyli/helloflask

This repo is not for tutorial.

**Comment by davidism** [comment]
This appears to be an issue with pipenv, not Flask.
