### ISSUE TITLE
FLASK RESPONSE HEADER FILENAME PASS DYNAMIC VALUE

### ISSUE THREAD

**Issue by deepakchandra00** [pallets/flask#3123]
FLASK RESPONSE HEADER FILENAME PASS DYNAMIC VALUE

return Response(
            csv, 
            mimetype="text/csv",
            headers={"Content-disposition":
                    "attachment; filename={{**here i want to dynamic variable**}}"})

**Comment by ThiefMaster** [comment]
Use [`send_file`](http://flask.pocoo.org/docs/1.0/api/#flask.send_file) (or look at how it sets that header).

PS: Why are you shouting at us? Also, this is not the right place for support questions.
