### ISSUE TITLE
Use Werkzeug's JSON mixin

### ISSUE THREAD

**Issue by davidism** [pallets/flask#3125]
pallets/werkzeug#1445 moved Flask's `JSONMixin` to Werkzeug. Flask should now use Werkzeug's version, with some overrides. Will need to bump minimum Werkzeug version.

**Comment by PyDever** [comment]
Why are you wanting to use that API instead of using the default standard library `JSON` parsing mechanism.

**Comment by jamespic** [comment]
@PyDever The standard library `json` module didn't handle binary data (i.e, the data that comes into Flask over the network) properly until Python 3.6, so some additional handling is required for that. You also have issues with CSRF if you use the standard library `json` code naïvely.

**Comment by seawolf42** [comment]
starting to work on this
