### ISSUE TITLE
Cannot differentiate between a regular text input field and a non-uploaded file

### ISSUE THREAD

**Issue by senabIsShort** [pallets/flask#3130]
Issue came up while trying to send an empty file (and filename) to an HTTPbin form.
Using Flask you're unable to differentiate between the content of a text field in a form and a non-uploaded file from the `request` object

### Example test
Using flask alone;
User @moy helped with this and prompted me to post this bug report
```python
from flask import Flask, flash, request, redirect, url_for, escape

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        return '<pre>{}</pre>'.format(escape(str(request.form) + '\n' + str(request.files)))
    return '''
    <!doctype html>
    <title>Upload new Files</title>
    <h1>Upload new Files</h1>
    <form method=post enctype=multipart/form-data>
      <input name="normal_field" value="field_value" />
      <input type=file name=file>
      <input type=file name=secondfile>
      <input type=submit value=Upload>
    </form>
    '''
```
### Expected Behavior
Submitting with only the first file field set in the browser,
one would expect to find :
- the content of both file fields in the same object ;
- the content of normal text input fields in a separate objects ;

So something along the lines of
```
ImmutableMultiDict([('normal_field', 'field_value')])
ImmutableMultiDict([('file', <FileStorage: 'tmp-rg1.xpi' ('application/x-xpinstall')>), 
                    ('secondfile', <FileStorage: '' ('...')>)
                   ])
```

### Actual Behavior
Submitting with only one file (the first field) set in the browser gives:

```
ImmutableMultiDict([('normal_field', 'field_value'), ('secondfile', '')])
ImmutableMultiDict([('file', <FileStorage: 'tmp-rg1.xpi' ('application/x-xpinstall')>)])
```

The first is the form's field, the second the actual files uploaded. I see no way to distinguish between an empty text field and a non-uploaded file from the `request` object.
Is this behavior intended ?

**Comment by davidism** [comment]
That's just how HTML forms send data. You distinguish it by knowing that `secondfile` is a file, and doesn't appear in `request.files`.

**Comment by moy** [comment]
> That's just how HTML forms send data.

It's not. When sending a file, the corresponding part contains a `filename=...` entry, with an empty filename to indicate that the file is absent.  Here's a small test in PHP to show it:

https://matthieu-moy.fr/tmp/2019/tmp.php

When I submit the form without specifying the file, and use Firefox's webmaster tools to display the request's payload, I see:

```
-----------------------------836990156529063132208061493
Content-Disposition: form-data; name="pic"; filename=""
Content-Type: application/octet-stream


```

The content is empty, but there's still a `filename=""` sent by the browser. Non-file fields are sent as:

```
-----------------------------3052647601320914323543240568
Content-Disposition: form-data; name="customer"


```

i.e. without `filename=...` at all. As the test shows, PHP can distinguish non-submited files, put in `$_FILES`, and non-file fields, in `$_POST`. The information is there, but it's not used by flask.

**Comment by davidism** [comment]
This would be an issue with Werkzeug, although I'm not planning to change this at this point. `request.files` always has whatever is submitted. You can do `request.files["pic"].filename == ""`, or look at its size.

**Comment by moy** [comment]
> `request.files` always has whatever is submitted.

Unfortunately, no: `request.files` doesn't have the file, and that's the point of this issue. As @senabIsShort wrote in the first message, when `file` corresponds to an actually submitted file and `secondfile` to a file that wasn't submitted, one gets

```
request.form == ImmutableMultiDict([('normal_field', 'field_value'), ('secondfile', '')])
request.files == ImmutableMultiDict([('file', <FileStorage: 'tmp-rg1.xpi' ('application/x-xpinstall')>)])
```

The information is provided in the HTTP payload (`filename=""` vs no `filename` entry at all), but is not present in `request.files`.

I didn't dig further to see whether it was an issue with Werkzeug or Flask (we actually noticed the issue in httpbin first, which is using flask).

**Comment by davidism** [comment]
I'm sorry, I'm having trouble understanding the issue you're trying to describe. I tried the given example and got the given expected output.

```
request.form: ImmutableMultiDict([('normal_field', 'field_value')])
request.files: ImmutableMultiDict([('file', <FileStorage: 'image.jpg' ('image/jpeg')>), ('secondfile', <FileStorage: '' ('application/octet-stream')>)])
```

**Comment by moy** [comment]
> I tried the given example and got the given expected output.

Hmm, indeed, I tested again (not on the same machine), and I can't reproduce anymore. Probably the issue was fixed in the meantime.

**Comment by moy** [comment]
I could reproduce on the machine I first did the test, but the problem disappeared when I `pip3 install --upgrade flask`-ed. So, indeed, problem solved. Thanks.
