### ISSUE TITLE
Flask + gevent: possible sockets leaks (in the CLOSE_WAIT state)

### ISSUE THREAD

**Issue by chubin** [pallets/flask#3135]
```python
@app.route('/', defaults={'path': ''}, methods=['GET', 'POST'])
def catch_all(path):
     session_id = 'session1'
     if session_id not in sessions:
         session = Session()
         sessions[session_id] = session
     else:
         session = sessions[session_id]

     session.start()
     queue = register_queue()
     def events():
         try:
             if queue:
                 while True:
                     for _, data in queue:
                         yield data
         finally:
             # THIS POINT HERE IS NEVER BEING REACHED
             # FOR SOME CLIENTS, becase the connection
             # is getting stuck in the CLOSE_WAIT state

             deregister_queue(queue)
             if len(queues) == 0:
                 session.kill()
                 del sessions[session_id]

  return Response(events(), content_type='text/event-stream')
```

### Expected Behavior

All sockets are getting closed after they are closed from the client side.

### Actual Behavior

Some sockets are getting stuck in the CLOSE_WAIT state
after they are closed from the client side.

### Environment

* Python version: Python 2.7.16rc1
* Flask version: `Flask==1.0.2`
* Werkzeug version: `Werkzeug==0.15.1`
* gevent version: `gevent==1.4.0`

**Comment by davidism** [comment]
I know nothing about gevent, so you're probably going to have to investigate this on your own if you want a fix merged.

**Comment by davidism** [comment]
Please reduce this to a self contained example with both the server and client code to demonstrate the issue.

**Comment by chubin** [comment]
@davidism I think that the problem is even worse that I expected. I think it happens only when some NAT or a stateful filter is in between. I will write a self contained example after the deeper investigation.

**Comment by davidism** [comment]
It looks like you have an infinite loop (`while True` without a `break`).

I'm also not clear what the `CLOSE_WAIT` state is, it doesn't sound like part of the WSGI application layer. This sounds like an issue with Gevent not closing connections and therefore not entering the `finally` block.

**Comment by chubin** [comment]
@davidism It is not a problem here. It works this way:
after the socket is closed, and you are trying to write to a closed socket,
you get an exception and thus leave the endless loop (jumping to the `finally`).

In this particular case, it does not happen because the sockets are getting stuck in the `CLOSE_WAIT` state (it is a standard state of TCP/IP socket).

**Comment by davidism** [comment]
Closing as this sounds like an issue with Gevent's WSGI server or your network stack. If you can create a minimal example demonstrating that this is an issue with Flask, I'll reopen.
