### ISSUE TITLE
raise exception instead of using abort()

### ISSUE THREAD

**Issue by leandropls** [pallets/flask#3158]
Using abort() makes static code analysis harded because it only works if the IDE knows that abort() interrupts the function execution.

Is there a reason why flask handler abortion isn't done with a raise instead of abort?

Would an abortion interfaced based on raising exceptions directly be accepted into the code?

**Comment by davidism** [comment]
You can do either. `abort` does raise exceptions, it's a shortcut for status codes instead of importing exceptions. That static analysis can't pick that up is a failing of static analysis capabilities in Python.

**Comment by pgjones** [comment]
@leandropls you could try adding a typing stub that marks `abort` as a returning `NoReturn` - the IDE may then understand it.

**Comment by leandropls** [comment]
@pgjones this does seem to be the best approach. Thanks!

**Comment by allanlewis** [comment]
This approach doesn't help in PyCharm as of v2020.1.2. Perhaps we could make `Aborter` _return_ the exception instead of raising it? (I mean optionally, the default can stay as the status quo. Then I could do something like:

```py
try:
    foo = this_might_fail()
except ValueError:
    raise flask.make_exc(400)

do_something_with(foo)
```

PyCharm would complain about the last line above as `foo` might not be assigned if we used `flask.abort`, but if I `raise` something it won't as it can see that the function would end at that point.

My only solution at the moment is to do `raise flask.abort(...)`, which is far from ideal. I could wrap that in a function, but that's not great either:

```py
def make_exc(*args, **kwargs):
    try:
        flask.abort(*args, **kwargs)
    except HTTPException as exc:
        return exc

try:
    try:
    foo = this_might_fail()
except ValueError:
    raise flask.make_exc(400)
```

**Comment by pgjones** [comment]
I'd caution against changing the `abort` function return or signature, instead

```python
from werkzeug.exceptions import default_exceptions

abort(400)
# becomes
raise default_exceptions[400]()
```

Ideally though we'll type hint Werkzeug and this will go away - @allanlewis do you know why the stub doesn't work with PyCharm now?

@davidism maybe Werkzeug's `HTTPException` should allow a `code` keyword argument to allow `raise HTTPException(code=400)`

**Comment by davidism** [comment]
@allanlewis Note that the PyCharm issue you commented on where you said that the maintainers don't care to provide a fix for this was in fact opened by one of our core maintainers, and followed by another one (me). This is not an issue with Werkzeug, it's an issue with PyCharm, which has the huge complicated task of providing generic type and execution inference for all libraries in a dynamic language.

I usually don't use `abort` anyway, I just import the exception I want and raise it. pgjones offers a similar alternative.

@pgjones I don't think it's advisable to start implying raising `HTTPException` directly is good. This would also break Flask's error handler system, which relies on the type of the exception, not the code.

I don't plan to make any changes at this time, beyond adding type hinting. If existing hinting or PyCharm's system isn't working, that needs to be reported to typeshed or PyCharm.

**Comment by allanlewis** [comment]
Thanks for your responses, @pgjones & @davidism.

> Note that the PyCharm issue you commented on where you said that the maintainers don't care to provide a fix for this

For the record, I don't think that's a good summary of [what I said][1] on the PyCharm issue. I said that this project didn't seem willing to provide _an alternative solution_ - I'm not suggesting making a breaking change, or that anything is broken.

My view on making this PyCharm's problem is that having functions that always raise makes it difficult for any static analysis system; having said that, I'm not sure what Pylint does. My suggestion is that we make things easier for the huge number of PyCharm users by providing an officially-supported way of directly raising an exception with a given code with a given message.

Maintainers have every right to disagree, but FWIW I feel the tone here is getting a little confrontational.

[1]: https://youtrack.jetbrains.com/issue/PY-11199#focus=streamItem-27-4222580.0-0
