### ISSUE TITLE
Catch-all route does not work if url has another handler even if method is different

### ISSUE THREAD

**Issue by ekor15** [pallets/flask#3187]
I want to set up a handler for all URLs that will handle the OPTIONS preflight requests
Following the "catch-all" example (@app.route("/<path:path>", methods=['OPTIONS']))

I found that if the server gets a route that has a handler with a different method neither of the handlers are called
 
### Expected Behavior
The OPTIONS request should have been routed to the "wildcard" OPTIONS handler

```python
from unittest import TestCase
from flask import Flask
from hamcrest import assert_that, equal_to
class TestSitePreferencesService(TestCase):
    def test(self):
        app = Flask(__name__)

        @app.route("/<path:path>", methods=['OPTIONS'])
        def catch_all(path):
            return "catch_all"

        @app.route("/specific", methods=['GET'])
        def specific():
            return "specific"

        client = app.test_client()
        result = client.options('/some/url')
        assert_that(result.data.decode('utf-8') , equal_to('catch_all'))

        result1 = client.get('some/url')
        assert_that(result1.status_code , equal_to(405)) # this identifies the global handler but the method is wrong this is expected

        result2 = client.options('/specific')
        # looks like this is not going to ether of the handlers
        assert_that(result2.data.decode('utf-8'),equal_to('catch_all')) # fails
```

### Actual Behavior
The request was not routed to the correct handler OPTIONS handler

### Environment

* Python version:3.7
* Flask version:1.0.2
* Werkzeug version:0.15.2

**Comment by carc1n0gen** [comment]
I'm pretty sure routes are matched in order of creation.  So if you want to ensure the specific one is hit, you'll need to move it above the catch-all one

**Comment by jab** [comment]
I believe routes are matched in order of specificity, not creation, in which case this will never work. Can you use an @app.before_request func to accomplish this instead?

**Comment by ekor15** [comment]
First, thank you for the quick reply
@carc1n0gen - I did register the OPTIONS handler first - so it should have hit it

@jab - I think you are correct, flask does create an OPTIONS handler for each registered route

Is there any way to avoid this? 

Also, I cannot use before_request because my real implementation adds CORS headers to the response - and the before_request happens before the response is created and has no access to it

**Comment by ekor15** [comment]
Found the solution - adding 
 @app.route("/specific", methods=['GET'], provide_automatic_options=False) to the route

Documentation:
http://flask.pocoo.org/docs/1.0/api/#flask.Flask.add_url_rule

I really don't understand why this is the default behavior...

**Comment by carc1n0gen** [comment]
You misunderstood me. I said define the `/specific` route first.  (Well I only said "specific" but I thought that was clear enough.

In your example you define the catch all first. Just switch  the order.
