### ISSUE TITLE
Flask Session variable not available in threads

### ISSUE THREAD

**Issue by HourGlss** [pallets/flask#3193]
For example of passing via a Queue that does not work. https://github.com/HourGlss/FlaskSSE/blob/master/sse/sse.py

### Expected Behavior
Session is a global variable

### Actual Behavior
When passed via a queue the keys and associated values are dropped. When attempting to access globally, no keys are available even if they had been added by endpoints

### Environment

* Python version: 3.7
* Flask version: Default install
* Werkzeug version: Default install

**Comment by ThiefMaster** [comment]
http://flask.pocoo.org/docs/1.0/advanced_foreword/#thread-locals-in-flask

**Comment by HourGlss** [comment]
Do you have a good discord to ask in? I'd love some help! I am Xyf#1337 on discord, I'd love to chat! Please.

**Comment by Set4now** [comment]
def long_task(i):
    
        # global session
        print "started executing for {}".format(i)
    
        time.sleep(5)
        print "working"
        # session['step1'][i]["status"] = 'Completed'

**Comment by Set4now** [comment]
how to access the session inside thread?
