### ISSUE TITLE
Changelog button on documentation does not work on Stable

### ISSUE THREAD

**Issue by eamanu** [pallets/flask#3201]
### Expected Behavior

On documentation e.g. http://flask.pocoo.org/docs/1.0/config/#ENV when I 
press changelog button will show some information.

### Actual Behavior

When I press changelog button doesn't show any news.  This is working on unstable
documentation, but will be great if that is working on stable documentation too. 

### Environment

* Flask version: 1.0
* Documentation: http://flask.pocoo.org/docs/1.0/config/#ENV

**Comment by davidism** [comment]
There are no changes, so it's an empty container. You can report this to https://github.com/davidism/sphinxcontrib-log-cabinet if you'd like.

**Comment by eamanu** [comment]
Hmm actually there is a change. If you go to stable and then on unstable docs for ENV variable you will show the difference:

The stable version:
![image](https://user-images.githubusercontent.com/7605307/57864402-32c32c80-77d2-11e9-97ee-c99a2b530aed.png)

The development version:
![image](https://user-images.githubusercontent.com/7605307/57864444-45d5fc80-77d2-11e9-98af-dd9eca4042ac.png)

**Comment by davidism** [comment]
Because that's how the extension works: stuff for the current version is displayed, stuff for past versions is hidden.

**Comment by eamanu** [comment]
Oh, yes. I understand the logic :-) sorry
