### ISSUE TITLE
Convert make_test_environ_builder into EnvironBuilder subclass

### ISSUE THREAD

**Issue by davidism** [pallets/flask#3207]
Werkzeug's `EnvironBuilder` gained a `json_dumps` attribute, but Flask doesn't have an `EnvironBuilder` subclass right now to take advantage of that, and there's no way to configure the `Client` to use a different builder class anyway. Might be good to refactor `flask.testing.make_test_environ_builder` to be an `EnvironBuilder` subclass at some point, rather than a factory wrapper.

_Originally posted by @davidism in https://github.com/pallets/flask/pull/3181#issuecomment-493489553_

**Comment by lordmauve** [comment]
I'm looking at this.
