### ISSUE TITLE
Don't require ssl module

### ISSUE THREAD

**Issue by davidism** [pallets/flask#3211]
Python can be compiled without certain modules, including `ssl`. It's somewhat common for that to happen when users compile Python from source and don't have the `libssl` headers set up. `flask.cli` imports `ssl` unconditionally, but it's only for optional SSL cert support in the dev server, so this can be guarded with `except ImportErrror`. Werkzeug already has such a workaround, although it's a little more complicated than what needs to be done in Flask.

If no `ssl` module is imported, using the cert-related options in the CLI should raise a usage error.

**Comment by t3ja** [comment]
Hey David,

I'm trying to make this my first contrib to flask.

From what I understand:
- `import ssl` needs to be removed from `flask/cli.py`
- `CertParamType.convert` method and `_validate_key` function should try to import ssl module and raise a usage error in case of an ImportError

Is there anything else I'm missing?

**Comment by davidism** [comment]
Hi, while I appreciate that you'd like to start contributing, this task is tagged for an upcoming sprint.

As to the questions, I'd expect to use the same except guard that's used for other optional imports, and check whether its none when validating.

**Comment by t3ja** [comment]
> Hi, while I appreciate that you'd like to start contributing, this task is tagged for an upcoming sprint.

So, Can I still make the changes and create a PR against the current `1.0.x` branch? 
Or should I just ignore this issue and move on for now?
(maybe until there's a 1.1.0 branch setup for the milestone)
