### ISSUE TITLE
Static Analysis for Security Issues and Vulnerabilities

### ISSUE THREAD

**Issue by PulkitMittal22** [pallets/flask#3217]
The attached report shows the vulnerabilities found in the code. It also shows the line of code and python file which needs fixation for the security Issues.

[Flask.zip](https://github.com/pallets/flask/files/3218971/Flask.zip)

**Comment by davidism** [comment]
This is not an acceptable format for a bug report, and not a responsible way to report potential security issues. If you believe you have found an unpatched security issue, please email security@palletsprojects.com. Be sure to include a writeup in your own words of a single issue, not a huge dump from some automated tool.
