### ISSUE TITLE
url_for produces relative links with nontrivial APPLICATION_ROOT

### ISSUE THREAD

**Issue by rosekunkel** [pallets/flask#3219]
### Expected Behavior

`url_for` should consistently produce urls which are absolute with regard to the server root, i.e., they should start with a `/`.

```python
app = Flask(__name__, static_url_path='')
url_for('static', filename='some_static_file')
```

### Actual Behavior

When running under gnunicorn with `APPLICATION_ROOT='/myapp/'`, the `url_for` call produces the URL `myapp/some_static_file`, while when running under werkzeug with `APPLICATION_ROOT='/'`, the `url_for` call produces the URL `/some_static_file`.

This is a problem, because, combined with [this werkzeug issue](https://github.com/pallets/werkzeug/issues/1132), there's no straightforward way to use `url_for` in templates for both development and production: `{{ url_for('static', filename='some_static_file') }}` produces `myapp/some_static_file` in production, which fails, while `/{{ url_for('static', filename='some_static_file') }}` produces `//some_static_file` in development, which fails.

### Environment

* Python version: 3.6.5
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
`APPLICATION_ROOT`, along with `SERVER_NAME`, is only used when generating URLs outside a request (such as generating external URLs for an email). It appears to still be working as expected.

```python
app.config["SERVER_NAME"] = "example.com"
app.config["APPLICATION_ROOT"] = "/app"

with app.app_context():
    print(url_for("static", filename="test.txt", _external=True))
    # http://example.com/app/static/test.txt
```

If you're using Gunicorn to serve a Flask app under a non-root path, you need to configure Gunicorn to set the WSGI `SCRIPT_NAME` correctly. One way to do this is to set the `SCRIPT_NAME` environment variable.

```
SCRIPT_NAME=/app gunicorn -b 127.0.0.1:5000 -w 2 example:app
```

If you're using the dev server, you can use `DispatcherMiddleware` to configure the `SCRIPT_NAME` in a similar way. You can also use this with Gunicorn, if you don't want Gunicorn to handle `SCRIPT_NAME` itself.

`dev_app.py`:

```python
from werkzeug.exceptions import NotFound
from werkzeug.wsgi import DispatcherMiddleware
from myproject import app

app.wsgi_app = DispatcherMiddlware(NotFound(), {"/app": app.wsgi_app})
```

```
export FLASK_APP=dev_app.py
export FLASK_ENV=development
flask run
```

**Comment by davidism** [comment]
#2759 is open for better documentation about this.

**Comment by bsolomon1124** [comment]
Not sure if gevent as wsgi server supports `SCRIPT_NAME`. For some reason it looks to simply [set that value empty](https://github.com/gevent/gevent/blob/b8bca6fa5eae9768b0f3ee25d60464b0a517b46b/src/gevent/pywsgi.py).

**Comment by davidism** [comment]
I'm not sure what part of Gunicorn that is, but it does indeed support `SCRIPT_NAME`, as shown above.

**Comment by bsolomon1124** [comment]
@davidism I am actually talking about using gevent as standalone wsgi app server (as you allude to, it is more commonly used as a gunicorn worker class):

```python
from flask import Flask, redirect, url_for
from gevent.pywsgi import WSGIServer

app = Flask(__name__)

@app.route('/foo')
def hello_world():
    return "hi"

@app.route("/favicon.ico")
def favicon():
    return redirect(url_for("static", filename="favicon.ico"))

if __name__ == "__main__":
    WSGIServer(('127.0.0.1', 5000),application=app).serve_forever()
```

```bash
$ SCRIPT_NAME='/foo' python hello.py
```

In this case `url_for("static", filename="favicon.ico")` will still generate the absolute path `/static/favicon.ico`.  If the app reverse-proxied by something like nginx which proxy-passes `/foo` to gevent, that path should be `foo/static/favicon.ico`.

It is the end of a long day and I am probably not thinking about this the right way, though.

**Comment by davidism** [comment]
Oh, that's gevent. This sounds like an issue with gevent then, or with your setup of gunicorn and gevent. A closed issue on the Flask issue tracker is not the best place to get answers about that. :wink:

**Comment by bsolomon1124** [comment]
@davidism Please let me give another example here.

Say that a template contains

```html
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
```

In this case (using example above) you have `href="/static/favicon.ico"` in HTML with no other contextual information for the browser to go off of.  If your reverse proxy server is proxy-passing requests to `www.host.example.com/foo` to your application's _root_, then this href should be `/foo/static/favicon.ico`.  That seems to be independent of gunicorn vs gevent, no?  Taking gunicorn as an example, could you help me understand through what mechanism `SCRIPT_NAME` makes its way into `url_for()`?

**Comment by davidism** [comment]
When `Flask.url_map` is bound to the current `request.environ`, it will append `SCRIPT_NAME` to any URL it generates. Whether `SCRIPT_NAME` is set is not something Flask controls, only uses.
