### ISSUE TITLE
suspicious/unexplained `del <local_variable>` in last line of function

### ISSUE THREAD

**Issue by jab** [pallets/flask#3225]
The following line contains a `del <local_variable>` as the last line of the function (inside a `finally` block):
https://github.com/pallets/flask/blob/2c68f86336dc8729f58e8e19af0f49c269c1cfaa/flask/cli.py#L135

This looks suspicious since there is usually no need to `del` a variable that is local to a function in its last line. If this is unintended it should be removed, otherwise there should probably be a comment in the code explaining why this is necessary?

**Comment by ThiefMaster** [comment]
I think it's something about avoiding a circular dependency that could not be resolved by the GC.

**Comment by RonnyPfannschmidt** [comment]
This is required to deal with the gc

**Comment by davidism** [comment]
Can't hurt to add a comment explaining that. I think it has to do with the traceback containing a reference to the function that contains it, which GC doesn't catch when the function ends. I think there's a section in the Python docs about it. Might be good to check if this is done consistently, also in Werkzeug.
