### ISSUE TITLE
unused import: werkzeug.datastructures:Range

### ISSUE THREAD

**Issue by jab** [pallets/flask#3226]
The following line contains an unused import:
https://github.com/pallets/flask/blob/2c68f86336dc8729f58e8e19af0f49c269c1cfaa/flask/helpers.py#L26

Specifically, `Range` is unused.

**Comment by jab** [comment]
Before removing this, just need to confirm that this is unintentional, i.e. no code should be importing `Rang`e from `flask.helpers` but rather should import it directly from `werkzeug.datastructures`.

**Comment by davidism** [comment]
Should be fine

**Comment by rtilk89** [comment]
I'll give this issue a shot

**Comment by jon-stumpf** [comment]
Submitted #3238 .
