### ISSUE TITLE
suspicious unexplained `except: raise`

### ISSUE THREAD

**Issue by jab** [pallets/flask#3227]
The following two lines:
https://github.com/pallets/flask/blob/2c68f86336dc8729f58e8e19af0f49c269c1cfaa/flask/_compat.py#L100
do
```python
except:
    raise
```
which looks like a no-op. Is this actually doing something? If not remove, if so let's add a comment explaining.

**Comment by ThiefMaster** [comment]
`try: ... except: raise` looks like a no-op to me, but it may be targetting something pypy-specific so I would not touch this without first checking with the original author or someone familiar with the pypi issue mentioned in the comments about there.

In any case, a bare `except:` is perfectly fine as long as the block contains a `raise` to reraise the same exception (which is the case here).

**Comment by gokcegrbl** [comment]
I will work on this issue as part of the @twosigma sprint.

**Comment by davidism** [comment]
Based on what @ThiefMaster found, I don't know if there's anything to work on here, it might just be an invalid finding. Might be good to check PyPy 6 and 7 releases to see if the issue still happens.

**Comment by gokcegrbl** [comment]
Makes sense, will check as suggested.
