### ISSUE TITLE
Meta: run tox -e stylecheck on Azure Pipeline

### ISSUE THREAD

**Issue by lordmauve** [pallets/flask#3228]
In the [contributing guide](https://github.com/pallets/flask/blob/master/CONTRIBUTING.rst) we request people to use Black to autoformat their code via pre-commit.

However, [there is no check for this on Azure Pipelines](https://github.com/pallets/flask/blob/master/.azure-pipelines.yml), meaning it is not checked automatically by GitHub for each pull request. This means style issues can be merged, requiring unrelated style fixes in later commits.

In tox.ini there is a [stylecheck target](https://github.com/pallets/flask/blob/2c68f86336dc8729f58e8e19af0f49c269c1cfaa/tox.ini#L46). We should configure this to run on Azure Pipelines.

**Comment by davidism** [comment]
I didn't have this enabled yet because I was waiting to get the pr backlog down. Now that it is, we can turn this on.

We can also copy the full config from Werkzeug and start applying that.

**Comment by lordmauve** [comment]
Also, I note that `tox -e stylecheck` makes changes to your local clone, which was unexpected. Maybe change it to run `black --check` directly?
