### ISSUE TITLE
Should _get_exc_class_and_code method have param entry for the docstring?

### ISSUE THREAD

**Issue by aligoren** [pallets/flask#3252]
Currently the `_get_exc_class_and_code` method does not have `:param:` entry for `exc_class_or_code`.

If so, I can add `:param:` entry for methods which does not contain `:param:` entry.

https://github.com/pallets/flask/blob/d4b688bd035b9704b3168b28fed39c8fcfe3b997/src/flask/app.py#L1334-L1346

**Comment by davidism** [comment]
Sure, more docs are welcome.

**Comment by aligoren** [comment]
@davidism Ok. Thanks. I think this should be only the one. The others need a new issue because I mentioned a method name in this issue.
