### ISSUE TITLE
Refactoring explain_template_loading_attempts method in debughelpers.py

### ISSUE THREAD

**Issue by aligoren** [pallets/flask#3254]
Before starting, I'm so sorry because this issue can be totally ridiculous.

Hi. I've been doing a review of the Flask code base for a while.

I found this method

https://github.com/pallets/flask/blob/d4b688bd035b9704b3168b28fed39c8fcfe3b997/src/flask/debughelpers.py#L124-L169

I'm also using SonarQube to review codes. SonarQube warned me about Cognitive Complexity. There is documentation here;

https://www.sonarsource.com/docs/CognitiveComplexity.pdf

For example,

https://github.com/pallets/flask/blob/d4b688bd035b9704b3168b28fed39c8fcfe3b997/src/flask/debughelpers.py#L130

this part can be changed like that.

```python
if reqctx and reqctx.request.blueprint is not None:
```

The other thing is;

https://github.com/pallets/flask/blob/d4b688bd035b9704b3168b28fed39c8fcfe3b997/src/flask/debughelpers.py#L146-L150

this part can be changed like that.

```python
detail = "no match"
if triple is not None:
   detail = "found (%r)" % (triple[1] or "<string>")
   total_found += 1
```

I think we can say; if the triple variable is **None**, don't run this `total_found += 1` statement.

The last one is;

https://github.com/pallets/flask/blob/d4b688bd035b9704b3168b28fed39c8fcfe3b997/src/flask/debughelpers.py#L154-L159

I think this part can be changed too. Because `total_found` variable initialized with **0** value.

So, there will be two situations always. for **0** or for **> 1**.

When `total_found` is 0 or 1, the `seems_fishy` will be True. So, we may don't need to reassign this variable for each control flow. Instead of that, we can change this code like below;

```python
info_msg = "Error: the template could not be found."
seems_fishy = True
if total_found > 1:
   info_msg = "Warning: multiple loaders returned a match for the template."
```

**Comment by jab** [comment]
Thanks for taking the time to try to contribute! It’s absolutely not ridiculous to try to make code improvements like the ones you mention. Could you please submit pull request(s) with your proposed changes? And try to put only related changes in each pull request. I think that would make it easier for maintainers to review what’s being proposed. In the meantime, I’ll close this issue in favor of the more targeted PRs.
