### ISSUE TITLE
import urlparse breaks app.cli.command

### ISSUE THREAD

**Issue by landergate** [pallets/flask#3262]
```python
from flask import Flask
import urlparse

app = Flask(__name__)


@app.cli.command()
def hello():
    print("Hello World")


if __name__ == "__main__":
    app.run()
```

---

### Expected Behavior

```bash
ubuntu@bionic:/reproduce# flask hello
Hello World
```

### Actual Behavior

```bash
ubuntu@bionic:/reproduce# flask hello
Usage: flask [OPTIONS] COMMAND [ARGS]...

Error: No such command "hello".
```

### Environment

* Python version: 3.6.7
* Flask version: 1.0.3
* Werkzeug version: 0.15.4

**Comment by jab** [comment]
Did you set FLASK_APP?

http://flask.pocoo.org/docs/1.0/cli/#application-discovery

**Comment by landergate** [comment]
Nvm. It's a reaction to any ModuleNotFoundError.
Since python3, `urlparse` module was renamed to `urllib.parse`.
