### ISSUE TITLE
Flask object Issue: Assertation error on python 2.7.14 in Werkzeug 0.15.4

### ISSUE THREAD

**Issue by Ahmedest61** [pallets/flask#3268]
### Actual Behavior

When trying to create new flask object, I get following error:

```python
>>> from flask import Flask
>>> flask_app = Flask(__name__)
python: ../Python-2.7.14/Python/symtable.c:1319: symtable_visit_params: Assertion `arg->v.Name.ctx == Param || (arg->v.Name.ctx == Store && !toplevel)' failed.
Aborted

```

### Environment

* Python version: 2.7.14
* Flask version: 1.0.3
* Werkzeug version: 0.15.4

**Comment by ThiefMaster** [comment]
sounds more like your python installation is somehow broken

**Comment by Ahmedest61** [comment]
I'm trying to run a webserver inside linux of an FPGA board. I've tried with python 3.7.3 but faced the same problem. Other packages including scapy working fine. :(

**Comment by ThiefMaster** [comment]
Fun. But that sounds very much like a problem with your environment...

**Comment by ruslan-gennadievich** [comment]
I have same problem with my sama5d27 board (arm)
Python 2.7.14

**Comment by davidism** [comment]
duplicate of pallets/werkzeug#1553
