### ISSUE TITLE
Allow accessing CLI command name from Flask CLI app factory

### ISSUE THREAD

**Issue by justanr** [pallets/flask#3289]
### Expected Behavior

The selected command should be available in the application factory provided to the click integration.

I recently started adding instrumentation to an application, however when I run most CLI commands I don't want to trigger the instrumentation to be initialized. However by the time I gain access to the application it's too late to turn it off (things have been mucked with and monkeypatched, etc). It seems like the easiest thing to do is allow the selected command to be considered when running the application factory so the factory can make informed decisions about what should/shouldn't be initialized during application setup based on what I'm attempting to do.

There is the possibility of doing various things such as:

- adding a `--no-trace` flag to the top level command
- using a custom configuration when executing CLI commands _other_ than run
- probably some other gross things

I managed to work around this not being available out of the box by adding the following to a custom flask group (something we were already using):

```python
def get_command(self, ctx, name):
    # arguably belongs on ScriptInfo.data instead of just shoving it on there
    ctx.ensure_object(ScriptInfo).command = name
    super().get_command(ctx, name)
```

### Actual Behavior

Unless I'm missing something, it's not available through vanilla means.

### Environment

* Python version: 3.7
* Flask version: 1.0.2
* Werkzeug version: 0.14.1
* Click version: 6.7

**Comment by davidism** [comment]
I'm sorry, I can't tell what issue with Flask you're trying to describe.

**Comment by justanr** [comment]
What I want to do is do further configuration on my application depending on if I'm running the server OR running a CLI command (shell, routes, using flask-alembic, etc) however it doesn't appear that the `flask <command name>` is exposed to the application factory that can be given to the click integration via `@click.group(class=FlaskGroup, create_app=create_app)`.

I can't trigger the setup in the command itself because the application has already been created by that point and creating a second app seems like it would be error prone at best.

Instead, I'd like to be able to access some attribute on the ScriptInfo that would give this information similar to my workaround above.

Maybe it's better to discuss this in `#pocoo`?

**Comment by davidism** [comment]
The CLI needs to create the application to understand what commands are available to it. It looks like you already have a workaround for your specific project. You can also look at `sys.argv` in the factory.

It's not clear to me right now that this is something that needs to be changed in Flask, or even what that change would be. I am very reluctant to introduce more complexity into the CLI code.

**Comment by justanr** [comment]
>  It looks like you already have a workaround for your specific project.

I do, but in implementing it, it seemed like a hole in the API but then again maybe I'm just doing something weird.

> You can also look at sys.argv in the factory.

Seems odd at best to consult a lower level system when a higher level one can provide it and that means we'd potentially need to parse `sys.argv` again (because iirc some of the flask commands make changes to this, or am I remembering something from an older version/werkzeug?)

> It's not clear to me right now that this is something that needs to be changed in Flask, or even what that change would be.

As far as I can tell, it would be a change to ScriptInfo (add a `command` field) AppGroup.get_command to attach the command we're wanting to run to the ScriptInfo.

I understand not wanting to introduce more complexity into the CLI code though. 

It's possible I'm the only one (or one of the few people) trying to do this so if you feel the use case is too specific or not a good fit, feel free to close this issue. Otherwise I'm happy to open a PR to add these changes.

**Comment by davidism** [comment]
Thanks for your interest. Your workaround seems fine. I don't think Flask should be changed for this right now.
