### ISSUE TITLE
Warning on old documentation / SEO

### ISSUE THREAD

**Issue by exic** [pallets/flask#3300]
I just found out that there is a newer page for documentation after strolling around on flask.pocoo.org for quite a while 🙈 I think there should be some more links on pocoo.org to the newer docs so that people don't accidentally read outdated stuff. Maybe someone also has ideas how to improve search engine stuff since pallets flask docs seem to be really hard to find right now.

### Expected Behavior

Searching for "flask documentation" on google.com or duckduckgo.com, https://flask.palletsprojects.com/en/1.1.x/ should be listed higher up, but at least the documentation on http://flask.pocoo.org/docs/1.0/ should have links to the newer documentation.

### Actual Behavior

Pallets documentation is hard to find and the only link from Pocoo to Pallets seems to be on http://www.pocoo.org/ itself.

**Comment by davidism** [comment]
I'm working on it
