### ISSUE TITLE
Flask documentation links to a page 'Extension Registry' which redirects to the generic Flask website

### ISSUE THREAD

**Issue by jwg4** [pallets/flask#3304]
### Expected Behavior
The Flask docs should link to the correct page for the Flask Extension registry, or, if this no longer exists, references to it  should be removed from the docs.

### Actual Behavior
The page about extensions at https://flask.palletsprojects.com/en/1.1.x/extensions/ has a link to http://flask.pocoo.org/extensions/ which redirects to https://palletsprojects.com/p/flask/ This latter page does not contain any info about Flask extensions, nor does it indicate where that might be found.

### Environment

* Flask version: docs to Flask 1.1. Also current docs on master.

**Comment by kevincal** [comment]
Bump
