### ISSUE TITLE
`flask run` not using ENV variable set in code.

### ISSUE THREAD

**Issue by klondikemarlen** [pallets/flask#3307]
### Expected Behavior
When using `flask run` I expect it to use the variables I set in my code.

```python
from flask import Flask

class DevelopmentConfig(object):
    ENV = 'development'
    DEBUG = True

app = Flask(__name__)
app.config.from_object(DevelopmentConfig)

# then using `flask run`
```

### Actual Behavior
It uses the default 'production' enviroment with debug off.

> * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
>  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

### Environment

* Python version: 3.7.3
* Flask version: 1.0.3
* Werkzeug version: 0.15.4

Yes I realize that in the API documentation it explicitly says this won't work, yet it used to in older version of flask (at least when using app.run()). Perhaps this is more a of feature request?

**Comment by klondikemarlen** [comment]
This is the hack I'm currently using to make it work in my code. Well `flask serve` instead of `flask run`.
```python
import os

import click
from click import pass_context
from flask.cli import with_appcontext, run_command
from flask import current_app

@click.command('serve', context_settings={"ignore_unknown_options": True})
@with_appcontext
@click.argument('args', nargs=-1)
def serve(args):
    """Alias for 'flask run'."""
    os.environ['FLASK_ENV'] = current_app.config['ENV']
    ctx = run_command.make_context('serve', list(args))
    run_command.invoke(ctx)
```

**Comment by davidism** [comment]
Config is not the same as env vars. These vars are intended to be set in the env, outside Flask before it runs.

**Comment by klondikemarlen** [comment]
:( I kind of like keeping my code inside python, but fair enough.

**Comment by carc1n0gen** [comment]
@klondikemarlen no outside code needed,  just run:

`FLASK_ENV=development flask run`

**Comment by klondikemarlen** [comment]
@carc1n0gen
But why not just make it `flask run`? And have it pull the data from my config so I don't have to type that in? I'm lazy ok. :P Plus I don't really want to learn OS specific setup commands (exporting variables is different on each OS)  when I can just run it natively in Python. I mean my code totally works. It hacks the FLASK_ENV directly from Python then lets me run it with `flask serve`. I'm curious why you don't just build that in to `flask run`? I mean other than it taking some amount of work :)

**Comment by carc1n0gen** [comment]
@klondikemarlen then make a `.flaskenv` file containing

```bash
export FLASK_ENV=development
```

The flask cli will look for and load env vars from that file automatically.  You can use config values if you reall want to.  FLASK_ENV=development is just a shortcut to these config options:

```python
DEBUG = True
PROPAGATE_EXCEPTIONS = True
TEMPLATES_AUTO_RELOAD = True
# maybe more, these were just ones I know off the top of my head
```

**Comment by klondikemarlen** [comment]
@carc1n0gen 
Thanks for the tip! Although, isn't that OS specific?

**Comment by carc1n0gen** [comment]
The .flaskenv isn't OS specific.  It's loaded with the dotenv package, not anything related to the OS.  And for the debug, ya you're right.  It's a side effect of FLASK_ENV defaulting to production, which forces debug to false.  I guess I never noticed that, but it is mentioned in the [docs](https://flask.palletsprojects.com/en/1.1.x/config/#DEBUG):

>This is enabled when ENV is 'development' and is overridden by the FLASK_DEBUG environment variable. It may not behave as expected if set in code.

Same disclaimer is present for the `ENV` config key.

It's just a common convention when building web applications that things like development|testing|production be set by env vars.  See `NODE_ENV` in nodejs applications for example.

**Comment by carc1n0gen** [comment]
(not to mention you're going to need env vars anyway, when it comes to things like SECRET_KEY, database credentials, etc.  because you're not committing those things to your repo right 😉 )

**Comment by ThiefMaster** [comment]
@carc1n0gen the config shouldn't be the the repo anyway :) and i don't think there's much benefit in putting that stuff in env vars unless you use containers

**Comment by carc1n0gen** [comment]
@ThiefMaster I like my "get the developer going as quick as possible" dev default configs to be in the repo, with "secret" things loaded from env vars in production.  Env vars are super nice and easy to set per app with things like supervisord. Not only beneficial for containers.

**Comment by ThiefMaster** [comment]
i agree for the default config - but i think for the rest it's just as easy to simply use `app.config.from_envvar()` and point your env var to an actual config file.

btw, regarding being os-specific: most likely you don't want to support anything besides linux (dev/prod) and osx (dev) anyway :)

**Comment by klondikemarlen** [comment]
Thanks for all the info! I'm not that familiar with standards and using environmental variables. That said I do have a separate private_config.py that is generated via os.urandom into a template. That way nobody is tempted to just use 'secret' as the secret key :P. I kind of like keeping everything in Python.

**Comment by Ryze-Ca** [comment]
会199993311 

---Original---
