### ISSUE TITLE
static file would not send to browser correctly 

### ISSUE THREAD

**Issue by heavenshell** [pallets/flask#331]
Hi, 

I've got a issue about static file.

When I put css file in /static/css/style.css in static directory and I described view function with `Variable Rules`.
Please see sample code on https://gist.github.com/1254213

`GET /static/css/style.css` request dispatch to view function and css file did not send to browser correctly.
I expected to `GET /static/css/style.css` should send css file to browser, not dispatch to view function.

Regards.

**Comment by hyunchel** [comment]
Just to note, this is still relevant issue to the current [`master`](bbd6c8c791ffa0f9f30f31d17e47e8fe8e587526).

**Comment by jeffwidman** [comment]
Forked the gist just in case the OP accidentally removes it in the future: https://gist.github.com/jeffwidman/11d8b8d952abca30756ca4ba01909143

**Comment by davidism** [comment]
We could give extra weight to the `path` converter, it seems weird to only treat it as twice as important as a single segment rule.  There's no general way to solve this, although we could pick some weight where it would be less likeley for there to be a rule that complex.

**Comment by davidism** [comment]
We could allow passing a different rule class to `add_url_rule` and override `Rule.match_compare_key` to return something like `1, float('-inf'), 200`.  But that seems a little extreme for just this.  I'm actually surprised this hasn't come up more often, `/<string>(/<string>)+` seems like it would be a common rule.

@pallets/devteam-flask
