### ISSUE TITLE
Dynamic Subdomain Value Unfilled

### ISSUE THREAD

**Issue by LewdNeko** [pallets/flask#3316]
### Expected Behavior
The bot value should be filled with the current subdomain.
```python
@app.route('/', subdomain='<bot>')
def index(bot):
    return bot  # Or do something else
```

### Actual Behavior
The value is not filled, it is just an empty string.
This also happens if inside a blueprint:
```python
bp = Blueprint('foo', __name__, subdomain='<bot>')
@bp.route('/')
def my_route(bot):
    return bot  # Or do something else
```
```pytb
N/A
```

### Environment

* Python version: 3.6.6
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

*Yes, nginx and my DNS are configured correctly*

**Comment by amardeep24** [comment]
I was not able to replicate this, for me it is working fine. Did you add this:
`app = Flask(__name__, subdomain_matching=True)
app.config['SERVER_NAME'] = "<your_domain.com>:<port>"`  ?

**Comment by LewdNeko** [comment]
Yes, however it has been a while since I last looked at this. I will check later and update if I have / have not done so.

**Comment by lepture** [comment]
```
Flask version: 1.0.2
Werkzeug version: 0.14.1
```

(Off Topic) When reporting an issue, you'd better try the latest version at first. Because the problem you are reporting may be solved already.

**Comment by davidism** [comment]
I can't reproduce this issue. With the following code, going to `flask.localhost:5000` works as expected.

```python
from flask import Blueprint
from flask import Flask

app = Flask(__name__, subdomain_matching=True)
app.config["SERVER_NAME"] = "localhost:5000"

bp = Blueprint("index", __name__, subdomain="<name>")


@bp.route("/greet", subdomain="<name>")
def hello(name):
    return f"Hello, {name}"


app.register_blueprint(bp, url_prefix="/test")
```
