### ISSUE TITLE
Version tag mismatch in link to example projects from docs

### ISSUE THREAD

**Issue by neirbowj** [pallets/flask#3320]
### Scenario

As of v1.1.1.

1. Navigate to the Flask docs via the Pallets Project site.
2. Progress to [Tutorial :: Keep Developing!](https://flask.palletsprojects.com/en/1.1.x/tutorial/next/)
3. Follow the link to [example project](https://github.com/pallets/flask/tree/1.1.2.dev0/examples/tutorial)

### Expected Behavior

The version tag in the link matches the documentation version tag, and/or the target URL leads somewhere useful.

### Actual Behavior

Link target version is not the same as the doc version, and it refers to a development version that has not yet been tagged (404).

### Environment

N/A

**Comment by neirbowj** [comment]
The same problem affects the "[...tutorial project...example...](https://github.com/pallets/flask/tree/1.1.2.dev0/examples/tutorial)" link on the [the main tutorial page](https://flask.palletsprojects.com/en/1.1.x/tutorial/).

**Comment by greyli** [comment]
Thanks for reporting on this, #3321 will fix this issue.
