### ISSUE TITLE
`flask run` in debug mode fails with `No module named C:\programs\Python37\Scripts\flask`

### ISSUE THREAD

**Issue by sorgloomer** [pallets/flask#3327]
### How to reproduce

 * Have flask installed
 * Open up a terminal in an empty folder
 * run `set FLASK_DEBUG=1 && flask run` (yep, its windows)

### Expected Behavior
Flask should attempt to start in debug mode, should fail with `Error: Failed to find Flask application or factory in module "app". Use "FLASK_APP=app:name to specify one.` or if you have a valid app in the folder it should start normally in debug mode. Should not fail with `No module named C:\programs\Python37\Scripts\flask`

### Actual Behavior
Flask fails earlier, with message: `No module named C:\programs\Python37\Scripts\flask`

### Console dump

```
C:\workspace\aliz\temp\flaskbug>set FLASK_DEBUG=1 && flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
c:\programs\python37\python.exe: No module named C:\programs\Python37\Scripts\flask
```

### Environment

```
C:\workspace\aliz\temp\flaskbug>python --version
Python 3.7.4

C:\workspace\aliz\temp\flaskbug>python -m pip show flask
Name: Flask
Version: 1.1.1
...

C:\workspace\aliz\temp\flaskbug>python -m pip show Werkzeug
Name: Werkzeug
Version: 0.15.5
...

C:\workspace\aliz\temp\flaskbug>python -c "import platform;print(platform.python_version(), platform.architecture())"
3.7.4 ('64bit', 'WindowsPE')
```

**Comment by carc1n0gen** [comment]
I believe this is a known issue.  Try the workaround `set FLASK_DEBUG=1 && python -m flask run`

**Comment by sorgloomer** [comment]
Thanks! The workaround indeed works and suits my usecase. I did not find this issue before, searched again, the closest seems to be this one: https://github.com/pallets/werkzeug/issues/1619 . I will follow up there, and I am closing this one. Thanks again!
