### ISSUE TITLE
test_client.set_cookie does not seem to work

### ISSUE THREAD

**Issue by JohnEmhoff** [pallets/flask#3330]
### Expected Behavior
The test client should be able to set cookies in a manner that the application object can read them. There's a `.set_cookie(...)` method but it doesn't seem to work -- after stepping through it I think the issue is that cookies aren't getting signed?

```python
import flask

app = flask.Flask("test")


@app.route("/")
def index():
    assert "thing" in app.session
    return "okay"


def test():
    with app.test_client() as client:
        client.set_cookie("example.com", "thing", "value")
        response = client.get("/", base_url="http://example.com")
    assert response.status_code == 200

test()
```

### Actual Behavior
The assertion is tripped due to an empty session, despite `set_cookie()` seemingly succeeding.

### Environment

* Python version: 3.6.7
* Flask version: 1.1.1
* Werkzeug version: 0.15.4

**Comment by JohnEmhoff** [comment]
Oops, I'm conflating sessions and cookies a bit here, but I think the point still stands that this appears to be missing functionality.

**Comment by davidism** [comment]
Using sessions with the test client is documented.
