### ISSUE TITLE
Mypy and ProxyFix

### ISSUE THREAD

**Issue by revmischa** [pallets/flask#3335]
The docs say (https://flask.palletsprojects.com/en/1.1.x/deploying/wsgi-standalone/#proxy-setups):
```python
from werkzeug.middleware.proxy_fix import ProxyFix
app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_host=1)
```

I get this from mypy:
`qc/create_app.py:47: error: Cannot assign to a method`

What's the correct solution here?

**Comment by davidism** [comment]
We do not support MyPy. You'll need to ask them what that error means.
