### ISSUE TITLE
Does flask plan to support asyncio?

### ISSUE THREAD

**Issue by leafonsword** [pallets/flask#3339]
Asyncio is the future of Python, does flask plan to support it?

**Comment by ThiefMaster** [comment]
> Asyncio is the future of Python

That's a bold statement. It is **perfectly fine** to not use async for most typical webapps.

But regarding async, this werkzeug issue might be worth reading: werkzeug#1322

**Comment by ashrafuzzaman** [comment]
Async excels in IO-bound works but where there is processing-intensive work, single-threaded asyncio becomes a bottleneck.
