### ISSUE TITLE
Flask marshall_with many bug after change to version 1.1

### ISSUE THREAD

**Issue by PMLP-novo** [pallets/flask#3348]
After changing to from version 1.0.3 to 1.1 my marshall with many code breaks

```python
from marshmallow import fields
from flask import Blueprint
from flask_apispec import marshal_with, doc
from database import Team
from marshmallow import Schema


bp = Blueprint("team", __name__, url_prefix="/teams")


class TeamSchema(Schema):
    id = fields.Str(required=True, dump_only=True, example="1")
    name = fields.Str(required=True, example="123 Abc")


@bp.route("")
@marshal_with(TeamSchema(many=True), description="A list of teams.")
@doc(tags=["Team"])
def search():
    """Fetch the list of teams, ordered by name."""
    return Team.query.order_by("name")
```
 And gives the following error when invoked either by localhost/teams
`TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.`

When running when changing to flask 1.0.3 it works. Without an error

### Environment

* Python version: 3.6.8
* Flask version: 1.1
* Werkzeug version: 0.15.5
* marshmallow:  2.20.2

**Comment by ThiefMaster** [comment]
Sounds like a problem with `flask_apispec`. Check their docs.
