### ISSUE TITLE
Documentation for older versions of Flask is missing

### ISSUE THREAD

**Issue by untitaker** [pallets/flask#3350]
https://flask.palletsprojects.com/en/0.12.x/deploying/wsgi-standalone/#proxy-setups used to be a valid link and no longer is.

@davidism is this intended? I can probably fix it in rtd.

**Comment by untitaker** [comment]
as far as I can tell renaming 0.12-maintenance to 0.12.x and enabling the build in rtd would fix it

**Comment by davidism** [comment]
I might need to port some docs fixes back to 0.12.x, but I don't mind re-enabling it.

**Comment by davidism** [comment]
0.12.x docs are now available here: https://flask.palletsprojects.com/en/0.12.x/

**Comment by untitaker** [comment]
thank you very much
