### ISSUE TITLE
Filename altered after upload

### ISSUE THREAD

**Issue by Chocorean** [pallets/flask#3351]
Trying to upload a file named `Расшифровка RootKit.com [63k].txt` via `requests.post(files={'file': open(fn, 'rb')})`. I checked the file is sent with its correct name. On the other side, `request.files['file']` does not have the good filename.

### Expected Behavior
The file should be should saved with its filename.

```python
def _upload_file(filename):
    def filter_filename(filename: str) -> str:
        """Stolen from werkzerg and add exotic letters"""
        from unicodedata import normalize
        # filtered = normalize("NFKD", filename)
        filtered = filename
        for s in sep, altsep:
            if s:
                filtered = filtered.replace(s, " ")
        pattern = re.compile(r"[^\w.-]")
        filtered = pattern.sub("", "_".join(filtered.split()))
        filtered = filtered.strip("._")
        # filtered = filtered.encode('utf-8')
        return filtered

    global TMP_PATH
    u_file = request.files[filename]
    u_path = pjoin(TMP_PATH, filter_filename(path))
    u_file.save(u_path)  # crash: UnicodeEncodeError
    return u_path
```

### Actual Behavior
Flask fails to save the uploaded file.

```pytbssh
File "/var/www/app/eyeaieouille/app/api.py", line 174, in post_leak
[Wed Sep 04 11:46:21.960213 2019] [wsgi:error] [pid 72138:tid 140145960113920] [remote 192.168.180.67:53369]     u_path = _upload_file('dump')
[Wed Sep 04 11:46:21.960240 2019] [wsgi:error] [pid 72138:tid 140145960113920] [remote 192.168.180.67:53369]   File "/var/www/app/eyeaieouille/app/api.py", line 76, in _upload_file
[Wed Sep 04 11:46:21.960261 2019] [wsgi:error] [pid 72138:tid 140145960113920] [remote 192.168.180.67:53369]     u_file.save(u_path)
[Wed Sep 04 11:46:21.960266 2019] [wsgi:error] [pid 72138:tid 140145960113920] [remote 192.168.180.67:53369]   File "/usr/lib/python3/dist-packages/werkzeug/datastructures.py", line 2725, in save
[Wed Sep 04 11:46:21.960274 2019] [wsgi:error] [pid 72138:tid 140145960113920] [remote 192.168.180.67:53369]     dst = open(dst, 'wb')
[Wed Sep 04 11:46:21.960291 2019] [wsgi:error] [pid 72138:tid 140145960113920] [remote 192.168.180.67:53369] UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-15: ordinal not in range(128)

```

Whenever I try to print `request.files['file'].filename` with `app.logger.info()`, I have:

```pytb
[Wed Sep 04 11:40:08.636779 2019] [wsgi:error] [pid 71927:tid 140645057996544] [remote 192.168.180.67:53298] Message: '\xd0\xa0\xd0\xb0\xd1\x81\xd1\x88\xd0\xb8\xd1\x84\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb0 RootKit.com [63k].txt'
```

### Environment

* Python version: 3.6.8
* Flask version: 0.12.2
* Werkzeug version: 0.14.1

EDIT:
I took a look at Wireshark, and this is what I saw:  
`Content-Disposition: form-data; name="dump"; filename*=utf-8''%D0%A0%D0%B0%D1%81%D1%88%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%BA%D0%B0%20RootKit.com%20%5B63k%5D.txt`
I think Flask turns this into `\xd0\xa0\xd0\xb0\xd1\x81\xd1\x88\xd0\xb8\xd1\x84\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb0 RootKit.com [63k].txt` instead of `Расшифровка RootKit.com [63k].txt`. I am not expecting for a fix as long as the documentation advises to use the `werkzerg.secure_filename()` function, but as it erases some characters (`[^a-zA-Z0-9]` cleaning), but I would appreciate a wordaround, it did not manage to solve this issue.

**Comment by davidism** [comment]
That is the correct filename, `u_path.decode('utf8')` produces the original filename. If `open` is trying to open using the ascii filesystem encoding, that sounds like a misconfiguration of your system locale or Python.

I tried uploading and saving a file with that name on my system, and did not encounter this issue. 

Note that you can pass an open file to `save` instead of a path, so you can open the file manually in a way that works for you and pass that in.

**Comment by Chocorean** [comment]
I wonder how do you manage to do `u_path.decode('utf8')` because it is not a `bytes` object but a `str`...

**Comment by davidism** [comment]
I didn't have to, everything just worked. I was pointing out that the representation you were seeing was an encoded version of the name.
