### ISSUE TITLE
DOCs: escape import needed to follow quickstart tutorial.

### ISSUE THREAD

**Issue by LeonardoFurtado** [pallets/flask#3354]
### Expected Behavior
All tutorial steps should work

### Actual Behavior
error in method not imported

```pytb
return "User  %s" % escape(username)
NameError: name 'escape' is not defined
```

I think all the steps of the tutorial should be followed without errors, this helps the beginners. At [Quickstart](https://flask.palletsprojects.com/en/1.1.x/quickstart/#quickstart), [Variable Rules](https://flask.palletsprojects.com/en/1.1.x/quickstart/#variable-rules) generate an error because the escape method was not imported earlier in the tutorial. I could open a PR for that, but repeating the previous code doesn't make much sense to me, and I can't think of a way to not make it messy. So I'll open this issue before I sleep and forget it.

It may seem like a silly issue, but I always worry about documentation and how easy it should be for beginners to follow.

**Comment by LeonardoFurtado** [comment]
Is updating the tutorial to use fstring a viable solution?

**Comment by Jamim** [comment]
Hello @LeonardoFurtado,

> Is updating the tutorial to use fstring a viable solution?

I don't think so because `flask` still supports Python 2.7.

**Comment by LeonardoFurtado** [comment]
> Hello @LeonardoFurtado,
> 
> > Is updating the tutorial to use fstring a viable solution?
> 
> I don't think so because `flask` still supports Python 2.7.

it's true...

**Comment by agentm007** [comment]
Not sure why this was closed. It seems to still be a problem with the documentation.

**Comment by LeonardoFurtado** [comment]
> Not sure why this was closed. It seems to still be a problem with the documentation.

This is reflected in many points of the documentation, I do not know if correcting all these points can make the examples very large. I will open this again :).

**Comment by MarcoGorelli** [comment]
Why not just move this import (`escape`) further up in the documentation?

I think it's already implicit that to run an example, you need to already have run what comes before it. For example, to run the one in https://flask.palletsprojects.com/en/1.1.x/quickstart/#rendering-templates, it's implicit that to run `app = Flask(__name__)` from the beginning of the tutorial.

But looking for missing imports in later sections of the documentation isn't obvious, and errors early on can be discouraging to beginners

**Comment by LeonardoFurtado** [comment]
> 
> But looking for missing imports in later sections of the documentation isn't obvious, and errors early on can be discouraging to beginners

Very good, that's exactly what I meant.
