### ISSUE TITLE
Automatic 308 Redirection does not maintain schema 

### ISSUE THREAD

**Issue by csanders-git** [pallets/flask#3367]
### Expected Behavior
When a user enters a route to a location with a trailing slash but leaves the trailing slash off, they either receive a 404 or they are redirected to that location with a trailing slash using the same scheme they provided (https vs http)

```python
@sp_app.route('/acs/', methods=["GET", 'POST'])
def acs():
    # example code here
```

### Actual Behavior
Flask will happily accept a route appended with a slash. When a user navigates to that route without the trailing slash they will be redirected with a 308 PERMANENT REDIRECT. This redirection does not maintain the schema of the original request, always dropping the request to HTTP. 

This can be abused by an attacker to force transmission by a user over HTTP by sending a crafted link such as https://mysite.com/acs instead of https://mysite.com/acs/. It is also likely an administrator might make this mistake when configuring locations or distributing links. 

### Environment
* Python version: 2.7.16
* Flask version:  1.1.1

**Comment by davidism** [comment]
Sounds like your app is behind a reverse proxy like Nginx and you don't have the `X-Forwarded-Proto` header and `ProxyFix` middleware configured correctly.

**Comment by csanders-git** [comment]
That is correct, it is behind an AWS LB

**Comment by csanders-git** [comment]
@davidism i'm now looking at https://github.com/pallets/werkzeug/issues/1023 -- is there documentation for this anywhere?

**Comment by davidism** [comment]
```python
from werkzeug.middlware.proxy_fix import ProxyFix

app.wsgi_app = ProxyFix(app.wsgi_app)
```

See the docs on AWS LB to figure out what `X-Forwarded-` headers it sets and configure [`ProxyFix`](https://werkzeug.palletsprojects.com/middleware/proxy_fix/) appropriately.
