### ISSUE TITLE
from werkzeug.wsgi import DispatcherMiddleware

### ISSUE THREAD

**Issue by oaigudmundsson** [pallets/flask#3373]
### Expected Behavior

It seems to me the DispatcherMiddleware is not available when call **werkzeug.wsgi** on flask 1.1.1. 

```python
from werkzeug.wsgi import DispatcherMiddleware
```

### Actual Behavior

Should be in the document:

from werkzeug.middleware.dispatcher import DispatcherMiddleware

### Environment

* Python version: 3.6
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

**Comment by davidism** [comment]
It's still available, just deprecated. You should see a `DeprecationWarning` when running:

> DeprecationWarning: The import 'werkzeug.wsgi.DispatcherMiddleware' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.wsgi.middleware.dispatcher import DispatcherMiddleware' instead.
