### ISSUE TITLE
Is it a viable option to use flask with Gunicorn GEVENT

### ISSUE THREAD

**Issue by sudhakar-datta** [pallets/flask#3379]
I need to scale the flask based micro-service to handle 1K-requests/sec, but the call are sync calls to 3rd party which would block 8 to 10 secs. Celery or RQ is not an option (due to certain restrictions).

### Environment

* Python version: 3.7
* Flask version: 1.11
* Werkzeug version:

**Comment by jab** [comment]
This issue tracker is for tracking issues to Flask itself. Please use StackOverflow for questions about your own code.

**Comment by sudhakar-datta** [comment]
Interesting is, they punt from stackoverflow to here, and getting punted back to stackoverflow.
