### ISSUE TITLE
static css media print doesn't work

### ISSUE THREAD

**Issue by imsuneaik** [pallets/flask#3384]
### Expected Behavior

I am trying to develop a web page and create a button to generate PDF. I realised that if i were to include @Media print after defining my static url for css. It does not go through. 

```python
# The method as per documentation 
<link rel=stylesheet href="{{ url_for('static', filename='css/style.css') }}">

# What I want to create 
<link rel=stylesheet href="{{ url_for('static', filename='css/print.css') }}" media= "print" >

@media print {
logo{
       width : 50px !important
       height : 100px !important
  }
}
```

### Actual Behavior

```pytb
PDF preview still shows the original-sized image. 
```

### Environment

*Python 3.7.4
*Flask 1.1.1
*Werkzeug 0.16.0

**Comment by lepture** [comment]
Not an issue of Flask. You can try to ask for help in stackoverflow.
