### ISSUE TITLE
Can not be connected on local area network on macOS 10.15 (Catalina)

### ISSUE THREAD

**Issue by kant-li** [pallets/flask#3387]
I just upgraded the macOS to 10.15 (Catalina) on my MacBook (Retina, 12-inch, Early 2015) and encountered a weird issue:

1. I'm running a python flask app on local area network which worked fine before the upgrade, but other people could not access to my server now;
2. With Wireshark, I know the TCP SYN requests was received but not responded; And the flask server did not received the request at all;
3. I started a simple TCP server with a python script in terminal. By allowing Python.app to access to the network on a pop-up, this simple TCP server could be connected by others;
4. If I turn down the firewall on macOS, the flask server could be connected by others;
5. In the firewall configuration, the Python was allowed to access to the network; And there was no pop-ups to allow the network access when I started the flask app;

Anything i missed?

### Environment

* macOS 10.15
* Python version: 3.7.2
* Flask version: 0.12.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
I'm sorry, I don't have any experience with the MacOS firewall, and I'm having a hard time understanding what you're reporting. Flask doesn't do anything specific with the network, the Werkzeug dev server that runs it during development uses the standard Python HTTP server, which as far as I know just opens a socket in the normal way.

**Comment by carc1n0gen** [comment]
@kant-li I am on Catalina, and I just tried this. When starting flask with host 0.0.0.0 (to allow outside connections) I was immediately prompted to allow it permission to do so by macOS, and clicking allow did allow me to access the flask app from another device on the network.

**Comment by kant-li** [comment]
@carc1n0gen thanks a lot, I'll check my firewall settings.
