### ISSUE TITLE
Browser doesn't show error message in tutorial

### ISSUE THREAD

**Issue by MarcoGorelli** [pallets/flask#3388]
I was following the [tutorial](http://flask.palletsprojects.com/en/1.1.x/tutorial/templates/), and got to the bottom of the page, where it says

> Try clicking the “Register” button without filling out the form and see that the browser shows an error message.

### Expected Behavior
I was expecting to see an error message in the browser

### Actual Behavior
I don't see an error message - instead, it seems to already work beautifully:
![image](https://user-images.githubusercontent.com/33491632/66699054-533cd780-ecdb-11e9-8981-e97d43d368c7.png)

### Environment

Python 3.7.4
Flask 1.1.1
Werkzeug 0.16.0

**Comment by ThiefMaster** [comment]
I do see a validation error there... "Please fill in this field"

**Comment by MarcoGorelli** [comment]
The tutorial says

> Try clicking the “Register” button without filling out the form and see that the browser shows an error message. Try removing the required attributes from the register.html template and click “Register” again. Instead of the browser showing an error, the page will reload and the error from flash() in the view will be shown.

Isn't the "Please fill in this field" the flash(), rather than the error?

**Comment by ThiefMaster** [comment]
No, the `flash()` message would just be showing up as normal text. This tooltip is coming from the browser.
