### ISSUE TITLE
[QUESTION] Does flask support other templating engine

### ISSUE THREAD

**Issue by tbhaxor** [pallets/flask#3392]
Does flask support other templating engines like `ejs`, `handlebars` etc? If no, is there any way to create your own templating engine?

**Comment by ThiefMaster** [comment]
You are mentioning non-python template engines. Not sure how you plan to use those in a Python app...

Anyway, just don't use `render_template` if you don't want to use Jinja. Use your preferred template engine as if you would use it standalone or see if there's an extension that integrates it nicely with the Flask environment.
