### ISSUE TITLE
Change celery to app in documentation

### ISSUE THREAD

**Issue by bngsudheer** [pallets/flask#3394]
### Expected Behavior
Should use clear language and variable names.

Example: https://flask.palletsprojects.com/en/0.12.x/patterns/celery/

### Actual Behavior
Use the variable celery instead of something like celery_app. Also imports Celery from celery package.

I would rename the variable `celery` to `celery_app` or `just app`.  `app` makes more sense because it is what is used in Celery documentation.

If you want to make this change, I am all ears. I would love to send the PR.

**Comment by ThiefMaster** [comment]
`app` makes no sense here because it would be very confusing to have a Flask `app` in some places, and a Celery `app` in others.

I think calling the Celery instance `celery` makes lots of sense, so I don't see the need to change anything here...
