### ISSUE TITLE
Test test_send_from_directory_bad_request fails in Python 3.8

### ISSUE THREAD

**Issue by jdevera** [pallets/flask#3402]
### Expected Behavior
All tests should pass in Python 3.8. However this one:

```python
    def test_send_from_directory_bad_request(self, app, req_ctx):
        app.root_path = os.path.join(
            os.path.dirname(__file__), "test_apps", "subdomaintestmodule"
        )

        with pytest.raises(BadRequest):
            flask.send_from_directory("static", "bad\x00")
```

Which calls:

```python
def send_from_directory(directory, filename, **options):
    # ...
    try:
        if not os.path.isfile(filename):
            raise NotFound()
    except (TypeError, ValueError):
        raise BadRequest()
    # ...
```

Is now affected by a change from 3.7 to 3.8.

[Python 3.8 now fixes the bug](https://docs.python.org/3.8/whatsnew/3.8.html#os-path) where a NULL character in a file name would trigger a ValueError in some `os.path` functions, such as `os.path.isfile`:

> os.path functions that return a boolean result like exists(), lexists(), isdir(), isfile(), islink(), and ismount() now return False instead of raising ValueError or its subclasses UnicodeEncodeError and UnicodeDecodeError for paths that contain characters or bytes unrepresentable at the OS level. (Contributed by Serhiy Storchaka in bpo-33721.)

The expectation is that this test should not be there, as it is testing buggy python behaviour. Furthermore, since the correct behaviour is now known, I would expect `send_from_directory` to raise `NotFound` also for paths with NULL characters in them.

### Actual Behavior

`send_from_directory` raises `BadRequest` for paths with null characters in them. This makes tests fail in python 3.8

```pytb
====================================== FAILURES =======================================
__________________ TestSendfile.test_send_from_directory_bad_request __________________
tests/test_helpers.py:789: in test_send_from_directory_bad_request
    flask.send_from_directory("static", "bad\x00")
.tox/py38/lib/python3.8/site-packages/flask/helpers.py:767: in send_from_directory
    raise NotFound()
E   werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
====================== 1 failed, 572 passed, 1 skipped in 4.14s =======================
```

### Environment

* Python version: 3.8
* Flask version: master
* Werkzeug version: 0.16.0

**Comment by haneybarg** [comment]
Hi! Can I take this?

**Comment by davidism** [comment]
Go for it! No need to ask first. :-)
