### ISSUE TITLE
Can't parse bson Object

### ISSUE THREAD

**Issue by ziadab** [pallets/flask#3418]
Hi,

I was working on a project using Flask and PyMongo, well when I try to parse the document from the mongo database and return it to the client I get an error that ObjectId can't be parsed, so I build a class base on JsonEncoder that fix this problem and I want to add it in Flask

**Comment by davidism** [comment]
Thanks for the interest. However, this is not something that would belong in Flask directly. There are already extensions to support Mongo in Flask, as well as JSON serializers for Mongo data, which would be used on a per-project basis.
