### ISSUE TITLE
Request fail on parsing json body with accent character

### ISSUE THREAD

**Issue by oliviercperrier** [pallets/flask#3424]
I am calling an endpoint i made to update a customer. When passing my json body i get a 400 Bad request. Seems like a json body that contains accent characters is not parsed correctly by the request object.

So this is the json body im sending to my endpoint:
```
{
  "last_name": "Gélinas"
}
```

### Expected Behavior
The `get_json` fonction should not return a 400 Bad Request
```
request.get_json(force=True)
```

The `request.data` should not remove the last `}` from the body when it contains accent character
```
request.data
# Should contain : "b'{\\n \"last_name\": \"G\\xc3\\xa9linas\"\\n}'"
```

### Actual Behavior
When reaching the endpoint, i am using the request object provided by flask to retrieve the body like so: 
```
request.get_json(force=True)
```
But with this code, i am getting a 400 Bad Request error. So i try using raw data instead like so:
``` 
request.data
```
I found out the request.data contains:
```
"b'{\\n \"last_name\": \"G\\xc3\\xa9linas\"\\n'"
```
As you can see, there is a missing `}` at the end which brakes any call to `json.loads` function

### Environment

* Python version: 3.7.4
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

**Comment by davidism** [comment]
I can't reproduce this issue as described. Posting the given example JSON, Flask receives the entire request body and loads it correctly.

If the body does not contain all the data, or incorrectly encoded data, that's an issue with the data you're sending. All Flask can do is try to load what it receives.

**Comment by Ca11MeE** [comment]
i meet this error too
when i use urllib3.PoolManager to request Flask Server(but i use tornado to  decorate Flask app)
in debug mode,i get some data:

> ![image](https://user-images.githubusercontent.com/19660023/74804641-d3271e00-531b-11ea-8bf3-9d842851bf95.png)
> ![image](https://user-images.githubusercontent.com/19660023/74804671-e1753a00-531b-11ea-8950-3963e56a212e.png)

but when i enter json.JSONDecoder.raw_decode() function and print decode string,it shows:

> ![微信截图_20200219134004](https://user-images.githubusercontent.com/19660023/74805201-64e35b00-531d-11ea-8ef8-33f8b9a7d333.png)

and then i search request which shown in stack,i found in app.py line 1935 and req.data still missing } at last index

this is my env:

- Flask (1.1.1)
- tornado (6.0.3)
- Python (3.6)
- Werkzeug (1.0.0)
