### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by ssi-anik** [pallets/flask#3428]
<img width="1280" alt="Screen Shot 2019-11-15 at 7 28 50 PM" src="https://user-images.githubusercontent.com/2676602/68946908-4c274e80-07de-11ea-845c-afee494533a6.png">
Just a grammatical error. Expecting `a(n) Exception` instead of `a Exception`
To reproduce: return an exception from a view.
* Python version: `3.7`
* Flask version: `1.1.1`
* Werkzeug version: `0.16.0`

**Comment by ThiefMaster** [comment]
Thanks, but why not just send a PR to fix this typo? :)

**Comment by davidism** [comment]
This is pretty much the equivalent of adjusting the "s" on words based on if it's one or many. I don't think this makes the error clearer.
