### ISSUE TITLE
Static file with UTF-8 characters can not be served from ubuntu 18.04 with UTF-8 system encoding.

### ISSUE THREAD

**Issue by dmathijs** [pallets/flask#3429]
### Expected Behavior
Static file from under static path should be served if it has UTF-8 encoded characters in its name.
I'm running Flask in combination with Gunicorn. Although my ubuntu system encoding is UTF-8 it doesn't seem to behave correctly.

```python
# simple file name:
42%C3%A9.jpg
```

### Actual Behavior
I get a 404 status code

### Environment

* Python version: 3.6.8
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by davidism** [comment]
Does this happen with the latest versions of Flask and Werkzeug?

**Comment by dmathijs** [comment]
Yes, updating flask to v1.1.1 and werkzeug to v0.16.0 doesn't affect the behaviour
