### ISSUE TITLE
Shorter forms for url_for("static", ...)

### ISSUE THREAD

**Issue by famecastle** [pallets/flask#3438]
I can't seem to find a good place to share enhancement proposals and I've not come across any similar idea, so I thought I'd just ask it here. Coding static "/static" URLs is not the recommended style and we should use `{{ url_for('static', filename='xyz.abc') }}` in templates. While this is a great way of keeping Flask simple and dynamic, it's also becoming quite a lot of characters there if we have more resources we'd like to link to. Hence, wouldn't it be a considerably comfortable alternative if we had short forms like `{{ u("static", "xyz.abc") }}` or at least for the static files like this: `{{ s("xyz.abc") }}` ?
I know this reduces readability, but inside a `<link>`s href it's self-explanatory and still just an additional way of specifying resources in a shorter form.

**Comment by davidism** [comment]
```python
from functools import partial

@app.template_global("s")
def static_url(filename, **kwargs):
    return url_for("static", filename=filename, **kwargs)
```
