### ISSUE TITLE
“Last-Modified” header gone missing when receiving in the client end from the Python Flask Rest API for 304 HTTP Response

### ISSUE THREAD

**Issue by chamikabm** [pallets/flask#3440]
### Expected Behavior
It should return the **_'Last-Modified'_** header when returning 304 Not Modified HTTP response.

```python
**_Here is my code:_**

def get_response:
  headers = {
    'Last-Modified': last_modified_after,  Wed, 04 Dec 2019 01:47:01 GMT #
    'Cache-Control': 'no-cache',
    'Name': 'Test'
  }
  if user_has_old_version:
    return cloud_doc, 200 headers
  else:
    return cloud_doc, 304, headers
```

### Actual Behavior
my issue is when I returning the response with the headers including the header **_Last-Modified_** it is gone missing when it receives to the client end, But all the other headers are present. I wonder how only that header is gone missing.

When I get the response for the **_else_** condition (i.e HTTP 200 response) I only get the _Cache-Control_ header and the custom _Name_ header, this _Last-Modified_ gone missing. But when I receive the  **_if_** (i.e HTTP 304 response) case, I'm getting all the headers including the _Last-Modified_ header.

* Python version: 3.7
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

**Comment by davidism** [comment]
According to https://tools.ietf.org/html/rfc2616#section-10.3.5

> If the conditional GET used a strong cache validator (see section 13.3.3), the response SHOULD NOT include other entity-headers. Otherwise (i.e., the conditional GET used a weak validator), the response MUST NOT include other entity-headers; this prevents inconsistencies between cached entity-bodies and updated headers.

In order to conform with this, `BaseResponse.get_wsgi_headers()` calls `werkzeug.http.remove_entity_headers()` when the status code is 304.
