### ISSUE TITLE
challenge load_dotenv and chdir assumption

### ISSUE THREAD

**Issue by robshep** [pallets/flask#3444]
Re: https://github.com/pallets/flask/blob/master/src/flask/cli.py#L607

### Expected Behavior
Should not change directory, or at least log a warning that is happening.

### Cause

Have a package tree that is not in the root of the project. 

### Actual Behavior
* Changes CWD of the process.  
* If PYTHONPATH is not set then werkzeug's debug reload fails. 
* relative file path do not resolve.

### Suggestion.

Allow a toggle environment variable to disable this behaviour.

### Environment

* Python version: 3.6
* Flask version: 1.1.1
* Werkzeug version: 0.16

### Notes

We have a multi-program codebase where there is lots of shared code and a couple of Flask webapps, along with other programs in the same project tree.  A shared .env (which we had no idea was loaded, just because we have python dotenv installed) 
This file stores common paths to other resources, services etc. 

The python codebase is in $PROJECT_ROOT/codebase/src and there are lots of other things in the root (like frontend SPA sources etc)

**Comment by robshep** [comment]
https://stackoverflow.com/questions/59323283

I had to monkeypatch `os.chdir()` to find this one

**Comment by davidism** [comment]
You can disable automatic loading and set up the project manually instead. http://flask.palletsprojects.com/en/1.1.x/cli/#disable-dotenv

**Comment by robshep** [comment]
oops, sorry I missed this.  My stacktrace led me to the point of chdir() and whilst there is lots of other conditional stuff I didn't see the higher up switch.  Thanks for the link.
