### ISSUE TITLE
Unexpected argument: PyCharm set_cookie samesite

### ISSUE THREAD

**Issue by danieldaeschle** [pallets/flask#3449]
### Expected Behavior
PyCharm shouldn't highlight the line as an warning

```python
from flask import Flask

app = Flask(__name__)

@app.router("/")
def index():
    resp = redirect("")
    resp.set_cookie("key", "val", samesite='strict')
```

### Actual Behavior
![image](https://user-images.githubusercontent.com/30751516/71026964-9451cd80-210a-11ea-9e8c-55c11d8dff79.png)

### Environment

* Python version: 3.7.5
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

**Comment by davidism** [comment]
We can't help what pycharm picks up for this. Seems like this should be reported to pycharm.
