### ISSUE TITLE
Feature request: Access jinja environment options for render_template

### ISSUE THREAD

**Issue by Matteljay** [pallets/flask#3450]
Is there a way to enable Jinja's LINE_STATEMENT_PREFIX option from inside of Flask?
I'm currently using this ugly hacky way:

```python
def customRender(file, **kwargs):
    env = jinja2.Environment(loader=jinja2.FileSystemLoader(searchpath="./templates"), line_statement_prefix='#')
    template = env.get_template(file)
    return template.render(kwargs)
```

* Python version: 3.7.4
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

**Comment by davidism** [comment]
There are various attributes and methods on the Flask object to override and configure the jinja environment. It cannot be done from the render functions.
