### ISSUE TITLE
flask.request cannot be patched by unittest.mock.patch in Python 3.8

### ISSUE THREAD

**Issue by snordhausen** [pallets/flask#3454]
### Expected Behavior
In Python 3.7.5, this works just fine and does nothing:

```python
from unittest.mock import patch
import flask

@patch("flask.request")
def foo(patched_request):
    pass

foo()
```

### Actual Behavior
In Python 3.8.0, it fails with

```
RuntimeError: Working outside of request context.
```
This happens because `patch` now tries to return an AsyncMock in some cases and Python's [mock.py line 51](https://github.com/python/cpython/blob/4594565b56e9c99d2d3fb7549041bbca5ecba8e2/Lib/unittest/mock.py#L51) calls asyncio.iscoroutinefunction() on flask.request. This will then call `getattr(func, '_is_coroutine', None)` in [coroutines.py line 167](https://github.com/python/cpython/blob/4594565b56e9c99d2d3fb7549041bbca5ecba8e2/Lib/asyncio/coroutines.py#L167) which flask then complains about.

It might be fixable by adding a special case to raise AttributeError instead when the `_is_coroutine` attribute is accessed.

### Environment

* Python version: 3.8.0
* Flask version: 1.1.1 and git master
* Werkzeug version: 0.16.0 and git master

**Comment by davidism** [comment]
It doesn't really make sense to mock the proxy object. Either use Flask's built in methods for creating a test client or context, or mock those methods to return your custom objects.

**Comment by kliyes** [comment]
@snordhausen encountered the same problem here, what's your solution in the end, please?
