### ISSUE TITLE
app.run() doesn't work when port is not specified in `SERVER_NAME`

### ISSUE THREAD

**Issue by rickywxg** [pallets/flask#3457]
### Expected Behavior
app.run() should work when port is not specified in `SERVER_NAME`.

```python
from flask import Flask

app = Flask(__name__)
app.config['SERVER_NAME'] = 'example.com'

@app.route('/')
def hello_world():
    return 'Hello, World!'

app.run()
```

### Actual Behavior
```
application fails during start
```

```pytb
Traceback (most recent call last):
  File "mini_svr_2.py", line 10, in <module>
    app.run()
  File "/Users/rickwang/Source/flask/src/flask/app.py", line 973, in run
    port = int(next((p for p in (port, sn_port) if p is not None), _port))
ValueError: invalid literal for int() with base 10: '
```

### Environment

* Python version: Python 3.7
* Flask version: latest 1.1.2.dev0
* Werkzeug version: 0.16.0

**Comment by carc1n0gen** [comment]
Probably working as intended: https://flask.palletsprojects.com/en/1.1.x/config/#SERVER_NAME

> Inform the application what host and port it is bound to

**Comment by rickywxg** [comment]
> Probably working as intended: https://flask.palletsprojects.com/en/1.1.x/config/#SERVER_NAME
> 
> > Inform the application what host and port it is bound to

Maybe you're right. Requests cannot be processed even after my code change in #3458. The reason is because default 5000 is not part of the server name, and it won't match  `localhost:5000` in http request `http://localhost:5000/`.

```
curl http://localhost:5000/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```
