### ISSUE TITLE
AttributeError: 'function' object has no attribute 'name' when blueprint is a function

### ISSUE THREAD

**Issue by rickwierenga** [pallets/flask#3459]
Consider the following blueprint file:

```python
from flask import Blueprint

bp = Blueprint('bp', __name__)


@book.route('/')
def bp():
    return "hello"
```

When one tries to register `bp` from this file like so:
```python
from app.bp import bp
app.register_blueprint(bp)
```

This error is raised:

```
AttributeError: 'function' object has no attribute 'name'
```

The cause is obvious, but the error message does not correspond with the actual error. This could be fixed by checking if an added blueprint is of type `Blueprint`, or a subclass, and returning an error if that's not the case.

**Comment by davidism** [comment]
Argument type checking is not commonly used in Python. I do not plan to add special error messages for this type of issue.
