### ISSUE TITLE
Werkzeug base_response.py doesn't support Flasks response.set_cookie

### ISSUE THREAD

**Issue by MertDalbudak** [pallets/flask#3464]
I want to simply response with a cookie to a client. But I get a strange error from: <br>`/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py`.

Error log here: https://pastebin.com/XjqFt7tW

    response = jsonify(filterData)
    response.headers = api_response['headers']
    response.set_cookie('name', 'value')
    return response

`filterData` is a simple `dict`

Python 3.6.9
Flask 1.1.1
Werkzeug 0.16.0

**Comment by davidism** [comment]
You're overwriting `response.headers` with a regular `dict`.
