### ISSUE TITLE
SERVER_NAME still implicitly changes routing behavior

### ISSUE THREAD

**Issue by BoWuGit** [pallets/flask#3465]
Just like this [old issue](https://github.com/pallets/flask/issues/998) said, routing behavior changed even when `subdomain_matching` defaults to false, so take [this repository](https://github.com/namieluss/python-flask-with-subdomain/blob/master/app.py) as example, if you comment following lines, 

```
@app.before_request
def start():
    """
    init globals and set the schema search path for the current request.
    """
    g.user = session.get('user', None)
    current_url = urlparse(request.url)
    subdomain = current_url.hostname.split('.')

    if subdomain.__len__() > 2:
        """
        redirect to home page
        """
        if current_url.path == "/":
            return redirect(url_for('index'))
        pass
    pass
```

then requests to `user1.flask-subdomain.com` won't route to `index`, default 404 as response. Or am I missing something, as a result have misunderstood it. Thanks very much.

```
@app.route('/')
def index():
    return render_template('index.html')
```

### Environment

* Python version: 3.6
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

**Comment by sagnik-chatterjee** [comment]
Hi can i take up this issue ?

**Comment by davidism** [comment]
I'm sorry, it looks like you're asking about code in another repository. As far as I can tell `SERVER_NAME` works as intended at this point.

**Comment by davidism** [comment]
#5634 in Flask 3.1 will further address this. `SERVER_NAME` no longer affects routing except to determine subdomains if `subdomain_matching` is enabled.
