### ISSUE TITLE
Intersphinx error when building documentation

### ISSUE THREAD

**Issue by sfermigier** [pallets/flask#3472]
Intersphinx doesn't build document for my projects, due to missing https://flask.palletsprojects.com/objects.inv on the documentation site.

My current config:

```
intersphinx_mapping = {
    "flask": ("https://flask.palletsprojects.com/", None),
}
```

The error messages:

```
intersphinx inventory 'https://flask.palletsprojects.com/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://flask.palletsprojects.com/objects.inv
```

**Comment by davidism** [comment]
You'll need to report this to Read the Docs if you think there should be some sort of default inventory URL.

**Comment by ltalirz** [comment]
@davidism Can I ask to reopen this issue?

The core of the question is about using intersphinx to link to your documentation of the `flask` package.
I think there are two questions here:

 * Do you want to support developers linking to the flask documentation via intersphinx?
 * If yes, what is the official location of the `objects.inv` file for the flask documentation that people should point to?

At the time of writing, the URL for which @sfermigier got a 404 is actually working:
```
 wget https://flask.palletsprojects.com/objects.inv
--2020-04-15 13:39:53--  https://flask.palletsprojects.com/objects.inv
Resolving flask.palletsprojects.com (flask.palletsprojects.com)... 2606:4700::6811:2152, 2606:4700::6811:2052, 104.17.33.82, ...
Connecting to flask.palletsprojects.com (flask.palletsprojects.com)|2606:4700::6811:2152|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://flask.palletsprojects.com/en/1.1.x/objects.inv [following]
--2020-04-15 13:39:54--  https://flask.palletsprojects.com/en/1.1.x/objects.inv
Reusing existing connection to [flask.palletsprojects.com]:443.
HTTP request sent, awaiting response... 200 OK
Length: 5768 (5.6K) [application/octet-stream]
Saving to: ‘objects.inv’

objects.inv                100%[=====================================>]   5.63K  --.-KB/s    in 0s

2020-04-15 13:39:54 (16.9 MB/s) - ‘objects.inv’ saved [5768/5768]
```

However, we have been experiencing occasional failures in documentation builds where we get a 502 on the same URL, e.g.
```
Warning, treated as error:
failed to reach any of the inventories with the following issues:
flask inventory 'https://flask.palletsprojects.com/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 502 Server Error: Bad Gateway for url: https://flask.palletsprojects.com/objects.inv
```

The same applies to other projects hosted under palletsprojects.com (such as `click`), while we've never had a similar issue with documentations hosted under readthedocs.org.
