### ISSUE TITLE
Static files only work for blueprints registered with url_prefix

### ISSUE THREAD

**Issue by deshipu** [pallets/flask#348]
The option `static_folder` for blueprints only works correctly when the blueprint has been registered with a `url_prefix`, otherwise the application's default static URL takes precedence.

There is nothing wrong in that behavior, but it is not documented. It would be nice to have that fact mentioned at http://flask.pocoo.org/docs/blueprints/#static-files and/or http://flask.pocoo.org/docs/api/#blueprint-objects

**Comment by oxbambooxo** [comment]
<https://vilimpoc.org/blog/2012/11/21/serving-static-files-from-root-and-not-static-using-flask/>
this essay look like is can work fix that situation can be resolved

**Comment by juanitogan** [comment]
Something very strange is up when using `static_url_path`, and I'm not using blueprints.  When I set:

`app = Flask(__name__, static_url_path="", static_folder="../public")`

then `@app.route("/<path:path>")` doesn't match on anything even though all my other routes work.  When I set:

`app = Flask(__name__, static_folder="../public")`

then `@app.route("/<path:path>")` matches on everything including intercepting all links to resources in index.html, which is annoying.  It seems my only hope is to rebuild :tired_face: to default Flask locations (`<app>/static`) and see if that magically works.  I dislike magic.  Flask 0.10.1.

**Comment by danielmhair** [comment]
Hey guys, thank you @juanitogan, we have been working on this for days and your post really solved it, thanks!

**Comment by jbejar** [comment]
I manually created the rules instead of registering the blueprint
```
    react = Blueprint('react', __name__, static_folder='../react/dist/')
    app.add_url_rule('/', endpoint='root',
                     view_func=lambda: react.send_static_file("index.html"))
    app.add_url_rule('/<path:filename>',
                     endpoint='react.static',
                     view_func=react.send_static_file)
```

**Comment by DusanMadar** [comment]
It works for me when:

1. set `static_folder='static'` when creating the Blueprint
2. use `'.static'` (note the `.`) in `url_for`, e.g.  I have `{{ url_for('.static', filename='js/a-script.js') }}` in `base.html`

And here's my app structure:
```
flask_app
├── flask_app
│   ├── app.py
│   ├── blueprints
│   │   ├── __init__.py
│   │   └── a-blueprint
│   │       ├── blueprint.py
│   │       ├── __init__.py
│   │       ├── static
│   │       │   └── js
│   │       │       └── a-script.js
│   │       ├── templates
│   │       │   └── base.html
│   │       └── views.py
│   └── __init__.py
├── config.py
└── manage.py
```

**Comment by davidism** [comment]
@DusanMadar that isn't what this issue is about: you're not mounting the blueprint at `/`. If you did, you wouldn't get the blueprint's static folder because the app static path would take precedence.

**Comment by swiknaba** [comment]
workaround: `app.register_blueprint(mod, url_prefix='/')`and then just do `@mod.route('test')` instead of `@mod.route('/test')` now localhost:5000/test correctly shows what you defined under 'test' in a submodule, which basically has the same effect as no url_prefix

**Comment by kozmaz87** [comment]
I also happened to run into this issue and I am now at the point that the static folder merges with the application static folder as needed but since I mounted it at a prefix there are 2 related problems.

Only the registration time prefix works as described above. The one in the Blueprint init is not the same.

The other problem is that the url_for template tag is broken for these static files as they are mounted at /static/whatever but the blueprint prefix is computed and prepended in front of it

**Comment by savvasenok** [comment]
Found easy solution. Do it only for your page with `url_prefix='/'`, because other pages work correctly

**main_page/view.py**
`from flask import render_template, Blueprint

main_page_blueprint = Blueprint(
    'main_page',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/project.main_page.static'
)

@main_page_blueprint.route('/')
def index():
    return render_template('main_page/index.html')
`


**main_page/templates/main_page/index.html**
`{% block content%}
	<img src="{{url_for('main_page.static', filename='img/photo.png')}}" alt="">
{% endblock %}`


**in __init__.py**
`from project.main_page.view import main_page_blueprint
app.register_blueprint(main_page_blueprint, url_prefix='/')
`

Hope it works!

**Comment by Es489** [comment]
Hi, mine worked with this set up:

Folders structures:

```
flask_app
|---modules
|     |-----user
|     |-----user_entry
|.              |------static
|.              |------templates
|.              |------__init__.py
|.              |-------my_blueprint.py
|
|---static
|---templates
|---app.py
```

In my_blueprint file:
```
my_blueprint = Blueprint("loin_register_module",
                                  __name__,
                                  template_folder="templates",
                                  static_folder="static",
                                  static_url_path=**"/modules/user_entry/static"**) #have to show full path from root directory
```

In my templates files:

```
<link href="{{url_for('.static', filename='login.css')}}" rel="stylesheet">
<script src="{{url_for('.static', filename='login_page.js')}}"></script>
```

Hope this will help!
