### ISSUE TITLE
Got Vulnerability while feeding request.get_json() data to marshmallow directly .

### ISSUE THREAD

**Issue by vvksahoo** [pallets/flask#3485]
I am using flask-marshmallow for user input validation .

```python
from marshmallow import Schema, fields, validate


class UserSchema(Schema):
    username = fields.String(required=True,
                            validate=[validate.Length(min=1, error="Field should not be empty.")])
    pincode = fields.Integer(required=True, validate=validate.Range(
        min=0, error="pincode is invalid, it should be a positive integer."))
```
```
class UserDetails(Resource):
    user_schema_obj = UserSchema()
    def post(self):
        if not request.is_json:
            return make_response(jsonify(error_dict(
                current_request_id(), "Unsupported media type, Requests must be JSON",
                415)), status.HTTP_415_UNSUPPORTED_MEDIA_TYPE)

        if not request.json:
            return make_response(jsonify(error_dict(
                current_request_id(), "Required parameter not found",
                400)), status.HTTP_400_BAD_REQUEST)
        request_jsn = UserDetails.user_schema_obj.load(request.get_json())
        username = request_jsn['username']
        pincode = request_jsn['pincode']
```
This is the way i am feeding user input to marshmallow schema . when i am doing app scan it saying ```gets user input from element **get_json**. This element’s value flows through the code without being properly sanitized or validated and is eventually stored in the server-side Session object, in post ```.
This constitutes a Trust Boundary Violation. 
Dont know how to resolve this ? 

### Environment

* Python version:3.7.4
* Flask version:1.1.1
* Werkzeug version:0.16.0

**Comment by ThiefMaster** [comment]
sounds like a shitty security checker tool showing useless warnings since it doesn't know about marshmallow's validation...

BTW, you may want to have a look at webargs when using marshmallow schemas to validate inpit.
