### ISSUE TITLE
Incompatibility issues with werkzeug 1.0

### ISSUE THREAD

**Issue by mcjlnrtwcz** [pallets/flask#3490]
On February 6th a new version of Werkzeug was released: https://pypi.org/project/Werkzeug/#history
It introduces a breaking API change which results in a crash. This is not directly happening in flask code, but in plugins - in my case it's `flask_session`.

### Expected Behavior
Flask should have a new version that uses werkzeug in version greater than 0.15, but less than 1.0. Other packages depending on flask can use that version and then the code will work as previously. :)

Compare this with https://github.com/phovea/phovea_server/issues/105 - see details about breaking changes in Werkzeug.

### Actual Behavior
Flask application can't be tested.

```pytb
/usr/lib/python3.7/unittest/mock.py:1204: in patched
    return func(*args, **keywargs)
reforis/test_utils/fixtures.py:72: in _stubbed_app
    return create_app('test')
reforis/__init__.py:41: in create_app
    Session(app)
venv/lib/python3.7/site-packages/flask_session/__init__.py:54: in __init__
    self.init_app(app)
venv/lib/python3.7/site-packages/flask_session/__init__.py:61: in init_app
    app.session_interface = self._get_interface(app)
venv/lib/python3.7/site-packages/flask_session/__init__.py:93: in _get_interface
    config['SESSION_USE_SIGNER'], config['SESSION_PERMANENT'])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <flask_session.sessions.FileSystemSessionInterface object at 0x7f38e4d255c0>, cache_dir = '/tmp/foris-sessions', threshold = 500, mode = 384, key_prefix = 'session:'
use_signer = False, permanent = True

    def __init__(self, cache_dir, threshold, mode, key_prefix,
                 use_signer=False, permanent=True):
>       from werkzeug.contrib.cache import FileSystemCache
E       ModuleNotFoundError: No module named 'werkzeug.contrib'

venv/lib/python3.7/site-packages/flask_session/sessions.py:313: ModuleNotFoundError
```

### Environment

* Python version: 3.7
* Flask version: 1.1.1
* Werkzeug version: 1.0

**Comment by davidism** [comment]
Flask itself isn't breaking, we don't plan to add such a pin. See https://github.com/pallets/werkzeug/issues/1714
