### ISSUE TITLE
Flask 0.12.2 fresh install broken due to Werkzeug 1.0.0

### ISSUE THREAD

**Issue by gricey432** [pallets/flask#3493]
This has been raised several times #3490 #3486 etc.

These have been closed due to no stacktrace or the issue being in a third party project.
Here are some reproducible examples just using Flask.

```
> python --version
Python 3.8.0
> pip install flask==0.12.4
Successfully installed Jinja2-2.11.1 MarkupSafe-1.1.1 Werkzeug-1.0.0 click-7.0 flask-0.12.4 itsdangerous-1.1.0
```

```
from flask import Flask, request
app = Flask(__name__)

@app.route('/')
def hello_world():
    return "Is xhr" if request.is_xhr else "Isn't xhr"
```
Using the documented property [is_xhr](https://flask.palletsprojects.com/en/0.12.x/api/#flask.Request.is_xhr) gives

```
  File "/home/mitchell/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
```

Also in `jsonify`

```
from flask import Flask, jsonify
app = Flask(__name__)

@app.route('/')
def hello_world():
    return jsonify({
        "hello": "world",
    })
```
gives
```
  File "/home/mitchell/.virtualenvs/flask/lib/python3.8/site-packages/flask/json.py", line 298, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/home/mitchell/.virtualenvs/flask/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
```

Hopefully these purely-flask reproducible examples will help this get sorted out.

**Comment by davidism** [comment]
">=" pins mean "we use features/changes that started in this minimum version of Werkzeug", not "every version of Werkzeug forever will always support this version of Flask". We don't plan to retroactively add pins to every old Flask release. Instead, just like you've pinned your Flask to 0.12.2, you should pin your other dependencies as well. This is a good practice for projects and dependencies in general, not just when using Flask.

**Comment by gricey432** [comment]
Looks like this needs some communication in the flask team, I made this issue since @ThiefMaster [said](https://github.com/pallets/flask/pull/3488#issuecomment-584009121)
>You are right, I hadn't realized that older versions also pull in the latest Werkzeug. We'll need to update the pinning (to >=0.15,<1.0.0) in a bugfix release for the older but still-supported Flask versions

Personally, I disagree about me pinning Flask's dependencies being normal practice, this isn't normal practice with any library I know of, and it's not mentioned in Flask's docs as being a requirement for use.
Would you accept a docs PR to make sure everyone knows all of Flask's dependencies are supposed to be pinned by the user during the setup process?

**Comment by davidism** [comment]
0.12.5 pins this version. I will definitely encourage you and all applications to pin their exact dependencies, that's how you control your own upgrade process. This is a standard feature of pip (`pip freeze`) as well as other tools like pip-compile, pipenv, and poetry. However, this is not specific to Flask, so it doesn't need to be in our docs.
