### ISSUE TITLE
SESSION_REFRESH_EACH_REQUEST seems pointless in SecureCookieSessionInterface

### ISSUE THREAD

**Issue by dblakemore** [pallets/flask#3494]
Apologies if I am misunderstanding this, but there seems to be an oversight with the `session.permanent` property function on `SecureCookieSession` in conjunction with the session interface's `should_set_cookie()`.

The session interface's `should_set_cookie()` function will return true if either of the following conditions is met:
* The session has been modified, or
* The session is permanent _and_ the `SESSION_REFRESH_EACH_REQUEST` is set to True.

However, setting `session.permanent = True` will internally add `_permanent` property on the current session, which in turn (due to the nature of the `SecureCookieSession` class), will set the `session.modified` to True. As such, the `SESSION_REFRESH_EACH_REQUEST` seems pointless as it seems impossible to set a session as permanent without it also getting set as modified each time.

It's certainly not a huge issue, as I don't think there is necessarily a use-case for setting session as permanent without using `SESSION_REFRESH_EACH_REQUEST`, but (in my opinion) it _does_ behave unexpectedly. Have I misunderstood something here?

### Expected Behavior
Setting `session.permanent = True` on a SecureCookieSession (or subclass of) and `app.config['SESSION_REFRESH_EACH_REQUEST'] = False` should make the session interface `should_set_cookie()` return False when the session has not been modified.

### Actual Behavior
The session interface's `should_set_cookie()` function always returns `True`, because the `session.modified` property is `True` (I believe this happens automatically when setting `session.permanent = True`)

**Comment by dblakemore** [comment]
To clarify, I believe this is less an issue with `session.permanent`, as this property is used elsewhere, like in `get_expiration_time()`. It's more that the `SESSION_REFRESH_EACH_REQUEST` seems pointless.

I've updated the issue description.

**Comment by davidism** [comment]
Setting `permanent` only affects the response that sets the cookie, not subsequent responses.
