### ISSUE TITLE
app.teardown_request and app.errorhandler investigation

### ISSUE THREAD

**Issue by Natim** [pallets/flask#3502]
Hello party people,

My understanding was that `@app.teardown_request` function would be called after a request whenever an error occurred or not.

However, it seems that when I set an `@app.errorhandler(Exception)`, the error handler is called but then the `@app.teardown_request` function is not.

Is this the expected behaviour?

Best regards,

Rémy

```
@app.teardown_request
def commit_or_rollback_db_session(ctx):
    try:
        if g.get("rollback_db_session"):
            g.db_session.rollback()
        else:
            g.db_session.commit()
    except Exception:
        g.db_session.rollback()
        raise

@app.errorhandler(Exception)
@app.errorhandler(500)
def handle_internal_server_error(e):
    g.rollback_db_session = True
    return jsonify(error=True, code=500)
```

**Comment by davidism** [comment]
I can't reproduce this issue. In the following example, "handle_500 bad" and "teardown None" are printed, and "Handled 500" is returned. `e` is `None` in the teardown because it was already handled in the error handler.

```python
from flask import Flask

app = Flask(__name__)


@app.route("/")
def index():
    raise Exception("bad")


@app.teardown_request
def teardown(e):
    print("teardown", e)


@app.errorhandler(Exception)
@app.errorhandler(500)
def handle_500(e):
    print("handle_500", e)
    return "Handled 500"
```

**Comment by Natim** [comment]
I guess the difference between your code and my code is the raise inside the `teardown_request`
