### ISSUE TITLE
Wanna see my hot pics?💋💋💋

### ISSUE THREAD

**Issue by akdnfbf** [pallets/flask#3503]
Hi!😻😻😻 Wanna see my hot pics?💋💋💋 Go to this site and find me here. ❤️❤️❤️ My nick is sexygirl662 👇👇👇

https://tinyurl.com/sbmadwq

**Comment by ThiefMaster** [comment]
go fuck yourself

**Comment by onlinejudge95** [comment]
@ThiefMaster I guess they confused GitHub with PornHub.
On a serious note, this scammer didn't spare the following repos too

https://github.com/tuvtran/project-based-learning/issues/211
https://github.com/TheAlgorithms/Python/issues/1760
