### ISSUE TITLE
url_for behavior is different in production than under test

### ISSUE THREAD

**Issue by ColdHeat** [pallets/flask#3506]
### Expected Behavior
url_for apparently has behavior where it will generate routes that use the current request method. For example in the following example, url_for can return either of the following depending on the method.

GET: `http://localhost:4444/bad/bad`
POST: `http://localhost:4444/bad?data=bad`

I would actually expect it to always return `http://localhost:4444/bad/bad`. 

Secondly during a test, since there is no method it seems like Flask will return the expected value of `http://localhost:4444/bad/bad`. This recently bit me and broke some functionality that was covered by a test that then failed in production because of this. 

```python
from flask import Flask, url_for
app = Flask(__name__)
app.config["SERVER_NAME"] = "localhost:4444"

@app.route('/bad', methods=["POST", "GET"])
@app.route('/bad/<data>', methods=["GET"])
def hello_world(data=None):
    return url_for("hello_world", data="bad", _external=True)

with app.app_context():
    # The value that would probably be generated under a test. 
    print(url_for("hello_world", data="bad"))

if __name__ == '__main__':
    app.run(debug=True, threaded=True, host="127.0.0.1", port=4444)

# curl -X POST http://localhost:4444/bad
# or 
# curl -X GET http://localhost:4444/bad
```

### Environment

* Python version: Python 3.7.6
* Flask version: 1.1.1
* Werkzeug version: 1.0.0

**Comment by cydave** [comment]
Providing a defaults would make it work again.

```python
from flask import Flask, url_for
app = Flask(__name__)
app.config["SERVER_NAME"] = "localhost:4444"

@app.route('/bad', methods=["POST", "GET"], defaults={"data": None})
@app.route('/bad/<data>', methods=["GET"])
def hello_world(data=None):
    return url_for("hello_world", data="bad", _external=True)

with app.app_context():
    # The value that would probably be generated under a test. 
    print(url_for("hello_world", data="bad"))

if __name__ == '__main__':
    app.run(debug=True, host="127.0.0.1", port=4444)

# curl -X POST http://localhost:4444/bad
# or 
# curl -X GET http://localhost:4444/bad
```

**Comment by davidism** [comment]
This is a pretty weird configuration. If anything, this would be something for Werkzeug, not Flask, but I don't think there's anything unexpected going on here.

1. `/bad/<data>` is registered before `/bad` (decorator order is bottom to top).
2. When there's no request, the method is assumed to be GET unless passed with `_method="POST"`.
3. Werkzeug uses the current method and the matching variable rules to decide on which rule to build for an endpoint with multiple rules.

So you get:

* No request, GET method assumed: `/bad/bad` is the most specific rule for GET with `data`.
* GET request: `/bad/bad`, same reason.
* POST request: `/bad` is the only rule for POST, `data` is an extra kwarg.
