### ISSUE TITLE
Static files sent as content type text/html when redirecting from app.before_request

### ISSUE THREAD

**Issue by SvenMarcus** [pallets/flask#3509]
### Expected Behavior
I have an application that checks if my users log in for the first time and if they are they will be redirected to a page where they need to change the default password they have been provided.
This redirect is happening with `app.before_request`.

```python
@app.before_request
def redirect_to_othersite():
    other_url = url_for("othersite")
    if request.path == other_url:
        return

    return redirect(other_url)

@app.route('/')
def home():
    return render_template("index.html")

@app.route('/othersite/')
def othersite():
    return render_template("othersite.html")
```

### Actual Behavior
After the redirect static files like stylesheets and images are broken on the page. Chrome dev tools show that all files from my static folder are being sent with content type `text/html`, which I suspect is the issue. Caching should be disabled in the Chrome dev tools to see the issue.

When decorating all routes with a function manually then stylesheets are loading fine.

### Environment

* Python version: 3.7.5
* Flask version: 1.1.1
* Werkzeug version: 1.0.0

**Comment by BLasan** [comment]
@SvenMarcus  Can I work on this?

**Comment by ThiefMaster** [comment]
I don't anything that needs working on here. @SvenMarcus you are redirecting pretty much *everything*, and that includes static files of course. If you still believe there's a bug, please provide a minimal *runnable* example showing this issue.

PS: `if request.endpoint == 'othersite'` would be abetter check
