### ISSUE TITLE
Can not compress response json uses jsonify

### ISSUE THREAD

**Issue by abinhho** [pallets/flask#3511]
### Expected Behavior

I am using docker with python3, I'd like to compress response json uses `jsonify` but not luck.
Refs: https://github.com/colour-science/flask-compress

```python
// Code
...
from flask_compress import Compress
...
app = Flask(__name__)
CORS(app)
Compress(app)
```

Expect:
```python
{ "success": true,  "data": {}}
```

### Actual Behavior

```pytb
{
  "success": true, 
  "data": {}
}
```

### Environment

* Python version: Docker python3.7
* Flask version: 1.1.1
* Werkzeug version: Unknown

**Comment by ThiefMaster** [comment]
That's not compression. gzip transport encoding is usually transparent. look at the headers your client receives instaed.

also, this is not related to flask in any case but rather flask-compress

**Comment by abinhho** [comment]
@ThiefMaster Thank you!
