### ISSUE TITLE
flask how to stop after run() called

### ISSUE THREAD

**Issue by premananda8** [pallets/flask#3515]
i want help i called run() it is running forever. Is there any method to close or stop without using service?

**Comment by ThiefMaster** [comment]
CTRL+C...

`flask run` is *only* meant for development, so if you are running it as a service you are most likely doing something wrong.

**Comment by premananda8** [comment]
u mean flask i can't use as service?

**Comment by ThiefMaster** [comment]
Please read the flask docs (and this is not whatsapp, it's not too much work to write "you" instead of "u"): https://flask.palletsprojects.com/en/1.1.x/deploying/
