### ISSUE TITLE
Description contradicts code sample

### ISSUE THREAD

**Issue by ongopongo** [pallets/flask#3520]
I read the Flask documentation at https://flask.palletsprojects.com/en/1.1.x/errorhandling/#unhandled-exceptions and noticed the property name used in the description is different from the property name used in the example code.

![image](https://user-images.githubusercontent.com/53710895/75581125-c68e7e00-5a1d-11ea-9f94-fd10e5a34856.png)

### Expected Behavior

I expected them to be the same as one another.

### Actual Behavior

They were different from one another.

### Environment

* Python version: N/A
* Flask version: 1.1.x
* Werkzeug version: N/A

**Comment by davidism** [comment]
Nice find, could you make a pr against the 1.1.x branch?

**Comment by ongopongo** [comment]
I am willing to do that, but I don't know which property name is the correct one. Do you know which one is the correct one?

I'm also OK with someone else submitting the PR based upon this report.

**Comment by davidism** [comment]
The docs say it's `original_exception`: https://werkzeug.palletsprojects.com/en/1.0.x/exceptions/#werkzeug.exceptions.InternalServerError
