### ISSUE TITLE
Creating realtime API with flask

### ISSUE THREAD

**Issue by SharkJ** [pallets/flask#3522]
Hi,

I'm working on a project in which I have to create a realtime working python rest API that does the following: - multiple request receiving, processing them, and responding.

My question is, is it possible to work realtime with python flask APIs? And if there is, is there a way for me to view the realtime responses when a stream of requests are provided?

Thanks!

**Comment by shivamguys** [comment]
Could You please elaborate it further multiple request receiving, processing them, and responding?
Every Web Server Works the same way. :-)

**Comment by davidism** [comment]
See Flask-SocketIO for an interesting starting point.

Please use Discord or the mailing list for general discussion about your own code. This tracker is for issues related to the project itself.
