### ISSUE TITLE
Flask dev server not working with Python 3.6 on Anaconda

### ISSUE THREAD

**Issue by scribu** [pallets/flask#3523]
We are forced to use Python 3.6 due to some other dependencies that do not work with newer versions of Python.

Steps to reproduce:

1) Create `hello.py`, as described in the example:

```python
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello, World!"
```

2) Try to run it:

```bash
FLASK_APP=hello.py flask run
```

### Expected Behavior

I see "Hello, World!" in the browser.

### Actual Behavior

```bash
 * Serving Flask app "hello.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "hello".
```

Running the same example in Python 3.7 works fine.

### Environment

* Python version: 3.6.10
* Flask version: 1.1.1
* Werkzeug version: 1.0.0

**Comment by scribu** [comment]
If I convert `hello.py` to a package (`hello/__init__.py`), it works fine in all Python versions.

**Comment by GrayTable** [comment]
Is this issue still open? I've tried to replicate the behavior with no luck:

**Env**
```shell
$ python3.6 -m flask --version

Python 3.6.10
Flask 1.1.1
Werkzeug 1.0.0
```
**Running**
```shell
$ export FLASK_APP=hello.py && python3.6 -m flask run

 * Serving Flask app "hello.py" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[GCC 9.2.1 20200130]
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

Python version may not be an issue here.

**Comment by scribu** [comment]
@GrayTable I can still reproduce it. Maybe it's because I have Python installed via Anaconda:

```bash
$ python --version
Python 3.6.10 :: Anaconda, Inc.
```

**Comment by davidism** [comment]
If this is Anaconda-specific, you'll need to identify the issue and submit a PR, I don't have the capacity to support that.

**Comment by GrayTable** [comment]
Still can't reproduce the issue even with Anaconda setup. It seems that the issue is specific to your environment somehow. I'm not an expert when it comes to Anaconda, so here are the steps I've taken:

**Env setup**
```shell
$ conda create --name iss3523
$ conda activate iss3523
$ conda install python=3.6.10
```
```shell
$ python --version
Python 3.6.10 :: Anaconda, Inc.
```
**Flask**
```shell
$ pip install flask
```
```shell
$ flask --version
Python 3.6.10
Flask 1.1.1
Werkzeug 1.0.0
```
**Running**
```shell
$ export FLASK_APP=hello.py && flask run

 * Serving Flask app "hello.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

**Comment by scribu** [comment]
Now I can't reproduce it either.

That's so strange, as I haven't updated my conda install or the Flask version.

Sorry for the goose chase.
