### ISSUE TITLE
A problem about request.json

### ISSUE THREAD

**Issue by jiangyanglinlan** [pallets/flask#3531]
### Expected Behavior

When 'Content-Type': 'application / json' is set and the request sent by the user does not have json, the request will report an error, then the client will get 400 Bad request.I don't know if it should be.

Through debug I found that `request.json` will deserialize the request json data, and json is None, so it will throw an error.

```python
# a example
# Client code
url = 'http://localhost:5000/api/v1/oauth'
response = self.client.get(url, headers={
    'Content-Type': 'application/json'
})
print(response)
print(response.data)
```

### Actual Behavior
User get 400 bad request
`.400 Bad Request: The browser (or proxy) sent a request that this server could not understand.`
```pytb
# print(response)
.<Response streamed [400 BAD REQUEST]>
# print(response.data)
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>400 Bad Request</title>\n<h1>Bad Request</h1>\n<p>The browser (or proxy) sent a request that this server could not understand.</p>\n'

```

### Environment

* Python version: 3.7.5
* Flask version: 1.1.1
* Werkzeug version: 1.0.0

**Comment by ThiefMaster** [comment]
That does sound like a bad request to me...

**Comment by davidism** [comment]
If you try to get `request.json` and there's no JSON, it returns a bad request response by default. There are mechanisms to control this behavior, see the docs.
