### ISSUE TITLE
Code reload prevents server start 

### ISSUE THREAD

**Issue by renatofsp** [pallets/flask#3532]
### Expected Behavior
Executing flask.run(debug=True) should start the server (for development purposes at least)
```python
#app.py file
app = Flask(__name__)
app.config["SERVER_NAME"]="localhost:9191"
if __name__=="__main__":
    app.run(debug=True)
```

### Actual Behavior
The server does not start stays ad eternum on " * Restarting with ....":
if **watchdog-0.10.2** is installed (with pip install watchdog)
 * Restarting with windowsapi reloader
if **watchdog-0.10.2** is **not** installed
* Restarting with stat

No Exception is shown on the logs whatsoever just hangs

### Extra information
Server run as expected if
```python
#app.py file
app = Flask(__name__)
app.config["SERVER_NAME"]="localhost:9191"
if __name__=="__main__":
    app.run()
```
or 
```python
#app.py file
app = Flask(__name__)
app.config["SERVER_NAME"]="localhost:9191"
if __name__=="__main__":
    app.run(debug=True, use_reloader=False)
```

### Environment

* Python version: 3.8.2
* Pip version: 20.0.2
* Flask version: 1.1.1
* Werkzeug version: 1.0.0

**Comment by davidism** [comment]
I can't reproduce this issue. The reloader works as expected with and without Watchdog installed, with the versions specified.

**Comment by renatofsp** [comment]
can you tell me what OS are you running? I'm running windows 10 Pro x64 1903.

I just:
1.  setup a fresh new virtual env 
2. installed flask from scratch and same issue

this is my pip list under the virtual env:
```console
Package           Version Location
----------------- ------- ------------------------------------------------------------------
astroid           2.3.3
Click             7.0
colorama          0.4.3
Flask             1.1.1
Flask-Cors        3.0.8
isort             4.3.21
itsdangerous      1.1.0
Jinja2            2.11.1
lazy-object-proxy 1.4.3
MarkupSafe        1.1.1
mccabe            0.6.1
pathtools         0.1.2
pip               20.0.2
PyJWT             1.7.1
pylint            2.4.4
setuptools        45.3.0
six               1.14.0
Werkzeug          1.0.0
wheel             0.33.6
wrapt             1.11.2
```

**Comment by davidism** [comment]
I used a fresh virtualenv on Windows 10.

**Comment by renatofsp** [comment]
@davidism you are correct I found the difference IDE related this happens when debugging with VSC IDE 

sorry for the false positive ticket
