### ISSUE TITLE
how to solve Connection was closed cleanly . scrapy flask gevent Process 

### ISSUE THREAD

**Issue by luoqishuai** [pallets/flask#3539]
Description
scrapy code
```
            url='http://192.168.5.9:6010/predict?url={}'.format(response.meta['url'])
            data={'html_url':response.meta['url'],'html_cn_text':cn_result}
            meta['status_404']=True
            meta['response']=response
            meta['proxy']=''
            return scrapy.FormRequest(url,formdata=data,callback=self.parse,dont_filter=True,meta=meta)
```
flask gevent code
```
monkey.patch_all()
app = Flask(__name__)
ctx=app.app_context()
ctx.push()

# 获取本机ip
myaddr = '192.168.5.73'
myport = 6010
decide_404=Decide404()
@app.route('/predict',methods=['POST','GET']) 
def predict():
    try:
        start_time=time.time()
        if request.method == "GET":
            return 'http method need post'
        elif request.method == "POST":
            form = request.form
            data = form.to_dict() #
            html_url=data['html_url'] if 'html_url' in data else ''
            html_text=data['html_cn_text']
            score=decide_404.decide_model(html_text)
            logging.info('url: {} ;text: {} ;predict: {} ;cost: {} ;'.format(html_url,html_text[:20],score,round(time.time()-start_time,2)))
            return str(score)
        else:
            return 'None'
    except Exception as e:
        logging.info('error {} '.format(e),exc_info=True)
        return 'None'
server = WSGIServer(('', 6010), app)
server.start()
def serve_forever():
    server.start_accepting()
    server._stop_event.wait()

if __name__ == "__main__":
        try:
            for i in range(32):
                p = Process(target=serve_forever)
                p.start()
        except Exception as e:
            logging.info('404 webserver false')
            decide_404.send_email('404 webserver false')
```

scrapy is responsible for sending post requests to my service, and the service is responsible for processing post requests and returning calculation results
However, scrapy will soon catch in middlwares when making a request. 

> /Scrapy_spider_9.log:2019-12-20 16:13:50 [root] INFO: get url https://news.10jqka.com.cn/tapp/news/ share / 616126829 / is 404 by error {'url': 'https://news.10jqka.com.cn/tapp/news/share/616126829/', 'retry': 0, 'url_format': 'https: / /news.10jqka.com.cn/tapp/news/share/()/ ',' article_id ': 616126829,' upload_type ':' news', 'download_timeout': 60.0, 'proxy': '', 'download_slot' : 'news.10jqka.com.cn', 'download_latency': 1.4705162048339844, 'status_404': True, 'response': <200 https://news.10jqka.com.cn/tapp/news/share/616126829/> , 'depth': 1, 'status': ResponseNeverReceived ([<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>],)}

[Exception. The server does not have extra anti-crawl processing.
The server has captured the requested address:

> :: ffff: 192.168.5.9--[2019-12-20 16:13:58] "POST /predict?url=https://news.10jqka.com.cn/tapp/news/share/616126829/ HTTP / 1.1 "200 115 3.574375

And the calculation will only return '0', '1', 'None'
The request was recorded in the server's log and the result was obtained

> ./decide_404.log:[2019-12-20 16: 13: 58,449] [decide_404.py:300] [INFO] [url: https://news.10jqka.com.cn/tapp/news/share/616126829 /; text: Jiahua Energy's monthly big order reveals the secret number of mobile straight flush financials; predict: 1; cost: 3.57;)

scrapy setting.py
```
CONCURRENT_REQUESTS =20
DOWNLOAD_TIMEOUT = 60
CONCURRENT_REQUESTS_PER_IP = 0
CONCURRENT_REQUESTS_PER_DOMAIN = 1000
DOWNLOAD_DELAY = 0
REACTOR_THREADPOOL_MAXSIZE = 1000
```

Another phenomenon is that scrapy sends a request, and then quickly returns an error that the connection was cleaned up. However, after 8 seconds, gevent showed that the request was received and then processed it.

So who cleans it up, is scrapy automatically cleaned up because of too many requests, or gevent cleans up because of too many concurrents. Both have mechanisms to delay processing.
For scrapy delayed requests, it should be timeout and the time returned is abnormal. I see stackoverflow that gevent can handle any number of requests, and if gevent cleans up the request, why does it continue to calculate the request?

This is the timeline in the log
```
2019-12-20 16:13:50 scrapy:The request has been sent and returned an exception.
2019-12-20 16:13:58 gevent console :Shows that there is a request coming.
2019-12-20 16:13:58 gevent Calculate the request
```

1.  I sent a request and soon scrapy told me the connection was cleared
2.  8 seconds after(or other times)
3.  Flask console shows that the request has been received
4.  Flask begins to calculate the request
But my scrapy request never came to fruition

Where is the setting wrong? Scrapy flask gevent?

The server did not perform any additional anti-crawling measures on the request, why does scrapy catch exceptions such as Connection was closed cleanly.

scrapy = 1.8.0 falsk =1.1.1 gevent =1.4.0 Werkzeug =0.16.0 python3 =3.6.5

**Comment by luoqishuai** [comment]
I want to know  why some of  my scrapy request was closed cleanly.

**Comment by luoqishuai** [comment]
I find it difficult to provide test cases.
I can only describe my code as best I can.
I know my description is sketchy. Is there anything else you'd like to know.

**Comment by davidism** [comment]
I'm sorry, this issue tracker is for issues specifically with Flask itself. We can't help debug your project.

**Comment by luoqishuai** [comment]
> 
> 
> 对不起,这个问题跟踪器是专门与瓶本身问题。 我们不能帮助调试您的项目。

Don't you have any clue? I think the question it's not scrapy, is flask and gevent
Can you give me some hints and directions for the query?
