### ISSUE TITLE
Update documentation of url_for to indicate more clearly that substitution token values are required (maybe an example?)

### ISSUE THREAD

**Issue by nathan-rice** [pallets/flask#354]
Upon initially reading the url_for function documentation I assumed that if I provided an endpoint matched to a URL rule with substitution tokens without specifying substitution values, it would return the base rule.  Having debugged my problem and re-read the url_for documentation closely, I realized that you tried to express this, it just isn't very 'tard friendly.

**Comment by jeffwidman** [comment]
Closing because this is an ancient issue that hasn't gotten much traction. PRs to improve the docs are always welcome if you want to take a stab at fixing this.
