### ISSUE TITLE
Memory leak running Flask in debug mode

### ISSUE THREAD

**Issue by robbitara** [pallets/flask#3540]
I'm developing a web server and running Flask in debug mode is giving me a really strange issue.
If I try to send through an XHR a blob with "application/octet-stream" as Content-Type to the Flask server, I successfully receive the file, but RAM memory increase exactly by the same size of the file and never gets released until I press CTRL+C to stop Flask. Even if I close the browser, memory stays there.
In particular this happens if run this .sh script on bash:
```bash
# start_flask.sh
if [[ -n $1 ]]; then
	# I select this option
	if [[ $1 == '-s' ]]; then
		export FLASK_ENV=development
		export FLASK_APP=wsgi/j_wsgi.py
		flask run
	elif [[ $1 == '-l' ]]; then
		git log --oneline --decorate --graph --all
	else
		echo "Invalid arguments"
	fi
else
	echo "No arguments given"
fi
```
Instead, running this simple command doesn't give any issue:

`env FLASK_APP=wsgi/j_wsgi.py flask run`

I think the problem it's not browser related, because I tested it on several clients:

- **Google Chrome** (v80.0.3987.149-1)
- **Chromium** (v80.0.3987.149-1)
- **Firefox** (v73.0.1-1)
- **curl** (v7.68.0-1)

This is the Javascript function running on the browser:

```javascript
function sendBlob(file)
{
    var chunkSize = 500000000; // 500 MB

    var xhr = new XMLHttpRequest();

    var blob = file.slice(0, chunkSize, "application/octet-stream");

    xhr.open("POST", "http://127.0.0.1:5000/api/get_layout/");

    xhr.onreadystatechange = function()
    {
        if (this.readyState == 4 && this.status == 200)
            console.log("blob successfully sent.");
    }

    xhr.setRequestHeader("Content-Type", "application/octet-stream");
    xhr.setRequestHeader("X-Content-Name", "blob");

    xhr.send(blob);
}
```
I tried also with curl:
`curl --data-binary @filename -H 'Content-Type: application/octet-stream' -H 'X-Content-Name: blob' application' http://127.0.0.1:5000/api/get_layout/`

Here is the python running on the server:
```python
# main.py
from flask import Flask, abort, render_template, send_file, request, send_from_directory, abort, Response, jsonify

import json
from flask_restful import Api, Resource, reqparse
from flask_wtf.csrf import CSRFProtect

import socket
import re

from werkzeug.datastructures import FileStorage

import os
import shutil

app = Flask(__name__)
csrf_protect = CSRFProtect(app)
api = Api(app, decorators=[csrf_protect.exempt])

# implementing parser
cmd_parser = reqparse.RequestParser()

# adding parser arguments
cmd_parser.add_argument('file_', type=str, required=False, location='json')
cmd_parser.add_argument('file', type=FileStorage, location='files')

@app.route('/')
def hello_world():
    return render_template("index.html")

class Upload(Resource):

    def post(self):

        filename = request.headers['X-Content-Name']
        content = request.data

        f = open("/home/roberto/upload/" + filename, "ab")
        f.write(content)
        f.close()

        return "OK"
    
    def get(self):
        return "GOOD"

api.add_resource(Upload, "/api/get_layout/")
```

### Environment

* Python version: 3.8.1
* Flask version: 1.1.1
* Werkzeug version: 0.16.0

**Comment by davidism** [comment]
This is probably tied to how Python manages memory, it doesn't necessarily release memory back to the OS when something is deallocated. It may also have to do with how the debugger stores previous frames, which is only for the development server where we don't really care about memory use. There's not really anything I can see here that would be specific to Flask outside development mode, so I don't think there's anything we can do to address it.
