### ISSUE TITLE
how remove response header server 

### ISSUE THREAD

**Issue by hktalent** [pallets/flask#3542]
how remove response header server 
how remove 
```
Server: Werkzeug/0.15.6 Python/3.7.3
```

**Comment by ThiefMaster** [comment]
The dev server is not meant for production, and in development it shouldn't really matter

**Comment by hktalent** [comment]
resp = make_response("Hello, World!")
# I can set None
resp.headers['server']=None
but can not del
del resp.headers['server']

@ThiefMaster

**Comment by ThiefMaster** [comment]
I doubt you can remove it. Again, why do you need to remove it in development?
