### ISSUE TITLE
Testing docs are out of date

### ISSUE THREAD

**Issue by mattc41190** [pallets/flask#3545]
The **Tutorial** section of the docs refers to to the most recent `Flaskr` application structure however the **Testing Deep Dive** section is still referring to an application structure from at least the `0.12` version of the tutorial which assumes an application structure that doesn't involve the  app factory. This could certainly confuse a new comer... I mean not me.... I certainly wasn't confused by it _shifts eyes around nervously_

Ref: Ref code snippet here

https://flask.palletsprojects.com/en/1.1.x/testing/#the-testing-skeleton

**Comment by devarshigoswami** [comment]
Can I work on this?

**Comment by greyli** [comment]
This issue may related with https://github.com/pallets/flask/issues/2833.

@devarshigoswami Sure, we are happy to review a PR.

**Comment by isdanni** [comment]
Added a pull request [here](https://github.com/pallets/flask/pull/3606#issue-415740732) :thumbsup:

**Comment by jackwardell** [comment]
is there an appetite for testing examples with requests and selenium?
