### ISSUE TITLE
url  //  404

### ISSUE THREAD

**Issue by luoqiuluoqiu** [pallets/flask#3550]
When I used flask and found ‘//‘’ in the url, 404 appeared

```python
from flask import Flask, request, render_template,url_for
app = Flask(__name__)
@app.route('//login', methods=["GET"])
def login():
    return 'ok'
print(app.url_map)
app.run()
```

result:
![image](https://user-images.githubusercontent.com/18000060/78228209-f8a16d00-7500-11ea-8b27-a2890910a52b.png)
-------------------
![image](https://user-images.githubusercontent.com/18000060/78228601-80877700-7501-11ea-8be9-1d47133ef847.png)
---------------------------
![image](https://user-images.githubusercontent.com/18000060/78228630-867d5800-7501-11ea-9947-0037331f55ae.png)

### Environment

* Python version:3.6
* Flask version:1.1.1
* Werkzeug version:

**Comment by ThiefMaster** [comment]
you shouldn't have `//` in your url.

**Comment by luoqiuluoqiu** [comment]
> you shouldn't have `//` in your url.

I have to use it because the project requires it

**Comment by dotunpeters** [comment]
Try using 
`@app.route('%//login', methods=["GET"])`

**Comment by davidism** [comment]
Werkzeug 1.0 added the [`merge_slashes`](https://werkzeug.palletsprojects.com/en/1.0.x/routing/?highlight=merge#rule-format) option. Set that to `False` for your route if you absolutely need consecutive slashes. Be aware that you will also have to configure the web server and any other proxies in front of your application to also not merge slashes.
