### ISSUE TITLE
Remove simplejson

### ISSUE THREAD

**Issue by davidism** [pallets/flask#3555]
In modern Python it's unlikely to be significantly better than the built-in `json`. The module used by `JSONMixin` is overridable, so users can plug it in again if they want.

See pallets/itsdangerous#146 and pallets/werkzeug#1766.

**Comment by owaiskazi19** [comment]
@davidism if this issue open can I pick it up?

**Comment by davidism** [comment]
Sorry, it's already assigned to me, I'm working on it. You're welcome to work on any unassigned issues without PRs on any Pallets project.

**Comment by owaiskazi19** [comment]
Sure Np! I'll look for some other issue.

**Comment by svidela** [comment]
Hi,

I'm relying on `simplejson` to serialize `decimal.Decimal` objects when calling to `jsonify`. In fact, `jsonify` it's called by flask-smorest which I'm using for building my API. What would be the recommended way (if any) to force `jsonify` to keep using `simplejson`?

Regards,

**Comment by davidism** [comment]
```python
from simplejson import JSONEncoder

app.json_encoder = JSONEncoder
```
