### ISSUE TITLE
Reloader does not work correctly with lazy loading

### ISSUE THREAD

**Issue by wieczyk** [pallets/flask#3556]
I observed that reloader does not work correctly with threads on my system (latest Ubuntu).

```
wieczyk@tortilla:~/Repozytoria/Finanse/utargsystem$ FLASK_ENV=development FLASK_APP=web/main.py flask run
 * Serving Flask app "web/main.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 135-710-631
127.0.0.1 - - [04/Apr/2020 23:14:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2020 23:15:02] "GET /markets/6 HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2020 23:15:06] "GET /markets/7 HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2020 23:15:07] "GET /symbols/1350 HTTP/1.1" 200 -
127.0.0.1 - - [04/Apr/2020 23:17:24] "GET /symbols/1350 HTTP/1.1" 200 -
 * Detected change in '/home/wieczyk/Repozytoria/Finanse/utargsystem/web/main.py', reloading
```

After `Detected change` I see that reloading has no effect. Further changes in a file are not detected.

I observed that adding `--eager-loading` to the command line solves problem -- it est reloading has effect and further changes are detected correctly. Hence my conclusion that `lazy-loading` is a problem.

**Comment by davidism** [comment]
There's not enough information here to reproduce the issue. I just tried the reloader on latest Ubuntu, and it works as expected.

**Comment by wieczyk** [comment]
What information do you need?
