### ISSUE TITLE
Different logging (handler) behavior when running app with pycharm debugger

### ISSUE THREAD

**Issue by nachiketrss** [pallets/flask#3559]
When python logging is configured prior to creating the flask app, then the behavior of app log handler changes based on where I place the pycharm debugger. Not sure if this is a bug, but I thought best to raise so can be reviewed please.

Code:

```python
import logging
from flask import Flask
logging.basicConfig(level=10, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

app = Flask(__name__)

for log_handler in logging.getLogger().handlers:
    log_handler.setLevel('WARNING')

var_test = 1
```

### Behavior
I place the debugger debug point on the last line, and hit the debug button. When the debugger hits the debug point, the value of app.logger.handlers shows 1 stream handler for the app logger and the value of logging.getLogger().handlers shows 1 stream handler for the python root logger.

Where as if I place the debugger debug point at the for loop, and also on the last line of the code, and hit debug button. Step over to the last debug point, notice that the value of app.logger.handlers shows nothing and the value of logging.getLogger().handlers shows 1 stream handler for the python root logger.

Why is there such a difference in behavior?

### Environment

* Python version: 3.6.5
* Flask version: 1.0.2

**Comment by davidism** [comment]
I can't reproduce this issue. Perhaps you're affecting the order that things are initialized by accessing them in different orders while looking at debug watches? Flask will add a handler only if there's not a handler for the app logger's level already added in the chain.

**Comment by nachiketrss** [comment]
1. When you say "Flask will add a handler" - do you mean to the root logger or flask logger?

2.  At what point in the execution will the adding of handler happen? Is it when app is initialized or when the flask logger is invoked?

**Comment by nachiketrss** [comment]
Please can you tell me:

1. When you say "Flask will add a handler" - do you mean to the root logger or flask logger?

2. At what point in the execution flow will the automatic adding of handler happen? Is it when app is initialized (app=Flask(__name__) or when the flask logger is invoked via for example app.logger.info?
