### ISSUE TITLE
How to deal with multiple slashes in URL

### ISSUE THREAD

**Issue by muteebakram** [pallets/flask#3565]
Hi,

consider this URL http://abc/e/f. This route perfectly works that is fine.

If the client sends this URL http://abc/e///f as you can see there are multiple slashes
The output is a redirect HTML page when merge_slashes(werkzeug RULE) is True

Since I am using flask for REST APIs I don't want HTML page I want flask to go to that redirect link directly.
Also, I don't want to use curl -L option

How can I solve this issue?

* Python version:2.7
* Flask version:1.1x
* Werkzeug version:latest

**Comment by davidism** [comment]
See the merge_slashes option added to Werkzeug 1.0. Note that multiple slashes is not what you want in most cases.

**Comment by davidism** [comment]
Werkzeug 1.0 will merge multiple slashes in the dev server and when matching and building rules.
