### ISSUE TITLE
Problem with "flask run" command

### ISSUE THREAD

**Issue by Miloszun** [pallets/flask#3568]
### Expected Behavior
Flask should execute the "flask run" command.

```python
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"
```

### Actual Behavior
An error appears: "Fatal error in launcher:"

### Environment

* Python version: 3.8.2
* Flask version: 1.1.2

**Comment by ThiefMaster** [comment]
https://www.google.com/search?client=firefox-b-d&q=%22Fatal+error+in+launcher%22

Doesn't sound directly related to Flask...

**Comment by Miloszun** [comment]
The problem is that all of these solutions refer to Python's Pip. In these errors there is also a directory path after the colon. In my case there's no path.

**Comment by ThiefMaster** [comment]
So you get no traceback etc either? Please post what exactly you run in the shell and all the output.

**Comment by Miloszun** [comment]
I run "flask run" in cmd and I get "Fatal error in launcher:".

**Comment by ThiefMaster** [comment]
OK, so you:

- did not mention that you are apprently on Windows
- apparently did not set the FLASK_APP env var pointing to your app?

**Comment by Miloszun** [comment]
Oh, sorry, I did set the variable and yes, I am on Windows. The problem still occurs though.

**Comment by ThiefMaster** [comment]
What did you set it to?

**Comment by Miloszun** [comment]
To a flaskblog.py file. The content of it is in the first post.

**Comment by davidism** [comment]
I can't reproduce this issue. I created the sample file, did `set FLASK_APP=flaskblog.py`, and `flask run` ran as expected. It sounds like this is a problem with how your Python, pip, or virtualenv is installed or created.
