### ISSUE TITLE
werkzeug.routing.BuildError: Could not build url for endpoint 'cap.mjpg'

### ISSUE THREAD

**Issue by mhechthz** [pallets/flask#3570]
Hi,

I wanted to provide a video_feed as found in many examples. As long as I use:
```
@app.route('/video_feed')
def video_feed():
```    
and in index.html `<img src="{{ url_for('video_feed') }}">` all works well. If I change the code like this:
```
@app.route('/cap.mjpg')
def video_feed():
```    
and  `<img src="{{ url_for('cap.mjpg') }}">` I get the error:
`werkzeug.routing.BuildError: Could not build url for endpoint 'cap.mjpg'. Did you mean 'static' instead?`

On the other hand  I can directly access the video_feed by `http://myip:5000/cap.mjpg`, so basically it works but the html template has problems.

**Comment by davidism** [comment]
The endpoint name is `video_feed`, so that's what should be used with `url_for`.
