### ISSUE TITLE
werkzeug.routing.BuildError: Could not build url for endpoint 'cap.mjpg' no. 2

### ISSUE THREAD

**Issue by mhechthz** [pallets/flask#3571]
Unfortunately the original question was closed, so I could not answer or ask again. Sorry for opening the same issue again (https://github.com/pallets/flask/issues/3570).

If I take the example from flask (many others are comparable) :
```
@app.route('/<username>')
def show_user(username):
    pass
```
then **route** and **function** don't match in name. So why I cannot write:
```
@app.route('/cap.mjpg')
def video_feed():
```
I'm really sorry if I don't understand the concept of decorators here, but I didn't find anywhere that the names have to match. 
At least 
```
@app.route('/cap.mjpg')
@app.route('/video_feed')
def video_feed():
```
works with calling `http://myip:5000` (using index,html) as well as `http://myip:5000/cap.mjpg` (as direct access to video stream).

So the basic question is, why changes in `<img src="{{ url_for('video_feed') }}">`  don't work, or work only if I change the decorater **and** the function name.

**Comment by davidism** [comment]
The endpoint name is `video_feed`, so that's what should be used with `url_for`.
