### ISSUE TITLE
RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by zxiaozhou** [pallets/flask#3585]
### Expected Behavior

```python
Flask-apscheduler gets the loaded redis configuration information from Flask create_app
```

### Actual Behavior

```pytb
RuntimeError: Working outside of application context
```

### Minimum example 

```
git@github.com:zxiaozhou/example.git
```

### Environment

* Python version: 3.6
* Flask version:1.1.2
* Werkzeug version:pycharm 2020.1

# Part of the network problem has not been submitted. I want to save it first and then modify it.
# So before I could finish, I was locked up, and the management desk got excited

**Comment by ThiefMaster** [comment]
You are doing things wrong. Don't push app contexts randomly, especially not at import time.

In any case, this is not a flask issue so either ask in a place related to flask-apscheduler or in our Discord/IRC channels.

**Comment by zxiaozhou** [comment]
@ThiefMaster But I've deleted 'app.app_context().push()' as well。

**Comment by zxiaozhou** [comment]
The main idea is to uniformly read the configuration information in memory from flask everywhere. But something went wrong

发自我的iPhone

**Comment by ThiefMaster** [comment]
If you have to access the app or flask config at import time you are doing something wrong. The only case where this is OK is while instantiating your app. There is no need to change anything on the flask side.
