### ISSUE TITLE
Increase a max header size, when using the GET request

### ISSUE THREAD

**Issue by pcyoung75** [pallets/flask#3593]
Hi 

I'd like to know how to increase the maximum header size for the GET request. 

The tornado server allows to increase it as shown bellow, so that one can use the GET request with a large request header.  

**tornado.httpserver.HTTPServer(application, max_header_size=1024 ** 3)**

Should I use a werkzeug configuration to do this?

Thank you very much in advance.

**Comment by davidism** [comment]
No, the WSGI application doesn't control this. You'll need to configure the servers in front of it.

**Comment by pcyoung75** [comment]
Thank you very much!
I got it.
