### ISSUE TITLE
after_request executed if exception raised

### ISSUE THREAD

**Issue by eLRuLL** [pallets/flask#3607]
### Expected Behavior
`after_request` not being executed

```python
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    raise ValueError("after_request should not run")
    return 'Hello, World!'


@app.after_request
def after_request_func(response):
    print('after request executed')
    return response
```

### Actual Behavior
`after_request_func` is being executed

According to [the documentation](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Flask.after_request), this shouldn't be executed if an unhandled exception is present

This is happening on all versions since 1.1.0 (1.1.0, 1.1.1, 1.1.2, not happening on 1.0.4)

### Environment

* Python version: 3.7.7
* Flask version: >=1.1.0
* Werkzeug version: 1.0.1

**Comment by carc1n0gen** [comment]
I believe this is expected behaviour.  Exception interrupt the normal request/response flow.  In order to get to the after_request handler, the view function needs to have completed successfully.

**Comment by davidism** [comment]
From the changelog:

> #3266 `Flask.finalize_request` is called for all unhandled exceptions even if there is no `500` error handler.

Relevant section from the PR writeup:

> While fixing this, I noticed that `finalize_request` was only called if a 500 error handler was found. If no custom handler was registered, then an unhandled error would skip `after_request` functions, saving the session, and sending the `request_finished` signal. This is now fixed, so `finalize_request` is always called.

The wording in the docs is "might not", not "will not". The existing code was fixed to apply `finalize_request` in more places where it was possible.
