### ISSUE TITLE
Blueprint cli commands cannot provide help for cli groups

### ISSUE THREAD

**Issue by Sebi2020** [pallets/flask#3608]
### Expected Behavior
There should be a way to specify blueprint command group help.
```python
from flask import Blueprint
editUser = Blueprint("editUser",__name__) # cannot add help to this entry (flask --help)

# Will be ignored:
editUser.__doc__ = "maybe this adds help...."

@editUser.cli.command("seed")
def seed():
    """ Seeds user database (will be shown if you type flask editUser --help)"""
    pass
```

### Actual Behavior
Currently flask does not provide a way to display help for blueprint commands.

*`flask --help` Output:*
```
Options:
  --version  Show the flask version
  --help     Show this message and exit.
Commands:
  editUser 
  routes    Show the routes for the app.
  run       Run a development server.
  shell     Run a shell in the app context.
```

### Environment

* Python version: 3.6.9
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

### Suggestion 
Add a cli_group_help keyword to blueprints:
```
editUser = Blueprint("editUser",__name__, cli_group_help="Provides user management commands")
```

**Comment by davidism** [comment]
`bp.cli` is a Click `Group`, assign to `bp.cli.short_help` to set its help text in the list.
