### ISSUE TITLE
flaskenv is not read on windows

### ISSUE THREAD

**Issue by phanirithvij** [pallets/flask#3610]
### Expected Behavior

`.flaskenv` should be read by flask.

### Actual Behavior

```python
# app/__init__.py
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello():
    return 'Hello, Flask!'
```

```env
# .flaskenv
FLASK_APP=main.py
```

```py
# main.py
from app import app
```

With this file structure
```
project/
     - .flaskenv
     - app/
          - __init__.py
     - main.py
```

with `flask run` I get

```pytb
Error: Could not locate Flask application. You did not provide the FLASK_APP environment variable.
```

A question on [SO](https://stackoverflow.com/q/53725865/8608146)

### Environment

**On Windows 10**

```
Flask 0.12.2
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]**
```

minimal example zip 
[project.zip](https://github.com/pallets/flask/files/4621092/project.zip)

**Comment by carc1n0gen** [comment]
Did you install the `python-dotenv` package?

**Comment by davidism** [comment]
Flask 0.12 is no longer supported. I can't reproduces this issue, `.flaskenv` is loaded if python-dotenv is installed.
