### ISSUE TITLE
question about "quickstart"

### ISSUE THREAD

**Issue by joeydream** [pallets/flask#3613]
I just follow the website learn about flask ,
when reaching to

quick start, variable rules:

I type all the prog and save as .py
try to export but 
404 Not Found

I just wonder that I should create a database called escape

right?
![Screenshot_20200518-002321_Chrome](https://user-images.githubusercontent.com/56774958/82162730-a0e77700-989e-11ea-8f49-c502b5350729.jpg)
![Screenshot_20200518-003023_Chrome](https://user-images.githubusercontent.com/56774958/82162758-d1c7ac00-989e-11ea-86e9-1727aa106064.jpg)

### Expected Behavior

```python
# Paste a minimal example that causes the problem.
```

### Actual Behavior

```pytb
Paste the full traceback if there was an exception.
```

### Environment

* Python version:
* Flask version:
* Werkzeug version:

**Comment by ThiefMaster** [comment]
The quickstart guide explains how to run your flask app:

```
$ export FLASK_APP=hello.py
$ flask run
 * Running on http://127.0.0.1:5000/
```

PS: Are you seriously trying to do development directly on a mobile phone without using a PC/laptop?!
