### ISSUE TITLE
App config(debug set to true but it still appears as false). Is this a bug?

### ISSUE THREAD

**Issue by SarpongAbasimi** [pallets/flask#3615]
As you can see from the application config, I have set
`'ENV': 'development', 'DEBUG': True`.

but flask still says  `Debug mode: off`.

Is that a bug?

<img width="1024" alt="Screenshot 2020-05-18 at 20 43 25" src="https://user-images.githubusercontent.com/37377831/82253234-781bbc00-9948-11ea-874e-6cb3964b5f82.png">

* Python version:3
* Flask version:1.1.2
* Werkzeug version:

**Comment by davidism** [comment]
Config can't be used for this when using the CLI, use the environment variables.
