### ISSUE TITLE
Flask app prints environment variable as object instead of string returned from os.getenv

### ISSUE THREAD

**Issue by khteh** [pallets/flask#3630]
I have the following code snippet in my main.py:
```
import os
from app import create_app
from models import db, bcrypt
if __name__ == '__main__':
    HOST = os.environ.get('SERVER_HOST', 'localhost')
    try:
        PORT = int(os.environ.get('SERVER_PORT', '5555'))
    except ValueError:
        PORT = 5555
    env_name = os.getenv('FLASK_ENV', "Please set FLASK_ENV")
    print("env_name: ", env_name)
    app = create_app(env_name)
```
I run it using `flask run` inside `pipenv shell` and bump into the following error in the line which prints out the `env_name`. I have tried both `set FLASK_ENV=development` (Windows 10) and using `.env` but to no avail. I use python-3.8.3
```
(src-4Nvvrxp5) C:\Projects\Python\PythonFlaskRestAPI\src>flask run
 * Serving Flask app "main.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
env_name: <flask.cli.ScriptInfo object at 0x000002D6BA598940>
 * Debugger is active!
 * Debugger PIN: 269-678-937
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```
Any advice and insight is appreciated.
### Expected Behavior
```
C:\Projects\Python\PythonFlaskRestAPI\src>python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> env_name = os.getenv("FLASK_ENV")
>>> print(env_name)
development
>>>

C:\Projects\Python\PythonFlaskRestAPI\src>flask --version
Python 3.8.2
Flask 1.1.2
Werkzeug 1.0.1
```

```python
# Paste a minimal example that causes the problem.
```

### Actual Behavior

```pytb
Paste the full traceback if there was an exception.
```

### Environment

* Python version: 3.8.2
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by ThiefMaster** [comment]
Something is very wrong there. `flask run` does not execute `__main__` code.

**Comment by khteh** [comment]
I am not sure what you mean. Can you elaborate?

**Comment by ThiefMaster** [comment]
`the `__name__ == '__main__'` block should result in your `print` etc never being executed when you use `flask run`. so I'd check if you have similar code somewhere else.

Also, what is `FLASK_APP` set to?

**Comment by khteh** [comment]
I set `FLASK_APP=main.py` and that's why the code snippet runs.

**Comment by davidism** [comment]
There is something else wrong with your code that is causing this, unrelated to Flask. The code you've shown is unrelated, since `flask run` does not execute `__name__ == "__main__"`. I cannot reproduce your issue.

**Comment by jab** [comment]
Maybe one of your other modules that you’re importing whose code you haven’t shown has side effects at import time that are causing the FLASK_ENV env var to be overwritten to this object. IIRC, nothing in Flask itself would ever (over)write this env var, Flask only ever tries to read it.

Hope this helps. Please use StackOverflow for any further questions.

**Comment by khteh** [comment]
I have no problem running the project with `python src/main.py` on the same code. Doesn't this tell something wrong with flask? Repo: https://github.com/khteh/PythonFlaskRestAPI

https://stackoverflow.com/questions/62102156/flask-app-prints-environment-variable-as-object-instead-of-string-returned-from

**Comment by jab** [comment]
I verified that Flask itself never overwrites the FLASK_ENV env var. So something else that you’re doing must be erroneously setting it to the ScriptInfo object. I’d guess maybe some bad interaction between pipenv shell and your .env? Can you try running without those? Also print out the value of FLASK_ENV in earlier spots to converge on where it’s getting set to the bad value, or use a tool like strace when running to track down what’s setting this env var when.
