### ISSUE TITLE
shlex.parse fails to parse quoted args inside a Flask application

### ISSUE THREAD

**Issue by paulyhedral** [pallets/flask#3631]
### Expected Behavior
Quoted arguments should be parsed as a single argument.

```python
# Paste a minimal example that causes the problem.
args = shlex.parse('This is "Star Trek"')
```

```sh
['This', 'is', 'Star Trek']
```

### Actual Behavior
Quoted argument is parsed as two (or more) arguments.

```sh
['This', 'is', '"Star', 'Trek"']
```

### Environment

* Python version: 3.8
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by davidism** [comment]
Under what circumstances are you passing such a value? Flask doesn't do anything regarding this, and you haven't shown any code related to Flask.
