### ISSUE TITLE
So sorry! Can you explain it to me? There is no answer in other forums

### ISSUE THREAD

**Issue by hyfand** [pallets/flask#3661]
**about flask document! The Part Of Request**
_original text_
`Imagine the context being the handling thread. A request comes in and the web server decides to spawn a new thread (or something else, the underlying object is capable of dealing with concurrency systems other than threads). When Flask starts its internal request handling it figures out that the current thread is the active context and binds the current application and the WSGI environments to that context (thread). It does that in an intelligent way so that one application can invoke another application without breaking.`

i cant understand what mean the sentence is:
`It does that in an intelligent way so that one application can invoke another application without breaking.`

who can explain for me? thanks!

**Comment by davidism** [comment]
Our [contributing guide](https://github.com/pallets/flask/blob/master/CONTRIBUTING.rst), which is linked in the new issue form when you created this, outlines where to ask questions.
