### ISSUE TITLE
Show change log entries on PyPi / Include change log entries in the long description

### ISSUE THREAD

**Issue by jugmac00** [pallets/flask#3663]
Hi,

it would be awesome to have the change log entries on PyPi / included in the long description, so one could see at first glance what has changed.

My use case:
When I check dependencies for new versions, I usually first go to pypi and search for the name.
Quite some projects have included the contents of the change log also in the long description, so it is visible at the PyPi page.

For Flask, I went to PyPi, did not find the change log.
Then I clicked on documentation, I did not find the change log.
Then I clicked on Homepage, no change log.
Then I went to the GitHub repo and here we go... 

As a nice example, let's have a look at `attrs`:
I go to PyPi, search for attrs - I get all the info I need (the latest change log), and a link to the full change log.

Thanks!

**Comment by davidism** [comment]
I don't want to add this there, it's noisy and requires a bunch of maintenance to keep synched. In the docs there's a clear section called "changes" in the index, or in the repo there's a file called "changes". The log is linked to in each GitHub release.

**Comment by jugmac00** [comment]
Hi David,

thanks for getting back to me.

You don't want it and that's perfectly fine.

I don't think it is noisy, as it is usually at the bottom of the PyPi description, and there is zero maintenance when one uses something like `long_description=read("README.rst") + "\n\n" + read("CHANGES.rst"),` in the `setup.py`.

I had another look at the documentation, and indeed, it is not listed at the "Contents Section" - but you can find it when you scroll down to the bottom.

Any chance to make "Changes" a top level section so it is listed at the "Contents Section"?

![Screenshot from 2020-06-23 15-11-07](https://user-images.githubusercontent.com/9895620/85407711-d6e5de00-b563-11ea-8a14-75e82dc891c8.png)

**Comment by jab** [comment]
+1. Instead or in addition, would it help if we added an additional link under "Project links" on https://pypi.org/project/Flask/ for "Changelog"?

According to the [packaging docs](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls), looks like that would just be a matter of adding one more link to `project_urls` in [setup.cfg](https://github.com/pallets/flask/blob/master/setup.cfg#L5).

**Comment by jugmac00** [comment]
A `project_urls` entry would be super awesome! Didn't know you can set arbitrary key/value entries there. Thanks @jab!

**Comment by jab** [comment]
Cool, want to submit a PR?

**Comment by davidism** [comment]
That has the same problem as putting the log in the readme, the link had to be adjusted for each version. 

It's not possible to change the docs sidebar given the current way Sphinx and our theme works.

I'm not sure what's going on here, but it's completely normal to expect the changelog to be linked somewhere on the front page of the docs, usually bear the bottom where the list of versions isn't disruptive. I don't think anything needs to change about Flask specifically in this regard.

**Comment by jab** [comment]
> the link had to be adjusted for each version

Just to clarify this, I was thinking we would use a stable URL to always just link to the latest changelog, to avoid that problem. That would still be an improvement, IMO.

Would https://flask.palletsprojects.com/changelog/ do the trick?

**Comment by davidism** [comment]
That's reducing exactly one click and scroll. Go to the documentation, scroll to the changelog, click on the changelog. I don't want to start adding more links to things on the PyPI page, it's crowded enough as it is.

Tools that handle dependency updates and notifications, such as PyUp, Dependabot, Tidelift, and others all are able to detect the changelog just fine.

This is basically a request for busywork. I get that you took a bit of time to find the changelog. I don't think that warrants a change. We've now discussed this longer that any time lost by looking for the changelog.

**Comment by jab** [comment]
(And to further clarify, the problem I was sympathetic to here is going to https://pypi.org/project/Flask/ and seeing no reference to the changelog from that page.)
