### ISSUE TITLE
Flask using same styling on different flask projects

### ISSUE THREAD

**Issue by delivey** [pallets/flask#3685]
### Expected Behavior

When running another flask project, the styling should be it's own, not the project's that's been run 1 time before.
```python
# Paste a minimal example that causes the problem.
```
I run this repo: https://github.com/delivey/xevis using `flask run`. (repo doesn't matter, but i've only encountered this bug with styling which uses CSS)
I go to the website, do something on it, etc.
I close the website by pressing `CTRL+C` in the terminal.
I close said terminal window.

I open another terminal window on which I run this project: https://github.com/delivey/schoolvid19 (again, repo doesn't matter)
I get some weird styling which is clearly not of this project, but the one I ran before, although images and text are of the current project.

### Actual Behavior

I get styling from the project I ran before, but the text and images from the project I'm currently running.
```pytb
Paste the full traceback if there was an exception.
```

### Environment

* Python version: 3.8.3
* Flask version: 1.1.2
* Werkzeug version: 0.16.0

### How to fix

It is possible to fix this error, simply by hitting CTRL+SHIFT+R, which reloads the browser cache, but getting this bug fixed would be nice

### Images

![expected_styling](https://user-images.githubusercontent.com/35540227/87248179-b1603c00-c460-11ea-85bc-4928823addbf.png)
![old_project_styling](https://user-images.githubusercontent.com/35540227/87248180-b4f3c300-c460-11ea-8823-c35b768f88d9.png)
![weird_styling_got_by_running_the_new_project](https://user-images.githubusercontent.com/35540227/87248181-b58c5980-c460-11ea-9922-40c4409481b2.png)

**Comment by delivey** [comment]
sorry for not clarifying, the first image is the one I should have gotten by running the project, the second image is a screenshot of the old project i ran before, and the third image is the weird styling i shouldnt get

**Comment by ThiefMaster** [comment]
Flask does not have "styling". Sounds like you are running both projects on the exact same host+port and don't clear your cache (or use CTRL+F5) to reload when switching between projects.

**Comment by jab** [comment]
@delivey, it sounds like you may not understand how HTTP cache headers work and haven't seen Flask's https://flask.palletsprojects.com/en/1.1.x/config/#SEND_FILE_MAX_AGE_DEFAULT (this is a feature, not a bug). Here are some resources that may be helpful to you:
* https://web.dev/http-cache/#flowchart
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
* https://developers.google.com/web/fundamentals/performance/get-started/httpcaching-6
* http://whitenoise.evans.io/

**Comment by delivey** [comment]
thanks @jab. my mistake for blaming flask and not the way http works.

**Comment by jab** [comment]
@delivey, glad those references were helpful. In general, it is helpful to us to know where new users are having trouble, though in the future, please try asking in other places like StackOverflow before opening up a new bug. :)

**Comment by jab** [comment]
After further discussion, we’ve opened pallets/wekzeug#1882 to try to reduce confusion stemming from Flask’s current behavior.
