### ISSUE TITLE
Concurrent requests are taking more time then single request for python api code(using flask + waitres WSGI server)

### ISSUE THREAD

**Issue by SagarPalyal** [pallets/flask#3688]
When I am hitting api code with a single request, the response is coming back in 1 second approximately. Thats fine. As I am using waitress wsgi server , my flask code is handling concurrent request but problem is coming on performance. Whenever more than one concurrent requests are hitting api code, response time is getting increased to 1.5 sec to 2 sec to so on depends upon how many concurrent requests are hitting the api. More the concurrent requests more the response time for all requests. Provided threaded concept is working fine and currently waitress has been configured with 50 threads.

```python
from flask import Flask, request, g, jsonify
from waitress import serve
import json
import time

app = Flask(name)

@app.before_request
def before_request():
    g.start = time.time()

@app.route('/', methods=['POST', 'GET'])
def home():
    data = json.loads(request.data.decode('utf-8'))
    #some statements
    result = es.search() #fetching some data from elasticsearch
    #some statements
    data['New_key'] = 'some value' #updating data
    data['New_key1'] = 'some value' #updating data
    return jsonify(data)

@app.after_request
    def after_request(response):
    diff = time.time() - g.start
    return response

@app.errorhandler(Exception)
def handle_exception(e):
    return response

if name == 'main':
    serve(app, host='0.0.0.0', port=5000)
```

################################################
### Environment

* Python version: 3.7
* Flask version: 1.1.2
* Waitress version: 1.4.4

**Comment by davidism** [comment]
This is not caused by Flask. You'll need to profile your code to identify the parts that are slow.
