### ISSUE TITLE
Deploying doc mod_wsgi.rst is specific to Python 2.X

### ISSUE THREAD

**Issue by ghost** [pallets/flask#3696]
### Expected Behavior
The doc mentions to install libapache2-mod-wsgi package on debian/ubuntu but the package is for Python 2.x. For python 3.x the package to be installed is libapache2-mod-wsgi-py3. The document doesn't mention anywhere that the steps are specific to Python 2.x.

### Actual Behavior
Update the doc to Python 3.x specific steps or mention that the doc is specific to Python 2.x

### Environment

* Python version: 3.X
* Flask version: 1.1.2
* Werkzeug version:

### Links

Doc: https://flask.palletsprojects.com/en/1.1.x/deploying/mod_wsgi/#installing-mod-wsgi
Source: https://github.com/pallets/flask/blob/master/docs/deploying/mod_wsgi.rst

**Comment by raghavendrashekhawat2** [comment]
Hi. I would like to work on this issue as my first contribution may i ?.

**Comment by greyli** [comment]
@raghavendrashekhawat2 Sure thing! Be sure to update the third command too (`$ pkg install ap22-mod_wsgi2`), then test these commands on specific OS and Python version.
