### ISSUE TITLE
Add tip for set environment variable with Powershell in the Configuration documentation

### ISSUE THREAD

**Issue by eastbury13** [pallets/flask#3697]
Hi,

Minor tweak to the Debug Mode section of the documentation to include the command for Windows Powershell when changing environment to development:

$env:FLASK_ENV = "development"

Thanks
Steve
![Debugmode_screenshot](https://user-images.githubusercontent.com/64620034/88460738-4833ec00-ce96-11ea-9ca6-f7398decb857.PNG)

**Comment by greyli** [comment]
If we decide to update this one, there are a few places that need to update too (e.g. the section *[Configuring from Files](https://flask.palletsprojects.com/en/1.1.x/config/#configuring-from-files)*).

@davidism Any idea?

**Comment by davidism** [comment]
@greyli The [sphinx-tabs](https://github.com/djungelorm/sphinx-tabs) extension allows creating blocks with multiple tabs. That way, everywhere we do commands that depend on the shell, we can have tabs for "Bash", "CMD", and "PowerShell". Be sure to check that it renders OK, we might need to add some CSS to Pallets-Sphinx-Themes.

**Comment by greyli** [comment]
@davidism Sounds good, I will try to implement it.
