### ISSUE TITLE
Add CSS styling to Flask API docs hosted at palletsprojects.com, to aid visual navigation of the page.

### ISSUE THREAD

**Issue by vulcan25** [pallets/flask#3710]
### Expected Behavior
The page [API - Flask Documentation](https://flask.palletsprojects.com/en/1.1.x/api/) should have a CSS style applied which visually separates different sections, so when a reader navigates in through an anchor link, then scrolls through the document, it is easier to identify the end of a section.

I found this works nicely (the styling of course could be edited):

```
dl.function, dl.data, dl.class{
  border: 1px blue dashed;
  background-color:#fafafa;
  margin-bottom:30px;
}
```
This can be applied through the "style-editor" in Firefox dev tools to preview:

![Screenshot 2020-07-31 at 00 14 28](https://user-images.githubusercontent.com/6283434/88983812-ede6c100-d2c3-11ea-97ed-f882cc538fbe.png)

### Actual Behavior
One wall of text.

### Environment
https://flask.palletsprojects.com/en/1.1.x/api/

**Comment by davidism** [comment]
Thanks, I don't plan to change this right now, but feel you can to use an extension like Stylus to apply the style.
