### ISSUE TITLE
Support option to disable color escapes in the log

### ISSUE THREAD

**Issue by danny0838** [pallets/flask#3729]
Flask always generates color escapes in the log for each HTTP request once color package is installed, but color escapes are undesired for systems that don't support it (such as Windows) and when the log is to be written to a file.

I think we can add an option to disable generating the color escapes.

**Comment by davidism** [comment]
This is a bug with how color is added, there's an open issue in Werkzeug (on mobile, can't find it right now). We won't be adding a flag to disable it.

**Comment by danny0838** [comment]
> This is a bug with how color is added, there's an open issue in Werkzeug (on mobile, can't find it right now). We won't be adding a flag to disable it.

You probably means https://github.com/pallets/werkzeug/issues/1832. But I think the argument is invalid: even if it can be fixed to work with windows console, there's still a need to disable color escapes when the log is to be written to a file.

**Comment by danny0838** [comment]
Is there further reason for the request? Or should I open another issue for it?

**Comment by davidism** [comment]
I don't plan on adding a switch, please do not open a new issue for that.
