### ISSUE TITLE
Flask infer MIME type in javascript modules

### ISSUE THREAD

**Issue by danrneal** [pallets/flask#3731]
When loading static assets and a javascript module is declared like so:

```html
   <script
      type="module"
      src="{{ url_for('static', filename='js/app.js') }}"
    ></script>
```

and files are imported within the module like this:

```javascript
import SomeClass from './utils'
```

then it will have the content-type in the header set to 'html/text' and it will spit this error in the browser console

```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

The workaround for this is to import files in javascript like this:

```javascript
import SomeClass from './utils.js'
```

And then the server sends the correct content-type with the header.  My recommendation would be that if a file is getting imported as part of a javascript module, the server should infer that it is javascript even without the .js extension

Lastly, since it is the server that sets these headers, I assumed Flask was the culprit.  If I am mistaken, let me know where I should repost this issue.

### Environment

* Python version: 3.8.2
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by davidism** [comment]
Flask send files with the mime type detected from the file name. If you need another behavior, you can implement a different route to send files with a hard coded type.
