### ISSUE TITLE
Deprecation of itsdangerous.json

### ISSUE THREAD

**Issue by Brandogs** [pallets/flask#3745]
When running automated tests for a project using Flask, I am receiving the following error:

> DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in 2.1. Use Python's 'json' module instead.

* Python version: 3.6
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by davidism** [comment]
It sounds like you've installed a prerelease of itsdangerous (2.0.0a1). This warning (not error) is expected in that case. When released, Flask 2.0 will not raise that warning.

**Comment by pllim** [comment]
I just came across this warning as well with `flask` 1.1.2. Didn't do anything special to get `itsdangerous` 2.0.0a1. It was automatically pulled by other installations (possibly `flask` itself). When should I expect to see `flask` 2.0 release? Thank you.

**Comment by davidism** [comment]
Stop using `easy_install`, that's the only way you'd have got prerelease versions without requesting them. `easy_install` is no longer supported by setuptools, the Python packaging community recommends pip or another modern installer.

**Comment by pllim** [comment]
Not sure what is using it, but thanks for the tip.
