### ISSUE TITLE
Error 302 on Redirect after Form Post

### ISSUE THREAD

**Issue by kyle-walden** [pallets/flask#3752]
I have asked this on community forums, but to no avail. When redirecting to different routes after a form is submitted, an Error Response 302 (VFS connection does not exist) is thrown. The below is a small example of what I am dealing with, there are other redirects in other routes too that throw the exact same response. There is not anything odd about the code or the redirect, am I missing something? (I am using AWS Cloud9 by the way)

```python
app = Flask(__name__)

@app.route('/data/import-data', methods=['GET', 'POST'])    
def csv_import():
    
    if request.method == "POST":
        
        #fetch file, some logical tests, parse to pandas df and session data - this works all fine and well
        
        return redirect(url_for('map_fields')) #error occurs here
           
    return render_template('data-import-data.html')

@app.route('/data/import-data/map-fields', methods=['GET', 'POST'])
def map_fields():
     
    #get data from session data
    
    if request.method == "POST":
        
        #continue to work with the session data
        
        return redirect(url_for('data_table'))
        
    return render_template('data-import-map-fields.html')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True)
```
HTML form 
```HTML
<form class="" action="/data/import-data" method="POST" enctype=multipart/form-data>
      <div class="position-relative form-group"><label for="exampleFile" class="">File</label>
      <input name="csvfile" type="file" class="form-control-file">
      <small class="form-text text-muted">Max. file size 1.5MB(Mega-Bytes). Accepted file type .csv only. </small>
      </div>
      <div class="position-relative row form-check">
        <button hrefname="csvuploadbutton" class="mb-2 mr-2 btn btn-primary btn-lg btn-block" type="submit">Proceed
        </button>
      </div>
</form>
```

### Actual Behavior
`POST /data/import-data HTTP/1.1 302`
Page displays `VFS connection does not exist`
The URL after redirect does read correctly `/data/import-data/map-fields`

### Environment
Python 3.6.12
Flask 1.1.2
Werkzeug 1.0.1

**Comment by ThiefMaster** [comment]
It's not clear what your problem is. 302 is not an error, it's a [normal redirect](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302). Please ask e.g. in our [Discord](https://discord.gg/pallets) since this is not the place to ask for help with your code
