### ISSUE TITLE
could self.session_interface.save_session be run before the after_request_funcs are executed?

### ISSUE THREAD

**Issue by jay-tuckey** [pallets/flask#3764]
### Expected Behavior
Here:
https://github.com/pallets/flask/blob/master/src/flask/app.py#L1833-L1836
It would be nice if `after_request_funcs` could be run after the `save_session` function has been run. This would allow me to remove the session cookie from the response of a route, so that I can then have a templated route aggressively cached by my nginx reverse-proxy.  

```python
@app.route('/captive')
def captive():
    '''this url endpoint is static, and should be aggressively cached by nginx
    it doesn't provide any useful content, but has a JS embed for a web browser
    to trigger the auth if a user reaches it'''
    return flask.Response(
        response=render_template('captive.html'),
        status=200,
        headers={'Cache-Control': 'public,max-age=86400'},
    )
```

so from here:
https://github.com/pallets/flask/blob/master/src/flask/app.py#L1833-L1836

if the lines:
```python
        for handler in funcs:
            response = handler(response)
        if not self.session_interface.is_null_session(ctx.session):
            self.session_interface.save_session(self, ctx.session, response)
```
could be changed to
```python
        if not self.session_interface.is_null_session(ctx.session):
            self.session_interface.save_session(self, ctx.session, response)
        for handler in funcs:
            response = handler(response)
```
I think that would mean I could make a function that just deletes the session cookie header from the response?

### Actual Behavior
the `Set-Cookie: session=.....` header is still added to the response, and then possibly cached by nginx.

### Environment
* Python version: Python 3.8.5
* Flask version: 1.1.2  (but it still looks the same on the master branch)
* Werkzeug version: 1.0.1

I'm not sure if there's some obvious reason this can't be done.

I also tried getting the `url_map` and directly adding a werkzeug response creating function to it but the session info still got added.

**Comment by davidism** [comment]
It sounds like you want a custom session interface. I don't want to change the order that callbacks run.

**Comment by jay-tuckey** [comment]
Ok, thanks @davidism 

I've found a hacky workaround for a single function, but will look into making a custom session interface.

```python
@app.route('/captive')
def captive():
    '''this url endpoint is static, and should be aggressively cached by nginx
    it doesn't provide any useful content, but has a JS embed for a web browser
    to trigger the auth if a user reaches it'''

    # this is hacky - what we are doing is messing with the request context
    # we are setting the request context session to a NullSession
    # why, you ask? Well we need to cache this response, so we dont want any
    # user's session cookies saved in the response - therefore we need to
    # prevent the user's response session from being set when processing the
    # response. See https://github.com/pallets/flask/blob/1.1.x/src/flask/app.py#L2268-L2269
    # Also see: https://github.com/pallets/flask/issues/3764
    flask.globals._request_ctx_stack.top.session = flask.sessions.NullSession()
    
    return flask.Response(
        response=render_template('captive.html'),
        status=200,
        headers={'Cache-Control': 'public,max-age=86400'},
    )
```
