### ISSUE TITLE
Typo in Flask pallets fileuploads

### ISSUE THREAD

**Issue by miquelvir** [pallets/flask#3768]
### Expected Behavior
"if user does not select file, browsers also submit an empty part without filename" [missing plural s in 'browser']
or
"if user does not select file, browser also submits an empty part without filename" [missing present simple s in 'submit']

### Actual Behavior
"if user does not select file, browser also submit an empty part without filename"

Sorry if it should have been a pull request.

**Comment by ThiefMaster** [comment]
Yes, a PR would have been much better for this :)

Also, there should be a "the" before "user".

**Comment by miquelvir** [comment]
Okey, I'm going to close the issue and create a PR then.
