### ISSUE TITLE
why flask create a new thread with the same TID that already exists?

### ISSUE THREAD

**Issue by mengban** [pallets/flask#3770]
In my flask app, I start a dameon thread by:
```python
if __name__ == "__main__":
    # daemon thread
     t = threading.Thread(target=cls.daemon_thread)
     t.start()
     app.run("0.0.0.0", port=8081, debug=False)
```
where cls.daemon_thread is a method of the instance cls. 

### Expected Behavior

I start a new thread as a daemon thread to do some timing work and print some log at the same time. And the flask request 
will print some log too.
when I print the log, I also print PID(Process ID) and TID(Thread ID) to tell me  where the log from.

### Actual Behavior

``` Bash

L1:[2020-09-25 22:24:48,449 PID: 27642 TID: 140167677339392] INFO :  daemon thread output 
L2:[2020-09-25 22:24:48,549 PID: 27642 TID: 140167677339392] INFO :  daemon thread output 
L3:[2020-09-25 22:25:00,863 PID: 27642 TID: 140167677339392] INFO :  flask request output
L4:[2020-09-25 22:25:01,174 PID: 27642 TID: 140167677339392] INFO :    flask request output
```
When the I start the app, it works well, but after hours later, It  goes wrong. As u can see, L1 L2 are logs from daemon, and the TID of the daemon is **140167677339392**, but in the next request in L3, L4, flask starts a new thread with the same TID to deal with  the request. And the log from daemon thread never appears again.

### Environment

* Python version: 3.7.7
* Flask version:1.1.2
* Werkzeug version:1.0.1

**Comment by davidism** [comment]
Must be something about Python threads. Flask is not doing anything with threads in this regard. Werkzeug's development server will start threads, but it relies on Python's built-in `http.server`.
