### ISSUE TITLE
request.endpoint always None in SessionInterface.open_session

### ISSUE THREAD

**Issue by zeha** [pallets/flask#3776]
### Expected Behavior

Session Interface should have access to `request.endpoint` from `open_session`. In Versions before 1.1.0, this worked fine.

### Actual Behavior
Our SessionInterface subclass looks at `request.endpoint` to determine if it should open a new session - opening a new is only appropriate on some endpoints. Now this is always `None`, so it cannot make this distinction anymore.

I believe #3104 (issue #3088) broke this.

### Environment

* Python version: 3.8.5
* Flask version: 1.1.2
* Werkzeug version: 0.16.1

**Comment by Nta1e** [comment]
I would love to work on this @teymour-aldridge

**Comment by mbpreble** [comment]
Added a PR here which is simple enough - URL matching was happening immediately after session creation, now it happens immediately after.

**Comment by davidism** [comment]
Planning to roll this back, see #4053
