### ISSUE TITLE
@app.route should either trim urls or throw an error when route ending with space is provided

### ISSUE THREAD

**Issue by lalnuo** [pallets/flask#3780]
### Expected Behavior
If user writes code like this, @app.route should either throw an exception or trim the given path.
```python
from flask import Flask

app = Flask(__name__)

@app.route("/foobar ")
def hello():
    return "Hello, World!"
```

### Actual Behavior
@app.route silently accepts the url that ends with space and navigating to `/foobar` doesnt work. 

### Environment

* Python version: Python 3.8.0
* Flask version: 1.1.2
* Werkzeug version:

**Comment by davidism** [comment]
While this is probably not a good URL to use, there is nothing invalid about it. This would be a good test to add to a linter, such as a flake8 plugin for flask-related checks. But it is not an error, and would be incorrect for Flask to change the URL.

```python
from flask import Flask, url_for

app = Flask(__name__)

@app.route("/")
def index():
    return url_for("space")

@app.route("/space ")
def space():
    return "space"
```

```
/space%20
```
