### ISSUE TITLE
Enhancement Request: Response Class in Blueprint

### ISSUE THREAD

**Issue by upsteer** [pallets/flask#3783]
This is a feature request for implementing different response_class instances for individual Blueprint.
As of the latest release (1.1.x), we can only implement a global response_class for `app`.

This would be helpful in APIs where if we need a different response_class for APIs returning JSON instead of HTML.

**Comment by MarioCdeS** [comment]
This might pose a problem for testing. Werkzeug's test client class (Client) wraps the response from the WSGI app using an instance of TestResponse (or a derived class). The concrete type for the wrapper is set when the client is initialised, and is used in every subsequent call to Client.open, to wrap the response. You would need a way of changing this type, based on the current request's endpoint/blueprint, after the pytest client fixture has already been created i.e. after app.test_client() has been called. Something to consider.

**Comment by davidism** [comment]
@upsteer I'm not clear that this is particularly necessary, and it would add overhead to every single request to figure out what response class to use. If you want to return JSON, use `jsonify` or some REST extension that handles it for you. I'm not seeing a clear use case for this.

@MarioCdeS no that's not an issue. The test client's response is a wrapper around an arbitrary WSGI response, it's not directly related to the response object returned by a Flask view.

**Comment by MarioCdeS** [comment]
@davidism Thanks for clarifying. I was getting an instance of WrappedTestResponse back from the test client, which seemed to be of a class derived from both TestCase and response_wrapper, with respose_wrapper being app.response_class that was passed  to the FlaskClient initialiser, hence the comment.

**Comment by davidism** [comment]
That is how that unreleased new feature works, but it doesn't have any effect how this issue might have been implemented.
