### ISSUE TITLE
Set TRAP_BAD_REQUEST_ERRORS to True as the default when debugging is enabled

### ISSUE THREAD

**Issue by catlee** [pallets/flask#382]
When debugging an application, it's surprising to get a simple "400 Bad Request" when accessing a form parameter that doesn't exist instead of a full traceback. I always forget that I also need to set TRAP_BAD_REQUEST_ERRORS.

Is there a reason why this isn't set by default when debugging is enabled?

**Comment by Tjorriemorrie** [comment]
@mitsuhiko  Please think positively about it; it just wasted hours of my life :(

**Comment by jeffwidman** [comment]
Tenatively assigned to 1.0 milestone as that's the logical time to make a decision around changing this API.
