### ISSUE TITLE
Web site / documentation: Should tell what Flask *is*

### ISSUE THREAD

**Issue by MorrisR2** [pallets/flask#3833]
I went to the web site to find out what Flask **is**.  That question is never directly answered, that I can find.
It might be helpful if the front page of the web site and/or the _Introduction_ page in the documentation had 1-3 sentence statement of what the heck Flask is.  What's it for?

At present, the documentation on the site gives no indication of why one should read more, of what Flask can do.
Reading through the first bits of the docs, I get the feeling that maybe Flask has something to with writing web services in Python.

**Comment by ThiefMaster** [comment]
Doesn't "Flask is a lightweight WSGI web application framework." together with the quickstart example pretty much explain what Flask does? :)

**Comment by MorrisR2** [comment]
That sentence probably makes perfect sense to someone who already knows all about Flask.  To someone who doesn't - actually no, it really doesn't tell me what it does or why I might want to use it.  Flask does something for writing applications.  Python is for writing applications. So no, that really doesn't tell me anything about what Flask does beyond what Python does.

I bet that if you wrote a sentence or two about what Flask *does* instead of a dictionary definition of what it is that might be much more informative.

**Comment by davidism** [comment]
Unfortunately, we're not going to be able to write descriptions of this or any other thing that is 100% clear to 100% of people. This is not something I can devote more effort towards.
