### ISSUE TITLE
How to verify a flask web app in the google search console

### ISSUE THREAD

**Issue by akionsight** [pallets/flask#3840]
I have been trying to verify my flask web app in the google search console using the HTML file upload method but when uploading the file to the root directory, it does not appear and raises a 404 error. I also tried putting it in the templates folder but still, 404 was raised. Is there any way I can prevent this behavior and make it work

**Comment by ThiefMaster** [comment]
Define a route that serves the code/file needed for verification. Or configure your web server to serve a file for the verification URI instead of forwarding the request to your Flask app...

**Comment by akionsight** [comment]
Sorry, but the following method did not work. What did work was the authentication via the meta tag. 
Steps to do so:
- Copy the meta tag for the authentication
- Navigate to the HTML file being served on `/` or your home page
- Paste the meta tag in the head tag or the HTML file
- Deploy your website
- Go to the search console and click authenticate
- And You will be done
