### ISSUE TITLE
Flask master requires Werkzeug master

### ISSUE THREAD

**Issue by drewja** [pallets/flask#3849]
After cloning and installing the master branch I was trying to use flask.send_from_directory which is a wrapper to a call to
werkzeug.utils.send_from_directory which incidentally does not exist on a release version of werkzeug.

After following CONTRIBUTING.rst to install flask master in a clean virtualenv and running pytest. Many tests fail, I quickly realized that the version of werkzeug installed is not compatible with flask HEAD. 
```pytb
# Paste a minimal example that causes the problem.
(flask-test) $ pip install -e . -r requirements/dev.txt
(flask-test) $ pytest
...
FAILED tests/test_views.py::test_remove_method_from_parent - TypeError: argument of type 'BaseRequest' is not iterable
====================================== 215 failed, 233 passed, 3 xpassed in 8.90s ======================================
```

After making the following change (sourcing the master branch of werkzeug from github in setup.py),

```
diff --git a/setup.py b/setup.py
index 6218be60..61bb4d4e 100644
--- a/setup.py
+++ b/setup.py
@@ -10,7 +10,7 @@ setup(
     name="Flask",
     version=version,
     install_requires=[
-        "Werkzeug>=0.15",
+        "werkzeug @git+git://github.com/pallets/werkzeug@master#egg=werkzeug",
         "Jinja2>=2.10.1",
         "itsdangerous>=0.24",
         "click>=5.1",
```
```
(flask-test) $ pip uninstall werkzeug
(flask-test) $ pip install -e . -r requirements/dev.txt
(flask-test) $ pytest
================================================= test session starts ==================================================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
...
============================================ 448 passed, 3 xpassed in 1.92s ============================================
```

I didn't submit a PR because I'm not sure if this is the right way to fix this for building master, I think the real fix is publishing a new release of werkzeug so we can use a version number.

**Comment by davidism** [comment]
Yes, Flask dev currently requires Werkzeug dev. No need to submit a PR, it's just temporary as I work towards the next release.
