### ISSUE TITLE
Requiring endpoints to have a __dict__

### ISSUE THREAD

**Issue by piotrmaslanka** [pallets/flask#3864]
I've stumbled upon this bug while trying to bear Cython down with Flask.

Flask namely requires it's endpoint functions to have a `__dict__`, while Cython's def's are created as builtin_methods_or_functions which don't have a `__dict__`.

I've solved the problem in way mentioned [here](https://github.com/flasgger/flasgger/pull/451), but I still think it's a wrong design pattern to demand your endpoints to have a `__dict__`.

**Comment by davidism** [comment]
> Flask namely requires it's endpoint functions to have a `__dict__`

As far as I know, Flask itself does not. `@app.route` records the function, but does not modify it. I can't tell from the linked issue how this is related to Flask.

**Comment by piotrmaslanka** [comment]
> > Flask namely requires it's endpoint functions to have a `__dict__`
> 
> As far as I know, Flask itself does not. `@app.route` records the function, but does not modify it. I can't tell from the linked issue how this is related to Flask.

It does not have to be modifying. Accessing some wild attribute of this function would suffice to yield this kind of error.

**Comment by davidism** [comment]
As far as I can tell, Flask doesn't access anything on the view functions that would require `__dict__`. You've pointed to a separate library called flasgger, which is not this project. If you want to report an issue with Flask, please provided a minimal reproducible example for Flask.

**Comment by piotrmaslanka** [comment]
You're right. This only affects Flasgger. 
I'm sorry to bother you.
