### ISSUE TITLE
"Request" object has no attribute "is_xhr"

### ISSUE THREAD

**Issue by wangkai19961223** [pallets/flask#3869]
It seems  "Request" object has no attribute "is_xhr" ，Getting warnings here...  How do we fix this?
![6f2ab2c357e4a36213b6ad42b7d9669](https://user-images.githubusercontent.com/70581416/104300976-16751700-5502-11eb-9b61-51f3baa8d083.png)

**Comment by greyli** [comment]
Duplicate of #3493. The `request.is_xhr` property was deprecated since Werkzeug 0.13 and removed in Werkzeug 1.0.0. You will get this error when using Flask <= 0.12.4 and Werkzeug >=1.0.0. You can just upgrade Flask to fix this issue:

```
$ pip install -U flask 
```
Or with Pipenv:
```
$ pipenv update flask
```
