### ISSUE TITLE
Flask's Celery docs are going to start failing with Celery 6 and get deprecation warnings with 5.x today

### ISSUE THREAD

**Issue by nickjj** [pallets/flask#3871]
The current docs are at: https://flask.palletsprojects.com/en/1.1.x/patterns/celery/

They reference Celery's old configuration options which are the `CELERY_*` options. Since 5.x they've been renamed to be lowercase and there's an official migration guide available on Celery's site at https://docs.celeryproject.org/en/stable/userguide/configuration.html#conf-old-settings-map.

As of Celery 5.x, the old uppercase variants throw a deprecation warning and 6.x will remove them.

The current Flask docs for Celery reference things like:

```py
    celery = Celery(
        app.import_name,
        backend=app.config['CELERY_RESULT_BACKEND'],
        broker=app.config['CELERY_BROKER_URL']
    )
```

```py
flask_app.config.update(
    CELERY_BROKER_URL='redis://localhost:6379',
    CELERY_RESULT_BACKEND='redis://localhost:6379'
)
```

These imply you're using Flask's configuration mechanism which require uppercase variable names to be available, but that conflicts with Celery's new lowercase variables.

I talked with @ThiefMaster a few weeks ago about this on IRC and he came up with a great idea of doing:

```py
# settings.py

CELERY_CONFIG = {
  "broker_url": "redis://localhost:6379/0",
  "result_backend": "redis://localhost:6379/0"
}
```

And then in your Celery factory you can do `celery.conf.update(app.config.get("CELERY_CONFIG", {}))`.

This solves the problem and is working out nicely in practice. I'm doing that in a real project, along with extracting out the duplicate Redis connection string into an environment variable, etc.. A working example of that pattern is at https://github.com/nickjj/docker-flask-example/blob/ca1d48499a4007378bbe363bd5dc117c1a33cc3a/config/settings.py#L21-L28.

I didn't want to open a PR without asking first because I'm not sure which direction you want to go with the docs. To be honest the current docs are a little confusing because you jump straight into using Flask's app configuration values but there's no reference to setting up those config values.

Also with the current docs if you attempt to break things into separate files you'll end up with circular import issues when importing your tasks unless you start importing your tasks directly inside of the function you're using instead of the top of the file, but that's another issue. Although potentially semi-related if you plan to revamp the Celery docs.

**Comment by davidism** [comment]
That's fine, I've started using that config dict pattern in other places too.

**Comment by jaoxford** [comment]
I wouldn't worry too much about failure. I don't think that Celery 6 is going to be released for at least a year or two. It seems that they drop a major release every couple of years.

**Comment by davidism** [comment]
I'd also like to investigate if our docs reflect a modern approach to Celery use and integration, beyond the configuration.

**Comment by lecovi** [comment]
After a quick review in Celery documentation I didn't get any insight on having a new approach. But I'm a little bit rusty with Celery. Let me know if you are thinking in something in particular. 

I've just submitted #4581 to update the Configuration docs about Celery
