### ISSUE TITLE
Falsk url redirect with Masking

### ISSUE THREAD

**Issue by khannavivek** [pallets/flask#3873]
Is there a way to redirect url in flask app and mask the url?

```
@app.route("/test")
def handle_ext_url():
    url = "https://www.google.com"
    return redirect(url)
```

I just want my addressbar to show localhost:8080/test but the page should show google.com.

**Comment by nhdinh** [comment]
I think you want to embed google.com into your iframe.
The above code just redirect the browser to google.com, not embed it.

**Comment by ThiefMaster** [comment]
awful idea, don't do that. nobody likes frames nowadays.

also completely out of the scope of this issue tracker or flask in general.

**Comment by khannavivek** [comment]
@nhdinh @ThiefMaster 
I do not want to use iframe, I just want to mask my address bar to my flask app host port and show web content of redirected url.
Similar to what we do in the masked domain forward.

**Comment by nhdinh** [comment]
> @nhdinh @ThiefMaster 
> 
> I do not want to use iframe, I just want to mask my address bar to my flask app host port and show web content of redirected url.
> 
> Similar to what we do in the masked domain forward.

Got it. I think this issue is out of Flask scope.

**Comment by davidism** [comment]
"I just want to compromise browser security by hiding one site behind another URL." Stop trying to make what sounds like an email scam. Focus on more important and legitimate things, like the functionality of *your* site.
