### ISSUE TITLE
Testing docs example for setting 'g' seems incorrect

### ISSUE THREAD

**Issue by kmjbyrne** [pallets/flask#3878]
### Expected Behavior
In the Flask Testing docs: https://flask.palletsprojects.com/en/1.1.x/testing/#faking-resources-and-context

There is an example illustrating how to utilise the @contextmanager to set g early that appears to be misleading. The appcontext_pushed hook isn't correctly invoked following the example given.

In the usage section that uses the test_client, it appears app.app_context() gets the desired results.

Here is how I got it to work:

```python
@contextmanager
def user_set(state, _user):
    def handler(sender, **kwargs):
        g.user = _user

    with appcontext_pushed.connected_to(handler, state):
        yield

# yours is def user_set
with user_set(self.application, user):
    # use app_context() instead of test_client() context manager
    with app.app_context():
        client = app.test_client()
        # then make your request
        ...
```

### Environment

* Python version: 36
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by davidism** [comment]
This appears to work as currently documented. The following prints `{"username":"flask"}`:

```python
from contextlib import contextmanager

from flask import appcontext_pushed
from flask import Flask
from flask import g

app = Flask(__name__)


@app.route("/users/me")
def users_me():
    return {"username": g.user}


@contextmanager
def set_user(app, user):
    def handler(sender, **kwargs):
        g.user = user

    with appcontext_pushed.connected_to(handler, app):
        yield


with set_user(app, "flask"):
    with app.test_client() as c:
        r = c.get("/users/me")

    print(r.get_data(as_text=True))
```

The `with client` block isn't necessary here, that's only for persisting cookies, but it doesn't make any difference either way.
