### ISSUE TITLE
Flask silently overrides Jinja2 tojson filter

### ISSUE THREAD

**Issue by J08nY** [pallets/flask#3881]
### Expected Behavior
The `tojson` filter from Jinja2 will be used.

```jinja2
{{ some_object | tojson }}
```

### Actual Behavior
The Flask `tojson` filter overwrites the Jinja2 `tojson` filter. The Flask's filter is not as configurable as the Jinja2 one and when one configures the Jinja2 one and tries to use it in a template this behavior and silent override is hard to debug.

### Environment

* Python version: 3.9.1
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

### Suggested changes
Add a configuration option to choose between overriding the Jinja2 `tojson` filter or not. Make the default to override to keep current behavior. Will make a PR for this if it seems reasonable.

**Comment by ThiefMaster** [comment]
I think I'd rather make the flask one as configurable as the jinja one, so flask just adds functionality on top of it...

**Comment by davidism** [comment]
The two do the exact same thing, except Jinja's has an `indent` parameter. Given that indentation shouldn't matter anyway, I don't see that as particularly important. That said, you too can override the `tojson` filter to do whatever you want, just remember to at least do `Markup(flask.json.dumps())`.

**Comment by davidism** [comment]
Took another look at how Jinja's is implemented, and it allows setting the `dumps` function through `Environment.policies`, so we could actually completely drop our implementations of `tojson` and `htmlsafe_dumps` by adding the following to `Flask.create_jinja_environment`:

```python
rv.policies["json.dumps_function"] = flask.json.dumps
```

Users could further customize the dumps kwargs by setting `app.jinja_env.policies["json.dumps_kwargs"]`.
