### ISSUE TITLE
Views & Routing `methods` input throwing TypeError for tuples

### ISSUE THREAD

**Issue by gwolianglien** [pallets/flask#3882]
### Description

Hello fellow Flask(ers)! I'm not sure if this kind of issue belongs here, but please point me to the right place to post this if this is not the place to do so. I noticed a discrepancy between Blueprint routing source code and the [Flask pallets documentation](https://flask.palletsprojects.com/en/1.1.x/tutorial/views/) on it. If you follow this link, you'll see that the recommended way of setting up Blueprint and routing is as such:

```python
@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
    .....
```

However, if you actually do write your RESTful methods in a tuple as shown in the example, you'll encounter this error:

```python
TypeError: Allowed methods have to be iterables of strings, for example: @app.route(..., methods=["POST"])
```

I've gone through the [views.py source code](https://github.com/pallets/flask/blob/4e8b0204942d89c7956f4e1a20e97b1a16ba6800/src/flask/views.py) and see that there is an iteration through user inputted `methods`, which makes me wonder why this error occurs?

Much thanks for taking a look at this!

### Environment

* Python version: 3.9.0
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by davidism** [comment]
I can't reproduce this issue. The following runs without error:

```python
from flask import Blueprint
from flask import Flask

bp = Blueprint("example", __name__)


@bp.route("/register", methods=("GET", "POST"))
def register():
    return "hello"


app = Flask(__name__)
app.register_blueprint(bp)
```

The error message is shown when `methods` is a string, which suggests that unlike the code you've shown, you actually wrote `'GET, POST'`.

**Comment by gwolianglien** [comment]
@davidism FYI the code example I provided was directly from https://flask.palletsprojects.com/en/1.1.x/tutorial/views/ and not something I wrote myself. Perhaps something to pass along to whoever is in charge of documentation?

**Comment by davidism** [comment]
You have a typo then. I wrote the tutorial, I know it works. I just tried the exact same thing as shown above, and it works.
