### ISSUE TITLE
logout and factoring cookie problem

### ISSUE THREAD

**Issue by luckyxts** [pallets/flask#3900]
I use @login_required to check whether the user is authorized.But i save the cookie before i logout and then reassigned it in my browser.I can still be authorized.

I found that the content of the cookie is a password,which will contain "_id" and function "_session_protection_failed" in login_manager.py use "_id"  to check whether the user is authroized.I also found function verify_signature in singer.py use cookie and key to verify signature.

So in order to solve this problem.I change the key by use app.config["SECRET_KEY"] when logout.This method has no problem for my business at present.But i don't think it's a good idea.

Is that a question？and do i have any other good ways?

**Comment by davidism** [comment]
Please use [our Discord](https://discord.gg/pallets) for discussion about your own code. This tracker is for issues related to the project itself.
