### ISSUE TITLE
flask.run(post_func)?

### ISSUE THREAD

**Issue by gitpushdashf** [pallets/flask#3902]
From StackOverflow: https://stackoverflow.com/questions/54235347/open-browser-automatically-when-python-code-is-executed/54235461

```
import webbrowser

from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    webbrowser.open_new('http://127.0.0.1:2000/')
    app.run(port=2000)
```

What if there was: `app.run(port=2000 post_func=open_browser`?

Seems like maybe the cleanest way around this. post_func would be called once initialized to prevent race conditions.

**Comment by davidism** [comment]
Thanks for the suggestion. However, I don't plan to add that.
