### ISSUE TITLE
Flask Extension documentation references unmaintained Flask-OAuth

### ISSUE THREAD

**Issue by tophers42** [pallets/flask#3905]
This section: https://flask.palletsprojects.com/en/1.1.x/extensiondev/#initializing-extensions references Flask-OAuth as an example, but that project is unmaintained: https://github.com/mitsuhiko/flask-oauth#unmaintained
Recommend replacing the link with an actively maintained project. Perhaps: https://flask-dance.readthedocs.io/en/latest/

Environment:

- Python version: N/A
- Flask version: 1.1.X

**Comment by ThiefMaster** [comment]
[authlib](https://github.com/lepture/authlib) is also a good choice for oauth in flask

**Comment by greyli** [comment]
It's just used to demonstrate how to initialize the extension with classes for the extension developer, I don't think it needs to update.
