### ISSUE TITLE
CLI incompatibility with Werkzeug 2 LocalProxy

### ISSUE THREAD

**Issue by ziddey** [pallets/flask#3909]
LocalProxy has been changed in Werkzeug 2:

> LocalProxy matches the current Python data model special methods, including all r-ops, in-place ops, and async. __class__ is proxied, so the proxy will look like the object in more cases, including isinstance. Use issubclass(type(obj), LocalProxy) to check if an object is actually a proxy. :issue:`1754`

The Flask CLI can fail to run if the following conditions are met:

1. A `LocalProxy` is defined that requires an app context.
2. `FLASK_APP` is not defined.
3. The app is not named `app` or `application` or an app factory is used.

A simple `app.py` to reproduce:
```
from flask import current_app, Flask
from werkzeug.local import LocalProxy

log = LocalProxy(lambda: current_app.logger)

def create_app():
    app = Flask(__name__)
    return app
```

Then, running `flask shell` should drop nicely into the console. Instead, the result is `RuntimeError: Working outside of application context.`

Environment:

- Python version: 3.9
- Flask version: 1.1.2
- **Werkzeug version: 2.0.0rc1**

The issue is with this line: 
https://github.com/pallets/flask/blob/adeaf27e767f7bd37996d999eba135d63e890408/src/flask/cli.py#L51

and the aforementioned "the proxy will look like the object in more cases, including isinstance."

We can wrap the `isinstance` check in a try/except to ignore failing objects.

**Comment by PeterJCLaw** [comment]
It looks like this is the same underling issue as I hit with building Sphinx docs against a Flask project with Werkzeug 2. Adding this comment mostly in case others hit this via that route.

Specifically my case was that I have `flask.g` imported and it was that usage of `LocalProxy` which was hitting this error.
I've got fuller details in https://gist.github.com/PeterJCLaw/b017b2869590036d3d05a427fd9f34d0, though it looks like there's a fix on the way already - thanks :)

**Comment by alexdlaird** [comment]
My RTD doc builds are also now failing as a result of this, though for me I traced it to `itsdangerous` `2.0.0rc1`, not `Werkzeug`. I think it's because Flask pins `itsdangerous>=0.24`, though it does something similar with `Werkzeug`. In either case, seems Flask either needs to pin the high end of these as well so the latest `1.1.2` doesn't continue to have issues, or these RC candidates need to be made compatible with the existing released version (preferable so existing Flask builds with `1.1.2` pinned start working again).

**Comment by ThiefMaster** [comment]
If your code pulls in prereleases without `--pre` being used something is wrong on your site. Very outdated pip/setuptools maybe, or `python setup.py install` instead of pip?

**Comment by alexdlaird** [comment]
Yup, I raised that in the RTD issue, it's unclear why that happens (only in their env).

**Comment by ThiefMaster** [comment]
Try adding this to your `.readthedocs.yml`:

```yaml
python:
  setup_py_install: false
  pip_install: true
```

Possibly set the `version` in there as well. By default RTD uses the legacy setup.py commands.

**Comment by alexdlaird** [comment]
That fixed it, thanks so much!

**Comment by ThiefMaster** [comment]
RTD should probably switch to that by default instead of using legacy tools that are likely to break things nowadays...

**Comment by davidism** [comment]
Fixed by https://github.com/pallets/werkzeug/pull/2042/commits/352cd7167984f805daf226966f38f8dfeb991313
