### ISSUE TITLE
Enable *or disable* jsonify formtting regardless of app.debug = True

### ISSUE THREAD

**Issue by sam-wiser** [pallets/flask#3927]
My unit tests include testing error HTTP response output, created with `make_response`. I pass in a JSON object to `make_response` like so:
```
def error() -> Response:
	return make_response(
		{'err_msg': 'unable to verify'},
		401, 
		{'WWW-Authenticate': 'Basic realm="Login Required"'})
```

Then I test it like this:
```
    expected = Response(
        response=[b'{"err_msg":"unable to verify"}\n'],
        status=401,
        headers=[
            ('Content-Type', 'application/json'),
            ('Content-Length', '31'),
            ('WWW-Authenticate', 'Basic realm="Login Required"'),
        ],
    )

    result = error()

    for field in vars(result):
        assert getattr(result, field) == getattr(expected, field)
```

This passes when running with `current_app.debug = False`, and fails when the debug variable is True. The reason is the `flask.jsonify` function outputs pretty printed JSON in debug mode OR if `JSONIFY_PRETTYPRINT_REGULAR` config var is set, and unformatted JSON otherwise, [see here](https://github.com/pallets/flask/blob/4846e25e92638a1db5aa2b41f65eed7585366109/src/flask/json/__init__.py#L318).

I would like for my unit tests to pass in the way they're written regardless of if I'm running the tests in a debugger, which is of course very useful to do sometimes. Some config var or arg to `make_request` / `jsonify` that allows me to disable pretty printing would be great.

**Comment by davidism** [comment]
Debug mode shouldn't be enabled for testing, I'm not sure why you're doing that, it doesn't affect tests in any meaningful way.

Beyond that, you shouldn't be testing the exact formatting of JSON. Parse the JSON and validate that. In the next version of Werkzeug (and Flask), `response.get_json()` can be used for that.

I don't plan to add more configuration for JSON formatting at this time.

**Comment by sam-wiser** [comment]
For what it's worth, I have debug mode enabled because I'm running the tests in a debugger while I code, to grab values for test data and verify various operations in the context they'll run in.

I understand it's possible to test things other than the response string, but that's how these tests are written.
