### ISSUE TITLE
how to add #via in requirements

### ISSUE THREAD

**Issue by copdips** [pallets/flask#3929]
Hello,

I see the requirements files have `# via` under the module, could you please explain how to generate it, manually or with a magic command ?

https://github.com/pallets/flask/blob/master/requirements/dev.txt#L8

```python
alabaster==0.7.12
    # via sphinx
appdirs==1.4.4
    # via virtualenv
```

**Comment by ThiefMaster** [comment]
Those files are built using [pip-tools](https://github.com/jazzband/pip-tools)
