### ISSUE TITLE
[Suggestion]  Integrate password protection into Flask-Admin

### ISSUE THREAD

**Issue by codinghedgehog-python** [pallets/flask#3934]
I'd like to suggest to make Flask-Admin password protected out of the box just like it works in Django.
There is simply no reason for not doing that. I suggest to do it with next major release.

In can be as a integration of two extensions, Flask-Admin + Flask-BasicAuth.

**Comment by ThiefMaster** [comment]
Flask-Admin is not part of Flask, so please suggest that in the Flask-Admin repo...
