### ISSUE TITLE
Incorrect examples in docs Flaskr tutorial

### ISSUE THREAD

**Issue by stijnvdelsen** [pallets/flask#3948]
### Expected Behavior

Flaskr tutorial docs: https://flask.palletsprojects.com/en/1.1.x/tutorial/views/

The Flaskr Blueprints and Views tutorial explains how you can create a View in your Blueprint. It show the following code snippet on the page:

`@bp.route('/register', methods=('GET', 'POST'))`

I believe this is incorrect, because methods is argument that expects an array, thus this example will result into an error. This code snippet should be this `@bp.route('/register', methods=['GET', 'POST'])` I believe.

Environment:

- Python version: 3.7.7
- Flask version: latest

**Comment by ThiefMaster** [comment]
Did you try it? It doesn't matter whether you pass a list, tuple or set, or probably anything else that behaves like a container...
