### ISSUE TITLE
Changes link in readme doesn't work

### ISSUE THREAD

**Issue by Kyle-Verhoog** [pallets/flask#3953]
The "changes" link in the readme is broken: https://github.com/pallets/flask#links
![image](https://user-images.githubusercontent.com/6321485/113623785-d28b3d00-962c-11eb-9ae8-17b97fd3366c.png)

**Comment by davidism** [comment]
You're looking at the master branch on GitHub. You'll want to view the master build of the docs. Once 2.0 is released, these will match again.
