### ISSUE TITLE
BUG: No way of naming the flask main file "typing.py"

### ISSUE THREAD

**Issue by sinekonata** [pallets/flask#3956]
I create a python file on my `~/Desktop` named `typing.py` with minimal tutorial content inside :
```
from flask import Flask
app= Flask(__name__)
@app.route('/')
def website():
    return "This is my website!"
if __name__ == "__main__":
    app.run()
```
Then run `python typing.py`. This raises the error:
```
ImportError: cannot import name 'Flask' from partially initialized module 'flask' (most likely due to a circular import) (/home/dir/.local/lib/python3.9/site-packages/flask/__init__.py)
```
I managed to get the same error by naming the file `flask.py` or `werkzeug.py`.
But if I change the file name to `typingg.py` or even `int.py` or `str.py` all is fine.

Environment:

- Python version: 3.9.2
- Flask version: 1.1.2

**Comment by ThiefMaster** [comment]
Not using the name of a stdlib package for your app file may be a good idea ;) (that aside, not sure whether this is a bug that should be fixed or not..)

**Comment by davidism** [comment]
This is a general observation about Python's import system, not a bug with Flask.

**Comment by sinekonata** [comment]
But is anyone supposed to know that typing is a standard package? Besides, werkzeug and flask aren't in stdlib right? And if you can guess that naming it flask may be ill advised, how is one supposed to know all the dependencies of flask? I mean werkzeug means just "tool" in german, isn't this bug bound to happen to others as well?

**Comment by RonnyPfannschmidt** [comment]
@sinekonata by that logic every library would have to include the same boilerplate about figuring if the user renamed a stdlib module

imho thats just plain wrong

**Comment by sinekonata** [comment]
@davidism Are you saying this will happen with any other package as well? Do you have an article about the subject?

**Comment by sinekonata** [comment]
@RonnyPfannschmidt But werkzeug isn't in stdlib right?
