### ISSUE TITLE
JSON Lines support

### ISSUE THREAD

**Issue by azmeuk** [pallets/flask#3966]
[JSON Lines](https://jsonlines.org/) is a very simple data format. Here is the specification:
- Each line is a valid JSON object
- Encoding is UTF-8
- Line separator is `\n`

This data format is very convenient to stream huge dataset since the client side can start evaluating data as soon as the first line is received. This can also be done with the CSV format, but JSON seems more standard these days, especially on the browsers side.

I suggest implementing a `jsonlines` response utility, similar to `jsonify`.

I considered making a flask plugin instead, but the jsonlines specification is so simple, plus all the tooling is already there, that it makes sense to me to implement it directly in flask.
I volunteer to provide a patch if the idea is accepted, else I will make that plugin :)

It seems there is [no consensus on the mimetype](https://github.com/wardi/jsonlines/issues/36#issuecomment-586176344) to use yet, but there is a [RFC](https://tools.ietf.org/html/rfc7464) that defines `application/json-seq`. Maybe this is a good start?

What do you think?

**Comment by ThiefMaster** [comment]
I think an external package/library is a perfect place for this - in the (few?) cases where this is needed people can just install the library, without giving us the burden of maintaining this.

**Comment by davidism** [comment]
Sounds similar to SSE, which is similarly fairly simple and has an extension for it. Might be a good place to start.
