### ISSUE TITLE
Add redirect for the old versions of the changelog docs

### ISSUE THREAD

**Issue by greyli** [pallets/flask#3980]
[This commit](https://github.com/pallets/flask/commit/9e7d3a6b694b27f997266889ae463e06dd83a189) changes the URL of the changelog page from `/changelog` to `/changes`, this will break the URL in the [version warning banner](https://flask.palletsprojects.com/en/master/changes/#version-2-0-0) for non-stable versions.

I think we will need to add some redirect entries on [readthedocs's redirects setting page](https://readthedocs.org/dashboard/flask/redirects/) for old versions, for example:

- `/en/1.1.x/changes/` -> `/en/1.1.x/changelog/`

**Comment by davidism** [comment]
Fixed on all projects.
