### ISSUE TITLE
Do x before/after every request to a static resource.

### ISSUE THREAD

**Issue by Xd-pro** [pallets/flask#3987]
I was recently working on a project that involved a command line tool that would create static files for me. I need to make sure that the files are deleted around 5 minutes after they are served. I had to use a sort-of hacky solution to get this to work properly. https://stackoverflow.com/questions/67340382/how-can-i-run-a-function-after-each-request-to-a-static-resource-in-flask

Example possible syntax:

@app.after_static_request
def do_some_stuff(response):
  foo(response)
  return response

Excuse my rusty markdown skills.

**Comment by ThiefMaster** [comment]
Flask's static files feature is meant for assets that never change between deployments. If you serve dynamically generated content, add your own route and your own logic for deleting old files (a celery task could be an option).
