### ISSUE TITLE
Solution/ Feature Request for testing API while using Postgres

### ISSUE THREAD

**Issue by Grinch101** [pallets/flask#3990]
Having a test_client that can stack requests would be great while using after request and before requests to handle database connection.

I use before request to create a connection to database and after making the request, if any error doesn't occur, I commit the connection, otherwise roll it back.
This setup was great so far until I reached testing. with `test_client()` I can only make one request and since the before and after request will run while using test_client, my database will get affected with test data which is not my preference. 
I tried using test_request_contaxt to have a control on before and after requests funcs, but still cannot stack the requests.

for example I want to test a functionality called "update user". As the name suggest we need to sign up a test user, login in to it, and thet update the feature we want (for example name, email, etc). It would be great if we could stack all three requests and at the end rollback the changes. 
Maybe my sample/ sudo codes illuminates my point better:

```
# create app and register blueprints
app = create_app(DevelopmentConfig)

# Create a Global Connetion Pool:
connections = conn_pool(1, 10) # using psycopg2.ThreadedConnectionPool
```
```
@app.before_request
def open_conn():
    global connections
    g.conn = connections.getconn()

@app.after_request
def close_conn(response):
    if g.conn is not None:
        global app
        global connections
        if app.config['TESTING']:
            g.conn.rollback()
            connections.putconn(g.conn)
            g.conn = None
            return response
        elif not app.config['TESTING']:
            g.conn.commit()
            g.conn.cursor().close()
            connections.putconn(g.conn)
            g.conn = None
            return response
    else:
        return response
```

############# TESTING USING PYTEST :

```
def test_login2(app_runner):
    with app.test_client() as client:
        rs = client.post('/auth/signup',
                         data={'inputEmail': 'SomeNewEmail@gmail.com',
                               'inputPassword': 'A',
                               'client_name': 'ForTest'}
                         )
        data = json.loads(rs.data)['data']
        error = json.loads(rs.data)['error']
        assert error is None
        assert data is not None
        assert rs.status_code == 201
        rs2 = client.post('/auth/login',
                          data={'inputEmail': 'SomeNewEmail@gmail.com',
                                'inputPassword': 'A'})
        data = json.loads(rs2.data)['data']
        error = json.loads(rs2.data)['error']
        assert error is None
        assert rs2.status_code == 200
```

`assert rs2.status_code == 200` will fail because we have created a user, and rolled back the connection. So we cannot login in to that.
Is there any feature that I am not aware of to handle this situation without restructuring my app?

**_Many thanks in advance_**

**Comment by davidism** [comment]
This is outside the scope of Flask. There are libraries like Pytest-Flask-SQLAlchemy that help with testing databases.

**Comment by Grinch101** [comment]
Thanks for your quick reply. 
I managed to hack it somehow... I pushed an app_context, set a connection on g and after yielding test_client, I rolled back the connection. It is working like a charm...

```
@pytest.fixture(autouse=True, scope='module')
def _app_runner():
    app = creat_app(TestingConfig)
    yield app

@pytest.fixture(autouse=True, scope='module')
def client(_app_runner):
    conns = conn_pool(1,10)
    conn = conns.getconn()
    with _app_runner.app_context():
        g.conn = conn
        g.secret_key = _app_runner.config['SECRET_KEY']
        with _app_runner.test_client() as client:
            yield client
            conn.rollback()
            conns.putconn(conn)
```
