### ISSUE TITLE
While requesting API through https without slash it get permanently redirect 308 changing to http

### ISSUE THREAD

**Issue by kasimsharif** [pallets/flask#3994]
Assume following is the endpoint 

```
curl --location --request GET 'https://abc.com/hello'
```

From postman disable **Automatic follow redirects** from settings

You will get following response

```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a
		href="http://abc.com/hello/</a>.
	If not click the link.
```

While Permanent redirect 308, https gets automatically converted to http, which must not be

**Comment by ThiefMaster** [comment]
> https gets automatically converted to http, which must not be

Then flask does not know you are using HTTPS, e.g. because you are using a reverse proxy and do not use the ProxyFix middleware
