### ISSUE TITLE
jsonify() can't serialize numpy.float32()

### ISSUE THREAD

**Issue by zsong** [pallets/flask#4012]
Environment:

- Python version: 3.7.9
- Flask version: 1.1.2

The following code throws error - TypeError: Object of type float32 is not JSON serializable
```
    x = {'value': numpy.float32(0.1)}
    return jsonify(x)
```
but the jsonify() works for the type of float64
```
    x = {'value': numpy.float64(0.1)}
    return jsonify(x)
```

- Expected: jsonify() should handle float32 the same way as float64.

**Comment by davidism** [comment]
That's correct, numpy objects are not serializable by Python's `json` module by default, so you need to customize the encoder to handle that, or use numpy's functions to serialize its data.

**Comment by zsong** [comment]
Thank you. I also found this discussion on numpy board. https://github.com/numpy/numpy/issues/16432
