### ISSUE TITLE
Latest flask release (2.0.0) cannot import functions from flask_restful package

### ISSUE THREAD

**Issue by flumi3** [pallets/flask#4017]
### Description
The new flask version that got released today has problems with the flask_restful package and fails to import _endpoint_from_view_func from flask.helpers. I then changed my environments to older versions of flask and it was working again.

### How to replicate the bug:

**Requirements:**

- install newest version of flask
- install newest version of flask_restful

**Code example:** 

from flask import Flask
from flask_restful import Api

app = Flask(__name__)
api = Api(app)

@app.route('/')
def hello_world():
    return 'Hello, World!'

**Exception upon execution:**

app_1     | Traceback (most recent call last):
app_1     |   File "/app/app.py", line 3, in <module>
app_1     |     from flask_restful import Api
app_1     |   File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 14, in <module>
app_1     |     from flask.helpers import _endpoint_from_view_func
app_1     | ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/usr/local/lib/python3.9/site-packages/flask/helpers.py)

Environment:

- Python version: tested with 3.8 to latest
- Flask version: 2.0.0

**Comment by pgjones** [comment]
This is an issue with Flask-Restful, see #4009.
