### ISSUE TITLE
Assigning to attribute flask.g.[...] not defined in class slots (assigning-non-slot)

### ISSUE THREAD

**Issue by anders-kiaer** [pallets/flask#4020]
Thanks for a recent release of `flask` which looks great. :tada: Just started testing it out.

This is not directly a bug afaik, but our CI started failing on the new release of `flask` and `werkzeug`.

Following the flask documentation, it appears the recommended way of setting new attributes to `flask.g` is simply doing `flask.g.some_attribute = some_value`.

This example code
```python
from flask import g

g.some_attribute = 42
```
gives no `pylint` warning when used together with `pip install "flask<2" "werkzeug<2"`, however after `pip install --upgrade flask werkzeug` the same code gives the following `pylint` warning:
```
test_pylint.py:3:0: E0237: Assigning to attribute 'some_attribute' not defined in class slots (assigning-non-slot)
```

Any recommended code change that should be done related to setting attributes on the namespace object `flask.g`, or would the best recommendation be to silence `pylint` when used with newest `flask` + `werkzeug`?

**Comment by davidism** [comment]
`g` is a proxy object, and it is unbound in that example. Assigning to it is not doing what you expect even in previous versions. You can only use `g` within an application or request context.

```python
@app.before_request
def set_attr():
    g.some_attribute = 42
```

Or if you really need to test this without a request:

```python
with app.app_context():
    g.some_attribute = 42
```

**Comment by anders-kiaer** [comment]
@davidism Thanks for quick answer.

We are in practice doing it in an `@app.before_request`. I just moved it out in the snippet above in order to make a MWE when it comes to the `pylint` warning/feedback. In other words, using it inside an application/request context (also) raises the pylint warning.

**Comment by davidism** [comment]
That sounds like an issue with pylint. Unfortunately, `LocalProxy` is pretty magical, so it's not unexpected that static analysis tools might have trouble with it.

**Comment by hughsie** [comment]
> That sounds like an issue with pylint

Note, it also causes a failure in mypy with `"AppContext" has no attribute "some_attribute"`...

**Comment by davidism** [comment]
It looks like the type of `flask.globals.g` is incorrectly marked as `AppContext` instead of `_AppCtxGlobals`, which I can fix. However, neither of them set `__slots__`, so I'm not sure why that's the error.

**Comment by hughsie** [comment]
@davidism if you push a test branch I'd be happy to test with my app.

**Comment by davidism** [comment]
Ah, the issue will still be with `LocalProxy`, since it does set `__slots__`, and that's what the `g` object really is. That's probably still going to have to be reported to mypy and pylint.

**Comment by davidism** [comment]
The `__slots__` issue needs to be reported to pylint.

The "has no attribute" issue needs to be reported to mypy. It seems like it should allow any attribute since the class defines `__getattr__` and `__setattr__`. There's no good way for us to get mypy to ignore these errors. We could mark the object as `Any`, but then you wouldn't get the benefit of introspection/checking the methods that it has.

I updated the type annotation, but both messages are still produced, I don't think there's anything we can do.

**Comment by hughsie** [comment]
> I don't think there's anything we can do

I think anyone using either `mypy` or `pylint` is going to hit this on basically any project using Flask; most tutorials just tell you to create random properties on `g` and I fear the number of dupes for this issue is going to be huge when people start upgrading. Unfortunately I don't have the python experience to work this out. :(

**Comment by lucaswerkmeister** [comment]
> It looks like the type of `flask.globals.g` is incorrectly marked as `AppContext` instead of `_AppCtxGlobals`, which I can fix.

I assume this is also the reason for a mypy error I’m seeing since upgrading to Flask 2.0.0:

> app.py:390: error: "AppContext" has no attribute "setdefault"

`_AppCtxGlobals` has `setdefault`, `AppContext` doesn’t.

**Comment by davidism** [comment]
After experimenting, it looks like mypy understands that an object is a namespace for arbitrary attributes if `__getattr__`, etc. are defined, so I can add that to the globals class and things should start to work.

**Comment by pgjones** [comment]
Yea, the [SimpleNamespace](https://github.com/python/typeshed/blob/e66b7fa6600f0e193d3ee5fa14c27ba31c6cf3dd/stdlib/types.pyi#L130) is typed this way. I'm experimenting with Quart at the moment.

**Comment by hughsie** [comment]
@davidism this fixed the CI on the LVFS, thanks!

**Comment by surkova** [comment]
I'm in a similar seats here, trying to upgrade to 2.0.1 though:
```python
    @app.before_request
    def before_request():
        flask.g.start_time = time.time()
```
Getting
```
E0237: Assigning to attribute 'start_time' not defined in class slots (assigning-non-slot)
```

We are using attribute assignment to figure out how long the request takes and report it to datadog.

Any ideas on what we should be doing instead since it's 2.0.1 and not fixed for us yet?

**Comment by davidism** [comment]
Yes, that's a pylint error, not a mypy error. Nothing we can do about it, report it to pylint.

**Comment by anders-kiaer** [comment]
> Ah, the issue will still be with `LocalProxy`, since it does set `__slots__`, and that's what the `g` object really is. That's probably still going to have to be reported to mypy and pylint. The fact that it sets `__slots__` is not new, and it defines `__setattr__`, so not sure why the error started.

FWIW and future reference (if to be reported  in `pylint` and/or `werkzeug`), it looks like the reason the `pylint` warning started appearing is due to `LocalProxy`'s `__slots__` contains `"__dict__"` on `werkzeug<2` and does _not_ contain `"__dict__"` on `werkzeug>=2`.
