### ISSUE TITLE
When using url_for inside test_request_context, APPLICATION_ROOT is included in the path

### ISSUE THREAD

**Issue by gtmanfred** [pallets/flask#4030]
Here is a script to show this example

``` python
import flask

app = flask.Flask(__name__)
app.config.from_mapping({'APPLICATION_ROOT': '/models'})


@app.route('/test')
def test():
    return 'blah'


with app.test_request_context():
    print(flask.url_for('test'))


with app.request_context({'REQUEST_METHOD': 'GET', 'SERVER_NAME': 'localhost', 'SERVER_PORT': '80', 'wsgi.url_scheme': 'http'}):
    print(flask.url_for('test'))
```

``` bash
❯ python -m this
/models/test
/test
```

I would love if they both included the APPLICATION_ROOT, so that we can route stuff that has the url rewritten behind an api proxy, but it would be good to have them at least consistent.

Environment:

- Python version: 3.8.6
- Flask version: 1.1.2
- Werkzeug 1.0.1

**Comment by davidism** [comment]
If you're rewriting the path behind a proxy, you should apply [`ProxyFix`](https://werkzeug.palletsprojects.com/en/2.0.x/middleware/proxy_fix/) and this should already work.

**Comment by gtmanfred** [comment]
ahh, that works for that, but using url_for inside a test_request_context still applies APPLICATION_ROOT when the documentation says it should not inside a request context.  

https://flask.palletsprojects.com/en/1.1.x/api/#flask.url_for
> Configuration values APPLICATION_ROOT and SERVER_NAME are only used when generating URLs outside of a request context.

**Comment by davidism** [comment]
You need to set all the required values/headers in the environ to match. Or use something like `DispatcherMiddleware` to mount the app at a different location during development and testing too.

**Comment by gtmanfred** [comment]
ahh ok, cool, thanks.
