### ISSUE TITLE
get_send_file_max_age parameters changed in Flask 2.0

### ISSUE THREAD

**Issue by bazzadp** [pallets/flask#4031]
We use the following code to override the `SEND_FILE_MAX_AGE_DEFAULT` for certain file types:

```
# Set WOFF and WOFF2 caching to return 1 year as they should never change
class MyServer(Flask):
    def get_send_file_max_age(self, name):
        if name.lower().endswith('.woff') or name.lower().endswith('.woff2'):
            return 31536000
        return Flask.get_send_file_max_age(self, name)


# Initialize The Server
app = MyServer(__name__, template_folder=TEMPLATES_DIR, static_folder=STATIC_DIR)
```

As of the newly released Flask 2.0 this is failing with the following error:

```
  File "/Users/barry/almanac.httparchive.org/src/server/__init__.py", line 19, in get_send_file_max_age
    if filename.lower().endswith('.woff') or filename.lower().endswith('.woff2'):
AttributeError: 'PosixPath' object has no attribute 'lower'
```

So we have to change this to this to convert the name to a string:

```
# Set WOFF and WOFF2 caching to return 1 year as they should never change
class MyServer(Flask):
    def get_send_file_max_age(self, name):
        if str(name).lower().endswith('.woff') or str(name).lower().endswith('.woff2'):
            return 31536000
        return Flask.get_send_file_max_age(self, name)


# Initialize The Server
app = MyServer(__name__, template_folder=TEMPLATES_DIR, static_folder=STATIC_DIR)
```

Is this an intended behaviour change as [the documentation still says this uses a string as an argument](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.get_send_file_max_age) rather than a PosixPath?

Environment:

- Python version: 3.8
- Flask version: 2.0

**Comment by davidism** [comment]
You'll need to call `os.fspath(name)` if your code only expects to be working with strings and not `Path` objects.

**Comment by bazzadp** [comment]
Then should the documentation be updated to note it's now a Path object and not a string: https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.get_send_file_max_age

> **Parameters:** **filename** ([str](https://docs.python.org/3/library/stdtypes.html#str)) –
