### ISSUE TITLE
webtest does not get file

### ISSUE THREAD

**Issue by gbmarc1** [pallets/flask#4032]
File parameter not included in request view args

I have the following post request that fails with flask==2.0.0; but was working fine with flask<2.0.0.

Here is my call with the webtest wsgi app
```
from webtest import TestApp
api = TestApp("my_app_url")
api.post(
    f"projects/200000/workUnits/1/workUnitData/files",
    upload_files=[("file", "my_file_path.csv")],
    status=404,
)
```
Response is 400 because file is not included in `req.view_args`:
https://github.com/pallets/flask/blob/d575de5159a6e40944275763c9ada2801214058b/src/flask/app.py#L1485

The endpoint function is:
```
def projects_project_id_work_unit_work_unit_id_work_unit_data_files_post(project_id, work_unit_id, file): 

    return implementation.projects_project_id_work_unit_work_unit_id_work_unit_data_files_post(project_id, work_unit_id, file)
```

The value of req.view_args is:

`req.view_args = {'projectId': 200000, 'workUnitId': 1}`

`file` arg is missing even if provided

Environment:

- Python version: 3.8.5
- Flask version: 2.0.0

**Comment by davidism** [comment]
Please provide a minimal reproducible example. Otherwise, this sounds like something webtest will need to address.

**Comment by gbmarc1** [comment]
Seems that the error is in werkzeug. It is not a webtest error... Webtest hasn't change since Apr 27, 2020 it would have been surprising that the error was there. Flask, and werkzeug  just bumped their major version so it was surely somewhere there...

https://github.com/pallets/werkzeug/issues/2125
