### ISSUE TITLE
Flask 2.0.0 - breaking change with websocket

### ISSUE THREAD

**Issue by jcdevil** [pallets/flask#4035]
Hello, I noticed some breaking changes while using websocket protocol.
Unfortunately, quite hard to explain/analyse for me ATM.
Could be nice if somebody can help.

**Symptoms** :
Getting the error `BrokenPipeError: [Errno 32] Broken pipe` on the second message sent to the server.

**Environments**
Previous configuration - working fine :
```
python 3.9.4
Flask 1.1.2
Werkzeug 1.0.1
gevent 20.9.0
websocket-client 0.59.0
```

New configuration - failure described below :
```
python 3.9.4
Flask 2.0.0
Werkzeug 2.0.0
gevent 20.9.0
websocket-client 0.59.0
```

**How to reproduce the issue :**

launch this server script in a terminal
```
# -*- coding: utf-8 -*-
import sys

from flask import Flask, request
from gevent.pywsgi import WSGIServer
from geventwebsocket import WebSocketError
from geventwebsocket.handler import WebSocketHandler


class WebsocketServer(object):

    def __init__(self):
        super().__init__()
        self.app = None

    def echo(self):
        if request.environ.get('wsgi.websocket'):
            ws = request.environ['wsgi.websocket']
            while True:
                try:
                    message = ws.receive()
                    print(f'Received : {message}')
                    ws.send(message)
                except WebSocketError:
                    ws.close()
                    break
        return 'Done...'

    def start(self, port):
        http_server = WSGIServer(('0.0.0.0', port), self.app, handler_class=WebSocketHandler)
        http_server.serve_forever()

    def configure(self):
        self.app = Flask(__name__)
        self.app.debug = True
        self.app.add_url_rule('/echo', 'echo', self.echo)


if __name__ == '__main__':
    server = WebsocketServer()
    server.configure()
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 9000
    server.start(port)
```

then, on another terminal :

```
import websocket
ws = websocket.WebSocket()
ws.connect('ws://localhost:9000/echo')
ws.send('Hello !')
```
Then the `Hello !` message is no more printed on the console on which the server is launched (which is the case with the "working" configuration)
Moreover, when launching the same command another time :

```
ws.send('Hello !')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/lib/python3.9/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
  File "/path/to/lib/python3.9/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
  File "/path/to/lib/python3.9/site-packages/websocket/_core.py", line 512, in _send
    return send(self.sock, data)
  File "/path/to/lib/python3.9/site-packages/websocket/_socket.py", line 167, in send
    return _send()
  File "/path/to/lib/python3.9/site-packages/websocket/_socket.py", line 149, in _send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

Thx for your help.

**Comment by lacer93** [comment]
We're running into a similar issue, not the `Broken pipe` one but that is not the point. We are not using a lockfile (yes, our bad) but practically Flask<2.0.0 is unusable right now as Flask itself has no upper limit on its dependencies and will pull 2.0.0 Werkzeug and etc.

Old version's of Flask will never be useable again but could perhaps an 1.1.3 version be released where the dependencies are defined properly?

**Comment by miguelgrinberg** [comment]
I was unable to reproduce the broken pipe error, but the other problem is (I think) a mistake in your code, which older versions of Flask handled incorrectly. When you define your route, you have to tell Flask/Werkzeug that the route is going to handle WebSocket. 

Instead of this:

    self.app.add_url_rule('/echo', 'echo', self.echo)

Do this:

    self.app.add_url_rule('/echo', 'echo', self.echo, websocket=True)

**Comment by ThiefMaster** [comment]
@lacer93 wrong issue. (also, what stops you from explicitly installing `Werkzeug<2`?)

**Comment by jcdevil** [comment]
@miguelgrinberg 👍 : great news !!! your proposed update indeed fixes my problem.
Thx a lot !
