### ISSUE TITLE
Unused import statement in docs /quickstart/#variable-rules code block.

### ISSUE THREAD

**Issue by rafaVls** [pallets/flask#4054]
In the variable rules section of the quickstart docs, there's this code block: 

![before](https://user-images.githubusercontent.com/70592708/118275646-8f1dbd00-b47b-11eb-9701-17c246cccf1b.jpeg)

The escape import statement in this block is unused, and should be removed.

**Comment by ThiefMaster** [comment]
I think it should be used on `username` so the example doesn't allow XSS.

**Comment by rafaVls** [comment]
Can I get this assigned? I'd like to work on it.

**Comment by davidism** [comment]
Sure, go ahead, no need to ask first :-)
