### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by Yourun-proger** [pallets/flask#4065]
Hello. It all starts from [here](https://github.com/pallets/flask/blob/9039534eee6a87da98a1dee9e4338d1b73e861f8/src/flask/app.py#L2056). You can see that an exception is being handled. But why process it again? Why is this needed?

**Comment by ThiefMaster** [comment]
This is not the right place for this kind of questions; use our [discord channel](https://discord.gg/pallets) instead.
