### ISSUE TITLE
Ability to specify usage help text for blueprint

### ISSUE THREAD

**Issue by tomers** [pallets/flask#4067]
Example:
```py3
import click
from flask import Blueprint, Flask
app = Flask(__name__)
bp = Blueprint('twilio', __name__)

@bp.cli.command('session')
@click.argument('name')
def session(name):
    print(f"Creating session {name}")

app.register_blueprint(bp)

if __name__ == "__main__":
    app.run()
```

Execution:
```
❯ flask
Usage: flask [OPTIONS] COMMAND [ARGS]...

    ...

Commands:
  routes  Show the routes for the app.
  run     Run a development server.
  shell   Run a shell in the app context.
  twilio                                 <----------- CANNOT SET HELP TEXT HERE
```

It seems that there is no way to specify usage help text for a blueprint shown in CLI. This could be useful.

**Comment by davidism** [comment]
`bp.cli.help = ...`

**Comment by tomers** [comment]
That's a nice hack, which resolves the issue for me.
However, this doesn't seem to me as the most idiomatic way to do such thing, and it is definitely not documented anywhere.
I would suggest you consider adding `help` kwarg for this purpose.

**Comment by greyli** [comment]
Maybe we could reconsider #3609? Or add a tip in the docs for the `bp.cli.help` trick?
