### ISSUE TITLE
before_request function for parent does not trigger for child route & child route returns 404

### ISSUE THREAD

**Issue by Jonakemon** [pallets/flask#4068]
In this example, there are two routes: `/sample_parent` and `/sample_child`. The parent route is part of a parent blueprint; the child route is part of a child blueprint. The child blueprint is nested under the parent blueprint.

The expected behaviour is that both routes return a 403, because the parent blueprint has a before_request action that raises this.

The actual behaviour is that the parent route returns a 403, but the child route returns a 404.

The docs specifically state: `Blueprint-specific before request functions, etc. registered with the parent will trigger for the child.` [here](https://flask.palletsprojects.com/en/2.0.x/blueprints/#registering-blueprints)

It also confuses me that the route returns a 404 (not found) instead of a 200. I'd expect the route still to be found, but the before_request action not firing. This, however, could be related to [this issue](https://github.com/pallets/flask/issues/4037) which is already fixed in 2.0.1.

```python
from flask import Flask, Blueprint
from werkzeug.exceptions import Unauthorized

parent_bp = Blueprint("parent", __name__)
child_bp = Blueprint("child", __name__)


@parent_bp.before_request
def raise_error():
    raise Unauthorized


@parent_bp.route('/sample_parent', methods=['GET'])
def sample_parent():
    return 'ok', 200


@child_bp.route('/sample_child', methods=['GET'])
def sample_child():
    return 'ok', 200


def create_app(env=None):
    app = Flask(__name__)
    app.register_blueprint(parent_bp)
    return app


app = create_app()
app.run(port=5000, host="0.0.0.0")

```

When running `flask routes` I get:

```
Endpoint              Methods  Rule
--------------------  -------  -----------------------
parent.sample_parent  GET      /sample_parent
static                GET      /static/<path:filename>
```

Environment:

- Python version: 3.9
- Flask version: 2.0.0

**Comment by davidism** [comment]
Looks like you didn't do `parent_bp.register_blueprint(child_bp)`.

**Comment by Jonakemon** [comment]
Thanks! Even with the register_blueprint added, it still produces a 404 when a url_prefix is added. But that's something related to [this](https://github.com/pallets/flask/issues/4037) I guess.

**Comment by pgjones** [comment]
The 404 is expected as only a match to a route would result in the blueprint before_request triggering (partial matches, e.g. to the prefix don't trigger anything). If you want to match any route that has the parents prefix you can use the path url convertor as a catch all e.g. 
```python
@child_bp.route("/<path:path>")
def all_child():
    ...
```

**Comment by Jonakemon** [comment]
That is a great suggestion, thanks @pgjones!
