### ISSUE TITLE
Typing error with current_app when subclassing Flask

### ISSUE THREAD

**Issue by anagilda** [pallets/flask#4073]
### Outline of the issue

Typing error when subclassing Flask and getting the app with `current_app`.

According to the [docs](https://flask.palletsprojects.com/en/2.0.x/patterns/subclassing/):
> The Flask class is designed for subclassing.

But mypy doesn't seem to understand that `current_app` can return one subclass of `Flask`, and that these subclasses can have new arbitrary attributes, so it raises an error.

```bash
$ mypy src
src/cat.py:3: error: "Flask" has no attribute "meow"
```

### Reproducing the issue 

In the`src/cat.py` file:

```python
from Flask import current_app

meow = current_app.meow
```

The Flask subclass:

```python
from typing import Any

from flask import Flask
from flask_inflate import Inflate

class Cat(Flask):
    """
    Cat service implementation.
    """

    def __init__(self, import_name: str, meow: str,  *args: Any, **kwargs: Any) -> None:
        """
        Construct the object.
        """
        super().__init__(import_name, *args, **kwargs)

        self.meow = meow

        Inflate().init_app(self)
```

Run mypy in the console:

```bash
$ mypy src
```

### Expected behaviour

```bash
$ mypy src
Success: no issues found in 1 source file
```

### Environment:

- Python version: 3.8.0
- Flask version: 2.0.0
- mypy version: 0.812

**Comment by pgjones** [comment]
Yep, I think this is a tricky one to solve. Welcome suggestions as I haven't figured out a good solution yet.

**Comment by davidism** [comment]
There is nothing we can do about this, it is a shortcoming of typing. Typeshed did essentially the same thing, so this shouldn't be a new error if you've been using typing already.

**Comment by anagilda** [comment]
I was using typing before, but not typeshed, so this was a new error for me when moving from Flask `1.1.2` to Flask `2.0.0`.

I am not super happy about it, but I'm using this as a workaround to pass on CI/CD for now:

```python
from typing import TYPE_CHECKING

from flask import current_app as flask_current_app

if TYPE_CHECKING:
    from src import Cat

current_app: 'Cat' = flask_current_app  # type: ignore
meow = current_app.meow
```

I am using the type checking flag to avoid circular imports, but it might not be needed in all cases.

**Comment by davidism** [comment]
> I was using typing before, but not typeshed

That's impossible, if you're using typing you're always using typeshed implicitly. Why you weren't getting the error before I don't know.

Casting the global as your own type, then importing the global from your code from then on seems to be the only way around this.

@srittau any suggestions about this? Or should we ping another mypy dev?

**Comment by srittau** [comment]
One thing that could work (untested) is deriving `Flask` from `Any`. One example:

```python
from typing import Any

class X(Any):
    def foo(self, x: int) -> None: ...
    
x = X()
x.foo("")  # error: Argument 1 to "foo" of "X" has incompatible type "str"; expected "int"
x.bar(123)  # no error
```

Apart from that @anagilda's solution is the best, although I would suggest using a `cast`: `current_app = typing.cast('Cat', flask_current_app)`.

**Comment by srittau** [comment]
Or of course using something like this in Flask, where we get into quite hacky territory:

```python
class _AnyFlask(Flask, Any): ...

current_app: _AnyFlask = LocalProxy(_find_app)
```

**Comment by srittau** [comment]
> I'm still curious why the issue didn't happen with the typeshed types.

The typeshed stubs had this:

```python
class Flask(_PackageBoundObject):
    ...
    # These are not preset at runtime but we add them since monkeypatching this
    # class is quite common.
    def __setattr__(self, name: str, value: Any): ...
    def __getattr__(self, name: str): ...
```

But this has all the same problems as deriving from `Any`.
