### ISSUE TITLE
Flask 1.1.4 seems to depend on click < 8.0

### ISSUE THREAD

**Issue by mfmarche** [pallets/flask#4076]
Upgrading to flask 1.1.4, it will not allow click 8.0.0. Although the setup.py seems to suggest it should:

```
        "click >= 8.0",
```
https://github.com/pallets/flask/blob/main/setup.py#L10

Checking the installed 1.1.4 package and its metadata, I see this in the METADATA file:
```
Requires-Dist: click (<8.0,>=5.1)
```
(I'm not sure where this is generated from). 

I do see the tox.ini file have this follow line which could be the culprit?
https://github.com/pallets/flask/blob/main/tox.ini#L14

Note that flask 1.1.2 allows click 8.0.0.

Environment:

I'm using the poetry (pyproject) tool environment to install the package from https://pypi.org/project/Flask/.
- python version 3.8.5
- flask version (as outlined above)

**Comment by davidism** [comment]
That's correct, other people were having trouble pinning their dependencies and continually requested that we set max versions, until we did. You'll need to upgrade Flask to upgrade the other libraries.

**Comment by davidism** [comment]
You're looking at the dev setup.py, you need to select the correct branch for the version you want.

**Comment by mfmarche** [comment]
Thanks. My confusion was the difference in behavior between 1.1.2 and 1.1.4, but now I understand.
