### ISSUE TITLE
Pin asgiref dependency to less than v4

### ISSUE THREAD

**Issue by andrewgodwin** [pallets/flask#4079]
Flask currently depends on `asgiref>=3.2` as of Flask 2, but we may have to drop Python 3.6 support in `asgiref` eventually and would do a major version bump (to `4`) when this occurred. Is it worth incorporating this restriction in the version pin - either `asgiref~=3.2` or `asgiref>=3.2,<4` - so that when this happens, older releases of Flask are not broken?

**Comment by ThiefMaster** [comment]
As long as you use proper `python_requires` metadata (and publish the packages with an up to date version of twine that actually sends this metadata) this should not be necessary.

**Comment by andrewgodwin** [comment]
Ah, good point - that would probably solve this specific situation. I still think it would be wise to avoid a v4, since whatever would make us do it would be a massively breaking change, such as changing the signature of AsyncToSync or similar.

**Comment by davidism** [comment]
As a library (not an application), I'm very hesitant to add maximum version pins, as it seems easy to cause issues down the line where we say we don't support the version even though we do, so users can never upgrade.

**Comment by davidism** [comment]
As a library (not an application), I'm very hesitant to add maximum version pins, as it seems easy to cause issues down the line where we say we don't support the new version even though it didn't break anything, so users can never upgrade.

That said, if the maintainer is telling us to do it, I'm fine with it. :-) Presumably you wouldn't be able to make deprecation warnings first for this theoretical breaking change?

**Comment by andrewgodwin** [comment]
We probably would try to, for obvious reasons - and it turns out that Django does the same thing now, so I think I'll close this and we'll try to do it the Sensible Way, and not lock people's dependencies-of-dependencies too much.
