### ISSUE TITLE
config from_* methods should document their return type

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/flask#4082]
They do return *something*, but it's not obvious what it is, so having a `:return: whatever they return` in the docstring would be nice to have.

**Comment by starlightknown** [comment]
Can I get some info about how to get started with this issue? I would like to contribute

**Comment by greyli** [comment]
> Can I get some info about how to get started with this issue?

@starlightknown Basicially, you will need to find these `from_*` methods in `src/flask/config.py`, then add a `:return: REPLACE THIS WITH ACTUAL RETURN TYPE` statement in the docstring for each method ([example](https://github.com/pallets/flask/blob/main/src/flask/config.py#L86)).

**Comment by starlightknown** [comment]
Got it, can I get assigned to it or start working on it? @greyli

**Comment by davidism** [comment]
Yes, you're welcome to submit a pr, no need to ask.
