### ISSUE TITLE
Recent change to blueprint prevents Dynamic creation of Blueprints using __name__

### ISSUE THREAD

**Issue by schwab** [pallets/flask#4092]
We add flask blueprints to our project endpoint classes by using the `__name__ ` for dynamic binding.  All the endpoints now break because of the new Flask requirement ** 'name' may not contain a dot **.  This is problematic because it's much cleaner to use the __name__ property when creating a blueprint that spans many endpoint files in a consistent way with a simple function like... 

Environment:

- Python version:
- Flask version:

**Comment by ThiefMaster** [comment]
You can do `foo.__name__.replace('.', '__')` or some symbol that's not valid in a python identifier. With nested blueprints now using the `.` as a separator, we really can't support dots in function/blueprint names - just like a file/directory name cannot contain a `/`... the code needs to know what to split by (in a deterministic way).
