### ISSUE TITLE
Syntax error on flask import due to installation of dataclasses module (python2.7)

### ISSUE THREAD

**Issue by InlandTaipan** [pallets/flask#4107]
Howdy! I've been working a lot with Flask (1.1.2) recently and have been running into a bug when installing Flask on devices running python2.7. Flask installs Werkzeug>=2.0 as one of its dependencies, however past version 1.0.x, [Werkzeug only supports python3.6+](https://werkzeug.palletsprojects.com/en/2.0.x/installation/). As a result, Werkzeug installs the dataclasses module, which produces syntax errors when run in python2.7. To resolve this, Flask may have to downgrade the version of Werkzeug that it uses to one that offers python2.7 support (ex: 1.0.x)

For reference, here is where Flask expects an ImportError when trying to use dataclasses python < 3.7, but instead gets a SyntaxError because Werkzeug installs the dataclasses module.

https://github.com/pallets/flask/blob/7161776824734fc2797fe2b4fc974d183487ebf8/src/flask/json/__init__.py#L18-L22

### How to Replicate
Run `pip install flask>=1.1.2` on a device with python2.7

### Expected Behaviour
Should be able to install and import flask on devices running python2.7

Environment:

- Python version: 2.7.12
- Flask version: 1.1.12

**Comment by ThiefMaster** [comment]
Flask 1.1.4 pins `werkzeug<2`; use that version if you need older flask versions and/or python 2 compatibility.
