### ISSUE TITLE
Issue when base64 encoding session into cookie

### ISSUE THREAD

**Issue by fpereiro** [pallets/flask#4117]
Hi there! I stumbled across a bug that happens when setting a couple of session variables. When certain values are picked, the base64 encoding of the cookie is broken.

My Python version is 3.8.5. As for Flask, this happens on both 1.1.4 and 2.0.1

To replicate it, you can run the following Flask app:

```
from flask import Flask, request, jsonify, session

app = Flask(__name__)

app.config['SECRET_KEY'] = 'foobar'

@app.before_request
def before_request_proxy_testing():
    session ['session_id'] = 'id'
    session ['session-test'] = 'test'

@app.route('/', methods=['GET'])
def parse():
    return '', 200 

app.run(port=5000)
```

When you navigate to `localhost:5000`, a cookie will be set that is not properly encoded as base64. In my case I get `.eJyrVipOLS7OzM_TLUktLlGyUgJTOjDR-MwUoBiQqAUANscOVw.YLFEpg.mUktNdWRkgDnm0OWxbpoyOiY4kg`, which decoded yields `'x��V*N-.����-I-.Q�R\x02S:0���\x14�\x18��\x05\x006�\x0EW\x06\x0B\x14J`�I-5Ց�\x00�C�źh���H'` (tested on Chrome). On Firefox, I also get another invalid cookie.

Interestingly enough, Flask seems to recognize this cookie nonetheless, and if I were using sessions normally I would have never ever noticed this. But because I'm writing a reverse proxy that brings back info from a Flask instance, I need to base64 decode the cookie with the session and that's where I saw the issue.

I've dug into the code to see how sessions are encoded but haven't been able to figure out exactly how Flask does it. Using itsdangerous `encoding.base64_decode` also didn't do the trick.

Most of the time, depending on the value of the session, the cookie is encoded without any problems and I can extract the session by base64 decoding the cookie string.

Any pointers to relevant doc or code on how the session cookie can be decoded would be very appreciated.

Thank you for your time. Also thank you for having built Flask!

**Comment by ThiefMaster** [comment]
I can't reproduce this...

```
[adrian@claptrap:~]> http get http://localhost:5000/
HTTP/1.0 200 OK
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Fri, 28 May 2021 19:45:48 GMT
Server: Werkzeug/2.0.0 Python/3.9.2
Set-Cookie: session=.eJyrVipOLS7OzM_TLUktLlGyUgJTOjDR-MwUoBiQqAUANscOVw.YLFIbA.xUIdceTSuaHaoqyu7_NZPyy4iaE; HttpOnly; Path=/
Vary: Cookie
```

(flask/werkzeug 2.0.0)

**Comment by ThiefMaster** [comment]
Oh you are actually trying to base64-decode the whole string. Not sure where you read that this should be possible... itsdangerous use a custom format that includes the data and signature separately...

```
>>> import itsdangerous
>>> s = itsdangerous.URLSafeSerializer('')
>>> s.loads_unsafe('.eJyrVipOLS7OzM_TLUktLlGyUgJTOjDR-MwUoBiQqAUANscOVw.YLFIbA.xUIdceTSuaHaoqyu7_NZPyy4iaE')
(False, {'session-test': 'test', 'session_id': 'id'})
```

Check the code/docs of itsdangerous if you want to parse its data outside Python.

**Comment by fpereiro** [comment]
Hi @ThiefMaster -- thank you for the lightning-fast reply! I'll try then with `loads_unsafe` from itsdangerous then. Most of the time, base64 decoding worked well, except when it didn't.

Thanks for the help!

**Comment by fpereiro** [comment]
Good idea! We're not putting anything sensitive in the session and we trust the source and the connection, but you're right, it's definitely better to verify the signature. I'll do that instead. Thanks!
