### ISSUE TITLE
Various warnings when using Flask 2

### ISSUE THREAD

**Issue by RhinosF1** [pallets/flask#4118]
When running some tests using pytest for our project, I see various warnings:

`flask/json/__init__.py:31: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.`

`DeprecationWarning: 'jinja2.escape' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.escape' instead.`
(Note: I simply do from flask import escape)

Environment: GitHub Actions (ubuntu|macos)-latest

- Python version: 3.7-3.9
- Flask version: 2.0.1

**Comment by ThiefMaster** [comment]
My guess would be that you somewhere import escape from jinja2... as you can see [here](https://github.com/pallets/flask/blob/2.0.x/src/flask/__init__.py#L1), flask.escape is not coming from jinja.

**Comment by RhinosF1** [comment]
I checked my code and the only import of escape comes from

from flask import Flask, abort, escape, send_file

**Comment by RhinosF1** [comment]
I'm super blind, this project still runs flask 1

**Comment by vibaiher-qatium** [comment]
Hello!
Today I have seen same warnings. I have tested with Flask 1 and Flask 2.
This is the output:

```
/back # pytest -W error
ImportError while loading conftest '/back/tests/conftest.py'.
tests/conftest.py:4: in <module>
    from application import create_app
application/__init__.py:2: in <module>
    from flask import Flask
/usr/local/lib/python3.7/site-packages/flask/__init__.py:19: in <module>
    from . import json
/usr/local/lib/python3.7/site-packages/flask/json/__init__.py:31: in <module>
    _slash_escape = "\\/" not in _json.dumps("/")
/usr/local/lib/python3.7/site-packages/itsdangerous/_json.py:29: in __getattribute__
    stacklevel=2,
E   DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
```
