### ISSUE TITLE
en/2.0.x/tutorial/database "Error: No such command 'init-db'." fix

### ISSUE THREAD

**Issue by bryan-smith** [pallets/flask#4119]
https://flask.palletsprojects.com/en/2.0.x/tutorial/database/#id5

on the line

`from . import db`

That's not what is on the project github, and results in Error: No such command 'init-db'.

The line used on the github is

`from flaskr import db`

And that works, for some reason.

It doesn't seem to make any sense, but it took me like over an hour to find.

Environment:

- Python version: 3.9.5
- Flask version: 2.0.1

**Comment by davidism** [comment]
I can't reproduce this issue. I believe the imports are absolute instead of relative in the repo because of how we run the tests, but that shouldn't affect anything assuming you have followed the tutorial exactly. Are you sure you installed the project with `pip install -e .`?

You can use https://discord.gg/pallets to get help with your code.

**Comment by bryan-smith** [comment]
> I can't reproduce this issue. I believe the imports are absolute instead of relative in the repo because of how we run the tests, but that shouldn't affect anything assuming you have followed the tutorial exactly. Are you sure you installed the project with `pip install -e .`? I changed the imports to be relative to match the docs, installed it, and `export FLASK_APP=flaskr; flask init-db` worked as expected.
> 
> You can use https://discord.gg/pallets to get help with your code.
No, I was not installing the project with pip.  I was following the tutorial and making the file from scratch.


I would recommend keeping the GitHub repo absolute rather than relative. The way the docs page referenced the current folder with . because referring to the flaskr folder as the GitHub repo did worked for me.

I am new, so although I am sure I followed the tutorial exactly, but I am probably wrong in that.

**Comment by bryan-smith** [comment]
> I can't reproduce this issue. I believe the imports are absolute instead of relative in the repo because of how we run the tests, but that shouldn't affect anything assuming you have followed the tutorial exactly. Are you sure you installed the project with `pip install -e’ 

I did not install the project with pip, I followed the tutorial and built the files and folders from scratch following the described file structure.

when I have problems with something I check against what’s in the GitHub repo.

**Comment by davidism** [comment]
The tutorial instructs you to install the project as you start building it.
