### ISSUE TITLE
flask.Request.values is not combining GET and POST args in version 2.x

### ISSUE THREAD

**Issue by anetbnd** [pallets/flask#4123]
Hello

We have the following code currently working with flask 1.x:

```python
import flask
app = flask.Flask("Test")
with app.test_request_context(data={'code': '123'}):
       print(flask.request.values)
       print(flask.request.form)
       print(flask.request.args)
```

It delivers the following output:

```
CombinedMultiDict([ImmutableMultiDict([]), ImmutableMultiDict([('code', '123')])])
ImmutableMultiDict([('code', '123')])
ImmutableMultiDict([])
```

Which is inline with the documentation: 
https://flask.palletsprojects.com/en/2.0.x/api/?highlight=flask%20request%20values#flask.Request.values

Where it says that this property combines `args` and `form`.

However with flask 2.0.1 we get the following output:

```
CombinedMultiDict([ImmutableMultiDict([])])
ImmutableMultiDict([('code', '123')])
ImmutableMultiDict([])
```

Here obviously `args` and `form` has not been combined in the property `values`.

**Comment by ThiefMaster** [comment]
Is it a GET request by any chance? If yes, see #4120 and pallets/werkzeug#2037

**Comment by davidism** [comment]
When you create that request context, you're not specifiying the method, so it defaults to `GET`. Werkzeug no longer allows `values` to see `form` on GET requests to prevent issues with caching. Use `test_request_context(method="POST", ...)`, or use the test client to make POST requests.

**Comment by anetbnd** [comment]
Hello, 

please reopen this ticket again. This is clearly an error! 
The most recent documentation says:
"A werkzeug.datastructures.CombinedMultiDict that combines args and form."

As you can see from the output, the data is present is `args` and according to the documentation, the property `values` combines `args` and `from`. However this is obviously not the case anymore. Thus either the implantation of `values` is wrong or the documentation of `values`. 

Actually it does not matter, if the request was GET or POST. The only point which matters is: The data is in `args` but not in `values`. Furthermore: What is the point in having `values` if you are now anyway forced to check first if you are in a GET or POST request. Then you can access `args` and `from` directly and `values` is not needed anymore. 

On top of this: Changing the official interface in such a strong and application breaking way is something, which I don't consider as good practice. For those cases, you should have used deprecation warnings and a reasonable transition time. I would not be surprised if there are now many application out there, which are not working anymore, due to such a change. 

Best regards

**Comment by anetbnd** [comment]
Ok, I think there was a misunderstanding. It seems, that the problem is not using `values` for GET requests, but using the `data` argument in `test_request_context(...)` together with the GET method to transfer data.

Still the documentation of `values` is highly misleading: It should then be like this:
For GET requests it contains the values from `args` and for POST requests, it contains the combination of `args` and `form`.

And `test_request_context(...)` should raise an exception when `data` is used together with GET, since this seems to be an invalid usage according to the specs.

**Comment by pgjones** [comment]
I think the documentation for `values` is clear, why do you think it is misleading? Note that it is only `GET` requests where `values` is just `args`.

> And test_request_context(...) should raise an exception when data is used together with GET, since this seems to be an invalid usage according to the specs.

This isn't an invalid usage, it is rare in practice though. You can access the GET data (if specified) via the `form` property, but not via `values`.

**Comment by anetbnd** [comment]
The documentation says:
"A werkzeug.datastructures.CombinedMultiDict that combines args and form.

For GET requests, only args are present, not form."

Both sentences are incorrect. First of all, for GET requests the property is not combining `args` and `form`. Just for POST requests. And second for GET requests `form` is still present (as you can see in the minimal example from above) in addition to `args`. The only change in Flask 2.x is, that `values` is not combining `args` and `form` for GET requests anymore.

And if using `form` for GET requests is a valid use-case, then there is no reason to make the life of programmers more complicated, by not combining it anymore within the `values` property. The standard use-case for `values` is that you don't care about the source of data and probably even not about the type of request. And exactly this use-case is not possible anymore.
