### ISSUE TITLE
Unexpected behavior when deploying Flask as Azure WebApp after Flask 2.x release

### ISSUE THREAD

**Issue by eedokl** [pallets/flask#4128]
We deploy a Dash Dashboard as Azure WebApp with mounting blob storage. where Dash pulls the latest Flask version.

This works fine but starting mid of May we faced the problem that we noticed a high number (like 10k...10M) of ListBlob Transactions were happening increasing our storage cost.

We did not find the exact root cause, but we found that the problem starts when we recreated our Docker container mid of May which then pulled Flask 2.0.1 instead of Flask 1.1.x.

We further found that the root cause may not only be Flask itself but its dependencies.
E.g. all works fine with Flask 1.1.4 which install requires defines upper limits for its required packages:
install_requires=[ "Werkzeug >= 0.15, <2.0", "Jinja2 >= 2.10.1, <3.0", "itsdangerous >= 0.24, < 2.0", "click >= 5.1, < 8.0", ]
But things break today (End of May 2021) with Flask 1.1.2 which setup.py defines no upper limits of its required packages:
install_requires=[ "Werkzeug>=0.15", "Jinja2>=2.10.1", "itsdangerous>=0.24", "click>=5.1", ]
However, Flask 1.1.2 was working for us beginning of May 2021, but in mid of May there were major version updates on Werkzeug, Jinja and Click.
We were not deep diving further on this.

This ticket I anyway put here to inform the community, eventually get feedback from others and to raise the question how Flask may handle such eventual issues with major updates on its required packages, or if Flask 2 may need similar upper bounds on some of its used packages like version 1.1.4

Problem setup:
Brotli 1.0.9
click 8.0.1
dash 1.20.0
dash-bootstrap-components 0.12.2
dash-core-components 1.16.0
dash-html-components 1.1.3
dash-renderer 1.9.1
dash-table 4.11.3
Flask 2.0.1
Flask-Compress 1.9.0
future 0.18.2
importlib-metadata 4.3.1
itsdangerous 2.0.1
Jinja2 3.0.1
llvmlite 0.36.0
MarkupSafe 2.0.1
numba 0.53.1
numpy 1.20.3
pandas 1.2.4
pip 21.1.2
plotly 4.14.3
pyarrow 2.0.0
python-dateutil 2.8.1
pytz 2021.1
retrying 1.3.3
scipy 1.6.3
setuptools 57.0.0
six 1.16.0
typing-extensions 3.10.0.0
Werkzeug 2.0.1
wheel 0.36.2
zipp 3.4.1

Working setup:
Package Version

Brotli 1.0.9
bst-dashboards 0.1.1rc6flask112plus
click 7.1.2
dash 1.20.0
dash-bootstrap-components 0.12.2
dash-core-components 1.16.0
dash-html-components 1.1.3
dash-renderer 1.9.1
dash-table 4.11.3
Flask 1.1.2
Flask-Compress 1.9.0
future 0.18.2
itsdangerous 1.1.0
Jinja2 2.11.3
MarkupSafe 1.1.1
numpy 1.20.3
pandas 1.2.4
pip 21.1.2
plotly 4.14.3
pyarrow 2.0.0
python-dateutil 2.8.1
pytz 2021.1
retrying 1.3.3
setuptools 57.0.0
six 1.16.0
Werkzeug 1.0.1
wheel 0.36.2

Environment: Linux, Ubuntu

- Python version: 3.7
- Flask version: 2.x

**Comment by davidism** [comment]
Sorry, based on the information given there's nothing we can help with.
