### ISSUE TITLE
KeyError: None in do_teardown_request

### ISSUE THREAD

**Issue by Zlopez** [pallets/flask#4138]
Hi,

I have a PR hanging on the failing tests with update to Flask 2.0.1 [https://github.com/fedora-infra/anitya/pull/1110], I looked at the failing tests and they are failing on `do_teardown_request`, more specifically on [this line](https://github.com/pallets/flask/blob/aac67289e517bda4ef488819edab74539ef8e9b9/src/flask/app.py#L1918). I noticed that there is `self.teardown_request_funcs[None]` on the line and this must fail each time on `KeyError`.

Here is the whole traceback of the issue:
```
.tox/py36/lib/python3.6/site-packages/werkzeug/test.py:1132: in post
    return self.open(*args, **kw)
.tox/py36/lib/python3.6/site-packages/flask/testing.py:220: in open
    follow_redirects=follow_redirects,
.tox/py36/lib/python3.6/site-packages/werkzeug/test.py:1072: in open
    response = self.run_wsgi_app(request.environ, buffered=buffered)
.tox/py36/lib/python3.6/site-packages/werkzeug/test.py:943: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
.tox/py36/lib/python3.6/site-packages/werkzeug/test.py:1229: in run_wsgi_app
    app_rv = app(environ, start_response)
.tox/py36/lib/python3.6/site-packages/flask/app.py:2088: in __call__
    return self.wsgi_app(environ, start_response)
.tox/py36/lib/python3.6/site-packages/flask/app.py:2073: in wsgi_app
    response = self.handle_exception(e)
.tox/py36/lib/python3.6/site-packages/flask/app.py:2069: in wsgi_app
    ctx.push()
.tox/py36/lib/python3.6/site-packages/flask/ctx.py:384: in push
    top.pop(top._preserved_exc)
.tox/py36/lib/python3.6/site-packages/flask/ctx.py:431: in pop
    self.app.do_teardown_request(exc)
.tox/py36/lib/python3.6/site-packages/flask/app.py:1915: KeyError
```

Environment:

- Python version: 3.6, 3.7, 3.9
- Flask version: 2.0.1

**Comment by davidism** [comment]
I can't reproduce this issue. `teardown_request_funcs` is a default dict, so accessing a key that hasn't been used yet returns an empty list:

```pycon
>>> app.teardown_request_funcs[None]
[]
```

**Comment by Zlopez** [comment]
@davidism Thanks. In this case, this must be somewhere in my code :-/

**Comment by Zlopez** [comment]
I found out, that in the setup phase of the tests there was line that changed the `teardown_request_funcs` to `{}`. So the fix was to just change it to `{ None: [] }`.
