### ISSUE TITLE
flask 2.0.1 调试bug

### ISSUE THREAD

**Issue by main1015** [pallets/flask#4140]
Environment:

- Python version:  3.6.9
- Flask version: 2.0.1

测试代码：
```python
from flask import Flask, request

app = Flask(__name__)

@app.route("/")
def index():
    b = request.remote_addr
    a = 1 / 0
    return "ok: %s" % b

if __name__ == "__main__":
    app.run("0.0.0.0", port=23456, debug=True)`
```

运行后
![image](https://user-images.githubusercontent.com/3272281/121147304-55ba5080-c873-11eb-9231-5f3fe5245d36.png)
输入b变量
![image](https://user-images.githubusercontent.com/3272281/121147503-7f737780-c873-11eb-917f-24a813260806.png)
我没有看懂这是什么情况

**Comment by collinzrj** [comment]
`a = 1 / 0`
You produce a ZeroDivisionError in python

**Comment by main1015** [comment]
问题我已经找到了
是在调用调试模式的时候，输入pin时，response会设置一个cookie，但是这个时候cookie未设置成功
![image](https://user-images.githubusercontent.com/3272281/121156381-36272600-c87b-11eb-9427-28035ede098b.png)

![image](https://user-images.githubusercontent.com/3272281/121156467-4b03b980-c87b-11eb-8f25-69c35de39d3b.png)

**Comment by davidism** [comment]
See https://github.com/pallets/werkzeug/issues/2156

**Comment by main1015** [comment]
> See [pallets/werkzeug#2156](https://github.com/pallets/werkzeug/issues/2156)

Finally I used the source coverage approach to solve this

`
def patch_werkzeug_response(is_https=False):

    wv = Version(werkzeug.__version__)

    lv = Version('2.0.0')
    if wv >= lv:

        Response = werkzeug.wrappers.response.Response
        osc = Response.set_cookie
        import typing as t
        from datetime import timedelta, datetime

        def set_cookie(
                self,
                key: str,
                value: str = "",
                max_age: t.Optional[t.Union[timedelta, int]] = None,
                expires: t.Optional[t.Union[str, datetime, int, float]] = None,
                path: t.Optional[str] = "/",
                domain: t.Optional[str] = None,
                secure: bool = False,
                httponly: bool = False,
                samesite: t.Optional[str] = None,
        ) -> None:
            if samesite == 'None' and not secure:

                if is_https:
                    # samesite = None
                    secure = True
                else:
                    samesite = None
            osc(self, key, value, max_age, expires, path, domain, secure, httponly, samesite)

        Response.set_cookie = set_cookie

#  Call this function before the app.run 
patch_werkzeug_response()
`
