### ISSUE TITLE
Directly add Short Responses

### ISSUE THREAD

**Issue by donno2048** [pallets/flask#4141]
Instead of using the decorator which is confusing to newcomers and is a bit too long to just do simple responses like:

```py
@app.route("/style.css")
def style():
    return Response("body { background-color: red; }")
```
For simple responses it should be simple and pythonic to use something like:

```py
app.add_response("/style.css", "body { background-color: red; }")
```

I don't think it should be too hard to implement (I can actually do it myself).

**Comment by ThiefMaster** [comment]
You should not serve static content like this - the `static` folder exists for a reason.
