### ISSUE TITLE
Support of HTTP/2 cleartext (h2c) format in flask

### ISSUE THREAD

**Issue by mejuhi** [pallets/flask#4143]
From documentation it feels like flask does not support h2c (i.e. HTTP/2 in the clear, no encryption). 

I have a use cases where an L7 proxy (e.g. Envoy) is actually managing certificates and encrypted connections across the network, and the connection between the service and the proxy is just host-local. In this case, we want to achieve h2c between the proxy and the service (flask application).

Is there any way through which we can enable h2c via configuration in the flask application?
and if it is not supported now, is there any roadmap for it?

**Comment by ThiefMaster** [comment]
That should be handled on the webserver level...

**Comment by mejuhi** [comment]
which webserver would you suggest for easy integration of h2c and flask?

**Comment by ThiefMaster** [comment]
nginx and apache are the most common ones. you can then run flask behind it using e.g. uwsgi or gunicorn.

**Comment by pgjones** [comment]
You can also use Hypercorn and asgiref's WsgiToAsgi adapter.

**Comment by mejuhi** [comment]
Yes, since i was not able to find any sample/examples to do h2c with flask, started out with migration from flask to quart using following [docs](https://pgjones.gitlab.io/quart/how_to_guides/flask_migration.html) and then stumbled upon the following [docs](https://pgjones.gitlab.io/quart/tutorials/deployment.html) which suggests to use hypercorn with quart for prod deployments

Thankyou for suggestion! :)
