### ISSUE TITLE
In version 2.0, all IP addresses are not allowed.

### ISSUE THREAD

**Issue by youngkiu** [pallets/flask#4144]
Environment:
OS : Windows 10 Home

- Python version: Python 3.8.10 on Anaconda
- Flask version: 2.0.1

```
$ pip install Flask==1.1.4
$ flask run --host=0.0.0.0
 * Serving Flask app "app.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

```
$ pip install Flask==2.0.1
$ flask run --host=0.0.0.0
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://10.110.29.36:5000/ (Press CTRL+C to quit)
```

In fact, it is run in docker, and as above, it is set as the private IP address(http://172.17.0.2:5000/) of the docker container.

**Comment by davidism** [comment]
From the output:

>  `* Running on all addresses.`

See https://github.com/pallets/werkzeug/pull/2010, which changed the "running on" message to always show a valid address.

**Comment by youngkiu** [comment]
@davidism 
Even if the displayed message is like that, I can't actually connect from another IP.

**Comment by davidism** [comment]
I can't reproduce that issue. Sounds like there's something wrong with your Docker setup.
