### ISSUE TITLE
How to restrict malicious IP access?

### ISSUE THREAD

**Issue by littledotdot** [pallets/flask#4145]
101.133.136.80 - - [10/Jun/2021 18:15:00] 
code 400, message Bad request syntax 
("\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x10\x94b\x19m\x8bSÖ[õ>\r\x8bÁá|°Ç\x93\x05Ñ\x8búF\x0b¶Ût¶PQ£ 7C8\x01ó\x19ÒT©\x1c\x1bâÎN2Æ´\x1b½ô&'\t4\x92ÏùÙ\x91æ¾L\x00>\x13\x02\x13\x03\x13\x01À,À0\x00\x9fÌ©Ì¨ÌªÀ+À/\x00\x9eÀ$À(\x00kÀ#À'\x00gÀ")
Áá|°ÇÑúF136.80 - - [10/Jun/2021 18:15:00] "übmSÖ[õ>
        ¶Ût¶PQ£ 7C8óÒT©2Æ´	ÏùÙæ¾L>À,À0Ì©Ì¨ÌªÀ+À/À$À(kÀ#À'gÀ" HTTPStatus.BAD_REQUEST -
Xshell101.133.136.80 - - [10/Jun/2021 18:15:00] "GET / HTTP/1.1" 404 -
101.133.131.45 - - [10/Jun/2021 18:17:38] code 400, message Bad request syntax 
("\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x88cÑ?;\x8a6\x0czÿf\x01©=\x9c¡ö\x06\x84Wñ\x1c\x0f=ZÀÂ¯{=àå }3fäG5,\x8d$ý\x8c\x88!'³\x83¶ý\x99\x10Mó\x195\x9eLÏ\x842ñâ{\x00>\x13\x02\x13\x03\x13\x01À,À0\x00\x9fÌ©Ì¨ÌªÀ+À/\x00\x9eÀ$À(\x00kÀ#À'\x00gÀ")
101.133.131.45 - - [10/Jun/2021 18:17:38] "ücÑ?;6
                                                 zÿf©=¡öWñ=ZÀÂ¯{=àå }3fäG5,$ý!'³¶ýMó5LÏ2ñâ{>À,À0Ì©Ì¨ÌªÀ+À/À$À(kÀ#À'gÀ" HTTPStatus.BAD_REQUEST -
101.133.131.45 - - [10/Jun/2021 18:17:38] "GET / HTTP/1.1" 404 -
89.248.165.10 - - [10/Jun/2021 18:19:27] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
89.248.165.10 - - [10/Jun/2021 18:19:27] "/*àCookie: mstshash=Administr" HTTPStatus.BAD_REQUEST -

39.103.152.13 - - [11/Jun/2021 10:06:33] code 400, message Bad request syntax ('HELP')
39.103.152.13 - - [11/Jun/2021 10:06:33] "HELP" HTTPStatus.BAD_REQUEST -
39.103.152.13 - - [11/Jun/2021 10:06:36] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
39.103.152.13 - - [11/Jun/2021 10:06:36] "" HTTPStatus.BAD_REQUEST -
39.103.152.13 - - [11/Jun/2021 10:06:44] code 400, message Bad request syntax ('\x04\x01\x00\x16\x7f\x00\x00\x01root\x00')
39.103.152.13 - - [11/Jun/2021 10:06:44] root" HTTPStatus.BAD_REQUEST -
39.103.152.13 - - [11/Jun/2021 10:06:50] code 400, message Bad request syntax ('666')
39.103.152.13 - - [11/Jun/2021 10:06:50] "666" HTTPStatus.BAD_REQUEST -
39.103.152.13 - - [11/Jun/2021 10:06:57] code 400, message Bad request syntax ('vp3')
39.103.152.13 - - [11/Jun/2021 10:06:57] "vp3" HTTPStatus.BAD_REQUEST -

**Comment by littledotdot** [comment]
What is the reason for the large number of such logs?How can I prevent his malicious access?

**Comment by davidism** [comment]
This isn't related to Flask. Use a firewall or other service to prevent unwanted traffic.
