### ISSUE TITLE
Request being parsed before handler runs?

### ISSUE THREAD

**Issue by Joshuao95** [pallets/flask#4146]
Hi,
In my application I'm taking a file upload from a user, which may be very large (GBs).

I'd like to do some operations before finally iterating over the request body in chunks (and writing to a file), however as far as I can tell the function I decorate with the endpoint does not seem to run until the upload is complete.
This seems counter to what I expect, given a lot of discourse online about streaming request data (what's there to stream if it's already been taken in/saved?).

Am I missing something, or does Flask (or the underlying werkzeug) always parse/read the data before running the function?

My request looks like this (in cURL format), I've included all headers there, however I'm fairly sure most are irrelevant

    curl 'https://mysite.com/api/v1/upload?filename=blah\
      -H 'authority: mysite.com' \
      -H 'pragma: no-cache' \
      -H 'cache-control: no-cache' \
      -H 'accept: application/json' \
      -H 'x-requested-with: XMLHttpRequest' \
      -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.105 Safari/537.36' \
      -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary3xjJcHpMfz6sMB8p' \
      -H 'dnt: 1' \
      -H 'accept-language: en-US,en;q=0.9' \
      -H 'origin: https://mysite.com \
      -H 'sec-fetch-site: same-origin' \
      -H 'sec-fetch-mode: cors' \
      -H 'sec-fetch-dest: empty' \
      -H 'referer: https://mysite.com/' \
      -H 'cookie: session=eyJwcm9qZWN0LWlkIjoielVyTDl0Y3NKZGcyIn0.YMOC2w.Y1lZvTSczWPy6HAaNaZtAGz44LU' \
      --data-raw $'------WebKitFormBoundary3xjJcHpMfz6sMB8p\r\nContent-Disposition: form-data; name="file"; filename="blah"\r\nContent-Type: application/pdf\r\n\r\n\r\n------WebKitFormBoundary3xjJcHpMfz6sMB8p--\r\n' \

And here's the simple test application I'm using

```python
@app.route('/', methods = ["POST"])
def hello_world2():
    print(f"test2 start {time_ns()}")

    with open("/tmp/fileoutput", "bw") as f:
        chunk_size = 4096

        while True:
            chunk = request.stream.read(chunk_size)

            if len(chunk) == 0:
                print(f"test2 end: {time_ns()}")
                break
    
            f.write(chunk)

    return ''
```

In such a case, I notice the inital print does not happen for a long time, where the length of time is dependant on the size of the file uploaded, so I assume it's reading it in some way.

Thanks

**Comment by davidism** [comment]
I can't reproduce this issue. "start" is printed immediately, and "end" is printed after writing out the stream. I tried with a 1.2GB body. Flask and the Werkzeug dev server do not buffer the input stream before handling the request.

**Comment by Joshuao95** [comment]
Apologies, you were indeed correct.

If anyone ever finds this in the future, the issue was that I had Flask behind Nginx, which buffers requests.

The solution is to disable [proxy_request_buffering](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering)

**Comment by davidism** [comment]
For others, that option exists for a reason, and some WSGI servers such as Waitress also have that behavior. Evaluate your project's needs before enabling or disabling the option.
