### ISSUE TITLE
Class based views class attributes persist between requests

### ISSUE THREAD

**Issue by Andrew-Chen-Wang-LeaseMagnets** [pallets/flask#4148]
Using a class based view (specifically a MethodView), if you were to save something like a list, dict, or set, as a class attribute, this would persist through different requests.

To reproduce the bug:

```python
class MyView(MethodView):
    a_list = []
    a_dict = dict()
    a_set = set()

    def get(self):
        print(self.a_list, flush=True)
        self.a_list.append(len(self.a_list))
        print(self.a_dict, flush=True)
        self.a_dict[len(self.a_dict.keys())] = len(self.a_dict.keys())
        print(self.a_set, flush=True)
        self.a_set.add(len(self.a_set))
        return ""
```

If you hit this endpoint, the first time, the list, dict, and set is printed as empty. Then if you hit the same endpoint, the three vars now show the previous requests variables. Keep hitting the endpoint and the list, dict, and set will continue growing without ever refreshing.

Environment:

- Python version: 3.8.10
- Flask version: 1.1.2

**Comment by ThiefMaster** [comment]
I think the answer here is "don't do that". If you define mutable class level attributes, you should know how they behave.

**Comment by Andrew-Chen-Wang-LeaseMagnets** [comment]
@ThiefMaster ah I thought these classes are destroyed in memory and brought back up upon a new request. In that case, if I were to use a `cached_property` from werkzeug, then the data persists as well?

**Comment by ThiefMaster** [comment]
No, those are stored on the instance, and there's a new instance for each request.

**Comment by Andrew-Chen-Wang-LeaseMagnets** [comment]
Got it. Thank you!
