### ISSUE TITLE
Type of routing_exception seems too broad

### ISSUE THREAD

**Issue by kasium** [pallets/flask#4154]
The type of `flask.request.routing_exception` seems to be too broad. What I can see in your code is, that this field is only se in the case of a `werkzeug.exceptions.HTTPException`.
Therefore the type of `flask.request.routing_exception` is `Optional[Exception]` but could be `Optional[HTTPException]`

Environment:

- Python version: 3.7.1
- Flask version: 2.0.1

**Comment by davidism** [comment]
Other exceptions could be raised. Current annotation seems fine.
