### ISSUE TITLE
from flask.compat import text type modulenotfounderror no module named 'flask._compat' error in version 2.0.1

### ISSUE THREAD

**Issue by RobertLos** [pallets/flask#4159]
When upgrading to Flask 2.0.1 starting ther application leads to the error 
from flask.compat import text type modulenotfound: error no module named 'flask._compat'

this can be resolved by changing in __init__.py line 15
from flask._compat import text_type  to
from flask_script._compat import text_type

**Comment by ThiefMaster** [comment]
you need to remove this import. python 3 no longer needs this, use `str` instead of `text_type`.

and fyi, flask-script is dead. use Flask's built-in cli.

**Comment by RobertLos** [comment]
Thanks for the feedback. The effected code is in the flask module you 
import with pip install so I cannot change it myself.

greetings


Robert Los


Robert Los Commercial and Contract Services B.V.
Nachtegaallaan 46
3055 CS Rotterdam
The Netherlands
M:+31 6 24893872
E: ***@***.*** ***@***.***>
www.robertlos.nl <http://www.robertlos.nl>

**Comment by ThiefMaster** [comment]
maybe post a traceback?

**Comment by RobertLos** [comment]
Traceback (most recent call last):
  File "/home/robert/PycharmProjects/huisadmin/manage.py", line 3, in <module>
    from flask_script import Manager, Shell
  File "/home/robert/venvs/huisadmin_f2/lib/python3.9/site-packages/flask_script/__init__.py", line 15, in <module>
    from flask._compat import text_type
ModuleNotFoundError: No module named 'flask._compat'

requirements.txt: 
alembic
aniso8601
astroid
atomicwrites
attrs
Babel
blinker
click
dataclasses
decorator
dominate
Flask
Flask-Babel
Flask-Bootstrap
Flask-Bootstrap4
Flask-Fixtures
Flask-HTTPAuth
Flask-Login
Flask-Mail
Flask-Migrate
Flask-Moment
flask-restful
Flask-Script
Flask-Scss
Flask-SocketIO
Flask-SQLAlchemy
Flask-WTF
Flask-cors
Flask-EmailVerifier
...

**Comment by ThiefMaster** [comment]
Check the traceback again... `flask_script` is not flask itself, but a (dead - [repo archived](https://github.com/smurfix/flask-script)) flask extension written by someone else.

**Comment by RobertLos** [comment]
Thanks for the tip.

I see multiple remarks about this issue on the internet and the solution is clearly laid out by Miguel Grinberg on his post [https://blog.miguelgrinberg.com/post/migrating-from-flask-script-to-the-new-flask-cli](https://blog.miguelgrinberg.com/post/migrating-from-flask-script-to-the-new-flask-cli).

cheers
Robert
