### ISSUE TITLE
Large File Uploading Issue with RAM (x/post to Werkzeug)

### ISSUE THREAD

**Issue by RHQ-Rusty** [pallets/flask#4162]
Writing this as an open-ended discussion and will be submitting the same information to the respective packages involved in this issue. Please note that this issue has been raised *several times* before, but has yet to be fixed / resolved. ([Flask #2086](https://github.com/pallets/flask/issues/2086), [Werkzeug #1041](https://github.com/pallets/werkzeug/issues/1041), [Werkzeug #510](https://github.com/pallets/werkzeug/issues/510), [Codalab-Worksheet #301](https://github.com/codalab/codalab-worksheets/issues/301), see also: [StackOverflow Question](https://stackoverflow.com/questions/28321690/python3-flask-upload-file-in-server-memory))

Currently, the [`default_stream_factory` ](https://github.com/pallets/werkzeug/blob/eff04478a83619b4d7f15e6eee16a99bd80ed879/src/werkzeug/formparser.py#L60) that is embedded in [Werkzeug](https://github.com/pallets/werkzeug) (a [Flask](https://github.com/pallets/flask) Dependency) splits files and performs one of two operations:

- If under 500kb, store the uploaded file in-memory.
- If over 500kb, store the file in a temp file in /tmp.

This creates one main *visible* problem:

- Machines with a smaller /tmp may send a traceback to the user with a "No Space on Device" OSError, not allowing uploads to complete.

And one *hidden* problem:

- Large File Uploads (>500kb as defined in [`default_stream_factory`](https://github.com/pallets/werkzeug/blob/eff04478a83619b4d7f15e6eee16a99bd80ed879/src/werkzeug/formparser.py#L66)) *still* eat into the RAM of the host machine, despite being sent to /tmp via [`TemporaryFile`](https://github.com/pallets/werkzeug/blob/eff04478a83619b4d7f15e6eee16a99bd80ed879/src/werkzeug/formparser.py#L71) or [`SpooledTemporaryFile`](https://github.com/pallets/werkzeug/blob/eff04478a83619b4d7f15e6eee16a99bd80ed879/src/werkzeug/formparser.py#L69).

This redundancy can lead to a severe issue.
I was testing NS on a 4GB machine and performing a 4GB upload, which crashed the machine, and led me do two things:

- Up my /tmp size to 10GB in `/etc/fstab`
- Investigate the Memory Leak

I've not found a fix for this or any surefire way of counteracting the problem. Despite ensuring that /tmp has more than enough storage, RAM is still consumed. If the upload eats the RAM to 100% a system crash will occur, throwing the server offline. Somewhere in the reading I've been doing it's been suggested that Werkzeug stores the files into memory regardless of size (rendering `formparser` useless?) and has sloppy management with the data.

I have confirmed that this is reproducible by uninstalling and reinstalling both Flask and Werkzeug and trying it on multiple machines.

The intended behavior (storing in /tmp and not RAM) isn't happening.

Environment:

- Python Version: 3.9.5
- Flask Version: 2.0.1

Any possible fixes or monkey patches would be appreciated; collaboration and discussion is welcome!

**Comment by davidism** [comment]
Closing as this isn't a Flask issue.
