### ISSUE TITLE
Unable to store encrypted server-side sessions in Flask

### ISSUE THREAD

**Issue by irshad-io** [pallets/flask#4166]
The issue I am facing is that ```Werkzeug 1.0.0``` has removed deprecated code, including all of  ```Werkzeug.contrib``` so when I use flask-sessions I get

```
from werkzeug.contrib.cache import FileSystemCache
ModuleNotFoundError: No module named 'werkzeug.contrib'
```
So the solution suggested is to downgrade the ```werkzeug to 0.16.0``` which I did. But now the issue is
```
cannot import name 'ContextVar' from 'werkzeug.local'
```
For which the solution provided is to upgrade werkzeug to 2.0 or above.

What should I do to fix the flask-Sessions? How can I store session securely? 

I saw some alternatives to import ``` from cachelib import FileSystemCache ``` instead of ``` from werkzeug.contrib.cache import FileSystemCache``` in ```sessions.py``` but the issue is it doesn't encrypt the session files.

How can I fix this issue?

Also there is an issue with flask sessions that the sessions are not cleared when the browser is closed I have specifically given ```app.config["SESSION_PERMANENT"] = False``` at the beginning.

Environment:

- Python version: 3.9.5
- Flask version: 2.0.1
- Werkzeug version: 2.0.2

**Comment by ThiefMaster** [comment]
I would start by not using a library for security-related features such as sessions that appears to be unmaintained (last commit over a year ago).

You could then just implement your own flask session interface using your preferred storage backend.

**Comment by irshad-io** [comment]
Can you please explain a bit? What should I use instead of flask-sessions?

**Comment by ThiefMaster** [comment]
I don't know if there's a maintained alternative. I'm suggesting you write your own. Flask extensions are just to make things easier. If there's is no (up to date / maintained / working) extension for something, you simply have to write it yourself: https://flask.palletsprojects.com/en/2.0.x/api/#session-interface

Or alternatively fork and fix the extension...
