### ISSUE TITLE
Mypy issue if assigning to AppContext or Flask

### ISSUE THREAD

**Issue by kasium** [pallets/flask#4167]
In my application it's needed to store some data globally. In Flask 1.x I assigned them to the flask object which worked fine. However, the typing information in Flask 2 seems to not support this anymore.

```python
import flask

app = flask.Flask(__name__)
app.foo = 2

with app.app_context() as ctx:
    flask.current_app.foo = 2
    ctx.foo = 2
```

```shell
$ mypy repr.py 
repr.py:4:1: error: "Flask" has no attribute "foo"  [attr-defined]
    app.foo = 2
    ^
repr.py:7:5: error: "Flask" has no attribute "foo"  [attr-defined]
        flask.current_app.foo = 2
        ^
repr.py:8:5: error: "AppContext" has no attribute "foo"  [attr-defined]
        ctx.foo = 2
```

**Expected**:
Mypy should not show an error. This issue doesn't occur with the stub files of Flask 1.x in the typeshed package.

Environment:

- Python version: 3.7.1
- Flask version: 2.0.1

**Comment by ThiefMaster** [comment]
Use the `flask.g` object for request-scoped data. Actual globals are not related to flask and should just be normal globals, so I don't see any reason why we should change the typing to allow storing arbitrary attributes on either of the objects in your example...
