### ISSUE TITLE
flash method type signature not quite correct

### ISSUE THREAD

**Issue by jwag956** [pallets/flask#4168]
The signature for helper.flash:
def flash(message: str, category: str = "message") -> None:

Should have category typed as 't.Optional[str]' since it has a default.

Environment:

- Python version:3.9
- Flask version:2.0.1

**Comment by davidism** [comment]
Having a default is different than being optional. Optional means it can be None.

**Comment by jwag956** [comment]
Yup - sorry - python typing newbie....
