### ISSUE TITLE
Unable to set session SESSION_COOKIE_PATH individually

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [pallets/flask#4171]
Description:
The save_session method https://github.com/pallets/flask/blob/aac67289e517bda4ef488819edab74539ef8e9b9/tests/test_session_interface.py#L12
uses the `get_cookie_path(app)` always, i.e. the user can only set one SESSION_COOKIE_PATH in the `app.config`
and is unable to create a path for each session individually.

This is particularly an issue for non binary properties of a cookie such as SESSION_COOKIE_PATH. For such props as httponly and secure a central configuration seems to be ok.

Reproduce:
Try to set an individual path for each session. Impossible.

Expected behavior:

session.session_cookie_path or session.path should alter the sessions path

Environment:

- Python version: 3.9.5
- Flask version: 2.0.1

**Comment by ThiefMaster** [comment]
Uh, why would you want to use different paths for different sessions? There is only one session, and it sounds like you are trying to mix different applications within the same one... The whole reason for this property is that if your app is deployed e.g. in `/foo`, you can limit the session cookies to that subpath.

**Comment by F-Node-Karlsruhe** [comment]
I'm trying to get an individual expiration for each path. Therefore I aimed to create a session for each path as well.
Maybe this is not the way to go?

**Comment by ThiefMaster** [comment]
Doesn't sound like a typical usecase for the builtin sessions for sure...

**Comment by F-Node-Karlsruhe** [comment]
So maybe I should it implement it myself with cookies I guess? :/
