### ISSUE TITLE
Debug reloader extra files arg doesn't accept directories

### ISSUE THREAD

**Issue by graydenshand** [pallets/flask#4176]
I'm using Webpack to bundle static assets from an "src/assets" subdirectory and place the generated files into the "src/static" directory.

I need to instruct the reloader to watch all extra files in the "src/assets" directory and reload the app on changes. 

To do this, there are three options:
* There's an environment variable `FLASK_RUN_EXTRA_FILES=...`
* There's a command line argument to `flask_run --extra-files=...`
* You can pass it as an option directly to the `app.run(extra_files=[...])` function. 

All three of these approaches do not accept directory paths, every individual file to watch must be enumerated. 

I suppose that in and of itself is a problem with Werkzeug not Flask, since it appears the options are just passed through to the `run_simple` function. 

However, because of this limitation, I need to find a good way to construct this option dynamically based on the current state of the "src/assets" directory before the app starts. 

I can't figure out how one would do this, and still be able to use the `flask run` cli command to start the server. 

So I'm proposing one of two fixes:
1) Allow the `extra_files` option to accept directory paths as inputs. This would require enumerating each of the files in the directories before passing the option to Werkzeug, or patching Werkzeug to do this. 
2) Allow the `flask_run` command to be mapped to a specific configuration of the `app.run()` function. Currently I can either configure an `app.run()` to use within the `if __name__ == "__main__":` block, however then I can no longer use the `flask run` cli command and instead need to start the application with "python main.py". 

**Minimal example**
Project structure:
```
app/
  assets/
    main.js
  main.py
```
```python
# main.py
from flask import Flask


app = Flask(__name__)

if __name__=="__main__":
	app.run(debug=1, extra_files=["./assets/"])
```
```javascript
// assets/main.js
console.log('test');
```
Run using `python main.py` or `flask run --extra-fields=./assets/`, and modify `./assets/main.js`. The server does not reload. 

Then either modify the extra_files argument of the `app.run()` command to `extra_files=["./assets/main.js"]` and re-run with `python main.py`, or run the cli command `flask run --extra-fields=./assets/main.js`. Now, if you change `./assets/main.js` the server reloads. 

**Expected Behavior**
Specifying a path to a directory watches every file in that directory.  OR
`flask_run` calls the configured `app.run(...)` function so that I can generate the list of files to watch at run time. 

**Environment:**

- Python version: 3.9.5
- Flask version: 2.0.1

**Comment by graydenshand** [comment]
I did find a work around FWIW..

You can dynamically set your `FLASK_RUN_EXTRA_FILES` env variable before starting the app...

```python
#main.py
from flask import Flask
import os

app = Flask(__name__)

os.environ['FLASK_RUN_EXTRA_FILES'] = "./assets/main.js" # assume this string is generated dynamically
```

You can then run the app with `flask run` and it watches `./assets/main.js`.

**Comment by graydenshand** [comment]
@davidism would you accept a PR that fixes this? If so should this be handled in Flask or Werkzeug? 

This seems like unintended behavior, given that [the example in the docs](https://flask.palletsprojects.com/en/2.0.x/cli/#watch-extra-files-with-the-reloader) passes a directory. 

PS: I'm new to open source development and appreciate your help getting started!

**Comment by davidism** [comment]
`extra_files` can already contain directories, but only `*.py`, `*.pyc`, and `*.zip` files are watched. *Specific* other files can be watched, but not arbitrary files in arbitrary directories, it's too ineficient. Reloading on asset build changes doesn't make sense, Flask will already serve whatever file exists, it doesn't require a refresh. Perhaps you have a caching issue?

**Comment by graydenshand** [comment]
Ok 👍

I'm integrating with Webpack and am using the `@app.before_first_request` hook to rebuild static assets when the server reloads. 

Webpack takes the files in `assets/` and bundles them into the `static/` folder. So, I'm watching the 'assets' directory to trigger this reload/rebuild whenever a static asset changes.

I guess this is an edge case. Thanks for considering.

**Comment by ThiefMaster** [comment]
Webpack builds do not really belong in there. Run the webpack watcher separately from the flask dev server (and not at all in production).

**Comment by graydenshand** [comment]
I use the webpack watcher when it is running, but fall back this approach when it is not running (and only in dev mode). This makes it so that you don't *need* to run the watcher, even though it's usually faster to. 

Here's the full module for my webpack integration in case your curious. 

```python
import requests
from flask import current_app, url_for
import subprocess
import os


def static_url_for(path):
    if current_app.config["USE_WEBPACK_DEV_SERVER"]:
        return f"http://localhost:3000/static/{path}"
    else:
        return url_for("static", filename=path)


def webpack_init(app):
    if app.config["ENV"] == "development":

        @app.before_first_request
        def build_assets_on_reload_if_webpack_dev_server_not_running():
            if app.config["ENV"] == "development":
                try:
                    r = requests.get("http://localhost:3000/static/main.js")
                    # Webpack dev server is running
                    app.config["USE_WEBPACK_DEV_SERVER"] = True
                except requests.exceptions.ConnectionError as e:
                    # Webpack dev server is not running
                    app.logger.warning(
                        "Compiling static assets. To avoid this warning, start the webpack dev server in a new shell with `flask webpack watch`."
                    )
                    app.config["USE_WEBPACK_DEV_SERVER"] = False
                    subprocess.run("npx webpack", shell=True)

        @app.before_request
        def webpack_dev_server_health_check():
            if app.config["ENV"] == "development":
                try:
                    r = requests.get("http://localhost:3000/static/main.js")
                    # Webpack dev server is running
                    app.config["USE_WEBPACK_DEV_SERVER"] = True
                except requests.exceptions.ConnectionError as e:
                    # Webpack dev server is not running
                    app.config["USE_WEBPACK_DEV_SERVER"] = False

        # Add all files in ./src/assets directory to watched files list
        extra_files = []
        watched_directories = ["./src/assets"]
        for directory in watched_directories:
            for dirpath, dirs, files in os.walk(directory):
                for filename in files:
                    filename = os.path.join(dirpath, filename)
                    if os.path.isfile(filename):
                        extra_files.append(filename)
        if os.name != 'nt':
            os.environ["FLASK_RUN_EXTRA_FILES"] = ":".join(extra_files)
        else:
            os.environ["FLASK_RUN_EXTRA_FILES"] = ";".join(extra_files)



    @app.context_processor
    def webpack_init_template_vars():
        return {"static_url_for": static_url_for}
```

I also added two cli commands `flask webpack build` and `flask webpack watch`.

I hear you that rebuilding assets shouldn't be the job of the flask dev server, maybe I'll refactor this. Thanks for the feedback!
