### ISSUE TITLE
Flask with PyInstaller does not show images added at runtime

### ISSUE THREAD

**Issue by danishansari** [pallets/flask#4179]
I have a simple app running on Flask, which displays images from a directory. Which works fine, until I create an executable using Pyinstaller. This executable also works when there were already some images at the time of creation, but it can't load any later added images, I guess it just bundles all the existing images. I tried with both a single file and a directory, nothing worked. I would be really grateful if somebody can give me some direction on this.

For more detail and sample code to reproduce this issue is [here](https://stackoverflow.com/questions/68153266/flask-with-pyinstaller-does-not-show-images-added-at-runtime).

**Comment by greyli** [comment]
IMO, it's more like an issue related to your own code or Pyinstaller instead of a bug in Flask (notice this issue tracker is for issues related to Flask itself), so I'm going to transfer this to our GitHub discussion.
