### ISSUE TITLE
Flask tutorial `test_auth.test_logout` doesn't fully log in before it logs out

### ISSUE THREAD

**Issue by mkillianey** [pallets/flask#4201]
In the Flask tutorial, `test_auth.test_logout` passes even if one comments out the call to `auth.logout()` on line 68:

https://github.com/pallets/flask/blob/7a73171edc3bcffef96ef6367977ab3ae9af9350/examples/tutorial/tests/test_auth.py#L64-L69

It should probably match the structure of `test_auth.test_login`, and call `client.get("/")` to populate the session:

https://github.com/pallets/flask/blob/7a73171edc3bcffef96ef6367977ab3ae9af9350/examples/tutorial/tests/test_auth.py#L49-L51

So that the test looks like this:
```
def test_logout(client, auth):
    auth.login()

    with client:
        client.get("/") # Or similar so that `"user_id" in session` is true here
        auth.logout()
        assert "user_id" not in session
```

**Comment by davidism** [comment]
As far as I can tell the `.get` call isn't required, here or in the other test you observed it in. Perhaps it's used in `test_login` to assert that the index page still renders successfully after logging in, but that doesn't need to be tested again when logging out.

**Comment by mkillianey** [comment]
> As far as I can tell the .get call isn't required, here or in the other test you observed it in.

@davidism  This is a very minor point that only affects tutorial code, so I don't want to beat it to death, but I don't think that's true.

If you have the spare cycles to run the test locally, you can see that removing the `.get` call from `test_login` on line 50 does cause that test to fail (at least it does for me using Flask 2.0.1).

As for `test_logout`, the absence of `client.get("/")` doesn't cause the test to fail, but it makes the test somewhat misleading, in that it _looks_ like the test's precondition is that a user is logged in (and that, by implication, `user_id` is present on the `session`), and that the test's purpose is to verify that `auth.logout()` can _remove_ `user_id` from `session`.

If that is an accurate reading of the test's intended preconditions, adding this `assert` shows that it doesn't hold:
```
def test_logout(client, auth):
    auth.login()

    with client:
        assert "user_id" in session # this assertion will fail unless client.get (or equivalent) is called before this line
        auth.logout()
        assert "user_id" not in session
```
Without the above assertion, the test is more like `test_logout_when_user_is_not_logged_into_session` -- one can observe that replacing `auth.logout()` with a no-op _also_ passes the test.

FWIW, the reason why I'm bothering with this is because I copypasta-ed the tutorial code for my own purposes and spent a little time head-scratching before realizing that `auth.login()` didn't actually populate `user_id` on the `session`.   Given the excellent quality of the Flask tutorial (and documentation in general), I just wanted to help the next person to come along have an even better experience than I had, but if this is a drain on energy better spent improving Flask, happy to drop it.

**Comment by davidism** [comment]
> auth.login() didn't actually populate user_id on the session

Yes it does:

https://github.com/pallets/flask/blob/7a73171edc3bcffef96ef6367977ab3ae9af9350/examples/tutorial/flaskr/auth.py#L104

Seems the issue is that `with client` isn't around the `login` request.
