### ISSUE TITLE
View arguments

### ISSUE THREAD

**Issue by arihant2math** [pallets/flask#4206]
View arguments don't work unless there is a slash after them, even when they are at the end of the route. For example:
```
app = Flask(__name__)

@app.route('/view/<article_id>')
def view_article(article_id):
    return article_id
```
 fails to work, going to `localhost:5000/view/1` gives a 404 error. On the other hand:

```
app = Flask(__name__)

@app.route('/view/<article_id>/')
def view_article(article_id):
    return article_id
```
works perfectly well, notice that the only difference is the / at the end of the app.route.
Environment:

- Python version: 3.9.6
- Flask version: 2.0.1

**Comment by davidism** [comment]
I can't reproduce this issue. Both routes work as expected.
