### ISSUE TITLE
Questions about exceptions when run in docker container

### ISSUE THREAD

**Issue by leolcao** [pallets/flask#4215]
This issue is not want to report a bug of Flask, just want to throw it out and to see opinions about it.

Now, let me introduce the context and what I find.

We developed 2 servers base on Flask and gevent.pywsgi, and I cannot show the codes by the way, because they are company's codes.

But I can describe them in brief:

- Server A and Server B, they are both the web servers
- Once Server A received a http request from other subsystem(implemented by node.js), it will do some processing, and send the http request to Server B, after Server B response, server A send response back to its client.
- the Server A client will send the request in parallel, 45 counts at same time for one batch by using Axios.js.
- In Server A and B, we both use gevent.pywsgi and Flask to create the web server, and no limited for the pywsgi Pool
- In Server A and B, we create 2 threads to run 2 pywsgi servers, one is for health check, another is for the features.

sample codes
```
...
# function server
function_app = Flask(__name__)
# monitor server
monitor_app = Flask(__name__)
...
port = os.environ['HEALTH_PORT']
self.monitor_server = WSGIServer(('0.0.0.0', int(port)), monitor_app)
self.monitor_server.serve_forever()
...
port = os.environ['PORT']
pool = Pool(None)
self.http_server = WSGIServer(('0.0.0.0', int(port)), function_app, spawn=pool)
self.http_server.serve_forever()
...
```

I also use Apache Bench to do the performance testing, like(server A listen on 5000 port):

```
./ab.exe -T "application/tar" -p ./0001_0008.tar -n 1000 -c 1000 http://localhost:5000/processing
```

The key is I **find the exceptions only when I run those 2 web servers in the docker container**, but when I run them in my windows local, the exception are very rarely to see. So, I don't think the issues in docker container come from codes

we also tested 2 docker container environment: one is docker for windows, another is docker in ubuntu 20.04, the findings are same.

the exceptions are 2, after first look, I know something bad happened from the flask app context.

```
Traceback (most recent call last):
  File "main.py", line 58, in route_process_tile
    return jsonify(extraction.run_tile_production(request.stream, deploy_env))
  File "/usr/local/lib/python3.7/site-packages/flask/json/__init__.py", line 358, in jsonify
    if current_app.config["JSONIFY_PRETTYPRINT_REGULAR"] or current_app.debug:
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 422, in __get__
    obj = instance._get_current_object()
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 544, in _get_current_object
    return self.__local()  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/flask/globals.py", line 52, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
ERROR:ai:Working outside of application context.
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2457, in wsgi_app
    ctx.auto_pop(error)
  File "/usr/local/lib/python3.7/site-packages/flask/ctx.py", line 452, in auto_pop
    self.pop(exc)
  File "/usr/local/lib/python3.7/site-packages/flask/ctx.py", line 442, in pop
    self,
AssertionError: Popped wrong request context. (<RequestContext 'http://localhost:5000/xxxx' [POST] of main> instead of <RequestContext 'http://localhost:5000/xxxx' [POST] of main>)
2021-08-02T10:37:56Z {'REMOTE_ADDR': '10.0.0.2', 'REMOTE_PORT': '36148', 'HTTP_HOST': 'localhost:5000', (hidden keys: 22)} failed with AssertionError

10.0.0.2 - - [2021-08-02 10:37:56] "POST /xxxxx HTTP/1.0" 500 161 11.801833
```

So, for the exceptions themself, I think we don't need to discuss, they are well known issues, and I know the reason, but I don't understand what is the difference between the docker container environment and my windows local?

In my windows local, I use miniconda to create the virtual environment from python 3.7 version, and the python interpreter also same: cpython, then what else?

Environment:

- Python version: 3.7.10 (use the official docker python:3.7-slim-buster)
- Flask version: 1.1.1

**Comment by davidism** [comment]
Please use [our Discord](https://discord.gg/pallets) for discussion about your own code. This tracker is for issues related to the project itself.
