### ISSUE TITLE
flask and tkinter for a dialog box (yes or no - start server)

### ISSUE THREAD

**Issue by Xavlight** [pallets/flask#4216]
Hi,

I would like to create a dialog box (tkinter) with an on/off button.
When the program starts, it starts the Flask server directly.
And with the button, you can stop or restart it.

But as soon as I run app.run, the dialog box does not work anymore.
I tried with 'threading.Thread' to start flask and tkinter, it works. But in this case I can't stop the flask server.

Can anyone give me a hint?

Thanks

Environment:

- Python version: 3.9.6
- Flask version: 2.0.1
- Tkinter : 8.6

**Comment by ThiefMaster** [comment]
Please use Discussions or Discord/IRC channels for such questions.
