### ISSUE TITLE
pylint error: setting session.modified results in 'assigning non-slot' error

### ISSUE THREAD

**Issue by mrichar1** [pallets/flask#4219]
The `authomatic` library has started reporting pylint errors for the following code:

https://github.com/authomatic/authomatic/blob/master/authomatic/extras/flask.py

`authomatic/extras/flask.py:47:8: E0237: Assigning to attribute 'modified' not defined in class slots (assigning-non-slot)`

the line in question is doing:

`session.modified = True`

As described in https://flask.palletsprojects.com/en/2.0.x/api/#sessions

The easiest way to replicate is to run `tox` against the authomatic project:

```
git clone https://github.com/authomatic/authomatic
cd authomatic
python3 -mvenv env
env/bin/pip install tox
env/bin/tox
```

We can work around this by disabling pylint for this line, but I thought I'd flag it up. Let me know if we can provide any more info.

**Comment by LeOndaz** [comment]
I'd mention that I didn't find any __slots__ in the session handling in Flask, or perhaps I missed it while searching or smth, I'll be following this

**Comment by LeOndaz** [comment]
> I'd mention that I didn't find any `__slots__` in the session handling in Flask, or perhaps I missed it while searching or smth, I'll be following this

**Comment by davidism** [comment]
See #4020 for discussion. This is something that needs to be reported to pylint, the problem is that `session` is a special `LocalProxy` object that defines `__slots__`, but also defines `__getattr__` which means that pylint should allow arbitrary attribute access. There's nothing Flask or Werkzeug can do about this message.
