### ISSUE TITLE
Add support for a `FLASK_RUN_EXTRA_FILES` config variable.

### ISSUE THREAD

**Issue by graydenshand** [pallets/flask#4222]
[This section of the flask documentation](https://flask.palletsprojects.com/en/2.0.x/cli/?highlight=flask_run_extra_files#watch-extra-files-with-the-reloader) discusses how you can watch additional files with the reloader. 

You can currently do this by using the `--extra_files` option of the `flask run` command. Or by setting a `FLASK_RUN_EXTRA_FILES` environment variable. 

Ideally you could bundle this in with your application config, since it's not something that's likely to change from environment to environment but is inherent to the application itself.

Currently, I work around this by hard-coding the setting of the environment variable in my development config class:

```python
class DevelopmentConfig(Config):
    DEBUG = True
    ENV = "development"
    extra_files = [os.path.join("foo","bar.txt"), os.path.join("assets","styles.scss")]
    if os.name != 'nt':
            # Posix
            os.environ["FLASK_RUN_EXTRA_FILES"] = ":".join(extra_files)
        else:
            # Windows
            os.environ["FLASK_RUN_EXTRA_FILES"] = ";".join(extra_files)
```

I'm proposing a config variable that supports a list of file paths to watch:
```python
class DevelopmentConfig(Config):
    DEBUG = True
    ENV = "development"
    FLASK_RUN_EXTRA_FILES = [os.path.join("foo","bar.txt"), os.path.join("assets","styles.scss")]
```

**Comment by davidism** [comment]
See linked PR for close reason.
