### ISSUE TITLE
Add 2.x docs to Download

### ISSUE THREAD

**Issue by aparcar** [pallets/flask#4231]
The current docs are not available to Download while older versions are available as PDF or ePUB file. If possible please also add 2.x docs.

https://readthedocs.org/projects/flask/downloads/

![image](https://user-images.githubusercontent.com/16000931/128790365-914652f2-d0e2-4ead-8e4e-bef0b1eeab09.png)

**Comment by davidism** [comment]
I'm no longer building these, you can build by coming and running sphinx if you need it.
