### ISSUE TITLE
Not Found  in Interactive Console

### ISSUE THREAD

**Issue by ScRiPt1337** [pallets/flask#4240]
I am using Linux i am getting 404 in debug console in Microsoft edge

[17/Aug/2021 23:45:24] "GET /console?&__debugger__=yes&cmd=&frm=0&s=4ifZvBHH1vFHv5SV3lHR HTTP/1.1" 404

**Comment by davidism** [comment]
Sorry, there's not enough information to help you with this. Try asking for help in our discord chat and provide more details there
