### ISSUE TITLE
Partial content support

### ISSUE THREAD

**Issue by wilsaj** [pallets/flask#425]
from feedback site: "it doesn't support serving partial content (206), which seems to confuse browsers when serving them HTML5 media files even if it shouldn't."

link: http://feedback.flask.pocoo.org/message/288

**Comment by entd** [comment]
As of latest stable (10.x) this bug is still present. Video playing works, however video seeking does not. `videoDOM.currentTime = 10` fails (video rolls to the start). While flask is not intended for static content, these features would help greatly to improve usage of flask.

**Comment by untitaker** [comment]
Patches welcome.

**Comment by entd** [comment]
I took a quick look through flask code and it seems it would need some dive into werkzeug. If I will spin something up in a free time (patch for example - seems it will need to react to some headers, set 206, serve part of file) I will make you know :)

**Comment by Elizaveta239** [comment]
@entd Hello! Could you please provide a code sample for reproducing the issue?

**Comment by entd** [comment]
I dont know if I have it, but it goes like that
`
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    <video id="video1" width="420">
    <source src="mov_bbb.mp4" type="video/mp4">
    <source src="mov_bbb.ogg" type="video/ogg">
    Your browser does not support HTML5 video.
  </video>
 <button onclick="seek()">Click me</button>
  </body>
<script>
function seek() {
    var video = document.getElementById("video1");
    video.currentTime = 10;
}
</script>
</html>
`
if that video served from nginx it seeks to 10s. But if it is from flask than it fails to seek.

**Comment by brianrusso** [comment]
Tested with flask 0.12.2 using flask to serve an mp4 file. Seeking works correctly.

**Comment by brianrusso** [comment]
from flask import Flask

app = Flask(__name__)
app.debug = True
docstr = """
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    <video id="video1" width="420">
    <source src="/static/video.mp4" type="video/mp4">
    Your browser does not support HTML5 video.
  </video>
 <button onclick="seek()">Click me</button>
  </body>
<script>
time = 0;
function seek() {
    var video = document.getElementById("video1");
    console.log("click");
    video.currentTime +=1;
    console.log(video.currentTime);
}
</script>
</html>
"""


@app.route('/')
def hello_world():
    return docstr


@app.route('/video.mp4')
def video():
    print('hi')
    return app.send_static_file('video.mp4')
