### ISSUE TITLE
Minor glitch in documentation

### ISSUE THREAD

**Issue by Mindiell** [pallets/flask#4260]
Missing closing parenthesis in https://flask.palletsprojects.com/en/2.0.x/deploying/uwsgi/#starting-your-app-with-uwsgi.

**Comment by ThiefMaster** [comment]
Please do not open issues for minor issues like this but go straight for the PR. Having an issue as well just adds noise...

**Comment by Mindiell** [comment]
Oh sorry, I just wanted to strictly follow contibuting instructions.

**Comment by ThiefMaster** [comment]
The point is that people do not waste time making a large PR of something we don't need/want. Maybe we should clarify that this doesn't apply to typos etc..
