### ISSUE TITLE
Implementation of custom methods in blueprints

### ISSUE THREAD

**Issue by BorjaEst** [pallets/flask#4262]
I am following this guide to make my API as simple and standard as possible:
https://cloud.google.com/apis/design/custom_methods

I see this method is quite common as also I could found it at [API Design Patterns](https://www.manning.com/books/api-design-patterns) and it has sense.

However, I see currently in a flask blueprint it is not possible to use ':' separator for the root path resources.
For example:

```py
from flask.views import MethodView
from flaskimport Blueprint

blp = Blueprint('benchmarks', 'benchmarks')

@blp.route('')
class Benchmarks(MethodView)

    def get(self, query_args):
        ....
  
    def post(self, body_args):
        ....
```

This would create the following routes:
- GET /benchmarks
- POST /benchmarks

However, there is no simple way to create the following routes inside the blueprint:
- GET /benchmarks:search
- POST /benchmarks:my_custom_method

The main issue relies here
https://github.com/pallets/flask/blob/main/src/flask/blueprints.py#L93
where the only available separator after the blueprint url_prefix is '/', leading to strange combinations:
- GET /benchmarks/:search
- POST /benchmarks/:custom

Why not to use a resource path?
If I configure the following route:

- GET /benchmarks/search
Then it might conflict with my id resource

- GET /benchmarks/<string:name>
Threfore I cannot create a benchmark with name "search".
This is a design issue, the ':' convention was created to avoid this type of issues.

Solution?
Maybe just accept the ':' as an optional start character?
```py

        if self.url_prefix is not None:
            if not rule:
                rule = self.url_prefix
            elif rule[0] == ':' and 'somethingelse:
                rule =  ":".join((self.url_prefix.rstrip("/"), rule.lstrip("/")))
            else:
                rule = "/".join((self.url_prefix.rstrip("/"), rule.lstrip("/")))

```

Although there sure might be better ways.

**Comment by davidism** [comment]
I don't quite understand what's being asked here, but I don't want to make the separator for blueprint prefixes configurable. You can probably subclass, or use another API library besides blueprints, to create more custom URLs.
