### ISSUE TITLE
DOC: Link to Flask-WTF broken

### ISSUE THREAD

**Issue by KPLauritzen** [pallets/flask#4270]
The link to the Flask-WTF documentation is broken.

https://flask.palletsprojects.com/en/latest/patterns/wtforms/ links to https://flask-wtf.readthedocs.io/en/stable/ and should instead link to https://flask-wtf.readthedocs.io/

**Comment by davidism** [comment]
No need to open an issue about a simple docs typo, it's ok to only submit a PR to fix those.
