### ISSUE TITLE
.run() with arg load_dotenv ignores FLASK_RUN_PORT env variable

### ISSUE THREAD

**Issue by frostmorn** [pallets/flask#4286]
Also same happens with .flaskenv usage

Minimal reproducer:
```
from flask import Flask
app = Flask(__name__)
app.run(load_dotenv=True)
```
App serves on default port instead of serving on a port set in .env file.

Environment:

- Python version: 3.9.7
- Flask version:2.0.0

**Comment by davidism** [comment]
Those are a feature of Click, they fill in the equivalent CLI option values.
