### ISSUE TITLE
pdf version of docs has strange characters

### ISSUE THREAD

**Issue by wilsaj** [pallets/flask#429]
unhappy comment: "The pdf version of the doc contains strange ' chars, thus copy-pasting the code won't work. (It's ok with the online version though)"

link: http://feedback.flask.pocoo.org/message/277

**Comment by alatar-** [comment]
It's been quite a while and it seems to me that this issue is no longer valid. I didn't manage to reproduce it in current docs.

Current pdf doc: http://flask.pocoo.org/docs/0.11/.latex/Flask.pdf

**Comment by jeffwidman** [comment]
Thanks @alatar- for your hard work at the Pycon Sprint today.
