### ISSUE TITLE
Custom Redirect Screen

### ISSUE THREAD

**Issue by BD103** [pallets/flask#4290]
It would be amazing if, when returning a redirect, you could configure a Jinja template to be sent along with it. This would allow for custom styling if your internet is slow.

Technically this feature could be a part of Werkzeug, but I believe that it is more fitting for Flask. See below for some examples and code.

[What's currently being sent:](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/utils.py#L561)

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="{html.escape(location)}">{display_location}</a>. If not click the link.
```

(It also forgets a `<p>` tag.) Here would be a nicer way to do this:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Site Name - Redirecting</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <!-- or even better -->
  <style>body { background: black; color: white; }</style>
</head>

<body>
  <h1 class="title">Don't worry, the page is loading!</h1>
  <p>You accessed a redirect URL. Please wait a few seconds to be redirected.</p>
  <p>If it doesn't work, click <a href="{{ location | equivilant_of_html_escape }}">{{ display_location }}</a></p>
</body>

</html>
```

Then a custom function could be written:

```python
def redirect(location: str, code: int = 302, Response: t.Optional[t.Type["Response"]] = None, template: str = "redirect.html"):
  ...

  response = Response(render_template(template), code, mimetype="text/html")
  response.headers["Location"] = location
  return response
```

(Code left out for shortness.) I'm sure there is a better way to define a template, but it's just a sketch.

Thanks for this wonderful package (and hopefully feedback!)

~BD103

**Comment by davidism** [comment]
`redirect` returns a `Response`. You can assign any valid body you want to `response.data`.
