### ISSUE TITLE
MethodView Decorators list execution order

### ISSUE THREAD

**Issue by gruvw** [pallets/flask#4291]
Hello, I was experimenting with the option to add decorators to a view via the `decorators` class variable, which contains the list of the different decorators. ([Flask docs - decorating views](https://flask.palletsprojects.com/en/2.0.x/views/#decorating-views))

So in order to decorate a MethodView method, we can't do this:
```python
# Example 1
class Example(MethodView):
    @user_required
    @data_required
    def get(self):
        ...
```
But we must do this instead:
```python
# Example 2
class Example(MethodView):
    decorators = [user_required, data_required]
    def get(self):
        ...
```
This is totally fine, but there is an issue with the way it has been implemented.

The natural order of decorators (or should I say wrapper) execution is from top to bottom.
In my first example (the natural way you would decorate a function) you suppose the code in the first decorator (`user_required`) to be executed first and then the code from the second decorator (`data_required`) → `user_required(data_required(view))`.

The thing is in the implementation of the `decorators` class variable the decorators in the list are applied in the wrong (or unnatural) order:
```python
# from Flask source code (views.py -> View class)
if cls.decorators:
    ...
    for decorator in cls.decorators:
        view = decorator(view)
```
This will execute the second decorator (`data_required`) before the first one in the list (`user_required`) which is very confusing and unnatural → `data_required(user_required(view))`.

Just imagine that the first decorator (`user_required`) exposes the `user` variable to the `g` variable (`g.user`).
The second decorator (`data_required`) pulls data from the user but as it is implemented, this would throw an error as the `user_required` decorator hasn't been executed yet.

I suggest reversing the order of the decorators before applying them to the view method:
```python
if cls.decorators:
    ...
    for decorator in revesed(cls.decorators):
        view = decorator(view)
```
It would feel more natural and lead to less confusion...

**Comment by gruvw** [comment]
The decorators are applied from bottom to top, which is what I wrote: `user_required(data_required(view))`, what I meant was the wrapper execution goes from top to bottom.

> Even though the decorators do technically execute from bottom to top, what you have to remember is that when the decorator executes, it returns a wrapper. The wrapper is where the core functionality of the decorator should execute... and decorator wrappers execute top to bottom.  
Jimmy Huch ([SO - Does the order of decorators matter on a flask view](https://stackoverflow.com/questions/28204071/does-the-order-of-decorators-matter-on-a-flask-view))

But I understand it cannot be fixed without breaking old code... :(

**Comment by davidism** [comment]
You're sort of demonstrating why there's no way to fix this. Application order and execution order are reversed, and do read visually the same way. There is no "correct" order to write them in. They're currently written in application order, which makes sense to me.
