### ISSUE TITLE
tests/test_cli.py::test_lazy_load_error randomly fails with PyPy3

### ISSUE THREAD

**Issue by mgorny** [pallets/flask#4292]
After upgrading to 2.0.2, the tests sometimes (but not reliably) fail with pypy3.8:

```
============================================================== FAILURES ===============================================================
________________________________________________________ test_lazy_load_error _________________________________________________________
tests/test_cli.py:328: in test_lazy_load_error
    lazy._flush_bg_loading_exception()
E   Failed: DID NOT RAISE <class 'test_cli.test_lazy_load_error.<locals>.BadExc'>
======================================================= short test summary info =======================================================
FAILED tests/test_cli.py::test_lazy_load_error - Failed: DID NOT RAISE <class 'test_cli.test_lazy_load_error.<locals>.BadExc'>
=================================== 1 failed, 504 passed, 2 skipped, 2 xfailed, 1 xpassed in 10.40s ===================================
ERROR: InvocationError for command /tmp/flask/.tox/pypy3/bin/pytest -v --tb=short --basetemp=/tmp/flask/.tox/pypy3/tmp tests examples (exited with code 1)
_______________________________________________________________ summary _______________________________________________________________
ERROR:   pypy3: commands failed
```

I am able to replicate with every ~third invocation of:

```
tox -e pypy3
```

However, I was unable to reproduce when running just that one test. My totally random guess is that it might have something to do with PyPy's GC behavior.

Environment:

- Python version:
  ```
  Python 3.8.12 (7e233b73b92740ab7a20680a404ac100be1eb508, Sep 22 2021, 14:08:24)
  [PyPy 7.3.6 with GCC 11.2.0]
  ```
- Flask version: git 1cf43e08e3211e7ff21005dd778613e39b20a449 (happens since 2305b056c3a3161c92ea61e6fceb67262766bc40, i.e. adding the test)

**Comment by davidism** [comment]
This was happening to me constantly yesterday, but today I'm having a really hard time triggering it. I think #4293 should fix it, but let me know if it continues happening and I'll add a skip.

**Comment by mgorny** [comment]
Unfortunately, it failed on the second test run already :-(.

**Comment by davidism** [comment]
I'll allow the test to `xfail`. It would be nice to know why it's failing occasionally though, and how to more reliably reproduce that.

**Comment by mgorny** [comment]
> Actually, I just noticed you're using PyPy 3.8, which I don't have access to. I'm having a really hard time reproducing this on PyPy 3.7,

I'm going to try PyPy3.7 shortly.

> I tried running `tox -p -r` to put the tests in parallel under some load, and it passed ten times in a row. How are you running the tests?

My test script is:

```
#!/bin/bash
set -e -x

cd /tmp/flask
fail=0
for x in $(seq 1 10); do
	if ! tox -e pypy3; then
		fail=1
		break
	fi
done

exit $fail
```

> What are the specs of the machine?

AMD Ryzen 5 3600 6-Core Processor throttled down to 2800 MHz
32 GiB RAM

I've git-cloned flask into tmpfs.

> Are you absolutely sure you pulled the latest changes?

Yep. I presume you mean this;

```
commit 6d65595a3c0a02d098c36f7d337e053e07975316
Author: David Lord <davidism@gmail.com>
Date:   2021-10-05 17:03:30 +0200

    try to address flakiness of lazy loading test
```

**Comment by mgorny** [comment]
PyPy3.7 (7.3.5) also failed on the second run ;-).

**Comment by davidism** [comment]
I'll allow the test to xfail. It would be nice to know why it's failing occasionally though, and how to more reliably reproduce that.
