### ISSUE TITLE
 Debug reloader extra files arg should accept patterns

### ISSUE THREAD

**Issue by Glandos** [pallets/flask#4327]
As stated in #4176, watching for a whole directory might be too expensive.

But it is really annoying to kill and restart the dev server each time I change a template. So I'd like to use something like: `run --extra-files 'templates/*.html'`.

I know that I can use shell and/or Python to set the variable, but… would it be valuable to someone to have this plugged into Flask/Werkzeug?

**Comment by davidism** [comment]
The reloader does not effect template reloading.

**Comment by Glandos** [comment]
OK, so I'll have to investigate why my project needs a reload when a template is changed:
- With `run --reload`: template changed, but the output is not.
- Killing and restarting: template changed, output changed.
- With `run --reload --extra-files templates/template.html`: template changed, output changed after auto reload.

It seems to be an issue with my setup then.
