### ISSUE TITLE
ConnectTimeoutError when trying to install flask in company system.

### ISSUE THREAD

**Issue by Adithya-c-droid** [pallets/flask#4329]
While installing flask to my system, after activating the virtual environment(venv),  this is the error I'm finding.

(venv) C:\Users\sesa643668\Desktop\flask\venv\Scripts> pip install -U Flask
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB2BEF28F0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/flask/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB2BEF27D0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/flask/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB2BEF2710>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/flask/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB2BEF2140>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/flask/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001FB2BEF3340>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/flask/
ERROR: Could not find a version that satisfies the requirement Flask (from versions: none)
ERROR: No matching distribution found for Flask 

Please help me resolve this error as I need to perform my internship project in the system else my internship might get terminated . 
P.S: I have run the command in company network as well as my personal network. But no use.

**Comment by ThiefMaster** [comment]
your system can't connect to pypi. probably doesn't fail just for flask. so clearly out of scope here...

**Comment by Adithya-c-droid** [comment]
> your system can't connect to pypi. probably doesn't fail just for flask. so clearly out of scope here...

Any suugestions?..please

**Comment by jiamingla** [comment]
Maybe you can install others like numpy to check?
Or Ask your company's MIS for help?
