### ISSUE TITLE
should sphinxcontrib-jsmath be removed from configuration files?

### ISSUE THREAD

**Issue by yuluc123** [pallets/flask#4330]
Hi
I notice that sphinxcontrib-jsmath is listed as dependency in the configuration files such as requirements/docs.txt, but it is not used in source code.
So is it necessary to remove sphinxcontrib-jsmath  from dependencies?

**Comment by davidism** [comment]
We use `pip-compile` to pin all dependencies. It's a dependency of Sphinx, so it's pinned. The requirements files are for development, `install_requires` in `setup.cfg` lists the dependencies of the library itself.
