### ISSUE TITLE
`after_this_request` fails with a meaningless error when used outside request context

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/flask#4333]
https://github.com/pallets/flask/blob/9039534eee6a87da98a1dee9e4338d1b73e861f8/src/flask/ctx.py#L133

While it makes no sense to use it outside a context, the error message could be nicer when you do so anyway (e.g. because you accidentally call a function using it from a celery task or some other place without a request context), like e.g. in `copy_current_request_context` [in the same file](https://github.com/pallets/flask/blob/9039534eee6a87da98a1dee9e4338d1b73e861f8/src/flask/ctx.py#L161-L167).

```
AttributeError: 'NoneType' object has no attribute '_after_request_functions'
  ...
  File "flask/ctx.py", line 133, in after_this_request
    _request_ctx_stack.top._after_request_functions.append(f)
```

**Comment by afzal442** [comment]
hi @ThiefMaster, I'd like to contribute here. Do you mean to add an error message that you shared above in `copy_current_request_context` in the function `after_this_request` itself ?https://github.com/pallets/flask/blob/9039534eee6a87da98a1dee9e4338d1b73e861f8/src/flask/ctx.py#L112 Thanks.
