### ISSUE TITLE
Red the Docs Flask documentation out-of-date

### ISSUE THREAD

**Issue by smontanaro** [pallets/flask#4336]
Searching for flask docs on Brave:

https://search.brave.com/search?q=flask+documentation

yielded these two URLs as the first hits:

https://flask.palletsprojects.com/

https://flask-doc.readthedocs.io/

I didn't recognize the first URL (apologies, it's been awhile since I played with Flask), so I poked the second, as I recognized "readthedocs.io" as a semi-canonical place for Python module docs. Unfortunately, that documentation is quite old (0.10.1). I looked at what I had installed (2.0.2) and kept poking around, eventually deciding that maybe palletsprojects.com was okay after all.

It seems like either the flask-doc.readthedocs.io location should be updated, deleted, or set to permanently redirect to flask.palletsprojects.com.

**Comment by davidism** [comment]
https://flask.palletsprojects.com/ is the official URL, it's mentioned on the GitHub page, in the readme, and on the PyPI page.

That other one is some random person who built a version of the docs years ago and didn't update it since. I'll talk to RTD about taking that down.
