### ISSUE TITLE
Unable to use MethodView as a Metaclass base 

### ISSUE THREAD

**Issue by reubano** [pallets/flask#4369]
According to [Python docs](https://docs.python.org/3/reference/datamodel.html#determining-the-appropriate-metaclass)

> If the metaclass has a `__prepare__` attribute, it is called as `namespace = metaclass.__prepare__(name, bases, **kwds)` (where the additional keyword arguments, if any, come from the class definition)

> Once the class namespace has been populated by executing the class body, the class object is created by calling `metaclass(name, bases, namespace, **kwds)` (the additional keywords passed here are the same as those passed to `__prepare__`).

`MethodViewType` (and therefore `MethodView`) lacks this `**kwds`
https://github.com/pallets/flask/blob/9486b6cf57bd6a8a261f67091aca8ca78eeec1e3/src/flask/views.py#L106-L111

So the the three argument form of [`type`](https://docs.python.org/3/library/functions.html#type) won't work when supplied with `**kwargs` if `MethodView` is a base.

```python
from flask.views import View, MethodView


class PatchedMethodViewType(type):
    def __init__(cls, name, bases, d, **kwargs):
        super().__init__(name, bases, d)


class PatchedMethodView(View, metaclass=PatchedMethodViewType):
    def dispatch_request(self, *args, **kwargs):
        pass


class MyMethodView(MethodView):
    @classmethod
    def __init_subclass__(cls, author=None):
        cls.author = author

    def get(self):
        return 1


class MyPatchedMethodView(PatchedMethodView):
    @classmethod
    def __init_subclass__(cls, author=None):
        cls.author = author

    def get(self):
        return 1

type('MetaMethodView', (MyMethodView,), {})
# __main__.MetaMethodView

type('MetaMethodView', (MyMethodView,), {}, author='bob')
# TypeError: __init__() got an unexpected keyword argument 'author'

type('MetaMethodView', (MyPatchedMethodView,), {}, author='bob')
# __main__.MetaMethodView
```

**Comment by reubano** [comment]
```bash
$ python --version
Python 3.8.12
$ pip freeze | grep Flask=
Flask==1.1.4
```

**Comment by davidism** [comment]
I guess we can fix this, but this is *really* not the intended way to pass arguments to a `View` class. That's what the constructor is for, not the metaclass (which is only specific to `MethodView` anyway, not all `View` types).

**Comment by reubano** [comment]
@davidism Is there a better way to programmatically create views? Here's my use case:

```python
RESOURCES = {
    "xero": {
        "Projects": {
            "fields": ["projectId", "name", "status"],
            "id_field": "projectId",
            "subkey": "items",
            "methods": ["GET", "POST"],
        },
        "Users": {
            "resource": "projectsusers",
            "fields": ["userId", "name"],
            "id_field": "userId",
            "subkey": "items",
        },
        "ProjectTasks": {
            "fields": ["taskId", "name", "status", "rate.value", "projectId"],
            "id_field": "taskId",
            "subkey": "items",
            "subresource": "tasks",
            "methods": ["GET", "POST"],
        },
    },
}


def create_class(cls_name, *bases, **kwargs):
    attrs = {}

    for attr_name, value in kwargs.pop("attrs", {}).items():
        attrs[attr_name] = value

    return type(cls_name, bases, attrs, **kwargs)

for prefix, classes in RESOURCES.items():
    for cls_name, kwargs in classes.items():
        kwargs.setdefault("resource", cls_name.lower())
        resource = kwargs.get("resource")
        methods = kwargs.pop("methods", ["GET"])
        view = create_class(cls_name, base, prefix=prefix, **kwargs)
```

**Comment by davidism** [comment]
Sorry, I can't help you with your code design, but I strongly suspect that the answer is "yes, there is a better way."

**Comment by reubano** [comment]
I've update the above example to provide more context. Hopefully you can see what I'm trying to do. From what I've read, I thought Metaclasses was the best way to go about it. [Django](https://github.com/django/django/blob/7b8beeee3d45cafd7bec7ff3ee0e4371e142c36d/django/forms/widgets.py#L186-L196) and [others](https://github.com/jfinkels/flask-restless/blob/3c8e69bf4e2d34caa1671577e6ccddac2e63e168/flask_restless/helpers.py#L496-L512) do somewhat similar things...

**Comment by davidism** [comment]
OK, I've looked over this more, and I don't want to make the suggested change. By adding `**kwargs` to `ViewType.__init__`, it suggests that *any* `View` subclass can be passed metaclass arguments, which doesn't mean anything.

See a bit down in https://flask.palletsprojects.com/en/2.0.x/views/#basic-principle for how to define a `View` subclass that takes extra argument in `__init__`, which are passed from `as_view()`. That's the intended way to make a generic view. If you want to use metaclasses instead, I think the code you've shown is fine and indicates the intent explicitly.
