### ISSUE TITLE
flask test client + pytest asyncio: RuntimeError when test and view are both async

### ISSUE THREAD

**Issue by 0xf10413** [pallets/flask#4375]
Hi!

While migrating an application to asyncio, i encountered what I believed to be a bug.
Consider the following scenario:
* There is a view defined with a coroutine
* This function is called via the flask test client
* This test client is used in an async coroutine

Then there is the following exception:

```
Traceback (most recent call last):
  File "/home/flo/documents/code/flask-bug-testclient-asyncio/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/flo/documents/code/flask-bug-testclient-asyncio/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/flo/documents/code/flask-bug-testclient-asyncio/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/flo/documents/code/flask-bug-testclient-asyncio/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/flo/documents/code/flask-bug-testclient-asyncio/venv/lib/python3.9/site-packages/asgiref/sync.py", line 160, in __call__
    raise RuntimeError(
RuntimeError: You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.
```

See a reproducer in attachment.
[flask-bug-testclient-asyncio.tar.gz](https://github.com/pallets/flask/files/7687052/flask-bug-testclient-asyncio.tar.gz)

Steps to reproduce:
```
tar xvf flask-bug-testclient-asyncio.tar.gz
cd flask-bug-testclient-asyncio/

python -m venv venv
source venv/bin/activate
pip install -r  requirements.txt

pytest
```
If you change the view or the test function to not be async, the test pass. Both being not-async also works.
Both being async does not work.

There's probably a conflict due to the way this coroutine is scheduled. Could you have a peek ?
Thanks!

Environment:

- Python version: 3.9.9
- Flask version: 2.0.2

PS: couldn't find anything on the internet, except for [this post](https://stackoverflow.com/q/69431468).

**Comment by davidism** [comment]
I am not familiar with Pytest-Asyncio. What happens if you don't use that? It should be a requirement for testing Flask async routes.

**Comment by davidism** [comment]
Please include a minimal reproducible example in the issue itself, rather than as a download.

**Comment by miguelgrinberg** [comment]
The pytest-asyncio package just allows you to decorate an async test function so that a loop is automatically created, and the function called inside it.

The problem in this case is that the Flask codebase is not compatible with asyncio, so you cannot run the test client inside an asyncio loop. There is really nothing to gain from writing your unit test as an async test, since Flask itself isn't async. If you really need your test function to be async, then you can offload the test client call to an executor. This modified test passes:

```python
@pytest.mark.asyncio
async def test_async_in_async_fail():
    def sync_test():
        with app.test_client() as client:
            assert client.get("/").data == b"aaa"

    loop = asyncio.get_running_loop()
    await loop.run_in_executor(None, sync_test)
```

**Comment by 0xf10413** [comment]
Thanks for the explanation and the workaround!
>  There is really nothing to gain from writing your unit test as an async test

So, some context on that. I'm adding a bunch of async functions in my code. Some of them are called by flask views, and i call others to check the results in my tests. That's how i ended up in this situation.

I'm fine with the workaround, so i'm not sure what to do with this ticket. Google will probably index the error message so there's a reference now.

It's up to you!
