### ISSUE TITLE
The documentation's tutorial uses python2 syntax in an example

### ISSUE THREAD

**Issue by BrickGrass** [pallets/flask#4379]
I was reading the documentation, and noticed that one of the examples creates a class that inherits from object. Here: https://flask.palletsprojects.com/en/2.0.x/tutorial/tests/#id6

**Comment by ThiefMaster** [comment]
It's better to send just a PR for this kind of change instead of opening an issue...

**Comment by BrickGrass** [comment]
Sorry I'm new, was just sending this while I did the PR.
