### ISSUE TITLE
GeneratorExit exception is never raised when generator return empty bytes

### ISSUE THREAD

**Issue by clementperon** [pallets/flask#4385]
Hi,

I'm using streaming to send Raw data, sometimes the stream send nothing but in this case I can't properly catch when the user exit the stream.

Simple example
```
from flask import Flask, Response
from time import sleep

app = Flask(__name__)


@app.route("/")
def stream():
    def generator():
        try:
            while True:
                yield ""
                sleep(0.01)
        except GeneratorExit:
            print("Connection closed by user!!!!")

    return Response(generator())


if __name__ == "__main__":
    app.run(host='0.0.0.0')
```

In this case the GeneratorExit is never called when the client quit.
However If the yield return data it works properly.

Environment:
- Python version: 3.9.7
- Flask version: 1.1.4

**Comment by davidism** [comment]
That code doesn't make sense, a while loop will never raise a GeneratorExit. Regardless, it is not possible to detect client disconnects from within a WSGI request.

**Comment by clementperon** [comment]
@davidism  this code properly detect it

```
    def generator():
        try:
            while True:
                yield "0"
                sleep(0.01)
        except GeneratorExit:
            print("Connection closed by user!!!!")`
```
