### ISSUE TITLE
an ImportError was raised" but flask doesn't show the traceback #4307

### ISSUE THREAD

**Issue by Edmartt** [pallets/flask#4386]
Why are you closing this topic as fixed if is not? 

And when I say this topic I mean this [#4307](https://github.com/pallets/flask/issues/4307)

Please, this is still happening and needs to be fixed we can just guess what can be wrong and sometimes that's impossible

**Comment by davidism** [comment]
It's closed because a PR was merged, which will be available in the next release.

**Comment by Edmartt** [comment]
> It's closed because a PR was merged, which will be available in the next release.

Thank you, it would be nice to leave this message in the mentioned issue.
