### ISSUE TITLE
don't recommend using `X-XSS-Protection`

### ISSUE THREAD

**Issue by mousetail** [pallets/flask#4392]
The [security page](https://flask.palletsprojects.com/en/2.0.x/security/) of the docs recommends using X-XSS-Protection to prevent against XSS attacks. However, this is no longer recommended since it protects only against extremely rudimentary XSS attacks while at the same time causing while new types of more difficult to prevent XSS attacks.

See [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#x-xss-protection-header) and [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) for reasons why this is a problem.

This section should at least include a warning in case someone blindly copy pastes that code.

**Comment by davidism** [comment]
Go ahead and make a PR to remove it if it's no longer relevant to any supported browsers.
