### ISSUE TITLE
Endpoint registered for the HEAD method not called

### ISSUE THREAD

**Issue by erdnaxeli** [pallets/flask#4395]
Hi,

I am trying to implement a HEAD method for a route already having a GET route. The goal is to just return the headers without doing heavy computations to build the body. I know Werkzeug already provides a HEAD method, but I want to skip the heavy computations of the GET method as the body is not needed to answer quickly with just the headers. Actually the Werkzeug behavior is causing me some troubles.

Here is an exemple application:
```Python
from flask import Flask

app = Flask(__name__)

@app.route("/", methods=["GET"])
def hello_world():
    return "<p>Hello, World!</p>"

@app.route("/", methods=["HEAD"])
def hello_head():
    return '', 200, {"some-header": "some-value"}
```

This code is not HTTP compliant (both the GET and the HEAD methods do not return the same headers) but that is not relevant to see my problem.

I then run the app:
```
~ via 🐍 v3.9.9 on ☁️  erdnaxeli@myhost
❯ export FLASK_APP=t

~ via 🐍 v3.9.9 on ☁️  erdnaxeli@myhost
❯ flask run
 * Serving Flask app 't' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

```

Then here is the response I got with on a HEAD query:
```
❯ curl -vvv -X HEAD localhost:5000
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
*   Trying ::1:5000...
* connect to ::1 port 5000 failed: Connexion refusée
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> HEAD / HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 20
< Server: Werkzeug/2.0.2 Python/3.9.9
< Date: Wed, 29 Dec 2021 14:37:55 GMT
< 
* transfer closed with 20 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 20 bytes remaining to read
```

We can notice the "some-header" header is missing.

Environment:

```
❯ flask --version
Python 3.9.9
Flask 2.0.2
Werkzeug 2.0.2
```

Some real world details. I am trying to do this on a big flask applications with tens of routes (129 rules in the `MapAdapter.map._rules` object). If I explore the rules I can see my two rules: one for the GET method with GET / HEAD / OPTIONS (HEAD being added by Werkzeug, OPTIONS by Flask) and one for my HEAD method with HEAD / OPTIONS. By changing _things_ unrelated in my code (like adding an element to a list that had nothing to do with Flask or Werkzeug or even just adding `pdb.set_trace()` in some location) it seems I can have an influence on which rule will be find first by werkzeug. I didn't figured out why.

Ideally I would like a way to disable the automatically added HEAD method to my GET endpoint. This could be detected by Flask / Werkzeug or could be an option on the Flask decorator.

**Comment by Yourun-proger** [comment]
Hello, @erdnaxeli. This reminds me very much of [this discussion](https://github.com/pallets/flask/issues/4236). See [this](https://github.com/pallets/flask/issues/4236#issuecomment-898884278) comment. To put it simply, the `HEAD` is a `GET` without a body. In your case, the code should be like this:
```py
from flask import Flask

app = Flask(__name__)

@app.route("/", methods=["GET"])
def hello_world():
    return "<p>Hello, World!</p>", 200, {"some-header": "some-value"}
```
This code does exactly what you need, if I understand you correctly. I checked this locally and i see status code 200 and `some-header` with some-value in response headers.

**Comment by ThiefMaster** [comment]
@Yourun-proger, this doesn't really answer his question:

> but I want to skip the heavy computations of the GET method as the body is not needed to answer quickly with just the headers


@erdnaxeli you can always check `request.method == 'HEAD'` in your code; I think that's actually better than separate functions because besides the lack of a body HEAD *should* be identical to GET.

**Comment by Yourun-proger** [comment]
Oh! I delete the commit

**Comment by erdnaxeli** [comment]
> @erdnaxeli you can always check `request.method == 'HEAD'` in your code; I think that's actually better than separate functions because besides the lack of a body HEAD _should_ be identical to GET.

This should works but seems weird when using a [`MethodView`](https://flask.palletsprojects.com/en/2.0.x/api/#flask.views.MethodView) class.

**Comment by malwaredllc** [comment]
I submitted PR #4407 to address this issue, let me know if you have any thoughts on it.

**Comment by davidism** [comment]
I don't agree that this is an issue. `HEAD` is defined as the `GET` method without body. If you want to avoid a calculation as part of that, then you do if `request.method != "HEAD"` or similar. Werkzeug doesn't implement a separate HEAD function, it directly removes the body when generating the response.

It isn't clear how the result of a long computation would not contribute to the response headers for a GET request, since presumably you're doing that computation to GET results, which affects the content-length. If that's actually the case, it probably makes semantic sense to make that a POST request instead, since it's not a query at that point, it's kicking off a process, which is a side effect.

If you really don't want the GET route to handle the HEAD method, then you could remove the `HEAD` method from the rule after registering, or you could construct a `Rule` manually and add it.

```python
@app.route("/special")
def special():
    ...

for rule in app.url_map.iter_rules("special"):
    if rule.methods == {"GET", "HEAD"}:
        rule.methods = {"GET"}
```

```python
@app.endpoint("special")
def special():
    ...

rule = app.url_rule_class("/special", endpoint="special")
rule.methods = {"GET", "OPTIONS"}
rule.provide_automatic_options = True
app.url_map.add(rule)
```

**Comment by erdnaxeli** [comment]
> I don't agree that this is an issue. `HEAD` is defined as the `GET` method without body. If you want to avoid a calculation as part of that, then you do if `request.method != "HEAD"` or similar. Werkzeug doesn't implement a separate HEAD function, it directly removes the body when generating the response.

I think there is an issue, because this code works as expected:

```Python
from flask import Flask

app = Flask(__name__)

@app.route("/", methods=["HEAD"])
def hello_head():
    return '', 200, {"some-header": "some-value"}
```

But as soon as I add another method, it doesn't work anymore.

> It isn't clear how the result of a long computation would not contribute to the response headers for a GET request, since presumably you're doing that computation to GET results, which affects the content-length. If that's actually the case, it probably makes semantic sense to make that a POST request instead, since it's not a query at that point, it's kicking off a process, which is a side effect.

It is clear to me, the dev of the app, and that's not a side effect. For example, I may return some complexe objects for which I need to fetch geographical data using another API. In the HEAD I only want to count them (to return an header with the total count), I don't need to fetch the geographical data.
