### ISSUE TITLE
`render_error()` helper function

### ISSUE THREAD

**Issue by L0uisc** [pallets/flask#4398]
It would be nice to have a helper function which would automatically return the error as second tuple element when the decorator has an integer argument. Code in Flask as it is now:

```python
@app.errorhandler(500)
def handle_500(error):
    return render_template('500.html'), 500  # DRY violation: repeat error code from decorator.
```

How I envision it to be:

```python
@app.errorhandler(500)
def handle_500(error):
    return render_error('500.html')
```

I have no real idea how Python function decorators work, but I'd think it should be possible to change the function to call another helper, passing the error code for which the handler is registered, which then returns the tuple already packaged so that the application developer doesn't need to remember to add the status code.

Is something like this possible? I can understand if it is only going to be possible with a new major release for backwards compatibility.

**Comment by davidism** [comment]
Thanks for the suggestion, however I don't think this useful enough to add to Flask. It would require quite a few assumptions, and usually only 404 and 500 pages are rendered, so this saves minimal typing.
