### ISSUE TITLE
Typo/Bug in make_response()?

### ISSUE THREAD

**Issue by IlluminatiFish** [pallets/flask#4409]
https://github.com/pallets/flask/blob/660994efc761efdfd49ca442b73f6712dc77b6cf/src/flask/app.py#L1699-L1728

The else clause is called while trying to do the following:
```py
class LocalFlask(Flask):
    def process_response(self, response):
        response.headers['Server'] = 'TestServer/1.0'
        return response

app = LocalFlask(__name__)

class TestAPI(MethodView):
    def post(self):

        return ('Test', 'test'), 200

view = TestAPI.as_view('test_api')
app.add_url_rule('/api/upload/', view_func=view, methods=['POST',])
``` 
the return type is a tuple but the exception says that the type should be one of ``string, dict, tuple, Response instance, or WSGI callable`` so i'm not sure if this is a typo or bug

Environment:

- Python version: 3.10.0
- Flask version: 2.0.2

**Comment by davidism** [comment]
The docs for that function describe what the tuple should look like, what you've given isn't valid.

**Comment by IlluminatiFish** [comment]
> The docs for that function describe what the tuple should look like, what you've given isn't valid.

Good to know cheers
