### ISSUE TITLE
Closed Issue Still Happening

### ISSUE THREAD

**Issue by Edmartt** [pallets/flask#4418]
I read an issue some weeks ago about Flask giving no description when you run it and some error happens, this was reported as solved, but still happening in the last version even when I reported happening at that time, somebody told that in the next version some fix would be included

How to replicate:

Just make some basic mistake like an relative import or whatever you want and you'll get something like this:

* Serving Flask app './run.py' (lazy loading)

    Environment: development
    Debug mode: on
    Usage: flask run [OPTIONS]
    Try 'flask run --help' for help.

Error: While importing 'run', an ImportError was raised.

The expected behavior:
A traceback pointing possible errors

Environment:

    Python version: 3.9.9
    Flask version: 2.0.2

Note: I reported this a few days ago and mr @davidism  closed the issue without feedback or any explanation, THIS IS HAPPENING. I'm not asking help for my code, be responsable with the moderation, the community using flask is helping and we want flask to be improved in any way possible

**Comment by ThiefMaster** [comment]
I didn't check the other issues (also since you didn't link them ;)) but any change that it was fixed but simply isn't included in a release yet?

**Comment by Edmartt** [comment]
> I didn't check the other issues (also since you didn't link them ;)) but any change that it was fixed but simply isn't included in a release yet?

Is not included as they claim it is. the traceback isn't available and you need to guess what to do and solve any error, and now again the issue is closed even when I'm describing the problem

**Comment by davidism** [comment]
It seems you're aware of the previous issues. If you read them, you'll find that there was an associate merged PR and that both are marked with a release milestone. You'll also notice that that version is not out yet. You could also check the changelog, which lists it as unreleased. In the future, please spend more time reading the issues you refer to before opening multiple questions about them.
