### ISSUE TITLE
Undocumented dependency on pkg_resources

### ISSUE THREAD

**Issue by K900** [pallets/flask#4419]
The `flask` CLI uses `pkg_resources` (a part of `setuptools`) to detect plugin-provided subcommands, and fails silently when it's not available (see [here](https://github.com/pallets/flask/blob/fdac8a5404e3e3a316568107a293f134707c75bb/src/flask/cli.py#L498)). This isn't usually an issue because most environments will have pip, and therefore setuptools and pkg_resources, installed, but it does cause issues when in a hermetic environment, like Nix (see https://github.com/NixOS/nixpkgs/pull/155245) or a sufficiently fancy Docker container. It would be nice to make the soft dependency explicit, maybe as a setup.py extra, or even make it a hard dependency.

I'm not sure this fully qualifies as a bug, but I don't really know where else to report this, so here it is.

**Comment by FRidh** [comment]
if the cli should work out of the box, then setuptools needs to be in install_requires as well.

**Comment by K900** [comment]
The CLI does _work_, it just doesn't detect commands provided by third party extensions. It's definitely a very icky failure mode though.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pallets/flask/blob/fdac8a5404e3e3a316568107a293f134707c75bb/src/flask/cli.py#L494-L501  is a pain

it should at least warn
also on all modern pythons, importlib.metadata is available and should be used instead

**Comment by K900** [comment]
Actually it looks like the current version of Flask only supports 3.6 and up, so it should be possible to use `importlib.metadata` and remove the dependency entirely.

**Comment by RonnyPfannschmidt** [comment]
importlib metadata was added provisionally in 3.8 an only finalized in 3.10

so a backport would be needed to use the modern apis

**Comment by K900** [comment]
True, but I believe the official backport works on 3.4+, which was not OK before Flask dropped 2.7, but it is now.

**Comment by RonnyPfannschmidt** [comment]
https://pypi.org/project/importlib-resources/3.3.1/ supports 2.7

i believe this was mainly a oversight
