### ISSUE TITLE
Tutorial Blog Blueprint document SQL code issue

### ISSUE THREAD

**Issue by lugq1990** [pallets/flask#4422]
Hi team, 

Flask is really a great tool that I have ever used:) much thanks for your work!

After I follow the tutorial for building a blog website, I found that there is a issue for session: [Blog Blueprint Index](https://flask.palletsprojects.com/en/2.0.x/tutorial/blog/#index).

The issue is that for query SQL that if I register many users, but when to login with single user, SQL output will be a full list of posts with other users' posts.

So I think it should add `user_id` check from current session, so that could see only exactly user's posts.

```python
def index():
    db = get_db()
    user_id = session.get('user_id')
    posts = db.execute(
        'SELECT p.id, title, body, created, author_id, username'
        ' FROM post p JOIN user u ON p.author_id = u.id where u.id={} ORDER BY created DESC'.format(user_id)
    ).fetchall()
```

**Comment by davidism** [comment]
No, this is intended, a blog is public and shows all articles written by all authors. You're welcome to modify to fit your needs.
