### ISSUE TITLE
Not sanitising JSON arrays

### ISSUE THREAD

**Issue by Vishwamithra37** [pallets/flask#4427]
Flask is not sanitising arrays in JSON input like it does with normal string inputs. This is messing up my database and many more security threats could be possible.

- Make a simple route.
- Use `flask.request.get_json()` to get the input.
- Give the input with a key value pair. Where the value is an array. Ex: {"choco":["Van\nilla","Blueber\nry"]}
- Print the output.
- The values inside the arrays is not sanitised like in the regular key string pair.

```
`
import flask
app=flask.Flask(__name__)
@app.route('/api/makeapost',methods=['POST']) 
def poster():
    dat=flask.request.data
    print(dat)
    dat=flask.request.get_json()
    print(dat)`
```

I expect it to sanitise and remove everything '\\' in the arrays too.
Environment:

- Python version:3.9.6
- Flask version:2.0.2

**Comment by ThiefMaster** [comment]
You are looking a a python repr when printing this. The data doesn't contain the backslashes.

**Comment by Vishwamithra37** [comment]
> You are looking a a python repr when printing this. The data doesn't contain the backslashes.
IT does. Just test it. 
I inserted it as is in the mongoDB database and it is giving me LINE BREAKS.

**Comment by ThiefMaster** [comment]
It's not clear what you are doing. If you send `["Dow\n\n","dow\n\n", dow\n"]` in a JSON payload, then it CONTAINS LINE BREAKS. They may be printer as `\n` in the repr of the list, but the string there contains an actual linebreak

**Comment by Vishwamithra37** [comment]
> It's not clear what you are doing. If you send `["Dow\n\n","dow\n\n", dow\n"]` in a JSON payload, then it CONTAINS LINE BREAKS. They may be printer as `\n` in the repr of the list, but the string there contains an actual linebreak

Forget about \n for a second. Even \b  \f etc are going through when I parse using the 
`flask.request.get_json()`

Can you please test once?

**Comment by ThiefMaster** [comment]
There is no sanitization whatsoever. I still believe it's a bug  in your code. If you disagree, provide an executable example (e.g. a small flask app that demonstrates it AND a script that uses e.g. requests to send the json payload).
