### ISSUE TITLE
Flask 2 binds to default host address when --host=0.0.0.0 is used

### ISSUE THREAD

**Issue by diegofps** [pallets/flask#4428]
## Description

Flask ignores the parameter --host when it is equal to "0.0.0.0" and version is 2.0.x, binding to its host address.

## How to reproduce

Given the following server

```python3
from flask import Flask

# Create the http server
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"
```

Executing Flask 2.0.0, 2.0.1 or 2.0.2

```shell
# flask run --host=0.0.0.0 --port=7000
 * Environment: development
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://10.235.32.9:7000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 104-550-245
```

Executing Flask 1.1.4

```shell
root@ngd-k3s-example-6bwtc:/app# flask run --host=0.0.0.0 --port=7000
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:7000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 215-924-045
```

## Expected behavior

With the parameters used, I expected Flask 2.0.x would also bind and listen to http://0.0.0.0:7000/.

## Environments:

(1)
- Python version: Python 3.8.10
- Flask version: 2.0.1
- OS: Ubuntu 20.04.3 LTS

(2)
- Python version: Python 3.10.2
- Flask version: 2.0.0, 2.0.1 or 2.0.2
- OS: Debian GNU/Linux 11 (bullseye)

**Comment by davidism** [comment]
Try actually hitting your IP, it still works. See the line "Running on all addresses." People get confused because they didn't understand that 0.0.0.0  in the output before wasn't an actual visitable address (except in Firefox). Now we tell you what the actual address you bound to is.

Note that the only time you should run on 0.0.0.0 is when you're running the development server in Docker. You should never use the development server in production, use a production WSGI server.

**Comment by diegofps** [comment]
Indeed, now it makes sense,

I always thought of 0.0.0.0 as a way of telling "I am listening on all addresses, go enter your IP anywhere". It is now giving me the IP to connect, not telling me it is listening to all.

Anyway, IMHO, I always look for the pattern 0.0.0.0 when I need to check if a service is listening on all addresses. I guess it becomes a bit less intuitive if I need to parse a log file for a piece of information like "Running on all addresses.", which is not standard for all programs. For instance, when I play with Spark, the output log is huge, but visually finding 0.0.0.0 is really easy.

But that is a design consideration, I am sure your team considered plenty of things. 
Thank you for the fast reply :)
