### ISSUE TITLE
Flask Parameter is rounded up in Javascript

### ISSUE THREAD

**Issue by Vinyzu** [pallets/flask#4430]
Python code:
```py
from flask import Flask, render_template
app = Flask(__name__)

@app.route("/")
def test():
    id = "2138291837273817238" # Can Be some random number
    return render_template("first.html", id=id)

if __name__ == "__main__":
    app.run("0.0.0.0", 8000)
```
Html:
```html
<!DOCTYPE html>
<html>
<title>Testing</title>
<body style="background-color:#222736;">
<h1 style="color:#f6f6f6">Testing</h1>
</body>

<script>
console.log({{ id }})
</script>
</html>
```
Javascript console:
> 2138291837273817300

As you can see, `2138291837273817238` and `2138291837273817300` are not the same number. The parameter is always rounded up at the 17th number.
Is this just a JavaScript error?
Am I doing something wrong?
And can someone reproduce this?

Environment:

- Python version: 3.10.1
- Flask version: 2.0.2

**Comment by ThiefMaster** [comment]
You are passing a literal number to JavaScript, so if JavaScript can't handle that number then this can happen.

Maybe you want to pass it as a string since you have a string in Python as well?

```
console.log({{ id | tojson }})
```

Also, this is the wrong place for questions about your own code. The next time please use our Discord or GitHub discussions instead of an issue for this.

**Comment by Vinyzu** [comment]
Sorry, yes i wanted it to be a string, the solution was a easy 
console.log("{{ id }}")
Sorry for the inconvenience :/!

**Comment by ThiefMaster** [comment]
You should use `tojson` since that will work with anything even if your string contains weird characters, while just putting it in quotes would fail e.g. in case the string contains a quote as well.
