### ISSUE TITLE
First Tutorial Step Returns 404

### ISSUE THREAD

**Issue by and-viceversa** [pallets/flask#4431]
I'm trying to run the first step of the [tutorial](https://flask.palletsprojects.com/en/2.0.x/tutorial/factory/).

I've got the correct directory setup, and `flaskr/__init__.py` like
```
import os

from flask import Flask


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    @app.route('/hello')
    def hello():
        return 'Hello, World!'

    return app
```

```
export FLASK_APP=flaskr
export FLASK_ENV=development
flask run
 * Serving Flask app 'flaskr' (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 866-997-541
```

Both  http://127.0.0.1:5000/ and  http://127.0.0.1:5000/hello return 404. Sorry for the noob issue, but what's going on here?

Environment:

Python 3.9.7
Flask 2.0.2
Werkzeug 2.0.2

Browser Firefox
shell `zsh`
IDE PyCharm
OS macOS 11.6.1

What's odd to me is that adding another simple route works just fine.
```
    @app.route('/about')  # http://127.0.0.1:5000/about works just fine
    def about():
        return 'About Page'
```

**Comment by davidism** [comment]
I know the tutorial works, and the code you've shown works for me, so it sounds like you may have missed a step somewhere. Compare your code to the finished example https://github.com/pallets/flask/tree/2.0.x/examples/tutorial. You can ask for help on our Discord questions channel https://discord.gg/pallets.
