### ISSUE TITLE
github_link uses suboptimal shortcut

### ISSUE THREAD

**Issue by ggzel** [pallets/flask#4433]
On Line 91 of root/docs/conf.py, it says `options = options or {}`

It is trying to use the fact that options is initialized to None, which is falsy, to then initialize it to {}. 

However, this means that if you call github_link with options being some other falsy value (0, for example), rather than giving an error,  it will quietly initialize it to {}. This could potentially hide a bug in a caller of the function. 

An easy fix would be to replace it with: 
`if options is None:
     options = {}`

You can replicate the bug by simply calling github_link with options = 0. 

The expected behavior would be for the function to give an error. Instead, it silently corrects it to {}. 

Environment:

- Python version: Any
- Flask version:  Latest (2.0.2)

**Comment by davidism** [comment]
This is just a helper function for the docs, it's not intended to be used by others, and it seems to be working correctly currently.
