### ISSUE TITLE
Use `render_template("...", as_string=True, **ctx)` instead of `render_template_string("...", **ctx)`

### ISSUE THREAD

**Issue by Yourun-proger** [pallets/flask#4447]
Hello!
I looked at the code of these functions, it is very similar and differs little. It seems to me that it's too cumbersome to have one more function, it's easier to just add the `as_string` (or something like this) parameter, which will take the first parameter not as a path to a file, but as a string for templating. For compatibility up to version 2.1, you can leave this function and throw a deprecation warning.

Well, this is exactly what is described in the title. As an example:
```py
from flask import Flask, render_template

app = Flask(__name__)

@app.route('/')
def index():
    return render_template("index.html")
@app.route('/hello/<name>')
def hello(name):
    return render_template("<p1> Hello {{ name }} </p1>", as_string=True, name=name)
```
I think it is clear that the code is maximally simplified and exaggerated, so you should not go into implementation details. The main thing is that the principle of change is reflected here.

I looked at the code of these functions, it is very similar and differs little. It seems to me that it's too cumbersome to have one more function, it's easier to just add the `as_string` (or something like this) parameter, which will take the first parameter not as a path to a file, but as a string for templating. For compatibility up to version 2.1, you can leave this function and throw a deprecation warning.
The only negative that I see is the problem with type hints. However, this is probably not a barrier. 
Say what you think about it. If you like my way of thinking, I could take this feature on.

**Comment by ThiefMaster** [comment]
No, I don't think this is a good idea at all.

- both render functions take arbitrary kwargs to pass to the underlying template, so any additional kwarg would be a breaking change
- rendering from a file is much more common than rendering from a string, so it justifies separate functions as well

**Comment by Yourun-proger** [comment]
Well, yes, it is reasonable. Thank you!
