### ISSUE TITLE
Enhancement: rst `tabs` and `group-tab` directives are not properly rendered on git hub.

### ISSUE THREAD

**Issue by Harmouch101** [pallets/flask#4462]
The content of the `CONTRIBUTING.rst` is rendered as shown below:

![Screenshot from 2022-02-23 18-45-06](https://user-images.githubusercontent.com/62179149/155367897-9b68d479-c891-47eb-8866-3eab046ab22c.png)

 It seems like the GitHub renderer is not able to display it properly. I would suggest replacing `tabs` with collapsible sections:

![Screenshot from 2022-02-23 18-42-47](https://user-images.githubusercontent.com/62179149/155368720-add76675-3441-4150-9e23-193409912fa4.png)

![Screenshot from 2022-02-23 18-43-11](https://user-images.githubusercontent.com/62179149/155368945-94c433c0-0cf0-4102-9fff-1ea1f996eb64.png)

I am happy to open a PR to resolve the issue.

**Comment by davidism** [comment]
Thanks, however I'm prioritizing rendering in our docs over rendering on GitHub.
