### ISSUE TITLE
docs: 'Sending Requests with the Test Client' references non-existent 'query' parameter

### ISSUE THREAD

**Issue by usrme** [pallets/flask#4464]
In the [Sending Requests with the Test Client](https://flask.palletsprojects.com/en/2.0.x/testing/#sending-requests-with-the-test-client) section of the documentation it's said that:

> The `client` has methods that match the common HTTP request methods, such as `client.get()` and `client.post()`. They take many arguments for building the request; you can find the full documentation in [EnvironBuilder](https://werkzeug.palletsprojects.com/en/2.0.x/test/#werkzeug.test.EnvironBuilder). Typically you’ll use `path`, `query`, `headers`, and `data` or `json`.

And also:

> Pass a dict `query={"key": "value", ...}` to set arguments in the query string (after the ? in the URL). Pass a dict `headers={}` to set request headers.

But looking at the linked [EnvironBuilder class](https://werkzeug.palletsprojects.com/en/2.0.x/test/#werkzeug.test.EnvironBuilder) it's clear that there is no `query` parameter, but rather `query_string`, which does not take a `dict`. Passing `query` instead of `query_string` will result in the following error being thrown:

```text
TypeError: __init__() got an unexpected keyword argument 'query'
```

I only ran into this because I was following the documentation and didn't think to double-check the API reference.

Environment:

- Python version: 3.9.10
- Flask version: 2.0.1

**Comment by davidism** [comment]
Yep, that was a typo, it should be query_string. Despite the name, it does accept a dict.

**Comment by usrme** [comment]
Oh, my bad about it not accepting a dictionary. Should I prepare a pull request with the typo change?

**Comment by davidism** [comment]
Sure, that would be helpful :+1:
