### ISSUE TITLE
TaggedJSONSerializer doesn't round-trip naive datetimes

### ISSUE THREAD

**Issue by marksteward** [pallets/flask#4466]
Since https://github.com/pallets/werkzeug/commit/265bad7, `parse_date` always returns an aware datetime. This can't be compared with naive datetimes, so will break a bunch of existing code.

```
>>> from flask.json.tag import TaggedJSONSerializer
>>> s = TaggedJSONSerializer()
>>> datetime.utcnow()
datetime.datetime(2022, 2, 25, 1, 52, 43, 79586)
>>> s.loads(s.dumps(datetime.utcnow()))
datetime.datetime(2022, 2, 25, 1, 52, 44, tzinfo=datetime.timezone.utc)
```

This probably makes sense for werkzeug, but not for a JSON serialiser.

It might be enough to replace the calls to `http_date` and `parse_date` with `value.isoformat()` and `datetime.fromisoformat(value)`, which will work fine for aware and naive datetimes.

Environment:

- Python version: 3.9
- Flask version: 2.0.2

**Comment by marksteward** [comment]
Happy to PR this as long as it makes sense.

**Comment by davidism** [comment]
That was an intended change, I don't plan to revert it. You can register a different tag for datetimes if you need different behavior in your application.

```python
from flask.json.tag import TagDateTime

class TagNaiveDateTime(TagDateTime):
    __slots__ = ()

    def to_python(self, value):
        return super().to_python(value).replace(tzinfo=None)

app.session_interface.serializer.register(TagNaiveDateTime, force=True)
```

**Comment by marksteward** [comment]
Ahh thanks for the link, I hadn't seen that. Naive datetimes still have uses (e.g. recurring events), but I get why you'd want to force users into including a timezone.

I guess I should be using a pickle-based serialiser for session instead.

**Comment by davidism** [comment]
> I guess I should be using a pickle-based serialiser for session instead.

No, that is absolutely not the conclusion you should reach based on this. The PR, the docs added by the PR, and the example I showed all explain how to address this.

**Comment by marksteward** [comment]
I also found that dicts with numeric keys don't round-trip:

```
>>> s.loads(s.dumps({1: 1}))
{'1': 1}
```

I don't want to have to write an encoder and decoder every time we add something new to a session. I want a cookie-based container we can put things in and get them back. The cookies are signed, so I think this is a perhaps rare case where pickle is appropriate.
