### ISSUE TITLE
`app.route` and similar decorators can have better types

### ISSUE THREAD

**Issue by tusharsadhwani** [pallets/flask#4476]
Currently, `@app.route` creates a decorator function that takes in a `t.Callable` and returns a `t.Callable`.

This leads to type erasure:

```python
import flask

def foo() -> bool:
    return True

reveal_type(foo)

app = flask.Flask(__name__)

@app.route('/bar')
def bar() -> bool:
    return True

reveal_type(bar)
```

```console
$ mypy mycode.py
mycode.py:6: note: Revealed type is "def () -> builtins.bool"
mycode.py:14: note: Revealed type is "Any"
```

Although the function still works the same way:

```pycon
>>> foo()
True
>>> bar()
True
```

Replacing `t.Callable` in the code with a bound `TypeVar` should allow mypy to infer that the decorator shouldn't change the types of the function.

**Comment by davidism** [comment]
Happy to review a PR.
