### ISSUE TITLE
`flaskr` docs use raw SQL statements in SQLAlchemy

### ISSUE THREAD

**Issue by torbendury** [pallets/flask#4489]
Hello everyone and thanks for this project, especially the fantastic documentations!

In [this part of the documentation](https://flask.palletsprojects.com/en/2.0.x/tutorial/views/#the-first-view-register), the `flaskr` example application handles authentication mechanisms by inserting new users / authenticating existing users by connecting to a SQLite database. It uses raw string statements to register new users and/or authenticate them.

Of course, this is an example application, but SQLAlchemy offers database statements as objects which have several benefits as:

- SQL injection safety
- Database actions _as code_

The tutorial does in this case not show the optimal code regarding database statement executions. 

New(er) programmers might not just make their first steps in web application programming using Python Flask, but maybe even make their first steps connecting to a database. I'd propose to rather use a code snippet similar to this:

```python
# code snippet for registering a new user
users = Table('users', metadata, autoload=True)
stmt = users.insert()
stmt.execute(username=username, password=generate_password_hash(password))
```

This way, one does not think about writing raw SQL statements and writes safe code by default.

Thank you and have a nice day!

**Comment by ThiefMaster** [comment]
It's not using sqlalchemy at all: https://flask.palletsprojects.com/en/2.0.x/tutorial/database/

**Comment by torbendury** [comment]
Wow, how could I overlook that. Enough for today.

Thanks for clarifying anyway!
