### ISSUE TITLE
Sessions not fully encoded?

### ISSUE THREAD

**Issue by Gowixx** [pallets/flask#4490]
Are the contents of the session cookie really safe?

Hey there, I was browsing around with the flask sessions, and I got interested. I put the session into a base64decoder, and the exact contents where right there. Is there no other way to approach this issue? Is it really safe as everything before the dot is just base64 encoded?

Is it possible to also encode the contents of the cookie in a secure way, such that only the server can have the contents?

**Comment by davidism** [comment]
The session cookie is signed to prevent modification, not encrypted to prevent inspection.

**Comment by Gowixx** [comment]
Is it possible to make it encrypted?
