### ISSUE TITLE
Flask 2.1.0 can't handle request method properly when sending POST repeatedly with an empty body

### ISSUE THREAD

**Issue by tangbinyeer** [pallets/flask#4507]
With the following example:

```python
from flask import Flask

app = Flask(__name__)


@app.route('/', methods=['POST'])
def hello_world():
    return 'Hello World!'


if __name__ == '__main__':
    app.run()
```
When you set the request body to `{}` with Postman or any HTTP clients, the first request will return 200, while the second request will return a 405 error response. The log shows the request method is `{}POST`:

```
"{}POST / HTTP/1.1" 405
```

Notice the request body became the part of the request method.

**Comment by ThiefMaster** [comment]
Why do you think we understand/speak chinese?

Anyway, your client code is clearly broken, since it seems to be using `{}POST` as the HTTP verb instead of `POST`...

**Comment by tangbinyeer** [comment]
You can try to build a project with the latest version of Flask (2.1.0), your starter example code changes the methods to POST, then use postman to send the request, set the body and set the header Connection: keep-alive, and send the POST request multiple times . You will see the log as above, the request method was handled incorrectly. But if you remove the header Connection:keep-alive, there is no problem.
It is suspected that this is incorrect handling of long connections.
Sorry, the above is from google translate.

**Comment by tangbinyeer** [comment]
Try further, if I use request.json in the code to get the request body data, the program does not report an error。

**Comment by davidism** [comment]
There have been previous discussions about this, but with form data instead of JSON. The Werkzeug development server is not particularly robust, it does not handle draining the input stream if it's not actually consumed in the view function. Any production server will handle this, or you can make sure to read the body in a view that expects a body: ``request.get_json()``, for example.

**Comment by crono782** [comment]
Here is a simplified example showing that simple form handling is now broken. Seems like it is trying to pass stale data to the redirected view.

app.py
```python
from flask import Flask, render_template, redirect, url_for
from flask_wtf import FlaskForm
from wtforms import SubmitField

app = Flask(__name__)
app.config['SECRET_KEY'] = 'dummykey'

# FORM
class EmptyForm(FlaskForm):
    submit = SubmitField('Submit')

# VIEWS
@app.route('/')
def index():
    return 'hello world'

@app.route('/form', methods=['GET', 'POST'])
def form():
    eform = EmptyForm()
    return render_template('form.html', eform=eform)

@app.route('/formhandler', methods=['POST'])
def handler():
    # do some processing
    
    return redirect(url_for('index'))
```

form.html
```html
<html>
<body>
    <form action="{{url_for('handler')}}" method="POST">
    {{eform.hidden_tag()}}
    {{eform.submit}}
    </form>
</body>
</html>
```

When clicking the empty form submit button, I now see this:
```bash
127.0.0.1 - - [31/Mar/2022 17:03:42] "GET /form HTTP/1.1" 200 -
127.0.0.1 - - [31/Mar/2022 17:03:43] "POST /formhandler HTTP/1.1" 302 -
127.0.0.1 - - [31/Mar/2022 17:03:43] "csrf_token=ImQ1MTZiODI0ZTRkZDc4YTdkY2U3MTc1ODM3OWZjYmViMzg0M2VjNWUi.YkYlPg.tygGNlynY3FN87lE8SqM_YWG2ZQ&submit=SubmitGET / HTTP/1.1" 405 -
```

pip freeze
click==8.1.2
Flask==2.1.1
Flask-WTF==1.0.1
importlib-metadata==4.11.3
itsdangerous==2.1.2
Jinja2==3.1.1
MarkupSafe==2.1.1
Werkzeug==2.1.0
WTForms==3.0.1
zipp==3.7.0

This same setup worked not too long ago.

**Comment by davidism** [comment]
This will addressed by https://github.com/pallets/werkzeug/issues/2397, but reconsider why you're making a post request with data then not reading that data. Also note that the development server is not intended for production. Any production WSGI server handles this correctly already.
