### ISSUE TITLE
Location header relative rather than absolute URI.

### ISSUE THREAD

**Issue by toonarmycaptain** [pallets/flask#4514]
Flask renders  `response.headers['Location']` as relative rather than absolute path.

I have a bunch of failing tests moving from 2.0.3 to 2.1.x fitting this pattern:
```python
    def test_base_url_redirects_to_home(test_client, test_app):
        """Base url should go to home page."""
        response = test_client.get('/')
        assert response.status_code == 301
>       assert response.headers['Location'] == 'http://localhost/home/'
E       AssertionError: assert '/home/' == 'http://localhost/home/'
E         - http://localhost/home/
E         + /home/
```
Where the underlying route is:
```python
@bp.route('/', methods=['GET'])
def base_url():
    """Redirect bare url to home page."""
    return redirect(url_for('my_site.home'), code=301)
```

These tests were passing before the version bump, with no changes to application code. 
An interesting wrinkle is that tests still pass on Ubuntu in github actions, but not Windows. 

Environment:

- Python version: 3.8, 3.9
- Flask version: 2.0.3, 2.1.0, 2.1.1

My understanding (which may be flawed) is that this is a Flask behavioral change, and that spec would be for the header to contain an absolute URI.  Feel free to correct me if I'm wrong.

**Comment by davidism** [comment]
This is intentional, and follows the HTTP spec. The location header does not need to be absolute to scheme, domain, or path. https://github.com/pallets/werkzeug/issues/2352

**Comment by toonarmycaptain** [comment]
Ah ok. My search lead me to references to the older spec. Thanks :)
