### ISSUE TITLE
Argument 1 to "loads" has incompatible type "bytes"; expected "str"

### ISSUE THREAD

**Issue by karmingc** [pallets/flask#4519]
From the [documentations](https://docs.python.org/3/library/json.html#json.loads), json.loads accepts bytes as an argument, so i'm not sure what's the reasoning behind flask.json annotating it to `str` only. https://github.com/pallets/flask/blob/main/src/flask/json/__init__.py#L156. As a result, mypy is raising an error.

Is this correct?

```python
import requests
from flask.json import loads

# Making a get request
response = requests.get('https://api.github.com')

# With response.content
loads(response.content)
Argument 1 to "loads" has incompatible type "bytes"; expected "str"

# With response.text
loads(response.text)
No issue
```

Environment:

- Python version: 3.8x
- Flask version: 2.1x

**Comment by davidism** [comment]
Happy to review a PR that improves the accuracy of type annotations.

**Comment by rzimmerdev** [comment]
It seems the documentation for the [flask.json](https://github.com/pallets/flask/blob/main/src/flask/json/__init__.py#L156) module also agrees with you. The input parameter is restricted to a string, even though the loading function is actually just `json.loads`.

I'll happily open a new pull request to fix this.
