### ISSUE TITLE
test_cli_runner() does not work as demonstrated in the documentation

### ISSUE THREAD

**Issue by MeViMo** [pallets/flask#4525]
In the documentation for 2.0.x forward, the use of the `.invoke()` method is showcased like so:
[`runner.invoke(["hello", "--name", "Flask"])`](https://flask.palletsprojects.com/en/2.1.x/testing/#running-commands-with-the-cli-runner).

However, the first positional argument to `.invoke()` is the command object:
[`def invoke(self, cli: t.Any = None, args: t.Any = None, **kwargs: t.Any ) -> t.Any:`](https://github.com/pallets/flask/blob/f59574f61198f139616868393db8785bcf9e0fdf/src/flask/testing.py#L261=)
So usage as described by the documentation won't work.
I'm quite confused as to why the documentation was changed when the method was never altered.

I suggest either the documentation be changed or the position of `cli` and `args` be switched.

**Comment by davidism** [comment]
Happy to review a PR that changes it to `invoke(args=[...])`, looks like I forgot to write the keyword in front.
