### ISSUE TITLE
Fuzzing integration by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [pallets/flask#4538]
Hi,

Given the popularity of flask I was thinking that it would be nice to set up continuous fuzzing of flask by way of OSS-Fuzz. In this PR: https://github.com/google/oss-fuzz/pull/7542 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate flask. This includes developing an initial two fuzzers as well as the necessary glue for working with OSS-Fuzz. Down the line it is preferable to have the fuzzers upstream but it can be convenient to have on OSS-Fuzz to begin with.

Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid. The fuzzing set up on the OSS-Fuzz side relies on Atheris fuzzer to perform the fuzzing.

If you would like to integrate, the only thing I need is as list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by davidism** [comment]
Thanks, this looks interesting, however I don't have the time to manage another service like this. I know Google uses our projects extensively internally and externally, and I'd be happy to accept PRs their employees find as part of this program, all contributions are welcome. :-) Thank you.

---

That's the third time I've left that exact response to you @DavidKorczynski (https://github.com/pallets/jinja/issues/1318, https://github.com/pallets/werkzeug/issues/2011). Was something unclear the last time? It seems like you're just spamming automated PRs with no commitment, rather than putting thought into each OSS contribution you're making. I am open to contributions from Google, but a multi-billion dollar company can surely support the most used packages in the Python ecosystem more directly and thoughtfully than this.

**Comment by DavidKorczynski** [comment]
Hi @davidism -- thanks for your reply!

Sorry if it came off as spamming -- that's certainly not my intention! I manage a lot of OSS-Fuzz integrations and lost track of our messages from Werkzeug and Jinja integrations. Many apologies!

**Comment by davidism** [comment]
Do you have any response to the rest of the message? I'm interested in the project, but not as an external dashboard with limited availability, not without a demonstration of what the findings look like and are responded to, and not without commitment to continue to contribute. Your current approach does not seem helpful to maintainers who are already overworked and understaffed.

**Comment by DavidKorczynski** [comment]
- wrt external dashboard:
The way OSS-Fuzz works is by sending emails out when an issue is found to monorail issues, e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43654 which itself has links to a more detailed report on https://oss-fuzz.com where you find reproduce testcase, stack trace and more. Testcase in this case refers to the input needed for the fuzzer to trigger the given bug. By default reproducing the bug is straightforward using the oss-fuzz infrastructure (i.e. specific docker images that set's up the OSS-Fuzz environment), but, we can also set it up such that the fuzzers are locally in the flask repository and can be run without the use of the oss-fuzz environment.

OSS-Fuzz has recently released features for submitting bugs found as Github issues, so as of very recently you can get the issues directly in the issue tracker. However, I am not 100% sure about the details of this (I can check up for you if you'd be interested in this).

- wrt findings:
This various from language to language and the implementation of the fuzzers. By and large Python fuzzing is quite new and relies on atheris: https://github.com/google/atheris . So far, the findings in Python projects is centred around finding uncaught exceptions. This is useful to catch potential DOS issues. However, it's possible to design the fuzz tests in a manner similar to property-testing, which can help find more diverse issues. This requires a bit deeper understanding of the project being analysed though (from the perspective of the one writing the fuzz tests). 

The fuzzers can also be integrated to be run as part of the CI (https://google.github.io/oss-fuzz/getting-started/continuous-integration/) which can assist in catching bugs before they are merged into the project.

- wrt commitment:
I'm happy to commit to supplying more fuzzers to the project and assist in the root-cause analysis / bug finding. FYI I do this for many projects on OSS-Fuzz.
