### ISSUE TITLE
Flask allows register functions with same name for `before_request` functions

### ISSUE THREAD

**Issue by Yourun-proger** [pallets/flask#4547]
# Bug
Flask allows you to register multiple times a function with the same name when using the `before_request` decorator. 
Is that how it's intended? I tried to find something on this issue in docs, but couldn't.

# Minimal reproducible example
Code:
```py
from flask import Flask

app = Flask(__name__)

@app.route('/')
def main():
    return "42"

@app.before_request
def f():
    print('hi')

@app.before_request
def f():
    print('hi again')

app.run()
```
Console log:
```cmd
(env) C:\X\x\Project>py my_app.py
 * Serving Flask app 'my_app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
hi
hi again
127.0.0.1 - - [21/Apr/2022 22:17:40] "GET / HTTP/1.1" 200 -
```

# Expected behavior
Flask will throw an error like it does when you try to do the same for the `route` decorator
# Environment
- Python 3.8.2
- Flask 2.1.1
- Werkzeug 2.0.2

**Comment by ThiefMaster** [comment]
For route functions the name matters, for `before_request` it doesn't... so there's no problem in using the same function name more than once.

**Comment by Yourun-proger** [comment]
Oh. Okay. Thank you!
