### ISSUE TITLE
asserts with `pytest.raises` should be outside the `with` block

### ISSUE THREAD

**Issue by jaltmayerpizzorno** [pallets/flask#4553]
I've been using Flask's test suite to evaluate our [Slipcover](https://github.com/plasma-umass/slipcover) coverage tool and noticed likely bugs in the Flask tests.  For example, in `tests/test_basic.py`, you have

```python
def test_response_type_errors():
    [...]

    with pytest.raises(TypeError) as e:
        c.get("/none")
        assert "returned None" in str(e.value)
        assert "from_none" in str(e.value)

    with pytest.raises(TypeError) as e:
        c.get("/small_tuple")
        assert "tuple must have the form" in str(e.value)

    [...]

    with pytest.raises(TypeError) as e:
        c.get("/bad_type")
        assert "it was a bool" in str(e.value)
```
You probably don't want the `assert` statements checking `e` indented, as they won't execute when the exception is thrown.

**Comment by jpassaro** [comment]
seems like https://github.com/pallets/flask/commit/b05a685a03a2a186cd7ffb45a6cb8a7a4fbc49de introduced a lot of these

**Comment by davidism** [comment]
Always happy to review PRs to improve tests.

**Comment by qingpeng9802** [comment]
Just give an idea. Note part of [pytest-raises](https://docs.pytest.org/en/6.2.x/reference.html#pytest-raises) mentioned this hazard.

**Comment by davidism** [comment]
Always happy to review PRs to improve tests.
