### ISSUE TITLE
Flask server doesn't work when I import it from another file

### ISSUE THREAD

**Issue by JosephFrankFir** [pallets/flask#4562]
### Discussed in https://github.com/pallets/flask/discussions/4530

When I make a file for example web.py
web.py
```py
from flask import Flask
from flask import render_template

app = Flask(__name__)
@app.route('/')
def index():
    return render_template('index.html')

def start_server():
    app.run(host='0.0.0.0', debug=True) 
```
Then make a new file, for example, let's call it main.py 
main.py

```py
from web import start_server

start_server()
print("The server is running at port 5000")
```

When I run main.py in theory it must work, but
It doesn't

![image](https://user-images.githubusercontent.com/74981187/162972566-40bb7174-a5da-4a6c-b790-6f118c7f2b61.png)

Environment:

- Python version: 3.9.12
- Flask version: 2.0.1
</div>

**Comment by davidism** [comment]
I can't reproduce this with the information provided. Starting the dev server is then accessible from the location that the dev server outputs during startup.

Note that the development server is not intended for production. Your code and screenshot suggests you are using it to serve outside your local computer. The development server and debugger is not particularly secure, stable, or efficient. Use a production WSGI server such as Gunicorn, Waitress, mod_wsgi, or uWSGI to serve your application in production.
