### ISSUE TITLE
Move `abort` to the `Flask` app object

### ISSUE THREAD

**Issue by davidism** [pallets/flask#4567]
Add an `abort` method to the `Flask` app object. Similar to functions like `flask.json.dumps`, `flask.abort` should look for a `current_app` and call its `abort` method. This will allow applications to override the abort behavior.

**Comment by davidism** [comment]
Possibly add it to `Scaffold`, although I'm not sure if it makes sense for a specific blueprint to override the behavior.

**Comment by dzcode** [comment]
I'm at the sprint - would be interested in working on this if it's still open

**Comment by davidism** [comment]
I was starting to be a little unsure about whether having `app.make_aborter` was the right way to go, then I found my comment from 2017 proposing the same thing: https://github.com/pallets/flask/issues/1837#issuecomment-294289517, and I even closed an issue about it before https://github.com/pallets/flask/pull/2484.

**Comment by davidism** [comment]
`Scaffold._get_exc_class_and_code` is a `staticmethod` that looks at `werkzeug.exceptions.default_exceptions` to find the class to register an error handler by status code. Even if it weren't static, it's still `Scaffold`, and I'm not prepared for these types of methods to be overridden at the `Blueprint` level.

What this means is that even if you customize `app.aborter`, its mapping won't be used to look up a custom code like `@errorhandler(900)`, you'd still need to do `@errorhandler(My900Error)` instead. And even if we fixed it for `Flask`, `Blueprint` doesn't have access to `app.aborter` when registering handlers.

I'm fine with this, it's already raising a clear error about using a subclass instead of the code. Just commenting here so I have some reference years later again.
