### ISSUE TITLE
Unify `setupmethod` behavior between `Flask` and `Blueprint`

### ISSUE THREAD

**Issue by davidism** [pallets/flask#4571]
Many of the methods in the `Flask` app object are decorated with `setupmethod`, which prevents registering things with the application after it starts running. A similar behavior is in `Blueprint`, we want to prevent modifying it after registering it at least once. However, the blueprint checking is much less consistent, it's divided up into two parts, is only a warning sometimes, and has a different message. Figure out how we can make `Flask` and `Blueprint` more consistent with this error.

**Comment by hallacy** [comment]
@davidism I can start on this one

**Comment by davidism** [comment]
I also noticed that setting `app.debug`, `ConfigAttribute`, and `app.config` keys, could also reasonably be considered setup. I haven't applied a warning or error to these yet, but it's something to think about. It's a little more complicated because technically config should be finished as soon as the extension that uses it (or the app) is initialized. There are also other things, such as template config that shouldn't change after `app.jinja_env` is accessed, or static URL config after the static route is added.
