### ISSUE TITLE
test typing

### ISSUE THREAD

**Issue by davidism** [pallets/flask#4574]
Add a `typing_examples.py` file that has examples of different uses of Flask with type annotations. For example, show examples of views that return each valid return type for a view. We can run mypy against this to check that *using* Flask passes typing, not just the internal type checking.

**Comment by davidism** [comment]
See structlog for an example: https://github.com/hynek/structlog/blob/main/typing_examples.py

**Comment by lecovi** [comment]
Ok, I think I can handle this. Let me get this straight first:
You want a `typing_examples.py`, let's say inside the [examples](https://github.com/pallets/flask/tree/main/examples) directory, that shows a Flask App with differents [View](https://github.com/pallets/flask/blob/main/src/flask/views.py) types for help users to understand how to type their applications. Am I correct?

**Comment by davidism** [comment]
Yes, and probably other things like registering error handlers, before_request functions, etc. The application itself doesn't have to make much sense, it just has to be something we can run mypy against.

cc @hynek

**Comment by hynek** [comment]
Yeah to be clear: that code doesn't have to be executable at all. Use nonsense values! They just have to have correct types.

**Comment by lecovi** [comment]
Awesome! I will give it a shot If you let me 😉

**Comment by davidism** [comment]
Looks like `@route` is never type checked because MyPy ends up treating the `TypeVar("F", bound=t.Callable[..., ResponseReturnValue])` pattern as `def (Any) -> Any`, which always validates. I'll have to report this to MyPy.

**Comment by davidism** [comment]
We've now merged in some initial tests for `@app.route` and `@app.errorhandler`. I'll close this now, although I welcome anyone to add more typing tests for other parts of the code.
