### ISSUE TITLE
conda-forge package information is outdated

### ISSUE THREAD

**Issue by davidism** [pallets/flask#4584]
I noticed that the Conda-Forge versions of the Pallets libraries have out-of-date metadata compared to what we publish on PyPI. Each one is a GitHub repository that accepts PRs. For example, Flask:

* https://anaconda.org/conda-forge/flask
* https://pypi.org/project/Flask
* https://github.com/conda-forge/flask-feedstock

**Comment by polkapolka** [comment]
Hey, I am working on this during the pycon2022 sprint!

**Comment by polkapolka** [comment]
https://github.com/conda-forge/flask-feedstock/pull/36

**Comment by polkapolka** [comment]
https://github.com/conda-forge/markupsafe-feedstock/pull/28
https://github.com/conda-forge/itsdangerous-feedstock/pull/16
https://github.com/conda-forge/werkzeug-feedstock/pull/32
https://github.com/conda-forge/jinja2-feedstock/pull/31
https://github.com/conda-forge/click-feedstock/pull/42

**Comment by xylar** [comment]
Thanks for doing this clean-up.  It's really easy to lose track of these things over the years.

**Comment by davidism** [comment]
All merged now, thank you!
