### ISSUE TITLE
Error: read ECONNRESET while calling API with misleading headers

### ISSUE THREAD

**Issue by shayantabatabaee** [pallets/flask#4597]
Hi, 

I've tried to validate request based on existence or values of request headers, and if the conditions did not meet reject the request with some errors. 
The validation of body works perfect but when I try to validate headers suddenly connection drops.
I used `before_request` method to add interceptor to a blueprint. I tested API with Postman and Android application. In both apps connection drops (android received 'broken pipe' error and postman received Error: read ECONNRESET)
It seems that problem is related to something that mentioned in this issue:
https://github.com/postmanlabs/postman-app-support/issues/5365

here is some code to reproduce issue :

<pre>
def __validate_request_headers():
    try:
        x_request_id = request.headers['X-Request-Id']
        platform = request. headers['Platform']
        client_version =  request.headers['Client-Version']
    except Exception as e:
        raise AttributeError()

blueprint.before_request(__validate_request_headers) 
</pre>

And here is my error handling :
<pre>
def handle_exception(exception: Exception):
    return "error", 400
</pre>

If I put a break point inside `execute` method inside `serving.py` file in werkzeug library in line :
<pre>
                if hasattr(application_iter, "close"):
                    application_iter.close()  # type: ignore
</pre>
client received the error but if I run without breakpoint the connection hang up by server.

Environment:

- Python version: 3.7.4
- Flask version: 2.1.1

Thanks in advance

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided.

**Comment by shayantabatabaee** [comment]
Thanks for your response, I could reproduce issue with this code, I share the postman collection and the sample code of projects. It seems if the request is too large (around 500kb) the ECONNRESET error will received on postman. 
here is the link of code and the postman collection,
https://1drv.ms/u/s!ApUt6jL522-Pgd1TtGV5dnys_OXIaw?e=fwiu8t
please kindly review
