### ISSUE TITLE
callback types should use `bound` type vars instead of base types

### ISSUE THREAD

**Issue by f3ndot** [pallets/flask#4600]
* Flask 2.1.2
* Python 3.9.12
* mypy 0.950 (tested also 0.910)

For this type definition on `after_request`:

https://github.com/pallets/flask/blob/bd56d19b167822a9a23e2e9e2a07ccccc36baa8d/src/flask/typing.py#L39

It generates this mypy error:

```
error: Argument 1 to "after_request" of "Scaffold" has incompatible type "Callable[[Arg(Response, 'response')], Response]"; expected "Callable[[Response], Response]"
```

For the sample code of:

```python3
from flask import Flask, Response

def my_func(response: Response) -> Response:
    print("my after request func")
    return response

app = Flask(__name__)
app.after_request(my_func)  # <-- type error
```

This code works just fine, and did not generate typing errors for Flask 2.0.2

**Comment by davidism** [comment]
Please open this against MyPy first. It looks like they're treating your function as a named argument callable and not matching that to the basic callable in Flask's annotation.

**Comment by mwchase** [comment]
I had a look at this, and I think it's the fact that `flask.typing` defines a response as a `werkzeug.wrappers.response.Response`, and this code is passing a `flask.wrappers.Response`.

So, Mypy should be clearer, but this is a legitimate mismatch as written.

**Comment by davidism** [comment]
Flask's `Response` is a subclass of Werkzeug's.

**Comment by mwchase** [comment]
So, `after_request` wants to receive a function that accepts the base class (from werkzeug), but it's receiving a function that is annotated as accepting the subclass (from flask).

**Comment by davidism** [comment]
OK, so the problem is that anything that's annotated with `werkzeug.Response` should actually be annotated with a `TypeVar("ResponseType", bound=werkzeug.Response)`. And this might apply to some other callback annotations as well.

Happy to review a PR.
