### ISSUE TITLE
Unread multipart form input generates error output

### ISSUE THREAD

**Issue by lacibus** [pallets/flask#4601]
I am using Flask (2.0.2) for a web service API. It does not produce web pages, but accepts multipart form encoded requests to read and update a back-end data store, carries out the requests, and returns a simple text response (with response code 200) or an error response with error message.

The following "Hello World" code produces a rather strange response when some multipart input is posted.

@app.route('/hello', methods = ['GET', 'POST'])
def hello():
    return 'Hello World!\n'

The result of this is:

Hello World!
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code: 400</p>
<p>Message: Bad request syntax ('--&amp;').</p>
<p>Error code explanation: HTTPStatus.BAD_REQUEST - Bad request syntax or unsupported method.</p>
</body>
</html>

The returned response code is actually 200 but the response includes an error message that looks as though it was generated by trying to parse the multipart form input as HTML. (The multipart boundary was '&' and this looks to be the immediate cause of the "bad syntax".)

If, however, the following line is inserted before the return statement, the response is what I would expect. (One of the multipart parts is named 'json').

    ignore = request.files['json']

The result in this case is just:

   Hello World!

It looks as though, unless the input is read, it is parsed as HTML. Although there is an easy work-around, it would be better if this did not happen.

**Comment by davidism** [comment]
Upgrade Werkzeug. Also upgrade Flask.

**Comment by lacibus** [comment]
Thanks - David! Works with Flask 2.1.2 (I did look for relevant issues, but must have used the wrong search terms.)
