### ISSUE TITLE
Flask.auto_find_instance_path() can return wrong path for namespace packages installed in development mode

### ISSUE THREAD

**Issue by eprigorodov** [pallets/flask#4602]
https://github.com/pallets/flask/blob/bd56d19b167822a9a23e2e9e2a07ccccc36baa8d/src/flask/scaffold.py#L798

If there are several packages under the same namespace, all installed in development mode, like:

```
~/namespace-package1/
    namespace/
        package1/
            __init__.py
            app.py
    instance/

~/namespace-package2/
    namespace/
        package2/
            __init__.py
            app.py
    instance/
```
and the code in `namespace.package2` uses `app.instance_path`, then its expected value is `~/namespace-package2/instance` (["Uninstalled package" decision path](https://flask.palletsprojects.com/en/2.1.x/config/#instance-folders)).

Instead of that the following happens:
* `find_package()` [cuts import info](https://github.com/pallets/flask/blob/bd56d19b167822a9a23e2e9e2a07ccccc36baa8d/src/flask/scaffold.py#L846) to the very top package name, `namespace`,
* then `_find_package_path()` finds module specification for the whole namespace package, which contains several submodule search locations, like `ModuleSpec(name='namespace', loader=<_frozen_importlib_external._NamespaceLoader object at ...>, submodule_search_locations=_NamespacePath(['~/namespace-package1/namespace', '~/namespace-package2/namespace']))`
* and then the quoted line returns first, i.e. _arbitrary_, package from that namespace, e.g. `~/namespace-package1`, which produces wrong instance path.

Suggestion: pass also `import_name` into `_find_package_path` and use it for resolving ambiguity at this point, like:

```
def _find_package_path(root_mod_name, import_name):
...
            if spec.origin in {"namespace", None}:
                package_spec = importlib.util.find_spec(import_name)
                package_path = os.path.commonpath(package_spec.submodule_search_locations)
                return os.path.dirname(next(
                    location for location in spec.submodule_search_locations
                    if package_path.startswith(location)
                ))
```

**Comment by davidism** [comment]
Happy to review a PR.

**Comment by davidism** [comment]
Were you interested in submitting a PR for this?

**Comment by eprigorodov** [comment]
Hi @davidism, tried with #4610. `tox` detects an error which was not found by `pytest` under 3.8. I'll update later on this weekend.
