### ISSUE TITLE
Update of the downloadable documentation of flask2.0

### ISSUE THREAD

**Issue by forinda** [pallets/flask#4604]
I would love to be able to download the latest flask2.0 docs as it's always a good resource and since the update of flask the docs have been updated online but the downloadable versions are still in flask1.x.x
![flask](https://user-images.githubusercontent.com/55891685/169630359-e2941ef1-62c6-47d6-ac43-85fbfeedadf1.png)

**Comment by davidism** [comment]
I don't produce these anymore, but you can download and render the docs in many formats that Sphinx supports.

**Comment by forinda** [comment]
> I don't produce these anymore, but you can download and render the docs in many formats that Sphinx supports.

OK
