### ISSUE TITLE
Docs "Old version" banner lists incorrect "latest stable" version

### ISSUE THREAD

**Issue by Rosuav** [pallets/flask#4607]
When viewing a direct link to docs for an ancient version of Flask, a banner at the top of the page warns you that you're looking at old docs, and links to the "latest stable version". However, the version referenced and linked to is not the actual latest stable.

1. https://flask.palletsprojects.com/en/0.12.x/api/ - banner says 1.1.x
2. https://flask.palletsprojects.com/en/1.1.x/api/ - banner says 2.0.x
3. https://flask.palletsprojects.com/en/2.0.x/api/ - banner says 2.1.x
4. https://flask.palletsprojects.com/en/2.1.x/api/ - no banner

Expected behaviour: All three old versions should link to 2.1.x directly.

**Comment by davidism** [comment]
This is not generally possible to fix without constantly rebuilding every version forever.

**Comment by Rosuav** [comment]
Ah, fair enough. Would it be possible to reword it as "A newer version is" rather than saying "Latest stable"? That would remain permanently true.
