### ISSUE TITLE
app.logger logs messages multiple times when using mod_wsgi and application factory

### ISSUE THREAD

**Issue by rtheys** [pallets/flask#4618]
Hi,

I'm not sure if this bug is in Flask, python or mod_wsgi but since I can only reproduce it when I use an "application factory", I'm opening it here.

When I create an application that
 * uses an application factory (create_app function to create the app object)
 * add a WatchedFilehandler logger to the app.logger
 * Create a basic route that logs something

If I deploy this application using Apache and mod_wsgi and then send 3 requests to the application, the log file contains more than 3 lines.
For the first request, it will contain one line, for the second request it will contain two more lines, 3 for the 3rd request, ...

I've created a git repository with an example to reproduce it:

* Clone https://gitlab.esat.kuleuven.be/Rik.Theys/brol.git
* In the repository is a Containerfile that can be used with buildah (or Docker) to build a container image:
  ```buildah bud -f Containerfile -t brol```
* Run the resulting container:
  ```podman run -dt --rm -p 5000:80 --name brol localhost/brol```
* Verify that there's no log file in the container image:
  ```podman exec -it  brol cat /srv/app/logfile```
 * Send a single request:
   ```curl http://localhost:5000/app/```
 * Check the log again. It will show one line.
   ```podman exec -it  brol cat /srv/app/logfile```
 * Send another request.
     ```curl http://localhost:5000/app/```
 * Check the log again. It will show 3 lines: one for the 1st request and **two** for the second request.
   ```podman exec -it  brol cat /srv/app/logfile```
 * Repeat the request/cat a few times. For each request, there will be multiple lines in the log now.

When I don't use a create_app function to create the app, but instantiate the object directly in app.py, I can not reproduce this issue.

I'm using the following configuration for mod_wsgi:
```
WSGIDaemonProcess myapp python-home=/srv/app/venv user=apache group=apache processes=2 threads=10 home=/srv/app
WSGIProcessGroup myapp
WSGIScriptAlias /app /srv/app/myapp.wsgi

<Directory /srv/app>
    Require all granted
</Directory>
```
I'm not sure but it seems like the file logger is added to the list of loggers with each request?

Environment:

I'm using these versions as they are the defaults on RHEL 8 and Flask 2.1 is not supported on Python 3.6

- Python version: 3.6
- Flask version: 2.0.1

**Comment by rtheys** [comment]
Hi,

I've updated my test to return the list of currently registered log handlers.
Running this shows that for each request, an additional WatchedFileHandler is registered.

Regards,
Rik

**Comment by davidism** [comment]
Sounds like mod_wsgi is configured in such a way that it calls the factory for each worker it creates. And you're unconditionally registering a logging handler in that factory. Neither of these things are something Flask controls.
