### ISSUE TITLE
Documentation for FileStorage.save() is inadequate

### ISSUE THREAD

**Issue by kmccurley** [pallets/flask#4634]
The documentation for file uploads in flask has a flaw in it that caused me to lose data on my app. When an app receives an uploaded file, if it calls request.files['file'].save(filename1), they may not then call request.files['file'].save(filename2) because if they do, they get an empty file where filename2 is. The specific piece of documentation that is misleading is [werkzeug.datastructures.FileStorage](https://werkzeug.palletsprojects.com/en/2.1.x/datastructures/#werkzeug.datastructures.FileStorage.save) where it doesn't say that calling save() essentially destroys FileStorage. I understand that perhaps the underlying object is a stream, but it's called a FileStorage object, not a FileStream.

A minimal example is trivial to create:
<form action="/upload" method="POST">
<input type="file" name="file">

This posts to a flask app with the action:
f = request.files['file']
f.save(filename1)
f.save(filename2)

The file filename2 is created but has 0 bytes in it.

The expected behavior is to have save() a repeatable action. This could easily be fixed by documenting save() to say that it may only be called once. That's the simple fix, but a better fix would be to make the save() call be non-destructive on the FileStorage object.

**Comment by davidism** [comment]
This is the exact same behavior as any other file object in python.

**Comment by kmccurley** [comment]
Thisi s apparently a complete blind spot for the developers since it has arisen [multiple times before](https://github.com/pallets/werkzeug/issues/1666). The issue isn't what the behavior is - the issue is that the method is poorly named and poorly documented. There is no save() method on a file object in python. There are only stream-like methods(). This is also the first time I have seen a save() method that is a synonym for move() or truncate(). At the very least the second call to save() should raise an exception or not create a file at all. Creating a zero length file makes no sense. Having vague documentation also makes no sense, but hey it's your pony show.
