### ISSUE TITLE
flask.jsonify produces extra (trailing spaces)

### ISSUE THREAD

**Issue by NickVeld** [pallets/flask#4635]
[The current implementation](https://github.com/pallets/flask/blob/db3187fd7ab324d9175d8a1dd8c3919cec58d3b9/src/flask/json/__init__.py#L291) of flask.jsonify sets `separators` for `json.dump` as `(", ", ": ")` for "pretty-print". Such configuration causes a trailing space in each line ending with ",". But if one check [https://api.github.com/events](https://api.github.com/events) one can notice that it returns pretty-printed JSON without trailing spaces.

I believe it is inconvenient to have spaces in line ends.

Example:
```
import flask


# Without `app` creation  and run user get "RuntimeError: Working outside of application context." from `flask.jsonify`
app = flask.Flask(__name__)
app.config["JSONIFY_PRETTYPRINT_REGULAR"] = True


@app.route("/")
def hello():
    result = flask.jsonify({"id": 0, "message": "Hello, World!"})
    result_lines = result.data.splitlines()

    print("All lines are printed as `bytes` because the quotes shows the trailing spaces")

    print("Printing the whole expected output")
    for line in result_lines:
        print(line.rstrip())

    print("Printing the whole actual output")
    for line in result_lines:
        print(line)

    print("")
    for line in result_lines:
        assert not line.endswith(b" "), (
            "The following line has a trailing space: '" + line.decode("utf-8") + "'"
        )
    return result

if __name__ == "__main__":
    app.run()

```

The output after opening `http://127.0.0.1:5000`:
```
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
[2022-06-11 17:32:46,908] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  ...
  File "...\app.py", line 26, in hello
    assert not line.endswith(b" "), (
AssertionError: The following line has a trailing space: '  "id": 0, '
127.0.0.1 - - [11/Jun/2022 17:32:46] "GET / HTTP/1.1" 500 -
All lines are printed as `bytes` because the quotes shows the trailing spaces
Printing the whole expected output
b'{'
b'  "id": 0,'
b'  "message": "Hello, World!"'
b'}'
Printing the whole actual output
b'{'
b'  "id": 0, '
b'  "message": "Hello, World!"'
b'}'
```

So every line with the comma in the end have a trailing space (in the example this line is '`  "id": 0, `')

A suggestion how to fix:

- Change the [following line](https://github.com/pallets/flask/blob/db3187fd7ab324d9175d8a1dd8c3919cec58d3b9/src/flask/json/__init__.py#L291) `separators = (", ", ": ")` to `separators = (",", ": ")`

Environment:

- Python version: (Conda) `python 3.8.13 h6244533_0`
- Flask version: `flask 2.0.3 pypi_0  pypi`

**Comment by NickVeld** [comment]
I am ready to make a contribution but from [CONTRIBUTING.rst](https://github.com/pallets/flask/blob/db3187fd7ab324d9175d8a1dd8c3919cec58d3b9/CONTRIBUTING.rst#submitting-patches):
"If there is not an open issue for what you want to submit, prefer opening one for discussion before working on a PR."

**Comment by davidism** [comment]
I don't think this is particularly worth fixing. Pretty printing is only intended for debugging, you should use the minimal representation in production to reduce the size.

That said, I've already addressed this with a larger refactor to Flask's JSON system, so this isn't something that needs to be addressed separately.

**Comment by NickVeld** [comment]
@davidism I have created this issue because it created me a problem while testing. My app is proxing events from https://api.github.com/events . And it returns a pretty-printed JSON. So I need to test against pretty-printed response. But it is more difficult with this problem.

**Comment by NickVeld** [comment]
@davidism And even for debug it is a problem because someone uses debug output for testing, for reference and so on or at least navigates over it. But the trailing spaces are not welcome in many places. https://softwareengineering.stackexchange.com/questions/121555/why-is-trailing-whitespace-a-big-deal
And moreover, it is even not a big deal to fix it!
