### ISSUE TITLE
Installing extras with pip does not work

### ISSUE THREAD

**Issue by evanphilipsmith** [pallets/flask#4644]
As guided by [the docs](https://flask.palletsprojects.com/en/2.1.x/async-await/#using-async-and-await), when I try to install the `async` extra by running 
```
pip install flask[async]
```
I get the following message.
```
zsh: no matches found: flask[async]
```

I believe that this is because there is no `[options.extras_require]` section in `setup.cfg`.
I noticed that there is an `extras_require` section in `setup.py`, but I'm not sure why `pip` cannot find it.

It should have installed the dependencies needed for flask to run with coroutine functions.

Environment:

- Python version: 3.10
- Flask version: 2.1.2
- Pip version: 22.1.2

**Comment by davidism** [comment]
Put quotes around the name, so the shell doesn't interpret special characters.
