### ISSUE TITLE
namespace is preserved between invocations

### ISSUE THREAD

**Issue by mortoray** [pallets/flask#4705]
The object created by `namespace(...)` appears to be preserved between invocations of jinja, that is, it appears to become a global Python variable. I'm seeing this via `render_template` from flask routes.

For example, given a file `index.html`:

```
{% set gs = namespace(count = 0) %}
{% set gs.count = gs.count + 1 %}
{{ gs.count }}
```

The first call to `render_template('index.html')` produces `1` as expected.

The second call produces `2` which is unexpected. I was expecting a `1` to be produced again. This happens even if the next render is in a following HTTP request to a new route. This happens across sessions as well.

Environment:

- Python version: 3.10
- Jinja version: 3.1.2
- Flask 2.1.2

----

This behaviour is not exhibited by the direct use of Jinja. For example:

```
from jinja2 import Environment, FileSystemLoader, select_autoescape
env = Environment(loader=FileSystemLoader("."))

template = env.get_template("index.html")
print(template.render())
print(template.render())
```

This writes "1" both times.

**Comment by mortoray** [comment]
I'm trying to narrow it down. In my Flask server it happens only if the namespace is within a macros file, and invoked via a macro.

**Comment by ThiefMaster** [comment]
default arg of a macro by any chance? if yes: same pitfall as python: evaluated only once, not at call time

**Comment by mortoray** [comment]
Okay, this reproduces it:

templates/index.html
```
{% import 'macros.html' as eq %}
{{ eq.incr_value() }}
```

templates/macros.html
```
{% set iv = namespace(count = 0) %}
{% macro incr_value() %}
{% set iv.count = iv.count + 1 %}
{{ iv.count }}
{%- endmacro %}
```

server.py
```
from flask import Flask, render_template
app = Flask(__name__)

@app.route('/')
def hello_world():
    return render_template('index.html')
    ```

Invocation:
```
export FLASK_APP=server.py
flask run
```

- Go to localhost:5000/  (get 1)
- Go to localhost:5000/  (get 2)  *error*

**Comment by davidism** [comment]
You defined a namespace at the global scope then referenced it in a macro body. It's equivalent to a global variable for a function in Python.

**Comment by mortoray** [comment]
@davidism Outside of a macros file the namespace does not produce a global.  I don't see why it should behave differently when put inside a macro file.

**Comment by davidism** [comment]
Go look at what the output of `env.compile(raw=True)` is for both those templates, you'll see what's happening. You're defining a global variable compared to the scope of the macro. Macros are only compiled once with their template. Most templates don't have different scopes that would cause the same namespace to be referred to later.

**Comment by mortoray** [comment]
I can understand that is what is happening, but from the perspective of a user of the templates package, this is an error. There is no reason I'd expect this result, as the initial implications I wrote still stand, in particular the security aspect.

Even saying this is what should happen, it means there is no way for an import to safely use "namespace", thus no way to have variables preserved between invocations of a macro.
