### ISSUE TITLE
Fix Versions in setup.py with == not >=

### ISSUE THREAD

**Issue by xXBasti** [pallets/flask#4709]
Hi since the last release from Werkzeug, installing requirements from flask breaks the env/dockercontainer. 
It seems like Werkzeug has moved some files.
Werkzeug's 2.2.0 Update: flask_login/utils.py line 14 - ImportError: cannot import name 'parse_rule' from 'werkzeug.routing'

This is already the 2nd time this year, an update in Werkzeug is breaking flask. 

We would really apprciate if you could use == in setup.py and not only in the requirements for tox to make using flask more stable and convient. Current it is up to us to pin Werkzeug to 2.1.2 before the modules has been moved. 

The setup requirments of Flask 2.1.3, the current release, are currently wrong as this version requires Werkzeug <2.2.0 but Werkzeug>=2.0.0.

This would clearly increase the user experience as the user does not need to pin the version until a new flask version is released dealing with the change in Werkzeug.

Pip install flask or flask==2.1.3 should ne enough to reproduce the bug.

Expected behaviour, pip install flask should work without manually having pined the requirements of flask

Environment:

- Python version: 3.8 
- Flask version: 2.1.3

**Comment by pgjones** [comment]
Werkzeug is not breaking Flask. Flask-Login uses an internal API and needs updating, see https://github.com/maxcountryman/flask-login/issues/686 for the issue tracking.

Good practice is to use a lock file and pin your dependencies, please use a tool such as PDM, Poetry, Pipenv, pip-tools, etc (we really are spoiled for choice now).
