### ISSUE TITLE
Add test for flashed messages using sessions on external storage.

### ISSUE THREAD

**Issue by rduplain** [pallets/flask#472]
Add a test for #417.

**Comment by CorneliusIV** [comment]
I believe this test should should cover the issue
https://github.com/pallets/flask/blob/a4931ff3a74d9fcd8766bee69a01b62a75a5e131/tests/test_basic.py#L439

**Comment by jeffwidman** [comment]
Thanks @CorneliusIV for helping us out at the Pycon Sprint.
