### ISSUE TITLE
cannot import name 'request_ctx' from 'flask.globals'

### ISSUE THREAD

**Issue by hrauch** [pallets/flask#4723]
Environment:

- Python version: 3.9.2
- Flask version: 2.2.0

Updating from Flask 2.1.2 to 2.2. (without changes my sources, I got this error:

    File "../venv/lib/python3.9/site-packages/werkzeug/utils.py", line 109, in __get__
    value = self.fget(obj)  # type: ignore
    File "../venv/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 428, in form
    self._load_form_data()
    File "../venv/lib/python3.9/site-packages/flask/wrappers.py", line 122, in _load_form_data
    from .debughelpers import attach_enctype_error_multidict
    File "../venv/lib/python3.9/site-packages/flask/debughelpers.py", line 5, in <module>
    from .globals import request_ctx
    ImportError: cannot import name 'request_ctx' from 'flask.globals' (../venv/lib/python3.9/site-packages/flask/globals.py)

**Comment by davidism** [comment]
I can't reproduce the issue with the information provided. Be sure to include a minimal reproducible example when reporting an issue.

The following two examples deal with the lines in the traceback you provided, but neither raise an error.

```pycon
>>> from flask.globals import request_ctx
# no error
```

```python
from flask import Flask
from flask import request

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        return request.files["test"].filename

    return """<form method=post><input type=file name=test><input type=submit></form>"""

# access the page, submit the form, get the correct error not an ImportError
```
