### ISSUE TITLE
Not clear that Flask.run is threaded by default.

### ISSUE THREAD

**Issue by pfh** [pallets/flask#4737]
Flask.run sets threaded=True as the default when calling werkzeug.serving.run_simple. This wasn't mentioned in the function docstring, which only refers me on to werkzeug.serving.run_simple, where the default is threaded=False. So it surprised me when my non-thread-safe code behaved weirdly.

- Python version: 3.8.10
- Flask version: 2.2.1

**Comment by davidism** [comment]
In the changelog for the method:

> Threaded mode is enabled by default.

I don't think this is worth documenting further.

In general, you must never write thread-unsafe code in a web application. Don't use global variables to store data. A web application might be served using thread workers, process workers, coroutines, etc. It might even be distributed across multiple machines if you're using a deployment platform service.
