### ISSUE TITLE
No backward compatible way to access flask.globals.request_ctx

### ISSUE THREAD

**Issue by alisaifee** [pallets/flask#4750]
Accessing `flask._request_ctx_stack` in Flask `2.2+` results in a `DeprecationWarning` recommending
`flask.globals.request_ctx`. However, this is not available in previous versions. For extensions that support < 2.2 this means that the usage can't be simply upgraded.

I went with a conditional based on the import like [this](https://github.com/alisaifee/flask-limiter/blob/master/flask_limiter/_compat.py) - but wondering if there is a better way? (I realize this isn't exactly a bug, but it didn't quite fit the criteria of a general usage question either).

Environment:

- Python version: 3.10
- Flask version: 2.2.1

**Comment by davidism** [comment]
That's the standard way to do this. It's not specific to Flask. Also, don't store stuff on the context objects, transition to using attributes on g with a prefix.
