### ISSUE TITLE
Support mounting apps other than '/' for Debug mode with Werkzeug development server (or add workaround in docs)

### ISSUE THREAD

**Issue by gnbl** [pallets/flask#4751]
Mounting apps on a path other than root ('/'), e.g. '/test' is apparently not supported by the Flask Debug Mode (using Werkzeug), nor does it appear to be documented explicitly. A bit of searching led me to:

- Blog from 2020:  https://dlukes.github.io/flask-wsgi-url-prefix.html
- Issue from 2018: https://github.com/pallets/flask/issues/2759 (Solution with DispatcherMiddleware: https://github.com/pallets/flask/issues/2759#issuecomment-386887290)

I'd like to request that a short section be added in e.g.

- https://flask.palletsprojects.com/en/2.2.x/quickstart/#a-minimal-application
- https://flask.palletsprojects.com/en/2.2.x/quickstart/#debug-mode
- https://flask.palletsprojects.com/en/2.2.x/cli/#run-the-development-server

that would point out this "limitation" (along the lines of "Flask Debug Mode / Werkzeug do not support mount points, since the  WSGI variable `SCRIPT_NAME` is not supported") and maybe show an example using DispatcherMiddleware.

Also, maybe a CLI option like "--mount" for `flask` is feasible?

The other option is running the app script directly (not via `flask run`), which is what I am currently using:

```
if __name__ == "__main__":
    # from https://dlukes.github.io/flask-wsgi-url-prefix.html
    from werkzeug.middleware.dispatcher import DispatcherMiddleware
    from werkzeug.wrappers import Response
    app.wsgi_app = DispatcherMiddleware(
        Response('Not Found', status=404),
        {'/test': app.wsgi_app}
    )

    app.run(
        host='0.0.0.0', 
        port=1026, 
        debug=True
        )

```

**Comment by davidism** [comment]
I don't plan to add `--mount` to the CLI.

The docs could probably be updated a bit, but it's described here: https://flask.palletsprojects.com/en/2.2.x/patterns/appdispatch/

Use an app factory:

```python
def create_app():
    app = Flask(__name__)
    ...
    return app

def create_mounted_app():
    app = create_app()
    app.wsgi_app = DispatcherMiddleware({"/api": app.wsgi_app})
    return app
)
```

```
flask --app 'example:create_mounted_app()' run
```
