### ISSUE TITLE
TypeError: send_file() got an unexpected keyword argument 'attachment_filename'

### ISSUE THREAD

**Issue by igushev-truesource** [pallets/flask#4753]
Old code start throwing this exception:
`TypeError: send_file() got an unexpected keyword argument 'attachment_filename'`

**Comment by davidism** [comment]
As called out in the changelog:

> Remove previously deprecated code. #4667
>
> Old names for some `send_file` parameters have been removed. `download_name` replaces `attachment_filename`, `max_age` replaces `cache_timeout`, and `etag` replaces `add_etags`. Additionally, `path` replaces filename in `send_from_directory`.

These have been raising deprecation warnings since 2.0. Be sure to run your tests with warnings treated as errors so you can respond to deprecations (in any library, not just Flask).
