### ISSUE TITLE
flask.g is not an adequate replacement for _request_ctx_stack.top

### ISSUE THREAD

**Issue by jace** [pallets/flask#4774]
I'm migrating a local proxy to replace use of `_request_ctx_stack.top` with `g`, as recommended. This works in runtime use but is breaking tests where the app context is created before the request context. There doesn't seem to be an easy resolution:

1. A test that uses database fixtures with Flask-SQLAlchemy will need an app context. However, if a temporary app context is used, Flask-SQLAlchemy closes the database session on context teardown, and the database objects are expunged. Adding them back to the session ([as pytest-flask-sqlalchemy does](https://github.com/jeancochrane/pytest-flask-sqlalchemy/blob/12ad2fbd7da1005f5fd579a6c260aff527c6ee36/pytest_flask_sqlalchemy/fixtures.py#L66-L73)) creates a test environment that is not similar to runtime and will mask bugs elsewhere.

2. This means the app context must remain in place for the entire test, and a request context is created when needed (say using `test_client.get`). However, in this case, request context teardown will not cause app context teardown and `g` will contain stale data in the next request.

3. I tried using `request_ctx` instead. The problem is `request.copy()` does not copy any additional data in `request_ctx`, so a function decorated with `@copy_current_request_context` will need a replacement decorator to copy additional data. Chaining decorators won't work as the new context created in this decorator is not accessible from another decorator. There is no fix for use of this decorator in other extensions without monkey patching.

4. Another try: use `g` as recommended, but wipe the data on request teardown. I changed my proxy's constructor to register an `after_this_request` handler. Problem: this one runs before other `after_request` handlers, so the data is gone by the time it's needed.

5. There is no one-off `after_this_request_teardown` handler. Instead, the local proxy will need to provide an `init_app` to register the app teardown handler. Since it's a proxy, init_app can't be a method in its own namespace unless the proxy is designed to work without an app or request context. It will become a separate import (`from proxy_module import my_proxy, init_app as my_proxy_init_app`), and the `init_app` will effectively only be required for tests.

6. Violate the recommendations and store directly on `request` as an underscore-prefixed attribute. This seems to work, but is a dirty hack.

Possible resolutions:

1. `request.copy()` should copy everything in `request_ctx`. This may be the cleanest fix.
2. A new request-context namespace should be provided to complement `g`, maybe an `r` or `request.g`.
3. Creating a new request context should always create a new app context. However, this will need an additional fix: Flask-SQLAlchemy should not close the database session unless it is the outermost app context.

**Comment by davidism** [comment]
I don't know what your proxy is, so I can't say whether it's designed correctly or how to fix it. It sounds like you're making an incorrect assumption somewhere, and it just happened to work before. If you have a question about your own code, ask about it on Discord or Discussions.

1. That sounds like a possible issue with pytest-flask-sqlalchemy. I'm not clear how the change to `g` would affect that. I don't know how that library works, so I can't help debug it.
2. An app context should not be pushed for an entire test, do not do `with app.app_context(): yield` in a fixture. Only push a context manually very locally to where that's needed.
3. `copy` would not copy any custom data previously either, that has not changed.
4. Sounds like you want `after_request` or `teardown_request`, not `after_this_request`. But also, you probably want `teardown_appcontext`, it sounds like it's tied to the app context not the request context.
5. This didn't change from previously, so I don't see why it's a point to bring up.
6. This is not how things worked before, you would store things on the context object not the request object.

None of the solutions you propose reflect behavior prior to 2.2, so it's not clear why they would help.

Overall, I can't tell what issue you're describing. It really sounds like there's some fundamental misunderstandings that were happening before the current change as well. Please ask questions about your own code in an appropriate location.

**Comment by jace** [comment]
[Flask-SQLAlchemy removes the database session on app-context teardown](https://github.com/pallets-eco/flask-sqlalchemy/blob/2d9257e79b8246632b7518c613fb24bc523f9b1d/src/flask_sqlalchemy/__init__.py#L872-L885), so this is the base source of the problem. A fixture is not reliably available between app contexts. A test can only mimic runtime use if it keeps a single app context for the entire test.

**Comment by davidism** [comment]
> A test can only mimic runtime use if it keeps a single app context for the entire test.

Keeping a context alive for an entire test is incorrect, you should let Flask manage contexts. Only if you're specifically testing something outside of a request should you enter a context manually, then exit it as soon as possible.

The "app" in "app context" is not a description of its lifetime, it's a description of what data it tracks. The app context tracks data about the app itself, a request context tracks data about the request. Starting a request context also starts an app context, then cleans it up, so the context is still only intended to live as long as the request. Starting a CLI command starts an app context then cleans it up.

This has been true forever, the change in 2.2 does not change this.

**Comment by jace** [comment]
I agree with the principle, and this is likely a Flask-SQLAlchemy issue more than a Flask issue, but [yielding an app context in a test fixture appears to be a very common](https://github.com/search?q=with+app.app_context+yield&type=code). I will fix my code, but it does seem like moving variables from request context to app context is going to break tests for a lot of people.

Flask-SQLAlchemy's behaviour complicates this because a short-use app context breaks things elsewhere:

1. SQLAlchemy will expunge all objects from session and cause downstream failures unless they are re-added to the session. pytest-flask-sqlalchemy solves this (as above) by re-adding everything to the session (which I disagree with as it has uncontrolled side-effects). I don't have a reliable way to track what objects should be re-added, and where. When there's no wrapping appcontext, a simple `test_client.get` will cause the database session to be closed, and all fixtures must be re-added.
2. Flask-RQ2 `job` decorator creates an app context for the job. This is usually fine, but RQ's documentation suggests [running jobs in sync for unit tests](https://python-rq.org/docs/testing/#running-jobs-in-unit-tests). (In Flask-RQ2, that's by [setting `RQ_ASYNC=False`](https://flask-rq2.readthedocs.io/en/latest/#rq-async)). When the job finishes, Flask-SQLAlchemy's teardown handler closes the session and the fixtures blow up.
3. [Flask-Executor had a separate issue with database connections](https://github.com/dchevell/flask-executor/issues/15) and solved it by also pushing an app context. Calling an executor function in a unit test will now blow up fixtures again. In the linked issue #3306 @kaos concludes by suggesting request globals should be stored on `request` not `g`.

There is an open issue on Flask-SQLAlchemy for this: https://github.com/pallets-eco/flask-sqlalchemy/issues/508

It seems like people have come up with various coping mechanisms for dealing with app contexts that do not leave it to Flask, and moving variables from request context into app context will just complicate it.

My ask is simple: provide an officially documented way for an extension to continue storing data in the request context so that it can be compatible with Flask 2.3 without breaking downstream code. Cleaning up hacky use of app context should be separate.

The issue with `@copy_current_request_context` is separate: it affects async functions, which need a documented way to get context from extensions.

**Comment by jace** [comment]
I've modified my `db_session` fixture to monkeypatch `session.remove` and make it rollback instead. This resolves the problem with keeping app contexts alive for Flask-SQLAlchemy. It doesn't seem to be foolproof because rollback is failing with Flask-Executor in threaded mode, so I've temporarily set it to rollback if in the main thread, noop if in another thread – pending a deeper understanding of what is going on.

Sorry for the messy ticket, @davidism. Most of this is due to Flask-SQLAlchemy not having a documented way to use in tests.

For anyone interested, [this is my current version of the fixture](https://github.com/hasgeek/funnel/blob/f52b8dda8d64c95a762292c44d87b06e0057e7d2/tests/conftest.py#L663-L798).
