### ISSUE TITLE
CLI flask run describes that uses --debug to enable debugger and reloader, but flask run does not have the -- debug option

### ISSUE THREAD

**Issue by qiujiajin** [pallets/flask#4777]
flask run --help description:   The reloader and debugger are enabled by default with the '--debug' option.
But when I use flask run --debug, it tells me that there is no --debug option

flask run --debug

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/42339097/185777280-d4bfbacb-fef7-41a8-be21-1d14cbf53557.png">

According to the description of flask run --help, the --debug option should be supported.

Environment:

- Python version: 3.10.6
- Flask version: 2.2.2

**Comment by greyli** [comment]
The `--debug` and  `--app` options are for `flask` itself, not the subcommand (e.g. `run`):

```
flask --debug run
```

**Comment by Avinashbhat1199** [comment]
The reloader and debugger are enabled by default if FLASK_ENV=development or
  FLASK_DEBUG=1.
