### ISSUE TITLE
Link to example project in tutorial is dead (links 2.2.3 instead of 2.2.2)

### ISSUE THREAD

**Issue by geo7** [pallets/flask#4791]
From docs page : https://flask.palletsprojects.com/en/2.2.x/tutorial/next/ the link is

```
[example project](https://github.com/pallets/flask/tree/2.2.3/examples/tutorial)
```

Which gets a 404 from github - it should be (I _think_)  

```
[example project](https://github.com/pallets/flask/tree/2.2.2/examples/tutorial)
```

In order to work. 

I'm not too sure how sphinx picks up the following tag:

```
:gh:`example project <examples/tutorial>`
```

**Comment by jordyjwilliams** [comment]
@geo7 @davidism was aiming to have a look at this today... Didn't have as much time as expected. 

A quick glance over showed that the `:gh:` tag is picked up by `sphinx` as it's defined in the (conf.py here)[https://github.com/pallets/flask/blob/73b9bacbf7e7440e5a8a65e61fecfe3d0ce75579/docs/conf.py#L97-L98].

I couldn't see any glaring issues here, when building the docs `cd into docs -> make html` all tutorial links work as expected for me, however on the link shared above I can confirm that I am also getting a `2.2.3` in the requested URL when I would also concur that this should be `2.2.2` what's strange is `2.2.2` is the last listed tag but I couldn't find anywhere in the code that mentioned this was what was trying to be accessed. 

When running `pallets_sphinx_themes.__init__.py`'s `get_version` I obtain `(2.3.0dev0, 2.3.x)`. Pretty unsure as to where the `2.2.3` woudl be arising from... Also unsure why this would not reproduce locally for me.

Happy to put more time into this later although my `Sphinx` knowledge is not the best
