### ISSUE TITLE
Split session across multiple chunks if the session size is too large for a single cookie

### ISSUE THREAD

**Issue by infohash** [pallets/flask#4798]
It is not uncommon nowadays for big organizations to have more than one OIDC Provider (OP) for their v1, v2, v3, ...,  APIs. E.g. When moving to next API versions, if there is a change in OP, they keep the same OP for their legacy APIs until deprecation. In such web applications, OIDC tokens that are set in `flask.session` are also multiplied. This increases the size of session to more than 4KB and browsers ignore the set-cookie header silently if the cookie exceeds max-size limit. Browsers support 150-180 cookies per domain and 4KB size per cookie. Large session can be split across multiple chunks and set each chunk as cookie in browser.

# Possible Approach
1. After signing and encoding the session, if the size of the string is more than 4096 bytes, split the string from 4032 byte. 4032 because you have to accommodate for the cookie name.
2. Assign a sequential name to each chunk so that you can combine the string to its original order when loading the session from the cookies. Example names can be session-0, session-1, session-2, etc.
3. On incoming request, combine the cookies, verify their signature and load them into session.
4. When sending a response, check how many cookies are being set this time. If their count is less than the number of cookies that were set last time, that means you have to expire the redundant cookies that were previously set.

E.g.
```python
Request-1 -> No Cookies
Session Created...
Setting 3 chunks as cookies...
Response-1 -> Set-Cookie(session-0), Set-Cookie(session-1), Set-Cookie(session-2)

Request-2 -> session-0, session-1, session-2
Session Modified...
Setting 2 chunks as cookies...
If size of the session has changed, this will change the number of chunks.
Let's say number of chunks are 2 this time.
That means previously set cookie session-2 will not be overwritten so manually expire it.
Response-2 -> Set-Cookie(session-0), Set-Cookie(session-1), Set-Cookie(session-2, expire=0)

Request-3 -> session-0, session-1
...
```

**Comment by davidism** [comment]
You can write a custom session interface subclass if you need that. If you're sending more than 4kb back and forth in every request and response, it's probably time to redesign something in your app rather than do that though.

**Comment by miguelgrinberg** [comment]
The [Flask-Session](https://flask-session.readthedocs.io/en/latest/) extension is also a possible way to work around the issue of having a massive session, by keeping the session data stored in the server.
