### ISSUE TITLE
:inherited-members: does not work for attributes

### ISSUE THREAD

**Issue by SimonSapin** [pallets/flask#480]
I am not sure if this is a bug in Sphinx, but stuff like the `root_path` and `static_url_path` attributes/properties from `_PackageBoundObject` end up not documented in the API page of the docs. `api.rst` just contains this:

```
.. autoclass:: Flask
   :members:
   :inherited-members:
```

**Comment by jeffwidman** [comment]
Sphinx moved their issue tracker to GitHub and marked the above linked issue as a duplicate, so the new link to the upstream issue is https://github.com/sphinx-doc/sphinx/issues/741
