### ISSUE TITLE
mypy check error: "JSONProvider" has no attribute "sort_keys"  [attr-defined]

### ISSUE THREAD

**Issue by jakubczaplicki** [pallets/flask#4808]
Following the warning `The 'JSON_SORT_KEYS' config key is deprecated and will be removed in Flask 2.3. Set 'app.json.sort_keys' instead` we modified the code to use the mentioned `app.json.sort_keys`. However mypy check fails with the following error:

```
% mypy --install-types --non-interactive 
app.py:24: error: "JSONProvider" has no attribute "sort_keys"  [attr-defined]
```

where the line 24

```
23:    app = Flask(__name__)
24:    app.json.sort_keys = False
```

Environment:

- Python version: 3.10.4
- Flask version: 2.2.2

**Comment by davidism** [comment]
This is not possible to fix. `app.json` can be _any_ `JSONProvider` class, not only the default one, so it is annotated appropriately. You can add a `# type: ignore[attr-defined]` comment to ignore that finding in mypy.
