### ISSUE TITLE
Add a FORCE_URL_SCHEME option

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/flask#481]
It should be possible to force the URL scheme to https for all things. That includes URL generation as well as automatic redirect checks on all requests.

**Comment by dorianpula** [comment]
It sounds like @pwaller's issue was resolved.  But I assume this is still something we want to get working for 1.0?

**Comment by untitaker** [comment]
I think nowadays people use different means of enforcing HTTPS, so this might not be that necessary. Still a nice feature to have.

**Comment by SkiftCreative** [comment]
I am at the pycon sprints, I am going to see if I can add a config flag for adding this.
