### ISSUE TITLE
cant run https adhoc

### ISSUE THREAD

**Issue by meddany** [pallets/flask#4819]
Hi. 

for sometime i was able to run https using flask using tmp ssl cert. adhoc.
but now when i am trying to enable https back again from http. i face this issue.

```
  File "Z:\Python_Venv\env1\lib\site-packages\gevent\server.py", line 125, in __init__
    self.wrap_socket = ssl_context.wrap_socket
AttributeError: 'str' object has no attribute 'wrap_socket'
```

i am adding this to my code.

ssl_context='adhoc'

i am on Python 3.10.4 , flask 2.2.2

UPDATE : 
i found that this issue occurs when :

**from engineio.async_drivers import gevent**

But this is important as since i am packing using pyinstaller. this line must be there

**Comment by davidism** [comment]
Don't use the development server outside of development. That said, it sounds like this is Flask-SocketIO.
