### ISSUE TITLE
Inconsistent documentation on `debug`s default

### ISSUE THREAD

**Issue by ByteEater-pl** [pallets/flask#4842]
Does the `run` method of the `Flask` class take an optional argument `debug` with default value `None` [1], or `False` [2]?

[1] https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.run
[2] https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.debug

**Comment by davidism** [comment]
It takes a boolean value.

**Comment by ByteEater-pl** [comment]
from [1]: `run(host=None, port=None, debug=None, load_dotenv=True, **options)`
