### ISSUE TITLE
Large file uploads - form.field.data.save() copy takes too long 

### ISSUE THREAD

**Issue by praiskup** [pallets/flask#4844]
It would be nice to have a way to specify storage directory for the form
file uploads, and use tempfile.NamedTemporaryFile() instead of just
tempfile.SpooledTemporaryFile() when needed.

The thing is that uploads to SpooledTemporaryFile are stored in /tmp
(often tmpfs, or a specifically fast volume, etc.).  Later it is expected
that we use the werkzeug field.data.save() method to copy the file to the
final destionation.  This doesn't scale for files of several GB, the copy
action may take several minutes depending on many factors.

It would be nice to upload the files directly to the target destination,
or at least to the same volume (uploads are typically limited by network
connection, not I/O).  If on the same volume, we can hardlink the file to
the target destination, or move - and save a lot of the request time
(which potentially can timeout).

We are trying to way-around this using our own Request method that
overrides the internal _get_file_stream() method to enforce the
NamedTemporaryFile() usage:

  https://pagure.io/copr/copr/pull-request/2334#request_diff

If this can not be implemented in Flask or Werkzeug, it would be at least
nice to have a documented way how to use NamedTemporaryFile() for uploads.

Let me know if I can help with anything, and thank you for the pallets' projects!

Some interesting reading:
https://github.com/bottlepy/bottle/issues/288
https://github.com/bottlepy/bottle/pull/289

**Comment by davidism** [comment]
> overrides the internal `_get_file_stream()`

That's fine, it's intended that you override that method to customize how files are stored.

**Comment by praiskup** [comment]
> it's intended that you override that method to customize

Thanks for the confirmation!

> You can also use something besides file.save(), such as calling os.rename,

Sure, but we need to have the filename in hand first, thus NamedTemporaryFile (or similar) is needed.

**Comment by praiskup** [comment]
Not sure though what happens after os.rename() once the temporary file is closed (and auto-removed).
