### ISSUE TITLE
Improve JSONIFY_MIMETYPE deprecation warning

### ISSUE THREAD

**Issue by mephinet** [pallets/flask#4860]
With version 2.2 of flask, `JSONIFY_MIMETYPE` was deprecated in favor of `DefaultJSONProvider`'s `mimetype` class property.
When `JSONIFY_MIMETYPE` is still used, a `DeprecationWarning` is raised: 

> The 'JSONIFY_MIMETYPE' config key is deprecated and will be removed in Flask 2.3. Set 'app.json.mimetype' instead.

When following this instruction, [pyright](https://github.com/RobertCraigie/pyright-python) reports an error, though:

> error: Cannot assign member "mimetype" for type "JSONProvider": Member "mimetype" is unknown  - Pyright[reportGeneralTypeIssues]

I think pyright is correct: the `mimetype` property does not exist on `JSONProvider` - as it's only meant to be a base class allowing users to customize behavior. Only its subclass `DefaultJSONProvider` has this property, and is expected to act accordingly.

So I think the deprecation hint should instead say:

> Please set flask.json.provider.DefaultJSONProvider.mimetype instead.

If you agree, I'm happy to provide a pull request!

Environment:

- Python version: 3.10.8
- Flask version: 2.2.2
- pyright version: 1.1.278

**Comment by davidism** [comment]
You're welcome to treat pyright/mypy findings as errors, and work around them with the subset of Python accepted by type checkers. But the warning as-is is accurate for anyone who just upgraded and just wants to fix their config. I don't want a more complicated message.

Also, setting a global class-level variable isn't really correct either. The easiest solution is to just ignore that finding. But if you don't want to, then either cast the existing object, or create a new one. Both of these should type check.

```python
from typing import cast

provider = t.cast(DefaultJSONProvider, app.provider)
provider.mimetype = "..."

# or

provider = DefaultJSONProvider(app)
provider.mimetype = "..."
app.json = provider
```

**Comment by mephinet** [comment]
Understood, thanks for the clarification, @davidism! FWIW, I'll go with version 2 of your proposed solutions.
