### ISSUE TITLE
docs should explain the `@setupmethod` behavior

### ISSUE THREAD

**Issue by HLFH** [pallets/flask#4868]
The [appcontext documentation](https://flask.palletsprojects.com/en/2.2.x/appcontext/) should explain the new @setupmethod 'shell_context_process' behavior, linked to https://github.com/pallets/flask/pull/4577.

Flask raises an Assertion Error.

> AssertionError: The setup method 'shell_context_processor' can no 
    longer be called on the application. It has already handled its 
    first request, any changes will not be applied consistently. Make
    sure all imports, decorators, functions, etc. needed to set up the 
    application are done before running it.

The error should be documented, and a correct implementation should be provided.

**Comment by HLFH** [comment]
@davidism Well can you not explain/document the AssertionError on the new @setupmethod 'shell_context_processor' behavior and tell people that use Flask > 2.2.0 how to fix it. This new behavior with the PR https://github.com/pallets/flask/pull/4577 should be documented and it is not.

**Comment by bplaxco** [comment]
Question related to this until the docs are in place:

[Previously](https://github.com/pallets/flask/pull/4577/files#diff-d3e0349504081bb501c611b3954be364188a4cf442056181272e27e830ae446eL545) you could set the debug flag to false and avoid the error if for example unit tests called a setup method more than once. 

Is there a way to have it ignore the check during testing, or would a better approach be to create/mock a new app object each time?

**Comment by kemken077** [comment]
> 

Is this something that should be addressed in another issue?

**Comment by kemken077** [comment]
> Question related to this until the docs are in place:
> 
> [Previously](https://github.com/pallets/flask/pull/4577/files#diff-d3e0349504081bb501c611b3954be364188a4cf442056181272e27e830ae446eL545) you could set the debug flag to false and avoid the error if for example unit tests called a setup method more than once.
> 
> Is there a way to have it ignore the check during testing, or would a better approach be to create/mock a new app object each time?

Is this something that should be addressed in another issue?

**Comment by davidism** [comment]
Closed as part of #4973, see https://flask.palletsprojects.com/en/2.2.x/lifecycle/.
