### ISSUE TITLE
Heroku Deployment Tutorial

### ISSUE THREAD

**Issue by ctopherngoc** [pallets/flask#4884]
I wrote a simple tutorial a month ago on how to deploy a Flask project on Heroku for an assignment for the open source software course I am enrolled for my computer science program. A requirement is for the assignment is to contribute to an open source project and submit a pull request to project.  Hopefully I followed CONTRIBUTING.rst correctly. If anything you can close this issue and close the pull request.

This tutorial was written prior to announcement where Heroku stated that they will no longer be providing a free package for their dyno management system. The tutorial was recently updated to bring attention to this change. 

This tutorial was written to help others deploy their Flask projects on Heroku through the utilization of a Github account and repository.

**Comment by davidism** [comment]
Thanks, but this is not something we want to include.

Not only is Heroku no longer offering a free tier, but this tutorial is already severely out of date with the versions pinned, and lacks details about the application or how to configure and deploy to production.

I'd suggest focusing on existing issues when starting to contribute to open source projects. You may want to pass this feedback on to the course, this wasn't the first PR like this today.
