### ISSUE TITLE
flask.url_for no longer supporting values parameter

### ISSUE THREAD

**Issue by fluffy-critter** [pallets/flask#4893]
In Flask 2.2.2, `flask.url_for` is no longer using the `values` parameter as a proxy for the keyword arguments list, and is instead turning that into a URL parameter.

For example, in previous versions of Flask, I was able to do something like:

```
@app.route('/one')
def some_endpoint():
    return flask.redirect(flask.url_for("other_endpoint", values=flask.request.args))

@app.route('/two')
def other_endpoint():
    return "Hello"
```

and then a request to e.g. `/one?foo=bar&foo=baz` would then redirect to `/two?foo=bar&foo=baz`. However, now it redirects to `/two?values=ImmutableMultiDict([('foo',+'bar'),+('foo',+'baz')])`.

I'm guessing that the underlying parameter name for the keyword arguments list has changed, but [the documentation](https://flask.palletsprojects.com/en/2.2.x/api/?highlight=url_for#flask.Flask.url_for) has not been updated to reflect this.

As a workaround I can do e.g. `url_for("other_endpoint", **request.args)`, but this doesn't properly preserve argument lists with multiple identical keys.

Environment:

- Python version: 3.10.8
- Flask version: 2.2.2, Werkzeug 2.2.2

**Comment by ThiefMaster** [comment]
the values are passed as kwargs, not a single arg named `values`...

**Comment by fluffy-critter** [comment]
I could have sworn this used to work by providing a parameter named `values` instead. Is there an appropriate way to pass through `request.args` in a way which preserves the `request.args` MultiDict?

**Comment by ThiefMaster** [comment]
`**request.args.as_dict()` (not sure about the exact method name)

**Comment by fluffy-critter** [comment]
`to_dict()` doesn't preserve multiple keys of the same name, and even if it did, that probably wouldn't work with passing values in as kwargs.

**Comment by ThiefMaster** [comment]
` **request.args.to_dict(False)` should do the job

**Comment by fluffy-critter** [comment]
Ah, that did the trick. Thanks!
