### ISSUE TITLE
Type of SessionMixin underspecified, flask.session.get() fails strict type-check

### ISSUE THREAD

**Issue by scanny** [pallets/flask#4905]
To reproduce:
```python
from flask import session

session.get("foo")
```
Produces a pyright/Pylance error in VSCode in strict typing mode:
```
Type of "get" is partially unknown
  Type of "get" is "Overload[(__key: Unknown, /) -> (Unknown | None), (__key: Unknown, /, default: Unknown | _T@get) -> (Unknown | _T@get)]"Pylance[reportUnknownMemberType]
```
`mypy --strict` doesn't seem to mind, but it also accepts `session.get({"a": 7})` without complaint, so perhaps not a good measure.

Changing the offending line like this fixes the problem:
```python
cast(MutableMapping[str, Any], session).get("foo")
```

Based on this observation I changing this line in the `SessionMixin` declaration, which also fixes the problem:
https://github.com/pallets/flask/blob/main/src/flask/sessions.py#L21
```python
# --- from ---
class SessionMixin(MutableMapping):

# --- to ---
class SessionMixin(MutableMapping[t.Hashable, t.Any]):
```

I'm not sure if I've gotten those types exactly right, I believe they are the broadest possible types, but perhaps keys are limited to `str` or values could be narrowed.

Happy to submit a pull request if that's a help. Thanks so much for Flask, it is an immensely important contribution to the Python ecosystem I make my living in :)

Environment:

- Python version: 3.10.7
- Flask version: 2.2.2

**Comment by davidism** [comment]
I'm happy to review a pr, but otherwise will not be doing more to satisfy pyright at this time.
