### ISSUE TITLE
API Docs: typo in `tojson` example

### ISSUE THREAD

**Issue by rayanth** [pallets/flask#4906]
API Documentation since 2.0.x has included a typographical error in the code example for using the `tojson` filter in a Jinja template:

```
<script>
    const names = {{ names|tosjon }};
    renderChart(names, {{ axis_data|tojson }});
</script>
```

`names|tosjon` should be `names|tojson`

The first documentation version this occurs is in `2.0.x`, and it continues to occur through the current `latest`.

**Comment by davidism** [comment]
No need to open issues about typos, just fix them.
