### ISSUE TITLE
Logging bug when two Flask apps are initialized

### ISSUE THREAD

**Issue by azmeuk** [pallets/flask#4914]
I encountered a strange log related bug in the unit tests of a project I am working on. Here is the most minimalist snippet I could write to reproduce the bug.

The `run` method configures logs to be saved in a file, initializes an empty Flask application produces one log entry. The snippet runs the method twice, with two different log paths. The first time the method is ran, a log is actually produced in the expected log file, but not the second time.

```python
import os
import logging.config

from flask import Flask


def run(log_path):
    logging.config.dictConfig(
        {
            "version": 1,
            "formatters": {
                "default": {
                    "format": "%(message)s",
                }
            },
            "handlers": {
                "default": {
                    "class": "logging.FileHandler",
                    "filename": log_path,
                    "formatter": "default",
                },
            },
            "root": {"level": "DEBUG", "handlers": ["default"]},
        }
    )

    app = Flask(__name__)
    app.logger.info("FOOBAR")

    with open(log_path) as fd:
        assert fd.read(), "log file is empty"

    os.remove(log_path)


run("/tmp/firstlog.txt")
run("/tmp/secondlog.txt")
```

```python
Traceback (most recent call last):
  File "/path/to/flask_logging.py", line 37, in <module>
    run("/tmp/secondlog.txt")
  File "/path/to/flask_logging.py", line 31, in run
    assert fd.read(), "log file is empty"
AssertionError: log file is empty
```

This is so strange because the very same piece of code is executed twice and behave differently. It looks like the first run has side-effects on the second run.

The logging documentation indicates that `If app.logger is accessed before logging is configured, it will add a default handler.` This sound like this might be related, but in my case there are two completely different `Flask` objects.

I could solve this by different ways. None feels really right:
- Replacing `app.logger.info` with `logging.info`
- Giving a different `import_name` to the `Flask` objects on the two runs.
- Setting [disable_existing_loggers](https://docs.python.org/3/library/logging.config.html) to `False` in `dictConfig`.

Environment:

- Python version: 3.10
- Flask version: 2.2.2

**Comment by davidism** [comment]
Since `disable_existing_loggers` defaults to `True`, `app.logger.disabled` gets set to `True` on the second run, which means `logger.info` returns early without logging. This isn't something Flask can address. Aside from your suggested fixes, you could also change the handler rather than calling `dictConfig` each time.
