### ISSUE TITLE
Flask stops responding to requests if Process Pool exhausted

### ISSUE THREAD

**Issue by arch-user-france1** [pallets/flask#4923]
If there are more pending requests than the number of processes available for one client to process requests and the backend code runs forever or for a long time, flask won't respond to other requests. A typical response would be 500 - or it could start creating more processes, killing those that aren't working or at least inform the programmer.

You can easily replicate this bug by adding a route with the following code

```
def buggycode():
  import time
  while True:
     time.sleep(30)

```

Environment:

- Python version: 3.10.7
- Flask version: 2.1.3

**Comment by davidism** [comment]
Flask doesn't use a process pool. You seem to be confusing it with a WSGI server, while it is a WSGI application.

**Comment by arch-user-france1** [comment]
Oh sorry, but why is Flask multiprocessed then? And why are there stacktraces that say that processes were killed? Sure, they could be from my code, however I only use processes for dumping json files...

**Comment by ThiefMaster** [comment]
The flask dev server is for development only. You need to use a real WSGI server like uWSGI or Gunicorn for production deplyoment.

Any FWIW a 500 error is not appropriate for "overloaded". Waiting until a process/thread is available to handle a request makes much more sense. Also, your example is a good example for code that should not be running in the webapp - if something really takes much longer than a typical quick HTTP request, you may want to offload it to something like Celery.
