### ISSUE TITLE
flask does not return json

### ISSUE THREAD

**Issue by arch-user-france1** [pallets/flask#4924]
https://stackoverflow.com/questions/74690796/python-flask-request-get-json-returns-none-but-request-is-json

for whatever reason, flask decided that the request is not json and returns None instead of the json data

not sure

Environment:

- Python version: 3,10,7
- Flask version: 2.1.7

**Comment by arch-user-france1** [comment]
What???

**Comment by ThiefMaster** [comment]
Currently your error report is pretty much useless - we don't even know what exactly is being sent there!

Create a minimal demo app and provide a curl command, `requests.get()` call or similar to send a request that reproduces the problem you have.
