### ISSUE TITLE
Testing with authenticated and anonymous client at the same time gives mixed results

### ISSUE THREAD

**Issue by flixman** [pallets/flask#4930]
I want to test the unauthenticated endpoints of my application, after creating an authentication-required resource, and I am getting that the anonymous client is actually authenticated :-/.

```python
import pytest

@pytest.fixture(scope="module")
def app():
    app = create_app()
    app.test_client_class = APIAwareFlaskLoginClient
    yield app

@pytest.fixture
def client(app):
    with app.test_client() as client:
        yield client

@pytest.fixture
def authenticated_client(app):
    with app.test_client() as client:
        client.post("/api/auth/login", json=dict())
        yield client

@pytest.fixture
def create_resources(authenticated_client):
    response = authenticated_client.post('/api/myresource', json=dict())
    return response

def test_participant_not_logged_in(client, create_study):
    study_id = create_study.json['id']

    questions_response = client.get(f'/api/studies/{study_id}/questions')
    assert questions_response.status_code == 401
```
 The test test_participant_not_logged_in should fail because the client is not authenticated. When breaking on the first statement of that function I verify that the cookie jar of the client is empty (so, is not authenticated), but when hitting the url with the get... it comes as authenticated. How is this possible? I have been looking around and cannot explain this behavior. Am I doing something wrong, or this is a bug?

Environment:

- Python version: 3.10.8
- Flask version: 2.2.2

**Comment by davidism** [comment]
Nothing in your tests require `with client`, because you're not looking at `request` or `g` after a request is made. Remove the `with client` block completely. If you do need to preserve the context, use `with client` as locally as possible, only around the specific request being tested, not during an entire test.

**Comment by flixman** [comment]
@davidism I have made the changes you suggested (by the way, thank you very much), but I am still hitting the same error. This how the code looks now, with two more tests:

```python
import pytest

@pytest.fixture(scope="module")
def app():
    app = create_app()
    app.test_client_class = APIAwareFlaskLoginClient
    yield app

@pytest.fixture
def client(app):
    return app.test_client()

@pytest.fixture
def authenticated_client(app):
   client = app.test_client():
   client.post("/api/auth/login", json=dict())
   return client

@pytest.fixture
def create_resources(authenticated_client):
    response = authenticated_client.post('/api/myresource', json=dict())
    return response

def test_participant_not_logged_in(client, create_study):
    study_id = create_study.json['id']

    questions_response = client.get(f'/api/studies/{study_id}/questions')
    assert questions_response.status_code == 401

def test_participant_not_logged_in_forced_logout(client, create_study):
    client.post('/api/auth/logout')
    study_id = create_study.json['id']

    questions_response = client.get(f'/api/studies/{study_id}/questions')
    assert questions_response.status_code == 401

def test_participant_not_logged_in_forced_logout2(client):
    response = client.post('/api/auth/logout')
    assert response.status_code == 200
```
* Should I break on the first statement of test_participant_not_logged_in and look in the cookie jar of client, it shows empty. However, I am still able to do the client.get successfully (and if I break on the server side, it comes up with a user).
* on test_participant_not_logged_in_forced_logout, I am getting a "Bad request" error (because the CSRF token is missing... this error is extremely extrange, but read the next line)
* on test_participant_not_logged_in_forced_logout2, the test succeeds

So: it looks like for some reason the fixture create_study is "interfering" (for the lack of a better word) with client. I have another set of tests, on another module, that just call the unauthenticated client and all those succeed / fail as expected.

**Comment by flixman** [comment]
@davidism Forget my last comment. The problem seems to be on how flask-login is managing the authenticated user, when it is assigning the current_user and so. I am sorry for having bothered you with this. I will continue on their github project. Thank you!
