### ISSUE TITLE
Flask.inject_url_defaults() incorrectly splits Blueprint's name

### ISSUE THREAD

**Issue by ekoka** [pallets/flask#494]
The Flask.inject_url_defaults() function splits the endpoint at the wrong location to retrieve the name of the blueprint. This causes url_for() not to work properly for blueprints when combined with Blueprint.url_defaults()

e.g.
endpoint = "catalogue.admin.products.index"
bp = endpoint.split('.', 1)[0]

bp is now 'catalogue' rather than 'catalogue.admin.products'

I presume rsplit() would be more appropriate than split() for this one.

**Comment by jeffwidman** [comment]
@hyunchel I think you were looking into this at the Pycon Sprint earlier today. 

Were you able to reproduce or can this be closed?

**Comment by hyunchel** [comment]
@jeffwidman I ended up leaving a bit early while working on this.
I'm resuming my work to see if I can reproduce this issue!

**Comment by hyunchel** [comment]
According to this issue on nested blueprint(#594), current version of Flask **does not** support nested blueprint. And unless Flask is customized, I'm not sure if an endpoint could ever contain multiple dots.

Regardless, the fix with proposed and merged PR #494 allows `Flask.url_for` method to grab correct endpoint when the endpoint with nested blueprint(`foo.bar.baz.view`) is given as an argument.

To restate with clarity, the issue where `Flask.url_for` barfs with the endpoint being `foo.bar.baz.view`  is not reproducible with current [master][0].
Therefore, this issue can be closed!

[0]: 9c236d3b84332aef0c834266a0e3d2171fe5a7bd

**Comment by untitaker** [comment]
@hyunchel Thanks for your investigation!
