### ISSUE TITLE
Blueprint 404 handlers are not invoked from abort() calls in blueprint views

### ISSUE THREAD

**Issue by tucked** [pallets/flask#4944]
The docs suggest that, if a blueprint's view function calls `abort(404)`, the blueprint's `errorhandler(404)` will be called:
https://github.com/pallets/flask/blob/9da947a279d5ed5958609e0b6ec690160c496480/docs/errorhandling.rst#L397-L399
However, that does not seem to be the case:
``` python
# sscce.py

from flask import Flask, Blueprint, abort

app = Flask(__name__)
blueprint = Blueprint("", __name__)


@blueprint.route("/")
def router():
    abort(404)


@blueprint.errorhandler(404)
def handler(e):
    return "it worked", 404


if __name__ == "__main__":
    app.register_blueprint(blueprint)
    response = app.test_client().get("/")
    assert response.text == "it worked", response.text
```
``` console
$ python3.8 -m venv venv
$ venv/bin/python -m pip install flask
...
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 Werkzeug-2.2.2 click-8.1.3 flask-2.2.2 importlib-metadata-6.0.0 itsdangerous-2.1.2 zipp-3.11.0
$ venv/bin/python sscce.py
Traceback (most recent call last):
  File "sscce.py", line 22, in <module>
    assert response.text == "it worked", response.text
AssertionError: <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

```
This diff causes the handler to be called (but also causes the handler to be called for all views, not just those of the blueprint):
``` diff
@@ -11,7 +11,7 @@
     abort(404)


-@blueprint.errorhandler(404)
+@blueprint.app_errorhandler(404)
 def handler(e):
     return "it worked", 404
```

**Comment by ThiefMaster** [comment]
404s are never handled by a blueprint, because at least for a "real" 404 there is no blueprint involved in handling an invalid URL  - the URL did not match a route, and blueprints don't "own" let's say a path prefix (the url prefix of a blueprint is just appended to the routes, multiple blueprints can even have the same prefix).

I assume for consistency this is done regardless of what causes the 404 exception to be raised.

PS: Now I'm curious if `raise NotFound` has the same behavior...

**Comment by tucked** [comment]
Yes, `raise werkzeug.exceptions.NotFound` seems to behave the same way.

**Comment by davidism** [comment]
Don't give your blueprint an empty name. If you give it a name, like `"main"`, your example works.

**Comment by tucked** [comment]
Aha! So it does, thank you 👍 

Did I miss a memo/doc somewhere about that? Is there a reason `Blueprint` doesn't raise a `ValueError` when being instantiated with an empty `name`?
