### ISSUE TITLE
Switch from `setup.py` to `pyproject.toml`?

### ISSUE THREAD

**Issue by jeffwidman** [pallets/flask#4945]
Now that https://github.com/dependabot/dependabot-core/issues/3290 has shipped, it should be possible to replace this:
https://github.com/pallets/flask/blob/9da947a279d5ed5958609e0b6ec690160c496480/setup.py#L3-L17

with a `pyproject.toml` file... allowing you to completely drop `setup.py`.

Curious why you chose not to do that yet?

**Comment by davidism** [comment]
I've been on a break from open source development. I do plan on doing this. Although from a quick glance it looks like Flask-SQLAlchemy, which I switched as an experiment a while ago, no longer shows dependencies or dependants.

**Comment by jeffwidman** [comment]
Thanks for the heads up on Flask-SQLAlchemy. Since I work at GitHub I was able to check with that team and sounds like the issue was the Flask-SQLAlchemy change was pushed older than when they added support for it... They are already planning to run a backfill job for exactly this scenario, so I expect it to get refreshed in the not too distant future.

**Comment by davidism** [comment]
Done for all 6 libraries now.
