### ISSUE TITLE
Why do docs recommend opening/closing sqlite3 connection for each request?

### ISSUE THREAD

**Issue by marcospgp** [pallets/flask#4954]
In [this page](https://flask.palletsprojects.com/en/2.2.x/patterns/sqlite3/) the Flask docs present opening and closing a connection per request as the "official" way of working with sqlite3.

This does not make sense to me - surely opening and closing connections has some overhead, which can be avoided if a connection is shared across an entire application. Perhaps this overhead is negligible here, but I still couldn't get over it.

The problem is that a global connection created with `sqlite3.connect(DATABASE)` will raise an `Objects created in a thread can only be used in that same thread` error, due to the way (I assume) Flask processes web requests in worker threads.

As it turns out and [as explained here](https://ricardoanderegg.com/posts/python-sqlite-thread-safety/) this can be safely resolved by creating the connection with `sqlite3.connect(DATABASE, check_same_thread=False)` instead, as long as `sqlite3.threadsafety == 3` (the available variant of sqlite3 is in serialized mode).

Given this information, shouldn't the documentation suggest a global shared connection as the standard way of working with sqlite3?

**Comment by ThiefMaster** [comment]
If you use sqlite, performance is unlikely to be your main goal anyway. It's just something simple that works well for an example app.

In a real application you are likely using sqlalchemy or something else to maintain a connection pool and thus do not have the problem. Connecting to the sqlite database on startup / on first request just adds complexity though, for no real gain.

Also, by sharing a connection there's a good chance that you cannot have separate transactions for separate parallel requests, can you?

This is something on that topic I fond when googling "sqlite one connection per request": https://sqlite.org/forum/info/ff2fe46b1ff102bfbc78c112ea4eb25105354571b6c7551956d3cd72fe3e4624

**Comment by marcospgp** [comment]
> It's just something simple that works well for an example app.

But then maybe that should at least be made clear in the docs? Currently it is more or less implied that the presented way is the best approach.

I think this is particularly bad because one may interpret this to mean that it is always the best approach to open a connection per request, for any database!

> Also, by sharing a connection there's a good chance that you cannot have separate transactions for separate parallel requests, can you?

It does make sense that if Flask is multithreaded (perhaps you can clear this up for me), transactions that consist in more than one call to `connection.execute()` could find themselves mixed with some other thread's calls.
Although that seems like a smaller issue to me, and one that could be pointed out as a use case for having a request-specific connection.

In a way, this is also Python's fault for defaulting `check_same_thread` to True even if sqlite3 is in serialized mode. If that weren't the case, I probably wouldn't even have checked Flask's sqlite3 guide.

**Comment by davidism** [comment]
Well, we're definitely not going to do a single global connection, because that's definitely not safe. And we're not going to implement a connection pool for simple examples. The pattern of "get connection, store on g, return connection" is what's being demonstrated by the docs, and remains the same whether you're pooling or not.

Use Flask-SQLAlchemy (or just SQLAlchemy) if you need a pool. That said, even SQLAlchemy thinks that SQLite doesn't need a pool: https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#threading-pooling-behavior

> SQLite file-based connections have extremely low overhead, so pooling is not necessary. The scheme also prevents a connection from being used again in a different thread and works best with SQLite’s coarse-grained file locking.

If you're at the point where the SQLite connection is your bottleneck, you're way, way beyond the scope of this documentation.

**Comment by marcospgp** [comment]
> Well, we're definitely not going to do a single global connection, because that's definitely not safe.

@davidism Why is it so clearly not safe? Wouldn't it be similarly unsafe to have a single connection for an entire web request - which could be arbitrarily complex?

And regardless of whether we agree on the reasoning - shouldn't it be presented in the docs, so there is enough information to avoid readers having to make potentially erroneous assumptions?

The thread-global g pattern is not super elegant, and I find it hard to rely on it for database connection management. It would be great not to have to!

You have good arguments as to why this doesn't matter enough to think about - I just think what does matter is the readers - this isn't just a random documentation page, it builds up background knowledge.
