### ISSUE TITLE
ipv6 address not accessible

### ISSUE THREAD

**Issue by saquibntt** [pallets/flask#4956]
Hi,
I want to run the server on ipv6 address. I can see the port used by ipv6 address, however when called, it does not respond.

1) app.run(host='::', port=5000)
2) python -m flask run -h ::
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (::)
 * Running on http://[::1]:5000
 * Running on http://[2003:c6:4f1f:cd00:e4b0:a972:fdbb:ac6a]:5000

output of netstate
tcp6       0      0 :::5000                 :::*                    LISTEN      64170/python

Does not work for ipv6, works for ipv4 however.

Environment:

- Python version:3.8.10
- Flask version:.2.2.2

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. Using the dev server with IPv6 works fine for me.
