### ISSUE TITLE
Transactional tests

### ISSUE THREAD

**Issue by kettenbach-it** [pallets/flask#4962]
It would be good if flask-smorest could support that end-to-end tests via the REST API can be made transactional, i.e. that I can do a `rollback()` after the tests are finished and the database is therefore not touched.

**Comment by davidism** [comment]
Be sure to check which repository you're on before opening an issue.

Also, just to head off you making another issue over on Flask-Smorest, this is not under Flask-Somrest's control either. I suggest looking for resources or existing pytest plugins on how to isolate your database during testing.
