### ISSUE TITLE
docs show test_request_context data setting request args.

### ISSUE THREAD

**Issue by ablacklama** [pallets/flask#4964]
The `data` arg in `app.test_request_context()` is shown in the docs to set the request args, but as far as I can tell it isn't doing so.

I ran a minimal version of the [example in the docs](https://flask.palletsprojects.com/en/2.2.x/reqcontext/#manually-push-a-context)
```python
from flask import Flask, request
app = Flask("test_app")
def generate_report():
    format = request.args.get('format')
    print(format) # --> None

with app.test_request_context(
        '/make_report/2017', data={'format': 'short'}):
    generate_report()
```
The docs use `request.args.get('format')` which certainly implies that the data argument set there should set a request arg. But the code above just prints None. 

I assume that `data` in the example should be changed to `query_string` and that the `query_string` arg should be added to the docs [here](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.test_request_context)

Environment:

- Python version: 3.10 and 3.11
- Flask version: 2.2.2

**Comment by ablacklama** [comment]
Thanks for the fix, can you also add it as a parameter to the `test_request_context` [function doc?] (https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.test_request_context)

**Comment by davidism** [comment]
From the docs you just linked:

> Takes the same arguments as Werkzeug’s [EnvironBuilder](https://werkzeug.palletsprojects.com/en/2.2.x/test/#werkzeug.test.EnvironBuilder), with some defaults from the application. See the linked Werkzeug docs for most of the available arguments. Flask-specific behavior is listed here.

**Comment by ablacklama** [comment]
I'm aware but it seems very unintuitive based on the other arguments that are listed there. It's very easy to miss the part where it says that most arguments are listed in the linked doc. And personally, whenever docs link to other third party docs for additional arguments I always assume it's for more advanced arguments that I probably don't need to touch unless I'm really doing something funky.

I know we want to avoid listing arguments here that should be defined in (and only in) the Werkzeug docs. But perhaps a "**query_string** — see Werkzeug docs" would be appropriate? Or maybe saying "see the linked Werkzeug docs for most of the available arguments such as ..., ..., Or ..."?

I totally get it if you don't think that's appropriate though.

**Comment by davidism** [comment]
> I always assume

Don't do this, problem solved ;-)

**Comment by ablacklama** [comment]
Fair enough. And the confusion I had really stemmed from the bad example that you fixed. 

Cheers!
