### ISSUE TITLE
Tutorial Documentation Issue with --debug

### ISSUE THREAD

**Issue by ProsperousHeart** [pallets/flask#4986]
# Recap

[Run Application](https://flask.palletsprojects.com/en/2.2.x/tutorial/factory/#run-the-application) section says you should run:  `flask --app flaskr run --debug`

This provides this error:
```
(Discord) C:\Users\gradu\code\flask-tutorial>flask --app flaskr run --debug 
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: No such option: --debug (Possible options: --debugger, --no-debugger)
```

# Replication

Follow the tutorial.

# Resolution

The following should be run for it to work since `--debug` should be before `run`: 
`flask --app flaskr --debug run`

Environment:

- Python version:  3.10
- Flask version:  2.2.2

**Comment by davidism** [comment]
Update flask, it works in the latest version.

**Comment by ProsperousHeart** [comment]
@davidism this doesn't help someone who is looking at documentation on an older version
