### ISSUE TITLE
Single quotes added to ENV VARS on reload

### ISSUE THREAD

**Issue by brtobin** [pallets/flask#4988]
Our application uses an environment variable to store the path to our certificates which is used by the "hvac" and "requests" libraries to send verify requests. 

On an initial load of our Flask application, we are successfully able to make a request, and the certificate location that is passed to these libraries (sourced from the environment variable on our system) is 
`/path/to/ssl/cert.crt`

However, when we run our Flask app with `debug=True`, it causes this environment variable to be loaded with additional single quotes around it (e.g. `'/path/to/ssl/cert.crt'`). The addition of these quotes causes the path to become invalid and requests cannot be made.

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. In a sample app I created, env vars do not change between reloads.
