### ISSUE TITLE
Allow specifying reloader_type=stat via flask CLI

### ISSUE THREAD

**Issue by johnbaker32** [pallets/flask#5007]
Current behavior of enabling reloader in flask CLI (e.g. `flask --debug run`) does not allow specifying `reloader_type` parameter to `werkzeug.run_simple`: https://github.com/pallets/flask/blob/2.2.3/src/flask/cli.py#L923

The default value of `reloader_type='auto'` tries to import watchdog, and then fails back to stat if module is not found. This is problematic for environments where watchdog is installed, but stat is the preferred reloader type.

**Comment by davidism** [comment]
I don't want to expose this option to users, it's not something they should need to think about. It's not clear why you wouldn't use the Watchdog reloader if it's available, but if something isn't working you should submit an issue (and PR) about that to Werkzeug.
