### ISSUE TITLE
send_file wont accept filenames with comma

### ISSUE THREAD

**Issue by albcunha** [pallets/flask#5023]
If the user requests a file from server such as "CORAÇÕES,.html" the browser will return this error:
ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

This is caused by comma inside the filename.

if replace the name for "C,.html", it works.

To replicate this error, you can run this function:

```
send_from_directory(
        "CORAÇÕES,.html",
         as_attachment=True,
        
    )
```

Environment:

- Python version:3.10.9
- Flask version:2.2.3

Solution:
The comma can be replaced by a comma on the http header. It wont work with a commen comma, such as '"Corações,.html"', but it will work with urrllib.parse, such as:

```
from urllib.parse import quote
send_from_directory(
        "CORAÇÕES,.html",
         as_attachment=True,
         download_name=quote("CORAÇÕES,.html"),  
    )
```

Maybe we can add urrlibe.parse.quote as default for download_name?

**Comment by davidism** [comment]
We already quote the filename, but weren't using the correct set of safe characters. Already fixed by https://github.com/pallets/werkzeug/pull/2608.
