### ISSUE TITLE
URL Hack?

### ISSUE THREAD

**Issue by Rehold** [pallets/flask#5031]
![image](https://user-images.githubusercontent.com/50749933/227280757-1392b272-f997-4ef4-ba18-ccf528a01751.png)
![image](https://user-images.githubusercontent.com/50749933/227280821-4355646d-3564-4805-92c3-cecbf903e12e.png)

Im not too sure what the person was trying to do with this, but they were able to clear my MongoDB. I don't even use phpadmin so I'm not sure either what they were doing there, but yeah.

If this is just a issue with me and how i setup my site, would be nice if someone could tell me what i did wrong, since I've used flask for ages and I've never had this happen.

**new issue in comments**

**Comment by davidism** [comment]
This is not related to Flask. Bad traffic like this is normal for servers that are publicly accessible. If you have designed an insecure app that is affected by such traffic, you need to identify and address the cause of that on your own.
