### ISSUE TITLE
request json have not parsed correct?

### ISSUE THREAD

**Issue by SunYong0821** [pallets/flask#5032]
```
@user.post('/get_auth')
def get_auth():
    print(request.is_json, request.mimetype)
    username = request.json['username']
```

```
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 
True application/json
127.0.0.1 - - [24/Mar/2023 20:27:55] "POST /api/user/get_auth HTTP/1.1" 400 -
```

`curl -d "{'username':'test'}" -H "Content-Type: application/json" -X POST http://127.0.0.1:5000/api/user/get_auth`

Environment:
- Python 3.10.4
- Flask 2.2.3

why request json have not parsed correct?

**Comment by ThiefMaster** [comment]
Because you're not sending valid JSON - JSON always uses double quotes.
