### ISSUE TITLE
"Blueprint" has no attribute "register_blueprint" mypy typing error

### ISSUE THREAD

**Issue by LoopThrough-i-j** [pallets/flask#5035]
When we try to register one blueprint to another blueprint in flask getting an error from mypy: 
```sh
"Blueprint" has no attribute "register_blueprint" mypy typing error
```
This shouldn't ideally happen as described in the docs: https://flask.palletsprojects.com/en/2.2.x/blueprints/#nesting-blueprints

Environment: 
- OS: Ubuntu 22.10
- Python version: 3.10.10
- Flask version: Flask==2.2.2 Flask-RESTful==0.3.9

**Comment by Optimized-Coder** [comment]
Hi @LoopThrough-i-j great to see you reaching out and using Flask. It is a great framework. Are you using the syntax: 
```
app.register_blueprint(<bp_name>)
```
Also, have you imported Blueprint from flask and created it using:
```
bp = Blueprint(bp, __name__) 
```
It'll be great to hear an update from you, 
Josh

**Comment by davidism** [comment]
`Blueprint.register_blueprint` does exist, so if MyPy isn't seeing it then that's an issue with MyPy.

**Comment by Optimized-Coder** [comment]
> @Optimized-Coder Did you use some AI to write this answer? It makes no sense and feels more like what outsourced first-level tech support would reply to a problem they barely know... In fact, if I paste this issue into ChatGPT I get something more useful than your answer :D

I'm sorry, I'm pretty new to engaging on GitHub. If you have any genuine critical feedback for me it would be very much appreciated @ThiefMaster
