### ISSUE TITLE
App.json_provider_class has no effect is defined after app creation

### ISSUE THREAD

**Issue by azro352** [pallets/flask#5052]
Hi

### What happens

When setting `json_provider_class` after app creation, it has no effect, because you only set a variable, and it doesn't update `app.json` which is used after

```python
app = Flask(__name__)
app.json_provider_class = CustomProvider
```

It does work if you do the following :

```python
Flask.json_provider_class = CustomProvider
app = Flask(__name__)
```

And of you course if you do the following, but I find it a bit verbose

```python
app = Flask(__name__)
app.json = CustomProvider(app)
```
### Expectation

I expect either 

- `app.json_provider_class = CustomProvider` to work
- `Flask.json_provider_class = CustomProvider` to be explicitly documented 

### How to solve

I let you decide what you prefer. 

I can provide a PR for the first one, I'll just change  variable `json_provider_class: t.Type[JSONProvider] = DefaultJSONProvider` to a getter+setter that updates `self.json` as it is done in the `__init__` `self.json: JSONProvider = self.json_provider_class(self)`. 

Environment:

- Python version: 3.10
- Flask version: 2.2.3

**Comment by davidism** [comment]
That's correct, set `app.json = CustomProvider(app)` instead, the class attribute is for customizing at the class level, not the instance level.

**Comment by davidism** [comment]
From the docs https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask.json

> An instance of `json_provider_class`. Can be customized by changing that attribute on a subclass, or by assigning to this attribute afterwards.

**Comment by azro352** [comment]
Got it 
It wasn't obvious for me that it would have no effect on an instance regarding the docs 

How do you decide to put some property at class level or at instance level ?
