### ISSUE TITLE
Docs: chat assistant

### ISSUE THREAD

**Issue by rlew631** [pallets/flask#5055]
Proposal:
Use OpenAI (or other LLM) API to allow users to query the docs interactively with a chatbot assistant. For building it would involve chopping up the documentation into each section and storing them in a vector database like chroma, weviate, pinecone, supabase etc and using langchain as the back end to pre-prompt the LLM. The LLM would then query the vector database for the relevant section and return a nuanced answer to the user's question. It would look very similar to what supabase is working on with clippy for their docs: https://supabase.com/blog/chatgpt-supabase-docs . 

What it changes:
This would be a change to the doc site and not to Flask itself. It would also require an openAI api key (or another LLM or access to a self hosted LLM). I'm currently building out a version myself as part of a learning project but it will have a cap on the number of queries that can be asked since my spend limit on OpenAI is $30/month.

**Comment by davidism** [comment]
Absolutely not.
