### ISSUE TITLE
Allow to not trim prefixes on Config.from_prefixed_env

### ISSUE THREAD

**Issue by Zocker1999NET** [pallets/flask#5060]
`Config.from_prefixed_env` is quite helpful to automatically import configuration from the environment variables. However, I ran into the issue that I want to use it together with the `Config.get_namespace` feature, which itself requires a certain prefix, to configure extensions to Flask (PonyORM in my case) using environment variables.

I thought about using the prefix `PONY_` for the namespace, however with the current implementation, the environment variables must be called something like `FLASK_PONY_*` or `PONY_PONY_*` so they can be imported using `from_prefixed_env` to retain a prefix to then be correctly returned by `get_namespace`.

I know that this is theoretically possible without changing Flask by implementing the required variant for from_prefixed_env in my own app, however, I think this feature might be helpful to other Flask users, especially together with `get_namespace`.

**Comment by davidism** [comment]
> `FLASK_PONY_*`

This is deliberate, it keeps everything related to the Flask app in the same "namespace". You can even change the prefix so you can have different apps/instances without mixing their config.
