### ISSUE TITLE
CONTRIBUTING: Change from venv name "env" to ".venv" for Windows as well?

### ISSUE THREAD

**Issue by Zocker1999NET** [pallets/flask#5062]
https://github.com/pallets/flask/blob/182ce3dd15dfa3537391c3efaf9c3ff407d134d4/CONTRIBUTING.rst?plain=1#L123-L124

I think in line 124 `env` should also be renamed to `.venv`

**Comment by davidism** [comment]
9a4d370e

For future reference, you don't need to report docs typos, it's faster to submit a PR.
