### ISSUE TITLE
Cannot import Markup from flask

### ISSUE THREAD

**Issue by lucaswerkmeister** [pallets/flask#5084]
`from flask import Markup` and `flask.Markup` both don’t work. This is merely supposed to be deprecated, not broken, in Flask 2.3.0.

Example A:
```python
import flask

print(flask.Markup('hi'))
```
```
Traceback (most recent call last):
  File "/tmp/flask230/1.py", line 3, in <module>
    print(flask.Markup('hi'))
  File "/tmp/flask230/venv/lib/python3.10/site-packages/flask/__init__.py", line 102, in __getattr__
    raise AttributeError(name)
AttributeError: Markup
```

Example B:
```python
from flask import Markup

print(Markup('hi'))
```
```
Traceback (most recent call last):
  File "/tmp/flask230/2.py", line 1, in <module>
    from flask import Markup
ImportError: cannot import name 'Markup' from 'flask' (/tmp/flask230/venv/lib/python3.10/site-packages/flask/__init__.py)
```

Environment:

- Python version: 3.10.10
- Flask version: 2.3.0

**Comment by HK-Mattew** [comment]
I just had this problem on my website as well. I had to go back to the Flask==2.2.3 version of flask to get it working properly again.

**Comment by davidism** [comment]
PyPI's upload API is down at the moment, I will retry the release later.

**Comment by davidism** [comment]
Flask 2.3.1 is now available on PyPI.
