### ISSUE TITLE
Possible regression ver 2.3.1 module 'flask.json' has no attribute 'JSONEncoder'

### ISSUE THREAD

**Issue by chrisinmtown** [pallets/flask#5094]
I use connexion ver 2.14.2 which imports flask. Today my docker build picked up a new Flask version 2.3.1 and the tox tests fail.  I get similar results on startup when using Flask versions 2.3.0 and 2.3.1:
```
our_module/__init__.py:9: in <module>
    import connexion
.tox/code/lib/python3.9/site-packages/connexion/__init__.py:32: in <module>
    from .apps.flask_app import FlaskApp
.tox/code/lib/python3.9/site-packages/connexion/apps/flask_app.py:151: in <module>
    class FlaskJSONEncoder(json.JSONEncoder):
E   AttributeError: module 'flask.json' has no attribute 'JSONEncoder'
```

When I pinned Flask to version 2.2.4 it works fine. Of course this could be a problem over in *connexion*, or something I need to do differently to use the latest Flask. I'll go re-re-recheck your release notes. 

Please comment, thanks in advance!

Environment:

- Python version: 3.9
- Flask version: 2.2.4 is ok,

**Comment by davidism** [comment]
From the changelog:

> Remove previously deprecated code. [#4995](https://github.com/pallets/flask/pull/4995)

This would be a bug in connexion, sounds like they have not updated to be compatible with Flask 2.3. If they had run their tests with warnings treated as errors, they would have seen this when 2.2 was released last year and been able to update proactively.

**Comment by chrisinmtown** [comment]
Thank you for the instant answer!

**Comment by davidism** [comment]
Looks like it was already fixed in connexion: https://github.com/spec-first/connexion/issues/1576 be sure to search closed issues first before reporting new issues.
