### ISSUE TITLE
Cookie Expiry not working with Werkzeug upgrade

### ISSUE THREAD

**Issue by BobACollins** [pallets/flask#5103]
This looks like a regression in session expiry during testing I'm getting trying to upgrade Werkzeug to the latest version. But, I'm not sure which library to report between flask-login, werkzeug and flask. Happy to repost or restructure!

I'm overriding session expiry to set a cookie with custom expiry times. My test for this broke although my manual testing seems to work fine. So, I simplified my code to build this small minimal working example. If Werkzeug is `2.3.2` the session won't be expired despite being in the past. If I downgrade back to `2.2.2` the test will pass showing the cookie is being rejected.

main.py
```python
from datetime import datetime

from flask import Flask, jsonify
from flask.sessions import SecureCookieSessionInterface, SessionMixin
from flask_login import LoginManager, UserMixin, login_required, login_user


class CustomSessionInterface(SecureCookieSessionInterface):
    def get_expiration_time(
        self, app: "Flask", session: SessionMixin
    ) -> datetime | None:
        return datetime(2001, 1, 1, 12, 0, 0)


app = Flask(__name__)
login_manager = LoginManager(app=app)

app.config["SERVER_NAME"] = "test.fakedomain"
app.config["DEBUG"] = True
app.config["PROPAGATE_EXCEPTIONS"] = True
app.config["SECRET_KEY"] = "mysecretkey"
app.session_interface = CustomSessionInterface()


class User(UserMixin):
    def __init__(self, id):
        self.id = id

    def is_active(self):
        return True


@login_manager.user_loader
def load_user(user_id):
    return User(user_id)


@app.route("/login")
def login():
    user = User(1)
    login_user(user)
    return "Logged in successfully!"


@app.route("/protected")
@login_required
def protected():
    return jsonify({"status": "success"})
```

test_app.py
```python
import unittest

from flask import url_for
from flask_login import current_user
from main import app


class TestApp(unittest.TestCase):
    def setUp(self):
        self.app = app.test_client()
        self.app_context = app.app_context()
        self.app_context.push()

    def tearDown(self):
        self.app_context.pop()

    def test_login_and_access_protected_route(self):
        with self.app:
            with app.app_context():
                response = self.app.get(url_for("login"))
                self.assertEqual(response.status_code, 200)
                self.assertTrue(current_user.is_authenticated)

        with self.app:
            response = self.app.get(url_for("protected"))
            self.assertEqual(response.status_code, 401)
 ```

Environment:

Python 3.10.6
pip freeze:
```
click==8.1.3
Flask==2.2.4
Flask-Login==0.6.2
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.2
Werkzeug==2.3.2
```

**Comment by davidism** [comment]
Update Werkzeug

**Comment by davidism** [comment]
The test client no longer takes cookie expiration/age into account except to delete cookies if the timestamp is set to 0. https://github.com/pallets/werkzeug/issues/1680#issuecomment-1483222185 Tests that depend on the current date are unreliable, and testing that cookies expire when they expire is testing that browsers work like browsers, not anything about your Flask application. If you need to test that a specific date was set, use `assert client.get_cookie("key").expires == datetime(...)`.

---

Unrelated, but doing `with self.app` (which is misnamed, it's the client not the app), and `with app.app_context` around every request is incorrect. Neither of them are necessary. Only push an app context if you need to set something on `g` ahead of time, or to test something outside a request. Only push the client if you need to check something on `request` after the request is made.

**Comment by BobACollins** [comment]
Thanks! That solves my issues!
