### ISSUE TITLE
Uploading a file adds blank line at top of the file.

### ISSUE THREAD

**Issue by joseph2rs** [pallets/flask#5113]
When uploading or saving a file, a empty line is added at the top of the file.

Version impacted : at least 2.2.5

Working version : 2.2.2

## Reproduction :

```python
@app.route("/", methods=["POST"])
def upload_files():
    for file in request.files.getlist("files"):
        filepath = os.path.join(app.config.get("UPLOAD_FOLDER"), secure_filename(file.filename))
        file.save(filepath) 
```
### Current behavior :

The file has a blank line at the top (new line)

### Expected behavior :

The file is uploaded as is. (Working as expected on 2.2.2)

Environment:

- Python version: 3.10.11
- Flask version: 2.2.5

**Comment by joseph2rs** [comment]
Ok i thinks it's related to https://github.com/pallets/werkzeug/issues/2675 .

I let this open to have confirmation the issue is resolved.

**Comment by davidism** [comment]
Update Werkzeug
