### ISSUE TITLE
Bug with app.config.from_file

### ISSUE THREAD

**Issue by ughstudios** [pallets/flask#5117]
I like to use groups on my toml file to organize code. But flask does not seem to understand this. It will simply create config like this:

```
config = {
   'flask': { 'debug': True, 'SECRET_KEY': ''}
}
```

```
[flask]
DEBUG = true
SECRET_KEY = ""

[database]
SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite'
SQLALCHEMY_BINDS = {}
SQLALCHEMY_TRACK_MODIFICATIONS = false
```

Can we add an argument on the `from_file` method so that I do not have to do any manual modification of my toml files, or any manual modification after loading from the toml file in my python code? I should not have to do this. This seems like a bug.

**Comment by ughstudios** [comment]
Having to write code like this:


```
import toml

# Load the config file using the toml package
with open('config.toml', 'r') as f:
    config_dict = toml.load(f)

# Extract the Flask config options from the dictionary
flask_config = config_dict['flask']

# Set the Flask config options on the app
for key, value in flask_config.items():
    app.config[key.upper()] = value


```


Defeats the entire purpose of the from_file method

**Comment by jayanth-kumar-morem** [comment]
In order to resolve the issue, you can create a custom method for loading the TOML file and setting the Flask app's configuration. This method will handle nested TOML groups and update the Flask app's configuration accordingly.

1. First, you can create a helper function to flatten the nested TOML dictionary:

```python
def flatten_config(config_dict, parent_key='', sep='_'):
    flattened = {}
    for key, value in config_dict.items():
        new_key = f"{parent_key}{sep}{key}" if parent_key else key
        if isinstance(value, dict):
            flattened.update(flatten_config(value, new_key, sep=sep))
        else:
            flattened[new_key] = value
    return flattened
``` 

2. Then, create a custom from_toml_file method that loads the TOML file, flattens the nested configuration, and sets the Flask app's configuration:

```python
import toml
from flask import Flask

app = Flask(__name__)

def from_toml_file(app, toml_file):
    # Load the config file using the toml package
    with open(toml_file, 'r') as f:
        config_dict = toml.load(f)

    # Flatten the config dictionary
    flattened_config = flatten_config(config_dict)

    # Set the flattened config options on the app
    for key, value in flattened_config.items():
        app.config[key.upper()] = value

# Usage:
from_toml_file(app, 'config.toml')
``` 

Now you can use the from_toml_file method to load your TOML configuration file without having to manually modify the file or the Python code. This will handle the nested TOML groups and update the Flask app's configuration accordingly.

**Comment by ThiefMaster** [comment]
I'm pretty sure that TOML groups, like ini categories or yaml dict keys, are not arbitrary but result in nested data. But flask's config is flat. It would be really weird if you could randomly nest things. Maybe just use comments as "category headers" instead?

Of course nothing stops you from writing your own config parsing logic where settings are categorized. But honestly, I would then handle those settings manually and simply populate flask settings where needed.

**Comment by ughstudios** [comment]
> 



> In order to resolve the issue, you can create a custom method for loading the TOML file and setting the Flask app's configuration. This method will handle nested TOML groups and update the Flask app's configuration accordingly.
> 
>     1. First, you can create a helper function to flatten the nested TOML dictionary:
> 
> 
> ```python
> def flatten_config(config_dict, parent_key='', sep='_'):
>     flattened = {}
>     for key, value in config_dict.items():
>         new_key = f"{parent_key}{sep}{key}" if parent_key else key
>         if isinstance(value, dict):
>             flattened.update(flatten_config(value, new_key, sep=sep))
>         else:
>             flattened[new_key] = value
>     return flattened
> ```
> 
>     2. Then, create a custom from_toml_file method that loads the TOML file, flattens the nested configuration, and sets the Flask app's configuration:
> 
> 
> ```python
> import toml
> from flask import Flask
> 
> app = Flask(__name__)
> 
> def from_toml_file(app, toml_file):
>     # Load the config file using the toml package
>     with open(toml_file, 'r') as f:
>         config_dict = toml.load(f)
> 
>     # Flatten the config dictionary
>     flattened_config = flatten_config(config_dict)
> 
>     # Set the flattened config options on the app
>     for key, value in flattened_config.items():
>         app.config[key.upper()] = value
> 
> # Usage:
> from_toml_file(app, 'config.toml')
> ```
> 
> Now you can use the from_toml_file method to load your TOML configuration file without having to manually modify the file or the Python code. This will handle the nested TOML groups and update the Flask app's configuration accordingly.



Flask's code should be updated so that users do not have to write additional code like this.,
