### ISSUE TITLE
Cyclomatic complexity improvements

### ISSUE THREAD

**Issue by BMaxV** [pallets/flask#5118]
Hi, 

I found this hammer called "cyclomatic complexity" and a tool "radon" on pypi and I built my own tool on top of it. Now I'm looking for nails. In short it's a method to evaluate code quality and I could make small improvements to the code?

E.g. 
https://github.com/pallets/flask/blob/main/src/flask/app.py#L867

turning
```
if not host:
    if sn_host:
        host = sn_host
    else:
        host = "127.0.0.1"

if port or port == 0:
    port = int(port)
elif sn_port:
    port = int(sn_port)
else:
    port = 5000
```
into small functions like this 
```
def decide_on_default_host(self, host, sn_host)
    if not host:
        if sn_host:
            host = sn_host
        else:
            host = "127.0.0.1"
        return host

def decide_on_default_port(self, port, sn_port)
    if port or port == 0:
        port = int(port)
    elif sn_port:
        port = int(sn_port)
    else:
        port = 5000
    return port
```
and then using them in place of the old blocks.

Here are some links:
https://pypi.org/project/radon/
https://radon.readthedocs.io/en/latest/commandline.html#the-cc-command
https://en.wikipedia.org/wiki/Cyclomatic_complexity

An example of the problem which this feature
would resolve. Is this problem solvable without changes to Flask, such
as by subclassing or using an extension?

It's not a defect or shortcoming, Flask does not "need" changing. The aim is to make the source easier to read, that's all.

Flask looks pretty good though, the only "D" is `Blueprint.register` https://github.com/pallets/flask/blob/main/src/flask/blueprints.py#L273

Let me know if this kind of contribution is something you want.

Regards

**Comment by davidism** [comment]
Thanks for looking at this, but we generally don't do these sorts of refactors.
