### ISSUE TITLE
Flask 2.3.2 is not compatible with Flassger

### ISSUE THREAD

**Issue by nagamanickamm** [pallets/flask#5119]
Flask 2.3.2 is not compatible with Flassger

Description:
After upgrading Flask to latest version we are getting below error.

```
from flasgger import Swagger
  File "C:\Python310\lib\site-packages\flasgger\__init__.py", line 10, in <module>
    from .base import Swagger, Flasgger, NO_SANITIZER, BR_SANITIZER, MK_SANITIZER, LazyJSONEncoder  # noqa
  File "C:\Python310\lib\site-packages\flasgger\base.py", line 28, in <module>
    from flask.json import JSONEncoder
ImportError: cannot import name 'JSONEncoder' from 'flask.json' (C:\Python310\lib\site-packages\flask\json\__init__.py)
```

After downgrading flask to 2.2.3, it works again!

Environment:

- Python version: 3.10.10
- Flask version: 2.3.2
- Flassger: Latest

**Comment by ThiefMaster** [comment]
This is not for Flask but for Flassger. And it looks like they already have a PR to fix it: https://github.com/flasgger/flasgger/pull/564
They just need to release a version containing that fix.
