### ISSUE TITLE
AttributeError: 'Flask' object has no attribute 'before_first_request'

### ISSUE THREAD

**Issue by dirtycomputer** [pallets/flask#5123]
When I run code in [deepzoom](https://github.com/openslide/openslide-python/blob/main/examples/deepzoom/deepzoom_multiserver.py), it gives me **AttributeError: 'Flask' object has no attribute 'before_first_request'**
<img width="659" alt="截屏2023-05-12 18 25 03" src="https://github.com/pallets/flask/assets/48406770/fa211b95-b545-4fa0-be8b-94c8b98a85c8">
I don't known anything about flask. I'm just a student who want to view the image.
Can I replace this line with something simple?

**Comment by RonnyPfannschmidt** [comment]
as per https://github.com/pallets/flask/blob/main/CHANGES.rst#version-230 - version 2.3.0 removed those
so you need to use a older version of flask

**Comment by bgilbert** [comment]
For the record, this was fixed in OpenSlide Python in https://github.com/openslide/openslide-python/pull/200.

**Comment by davidism** [comment]
@bgilbert I won't object super strongly, since using the factory pattern is good in general. But it doesn't look like you actually needed to do that, you should have been able to do whatever was in `before_first_request` right next to the other setup you were doing, without other restructuring.

**Comment by bgilbert** [comment]
Thanks for looking!  The code is designed to be run either manually from the command line or via a WSGI wrapper.  I switched to a factory function because the WSGI wrapper needs to call a setup function that skips the command-line parsing.
