### ISSUE TITLE
Unexpected HTML in JSON

### ISSUE THREAD

**Issue by xi** [pallets/flask#5138]
I work with a class like this:

```python
class Reference:
    def __init__(self, url):
        self.url = url

    def __str__(self):
        return self.url

    def __html__(self):
        markup = Markup('<a href="%s" class="ref">%s</a>')
        return markup % (self.url, self.url)
```

This works well when I use this in a HTML template. However, when I include such an object in a JSON response, I get the HTML markup instead of the string version. I can think of very few cases in which that is useful.

This is a minor inconvenience because I can manually convert the object to a string before including it in the JSON response. But still, maybe this could be improved. I can think of different options:

- Do not use `__html__()` in jsonify
- Use `__str__()` in jsonify, with a higher priority than `__html__()`
- Use a new method `__json__()` in jsonify, with highest priority

The last option has the benefit of being backwards-compatible.

**Comment by davidism** [comment]
If you need specific control over the object-to-structure conversion before serialization, then you want a library such as marshmallow, cattrs, pydantic, etc.
