### ISSUE TITLE
Switch to importlib breaks scripts with `app.run()`

### ISSUE THREAD

**Issue by The-Compiler** [pallets/flask#5160]
With a trivial script [using `app.run()`](https://flask.palletsprojects.com/en/2.3.x/server/#in-code) such as:

```python3
from flask import Flask

app = Flask(__name__)

if __name__ == "__main__":
    app.run(debug=True)
```

The current git `main` breaks with:

```pytb
Traceback (most recent call last):
  File "/home/florian/tmp/flask/app.py", line 3, in <module>
    app = Flask(__name__)
          ^^^^^^^^^^^^^^^
  File "/home/florian/tmp/flask/src/flask/app.py", line 376, in __init__
    instance_path = self.auto_find_instance_path()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/flask/src/flask/app.py", line 630, in auto_find_instance_path
    prefix, package_path = find_package(self.import_name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/flask/src/flask/scaffold.py", line 898, in find_package
    package_path = _find_package_path(import_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/flask/src/flask/scaffold.py", line 858, in _find_package_path
    spec = importlib.util.find_spec(root_mod_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 114, in find_spec
ValueError: __main__.__spec__ is None
```

This seems to be a regression due to 84e11a1e827c0f55f9b9ee15952eddcf8a6492e0 from #5157.

Environment:

- Python version: 3.11.4
- Flask version: git main

**Comment by davidism** [comment]
Thanks for catching this before it got released.

**Comment by davidism** [comment]
The second half of the code in `_find_package_path` seems redundant now that we can only use `importllib.util.find_spec` and not `pkgutil.get_loader`. I'm not entirely clear how it was doing much even before that.

**Comment by The-Compiler** [comment]
Looking great now, thanks!

> Thanks for catching this before it got released.

I run a [nightly CI workflow](https://github.com/qutebrowser/qutebrowser/blob/master/.github/workflows/bleeding.yml) which [installs all dependencies from VCS](https://github.com/qutebrowser/qutebrowser/blob/master/misc/requirements/requirements-tests-bleeding.txt) - I can only recommend more projects to do so, it's a great way to catch and report problems before they turn into bigger problems :)
