### ISSUE TITLE
Config.from_file() feeds descriptor, not string to tomllib.loads()

### ISSUE THREAD

**Issue by smitty1eGH** [pallets/flask#5164]
**outline of what the bug is:**

https://github.com/pallets/flask/blob/main/src/flask/config.py#L236 

...has us loading from a .toml file path

**Describe how to replicate the bug.**

https://docs.python.org/3/library/tomllib.html provides `load()` for `rb` files, and `loads()` for .toml strings.

**Describe the expected behavior that should have happened but didn't.**

To get to desired behavior, I added another function to read in the .toml and provide it to tomllib.loads()

```
import tomllib
from flask import Flask


def tomllib_loads(fp):
    return tomllib.loads(fp.read())


def create_app(config_filename):
    app = Flask(__name__)
    app.config.from_file(config_filename, load=tomllib_loads, silent=False, text=True)

    @app.route("/hello")
    def hello():
        return "Hello, World!"

    return app

```

Environment:

- Python version: 3.11.3
- Flask version: 2.3.2

**Comment by davidism** [comment]
I don't understand what you're reporting. Please show the code that's not working.

**Comment by smitty1eGH** [comment]
Instead of 

`app.config.from_file(config_filename, load=tomllib.load, silent=False, text=True)`

... as in the documentation, I needed a helper:

```
tomllib_loads(fs):
    return tomllib.loads(fp.read())
```

So that I could say

`app.config.from_file(config_filename, load=tomllib_load, silent=False, text=True)`

to provide the .toml content string to `from_file()` instead of the .toml file path.

Regret the lack of clarity.
