### ISSUE TITLE
Uberweb: An idea for flask web-app generator

### ISSUE THREAD

**Issue by Paradoxer32** [pallets/flask#5181]
Hello, there!
Thank you for this great project.

I've an idea for flask project : A Flask Web-app generator, just for fun ! (Like 'Django', 'Express.js', or something these)
It's call 'Uberweb'.
For more information, you can visit its git repository -> [UberWeb](https://github.com/Paradoxer32/uberweb)
Tell me your ideas about that.
If you liked, develop it or introduce it in flask docs !

Have a nice time !
-Ahoora

**Comment by davidism** [comment]
We don't plan to add projects like this to Flask itself. You'll also want to check out projects like https://github.com/cookiecutter-flask/cookiecutter-flask amd other project templates.
