### ISSUE TITLE
Give possibility to change the MAX_FORM_PARTS of werkzeug

### ISSUE THREAD

**Issue by Always-prog** [pallets/flask#5203]
## Adding  MAX_FORM_PARTS to the config of flask
This feature allows for the customization of the maximum number of form parts when reading a request. The max_form_parts parameter has been introduced in Werkzeug version 2.2.3 - https://github.com/pallets/werkzeug/blob/4048509fb24196df67f944a24aaa4ce1afcba92f/src/werkzeug/wrappers/request.py#L90.

Real use case: Apache Superset uses Flask-AppBuilder for editing user roles in the application. Currently, when there are roles with 1000+ users, the editing process fails with a 413 error due to the max_form_parts limit, which cannot be changed in the current version of Flask.

**Comment by ThiefMaster** [comment]
You can already do that. Subclass the Request class and set `max_form_parts = ...` on it. And set `request_class = YourRequestClass` on your Flask instance (or a custom subclass thereof).

Also IIRC we reverted this to only apply to multipart requests (you typically only use those if you also have a file upload field), so if it's just normal form fields, then it should usually be fine.
