### ISSUE TITLE
After initialization/before run hook

### ISSUE THREAD

**Issue by zx80** [pallets/flask#5209]
I'm writing a Flask extension with non trivial setup and the need to do consistency checks before allowing it to run.
I have not found a hook/signal which would tell me that Flask is ready to run, before any request has arrived, so that I could plug these checks. Such a hook would be appreciated. Waiting for the first request is too late to report a configuration error.

**Comment by ThiefMaster** [comment]
why can't you do it during `init_app()`?

**Comment by zx80** [comment]
I assume that you suggest that the user code should invoke some method to tell that the setup is done so that checks can be performed.
If the user has to do it, they could do it at the wrong time (eg some initialization may depend on import ordering), or even forget it.
I do not think that the user should have to bother about that, it is no their problem, it belongs to the framework which should probably known when it is ready to run or running. Hopefully.
If I want to check that the user has not forgotten, it means clobbering every entry point with a check, which is a pain and a loss of cpu time.

**Comment by zx80** [comment]
Note that there is an *internal* `_check_setup_finished` thingy in `Flask`, which suggest that it knows about this event, but is not exposed to extensions or users.

**Comment by ThiefMaster** [comment]
My point was that if you want to use a flask extension, you eventually need to do `your_ext = YourExtension(app)` or `your_ext = YourExtension()` and later (again once the configuration has been fully loaded) call `your_ext.init_app(app)`.

So there's already a well-defined initialization flow someone using Flask and Flask extensions needs to follow. There should not be a need for additional initialization beyond that.

Then again, if you do something "special", you'll have to come up with something more something concrete... "*a Flask extension* with non trivial setup" makes it really hard to explain what you *should* do in case of any special requirements.

**Comment by zx80** [comment]
Hmmm… it seems that you do not need to really understand the issue to close it… If I may add something on the closed issue:

> My point was that if you want to use a flask extension, you eventually need to do `your_ext = YourExtension(app)` or `your_ext = YourExtension()` and later (again once the configuration has been fully loaded) call `your_ext.init_app(app)`.

No, I do not *need* that. I need that **only** if I do not have the appropriate hooks. Calling both the constructor and then some `init_app` looks like stammering and is best avoided if not strictly necessary, which is the case here.

> So there's already a well-defined initialization flow someone using Flask and Flask extensions needs to follow.

No, it does not *need* to, at least in this case. The extension overrides some Flask features to extend them so the pattern is *not* to use it with the usual extension pattern, but to use Flask simple direct pattern, which is must simpler for the user:

```python
from TheExtension import Flask
app = Flask(...)
app.config.from_envvar("APP_CONF")

@app.get("/foo", authorize="READER", auth="basic", realm="whatever")
def get_foo(...):
    # users authentified with a basic scheme in realm whatever and in group READER can get here
    …
```

> There should not be a need for additional initialization beyond that.

Yes and no. I want not to *need* the second initialization call because it may be placed or executed at the wrong time
quite easily. To avoid that, I wish I had a hook. I do without but with stupid code that I could move if I had a hook.
 
> Then again, if you do something "special", you'll have to come up with something more something concrete... "_a Flask extension_ with non trivial setup" makes it really hard to explain what you _should_ do in case of any special requirements.

I do not know if I do something *special*. If you are interested to understand what it does, the extension [FlaskSimpleAuth](https://github.com/zx80/flask-simple-auth). Note that it already works with stupid code which performs the checks at the last possible moment, currently when adding a route so I can assume that all configuration setup have been managed by then. If I had an appropriate hook I could remove the stupid code.

ISTM that other extensions could benefit from this kind of additional hooks/signals as well.

**Comment by ThiefMaster** [comment]
I have the feeling you misunderstand what flask extensions are / how they work... Flask extensions do not subclass the original Flask class (even though doing so is perfectly fine, but typically not in an extension). They are registered on a Flask instance, by one of the two methods I explained.

**Comment by zx80** [comment]
> I have the feeling you misunderstand what flask extensions are / how they work... Flask extensions do not subclass the original Flask class (even though doing so is perfectly fine, but typically not in an extension). They are registered on a Flask instance, by one of the two methods I explained.

Ok, the stuff I wrote may not a Flask *extension* per-se as it subclasses (not really, but in appearance yes) Flask.
Note that it can be used as an extension as well, but I prefer not to advertise it because using it as an extension weakens the security guaranties the framework wants to provide.

Now, this *not-really-a-Flask-extension* but *kind-of-wrapper-around* flask would benefit from a hook or signal which would tell when the configuration is done so that configuration consistency checks could be performed. If these checks are not performed, some route will fail miserably when invoked by a client, so they are somehow performed, but too late.

The underlying software engineering issue is that the extension provide hooks so that the user can change some features, eg how to check a password, if they do not like the very reasonable default provided, or really need something else (eg LDAP or whatever). Because these changes or additions can be declared here and there, possibly with decorators, in different files imported in pseudo-random orders, the code cannot know easily when these initialization are done and consistency checks can be performed, eg it is not obvious that a custom authentication scheme registration is performed *before* a route requires it. In order to circumvent this ordering issue, some checks are deferred to *later*, and this later would be nicely implemented if there was an *after initialization* hook where the framework knows that settings will not change further. I suspect that this already exists *inside* flask, but is not accessible.

**Comment by davidism** [comment]
WSGI has no hook into the application lifecycle separate from each worker creating the app while handling requests. What you're asking for is not possible. If you're subclassing Flask, you're already telling users to do something custom. It's ok to tell them to call `app.finalize_setup()` or something at the end of their app factory function.

**Comment by zx80** [comment]
Ok, WSGI does not cooperate:-(

My current work around is to do the checks when adding a route, i.e. I assume that all initializations (configuration, hook registering, ...) are done when `app.route` is called. This means that some checks which can change because they also depend on route settings are done over and over again… So I was naïvely hoping for a miraculous hook. I'll keep my stupid code and chicken and egg issue instead. I do not want to do that in some finalize setup function, because the user may/will certainly forget to call it.

Thanks for the answer.

**Comment by davidism** [comment]
Glad we could clear it up. Just a heads up for next time, telling maintainers "it seems that you do not need to really understand the issue to close it" isn't a good way to interact in the future. Clearly, we are deeply experienced with what is possible and what we want in the library, assuming otherwise isn't productive.

**Comment by zx80** [comment]
Please accept my apology for my occasional rudeness in expressing myself.

Note that closing an issue while the discussion is not yet fully concluded for some participant can feel a little bit like a "shut up". However, providing a clear answer is very nice, so thanks again.

Have a nice day/night/whatever!
