### ISSUE TITLE
Application Dispatching Docs Reference Removed `werkzeug` Function

### ISSUE THREAD

**Issue by dtreichler** [pallets/flask#5214]
The ["Dispatch by Path" section of app dispatching docs](https://github.com/pallets/flask/blob/main/docs/patterns/appdispatch.rst#dispatch-by-path) reference now-removed functions, `werkzeug.wsgi.peek_path_info` and `werkzeug.wsgi.pop_path_info`.

These functions were [deprecated in Werkzeug 2.2.0](https://github.com/pallets/werkzeug/pull/2461) and [removed in Werkzeug 2.3.0](https://github.com/pallets/werkzeug/pull/2592).

Using the documented example as-is produces `ImportError`s.

Since Flask 2.3 requires Werkzeug 2.3.6 or later, the documentation contain an example that works with Werkzeug's updated API. 

Environment:

- Python version: 3.9
- Flask version: 2.3.2

**Comment by davidism** [comment]
Happy to review a PR.

**Comment by dtreichler** [comment]
I'm not familiar enough with `Werkzeug` and these more advanced patterns to know what the proper solution would be.

**Comment by dtreichler** [comment]
Thank you, @davidism!

**Comment by dtreichler** [comment]
Thank you @pavithra-m13 and @davidism!
