### ISSUE TITLE
flask out of memory

### ISSUE THREAD

**Issue by lslstudy** [pallets/flask#5221]
1. use Flask create an app in manage.py and register blueprint.
2. In back_controller, ping_test return a simple dict and memory_test show memory usage with pyhon gc module.
3. In test_interface, for loop request multiple times, and memory out happed. 

- [structure](https://i.stack.imgur.com/1JL5T.png) 
- [manage.py](https://i.stack.imgur.com/s85oI.png) 
- [common.py](https://i.stack.imgur.com/wHDNz.png) 
- [back_controller.py](https://i.stack.imgur.com/9Ef5A.png) 
- [test_interface.py](https://i.stack.imgur.com/opOnc.png) 
- [first memory usage detail](https://i.stack.imgur.com/EUOqr.png) 
- [last memory usage detail](https://i.stack.imgur.com/cNieJ.png) 
- [pip list](https://i.stack.imgur.com/SepEx.png)

**Comment by ThiefMaster** [comment]
Posting code as images is rude. If there's an actual issue, create a minimal reproducer repo. WITHOUT your data science stack.
