### ISSUE TITLE
cannot install `dependencies = [ "flask>=2.3.2", ]` in toml file 

### ISSUE THREAD

**Issue by INF800** [pallets/flask#5240]
This is happening in google colab environment. Causes:

```
ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

This is my toml file: https://github.com/anarchy-ai/LLM-VM/blob/main/pyproject.toml

**Comment by ThiefMaster** [comment]
That error is clearly something related to your environment and not related to Flask...
