### ISSUE TITLE
Add passthrough_errors to flask run options

### ISSUE THREAD

**Issue by kgutwin** [pallets/flask#5255]
I'm building an API using Flask, and have an `@app.errorhandler(HTTPException)` to catch all HTTPExceptions in order to format them as JSON. This is working great via `flask run`, but when I add the `--debug` flag to get auto-reloading, the Werkzeug default error handler catches exceptions before my error handler has a chance to respond with JSON.

I noticed the `passthrough_errors` option to `werkzeug.run_simple()`, and when I run my app via a simple script, the error handler works as I'd expect, along with the reloader:

```
from my_app import create_app
from werkzeug import run_simple

app = create_app()
run_simple("0.0.0.0", 8170, app, use_reloader=True, use_debugger=False, passthrough_errors=True, threaded=True)
```

Therefore, it would be helpful if we could add something like `--passthrough-errors` to the `flask run` CLI command. Alternately, let me know if there's another recommended way to use `flask run --debug` but disable the Werkzeug default error handler page. Thanks!

**Comment by davidism** [comment]
Duplicate of https://github.com/pallets/flask/issues/4729
See also https://github.com/pallets/flask/issues/5046
