### ISSUE TITLE
TypeError: Flask.url_for() got multiple values for argument 'self'

### ISSUE THREAD

**Issue by sda97ghb** [pallets/flask#5258]
[Official documentation](https://flask.palletsprojects.com/en/2.3.x/api/#flask.url_for) doesn't mention any preconditions for values argument, but `self=1` raises an exception.

Can be replicated with the following test case:

```python
from unittest import TestCase

from flask import Flask, url_for


class UrlForTests(TestCase):
    def setUp(self) -> None:
        self.app = Flask(__name__)

    def test_with_self_argument(self) -> None:
        with (
            self.app.app_context(),
            self.assertRaisesRegex(
                TypeError, "got multiple values for argument 'self'"
            ),
        ):
            url_for("doesnotmatter", self=1)
```

Traceback example:

```
Traceback (most recent call last):
  File "/home/dmitry/git/github.com/minetest/contentdb/tests.py", line 6, in <module>
    url_for("doesnotmatter", self=1)
  File "/home/dmitry/.cache/pypoetry/virtualenvs/contentdb-MK2UWkId-py3.10/lib/python3.10/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
TypeError: Flask.url_for() got multiple values for argument 'self'
```

The expected behavior is the returned URL has query string like '?self=1'.

Environment:

- Python version: 3.10.6
- Flask version: 2.3.3

**Comment by ThiefMaster** [comment]
Probably `self` of that method should be made positional-only (unless we still support a Python version that does not support positional-only arguments). As a workaround we could possibly rename it to something like `___self` that is almost certainly never used in a real URL param...

**Comment by davidism** [comment]
Let's get this into 3.0 and use a position only arg.
