### ISSUE TITLE
Got error using flak Flask==2.0.2

### ISSUE THREAD

**Issue by bullet-dev-team** [pallets/flask#5278]
Environment: My application works fine previously, but after 2023/09/30, it deployed failed

- Python version: Python3
- Flask version:
- Flask==2.0.2
gunicorn==20.0.4

**Comment by ThiefMaster** [comment]
Do not crosspost your issues, even less so if they still lack even the slightest amount of details.

https://github.com/pallets/flask/discussions/5277
