### ISSUE TITLE
work around for getting _request_ctx_stack.top

### ISSUE THREAD

**Issue by kelvin-j-li** [pallets/flask#5280]
Environment:

- Python version: 3.11.5
- Flask version: 3.0.0

With the release of flask-3.0.0, _request_ctx_stack and _app_ctx_stack got remoevd. May I know whether it's possible to 
get _request_ctx_stack.top with the new version? any workaround and sample?

it's causing import error in downstream library (flask-track-usage) - https://github.com/ashcrow/flask-track-usage/issues/69

Thanks!

**Comment by ThiefMaster** [comment]
From the changelog:

> Extension maintainers, be aware that `_app_ctx_stack.top` and `_request_ctx_stack.top` are deprecated. Store data on `g` instead using a unique prefix, like `g._extension_name_attr`.

**Comment by kelvin-j-li** [comment]
@ThiefMaster ,
For _app_ctx_stack.top and _request_ctx_stack.top, would it be g. _app_ctx_stack.top / g._request_ctx_stack.top?

Many thanks!

**Comment by davidism** [comment]
It would just be g.
