### ISSUE TITLE
request.is_secure, Azure and X-ARR-SSL

### ISSUE THREAD

**Issue by fabswt** [pallets/flask#5301]
This code will cause a redirect when ran on Azure Web App (possibly on other Azure services as well):

```
@app.before_request
def before_request():
    if not request.is_secure:
        url = request.url.replace('http://', 'https://', 1)
        code = 301
        print("Redirecting to https")
        return redirect(url, code=code)
```

because request.is_secure will return False.

I had to use this instead:

```
@app.before_request
def before_request():
    """Redirect to https and www-less.
    BEWARE that the value must be returned. Otherwise, the request'll continue.
    So extracting into subfunctions not necessarily convenient.
    """    
    if not secure_site():
        url = request.url.replace('http://', 'https://', 1)
        code = 301
        print("Redirecting to https")
        return redirect(url, code=code)

    host = request.headers.get('Host')
    if host.startswith('www.'):
        url = request.url.replace(f'{host}', f'{host[4:]}', 1)
        print("Redirecting to www-less")
        return redirect(url, code=301)

def secure_site():
    # Check if Flask thinks it's secure
    if request.is_secure:
        return True

    # Check for Azure's header indicating SSL termination at the load balancer
    # Because Flask does not know/handle this.
    if request.headers.get('X-ARR-SSL'):
        return True

    # Check for the header used by Heroku and others
    forwarded_proto = request.headers.get('X-Forwarded-Proto')
    if forwarded_proto and forwarded_proto.lower() == 'https':
        return True

    return False
```

I would expect Flask to be able to detect that X-ARR-SSL is still secure.

Discussions:

- https://stackoverflow.com/questions/38501618/is-current-request-being-made-over-ssl-with-azure-deployment
- In discussing this with ChatGPT: "**Safety Note:** It's important to ensure that these headers can't be easily spoofed by a malicious client. Normally, reverse proxies (like those used by Azure or Heroku) remove or overwrite these headers if they're set by the client. Therefore, in a correctly configured environment, these headers should be trustworthy. However, if you're in a different environment where you're not certain about this, you'd want to ensure that external users can't set these headers to trick your app into thinking an insecure connection is secure."

Environment:

- Python version: 3.11
- Flask version: 2.3.2
- On Azure Web Apps

**Comment by ThiefMaster** [comment]
Use werkzeug's `ProxyFix` middleware. If Azure sets any standard headers (such as `X-Forwarded-Proto`), then this will work. `X-ARR-SSL` is certainly not standard, but probably they set the standard headers as well.
