### ISSUE TITLE
Deprecated link for ProxyFix via Sphinx

### ISSUE THREAD

**Issue by ravicodelabs** [pallets/flask#5308]
## Summary of Bug

The link to class `ProxyFix` in `Werkzeug` in the [Flask 3.0.x quickstart docs](https://flask.palletsprojects.com/en/3.0.x/quickstart/#hooking-in-wsgi-middleware), generated with ` :class:``~werkzeug.middleware.proxy_fix.ProxyFix`` `, is given as: 

https://werkzeug.palletsprojects.com/en/2.3.x/middleware/proxy_fix/#werkzeug.middleware.proxy_fix.ProxyFix

However, that link, linking to werkzeug 2.3.x is deprecated, and should instead link to 3.0.x I believe:

https://werkzeug.palletsprojects.com/en/3.0.x/middleware/proxy_fix#werkzeug.middleware.proxy_fix.ProxyFix

## Describe how to replicate the bug

I was not able to reproduce the bug. Building the docs locally gives the correct link (werkzeug 3.0.x). 

## Describe the expected behavior

The docs should build with the updated cross-link to `Proxyfix` in `Werkzeug`:

https://werkzeug.palletsprojects.com/en/3.0.x/middleware/proxy_fix#werkzeug.middleware.proxy_fix.ProxyFix

## Environment:

- Python version: 3.10.13
- Flask version: `main` branch: beedaa4eff3919f250fad49a5092cf07c4d638e1

**Comment by davidism** [comment]
Updated
