### ISSUE TITLE
Typo in docs/tutorial/factory

### ISSUE THREAD

**Issue by markalanboyd** [pallets/flask#5314]
I was working through the tutorial and ran into a problem getting the example code to work.

It appears that you need to put a trailing backslash on this route for it to render.

---

```python
@app.route("/hello") # no trailing backslash
def hello():
    return "Hello, World!"
```
This code returns:
![not_found_error](https://github.com/pallets/flask/assets/10804241/3fb97874-0fd0-4b13-b110-6b0feca66392)

---

```python
@app.route("/hello/") # with trailing backslash
def hello():
    return "Hello, World!"
```
returns:
![hello_world](https://github.com/pallets/flask/assets/10804241/f5071e1d-594c-474a-9391-4ace7d7b8f4b)

Environment:

- Python version: 3.11.2
- Flask version: 3.0.0

**Comment by davidism** [comment]
Tutorial is correct as is. Compare the link in the tutorial to what's in your browser, there's a difference.
