### ISSUE TITLE
Mention Extensions in the Docs more

### ISSUE THREAD

**Issue by kennethreitz** [pallets/flask#532]
I had a friend that was going through the quickstart, and he had absolutely no idea that there were any extensions available for flask.

He was using SQLAlchemy directly and was becoming quite frustrated quickly.

Since an ecosystem is clearly part of a framework, I think we should add some hints about extensions throughout the documentation. Not necessarily usage examples, just "hey, this extension might be useful to you".

**Comment by KWinston** [comment]
Hi, I'm a new contributor and would like to work on this issue. Where in the documentation are you referring to within the quickstart?

**Comment by untitaker** [comment]
There's already some work done in #1376, but I'll leave this open because there are surely more places where we can include extension hints.

**Comment by davidism** [comment]
Looks like we link to them more now, so closing this.

**Comment by kennethreitz** [comment]
✨🍰✨
