### ISSUE TITLE
Add OpenAPI functionality 

### ISSUE THREAD

**Issue by geekychandraul** [pallets/flask#5341]
As of today, Fast api and Flask are more preferred framework to develop microservice and service mesh architecture. 
Flask is more preferred for below points:
1. microservice architecture
2. more extension available in community than others as its bit matured.  

I really like the simplicity flask has. But in recent days Flask is loosing to FastAPI.

Biggest CON of flask is its **incompatibility** with OpenAPI/documentation capability. 
Being an Architect, my whole org has moved to FastAPI for a simple reason OpenAPI integration and documentation. As it helps us save on maintaining more than 30+ product API documentation. Earlier we were using 3rd party tools to maintain these documentation.    

It would really help flask gain more ability if we can add openapi specification just like fast api. 
I understand the same [feature request](https://github.com/pallets/flask/issues/4315) was raised in back in 2021 but I believe being in technology domain we have keep ourselves updated. Same goes with the web framework as well. 

To illustrate few, Django is adding capability to have microservice support. why? its to keep them updated with latest requirement.

Out of Django, Flask and FastAPI only Flask is not having OpenAPI support. 

I know there are library available in community which can do this but having it natively available in flask bring more confidence.   

Out of Django, Flask and FastAPI only Flask is not having OpenAPI support. I know there are library available in community which can do this but having it natively available in flask bring more confidence and usability. as there are open source repo which supports this functionality may slowly loose its contributor unlike Flask contributors.

**Comment by ThiefMaster** [comment]
To me it sounds like having a well-maintained Flask extension for this would fit much better in the spirit of how flask works...

**Comment by davidism** [comment]
There are already numerous extensions that provide this. It's outside the scope of Flask core.
