### ISSUE TITLE
Tutorial Database code doesn't work

### ISSUE THREAD

**Issue by MichaelArnoldOwens** [pallets/flask#5359]
Follow the Tutorial doc through the "Define and Access the Database" doc. When you try and initialize the db, you will be greeted with an error

`AttributeError: 'AppGroup' object has no attribute 'add_command'`

Environment:

- Python version:
- Flask version:

**Comment by davidism** [comment]
I can't reproduce this issue, `AppGroup` subclasses `click.Group`, which does provide `add_command`. The linked PR does not seem related.
