### ISSUE TITLE
I'm seeing "GET /socket.io/?EIO=3&transport=polling&t=OozzqO3 HTTP/1.1" 404 errors running a simple flask app

### ISSUE THREAD

**Issue by dhylands** [pallets/flask#5372]
I created a "Hello World" flask app (which can be found here: https://github.com/dhylands/flask-hello/tree/main

If I create a virtual environment and install flask and then do `flask run` I get the following output:
```
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [30/Dec/2023 19:42:28] "GET /socket.io/?EIO=3&transport=polling&t=OozzqO3 HTTP/1.1" 404 -
127.0.0.1 - - [30/Dec/2023 19:42:33] "GET /socket.io/?EIO=3&transport=polling&t=OozzrcF HTTP/1.1" 404 -
127.0.0.1 - - [30/Dec/2023 19:42:33] "GET /socket.io/?EIO=3&transport=polling&t=OozzrcI HTTP/1.1" 404 -
127.0.0.1 - - [30/Dec/2023 19:42:38] "GET /socket.io/?EIO=3&transport=polling&t=OozzsqT HTTP/1.1" 404 -
```

I'd expect to not see errors/warnings about socket.io

Environment:
 - Pop_OS! (aka ubuntu) 22.04 LTS
- Python version:  Python 3.10.12
- Flask version: 3.0.0

pip freeze reports:
```
blinker==1.7.0
click==8.1.7
Flask==3.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.3
Werkzeug==3.0.1
```

**Comment by davidism** [comment]
You have something making those requests, so you see them. If you didn't write code to do that, perhaps a browser extension?

**Comment by dhylands** [comment]
Hmm - yep - you're right. When I quit my browser they stopped, so there must have been a browser window open someplace that was doing that. Sorry for the noise.
