### ISSUE TITLE
Can I contribute 

### ISSUE THREAD

**Issue by Yuheshpandian** [pallets/flask#5373]
Hi I'm @Yuheshpandian. I love Flask and its capabilities, in fact when I wanted to learn _web dev_ , with only the knowledge of `Python`, I went for Flask without hesitation. I had made some projects using Flask, also a modern boilerplate for `flask` projects. Now I wanted to Contribute to my go to web framework in Python. 

I just want to contribute and make changes in the README.md/Documetation.

Thank You

**Comment by ThiefMaster** [comment]
that's not what issues are for... please see https://github.com/pallets/flask/blob/main/CONTRIBUTING.rst

**Comment by Yuheshpandian** [comment]
> that's not what issues are for... please see https://github.com/pallets/flask/blob/main/CONTRIBUTING.rst

no actually I asked a willing/permission, if the `pallets` would like me to contribute, I was not reporting any vulnearability/bugs or request a feature.

**Comment by ThiefMaster** [comment]
This is an open source project. If you can make useful contributions we're happy about them. And the link I posted literally recommends you to:

- not use the issue tracker for support-like questions (which yours here is, this would have been better suited in discussions or on our discord)
- open an issue to discuss if you think there's something you may want to contribute

It is up to you to find something you find worth contributing, either coming up with something you think would be useful (open an issue about it in that case), or finding an issue you'd like to work on (but considering there's just one issue open right now that might be hard).

**Comment by Yuheshpandian** [comment]
yeah thank you for spending your valuable time I would sure follow the Contributing guidelines and make my contributions. Thank you for you kind guidance.

**Comment by ThiefMaster** [comment]
Also please note that one-line "I think this could be worded differently" changes to readme/docs are usually not useful, *especially* if they do not actually fix e.g. incorrect spelling/grammar.

**Comment by davidism** [comment]
In this and other projects, please stick to open issues that are unassigned and do not yet have PRs submitted. You'll notice that Flask and Werkzeug have very few of those, so they're not good targets for first time contributors. Within Pallets, Click and Jinja have open issues, but those tend to be more complex or confusing, so still probably not good targets. The Flask extension ecosystem however is very large, and tends to receive much less contributor attention, so you may want to look around there for something that is actively maintained and needs help.
