### ISSUE TITLE
Donating Funds to Flask

### ISSUE THREAD

**Issue by Lfada** [pallets/flask#5379]
Hi Flask maintainers. I'm Lucas, a core contributor to the Drips project (drips dot network). I help recipients of donations through their learning and onboarding process.

Octant (octant dot build) (a project from the Golem Foundation) has been using https://github.com/pallets/flask. It's one of their most critical dependencies!

Octant’s core contributors appreciate the work you all do and want to make sure that you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through Drips.

Who can I talk to about it?

**Comment by davidism** [comment]
We already have funding sources set up, which can be found through GitHub's "Sponsor" button on each of our repositories. If any project would like to donate to us, they can do so through:

* GitHub sponsors: https://github.com/sponsors/pallets
* Python Software Foundation: https://psfmember.org/civicrm/contribute/transact/?reset=1&id=20
* Tidelift: https://tidelift.com/funding/github/pypi/Flask

If your platform has already taken their donation as if they were donating to us, then they should be refunded so they can direct their funds to the appropriate location.

**Comment by Lfada** [comment]
> We already have funding sources set up, which can be found through GitHub's "Sponsor" button on each of our repositories. If any project would like to donate to us, they can do so through:
> 
> * GitHub sponsors: https://github.com/sponsors/pallets
> * Python Software Foundation: https://psfmember.org/civicrm/contribute/transact/?reset=1&id=20
> * Tidelift: https://tidelift.com/funding/github/pypi/Flask
> 
> If your platform has already taken their donation as if they were donating to us, then they should be refunded so they can direct their funds to the appropriate location.

Hi @davidism,

Thank you for your quick response. I understand Flask is using certain platforms to accept donations, but none of them seem to accept cryptocurrencies.

The funder organization would like to donate in ETH because this is the asset they have.

Are you open to receiving cryptocurrencies, or is there a policy against it?

If Yes, let’s discuss how you can receive these funds.
If No, no worries. We can inform the funder and redirect those funds elsewhere.

Thank you

**Comment by Lfada** [comment]
hi @davidism, just wanted to hear your thoughts on this. 

Let me know if you have any questions, or if you all have made a decision on how to move forward.
