### ISSUE TITLE
send_file doesn't work with objects

### ISSUE THREAD

**Issue by AxelGarciaTello** [pallets/flask#5408]
I had a file in an object of type io.BytesIO(), but when I put this object in a send_file made me the error that the parameter is incorrect.
In the version 2 this work well but in the version 3.0.2 doesn't.

Environment:

- Python version: 3.10.12
- Flask version: 3.0.2

**Comment by davidism** [comment]
I can't reproduce the issue with the information provided. When reporting an issue, be sure to include a minimal reproducible example and the full traceback.
