### ISSUE TITLE
CHIPS support

### ISSUE THREAD

**Issue by SimonLiu423** [pallets/flask#5412]
Add an argument for `set_cookie` to add `Partitioned;` attribute to the Set-Cookie header.

According to Google, third-party cookies will soon be deprecated. [link](https://developers.google.com/privacy-sandbox/3pcd/prepare/prepare-for-phaseout)
For cross-site cookies which store data on a per site basis, like an embed, will need to migrate to [CHIPS](https://developers.google.com/privacy-sandbox/3pcd/chips), which uses `partitioned` storage to store cookies.

**Comment by davidism** [comment]
Duplicate of https://github.com/pallets/werkzeug/issues/2797
