### ISSUE TITLE
Failing to start (due to port unavailable) cannot be directly determined by the current python api

### ISSUE THREAD

**Issue by matanox** [pallets/flask#5471]
I believe that failing to start (due to the designated port being unavailable) cannot be directly determined by the current python api, if not mistaken.

When the port specified for startup is taken, a python code starting the server with Werkzeug cannot know if startup has failed, since no exception is raised, and no api is there to check on its status, while the following is written to stderr:

> Address already in use
> Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.

example code:

```python
from flask import Flask
from werkzeug.serving import run_simple

app = Flask(__name__)

try:
    run_simple('127.0.0.1', 5000, app)  
except Exception as e:
    start_success = False
```

Even though traditionally most web servers frameworks did not touch up their startup and shutdown usability from code to those levels, I think it would be implied to provide the caller with this basic level of transparency being robustly enabled for them. Apologies in advance if I've missed any obvious way. 

# Environment:

- Python version: 3.10.13
- Flask version: 3.0.3
- Platform: Ubuntu 22.04

# Mildly related on the same theme of api startup and shutdown: 
https://stackoverflow.com/questions/72824420/how-to-shutdown-flask-server

**Comment by matanox** [comment]
Complete code reproducing the context, which would preferably also be a skeleton for a test after the desired functionality has been implemented:

```python
from flask import Flask
from werkzeug.serving import run_simple
from multiprocessing import Process

app = Flask(__name__)

def start():
    print('starting a flask server')
    try:
        started = run_simple('127.0.0.1', 5000, app)
    except Exception as e:
        print(f'the flask web server crashed with an exception:\n{e}\n')
    else:
        # of course we will never get here unless the server shut down without throwing
        print(f'flask web server finished with return value {started}')


if __name__ == '__main__':

    flask_process = Process(target=start, daemon=True)
    flask_process.start()

    start()

print('second start done')
```

**Comment by ThiefMaster** [comment]
Not sure what you are trying to do, but keep in mind that this server is ONLY meant for development purposes, NOT for anything else. So if you want to run a flask app embedded in some other application for whatever reason, using `run_simple` is not what you should do.

**Comment by matanox** [comment]
Makes sense. My scenario is borderline in that regard. Will I have that kind of api-laden way of knowing the status of the server when using a non Werkzeug WSGI component?

**Comment by matanox** [comment]
Okay, I understand then that no underlying supported WSGI server component can be controlled (start and stop) robustly from code then.
