### ISSUE TITLE
request parsing special parameters

### ISSUE THREAD

**Issue by liangxiaojian0210** [pallets/flask#5494]
I want to know when i send "http://127.0.0.1:5000/?name=xiaojiann+&age=16" , why request.query_string can get b'name=xiaojiann+' but request.arg get ImmutableMultiDict([('name', 'xiaojiann ')]), request.args use blank space replace +

<img width="739" alt="image" src="https://github.com/pallets/flask/assets/61368566/0a58880c-a70b-4455-a949-4af5ff55ca5b">

I try flask version 2.0.3 , 3.0.3 and python version 3.6 , 3.10

**Comment by davidism** [comment]
Because that's how query strings work. You need to percent encode characters with special meanings.
