### ISSUE TITLE
Flask incorrectly parses chained query parameters 

### ISSUE THREAD

**Issue by alemiherbert** [pallets/flask#5519]
When accessing the /test route with both category and location query parameters (http://localhost:5000/test?category=fish&location=water), Flask correctly parses category but ignores location.

### Steps to Reproduce
Access the URL http://localhost:5000/test?category=fish&location=water.
Expected behavior: Both category and location parameters should be correctly parsed by Flask.
Actual behavior: Flask parses category correctly ("excavator"), but location is ignored.

```(python)
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route("/test")
def test():
    category = request.args.get("category")
    location = request.args.get("location")
    return {"category": category, "location": location}

if __name__ == "__main__":
    app.run(debug=True)
```

Expected:
```(json)
{
    "category": "fish",
    "location": "water"
}
```

Got:
```(json)
{
    "category": "fish",
    "location": null
}
```
### Environment:

- Python version: 3.8.10
- Flask version: 3.0.3

**Comment by davidism** [comment]
I can't reproduce the issue with the information provided. Running the example gives the expected output.

**Comment by kamau95** [comment]
how did you sort it out
