### ISSUE TITLE
`pyright` type checking seems to be unused. `mypy` still being used.

### ISSUE THREAD

**Issue by pygeek** [pallets/flask#5537]
We added `pyright` in 3.0.3 (see: https://github.com/pallets/flask/pull/5457), but `mypy` is still being used for type checking https://github.com/pallets/flask/blob/main/tox.ini#L29-L32, and `pyright` is not.

If this was an intentional change of type checkers, then would expect that `mypy` be completely removed, and `pyright` be the command run in `tox typing`.

It should be noted, however, that running `pyright` yields 90 errors (71 tests/19 src). Is there an upgrade path or was this an oversight?

Environment:

- Python version:
- 3.12
- Flask version:
- 3.0.3

**Comment by davidism** [comment]
fixed in #5620
