### ISSUE TITLE
test_helpers.py.test_open_resource_with_encoding function attribute error

### ISSUE THREAD

**Issue by 40gilad** [pallets/flask#5554]
the function test_open_resource_with_encoding, sends encoding arguemnt to app.open_resource() function. the open_resource function doesnt has any enoding parameter in it's signature.

- Python version: 3.11.5

- Flask version: current

**Comment by davidism** [comment]
All test pass locally for me and in CI.

**Comment by RonnyPfannschmidt** [comment]
To further elaborate 

https://github.com/pallets/flask/blob/main/src%2Fflask%2Fapp.py#L323-L325

Has the parameters
