### ISSUE TITLE
dotenv file arg should take precedence over default dotenv files

### ISSUE THREAD

**Issue by davidism** [pallets/flask#5628]
As pointed out in #5532, `-e file` is loaded after the default `.env` and `.flaskenv` files, which means it won't override env vars that are set by the defaults. It will be a little tricky to track during CLI startup, but I think it should be possible to fix this so that precedence is: `os.environ` > `-e path` > `.env` > `.flaskenv`.

**Comment by jalaj711** [comment]
Hey, can I work on this issue?
