### ISSUE TITLE
flask==2.2.4 incompatible with werkzeug==3.1.3

### ISSUE THREAD

**Issue by ranaprathapthanneeru** [pallets/flask#5652]
I use flask==2.2.4 for my project and when I install flask, it pulls **any** werkzeug>=2.2.2 (which is the default behaviour). After [werkzeug==3.1.3](https://pypi.org/project/Werkzeug/3.1.3/) got released on 8 Nov, 2024, flask pulls the latest version of it. With this new version of werkzeug, while executing unit tests, I get an error saying `module 'werkzeug' has no attribute '__version__'`

**A small example to reproduce the issue:**
(myenv) root@6426d8424cca:~# python3
Python 3.9.16 (main, Sep  2 2024, 12:46:28) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
 **">>> from flask import Flask
 ">>> app = Flask(__name__)
 ">>> my_test_client = app.test_client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/myenv/lib/python3.9/site-packages/flask/app.py", line 1252, in test_client
    return cls(  # type: ignore
  File "/root/myenv/lib/python3.9/site-packages/flask/testing.py", line 116, in __init__
    "HTTP_USER_AGENT": f"werkzeug/{werkzeug.__version__}",
**AttributeError: module 'werkzeug' has no attribute '__version__'****

I shouldn't be seeing any error like above.

Environment:

- Python version: 3.9.16
- Flask version: 2.2.4

**Comment by davidism** [comment]
You are using an unsupported version of Flask, please update to the latest version (3.1.0) if possible.

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates.

Please review any of the following for more information:

* https://hynek.me/articles/semver-will-not-save-you/
* https://www.youtube.com/watch?v=WSVFw-3ssXM&t
* https://snarky.ca/why-i-dont-like-semver/
* https://caremad.io/posts/2016/02/versioning-software/
* https://bernat.tech/posts/version-numbers/
* https://iscinumpy.dev/post/bound-version-constraints/

You can use `uv pip install --exclude-newer "date"` to install packages published before a certain date, so newer packages aren't pulled in. You can also do the same with `uv pip compile` to produce a lock in case you didn't previously.
