### ISSUE TITLE
Add config parser to blueprints

### ISSUE THREAD

**Issue by jhutchins** [pallets/flask#631]
I think that it would be useful to be able to add configuration items to a blueprint and then have those merged into the app configuration on load. My thinking is simply that there might be configurations specific to your blueprint that should have default values stored as part of the blueprint. I suppose this feature could also lead to use cases where people make blueprint simply to hold different configuration for the application.

**Comment by jeffwidman** [comment]
Many Flask extensions add configuration items to an app that can then be overridden by the user. I haven't dug into that part of the code, but I suspect you could simply expand your generic blueprint into a custom flask extension to achieve what you want.
