### ISSUE TITLE
Design issue with flask.logger.create_logger().

### ISSUE THREAD

**Issue by brownhead** [pallets/flask#641]
[`flask.logger.create_logger()`](https://github.com/mitsuhiko/flask/blob/master/flask/logging.py#L17) destroys any log handlers that have been added previously. Because the creation of the logger (and the calling of `create_logger()` that this entails) is [deferred until the first time `flask.app.logger` is accessed](https://github.com/mitsuhiko/flask/blob/master/flask/app.py#L548), this can lead to the destruction of log handlers that were purposefully added by the application.

I just tracked down a bug due to this that took me a very long time to debug because I had no idea this went on. To my eyes, it looked like the standard logging module was breaking at a seemingly random moment (it wasn't even my code that was accessing `app.logger`, it was [Flask's internal error handling code](https://github.com/mitsuhiko/flask/blob/master/flask/app.py#L1347)). Therefore, I think one of two courses of action should be taken:
- Because this behavior of `create_logger()` seems very strange, perhaps it should be removed. As in don't delete log handlers that are already in place when `create_logger()` gets called.
- If there is a good reason for this behavior to remain, it should be documented clearly in `app.logger`'s docstring.

I am happy to carry out either (or some other) change and send a pull request.

**Comment by crazygit** [comment]
@bhafichuk-redfall  I completely agree with you. I wasted a good morning figuring out why config logger from configure not work for Flask app instance

**Comment by kerma** [comment]
So what's wrong with the #1311 that it has been hanging here for a year and more? Another soul here who spent hours to figure this out. Now I have to go with dropping `app.logging` usage and adding the ugly hack :(

**Comment by tinproject** [comment]
For the record, @jonblack:

> Using the `LOGGER_NAME` setting helped me to create the correct "top-level" logger, but the default level for subsequent child loggers is being mysteriously set to `WARNING` instead of `NOTSET` (which means, use the parent's level). Here's an example output:
> ```
> myapp -> DEBUG
> myapp.factory -> WARNING
> myapp.measurements -> WARNING
> myapp.measurements.views -> WARNING
> ```

this happen because flask don't set explicitely the level for it's logger, instead _'subclass'_ the logger to return a effective level of `DEBUG` in the case of the level of the logger is `NOSET` (https://github.com/pallets/flask/blob/master/flask/logging.py#L61). 
This allows debug messages to be logged whichever the effective level is inherited from it's parent.  
But all the children are normal loggers (logging.Logger) so inherits their parent level, and as the Flask logger has really a `NOSET` level, surely, their inherit the default `WARNING` level from the root logger.

**Comment by davidism** [comment]
I've created #2436 that hopefully simplifies Flask's logging configuration. It also splits out and updates the documentation to help clarify how everything works. If anyone here wants to take a look and make sure it addresses the points brought up here, I'd appreciate it.

Closing this to move discussion either to the PR or #2023.
