### ISSUE TITLE
Add ability to app.route pluggable views

### ISSUE THREAD

**Issue by ghost** [pallets/flask#713]
### Rationale

Some `Views` could be created and used only once, for example `MethodViews` instead of "standard" functions with `if request.method == 'POST'`. This kind of use could be made easier.
### Proposal

Instead of writing:

```
class MyFantasticView(View):
    ...
app.add_url_rule('/fantastic/', view_func=MyFantasticView.as_view('fantastic'))
```

we could make it easier and consistent with other parts of the API:

```
@app.route('/fantastic/', endpoint='fantastic')
class MyFantasticView(View):
    ...
```

**Comment by davidism** [comment]
This won't work for the reason @mitsuhiko stated. You need to be able to pass arguments to initialize the `MethodView`, that's where a lot of the power comes from. Overloading `route` even more isn't worth it over just being explicit.
