### ISSUE TITLE
Add Sentry to error logging documentation

### ISSUE THREAD

**Issue by dcramer** [pallets/flask#720]
Thoughts on this?

Django includes it. I might be bias, but pretty much everyone needs it :)

**Comment by VishvajitP** [comment]
Well sentry itself has a nice documentation.

**Comment by etothemanders** [comment]
A link to Sentry has already been added to the Error Logging Tools section of the docs:  [http://flask.pocoo.org/docs/0.11/errorhandling/#error-logging-tools](http://flask.pocoo.org/docs/0.11/errorhandling/#error-logging-tools).  This issue can be closed!
