### ISSUE TITLE
Second mini-example on flask.pocoo.org might suggest the dev server is production ready

### ISSUE THREAD

**Issue by untitaker** [pallets/flask#721]
I just realized that the headline "And easy to setup" might trick the user into thinking that's all it takes to setup a Flask app *on the production server*.

Of course the exact opposite is stated in the quickstart, but then we never can expect people to actually read documentation.

Independent of whether this is really an issue anybody else but me sees, i think a large "Get Started" button on the front page might animate people to read the docs from the beginning.

**Comment by etothemanders** [comment]
Working on this at PyCon 2016

**Comment by untitaker** [comment]
@etothemanders We will completely refactor the entire website in the future, so this might be a bigger project than it seems

**Comment by etothemanders** [comment]
@untitaker Np.  I opened a PR for the pypi description and one in the new website project, but feel free to just close them if you like.

**Comment by untitaker** [comment]
We'll have to figure out what to do with the old website, but we'll probably just trash it. Done!
