### ISSUE TITLE
Move core Flask repositories to an organization

### ISSUE THREAD

**Issue by techniq** [pallets/flask#729]
Now that Github [supports redirects](https://github.com/blog/1508-repository-redirects-are-here), maybe it's time to consider moving Flask, and core extensions (Flask-SQLAlchemy, Flask-OAuth, etc) into an organization.

Thoughts from the team?

**Comment by jeffwidman** [comment]
+1

It seems @mitsuhiko is pretty busy/excited about other projects, which is great, but for those still excited by the Flask ecosystem, it'd probably be easier if @mitsuhiko was open to giving up control a bit and migrating Flask and the core modules that he's the owner of over to a Github organization. I'm aware of the [Metaflask](https://github.com/pocoo/metaflask) repo, but it feels like a hack that doesn't work that well.

**Comment by jeffwidman** [comment]
Flask is now part of the `pallets` Github org.
