### ISSUE TITLE
Given absolute URL, testclient discards query params

### ISSUE THREAD

**Issue by ryanolson** [pallets/flask#801]
The following fails at the assert inside the index subroutine.

``` python
import unittest
from flask import Flask, url_for, request, jsonify

class TestFlask(unittest.TestCase):

    def test_get_with_arguments(self):
        app = Flask(__name__)
        app.debug = True

        @app.route('/echo')
        def index():
            assert 'key' in request.args
            return jsonify( dict(key=request.args['key']) )

        url = None
        with app.test_request_context():
            url = url_for('index', key='test', _external=True)

        assert url == 'http://localhost/echo?key=test'

        rv = app.test_client().get(url)
        assert 'key' in rv.data
```

**Comment by manuelgodoy** [comment]
When I build my dict and pass it on as `data` the args are not received: 

```javascript
import unittest
from flask import Flask, url_for, request, jsonify

class TestFlask(unittest.TestCase):

    def test_get_with_arguments(self):
        app = Flask(__name__)
        app.debug = True

        @app.route('/echo')
        def index():
            assert 'key' in request.args
            return jsonify( dict(key=request.args['key']) )
 
        rv = app.test_client().get('/echo', data = dict(key = 'test') )
        assert 'key' in rv.data
```

**Comment by Frozenball** [comment]
This behaviour seems a bit unexpected. What's the reasoning behind this behaviour?

**Comment by adambyrtek** [comment]
I noticed this issue in other circumstances, without using the `_external` flag at all. Most of our view tests don't use request context explicitly, for example:

```
def test_foo_bar(client):
    response = client.get(url_for('endpoint'))
    assert response.status_code == 200
```

In order to make `url_for` work without the request context we had to explicitly set `app.config['SERVER_NAME'] = 'localhost'` in test setup, but besides that this works perfectly and is much less verbose.

The problem is that in this case `url_for` generates absolute URLs (e.g. `http://localhost/endpoint`) which suffer from the issue in question. In other words the obvious code doesn't work:

```
def test_foo_bar(client):
    response = client.get(url_for('endpoint', param='foo'))
    assert response.status_code == 200
```

And has to be replaced with much less obvious:

```
def test_foo_bar(client):
    response = client.get(url_for('endpoint'), query_string={'param': 'foo'})
    assert response.status_code == 200
```

Worst of all there is no warning whatsoever so you don't even know why a test is failing for a URL that seems perfectly correct.

**Comment by sprin** [comment]
If the test client needs a relative url, we should always be able to get a relative URL from `url_for`. And indeed, we can always get a relative url by calling `url_for` with  `_external=False`.

The catch is that we must set `SERVER_NAME`, even if we never need to generate absolute urls. It looks like the underlying constraint is that Werkzeug's [Map.bind](http://werkzeug.pocoo.org/docs/0.10/routing/#werkzeug.routing.Map.bind) requires the `server_name` argument.
> The server_name at least is a requirement because the HTTP RFC requires absolute URLs for redirects and so all redirect exceptions raised by Werkzeug will contain the full canonical URL.

I think changing `Map.bind` to treat `server_name` as optional would be very disruptive, so we should rule that out.

`url_for` could be made to work without either a RequestContext or `SERVER_NAME`, by creating a URL adapter (`MapAdapter`) with a dummy `server_name` set to the empty string. So in other words, when a there is no RequestContext, and `external=False`, we create a URL adapter with a dummy `server_name`.

This should be a non-breaking change that will enable the use of `url_for` with `_external=False` for use in tests without having to set `SERVER_NAME`. We can document the correct usage of `url_for` with a test client in the "Testing Flask Applications" doc.

**Comment by adambyrtek** [comment]
Sounds like a good plan.

**Comment by dorianpula** [comment]
I'll take this one on as part of the PyCon sprints.

**Comment by davidism** [comment]
The original issue here is invalid, since the url should be relative. The absolute url is being appended as the query string. That shouldn't change (and would happen in Werkzeug if it should).

I'll open a new issue with @spirin's plan.
