### ISSUE TITLE
Support mapping multiple subdomains to a single blueprint

### ISSUE THREAD

**Issue by rturpin** [pallets/flask#821]
I have a website with acces by more subdomain like : 
- 'www.mysite.com', 'category1.mysite.com', 'category2.mysite.com', ...
  whose point to one blueprint.

It's interesting to manage more one subdomain by blueprint, for example by a list : 
- landing_bp = Blueprint('landing', **name**, subdomain=['www','category1','category2'], url_prefix='/landing')

Or disable subdomain.

Thank's you.

**Comment by jeffwidman** [comment]
FTR, I've never tried it, but I suspect this mapping functionality could be provided by Nginx/Apache.
