### ISSUE TITLE
How to get the serialized version of the session cookie in 0.10?

### ISSUE THREAD

**Issue by lipis** [pallets/flask#834]
In version 0.9 I could simply get the value of the `session` like this: 

```
flask.session.serialize()
```

But after upgrading to 0.10 this is not working anymore.. what's the alternative? How can I get the session value?

(`flask.request.cookies.get('session')` is not good for me, because I would like to get the session right after login, so it's not part of the request yet)

**Comment by davidism** [comment]
`app.session_interface.get_signing_serializer(app).dumps(dict(session))`
