### ISSUE TITLE
Tutorial stores passwords in plaintext

### ISSUE THREAD

**Issue by ssbr** [pallets/flask#836]
http://flask.pocoo.org/docs/tutorial/views/#login-and-logout

Flask should not lead new users astray, and should instead make it as easy and obvious as possible to do the right thing.

**Comment by KWinston** [comment]
I've been looking into this issue. Should Werkzeug be mentioned for its ability to hash + salt passwords to avoid storing plain text user login information?

**Comment by untitaker** [comment]
Sorry to respond after you made the PR, but I think we could solve this problem and also take care of #532 at the same time: Mention extensions that are for password hash storage and validation.

**Comment by wldtyp** [comment]
Working on this during the pycon sprint!

**Comment by untitaker** [comment]
Thanks, feel free to ask questions here.

**Comment by jeffwidman** [comment]
@wldtyp don't forget to submit your improvements as a pull request
