### ISSUE TITLE
Update docs on Approved Extensions

### ISSUE THREAD

**Issue by rduplain** [pallets/flask#865]
Extension approval docs are out of date:
http://flask.pocoo.org/docs/extensiondev/#approved-extensions

Specifically, now that Flask supports Python3 as of its 0.10 release, extensions in the community should follow. Maintained extensions should support the same Python versions as Flask itself. On that note, I personally do not want to write any library that keeps support for Python 2.6. I prefer Python 2.7 and Python 3.2+.

**Comment by davidism** [comment]
#1220
