### ISSUE TITLE
Allow subdomains to work with no SERVER_NAME

### ISSUE THREAD

**Issue by yannk** [pallets/flask#905]
Would you be open to a patch allowing the use of subdomain routing with no SERVER_NAME pre-configured?

The motivation is to allow multiple domains to match a request, just like it does when SERVER_NAME is None, while still benefiting from the nice subdomain matcher. This is particularly useful in DEV to be able to develop on machine.local but also tunnel the instance to a vpn, and use things like xip.io (which all change the host).

The change would probably be mostly focused on create_url_adapter(). I imagine a configuration variable switching a different logic on for this function: it would look for subdomains and deduce the server_name which is the reverse of what's going on today.
The list of subdomains could come from the configuration I suppose, or better be deduced from the compilation of the routes.

1) What do you think of this idea?
2) If you are opposed to it, what alternative approach do you suggest instead?
3) If you are not opposed to it, how do you think the implementation should look like?

**Comment by asciifaceman** [comment]
:+1: 

This led to debating dumping blueprints with my partner

**Comment by davidism** [comment]
Subdomain routing requires setting the server name. It sounds like you want "wildcard" subdomains, where some routes don't care what subdomain they come in on. You can probably get this with some variable rules in the subdomain part, or by redirecting the subdomains to a canonical domain at the web server level. I don't think we should add anything to Flask at this time.

Note that #2635 allows setting `SERVER_NAME` without forcing subdomain matching, which may be what you were looking for.
