### ISSUE TITLE
Flask needs a way to announce new versions

### ISSUE THREAD

**Issue by arnuschky** [pallets/flask#908]
I think that flask needs some sort of dedicated channel to announce critical updates (or in general, new versions). 

The reason is that flask grew to a point where there is a lot of activity on the repository and the general mailing list. Listening on the mailing list or "watching" the repository for maintenance-only projects in order to catch new critical updates means siphoning through a lot of messages.

Would setting up something like a separate announce list be possible?

**Comment by jeffwidman** [comment]
The Flask mailing list averages at most 1-2 messages a week right now.

**Comment by jeffwidman** [comment]
Should this be moved to https://github.com/pallets/meta/issues and expanded to create a way for folks to subscribe to announcements about whatever Pallets projects they want updates on??

**Comment by untitaker** [comment]
This is actually fixed with the new blog, where at least major releases are announced.

Please refile against the tracker linked by @jeffwidman if this is not sufficient.
